### ISSUE TITLE
关于action.js里面perform的api问题咨询

### ISSUE THREAD

**Issue by diaojunxian** [alibaba/macaca#100]
想请教达峰的是，perform的api，我在WDA源码里没有看到，可能是我看的不仔细，我不是很理解？
还有`POST /session/:sessionId/execute`在WDA里也没有看到，这里是实现什么样的功能呢？

**Comment by xudafeng** [comment]
@diaojunxian `POST /session/:sessionId/execute` 是进入web才会有的api
