### ISSUE TITLE
win10 环境 macaca doctor 无法列出installed driver list 已安装驱动列

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#101]
win10 环境  已跑通样例脚本。
但是发现
![image](https://cloud.githubusercontent.com/assets/18392901/17470497/6b7852ec-5d6f-11e6-94f7-650eac09f475.png)
macaca doctor 无法列出installed driver list 已安装驱动列。

在我的ubuntu16.04 环境下 或MAC 环境下是正常显示该 installed driver list 已安装驱动列的。
cmd@TR:~$ macaca doctor

  Node.js checklist:
  node env: /opt/nodejs/bin/node
  node version: v4.4.7

  Android checklist:
  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/opt/android-sdk-linux`
  Platforms is set to `/opt/android-sdk-linux/platforms/android-19`
  Android tools is set to `/opt/android-sdk-linux/tools/android`

  Installed driver list:
  android: 1.0.23
  chrome: 1.0.1
  electron: 1.0.7

所以，请修复下在win10环境下的这个 驱动显示bug

**Comment by zenzhu** [comment]
@Archer456 已修复，请更新一下。https://github.com/macacajs/macaca-doctor/pull/7

**Comment by Archer456** [comment]
已修复 谢谢
