### ISSUE TITLE
请问通过定位如何获取web img的src？

### ISSUE THREAD

**Issue by tangoliver** [alibaba/macaca#1010]
请问通过定位如何获取web img的src

**Comment by candialala** [comment]
你好，来信已收到~~我会尽快查收并回复的！
XMU Software 
陈晓娟

**Comment by Jodeee** [comment]
你好，可以通过 getProperty('src') 获取到对应元素相关的属性，具体实现可参考 [API 文档](https://macacajs.github.io/macaca-wd/zh/apis/element/getProperty.html)

**Comment by tangoliver** [comment]
> 你好，可以通过 getProperty('src') 获取到对应元素相关的属性，具体实现可参考 [API 文档](https://macacajs.github.io/macaca-wd/zh/apis/element/getProperty.html)

好的，感谢，问题已解决
