### ISSUE TITLE
关于webdriveragent npm更新问题

### ISSUE THREAD

**Issue by chenchaoyi** [alibaba/macaca#102]
macaca-ios -> xctest-client -> webdriveragent

1) 目前有计划将webdriveragent npm module移到macacajs git org 下吗？
2) 能更新一下macaca-ios下的系列npm吗？如
* https://github.com/macacajs/macaca-ios/blob/master/package.json#L22
* https://github.com/macacajs/xctest-client/blob/master/package.json#L18

3) 有计划直接使用facebook的WebDriverAgent作为webdriveragent下的一个submodule吗？facebook/WebDriverAgent现在开发比较活跃，但看来https://github.com/xudafeng/webdriveragent/tree/master/WebDriverAgent 有一些针对macaca自己的改动，这些改动能提交到facebook/WebDriverAgent里从而以后使用同一版本的WebDriverAgent吗？

现在在试着migrate一些case到macaca上，发现有些locator有bug，但很难定位不知道facebook/WebDriverAgent是否已经有fix。

**Comment by xudafeng** [comment]
@chenchaoyi 目前将fb 的项目保留版权，初步封装了，但是也做了非常大的改动，不准备跟着源仓库版本走，待项目稳定时会开放到macacajs group。

**Comment by xudafeng** [comment]
@chenchaoyi 定位的相关fix请发一下。
