### ISSUE TITLE
如何触发keydown的事件

### ISSUE THREAD

**Issue by xiamidong** [alibaba/macaca#104]
## 如何触发keydown事件

> pc端网页上有个input，监听了keydown事件，需要按下enter事件，macaca应该如何触发这个事件

**Comment by zhuyali** [comment]
如果你现在的功能需求只是要按下enter事件，可以试一下 sendKeys('\uE007')。更多的PUA(Private Use Area)和key详见：https://w3c.github.io/webdriver/webdriver-spec.html#keyboard-actions 中 Character Types

**Comment by xiamidong** [comment]
我试了很多次，sendKeys('\uE007')不行

**Comment by xudafeng** [comment]
测试过 keydown 是可以的，针对chrome和electron的driver可以使用.sendKeys('\uE007')出发enter

**Comment by sachinGirish** [comment]
usage .keys('\uE009' + 'a');   to press cntr + a
