### ISSUE TITLE
How to open a new window in the broswer,and how to active the different window

### ISSUE THREAD

**Issue by xiamidong** [alibaba/macaca#105]
###  How to open a new window in the broswer,and how to active the different window

*  I need to test the communication of the different windows,so I need open a new window to handle the communication,but I can't konw how to do.
* I also need help how to active the different window

**Comment by xudafeng** [comment]
@xiamidong 是PC还是移动端？

**Comment by xiamidong** [comment]
PC

**Comment by xudafeng** [comment]
@xiamidong 可以初始化两个driver，就可以窗口交互测试了

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5096
