### ISSUE TITLE
android真机执行sample的时候报 Error: [contexts()] Error response status: 6,  Selenium error: no such session

### ISSUE THREAD

**Issue by BonnieShi** [alibaba/macaca#106]
执行$ platform=android make test-android
从#5开始开始失败，错误信息如下：
>>   1) macaca mobile sample #5 should go into webview:
     **Error: [contexts()] Error response status: 6,  Selenium error: no such session
  (Driver info: chromedriver=2.20.353124** (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.5 x86_64)
      at exports.newError (node_modules/.1.0.6@macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/.1.0.6@macaca-wd/wd/lib/callbacks.js:75:19
      at node_modules/.1.0.6@macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/.1.0.6@macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/.2.55.0@request/request.js:368:22)
      at Request.<anonymous> (node_modules/.2.55.0@request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/.2.55.0@request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

  2) macaca mobile sample #6 should go into test:
     Error: [contexts()] Error response status: 6,  Selenium error: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.5 x86_64)
      at exports.newError (node_modules/.1.0.6@macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/.1.0.6@macaca-wd/wd/lib/callbacks.js:75:19
      at node_modules/.1.0.6@macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/.1.0.6@macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/.2.55.0@request/request.js:368:22)
      at Request.<anonymous> (node_modules/.2.55.0@request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/.2.55.0@request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:913:12)

**Comment by xudafeng** [comment]
macaca doctor 看下你环境是什么

**Comment by BonnieShi** [comment]
$ macaca doctor 

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/shilaijing/Documents/work/android-sdk-macosx/`
  Platforms is set to `/Users/shilaijing/Documents/work/android-sdk-macosx/platforms/android-19`
  Android tools is set to `/Users/shilaijing/Documents/work/android-sdk-macosx/tools/android`

  Installed driver list:

  android: 1.0.25
  chrome: 1.0.1

**Comment by BonnieShi** [comment]
完整log：
>> chromedriver starting success.
>> proxy.js:52:14 [master] pid:3357 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body:
>> proxy.js:58:16 [master] pid:3357 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.11.5\"}}}"
>> proxy.js:52:14 [master] pid:3357 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.github.android_app_bootstrap","androidUseRunningApp":true,"androidDeviceSerial":"192.168.56.102:5555"}}}
>> proxy.js:58:16 [master] pid:3357 Got response with status 200: {"sessionId":"c85302119967218397b1c4523a2b7602","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=M...
>> chromedriver ready with: {"sessionId":null,"status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.5 x86_64)"}}
>> proxy.js:52:14 [master] pid:3357 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/c85302119967218397b1c4523a2b7602/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:3357 Got response with status 200: {"sessionId":"c85302119967218397b1c4523a2b7602","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X...
>> responseHandler.js:50:12 [master] pid:3357 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.5 x86_64)
>> responseHandler.js:56:14 [master] pid:3357 NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.5 x86_64)
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-android/lib/helper.js:68:11)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/macaca-android/lib/macaca-android.js:209:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:65:19)
    at process._tickCallback (node.js:369:9)
>> responseHandler.js:72:14 [master] pid:3357 Send Bad HTTP Respone to Client: {"sessionId":"d6db4b9d-aa1e-42ea-95f1-0f4b8bc970f1","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.5 x86_64)"}}
>>
>>     1) #5 should go into webview

**Comment by BonnieShi** [comment]
andy update?

**Comment by xudafeng** [comment]
#90

**Comment by xudafeng** [comment]
#91
