### ISSUE TITLE
针对macaca python版预研咨询

### ISSUE THREAD

**Issue by zhoujinjian** [alibaba/macaca#107]
最近两天准备对macaca python版预研下，目前网上开放出来可查询的资料太少，@zenzhu，是否提供一些帮助或者一些python版的产出文档参考一下。

* **Macaca Version**:
1.1.0
* **Macaca Doctor**:

* **Platform**:
window 7

**Comment by zenzhu** [comment]
@zhoujinjian [API 文档](https://macacajs.github.io/wd.py/) 已有，sample 下周会给出。

**Comment by zhoujinjian** [comment]
@zenzhu , github下，https://github.com/macacajs/wd.py下，将文件download下来，通过python setup.py install安装wd模块，此时,macaca python需要的依赖环境是否安装完毕了？

**Comment by zenzhu** [comment]
@zhoujinjian 已经发布了，你可以直接 
```pip install wd``` 即可。

**Comment by zhoujinjian** [comment]
@zenzhu ，嗯，已经安装OK，今天再调试一个功能，能否今天先提供一个python版的demo我参考一下，看一下基本流程是如何串起来的。

**Comment by zenzhu** [comment]
@zhoujinjian 顺手写了一个简单的 [Sample](https://gist.github.com/zenzhu/ff902f06a0f6f55b2eb37ab05ae3d063)，你先启动 macaca server，然后运行该脚本即可。如果写成测试用例的话，用原生的 unittest 或者 pytest，nose 组织一下都可以。

**Comment by zhoujinjian** [comment]
@zenzhu ,嗯，非常感谢！
