### ISSUE TITLE
macaca python client与server通讯连接机制？

### ISSUE THREAD

**Issue by zhoujinjian** [alibaba/macaca#109]
@zenzhu ,咨询两个问题：
1、macaca python版demo示例这周什么时候会放出来呢？
2、我看你之前写了一个简单的demo示例里中，在客户端代码中，并没有指出客户端连接服务器remote_Url地址，端口这些信息，那么客户端连接server的简单实现机制是？

**Comment by zenzhu** [comment]
@zhoujinjian 目前这个 URL 默认是 http://127.0.0.1:3456/wd/hub, 这也是 macaca 服务端的默认设置，如果需要改变，可以传入对应的服务器地址的字符串或者一个字典。
```
driver = WebDriver(desired_caps, 'https://macaca:123456@127.0.0.1:5678/wd/hub')
or
driver = WebDriver(desired_caps, {
    'protocol': 'https',
    'hostname': '127.0.0.1',
    'port': 5678,
    'username': 'macaca',
    'password': '123456',
    'path': '/wd/hub'
})
```
上述两者是等效的。

**Comment by zhoujinjian** [comment]
@zenzhu ，OK，那我知道了，即如果未指定就会去连接默认的URL，反之如果指定，则按照指定的server url来连
python demo的示例这周什么时候会放出来呢，因为我最近在预研macaca python这块东西。

**Comment by zenzhu** [comment]
@zhoujinjian 本周五前应该能弄完，入门和简单的 Sample 都会陆续放出，Python 的用法和 JS 版本的并没有太大区别，只是 API 和命名方式有所区别。

**Comment by zhoujinjian** [comment]
@zenzhu ，能否现在贴一个python版，mobile的demo给我参考一下

**Comment by zenzhu** [comment]
@zhoujinjian 对于 mobile 只要改变 desirec_caps 里面的 platformName 就可以了。
安装 macaca
```
npm install macaca macaca-ios macaca-android -g
```

启动 server
```
macaca server
``` 

用例
```
driver = WebDriver({
    'platformName': 'Android'
})

el = driver.element_by_id('login')
el.click()

# 获取当前存在的上下文（native or webview)
ctx = driver.contexts

>>>  print(ctx)
['NATIVE', 'WEBVIEW_1', 'WEBVIEW_2']

# 切换上下文（name 仅供示范）
driver.context = 'WEBVIEW_2'
```

其他的与 PC 并无太大差别。

**Comment by zhoujinjian** [comment]
@zenzhu ，thx !

**Comment by zhoujinjian** [comment]
@zenzhu 
from macaca.webdriver import WebDriver
import time
desired_caps = {
    "platformName": 'Android',
    "package": "xxx",
    "activity":" xxxxx.xxxx.xxx"
}

driver = WebDriver(desired_caps)
driver.init()
time.sleep(3)
el=driver.element_by_name("xx")
el.click()
driver.quit()
print("complete!")

@zenzhu ，这个基本流程有问题吗，macaca服务器会报内部错误：
InternalServerError: Internal Server Error
    at Object.module.exports.throw (C:\nodejs\node-global\node_modules\macaca-cli\node_modules\koa\lib\context.js:91:23)
    at Object.module.exports (C:\nodejs\node-global\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:53:17)
    at throw (native)
    at onRejected (C:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:81:24)
    at process._tickCallback (node.js:369:9)

**Comment by zhoujinjian** [comment]
@zenzhu ，上述mobile基础demo流程组装有问题吗？

**Comment by zenzhu** [comment]
@zhoujinjian 你可以在服务器运行 macaca server --verbose  看详细日志
@xudafeng 安卓是否支持
```
"package": "xxx",
"activity":" xxxxx.xxxx.xxx"
```
这样的写法？

**Comment by xudafeng** [comment]
@zenzhu 支持 sample仓库有示例的

**Comment by zhoujinjian** [comment]
@zenzhu ，
"package": "xxx",
"activity":" xxxxx.xxxx.xxx"
我只是把具体的包名和activity名在贴代码时，用xx来表示，实际运行时，是有真实的名称。

**Comment by zhoujinjian** [comment]
@xudafeng ，sample仓库地址是？

**Comment by zhoujinjian** [comment]
@zenzhu ,
@xudafeng 
python mobile sample仓库示例地址是？

**Comment by xudafeng** [comment]
看文档哦

**Comment by zhoujinjian** [comment]
@xudafeng ，哪里的文档呢， 现在关 于Python macaca除了上次发的API外，其它的没有相应的文档资料吧

**Comment by xudafeng** [comment]
@zhoujinjian https://github.com/macacajs/macaca-test-sample/blob/master/macaca-test/macaca-mobile-sample.test.js#L20 先看js版sample，一样的

**Comment by xudafeng** [comment]
http://macacajs.github.io/macaca/python.html
