### ISSUE TITLE
 [建议]macaca执行完，生成测试报告(html,xml) ，方便集成到jenkins里

### ISSUE THREAD

**Issue by zhangzhao4444** [alibaba/macaca#110]
* **Macaca Version**:

* **Macaca Doctor**:

* **Platform**:

**Comment by xudafeng** [comment]
@zhangzhao4444 jenkins里你目前配置的命令是什么?

**Comment by zhangzhao4444** [comment]
脚本在github上

**Comment by zhangzhao4444** [comment]
shell里配的 
npm install
platform=android macaca run --verbose

**Comment by zhangzhao4444** [comment]
报告可以用html就行 。有总case的passfail表。点某个case跳到其详细的html。 
详细的里每一步可以：
1用should.js 断言pass或fail
2 调takeScreenshot() 截图加到html里
3 可支持自定义输出log

**Comment by xudafeng** [comment]
macaca -o 可以导出报告的

**Comment by adfghzhang** [comment]
建议报告功能有这些：
运行步骤、日志、截图、断言同步记录并能生产html或其他可直观展示的报告

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/165
