### ISSUE TITLE
请问IOS真机运行的时候，是否必须对WebDriverAgent签名，如何操作能给个步骤么

### ISSUE THREAD

**Issue by BonnieShi** [alibaba/macaca#111]
>> xctest-client.js:155:14 [master] pid:9087 2016-08-15 17:01:48.261 xcodebuild[9247:360430] [MT] IDETestOperationsObserverDebug: (6749146A-55BB-44AE-AB32-F97B8590B854) Beginning test session 6749146A-55BB-44AE-AB32-F97B8590B854 with Xcode 7D1014 on target <DVTiOSDevice: 0x7f9ea2e9a5f0> {
		deviceSerialNumber:         DX3P4UY8FMLD
		identifier:                 df10fc93e4dee0eff701ed8bda1444f6bbb18099
		deviceClass:                iPhone
		deviceName:                 test
		deviceIdentifier:           df10fc93e4dee0eff701ed8bda1444f6bbb18099
		productVersion:             9.3.2
		buildVersion:               13F69
		deviceSoftwareVersion:      9.3.2 (13F69)
		deviceArchitecture:         armv7f
		deviceTotalCapacity:        5640351744
		deviceAvailableCapacity:    3299885056
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7f9ea2e69330 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.2 (13F69))
2016-08-15 17:01:48.261 xcodebuild[9247:360439]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/shilaijing/Library/Developer/Xcode/DerivedData/WebDriverAgent-drmzhetqodgefhaqpyureuezairh/Logs/Test/6338D307-5C62-4578-BDBB-212C792CDE80/Session-2016-08-15_17:01:48-MxYm9A.log

>> xctest-client.js:155:14 [master] pid:9087
Testing failed:

>> xctest-client.js:155:14 [master] pid:9087 	No provisioning profiles found: No non–expired provisioning profiles were found.
** TEST FAILED **

**Comment by BonnieShi** [comment]
最新进展：已经对webdriveragent签名并且安装到手机上，但是运行仍然报错
shilaijingdeMacBook-Pro:macaca-code shilaijing$ macaca run --verbose>> index.js:17:12 [master] pid:9931 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.60.213',
  host: 'shilaijingdeMacBook-Pro.local',
  loaded_time: '2016-08-16 16:06:26' }
>> middlewares.js:17:10 [master] pid:9931 base middlewares attached
>> router.js:108:10 [master] pid:9931 router set
>> webdriver sdk launched
>>

>>

>>   macaca ios sample

>> responseHandler.js:11:12 [master] pid:9931 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"deviceName":"陈可的 iPhone","platformName":"iOS","udid":"df10fc93e4dee0eff701ed8bda1444f6bbb18099","bundleId":"com.tqmall.crm "}}
>> session.js:47:10 [master] pid:9931 Creating session, sessionId: 09f54bfe-d7f9-4eba-9b1e-05a95389b1db.
>> xctest-client.js:43:14 [master] pid:9931 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:130:10 [master] pid:9931 {
	"bundleId": "com.tqmall.crm ",
	"platformName": "iOS"
}
>> xctest-client.js:182:12 [master] pid:9931 xcode version: 7.3.1
>> xctest-client.js:155:14 [master] pid:9931 2016-08-16 16:06:32.712 xcodebuild[9938:246370] [MT] IDETestOperationsObserverDebug: (38C89DFC-3CC3-409E-8CD7-8F2FFE265E2E) Beginning test session 38C89DFC-3CC3-409E-8CD7-8F2FFE265E2E with Xcode 7D1014 on target <DVTiOSDevice: 0x7f872c86e740> {
		deviceSerialNumber:         DX3P4UY8FMLD
		identifier:                 df10fc93e4dee0eff701ed8bda1444f6bbb18099
		deviceClass:                iPhone
		deviceName:                 陈可的 iPhone
		deviceIdentifier:           df10fc93e4dee0eff701ed8bda1444f6bbb18099
		productVersion:             9.3.4
		buildVersion:               13G35
		deviceSoftwareVersion:      9.3.4 (13G35)
		deviceArchitecture:         armv7f
		deviceTotalCapacity:        5640261632
		deviceAvailableCapacity:    3416342528
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7f872c385890 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.4 (13G35))
2016-08-16 16:06:32.712 xcodebuild[9938:246382]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/shilaijing/Library/Developer/Xcode/DerivedData/WebDriverAgent-drmzhetqodgefhaqpyureuezairh/Logs/Test/31002C8D-9B0A-42AD-97E5-B77BCA603819/Session-2016-08-16_16:06:32-1qQ7UI.log

>> xctest-client.js:155:14 [master] pid:9931 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xw/t5glt5nn0gx3b0hzzqknpmkr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/6aa2168fd7d17596c2c814af2a560223/df10fc93e4dee0eff701ed8bda1444f6bbb18099/ManifestCache.plist

>> xctest-client.js:155:14 [master] pid:9931 ** TEST FAILED **


>> xctest-client.js:163:14 [master] pid:9931 xctest client exit with code: 65, signal: null

**Comment by xudafeng** [comment]
@supern 签名这块你熟悉吗？

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/135

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5804
