### ISSUE TITLE
 For 'N' SDK Preview, attribute minSdkVersion in AndroidManifest.xml must be 'N' ，这个问题怎么解决

### ISSUE THREAD

**Issue by ZhuDeAiFeiErTieTa** [alibaba/macaca#113]
1、翻墙安装macaca android时，反复出现上述问题，JDK版本为1.8.0_101，附提示日志，该怎么解决，请大神们指点，谢谢！！
Error: build failed
    at ChildProcess.<anonymous> (D:\nodejs\node-global\node_modules\macaca-android\node_modules\ant-build\lib\ant-build.js:98:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
D:\nodejs\node-global
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node-global\\node_modules\\npm\\bin\\npm-cli.js" "i" "macaca-android" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! unlock-apk@0.1.15 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unlock-apk@0.1.15 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the unlock-apk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unlock-apk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls unlock-apk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
npm ERR! code 1

**Comment by xudafeng** [comment]
@ZhuDeAiFeiErTieTa http://macacajs.github.io/macaca/faq.html

**Comment by ZhuDeAiFeiErTieTa** [comment]
@xudafeng 查看了你给的地址，虽然知道是因为SDK设置导致的问题，还是没搞懂该怎么弄，能不能具体讲解下

**Comment by ZhuDeAiFeiErTieTa** [comment]
@xudafeng  这是没有翻墙，执行npm i macaca-android -g后打印的错误信息，麻烦帮忙看下怎么解决
 BUILD FAILED
D:\adt-bundle-windows-x86_64-20140702\adt-bundle-windows-x86_64-20140702\sdk\tools\ant\build.xml:538: For 'N' SDK Pr
eview, attribute minSdkVersion in AndroidManifest.xml must be 'N' (current: )

Total time: 0 seconds

[Error: build failed]
D:\nodejs\node-global\node_modules\macaca-android\node_modules\unlock-apk\script\build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (D:\nodejs\node-global\node_modules\macaca-android\node_modules\ant-build\lib\ant-bu
ild.js:98:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
D:\nodejs\node-global
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node-global\\node_modules\\npm\\bin\\npm-cli.js" "i" "macaca-andro
id" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! unlock-apk@0.1.15 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unlock-apk@0.1.15 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the unlock-apk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unlock-apk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls unlock-apk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
npm ERR! code 1

**Comment by xudafeng** [comment]
cd $ANDROID_HOME && cd platforms 

删除18-23 之外的目录

**Comment by ZhuDeAiFeiErTieTa** [comment]
@xudafeng 能不能解释下原因，是不是因为macaca暂时不支持最新的ANDROID SDK

**Comment by xudafeng** [comment]
@ZhuDeAiFeiErTieTa 预览版sdk不稳定，不建议使用
