### ISSUE TITLE
关于macaca python usage相关问题

### ISSUE THREAD

**Issue by zhoujinjian** [alibaba/macaca#116]
@zenzhu @xudafeng 

**issue1: PythonAPI 官网文档中，http://macacajs.github.io/macaca/python.html
示例模块导入错误：**

import unittest
from macaca import WebDriver

应改为:
import unittest
from macaca.webdriver import WebDriver

**issue2: 在调用driver.quit方法时，为何不直接在退出浏览器驱动前，同时引用driver.close()方法,不然代码执行完成后，被测窗口还存在，岂不是挺怪的，或者还要单独调用一次driver.close()，有点多余了，而且原生的selenium webdriver调用quit方法时，会释放驱动的同时，关闭被驱动程序所打开的窗口程序吧。

issue3: 如果通过在用例中引入测试框架如unittest，最终调用unittest.main()执行时，会提示
AttributeError: 'WebDriver' object has no attribute 'send_keys'错误。而如果直接硬代码书写的话调用正常，请问是什么问题的，查看源码发现send_keys等方法是放在webelement.py模块当中，那难道还要导入webelements模块？但为何直接硬编码不引入unittest的话又可以？

相关代码如下：

`#coding=utf-8
import unittest
import time
from macaca.webdriver import WebDriver

desired_caps = {
    'platformName': 'Desktop', # iOS, Android, Desktop
    'browserName': 'Chrome'    # Chrome, Electron
    #'app': 'path/to/app'       # Only for mobile
}

server_url = {
    'hostname': '127.0.0.1',
    'port': 3456
}

class MacacaTest(unittest.TestCase):
    def setUp(self):
        self.driver = WebDriver(desired_caps, server_url)
        self.driver.init()

    def tearDown(self):
        self.driver.close()
        self.driver.quit()

    def test_search_macaca(self):
        self.driver.set_window_size(1280, 800).get("https://www.baidu.com")
        self.driver.element_by_id("kw")
        self.driver.send_keys("macaca")  
        self.driver.element_by_id("su")
        self.driver.click()
        html = self.driver.source
        self.assertTrue('macaca' in html)

if __name__ == '__main__':
	unittest.main()     #==》调用一：引入unitest框架，此调用会报错

    #调用二：直接硬编码调用，正常：
	# driver = WebDriver(desired_caps,server_url)
	# driver.init()
	# driver.set_window_size(1280, 800).get("https://www.baidu.com")
	# el = driver.element_by_id("kw")
	# el.send_keys("macaca")
	# el = driver.element_by_id("su")
	# el.click()
	# html = driver.source
	# print('Does Macaca exist: ', 'macaca' in html)
	# time.sleep(3)
	# driver.close()
	# driver.quit()`

**Comment by zenzhu** [comment]
#1 是在版本 0.1.1 改的，加入到根模块了，你可能要更新一下 wd。
#2 这是服务端的问题，实际上调用 quit，被测浏览器应该直接退出了，没必要再 close 了。
#3 这是我写错了，driver 上面的方法叫 keys, element 上面的那个叫 send_keys，之后我会更新一下文档和代码。

**Comment by zhoujinjian** [comment]
@zenzhu ,thx
