### ISSUE TITLE
[问题]并行2个手机跑macaca ，配了不同的port ，但仍出现串行运行

### ISSUE THREAD

**Issue by zhangzhao4444** [alibaba/macaca#117]
并行跑2个手机的macaca 

 UDID=xxx MACACA_SERVER_PORT=3457  macaca run -p 3457
UDID=xxx MACACA_SERVER_PORT=3458  macaca run -p 3458

跑得时候发现 会先跑一个 ，另一个卡在socket client ready  
等头一个跑完，第二个会再跑一边instrumentation_status:numtest=1..socket client ready

第二台log 见图 
![macaca](https://cloud.githubusercontent.com/assets/16487430/17723353/09c637cc-646c-11e6-8b05-96609630fc5a.jpg)

**Comment by xudafeng** [comment]
参考 https://testerhome.com/topics/5361

**Comment by xudafeng** [comment]
chromedirver也配置了不同端口吗？

**Comment by zhangzhao4444** [comment]
UDID=xxx MACACA_SERVER_PORT=3457 MACACA_CHROMEDRIVER_PORT=9517 macaca run -p 3457
UDID=xxx MACACA_SERVER_PORT=3458 MACACA_CHROMEDRIVER_PORT=9518 macaca run -p 3458
这个仍有该报错

**Comment by xudafeng** [comment]
@zhangzhao4444 跑文章sample试试呢？
