### ISSUE TITLE
调用截图takeScreenshot API 截图不知道保存到哪里

### ISSUE THREAD

**Issue by ownehe** [alibaba/macaca#118]
在JS脚本中，调用了takeScreenshot API，用例执行成功，没有报错，查看日志也都正常，但是找遍所有目录，并没有发现截图，查看日志和API说明，也并没有截图保存路径说明。

期望：能在用例目录下生产一个目录专门用来保存用例截图。以便查看核对测试结果。

* **Macaca Version**:   1.0.36
* **Macaca Doctor**:  
 node env: D:\node\node.exe
 node version: v4.4.7
 Android checklist:
 JAVA version is `1.8.0_73`
 JAVA_HOME is set to `D:\jdk`
 ANDROID_HOME is set to `D:\Androidsdk`
 Platforms is set to `D:\Androidsdk\platforms\android-23`
 Android tools is set to `D:\Androidsdk\tools\android.bat`
 ANT_HOME is set to `D:\apache-ant-1.9.7`

* **Platform**: windows 8

**Comment by ownehe** [comment]
截图问题

**Comment by zenzhu** [comment]
takeScreenshot 返回的是 base64 字符串，要保存本地的话 使用 saveScreenshot('path/to/save')

**Comment by xudafeng** [comment]
@zenzhu 很多人问这个问题，我们faq看下有没说明白的地方吗？

**Comment by ownehe** [comment]
在http://macacajs.github.io/macaca-wd/api/  api文档中，并没有saveScreenshot这个接口。同时，takeScreenshot 返回的字符串，也不知返回在哪儿。

**Comment by zenzhu** [comment]
@ownehe 谢谢反馈，马上在文档中添加，takeScreenshot 返回的是 promise 对象。
```
driver
  .takeScreenshot()
  .then(base64 => console.log(base64))
```
这样的。

**Comment by Archer456** [comment]
@zenzhu 
https://github.com/macacajs/wd.java   这里也没有  .saveScreenshot（）  导入的项目代码里也没有

**Comment by xudafeng** [comment]
@Archer456 https://macacajs.github.io/wd.java/doc/ 有takeScreenshot

**Comment by xudafeng** [comment]
http://macacajs.github.io/macaca/faq.html
