### ISSUE TITLE
[问题]多台手机同时跑时，偶见在socket client ready后 返回this socket has been ended by the other party

### ISSUE THREAD

**Issue by zhangzhao4444** [alibaba/macaca#120]
ubuntu14.04
在同一机器上并行跑4台手机
偶见。部分手机socket连接报错
![macaca socket fail](https://cloud.githubusercontent.com/assets/16487430/17734212/6d4543e2-64ad-11e6-8d63-4954ee10560d.jpg)

**Comment by zhangzhao4444** [comment]
https://github.com/brianc/node-postgres/issues/725

**Comment by xudafeng** [comment]
@zhangzhao4444 需要指定不同端口 https://testerhome.com/topics/5361

**Comment by zhangzhao4444** [comment]
指定的是不同的端口
