### ISSUE TITLE
录制工具支持计划

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#123]
-  在[app-inspector](https://github.com/macacajs/app-inspector)基础上提供录制功能
- 支持iOS和Android两个平台
- PC端使用 [uirecorder](https://github.com/alibaba/uirecorder) 现有功能
- 生成语言模板（Java，JS，Py）三种模板待讨论，API遵从Webdriver风格，包依赖可以暂不支持

**Comment by xudafeng** [comment]
@yaniswang @supern @lihuazhang

**Comment by xudafeng** [comment]
https://github.com/alibaba/uirecorder/issues/9

**Comment by ZhuDeAiFeiErTieTa** [comment]
@xudafeng 能不能把xpath集成到app-inspector里面

**Comment by xudafeng** [comment]
@ZhuDeAiFeiErTieTa @meowtec会支持xpath的 https://github.com/macacajs/app-inspector/issues/6

**Comment by xudafeng** [comment]
@yaniswang 已经支持xpath  https://macacajs.github.io/app-inspector/cn/

**Comment by CodeToSurvive1** [comment]
@xudafeng 能问下
1.在app-inspector基础上提供录制功能
大约能在什么时候发布吗？

**Comment by xudafeng** [comment]
@yaniswang 正在开发，估计快了

**Comment by yaniswang** [comment]
开发中，目前已经接近尾声~

**Comment by xudafeng** [comment]
beta版已经发布，后续动态移步官网 https://macacajs.github.io/macaca/recorder.html
