### ISSUE TITLE
APP上运行脚本时，在一个页面执行case成功，但是跳转到另一个页面，没有执行case，请问下是什么原因

### ISSUE THREAD

**Issue by ZhuDeAiFeiErTieTa** [alibaba/macaca#124]
1、APP上运行脚本时，在一个页面执行case成功，但是跳转到另一个页面，没有执行case，请问下是什么原因，错误提示如下：
>> responseHandler.js:43:14 [master] pid:16212 Send HTTP Respone to Client: {"sessionId":"9be5d8e1-3f67-43ea-a584-4f3865d49e3b","status":0,"value":"{\"ELEMENT\":\"5\"}"}
>> responseHandler.js:11:12 [master] pid:16212 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/9be5d8e1-3f67-43ea-a584-4f3865d49e3b/element/5/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"5"}}

return: {"data":true,"success":true}

>> responseHandler.js:43:14 [master] pid:16212 Send HTTP Respone to Client: {"sessionId":"9be5d8e1-3f67-43ea-a584-4f3865d49e3b","status":0,"value":"true"}
>>
>>     √ #2 输入账号/密码,登录 (30840ms)

>> responseHandler.js:11:12 [master] pid:16212 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/9be5d8e1-3f67-43ea-a584-4f3865d49e3b/click, jsonBody: {"button":"com.zhenai.android:id/common_title_operat_button"}
>> responseHandler.js:50:12 [master] pid:16212 Send Error Respone to Client: TypeError: Cannot read property 'xoffset' of null
>> responseHandler.js:56:14 [master] pid:16212 TypeError: Cannot read property 'xoffset' of null
    at Android.controllers.click (D:\nodejs\node-global\node_modules\macaca-android\lib\controllers.js:50:58)
    at next (native)
    at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:65:19)
    at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
    at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:118:63)
    at next (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:99:29)
    at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:69:7)
    at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
    at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)

  TypeError: Cannot read property 'xoffset' of null
      at Android.controllers.click (D:\nodejs\node-global\node_modules\macaca-android\lib\controllers.js:50:58)
      at next (native)
      at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:65:19)
      at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
      at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)
      at Object.toPromise (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:118:63)
      at next (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:99:29)
      at onFulfilled (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:69:7)
      at D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:54:5
      at Object.co (D:\nodejs\node-global\node_modules\macaca-cli\node_modules\co\index.js:50:10)

>>
>>     1) #3 进入推荐页

>> responseHandler.js:11:12 [master] pid:16212 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/9be5d8e1-3f67-43ea-a584-4f3865d49e3b/element, jsonBody: {"using":"id","value":"com.zhenai.android:id/zhenai_more_Layout"}
recive: {"cmd":"find","args":{"strategy":"id","selector":"com.zhenai.android:id/zhenai_more_Layout","multiple":false}}

**Comment by xudafeng** [comment]
用例贴一下

TypeError: Cannot read property 'xoffset' of null

**Comment by ZhuDeAiFeiErTieTa** [comment]
@xudafeng  
it('#2 输入账号/密码,登录', function() {
    return driver
	  .elementById('com.zhenai.android:id/imageView')
	  .click()
	  .sleep(1000)
      .elementById('com.zhenai.android:id/account_input')
	  .clear()
      .sendKeys('95221023')
      .sleep(1000)
	  .elementById('com.zhenai.android:id/imageView2')
	  .click()
	  .sleep(1000)
	  .elementById('com.zhenai.android:id/password_input')
	  .clear()
	  .sendKeys('111111')
	  .sleep(1000)
	  .elementById('com.zhenai.android:id/login_button')
	  .click()
	  .sleep(1000);
});

  it('#3 进入推荐页', function() {
    return driver
    .click('com.zhenai.android:id/common_title_operat_button')
	  .sleep(1000);
  });

**Comment by xudafeng** [comment]
TypeError: Cannot read property 'xoffset' of null 这个是调用了什么方法？

**Comment by ZhuDeAiFeiErTieTa** [comment]
@xudafeng 这是整个脚本，都没有xoffset这个属性值
'use strict';

var path = require('path');//引用path 模块
var _ = require('macaca-utils');
var xml2map = require('xml2map');

var platform = process.env.platform || 'Android';
platform = platform.toLowerCase();

var iOSOpts = {
  platformVersion: '9.3',
  deviceName: 'iPhone 5s',
  platformName: 'iOS',
  app: path.join(__dirname, '..', 'app', `${platform}-app-bootstrap.zip`)
};

var androidOpts = {
  platformName: 'Android',
  app: path.join(__dirname, '..', 'app', `demo.apk`)
};

var wd = require('webdriver-client')(_.merge({}, platform === 'ios' ? iOSOpts : androidOpts));

// override back for ios
wd.addPromiseChainMethod('customback', function() {
  if (platform === 'ios') {
    return this;
  }

  return this
    .back();
});

describe('zhenai mobile sample', function() {
  this.timeout(5 * 60 * 1000); // mocha 设置超时时间

  var driver = wd.initPromiseChain(); // 初始化 webdriver

  driver.configureHttp({
    timeout: 600000
  });

  before(function() { // 所有测试用例的统一前置动作
    return driver
      .initDriver();
  });

  after(function() { // 所有测试用例的统一后置动作
    return driver
      .sleep(1000)
      .quit();
  });

it('#2 输入账号/密码,登录', function() {
    return driver
	  .elementById('com.zhenai.android:id/imageView')
	  .click()
	  .sleep(1000)
      .elementById('com.zhenai.android:id/account_input')
	  .clear()
      .sendKeys('95221023')
      .sleep(1000)
	  .elementById('com.zhenai.android:id/imageView2')
	  .click()
	  .sleep(1000)
	  .elementById('com.zhenai.android:id/password_input')
	  .clear()
	  .sendKeys('111111')
	  .sleep(1000)
	  .elementById('com.zhenai.android:id/login_button')
	  .click()
	  .sleep(1000);
});

  it('#3 进入推荐页', function() {
    return driver
    .click('com.zhenai.android:id/common_title_operat_button')
	  .sleep(1000);
  });

  it('#4 退出', function() {
    return driver
    .elementById('com.zhenai.android:id/zhenai_more_Layout')
	  .click()
    .sleep(5000)

    .elementById('com.zhenai.android:id/common_title_operat_imageButton')
    .click()
    .sleep(5000)

    .elementById('com.zhenai.android:id/listitemlinearlayout_setting_sign_out')
    .click()
    .sleep(5000);

  });

});

**Comment by ZhuDeAiFeiErTieTa** [comment]
@xudafeng 这是我的package.json文件
{
  "name": "macaca-test-sample",
  "version": "1.0.10",
  "description": "macaca-test-sample",
  "keywords": [
    "macaca",
    "sample"
  ],
  "repository": {
    "type": "git",
    "url": "git://github.com/macacajs/macaca-test-sample.git"
  },
  "dependencies": {
    "macaca-utils": "^0.1.8"
  },
  "devDependencies": {
    "jshint": "*",
    "macaca-cli": "^1.1.0",
    "pre-commit": "1.1.1",
    "webdriver-client": "~1.0.0",
    "xml2map": "^1.0.2"
  },
  "scripts": {
    "test": "make test-pc",
    "jshint": "make jshint"
  },
  "pre-commit": [
    "jshint"
  ],
  "license": "MIT"
}
