### ISSUE TITLE
Android用xpath定位的时候提示 Not JSON response

### ISSUE THREAD

**Issue by BonnieShi** [alibaba/macaca#125]
![image](https://cloud.githubusercontent.com/assets/20982752/17879174/502d5032-6922-11e6-8413-7539df050969.png)
我的页面上有多个android.widget.RelativeLayout的控件，现在我想通过xpath来定位，总是报Not Json response的错误，换成ClassName定位则没有问题，请问现在Android对Xpath已经支持了么
xpath如下：
![image](https://cloud.githubusercontent.com/assets/20982752/17879188/7c613b0a-6922-11e6-8098-c5c8980917f5.png)

**Comment by ZhuDeAiFeiErTieTa** [comment]
目前还不支持

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/36

**Comment by xudafeng** [comment]
@kobe990 正在开发中

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5888
