### ISSUE TITLE
请问macaca python包在哪里找？

### ISSUE THREAD

**Issue by gaye746560359** [alibaba/macaca#126]
已经下载好所有驱动和配置好了环境:
![image](https://cloud.githubusercontent.com/assets/3060035/17885116/587b8142-694e-11e6-97d6-7663fcd95e1a.png)

但是在IDE中写脚本时，无法import
![image](https://cloud.githubusercontent.com/assets/3060035/17885149/7b4a66c0-694e-11e6-8f40-9e9e776a185c.png)

请问macaca python包在哪里找？

**Comment by zenzhu** [comment]
你更新一下到 0.1.1 版本就可以了。

**Comment by gaye746560359** [comment]
@zenzhu 能说具体点吗？那个东西更新到0.1.1版本？另外，我目前的做法是下载了WD源码编译了，放在我的工程目录下引用的。

**Comment by zenzhu** [comment]
@gaye746560359 那就拉 master 分支上的最新代码编译下就可以了
