### ISSUE TITLE
能否增加类似selenium中的By

### ISSUE THREAD

**Issue by caizhenxing** [alibaba/macaca#127]
* **Macaca Version**:1.0.0

* **Operate System**: mac

* ***programming Language*: java
之前我用appium时，封装过一个这样的方法，我传一个locator，不用关心它到底是xpath还是id，name，目前macaca java版，貌似必须得指定这个locator具体是id、name还是xpath，这样会写很多重复的代码，感觉不是很方便
	public By getBy(String locator) {
		if (locator.startsWith("//") || locator.startsWith("(")) {
			return By.xpath(locator);
		} else {
			return new ByIdOrName(locator);
		}
	}

**Comment by xudafeng** [comment]
@caizhenxing 为了与JS和Py的api命名一致，是时候丢弃上一代的习惯了
