### ISSUE TITLE
pipe error: 109

### ISSUE THREAD

**Issue by gaye746560359** [alibaba/macaca#128]
![image](https://cloud.githubusercontent.com/assets/3060035/17887625/e58de9b6-6959-11e6-9676-fa31873008d7.png)
运行过程中出现上述错误提示，是什么问题？

python脚本在IDE中貌似掉不出某些方法，但是可以用。什么情况？
![image](https://cloud.githubusercontent.com/assets/3060035/17887749/6d524ce8-695a-11e6-933e-4c338f16aa20.png)
@xudafeng

**Comment by Archer456** [comment]
@gaye746560359   你用的是webstorm吧 .出来的是mocha的API提示.
以下是我webstorm 研究nodejs版本macaca.  语法提示. 你借鉴参考下看能弄出来不.
摸清webstorm 是在此处添加语法提示插件。
但是在此处搜索macaca发现该地址并未提供语法插件支持，
直接去https://github.com/DefinitelyTyped/DefinitelyTyped也搜不到macaca 到是搜到了mocha 和webdriverio 。
并且我们看到，mocha支持的after 框架语法，找到了语法提示文件 ***.mocha.d.ts.
![image](https://cloud.githubusercontent.com/assets/18392901/17959431/f057e944-6ad2-11e6-998b-363efa587ef4.png)
