### ISSUE TITLE
文档添加desiredCapabilities配置说明

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#132]
- [ ] Android 端提供reuse功能

desiredCapabilities 参数说明一直缺失，guide需要添加PC平台和移动平台的入参说明

http://macacajs.github.io/macaca/getting-started.html

**Comment by xudafeng** [comment]
reuse 的也可以放出来使用了

**Comment by xudafeng** [comment]
@zenzhu Android 也需要提供reuse了

https://github.com/macacajs/macaca-adb/issues/13

**Comment by xudafeng** [comment]
https://macacajs.github.io/macaca/desired-caps.html

**Comment by xudafeng** [comment]
@kobe990 Android 也需要提供reuse了

https://github.com/macacajs/macaca-adb/issues/13

**Comment by xudafeng** [comment]
https://macacajs.github.io/macaca/desired-caps.html

**Comment by tangzhenquan** [comment]
http://macacajs.github.io/macaca/getting-started.html
https://macacajs.github.io/macaca/desired-caps.html
这些地址都失效了，请问哪里可以找到desiredCapabilities的详细说明
