### ISSUE TITLE
ubuntu16.04环境下安装chrome驱动失败

### ISSUE THREAD

**Issue by Msxie** [alibaba/macaca#133]
* **Macaca Version**:1.1.0

* **Macaca Doctor**:
Node.js checklist:

  node env: /opt/software/nodejs/bin/node
  node version: v4.4.7；npm 3.8.7

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/opt/software/java/jdk1.8.0_101`
  ANDROID_HOME is set to `/opt/software/android-sdk-linux`
  Platforms is set to `/opt/software/android-sdk-linux/platforms/android-23`
  Android tools is set to `/opt/software/android-sdk-linux/tools/android`

  Installed driver list:

  electron: 1.1.2

* **Operate System**:
ubuntu 16.04（Linux VirtualBox 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux）
* ***programming Language*:

module.js:327
    throw err;
    ^

Error: Cannot find module '/bin/bin/macaca-chromedriver'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

无法安装chrome驱动，npm i macaca-chrome -g，
/opt/software/nodejs/lib/node_modules/macaca-chrome/node_modules/jszip/lib/zipEntries.js:152
                throw new Error("Corrupted zip : can't find end of central directory");
                ^

Error: Corrupted zip : can't find end of central directory
    at Object.ZipEntries.readEndOfCentral (/opt/software/nodejs/lib/node_modules/macaca-chrome/node_modules/jszip/lib/zipEntries.js:152:23)

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5509
