### ISSUE TITLE
macaca run之后的提醒

### ISSUE THREAD

**Issue by mercynoo** [alibaba/macaca#134]
* **Macaca Version**:1.0.2

* **Macaca Doctor**:

* **Operate System**:osx 10.11.6

* ***programming Language*:python

在输入macaca run之后的提示：
>> webdriver sdk launched
>> /usr/local/lib/node_modules/macaca-cli/node_modules/mocha/lib/utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'macaca-test'

完全按照文档提示操作安装的，请问该怎么解决

**Comment by xudafeng** [comment]
@mercynoo 根目录运行的吗？

**Comment by mercynoo** [comment]
/User/{username}  此路径下

**Comment by xudafeng** [comment]
@mercynoo 项目目录下运行啊

**Comment by xudafeng** [comment]
https://travis-ci.org/macacajs/macaca-test-sample/builds/154411527
