### ISSUE TITLE
xctest client proxy error with: Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by caizhenxing** [alibaba/macaca#137]
* **Macaca Version**: 1.1.0

* **Operate System**: mac os

* ***programming Language*: java

@xudafeng 请教个问题，我跑ios模拟器对应的IP是：
proxy.js:54:14 [master] pid:13977 Proxy: /session:POST to http://100.16.0.19:8100/session:POST with body
但是我我ios真机却是:
proxy.js:54:14 [master] pid:13977 Proxy: /session:POST to http://192.168.2.14:8100/session:POST with body

100.16.0.19是我本机IP，真机那个IP不知道是怎么来的，导致出现：
proxy.js:58:18 [master] pid:14202 xctest client proxy error with: Error: connect ECONNREFUSED 192.168.2.14:8100

**Comment by xudafeng** [comment]
@caizhenxing 来自你真机设备的ip，wda有usb2 tcp协议转换的

**Comment by xudafeng** [comment]
@caizhenxing 
升级macaca-ios
开启wifi
