### ISSUE TITLE
运行demo 跑完浏览器的案例后，跑移动端案例时出错，求解

### ISSUE THREAD

**Issue by pdhxxj** [alibaba/macaca#14]
>>   macaca desktop sample
>> 
>>   ✓ #0 should go into macaca (9273ms)
>> 
>>   ✓ #1 should works with macaca (8873ms)
>> 
>>   ✓ #2 should go into web (3774ms)
>> 
>>   ✓ #3 should works with web (8682ms)
>> 
>>   macaca mobile sample
>> responseHandler.js:24:12 [master] pid:30813 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","browserName":"chrome","app":"/Users/kasi/Downloads/demo/macaca-test-sample/app/ios-app-bootstrap.zip"}}
>> session.js:22:10 [master] pid:30813 Creating session, sessionId: 932b75c9-9763-4525-8e6b-c22053d5ab57.
>> helper.js:205:12 [master] pid:30813 Unzipping local app form /Users/kasi/Downloads/demo/macaca-test-sample/app/ios-app-bootstrap.zip
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/8g/fzl_x6l92j5418ftsb_8g95w0000gn/T/ios-app-bootstrap.app/Info.plist
>> macaca-ios.js:131:10 [master] pid:30813 Get available devices [{"name":"iPhone 4s","udid":"389C1D16-AE19-4F42-9DA1-C942595CBF5D","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 5","udid":"C14D3EFF-E3A9-4F1D-A719-560B3D123821","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 5s","udid":"20820324-B9C1-47BB-8618-79979AB8028A","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6","udid":"2F05E47C-F841-42CF-9078-6499E5B04CFB","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6 Plus","udid":"CFCECE36-5042-4167-8A7B-9B319BFC11E7","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6s","udid":"18D074B5-F6D4-421B-8213-2D7A7F630FC6","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6s Plus","udid":"7591CC7F-E3FA-4DF0-9D03-79E8FC22EDDB","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad 2","udid":"1508DD5B-6E06-49AF-8E85-1EC02DDBCC9D","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Retina","udid":"F78F69BD-781C-4469-9B3C-D3EE18A0F79A","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Air","udid":"F33E17A1-5DD5-4E28-AA76-50BD373E9893","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Air 2","udid":"60EE0546-E4EF-482B-B5EF-86A3A6DB00FE","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Pro","udid":"A14BCDDE-C7C0-48EA-B32A-E5B2CAE1909A","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"Apple TV 1080p","udid":"345C11EC-17A7-4BDB-8BC5-B3FDB74F4DC7","state":"Shutdown","available":true,"runtime":"tvOS 9.1"},{"name":"Apple Watch - 38mm","udid":"AFC22206-61AF-4A1C-8D75-60C53AE8D078","state":"Shutdown","available":true,"runtime":"watchOS 2.1"},{"name":"Apple Watch - 42mm","udid":"92091FC0-7BD7-481D-BA85-84DFAE0E235B","state":"Shutdown","available":true,"runtime":"watchOS 2.1"}]
>> macaca-ios.js:149:12 [master] pid:30813 Kill simulator failed Error: Command failed: /bin/sh -c killAll Simulator
No matching processes belonging to you were found

>> macaca-ios.js:155:12 [master] pid:30813 Shutdown simulator 20820324-B9C1-47BB-8618-79979AB8028A failed Error: Command failed: /bin/sh -c xcrun simctl shutdown "20820324-B9C1-47BB-8618-79979AB8028A"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to shutdown device in current state: Shutdown

>> responseHandler.js:56:12 [master] pid:30813 Send Error Respone to Client Error: Command failed: /bin/sh -c open -a Simulator --args -CurrentDeviceUDID "20820324-B9C1-47BB-8618-79979AB8028A"
The application /Applications/Cocos/cocos-simulator-bin/ios/Simulator.app cannot be opened because it has an incorrect executable format.

>> responseHandler.js:62:14 [master] pid:30813 Error: Command failed: /bin/sh -c open -a Simulator --args -CurrentDeviceUDID "20820324-B9C1-47BB-8618-79979AB8028A"
The application /Applications/Cocos/cocos-simulator-bin/ios/Simulator.app cannot be opened because it has an incorrect executable format.

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
>> responseHandler.js:81:14 [master] pid:30813 Unexcepted error Error

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-client/node_modules/webdriver-server/lib/server/responseHandler.js:82:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-client/node_modules/co/index.js:81:24)

>> 
>>   1) "before all" hook
>> responseHandler.js:24:12 [master] pid:30813 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:48:14 [master] pid:30813 Send HTTP Respone to Client: {"sessionId":"","status":0}
>> 
>> 
>>   4 passing (35s)
>>   1 failing
>> 
>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","browserName":"chrome","app":"/Users/kasi/Downloads/demo/macaca-test-sample/app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
  Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","browserName":"chrome","app":"app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at endReadableNT (_stream_readable.js:905:12)

>> 
>> Test completed!

**Comment by xudafeng** [comment]
@tsj1107

**Comment by tsj1107** [comment]
看上去有可能是配置有问题，如果设置了`"platformName":"iOS"`，就不存在配置`"browserName":"chrome"`
```
{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","browserName":"chrome","app":"/Users/kasi/Downloads/demo/macaca-test-sample/app/ios-app-bootstrap.zip"}
```

**Comment by pdhxxj** [comment]
demo的配置么

**Comment by tsj1107** [comment]
从日志来看 你改了 macaca-mobile-sample.test.js 里的文件，将里面 `"browserName":"chrome", ` 去掉应该就好了

**Comment by pdhxxj** [comment]
我没有修改那个文件，我替换环境也一样，这个文件本身没有你说的这个字段，但是在macaca-desktop-sample.test.js这里确实存在这个文件，是不是同时运行一个命令导致这个问题来着？

**Comment by xudafeng** [comment]
@ManShow0122

**Comment by tsj1107** [comment]
你是执行的什么命令 @pdhxxj

**Comment by pdhxxj** [comment]
macaca run --server --verbose

**Comment by ManShow0122** [comment]
我也感觉是配置冲突的问题，可以手动简化下配置再跑 macaca run --server --verbose 试试:
```
{
  "platformName":"iOS",
  "platformVersion":"9.3",
  "deviceName":"iPhone 5s",
  "app":"/Users/kasi/Downloads/demo/macaca-test-sample/app/ios-app-bootstrap.zip"
}
```

**Comment by xudafeng** [comment]
@pdhxxj 更新一下例子，重新在项目目录下执行 `npm i` 试试
