### ISSUE TITLE
请问下，怎么实现按键操作

### ISSUE THREAD

**Issue by jiangwenqiang1992** [alibaba/macaca#140]
如按back/home

**Comment by xudafeng** [comment]
哪个平台

**Comment by jiangwenqiang1992** [comment]
安卓、java

**Comment by jiangwenqiang1992** [comment]
@xudafeng  安卓、java

**Comment by xudafeng** [comment]
@jiangwenqiang1992 https://github.com/alibaba/macaca/issues/104

**Comment by jiangwenqiang1992** [comment]
![image](https://cloud.githubusercontent.com/assets/21332433/18123665/7b5e4f56-6fa1-11e6-9837-cbbff58acaab.png)
@xudafeng    还是不行

**Comment by jiangwenqiang1992** [comment]
![image](https://cloud.githubusercontent.com/assets/21332433/18123858/672e811c-6fa2-11e6-95bb-0386399b1365.png)

**Comment by xudafeng** [comment]
@jiangwenqiang1992

直接用
.back()

home使用keys 发送adb按键
