### ISSUE TITLE
macaca-cli version1.1.1 启动macaca server 报错

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#141]
本日31日
ubuntu16.04   64 系统 更新后,启动macaca server --verbose报错
`cmd@TR:~$ macaca server --verbose
/opt/nodejs/lib/node_modules/macaca-cli/bin/macaca-cli-server:12
  .option('-p, --port <d>',     'set port for server (default: ' + options.port + ')')
                                                                   ^

ReferenceError: options is not defined
    at Object.<anonymous> (/opt/nodejs/lib/node_modules/macaca-cli/bin/macaca-cli-server:12:68)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
`

版本情况如下
`cmd@TR:~$ macaca -v

  1.1.1

cmd@TR:~$ macaca doctor

  Node.js checklist:

  node env: /opt/nodejs/bin/node
  node version: v4.4.7

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/opt/android-sdk-linux`
  Platforms is set to `/opt/android-sdk-linux/platforms/android-24`
  Android tools is set to `/opt/android-sdk-linux/tools/android`

  Installed driver list:

  android: 1.0.25
  chrome: 1.0.1
  electron: 1.1.2
`

后换回 npm i macaca-cli@1.1.0 -g    启动恢复正常

**Comment by brunoyang** [comment]
已修复，请更新至 1.1.2，后续会加上单测

**Comment by xudafeng** [comment]
https://glebbahmutov.com/blog/unit-testing-cli-programs/
