### ISSUE TITLE
Any sample projects on how to use asserters functions?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#142]
* **Macaca Version**:

* **Macaca Doctor**:

* **Operate System**:

* ***programming Language*:

**Comment by xudafeng** [comment]
@mpreethi90

- [should.js](https://github.com/macacajs/macaca-test-sample/blob/master/macaca-test/macaca-desktop-sample.test.js#L67) was integrated into Macaca 
- require('assert')
- other assert lib like expect

**Comment by xudafeng** [comment]
@dfguo

**Comment by mpreethi90** [comment]
Thank you for the very quick response 👍
