### ISSUE TITLE
getProperty() does not return visible text of that element. Always return null

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#143]
* **Macaca Version**:

* **Macaca Doctor**:

* **Operate System**:

* ***programming Language*:

**Comment by zenzhu** [comment]
What's your  scene and intention? If you want to get text of the element, you can just use .text().

**Comment by xudafeng** [comment]
@dfguo

**Comment by mpreethi90** [comment]
I use macaca for automating tests for a reactnative project for both iOS and android.
DOM structure is like below-
<view><Button></Button></view>

When I try to retrieve the <Button> element and get its visible text using .text(), it just returns null

**Comment by xudafeng** [comment]
getProperty('size') or getProperty('origin')
