### ISSUE TITLE
A more common method say 'elementByCustomMethod' which encloses difference in retrieving UI elements specific to iOS and android 

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#144]
* **Macaca Version**:

We use Macaca framework for a reactnative project which is for both iOS and android. There are few screens where the element locator strategy differs for iOS and android and I wanted to check if macaca provides any clean approach to do the differentiation like below-

it('Tap on an element in both & andriod', function () {
      .getLoginElement()
      .click()
}
getLoginElement()
{
       if (platform === 'ios') {
return driver
      .elementByName(tutorialPageElements.LoginButton)

}
else
{
return driver
      .elementByXPath("Xpath")

}
}

**Comment by zenzhu** [comment]
I think u should write you own extension method to achieve this.
For example
```js
wd.addPromiseMethod(
  'elementBy',
  function(platform, data) {
    var obj = data[platform];
    var by = obj['by'];
    var value = obj['value'];
    return this.element(by, value);
  }
);

wd.elementBy(platform, {
  ios: { by: 'name', value: tutorialPageElements.LoginButton },
  android: { by: 'xpath', value: Xpath }
}); 
```
