### ISSUE TITLE
Is there any way to stop macaca reset iOS simulator on every macaca run?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#145]
* **Macaca Version**:

* **Macaca Doctor**:

* **Operate System**:

* ***programming Language*:

**Comment by xudafeng** [comment]
reuse http://macacajs.github.io/macaca/desired-caps.html

**Comment by xudafeng** [comment]
debug http://macacajs.github.io/macaca/debugging.html

**Comment by mpreethi90** [comment]
Thank you (Y)
