### ISSUE TITLE
Is there a way to get an element by its text? like elementByText() ??

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#146]
* **Macaca Version**:

* **Macaca Doctor**:

* **Operate System**:

* ***programming Language*:

**Comment by xudafeng** [comment]
byName

**Comment by mpreethi90** [comment]
elementByName works only when I set accessibilityLabel property to the element in most of the cases. Is there anything like findText() in the mobile screen and locate the element?

**Comment by brucejcw** [comment]
[.text](http://macacajs.github.io/macaca-wd/api/#text)
