### ISSUE TITLE
nodejs和java版本  脚本启动命令问题

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#148]
这是 nodejs版本的 
![image](https://cloud.githubusercontent.com/assets/18392901/18125025/3d7921ba-6fa7-11e6-9487-24d93d8e2499.png)

这是java版本的 
![image](https://cloud.githubusercontent.com/assets/18392901/18125032/44642bf0-6fa7-11e6-8f11-f0c0bf84adb3.png)

1.3 java 脚本执行环境

git clone https://github.com/macacajs/macaca-test-sample-java.git

编写好的java测试类脚本,cp入 macaca-test-sample-java/src/test/java/macaca/client/

命令行执行脚本:mvn test 或 mvn test -Dtest=macaca.client.AndroidAcp

﻿

1.4 nodejs 脚本执行环境

git clone https://github.com/macacajs/macaca-test-sample.git

编写好的nodejs脚本,cp入 /macaca-test-sample/macaca-test/

命令行执行脚本:make test 或 macaca run -d android-acp-sample.test.js

问题就是 java 是用 mvn test 的 而 Nodejs 是用 macaca run 的
那么 怎么在java 版本里 用上macaca run 带参数呢 ？

能否 支持java版本的  也可以用  macaca run 来运行脚本
或者 mvn test 可以带macaca run的参数呢?

目的是为了 macaca run  更方便去传递macaca的参数  而实际部署环境又是java版本,而java版本的是mvn test 执行方式 好像用不了macaca run的参数,这就尴尬了.  比如 udid ,apk,port. 都可以运行时参数传进去

**Comment by xudafeng** [comment]
@Archer456 shell搞定就行啊，或者Makefile配置

macaca server --verbose && mvn test

**Comment by Archer456** [comment]
知道了  我得研究下Makefile配置  和 mvn 命令 配置 还有 shell。。。
