### ISSUE TITLE
iOS AlertView弹出后布局变化了，但xpath没有变化不能选中元素(比较急请协助处理)

### ISSUE THREAD

**Issue by sencho** [alibaba/macaca#149]
iOS AlertView弹出后布局变化了，但xpath没有变化不能选中元素(比较急请协助处理)

**Comment by zenzhu** [comment]
是否用了 autoAcceptAlerts 设置？ 目的是要点掉还是做什么，直接 elementByName 应该能取到 Alert 上面的文字啊。

**Comment by sencho** [comment]
app启动时会弹那些地理位置的权限的alertview,是用了acceptAlert()，会自动点，但这里也会有问题，就是要sleep几秒，才可以再往下，要么就会报找不到元素或者
<img width="564" alt="d8746e09-7873-4940-a19c-6aefbc4f34db" src="https://cloud.githubusercontent.com/assets/863912/18153742/0588c48c-7032-11e6-99da-38bea2ee4228.png">

现在主要是之后的流程也会有AlertView弹出，一弹出之后xpath和byName都选不中要选的元素，反而是选中了其它元素，byName和byXPath都会选中同样错误的元素，如果再使用acceptAlert()就是报上面的截图错误。

**Comment by zenzhu** [comment]
选择了 autoAcceptAlerts 的话，以后每个命令前都会执行一遍 acceptAlert()，如果这个弹出非常不确定的话，能不能多试几次acceptAlert(), 只要执行就行了，不要让它抛错。

**Comment by zenzhu** [comment]
选择了 autoAcceptAlerts 的话，以后每个命令前都会执行一遍 acceptAlert()，如果这个弹出非常不确定的话，能不能多试几次acceptAlert(), 只要执行就行了，不要让它抛错。

**Comment by sencho** [comment]
我试过多次执行acceptAlert()，但会报截图那个错误，因为在第一个acceptAlert()时已经会自动点掉alertview,这里的逻辑一定是有问题的。现在问题是：1､alertview弹出之后布局有变化，用什么api都选不中元素，如果用sleep等他自动点掉后再选的话成功几率很低；

**Comment by sencho** [comment]
**问题已定位**
alertView的弹出并没有影响布局，发现wad点中alertView是使用坐标的，所以有诡异的选错元素现象，以为是影响了布局。另因为项目的配置默认autoAcceptAlerts是true,webdriver-client会把所有alertView都点掉，但点掉alertView后的回调时机webdriver-client没有保证，所以之后要再选中元素会有报错。

**解决办法**：
把autoAcceptAlerts设成false，弹出来的alertView使用acceptAlert()点掉。
`
var wd = require('webdriver-client')(_.merge({ autoAcceptAlerts: false}, platform === 'ios' ? iOSOpts : androidOpts));
`

@zenzhu 
**需要处理的问题：**
1､当项目autoAcceptAlerts为true时，如果用户使用了acceptAlert()，那么后续的用例autoAcceptAlerts都为false,保证alertView点掉之后的控制权交还给用户。
2､webdriver-client监听wad的alert/accept接口的response，保证alertView的回调时机
