### ISSUE TITLE
Is there a way to run subset of macaca tests?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#150]
* **Macaca Version**:
  1.1.2

I am writing macaca tests for a react native project. My requirement is like this-

Say I have a test file Login.test.js which has around 5 tests. Now, for each test I have one or many tags like "#smoke","#core".
Now, when I execute macaca run command, I just want to grep the tag name so that all the tests that matches the tag should only execute.
Please help.

**Comment by xudafeng** [comment]
pass env variable to distinguish it?

```
FLOW=smoke macaca run --verbose -d ./test/Login.test.js
```

**Comment by mpreethi90** [comment]
so how do I set "smoke" for certain test cases inside test.js?Please help

**Comment by mpreethi90** [comment]
Any update on this please?

**Comment by xudafeng** [comment]
@mpreethi90 

```javascript
const isSmoke = process.env. FLOW === 'smoke';
```

**Comment by mpreethi90** [comment]
The thing is- I just want to execute only few test cases (**it** cases) described if the flow is smoke. How do I actualy tag for every test case?

**Comment by mpreethi90** [comment]
Is there a grep command as in mocha framework to mark the tests and execute only those from command line?

**Comment by mpreethi90** [comment]
May I know what BDD framework does macaca uses to use styles like describe(),it()?

**Comment by mpreethi90** [comment]
@xudafeng  can you help?

**Comment by brucejcw** [comment]
@mpreethi90 [mochajs](https://mochajs.org/)
