### ISSUE TITLE
elementByXPath() in android throws error: "Not JSON response" for ReactNative project

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#153]
* **Macaca Version**:
1.1.2

PFA xml DOM from  my ReactNative android app. When I try to get an element by using ".elementByXPath('//node[@index="0"]/node[1]/node[@index="0"]/node[@index="0"]/node[1]/node[@index="0"]/node[@index="0"]/node[1]/node[3]/node[@index="0"]/node[@index="0"]/node[@index="0"]/node[1]/node[@index="0"]')", I get error as "Not JSON response".

Please help

[xmlAndroid.zip](https://github.com/alibaba/macaca/files/451655/xmlAndroid.zip)

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/36

**Comment by xudafeng** [comment]
Android Xpath support release at 2016.09.07

**Comment by xudafeng** [comment]
supported

```shell
$cnpm i macaca-android -g
```
