### ISSUE TITLE
elementsByClassName怎样选择其中一个元素进行操作

### ISSUE THREAD

**Issue by sunada** [alibaba/macaca#154]
* **Macaca Version**:
1.1.2

* **Macaca Doctor**:
 Node.js checklist:
 node env: D:\nodejs\node.exe
 node version: v4.5.0
 Android checklist:
 JAVA version is `1.8.0_101`
 JAVA_HOME is set to `D:\Program Files\Java\jdk1.8.0_101`
 ANDROID_HOME is set to `D:\program_setup\android_sdk\sdk`
 Platforms is set to `D:\program_setup\android_sdk\sdk\platforms\android-24`
 Android tools is set to `D:\program_setup\android_sdk\sdk\tools\android.bat`
 ANT_HOME is set to `D:\Program Files (x86)\apache-ant-1.9.4`
 Installed driver list:
 android: 1.0.25

* **Operate System**:
win7

* ***programming Language*:
js

我看api文档里有提供elementsByClassName。文档里只提到返回是一个array。我想取第二个元素进行click()，不知道可以怎么选中？api里木有说明，我自己尝试了几方法，也都没有成功。

**Comment by xudafeng** [comment]
@sunada

JS语言？

```javascript
then(elems => {
  return elems[1];
})
```
