### ISSUE TITLE
怎么卸载macaca,重新安装

### ISSUE THREAD

**Issue by mqlsq** [alibaba/macaca#157]
* **Macaca Version**:
macaca-cli@1.1.2
* **Macaca Doctor**:
执行命令异常
* **Operate System**:
Mac OSX 10.11.6
* **programming Language**:
Objective-C

**Comment by xudafeng** [comment]
log 麻烦贴一下

https://testerhome.com/topics/4359

**Comment by xudafeng** [comment]
npm 重新 install就好
