### ISSUE TITLE
整理faq列表

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#160]
整理github issue和社区评论的高频问题后修改这个文件

https://github.com/macacajs/macacajs.github.io/blob/master/_docs/faq.md

**Comment by xudafeng** [comment]
https://github.com/macacajs/macacajs.github.io/blob/master/_docs/faq.md

**Comment by brucejcw** [comment]
:thumbsup:

**Comment by xudafeng** [comment]
@brucejcw close?
