### ISSUE TITLE
运行macaca例子有两个失败，小白求解答,thanks大神

### ISSUE THREAD

**Issue by wrldeop** [alibaba/macaca#162]
* **Macaca Version**:
1.1.2
* **Macaca Doctor**:
Node.js checklist:

  node env: /Applications/devtools/nodejs/bin/node
  node version: v4.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/agathe/Library/Android/sdk`
  Platforms is set to `/Users/agathe/Library/Android/sdk/platforms/android-24`
  Android tools is set to `/Users/agathe/Library/Android/sdk/tools/android`

  Installed driver list:

  electron: 1.1.2
  ios: 1.0.36
* **Operate System**:
mac
* **programming Language**:
node.js

1) macaca mobile sample "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","browserName":"Safari"})] The environment you requested was unavailable.
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

**Comment by xudafeng** [comment]
make test-ios 试试

**Comment by wrldeop** [comment]
还是报了那两个异常

**Comment by xudafeng** [comment]
iOS 模拟器启动了吗

**Comment by wrldeop** [comment]
启动了

**Comment by xudafeng** [comment]
@wrldeop make test-ios 运行？

**Comment by wrldeop** [comment]
是的

**Comment by xudafeng** [comment]
能把全部log贴下吗

**Comment by wrldeop** [comment]
➜  macaca-test-sample git:(master) make test-ios
macaca doctor

  Node.js checklist:

  node env: /Applications/devtools/nodejs/bin/node
  node version: v4.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/agathe/Library/Android/sdk`
  Platforms is set to `/Users/agathe/Library/Android/sdk/platforms/android-24`
  Android tools is set to `/Users/agathe/Library/Android/sdk/tools/android`

  Installed driver list:

  electron: 1.1.2
  ios: 1.0.36


platform=ios macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js
>> index.js:17:12 [master] pid:33360 webdriver server start with config:
 { port: 3456,
  show: true,
  ip: '192.168.3.62',
  host: 'kanccydeiMac.local',
  loaded_time: '2016-09-07 16:02:12' }
>> middlewares.js:17:10 [master] pid:33360 base middlewares attached
>> router.js:108:10 [master] pid:33360 router set
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:33360 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"/Users/agathe/macaca-test-sample/app/ios-app-bootstrap.zip"}}
>> session.js:47:10 [master] pid:33360 Creating session, sessionId: 9596d65c-ad15-4ded-9c69-da1535fadea1.
>> helper.js:194:12 [master] pid:33360 Unzipping local app form /Users/agathe/macaca-test-sample/app/ios-app-bootstrap.zip
CFBundleIdentifier is xudafeng.ios-app-bootstrap
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/pm/8cswgqs52rg74zfpz0cgfcg80000gp/T/ios-app-bootstrap.app/Info.plist
>> macaca-ios.js:186:10 [master] pid:33360 Get available devices [{"name":"iPhone 4s","udid":"01BA1F4D-98FA-4B4D-A6B1-A235DCB69EC2","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 5","udid":"83EE75F7-A888-416C-8C83-52BD249C2498","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 5s","udid":"6F269D2F-AD1F-451C-82B4-7B3C34D0B09E","state":"Booted","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6","udid":"2DD48BB8-90E5-4E96-8171-32360E44454D","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6 Plus","udid":"979638C4-9376-4339-BC07-E7743912FFC4","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6s","udid":"87A46685-D19B-445D-9847-6F95E6BD29C9","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6s Plus","udid":"5CC53492-F321-485D-B62F-83B75A049B21","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad 2","udid":"31C9F4EC-C09F-4307-8BF8-F9D0F0A01268","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Retina","udid":"2CFB6842-0536-4138-BA9E-02C5FA08E779","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Air","udid":"2F36E68B-E741-4657-A660-ED1942F0C8B4","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Air 2","udid":"DADBA4A0-7E76-4B4B-8EE0-84FAD92CAAF1","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Pro","udid":"2A7C0C49-6A31-4474-9AFF-23FCBC98C52D","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"Apple TV 1080p","udid":"BFA4A25D-C74E-4BEB-891A-D45460901787","state":"Shutdown","available":true,"runtime":"tvOS 9.2"},{"name":"Apple Watch - 38mm","udid":"8D455689-0EEE-4E19-8376-FEFDFA5D38C2","state":"Shutdown","available":true,"runtime":"watchOS 2.2"},{"name":"Apple Watch - 42mm","udid":"0A11E49E-A09A-4457-9780-4039CF2BB3C0","state":"Shutdown","available":true,"runtime":"watchOS 2.2"}]
>> xctest-client.js:43:14 [master] pid:33360 project path: /Applications/devtools/nodejs/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:130:10 [master] pid:33360 {
	"bundleId": "xudafeng.ios-app-bootstrap",
	"platformName": "iOS",
	"platformVersion": "9.3",
	"app": "/var/folders/pm/8cswgqs52rg74zfpz0cgfcg80000gp/T/ios-app-bootstrap.app/"
}
>> xctest-client.js:183:12 [master] pid:33360 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.25
>> xctest-client.js:86:16 [master] pid:33360 tail: /Users/agathe/Library/Logs/CoreSimulator/6F269D2F-AD1F-451C-82B4-7B3C34D0B09E/system.log: No such file or directory

>> xctest-client.js:94:16 [master] pid:33360 bootstrap exit with code: 1, signal: null
>> responseHandler.js:50:12 [master] pid:33360 Send Error Respone to Client: undefined

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/Applications/devtools/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/Applications/devtools/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:53:17)
      at throw (native)
      at onRejected (/Applications/devtools/nodejs/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (node.js:369:9)

>> 
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:33360 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:19:14 [master] pid:33360 Send HTTP Respone to Client: 405 Method Not Allowed
>> 
>>     2) "after all" hook

>> 

>> 

>>   0 passing (19s)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"/Users/agathe/macaca-test-sample/app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
  Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)


>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

**Comment by xudafeng** [comment]
@wrldeop 你只有一个xcode？

**Comment by wrldeop** [comment]
是额

**Comment by xudafeng** [comment]
qq 群 287162474

**Comment by wrldeop** [comment]
我之前安装过appium会有影响么

**Comment by xudafeng** [comment]
不会的

**Comment by wrldeop** [comment]
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/Applications/devtools/nodejs/bin/macaca -> /Applications/devtools/nodejs/lib/node_modules/macaca-cli/bin/macaca-cli

> macaca-cli@1.1.2 postinstall /Applications/devtools/nodejs/lib/node_modules/macaca-cli
> node ./scripts/print.js


@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@888@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0Lt111111tL0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0GCLCG8@01ii1fLCGGGGCC8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80GLfCfL0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80GCLLfttttt1i1tfffLCG08@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8GLti;;;;;;;;;;;;;;;;;;;;;;;;itfC0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@8Cti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i1LG8@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@0L1;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;1L0@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@8L1;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;if0@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@880088@@@@0t;;;;;;;;;;;itLCG0000GCLt1;;;;itfCGG000GCLf1;;;;;;;;;;;;1C8@@@80008@@@@@@@@@@@
@@@@@@8Cti;;;;;;itLt;;;;;;;;;;tC8@@@@@@@@@@@@@@8GC0@@@@@@@@@@@@@@8Gfi;;;;;;;;;;;t1i;;;;;i1fG8@@@@@@
@@@@0t;;;;;;;;;;;;;;;;;;;;;;L8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@C1;;;;;;;;;;;;;;;;;;;;;if8@@@@
@@@L;;;;;;;;;;;;;;;;;;;;;;t8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@C;;;;;;;;;;;;;;;;;;;;;;iG@@@
@@L;;;;;;;;;;;;;;;;;;;;;;L@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0;;;;;;;;;;;;;;;;;;;;;;;0@@
@8;;;;;;;;;;;;;;;;;;;;;;f@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@G;;;;;;;;;;;;;;;;;;;;;;1@@
@G;;;;;;;;;;;;;;;;;;;;;;8@@@@@@@@@8CfLG@@@@@@@@@@@@@@@@@8CfLC@@@@@@@@@@@@@t;;;;;;;;;;;;;;;;;;;;;i@@
@8;;;;;;;;;;;;;;;;;;;;;t@@@@@@@@@G;;;;;t@@@@@@@@@@@@@@@8i;;;;i8@@@@@@@@@@@G;;;;;;;;;;;;;;;;;;;;;1@@
@@L;;;;;;;;;;;;;;;;;;;;t@@@@@@@@@G;;;;;1@@@@@@@@@@@@@@@8;;;;;i8@@@@@@@@@@@G;;;;;;;;;;;;;;;;;;;;;0@@
@@@L;;;;;;;;;;;;;;;;;;;i@@@@@@@@@@0LtfC@@@@@@@@@@@@@@@@@8LffC8@@@@@@@@@@@@L;;;;;;;;;;;;;;;;;;;iG@@@
@@@@0t;;;;;;;;;;;;;;;;;;C@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8;;;;;;;;;;;;;;;;;;;f8@@@@
@@@@@@0Lti;;;;;;;;;;;;;;i8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Ci;;;;;;;;;;;;;;1fC8@@@@@@
@@@@@@@@@@1;;;;;;;;;;;fG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Gt;;;;;;;;;;;i@@@@@@@@@@
@@@@@@@@@@t;;;;;;;;;f8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@01;;;;;;;;;i@@@@@@@@@@
@@@@@@@@@@L;;;;;;;;G@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@f;;;;;;;;t@@@@@@@@@@
@@@@@@@@@@0;;;;;;;0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@1;;;;;;;C@@@@@@@@@@
@@@@@@@@@@@1;;;;;t@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@G;;;;;;i8@@@@@@@@@@
@@@@@@@@@@@0;;;;;L@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;;;;;;C@@@@@@@@@@@
@@@@@@@@@@@@f;;;;f@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@i;;;;t@@@@@@@@@@@@
@@@@@@@@@@@@@t;;;i@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8;;;;i8@@@@@@@@@@@@
@@@@@@@@@@@@@@t;;;t@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@t;;;i8@@@@@@@@@@@@@
@@@@@@@@@@@@@@@f;;;t8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8t;;;t8@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@Gi;;iG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Gi;;;L@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@8f;;;tG@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8C1;;;t0@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@0t;;;ifG8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0Cti;;;tG@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@0fi;;;;tLG8@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@80Cti;;;;;f0@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@8Gt;;;;;;itfLC008@@@@@@@@@@@@@@@@@@880GCLt1;;;;;;;tC8@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@8Gf1;;;;;;;;;;ii11ttfffLffftt11ii;;;;;;;;;;itC8@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8Gfti;;;;;;;;;;;;;;;;;;;;;;;;;;;;;i1fC0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8GCLt11i;;;;;;;;;;;;;ii1tfCG0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@8880000000888@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


Macaca was successfully installed!

Run `macaca -h` for further help.

npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/appium-android-driver requires lodash@'^3.10.0' but will load
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/lodash,
npm WARN unmet dependency which is version 4.13.1
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/appium-android-driver requires source-map-support@'^0.3.1' but will load
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/source-map-support,
npm WARN unmet dependency which is version 0.4.0
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/appium-selendroid-driver requires lodash@'^3.10.1' but will load
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/lodash,
npm WARN unmet dependency which is version 4.13.1
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/appium-selendroid-driver requires source-map-support@'^0.3.2' but will load
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/source-map-support,
npm WARN unmet dependency which is version 0.4.0
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/appium-fake-driver/node_modules/babel-core/node_modules/regexpu/node_modules/recast requires source-map@'~0.5.0' but will load
npm WARN unmet dependency /Applications/devtools/nodejs/lib/node_modules/appium/node_modules/appium-fake-driver/node_modules/babel-core/node_modules/source-map,
npm WARN unmet dependency which is version 0.4.4

**Comment by wrldeop** [comment]
我重新安装就会报一些warn

**Comment by xudafeng** [comment]
warn 没关系，还有报错吗？

**Comment by wrldeop** [comment]
哈哈哈  我今早把虚拟机上安装的app卸载了  跑了两次成功了  不过有的时候还是有错误  不过我想应该是正常的 谢谢了

**Comment by zhuominjie** [comment]
@wrldeop 前面报的两个error我也碰到了，你是怎么解决的？

**Comment by zhuominjie** [comment]
@xudafeng 我有两个xcode，命名不一样，一个是xcode，一个是xcode64，跟这个有关系吗？

**Comment by zwyxsyu** [comment]
我也遇到这个问题了，你们是怎么解决的？

**Comment by mhlee0514** [comment]
这个问题你们解决了吗 @wrldeop @zwyxsyu @zhuominjie
