### ISSUE TITLE
How to find if an element is highlighted/selected in iOS and android

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#163]
* **Macaca Version**:

* **Macaca Doctor**:

* **Operate System**:

* **programming Language**:

**Comment by xudafeng** [comment]
https://macacajs.github.io/macaca/inspector.html

**Comment by mpreethi90** [comment]
No. I want to check in test if an element is selected.

**Comment by mpreethi90** [comment]
@xudafeng  please help

**Comment by brucejcw** [comment]
if you have got the element, then the select should work.  
To check it, you can add something in your click callback like `console.log`, `some class` and `alert` etc.

**Comment by mpreethi90** [comment]
No. I do not want to click the element. I just want to check if the element is enabled to select/tap. This is not in webview.Our project is reactnative and this is specific to ios/android. Please help @brucejcw
