### ISSUE TITLE
What does webview() do? How do I get source or access elements inside a webview?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#164]
- **Macaca Version**:
- **Macaca Doctor**:
- **Operate System**:
- **programming Language**:

**Comment by brucejcw** [comment]
@mpreethi90 `webview()` will get the web context of your app,  you can find usage from our [website](http://macacajs.github.io/macaca/getting-started.html)

**Comment by mpreethi90** [comment]
Problem I face is something different. I work on automation for a reactnative project for both iOS and android. So, in a screen there is an element of class type "TZWebView". When I try to get the webview content by using webview() and try to access elements inside, I do not succeed. Can you kindly help?

**Comment by mpreethi90** [comment]
also, is there any way to get the source of the webview loaded inside the app? Because whenever I try source(), macaca just prints source of entire app context like below-

>> { tree: 
   { bounds: '{{0, 0}, {375, 667}}',
     isEnabled: '1',
     isVisible: '1',
     children: [ [Object], [Object], [Object] ],
     rect: { origin: [Object], size: [Object] },
     value: null,
     label: '上线了',
     type: 'Application',
     name: '上线了',
     rawIdentifier: null } }

>>

**Comment by mpreethi90** [comment]
and do you have any methods to check if webview has finished loading?

**Comment by xudafeng** [comment]
@mpreethi90

execute javascript in webview, or check some web elements if existed.

**Comment by mpreethi90** [comment]
ok thank you. Just wanted to check if elementByXPath() does not work inside webview? throws me error

**Comment by xudafeng** [comment]
elementByXPath  do work in webview, post your test code to me?

**Comment by mpreethi90** [comment]
.webview()
              .elementByXPath('//*[@id="main"]/div[1]/div[2]/div[2]/div/div/div[1]/div/div[4]/div/div')
              .click()

**Comment by mpreethi90** [comment]
also, 
        .webview()
.execute('document.documentElement.innerHTML')
                  .then(function (html) {
console.log(html)                  })

throws error **"Error: [execute("document.documentElement.innerHTML")] Error response status: 1,"**

@xudafeng  kindly help

**Comment by xudafeng** [comment]
.source()
