### ISSUE TITLE
建议增加macaca日志导出功能【Macaca报告器优化】

### ISSUE THREAD

**Issue by adfghzhang** [alibaba/macaca#165]
功能类似于appium -g /temp/appium.log

**Comment by ownehe** [comment]
利用jenkins一次性跑多个脚本文件，最好能有一种方式统计每个用例的状态结果和执行情况，产出一个类似html的报告。

**Comment by xudafeng** [comment]
@zenzhu 正在实现中

**Comment by xudafeng** [comment]
已可用

参考 https://testerhome.com/topics/5995
