### ISSUE TITLE
Is there any method to tap/click at particular rect/point in an element/page?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#166]
- **Macaca Version**:
- **Macaca Doctor**:
- **Operate System**:
- **programming Language**:

**Comment by brucejcw** [comment]
JS?  use [elementBy...](http://macacajs.github.io/macaca-wd/)

**Comment by mpreethi90** [comment]
No. My requirement is something like tapping at a particular rect. Example- tapAtPoint(200,50) in the current window. Do we have something like this in macaca?

**Comment by mpreethi90** [comment]
any help on this please?

**Comment by brucejcw** [comment]
for android, you can use `driver.moveTo(null, x, y).click()`  
IOS not support yet

**Comment by CodeToSurvive1** [comment]
@brucejcw android的driver.moveTo(null, x, y).click()有些场景下不能用，比如密码键盘，只能通过模拟tap的方式才能有效，tapAtPoint(200,50)这种接口什么支持？

**Comment by brucejcw** [comment]
@CodeToSurvive1 目前还不支持哦....这些都是非标准的api了, 可以考虑自己封装一个

**Comment by CodeToSurvive1** [comment]
@brucejcw 后面会考虑添加吗？

**Comment by brucejcw** [comment]
@CodeToSurvive1 暂不不考虑添加
