### ISSUE TITLE
saveScreenshot 没有自动创建多层文件夹

### ISSUE THREAD

**Issue by brucejcw** [alibaba/macaca#170]
save到多层文件夹时会报错, `no such file or dir`

**Comment by xudafeng** [comment]
@brucejcw 哪个语言？

**Comment by brucejcw** [comment]
js

**Comment by xudafeng** [comment]
saveScreenshot 你传的时绝对路径吧

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-wd/blob/master/wd/lib/commands.js#L1117
