### ISSUE TITLE
app-inspector 无法连接ios设备

### ISSUE THREAD

**Issue by zhoujinjian** [alibaba/macaca#173]
@xudafeng 
环境布署mac机上，同样的环境，andoroid可以通过app-inpector来访问页面，并定位元素，
ios，无法连接进页面，详细如下：

>> server.js:15:12 [master] pid:19803 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'cf8bb63d33b5ffc4bf8cf78e49bbb6052afa8c29',
  ip: '172.17.21.11',
  host: 'mikezhoudeMac-mini.local',
  loaded_time: '2016-09-09 16:51:55' }
>> inspector start at: http://172.17.21.11:5678
>> xctest-client.js:43:14 [master] pid:19803 project path: /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.25@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:183:12 [master] pid:19803 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.25
>> xctest-client.js:156:14 [master] pid:19803 xcodebuild: error: The run destination FX-Ipod9 is not valid for Testing the scheme 'WebDriverAgentRunner'.
	FX-Ipod9’s iOS 9.0 doesn’t match WebDriverAgentRunner.xctest’s iOS 9.3 deployment target. Upgrade FX-Ipod9’s iOS version or lower WebDriverAgentRunner.xctest’s deployment target.

**Comment by xudafeng** [comment]
@zhoujinjian npm 装一下

**Comment by zhoujinjian** [comment]
@xudafeng 
![image](https://cloud.githubusercontent.com/assets/10597117/18381496/15459b9c-76af-11e6-8030-e577ce9da5f9.png)

**Comment by brucejcw** [comment]
@zhoujinjian Upgrade FX-Ipod9’s iOS version or lower WebDriverAgentRunner.xctest’s deployment target.

**Comment by zhoujinjian** [comment]
@xudafeng @黑猫
卸载app-inspector，重装后，重新执行下述命令，在调用ios的udid时，会调用andorid的adb来执行：

mikezhoudeMac-mini:~ mikezhou$ app-inspector -u C9A81621-8D15-5F6C-8680-5A1A84B9C9 --verbose
>> server.js:16:12 [master] pid:20131 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'C9A81621-8D15-5F6C-8680-5A1A84B9C9',
  ip: '172.17.21.11',
  host: 'mikezhoudeMac-mini.local',
  loaded_time: '2016-09-09 17:21:20' }
>> inspector start at: http://172.17.21.11:5678
>> app-inspector:64:44 [master] pid:20131 Error: Command failed: /usr/local/android-sdk/android-sdk-macosx/platform-tools/adb -s C9A81621-8D15-5F6C-8680-5A1A84B9C9 push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client/bin/uiautomator-bootstrap.jar /data/local/tmp

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)
^C

**Comment by zhoujinjian** [comment]
@Berton Zhu

**Comment by zhoujinjian** [comment]
@meowtec ，看一下上述的问题

**Comment by brucejcw** [comment]
@zhoujinjian `xcrun simctl list`, 贴一下

**Comment by brucejcw** [comment]
@zhoujinjian 你先用模拟器试试,模拟器在udid长度36个长度啊

**Comment by zhoujinjian** [comment]
@brucejcw :
ios真机，模拟器都试过了，都不行呢,android的真机试的可以
== Devices ==
-- iOS 9.3 --
    iPhone 4s (837E1B83-2884-412E-A49B-C8D45495811A) (Shutdown)
    iPhone 5 (75E5344E-19FB-4130-9585-9798BBF5EDEC) (Shutdown)
    iPhone 5s (2708ACD4-B518-4080-9C36-B848B80D541B) (Shutdown)
    iPhone 6 (12AEA3C5-41C0-4DDE-83AE-EABD1D72CDE5) (Shutdown)
    iPhone 6 Plus (92CF7E65-3EE5-4594-90B6-574E75DB40BE) (Shutdown)
    iPhone 6s (8D17FBAD-ADFA-4C1E-99B3-3EC55CA99E57) (Shutdown)
    iPhone 6s Plus (3937B2C1-3BF1-4F92-9110-F5C9AFA96F2F) (Booted)
    iPad 2 (06466A6D-CD2C-4DB8-A0AB-89EBE032462F) (Shutdown)
    iPad Retina (0F941F84-D8C0-4E7A-9A65-B0A3A6164B26) (Shutdown)
    iPad Air (89C0BD0B-1F9F-465B-B5FF-6F4B968C455B) (Shutdown)
    iPad Air 2 (A70BA92A-0DA5-47DC-B04F-F0C4E12F5D54) (Shutdown)
    iPad Pro (8CA9DB5C-F96E-4B1C-8C2E-7A0A79C3A823) (Shutdown)
-- tvOS 9.2 --
    Apple TV 1080p (F0E671A1-7B9E-497D-9830-3A199AA4F923) (Shutdown)
-- watchOS 2.2 --
    Apple Watch - 38mm (41E392E4-53FD-43ED-B2AB-A9D802A108D5) (Shutdown)
    Apple Watch - 42mm (CA679A7B-BD5F-4BBB-AFA6-5ADFD6C4E7DC) (Shutdown)
== Device Pairs ==
6BA16F5E-0A61-47E9-B4ED-DD71C1E8E1F6 (active, disconnected)
    Watch: Apple Watch - 38mm (41E392E4-53FD-43ED-B2AB-A9D802A108D5) (Shutdown)
    Phone: iPhone 6s (8D17FBAD-ADFA-4C1E-99B3-3EC55CA99E57) (Shutdown)
726B7460-E2B0-4CAC-B167-430D8BF458B8 (active, disconnected)
    Watch: Apple Watch - 42mm (CA679A7B-BD5F-4BBB-AFA6-5ADFD6C4E7DC) (Shutdown)
    Phone: iPhone 6s Plus (3937B2C1-3BF1-4F92-9110-F5C9AFA96F2F) (Booted)

**Comment by brucejcw** [comment]
@zhoujinjian `app-inspector -u 2708ACD4-B518-4080-9C36-B848B80D541B --verbose`

运行一下, 应该正常的

**Comment by zhoujinjian** [comment]
@brucejcw 
用这个udid运行没报错，但还是访问不了，一直在等待中，找不到页面

mikezhoudeMac-mini:~ mikezhou$ app-inspector -u 2708ACD4-B518-4080-9C36-B848B80D541B --verbose
>> server.js:16:12 [master] pid:20524 server start with config:
 { port: 5678,
  verbose: true,
  udid: '2708ACD4-B518-4080-9C36-B848B80D541B',
  ip: '172.17.21.11',
  host: 'mikezhoudeMac-mini.local',
  loaded_time: '2016-09-09 17:48:11' }
>> inspector start at: http://172.17.21.11:5678
>> xctest-client.js:43:14 [master] pid:20524 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:183:12 [master] pid:20524 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.25
>> xctest-client.js:94:16 [master] pid:20524 bootstrap exit with code: 1, signal: null
>> app-inspector:64:44 [master] pid:20524 undefined
>> xctest-client.js:86:16 [master] pid:20524 tail: /Users/mikezhou/Library/Logs/CoreSimulator/2708ACD4-B518-4080-9C36-B848B80D541B/system.log: No such file or directory

>> xctest-client.js:156:14 [master] pid:20524 2016-09-09 17:48:11.831 xcodebuild[20528:1409486] [MT] IDETestOperationsObserverDebug: (F0F9D804-53CB-4C0D-B049-D256B64E4601) Beginning test session F0F9D804-53CB-4C0D-B049-D256B64E4601 with Xcode 7D1014 on target <DVTiPhoneSimulator: 0x7fc55c6c7700> {
		SimDevice: SimDevice : iPhone 5s (2708ACD4-B518-4080-9C36-B848B80D541B) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 9.3 (13E230) - com.apple.CoreSimulator.SimRuntime.iOS-9-3 }
} (9.3 (13E230))

>> xctest-client.js:156:14 [master] pid:20524 2016-09-09 17:48:11.833 xcodebuild[20528:1409503]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/mikezhou/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/0869EAFC-CB3A-4CFE-B938-67782A77F9F6/Session-2016-09-09_17:48:11-0osXiQ.log

  <-- GET /
  --> GET / 200
  <-- GET /apple-touch-icon-precomposed.png
  --> GET /apple-touch-icon-precomposed.png 404
  <-- GET /apple-touch-icon.png
  --> GET /apple-touch-icon.png 404
  <-- GET /
  --> GET / 200
  <-- GET /apple-touch-icon-precomposed.png
  --> GET /apple-touch-icon-precomposed.png 404
  <-- GET /apple-touch-icon.png
  --> GET /apple-touch-icon.png 404
  <-- GET /
  --> GET / 200
  <-- GET /apple-touch-icon-precomposed.png
  --> GET /apple-touch-icon-precomposed.png 404

**Comment by brucejcw** [comment]
可能是xcode安装的问题, 你怎么装的

**Comment by zhoujinjian** [comment]
@brucejcw ,模拟器的可以了，那现在真机的问题，（只能升级设备verison了）
> inspector start at: http://172.17.21.11:5678
>> xctest-client.js:43:14 [master] pid:21879 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:183:12 [master] pid:21879 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.25
>> xctest-client.js:156:14 [master] pid:21879 xcodebuild: error: The run destination FX-Ipod9 is not valid for Testing the scheme 'WebDriverAgentRunner'.
	FX-Ipod9’s iOS 9.0 doesn’t match WebDriverAgentRunner.xctest’s iOS 9.3 deployment target. Upgrade FX-Ipod9’s iOS version or lower WebDriverAgentRunner.xctest’s deployment target.

**Comment by brucejcw** [comment]
目前的解决方案是升级设备.  
@xudafeng

**Comment by zhoujinjian** [comment]
@brucejcw ，如果选择这种降底布署环境的 ，这个该 怎么降版本的呢
lower WebDriverAgentRunner.xctest’s deployment target.

**Comment by brucejcw** [comment]
可以升级到9.3吗

**Comment by zhoujinjian** [comment]
OK

**Comment by zhoujinjian** [comment]
@xudafeng ,
@brucejcw ,
@meowtec,
ios真机设备升到9.3后，
还是不能正常连接访问到页面，报如下错误
(null)
	} (9.3.5 (13G36))

>> xctest-client.js:156:14 [master] pid:23514 2016-09-09 19:12:48.600 xcodebuild[23518:1470830]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/mikezhou/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/52E4802B-76F9-4C8A-A4D4-C221C6801410/Session-2016-09-09_19:12:48-NixVFw.log

>> xctest-client.js:156:14 [master] pid:23514 
Testing failed:

>> xctest-client.js:156:14 [master] pid:23514 	No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:164:14 [master] pid:23514 xctest client exit with code: 65, signal: null
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /

**Comment by meowtec** [comment]
证书问题，这个是已知的问题。

**Comment by zhoujinjian** [comment]
@xudafeng ,
@brucejcw ,
@meowtec,
那这个证书的问题 估计什么时候能解决的呢？

**Comment by xudafeng** [comment]
@zhoujinjian 会尽快的，usb问题一起修复

**Comment by zhoujinjian** [comment]
@xudafeng 好的，修复后，知会一下。

**Comment by xudafeng** [comment]
@zhoujinjian 会的

**Comment by xudafeng** [comment]
已支持真机，请升级macaca-ios

https://github.com/alibaba/macaca/issues/42

**Comment by ManningZhang** [comment]
@zhoujinjian @xudafeng 请问下两位，我在使用app-inspector获取ios真机控件元素的时候出现以下错误：
-- GET /
>> xctest-client.js:230:20 [master] pid:16491 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.4.6@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:16491 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.4.6@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:16491 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.4.6@xctestwd/XCTestWD/XCTestWD.xcodeproj
  <-- GET /
![2019-02-18 7 47 31](https://user-images.githubusercontent.com/30856555/53006813-eeddb700-3470-11e9-8e63-bbcbad635251.png)
请问下这是什么原因呢？
