### ISSUE TITLE
app-inspector 生成的xpath表达式无法匹配

### ISSUE THREAD

**Issue by zhoujinjian** [alibaba/macaca#175]
<!--
Thanks for wanting to report an issue you've found in Macaca. Please fill in the template below by replacing the html comments with an appropriate answer.

Macaca Version: usually output of `macaca -v`
Macaca Doctor: usually output of `macaca doctor`
Platform: either `uname -a` output, or if Windows, version and 32 or 64-bit.

@meowtec,@xudafeng ,
通过app-inspector生成的xpath表达式，无法成功匹配到元素，
如app-inspector生成的xpath表达式，都是
XPath=
//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]
这种形式。
而实际app能识别到的xpath表达式是//UIAApplication[1]/UIAWindow[1]/UIATabBar[1]/UIAButton[2]这种控制表达形式。

**Comment by meowtec** [comment]
Are you using macaca's `getByXPath` method?

**Comment by meowtec** [comment]
XCUI XPath can be only used with Macaca(using xctest).
