### ISSUE TITLE
Is there a way to check if the webview has finished loading?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#177]
* **Macaca Version**:

* **Macaca Doctor**:

* **Operate System**:

* **programming Language**:

**Comment by brucejcw** [comment]
[onload](https://facebook.github.io/react-native/docs/webview.html) provided by react-native

**Comment by mpreethi90** [comment]
@brucejcw , Yes onload is there in reactnative. But how do I access that method through macaca?
