### ISSUE TITLE
android真机跑官方案例后台日志出现 no emulator detected

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#178]
* **Macaca Version**:
  1.1.2
* **Macaca Doctor**:

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/opt/android-sdk`
  Platforms is set to `/usr/local/opt/android-sdk/platforms/android-24`
  Android tools is set to `/usr/local/opt/android-sdk/tools/android`

  Installed driver list:

  android: 1.0.27
  chrome: 1.0.2
  electron: 1.1.2
  ios: 1.0.36

* **Operate System**:
OS X EI Capitan
10.11.6 (15G1004)
* **programming Language**:

1.下面是官方例子在android真机上运行的后台日志，虽然案例跑成功，但是后台日志中出现macaca-android.js:64:16 [master] pid:1343 Error: Command failed: /bin/sh -c /usr/local/opt/android-sdk/platform-tools/adb emu kill error: no emulator detected，自己重新写了一个脚本，也发现同样的问题，不知道是macaca在跑完案例的时候会断开当前设备及检查模拟器的原因？还是？
2.咨询下macaca会对安全键盘这块有相关的后期计划吗？

>>     ✓ #7 should works with web (9086ms)

>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a/contexts, jsonBody: {}
>> proxy.js:52:14 [master] pid:1343 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/9f72ed5ff3d79c3774c4e9b6b29303ea/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:1343 Got response with status 200: {"sessionId":"9f72ed5ff3d79c3774c4e9b6b29303ea","status":0,"value":["CDwindow-f8ecd080-a2cc-4747-a2cc-c8e72240f163","CDwindow-579d2941-a3b7-4f29-9b12-35dd567312ab","CDwindow-c6ca0a04-f1ac-4a44-a126...
>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0,"value":"[\"NATIVE_APP\",\"CDwindow-f8ecd080-a2cc-4747-a2cc-c8e72240f163\",\"CDwindow-579d2941-a3b7-4f29-9b12-35dd567312ab\",\"CDwindow-c6ca0a04-f1ac-4a44-a126-861f1f0b0d3a\"]"}
>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a/context, jsonBody: {"name":"NATIVE_APP"}
>> proxy.js:52:14 [master] pid:1343 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/9f72ed5ff3d79c3774c4e9b6b29303ea/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:1343 Got response with status 200: {"sessionId":"9f72ed5ff3d79c3774c4e9b6b29303ea","status":0,"value":["CDwindow-f8ecd080-a2cc-4747-a2cc-c8e72240f163","CDwindow-579d2941-a3b7-4f29-9b12-35dd567312ab","CDwindow-c6ca0a04-f1ac-4a44-a126...
>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a/element, jsonBody: {"using":"name","value":"PERSONAL"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"PERSONAL","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"12"}}
>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0,"value":"{\"ELEMENT\":\"12\"}"}

>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a/element/12/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"12"}}

>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0,"value":"true"}
return: {"success":true,"data":true}

>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a/screenshot, jsonBody: {}
>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzs3XdcU1f/B/BPJiMhIiIoIOJEERURqeKsW+pAVLRaF+JCsVap66EWcdS6V90DR5VaNxatoo+rihusYh04EBARERlhheT3R365TSCBBAIBn+/79eqrIdyceyMZ937OOd/DAiADIYQQQgghhBBCSDXGNvQBEEIIIYQQQgghhJQXBRyEEEIIIYQQQgip9ijgIIQQQgghhBBCSLVHAQchhBBCCCGEEEKqPQo4CCGEEEIIIYQQUu1RwEEIIYQQQgghhJBqjwIOQgghhBBCCCGEVHsUcBBCCCGEEEIIIaTao4CDEEIIIYQQQggh1R4FHIQQ..."}
>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a/element, jsonBody: {"using":"name","value":"Logout"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"Logout","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"13"}}

>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0,"value":"{\"ELEMENT\":\"13\"}"}
>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a/element/13/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"13"}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a/screenshot, jsonBody: {}
>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzs3XdYU+f7BvA7JMwAIiIqIuJWRKWo1K11b3Gh1bpwW7VWqVZrLeKsdWtrtXVUrVLr1lJr0Tqoqw5wYOsWkSqismWE5PdHfjlNIIEEAiF+78919WoIJ+ccMJycc5/nfV4RAAWIiIiIiIiIiMyYhal3gIiIiIiIiIioqBhwEBEREREREZHZY8BBRERERERERGaPAQcRERERERERmT0GHERERERERERk9hhwEBEREREREZHZY8BBRERERERERGaPAQcRERERERERmT0GHERERERERERk9hhwEBEREREREZHZY8BBRERERERERGaPAQcR..."}
    ✓ #8 should logout success (5469ms)

>> responseHandler.js:11:12 [master] pid:1343 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/842cf391-ab48-4095-84d9-4d3500678f3a, jsonBody: {}
>> macaca-android.js:64:16 [master] pid:1343 Error: Command failed: /bin/sh -c /usr/local/opt/android-sdk/platform-tools/adb emu kill
error: no emulator detected

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
>> session.js:80:12 [master] pid:1343 Delete session, sessionId: 842cf391-ab48-4095-84d9-4d3500678f3a
>> responseHandler.js:43:14 [master] pid:1343 Send HTTP Respone to Client: {"sessionId":"842cf391-ab48-4095-84d9-4d3500678f3a","status":0}
>> 

>> 

>>   8 passing (2m)

>> 

>> Test completed!

**Comment by xudafeng** [comment]
@lixiaojiao 目前内置了utf7 键盘https://github.com/macacajs/android-unicode，安全键盘支持是指？

**Comment by lixiaojiao** [comment]
@xudafeng 银行业务中的安全键盘，比如招商银行输入数字验证码这类的

**Comment by xudafeng** [comment]
@lixiaojiao 业务逻辑？需要业务层面解决了。

**Comment by lixiaojiao** [comment]
@xudafeng 如果我已经拿到了验证码，用现有的api发送sendKeys('123456')到密码框中，能输入成功，   用inspector查看是123456，提交的时候识别不了。  但是手工按键的时候用inspector查看内容是******。
