### ISSUE TITLE
建议增加全页面截图的api，saveScreenshot()只能针对当前可视区域截图

### ISSUE THREAD

**Issue by tonyying** [alibaba/macaca#180]
如题，有些页面比较长，想整个页面截图保存下来，请问是否可以增加相关的api支持？

**Comment by xudafeng** [comment]
phantomjs 貌似可以

**Comment by meowtec** [comment]
electron 做不了整页截图

**Comment by xudafeng** [comment]
@tonyying @meowtec 可以业务逻辑实现吗？

滚动+截图

**Comment by tonyying** [comment]
好吧 我目前的实现方式就是滚动+截多张图的方式来实现的。。不知道后续是否可以实现这个功能 @xudafeng

**Comment by zenzhu** [comment]
@tonyying 其实让我们做，也是做成滚动+截图的功能，但如果遇到那种无限下拉的，就会一直截不停了，建议还是自己截图啊。

**Comment by xudafeng** [comment]
@tonyying 这是业务逻辑层面的实现，不是wd基础模块的功能哦
