### ISSUE TITLE
建议web端增加支持模拟鼠标点击操作

### ISSUE THREAD

**Issue by tonyying** [alibaba/macaca#181]
web上有些元素无法定位到，比如canvas画布中的可点击元素
所以我考虑使用笨办法，moveTo()结合鼠标点击来实现，但是看了下sendkeys()好像只支持模拟键盘输入，并不支持鼠标点击操作，是否可以增加相关支持？
或者是否还有其他更好的实现方式？谢谢

**Comment by xudafeng** [comment]
@tonyying canvas 这种没有子view体系的元素，可以考虑截图对比来断言，及时坐标找到了也相应不了点击事件的

**Comment by xudafeng** [comment]
例子 https://testerhome.com/topics/4922
