### ISSUE TITLE
macaca是否支持操作过程或关键字的自定义封装？

### ISSUE THREAD

**Issue by tonyying** [alibaba/macaca#182]
比如我有两个自动化用例，分别有以下操作项：
1.A->B->C->D
2.A->B->C->E
我想把A->B->C这个过程自行定义成一个X
这样我就能把公共部分抽离出来，减少脚本编写量，2个用例就能精简成：
1.X->D
2.X->E
想问macaca是否支持这样的写法？

**Comment by zenzhu** [comment]
这是可以的，客户端模块是可以自定义扩展方法的，你可以参考这个例子 [自定义方法](https://github.com/admc/wd/blob/master/examples/promise/add-method.js)

**Comment by tonyying** [comment]
好的 谢谢我试试
