### ISSUE TITLE
MAC 安装cnpm i macaca-android -g

### ISSUE THREAD

**Issue by hujiachun** [alibaba/macaca#184]
hujiachun:~ hujiachun$ cnpm i macaca-android -g
[win-spawn@2.0.0](/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.4@ant-build/node_modules/win-spawn) deprecate: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
[tough-cookie@2.2.2](/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.2.69.0@request/node_modules/tough-cookie) deprecate: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[macaca-android@*] installed at node_modules/.macaca-android_npminstall/node_modules/.1.0.27@macaca-android (113 packages, use 7s, speed 231.49kB/s, json 1.49MB, tarball 0B)
execute post install scripts...
[unlock-apk@0.1.15] scripts.install: "node ./script/build.js" at /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.15@unlock-apk
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home
Buildfile: /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.15@unlock-apk/build.xml

-set-mode-check:

-set-debug-files:

-check-env:

 [checkenv] Android SDK Tools Revision 24.4.1

 [checkenv] Installed at /usr/local/Cellar/android-sdk/24.4.1_1

-setup:

     [echo] Project Name: unlock_apk

  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:

BUILD FAILED
/usr/local/Cellar/android-sdk/24.4.1_1/tools/ant/build.xml:483: SDK does not have any Build Tools installed.

Total time: 0 seconds

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.4@ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.15@unlock-apk/script/build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.4@ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
Error: post install error, please remove node_modules before retry!
Run "sh -c node ./script/build.js" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npminstall version: 2.2.1
npminstall args: /usr/local/Cellar/node/6.3.1/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/hujiachun/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org macaca-android -g
hujiachun:~ hujiachun$ cnpm i macaca-android -g
[win-spawn@2.0.0](/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.4@ant-build/node_modules/win-spawn) deprecate: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
[tough-cookie@2.2.2](/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.2.69.0@request/node_modules/tough-cookie) deprecate: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[macaca-android@*] installed at node_modules/.macaca-android_npminstall/node_modules/.1.0.27@macaca-android (113 packages, use 24s, speed 62.2kB/s, json 1.44MB, tarball 0B)
execute post install scripts...
[unlock-apk@0.1.15] scripts.install: "node ./script/build.js" at /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.15@unlock-apk
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home
Buildfile: /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.15@unlock-apk/build.xml

-set-mode-check:

-set-debug-files:

-check-env:

 [checkenv] Android SDK Tools Revision 24.4.1

 [checkenv] Installed at /usr/local/Cellar/android-sdk/24.4.1_1

-setup:

     [echo] Project Name: unlock_apk

  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:

BUILD FAILED
/usr/local/Cellar/android-sdk/24.4.1_1/tools/ant/build.xml:483: SDK does not have any Build Tools installed.

Total time: 0 seconds

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.4@ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.15@unlock-apk/script/build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.0.1.4@ant-build/lib/ant-build.js:98:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
Error: post install error, please remove node_modules before retry!
Run "sh -c node ./script/build.js" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npminstall version: 2.2.1
npminstall args: /usr/local/Cellar/node/6.3.1/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/hujiachun/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org macaca-android -g

**Comment by hujiachun** [comment]
hujiachun:~ hujiachun$ macaca doctor

  macaca-doctor version: 1.0.19


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.3.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_65`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/Cellar/android-sdk/24.4.1_1`
  Platforms is set to `/usr/local/Cellar/android-sdk/24.4.1_1/platforms/android-21`
  Android tools is set to `/usr/local/Cellar/android-sdk/24.4.1_1/tools/android`
  ADB tool is set to `/usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb`

  Installed driver list:

  android: 1.0.27
  chrome: 1.0.2
  ios: 1.0.36

**Comment by hujiachun** [comment]
求解答~~

**Comment by xudafeng** [comment]
@hujiachun https://macacajs.github.io/macaca/faq.html
