### ISSUE TITLE
clear() does not clear the textbox element in webview

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#186]
My div element in webview is as follows-
`<div class="s-component-content needsclick recursive s-font-heading cke_editable cke_editable_inline cke_contents_ltr" contenteditable="true" style="outline: 0px;" tabindex="0" spellcheck="true" role="textbox" aria-label="false"><p><em>添加副标题</em></p></div>`

when I try to execute the below command to clear the textinput, it does not work.

`.elementByClassName('s-component-content needsclick recursive s-font-heading cke_editable cke_editable_inline cke_contents_ltr')
.clear()
`

**Comment by zenzhu** [comment]
For now, we didn't support clear method on div with contenteditable="true"  like inputs. You may use pure js snippet to clear that.

**Comment by mpreethi90** [comment]
can you kindly provide some example on doing that please?

**Comment by mpreethi90** [comment]
I even tried .setText(), .replaceKeys(). But both throws error **"Unexpected data in simpleCallback."**

**Comment by zenzhu** [comment]
For example,
```
driver.exec(
  "document.querySelector('s-component-content needsclick recursive s-font-heading
   cke_editable cke_editable_inline cke_contents_ltr').textContent = \'\'"
)
```
