### ISSUE TITLE
How to access system menu in iOS/android

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#187]
Accessing system menu in iOS /android is doable through macaca?

**Comment by xudafeng** [comment]
what's your goal??

**Comment by mpreethi90** [comment]
My goal is to get the handler of system menu that is displayed in iOS/android. 

For example in iOS app-
My project is a reactnative one. In that, I display a system menu using **ImagePickerManager** to display a menu that shows **Choose from Photos, use camera and a custom,dynamic button** etc., (please refer attachment).

In macaca- 

How do I access those buttons from system menu? 
If I use 'elementByName' I am able to tap on the button.But 'elementByXPath' does not seems to work.  But, since the button I want to tap is dynamic I cannot rely on elementByName. 
Kindly suggest an alternative.

**Comment by xudafeng** [comment]
ImagePickerManager element can not be selected?

**Comment by mpreethi90** [comment]
Yes. Cannot be clicked/tapped through XPath .

**Comment by xudafeng** [comment]
watch this one https://github.com/alibaba/macaca/issues/366
