### ISSUE TITLE
Is there a way to delete only one or few characters instead of full clearing textinput?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#188]
* **Macaca Version**:

* **Macaca Doctor**:

* **Operate System**:

* **programming Language**:

**Comment by brucejcw** [comment]
just write again without those deleted characters

**Comment by mpreethi90** [comment]
No. My requirement is something like backspace and entering a new line etc.,
@brucejcw

**Comment by brucejcw** [comment]
[.sendKeys('\ue003')](https://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.keys.html#selenium.webdriver.common.keys.Keys.BACKSPACE)  
Enter any keycode you want to complete your requirement
