### ISSUE TITLE
IOS 真机测试 

### ISSUE THREAD

**Issue by hujiachun** [alibaba/macaca#189]
>> responseHandler.js:11:12 [master] pid:30723 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"/Users/hujiachun/Library/Developer/Xcode/DerivedData/PALifeApp-gbocrwhyniwrcbfqcpmiatprrobp/Build/Products/Debug-iphonesimulator/PALifeApp.app","reuse":"2","bundleId":"com.hujiachun.1","platformName":"iOS","udid":"ecab65eca01ae1d42874c26e645a33aee78296b6","deviceName":"iPhone 6","version":"9.3.2","autoAcceptAlerts":true}}
>> session.js:47:10 [master] pid:30723 Creating session, sessionId: 31fb58ca-1b01-4698-8f5c-e74c9ee183bd.
>> helper.js:191:12 [master] pid:30723 Using local app form /Users/hujiachun/Library/Developer/Xcode/DerivedData/PALifeApp-gbocrwhyniwrcbfqcpmiatprrobp/Build/Products/Debug-iphonesimulator/PALifeApp.app
>> xctest-client.js:43:14 [master] pid:30723 project path: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.25@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:130:10 [master] pid:30723 {
	"bundleId": "com.hujiachun.1",
	"app": "/Users/hujiachun/Library/Developer/Xcode/DerivedData/PALifeApp-gbocrwhyniwrcbfqcpmiatprrobp/Build/Products/Debug-iphonesimulator/PALifeApp.app",
	"platformName": "iOS"
}
>> xctest-client.js:183:12 [master] pid:30723 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.25
>> xctest-client.js:156:14 [master] pid:30723 2016-09-13 18:05:06.634 xcodebuild[30735:361213] [MT] IDETestOperationsObserverDebug: (2D0A7F3C-6B44-48F4-940C-B4547D30F472) Beginning test session 2D0A7F3C-6B44-48F4-940C-B4547D30F472 with Xcode 7D1014 on target <DVTiOSDevice: 0x7f874ae45c10> {
		deviceSerialNumber:         FFMRJAR0G5MQ
		identifier:                 ecab65eca01ae1d42874c26e645a33aee78296b6
		deviceClass:                iPhone
		deviceName:                 iPhone 6
		deviceIdentifier:           ecab65eca01ae1d42874c26e645a33aee78296b6
		productVersion:             9.3.2
		buildVersion:               13F69
		deviceSoftwareVersion:      9.3.2 (13F69)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12756144128
		deviceAvailableCapacity:    2092818432
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7f874ac299b0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.2 (13F69))

>> xctest-client.js:156:14 [master] pid:30723 2016-09-13 18:05:06.637 xcodebuild[30735:361223]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/hujiachun/Library/Developer/Xcode/DerivedData/WebDriverAgent-akymcjmuzehfilejizgprruppiiu/Logs/Test/C55174C9-1550-4E7D-ABA6-6BEA34228615/Session-2016-09-13_18:05:06-dm1FSP.log

>> xctest-client.js:156:14 [master] pid:30723
Testing failed:
	No matching provisioning profiles found: No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.facebook.WebDriverAgentRunner” were found.

>> xctest-client.js:156:14 [master] pid:30723 ** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:164:14 [master] pid:30723 xctest client exit with code: 65, signal: null

**Comment by hujiachun** [comment]
JSONObject porps = new JSONObject();
		porps.put("autoAcceptAlerts", true);
		porps.put("deviceName", "iPhone 6");
		porps.put("platformName", "iOS");
		porps.put("version", "9.3.2");
		porps.put("udid", "ecab65eca01ae1d42874c26e645a33aee78296b6");
		porps.put("bundleId", "com.hujiachun.1");
        porps.put("reuse", "2");

**Comment by xudafeng** [comment]
已支持真机，请升级macaca-ios

https://github.com/alibaba/macaca/issues/42
