### ISSUE TITLE
.click() does not work when the element is got through cssselector/xpath in webview

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#193]
I get a web element like below-

`.elementByCssSelector('.s-component-content.needsclick.recursive.s-font-title.cke_editable.cke_editable_inline.cke_contents_ltr')
`

When I execute below command,

`.click()`

it just focuses on the element but not triggering click and keyboard is displayed.

**Comment by zenzhu** [comment]
What is the type of that element, maybe the element is not a input?

**Comment by mpreethi90** [comment]
Does click() works only for input element??
I have an element in webview as follows-
`<div class="power" id="navbar-top-button"><div class="s-component s-image"><div class="s-component-editor-wrapper"><div class="s-component-overlay" title="On-line sites will not display a blank"><div class="center edit-button"><span><font><font>edit</font></font></span></div></div><div class="s-component-empty"><div class="overlay"><div class="center"><span><font><font>add pictures</font></font></span></div></div></div><span></span></div><span></span></div></div>`

and I try to get the top div using below macaca command-
`.elementById("navbar-top-button")
.click()`

the click() does not click the element.

**Comment by brucejcw** [comment]
@mpreethi90 .elementById("navbar-top-button") .click() worked on my side
