### ISSUE TITLE
inspector真机页面刷新还是waiting device wait，后台无错误日志

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#195]
- **Macaca Version**:
  1.1.2
- **Macaca Doctor**:
  macaca-doctor version: 1.0.19
  
  Node.js checklist:
  
  node env: /usr/local/bin/node
  node version: v4.5.0
  
  iOS checklist:
  
  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy
  
  Android checklist:
  
  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/opt/android-sdk`
  Platforms is set to `/usr/local/opt/android-sdk/platforms/android-24`
  Android tools is set to `/usr/local/opt/android-sdk/tools/android`
  ADB tool is set to `/usr/local/opt/android-sdk/platform-tools/adb`
  
  Installed driver list:
  
  android: 1.0.27
  chrome: 1.0.2
  electron: 1.1.2
  ios: 1.0.37
- **Operate System**:
  mac os
- **programming Language**:

inspector -u 3985a643cae34dadc6e97fba4f8bc93069a5ab8e --verbose
`>> request.js:23:12 [master] pid:2451 get remote update info failed.

> > server.js:16:12 [master] pid:2451 server start with config:
> >  { port: 5678,
> >   verbose: true,
> >   udid: '3985a643cae34dadc6e97fba4f8bc93069a5ab8e',
> >   ip: '172.16.250.12',
> >   host: 'codetosurvivemac.hitwh.edu.cn',
> >   loaded_time: '2016-09-18 10:36:49' }
> > inspector start at: http://172.16.250.12:5678
> > xctest-client.js:43:14 [master] pid:2451 project path: /Users/codetosurvivemac/npm/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.27@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > xctest-client.js:183:12 [master] pid:2451 xcode version: 8.0
> > WebDriverAgent version: 1.0.27
> > xctest-client.js:123:16 [master] pid:2451 ERROR: Could not start service com.apple.syslog_relay.
> > Could not start logger for udid 3985a643cae34dadc6e97fba4f8bc93069a5ab8e
> > 
> > xctest-client.js:156:14 [master] pid:2451 2016-09-18 10:36:50.659 xcodebuild[2455:31134]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/codetosurvivemac/Library/Developer/Xcode/DerivedData/WebDriverAgent-ascdzqctqtgkycfaawpdqwhhalcm/Logs/Test/4DFD1D5F-2B67-40CD-9AAF-EB85A088B745/Session-WebDriverAgentRunner-2016-09-18_103650-7QAsCd.log
> > 
> > xctest-client.js:156:14 [master] pid:2451 2016-09-18 10:36:50.660 xcodebuild[2455:31130] [MT] IDETestOperationsObserverDebug: (1EB2E66A-6657-43E0-8D8D-1E3C6DD98D53) Beginning test session WebDriverAgentRunner-1EB2E66A-6657-43E0-8D8D-1E3C6DD98D53 at 2016-09-18 10:36:50.659 with Xcode 8A218a on target <DVTiOSDevice: 0x7fae428bc910> {
> >         deviceSerialNumber:         FK4NRWLAG5QQ
> >         identifier:                 3985a643cae34dadc6e97fba4f8bc93069a5ab8e
> >         deviceClass:                iPhone
> >         deviceName:                 iPhone6 plus
> >         deviceIdentifier:           3985a643cae34dadc6e97fba4f8bc93069a5ab8e
> >         productVersion:             9.3.4
> >         buildVersion:               13G35
> >         deviceSoftwareVersion:      9.3.4 (13G35)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12402151424
> >         deviceAvailableCapacity:    10230353920
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7fae42930810 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:  
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (9.3.4 (13G35))
> > 
> > xctest-client.js:156:14 [master] pid:2451 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/480fdfa903cf9ba4de5ba7f36fe13f08/3985a643cae34dadc6e97fba4f8bc93069a5ab8e/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/codetosurvivemac/Library/Developer/Xcode/DerivedData/WebDriverAgent-ascdzqctqtgkycfaawpdqwhhalcm/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.1cvpCj/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.1cvpCj/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:2451 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.1cvpCj/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:2451 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.1cvpCj/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

  <-- GET /
  --> GET / 200`

手机上webdriver打开后黑屏后退出，页面waiting device start，后台无错误日志。

**Comment by xudafeng** [comment]
什么型号手机？
wifi开启了？
WebDriverAgentRunner装到手机中了？

**Comment by lixiaojiao** [comment]
@xudafeng iPhone 6 plus 手机跟电脑都属于同一WiFi网络  web driver agent driver也已经通过Xcode安装到手机中

**Comment by xudafeng** [comment]
@lixiaojiao 模拟器ok?

**Comment by xudafeng** [comment]
@lixiaojiao 蓝色log webdriveragent 版本多少？

**Comment by lixiaojiao** [comment]
@xudafeng  WebDriverAgent version: 1.0.27

**Comment by lixiaojiao** [comment]
@xudafeng iPhone 6s的模拟器是ok的

**Comment by xudafeng** [comment]
@lixiaojiao 那就奇怪了，找到WebDriverAgent工程目录，手动打开xcode，product-> test 运行一下runner，看报什么错

**Comment by lixiaojiao** [comment]
`2016-09-18 11:13:39.525 XCTRunner[529:259161] Running tests...
2016-09-18 11:13:40.673 XCTRunner[529:259161] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2016-09-18 11:13:41.395
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-09-18 11:13:41.398
Test Suite 'UITestingUITests' started at 2016-09-18 11:13:41.399
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2016-09-18 11:13:41.403
    t =     0.01s     Set Up
2016-09-18 11:13:41.414 XCTRunner[529:259161] Built at Sep 18 2016 11:13:29
2016-09-18 11:13:41.446 XCTRunner[529:259161] ServerURLHere->http://172.16.250.6:0<-ServerURLHere
2016-09-18 11:13:41.447 XCTRunner[529:259161] Listening on USB
`

**Comment by xudafeng** [comment]
```shell
http://172.16.250.6:0 
```
怎么会有这种url，应该是8100端口，你确定wifi开了？

**Comment by lixiaojiao** [comment]
@xudafeng 确实开了 是我们同事用电脑共享了一个网络  我电脑和手机都是连的这一个网络

**Comment by xudafeng** [comment]
@lixiaojiao 关掉系统防火墙试一下

**Comment by lixiaojiao** [comment]
@xudafeng 我防火墙是关闭的

**Comment by xudafeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1011681/18613248/05e61bee-7da9-11e6-956b-e38c62239078.png)
这里的勾选去掉，应该就会启动8100端口了

**Comment by lixiaojiao** [comment]
@xudafeng 这个页面是从哪里进去的呢？对xcode不太熟悉

**Comment by lixiaojiao** [comment]
中午把macaca-ios跟inspector重新安装了下 出现新的错误了
`2016-09-18 14:12:01.371 XCTRunner[259:10123] Running tests...
2016-09-18 14:12:01.461 XCTRunner[259:10123] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-09-18 14:12:01.461 XCTRunner[259:10123] (dlopen_preflight(/var/containers/Bundle/Application/C48031D6-0A9C-443C-ABCD-4A13A2B4B485/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/KissXML.framework/KissXML
  Referenced from: /private/var/containers/Bundle/Application/C48031D6-0A9C-443C-ABCD-4A13A2B4B485/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/C48031D6-0A9C-443C-ABCD-4A13A2B4B485/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML: mmap() error 1 at address=0x106844000, size=0x00010000 segment=__TEXT in Segment::map() mapping /private/var/containers/Bundle/Application/C48031D6-0A9C-443C-ABCD-4A13A2B4B485/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML)
`

**Comment by xudafeng** [comment]
@lixiaojiao 再重装 确保webdriveragent 1.0.28

然后看这篇文章https://testerhome.com/topics/5953

**Comment by lixiaojiao** [comment]
webdriveragent已经升级到1.0.28  
也按照https://testerhome.com/topics/5953将WebDriverAgentLib和WebDriverAgentRunner改为同一个 也已经按照你发的截图中将选中的对勾去掉 
 还是不行，换了另外一台设备也是不行，同样的问题
<-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200

**Comment by xudafeng** [comment]
@lixiaojiao 报错应该变了吧

**Comment by lixiaojiao** [comment]
上面的报错是没有了 但是又恢复到最初的问题了，下面是全部启动日志，也是没有错误信息
`lixiaojiaomac:tutorial lixiaojiao$ inspector -u 3985a643cae34dadc6e97fba4f8bc93069a5ab8e --verbose






>> request.js:23:12 [master] pid:11186 get remote update info failed.
>> server.js:16:12 [master] pid:11186 server start with config:
 { port: 5678,
  verbose: true,
  udid: '3985a643cae34dadc6e97fba4f8bc93069a5ab8e',
  ip: '172.16.250.12',
  host: 'lixiaojiaomac.hitwh.edu.cn',
  loaded_time: '2016-09-18 14:59:12' }
>> inspector start at: http://172.16.250.12:5678
>> xctest-client.js:43:14 [master] pid:11186 project path: /Users/lixiaojiao/npm/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.28@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:183:12 [master] pid:11186 xcode version: 8.0
>> WebDriverAgent version: 1.0.28

>> xctest-client.js:123:16 [master] pid:11186 ERROR: Could not start service com.apple.syslog_relay.
Could not start logger for udid 3985a643cae34dadc6e97fba4f8bc93069a5ab8e



>> xctest-client.js:156:14 [master] pid:11186 2016-09-18 14:59:13.616 xcodebuild[11190:92287]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/lixiaojiao/Library/Developer/Xcode/DerivedData/WebDriverAgent-ebyoubcdcykjqeamprogzcmgbvmc/Logs/Test/5B2DEC19-3B84-4852-9A3B-3C9F10587410/Session-WebDriverAgentRunner-2016-09-18_145913-dRYzcE.log

>> xctest-client.js:156:14 [master] pid:11186 2016-09-18 14:59:13.616 xcodebuild[11190:92281] [MT] IDETestOperationsObserverDebug: (9108C3A2-8676-4C53-A1EE-223064048B7D) Beginning test session WebDriverAgentRunner-9108C3A2-8676-4C53-A1EE-223064048B7D at 2016-09-18 14:59:13.615 with Xcode 8A218a on target <DVTiOSDevice: 0x7fee1e168f70> {
		deviceSerialNumber:         FK4NRWLAG5QQ
		identifier:                 3985a643cae34dadc6e97fba4f8bc93069a5ab8e
		deviceClass:                iPhone
		deviceName:                 iPhone6 plus
		deviceIdentifier:           3985a643cae34dadc6e97fba4f8bc93069a5ab8e
		productVersion:             9.3.4
		buildVersion:               13G35
		deviceSoftwareVersion:      9.3.4 (13G35)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12402151424
		deviceAvailableCapacity:    10367275008
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fee1de083d0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.4 (13G35))








>> xctest-client.js:156:14 [master] pid:11186 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/fa9a6738ee353b0a76a54c565433ea30/3985a643cae34dadc6e97fba4f8bc93069a5ab8e/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/lixiaojiao/Library/Developer/Xcode/DerivedData/WebDriverAgent-ebyoubcdcykjqeamprogzcmgbvmc/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.OGA0G3/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.OGA0G3/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:156:14 [master] pid:11186 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.OGA0G3/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:156:14 [master] pid:11186 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/0s/bccg6xrx6f31mql9grggj1mr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.OGA0G3/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

<-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /



`

**Comment by xudafeng** [comment]
xcode8？

**Comment by lixiaojiao** [comment]
@xudafeng 是的 上面跟你提到过 xcode版本是Version 8.0 (8A218a)

**Comment by xudafeng** [comment]
@lixiaojiao 要不你把手机升级ios10？

我这边没问题的

**Comment by lixiaojiao** [comment]
@xudafeng 我手头有一个ios10  也是同样的问题

**Comment by xudafeng** [comment]
orz，不知道原因了，手动8100启动wda吧，然后查问题，没辙了

**Comment by lixiaojiao** [comment]
@xudafeng 这条信息看不懂咧  具体怎么操作呢？我刚才又试了个ios10的 还是同样的问题

**Comment by xudafeng** [comment]
@CodeToSurvive1 wda 的 bundleId 你改过吗？

**Comment by CodeToSurvive1** [comment]
@xudafeng 改过呀 不改不是编译不成功吗

**Comment by xudafeng** [comment]
teamviewer有吗?

**Comment by CodeToSurvive1** [comment]
@xudafeng 个人免费帐号

**Comment by candialala** [comment]
@xudafeng 
xctest-client.js:156:14 [master] pid:20740 
Testing failed:
Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

xctest-client.js:156:14 [master] pid:20740 ** TEST FAILED **

xctest-client.js:164:14 [master] pid:20740 xctest client exit with code: 65, signal: null
相同的用例，9.3的真机可以执行。10系统的模拟器也可以执行。
已重装libimobiledevice ： brew reinstall libimobiledevice
已给webdriveragentrunner重签名：修改webdriveragentrunner Product Bundle Identifier
已添加WebDriverAgentLib和WebDriverAgentRunner两个targets的证书，选择一个team
方法都试过，还是不行。

**Comment by CodeToSurvive1** [comment]
@xudafeng 这个定位到问题原因了吗？能排除个人免费帐号的原因吗？

**Comment by xudafeng** [comment]
个人免费帐号是可以的

**Comment by xudafeng** [comment]
https://testerhome.com/topics/6314

**Comment by johnwanggithub** [comment]
same issue on Xcode 8.1 OSX:10.11.6, iOS: 10.1.1. @xudafeng .  Try Xcode->Product->Test, there is a  following error: Logic Testing on iOS devices is not supported. You can run logic tests on the Simulator.
see pictures.
![2016-12-05 04 31 18 pm](https://cloud.githubusercontent.com/assets/3618122/20878196/76beb078-bb08-11e6-9cd5-f78e836be903.png)
