### ISSUE TITLE
Java 怎么tap坐标？

### ISSUE THREAD

**Issue by hujiachun** [alibaba/macaca#198]
只看到这个方法

public void tap(JSONObject jsonObject) throws Exception {
        jsonObject.put("sessionId", driver.getSessionId());
        utils.request("POST", DriverCommand.TOUCH_CLICK, jsonObject);
    }
怎么去调用？

**Comment by xudafeng** [comment]
@hustzyd 有解决经验吗

**Comment by xudafeng** [comment]
关注这个issue https://github.com/alibaba/macaca/issues/366
