### ISSUE TITLE
重置App功能

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#199]
https://testerhome.com/topics/5961

**Comment by xudafeng** [comment]
默认重置

需要保留状态请使用reuse参数

https://macacajs.github.io/macaca/desired-caps.html

**Comment by BachWings** [comment]
这个desired-caps页面找不到了

**Comment by xudafeng** [comment]
@BachWings https://macacajs.github.io/zh/guide/helpful-settings.html#%E5%88%9D%E5%A7%8B%E5%8C%96%E5%8F%82%E6%95%B0
