### ISSUE TITLE
建议click或者对元素的其它操作，增加默认等待时间

### ISSUE THREAD

**Issue by hujiachun** [alibaba/macaca#200]
目前使用逻辑，如果没有出现click的对象，不报错直接执行下一步，其实上一步没出现执行下一步也是错的。
 建议，click或者对元素的其它操作，增加默认等待时间，如果没有出现click的对象，报错抛出异常，中断本次用例的执行

**Comment by xudafeng** [comment]
@hujiachun  waitfor 元素出现
