### ISSUE TITLE
How to get number of items that are populated dynamically in s listview?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#201]
I am using macaca for a reactnative project. I have a <ListView> where the list is generated dynamically from backend. I would like to know there is a way in macaca to get number of items in the list generated dynamically.

**Comment by brucejcw** [comment]
first: [app-inspector](https://macacajs.github.io/app-inspector/) to fetch `xpath`
then: using [elementsByXPath](http://macacajs.github.io/macaca-wd/#elementsByXPath) API
