### ISSUE TITLE
How do I call .click() on an element that is produced from an array?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#203]
This is my test script-
.elementsByClassName("s-nav-item")
            .then(function (sections) {
              for (var i = 0, len = sections.length; i < len; i++) {
                console.log("no of sections")

                if (i == 0) {
                  console.log("i=0")
                  chainedPromise = chainedPromise
                    .native()
                    .sections[i]
                    .click()
                  // .native()
                  // .elementByXPath('//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]')
                  // .click()
                }

                console.log("after")

              }
              chainedPromise
                .then(function () {
                  done()
                })

            })

**Comment by zenzhu** [comment]
You can return that promise.
```js
.elementsByClassName("s-nav-item")
.then(function (sections) {
  return sections[0].click();
})
```
You want click just one element of that array ? or click one by one ?
