### ISSUE TITLE
ios真机测试报错

### ISSUE THREAD

**Issue by hujiachun** [alibaba/macaca#204]
# macaca server --verbose

> responseHandler.js:11:12 [master] pid:45228 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"bundleId":"com.hujiachun.com","platformName":"iOS","udid":"ecab65eca01ae1d42874c26e645a33aee78296b6","deviceName":"iPhone 6","version":"9.3.2","autoAcceptAlerts":true}}
> 
> > session.js:47:10 [master] pid:45228 Creating session, sessionId: a320c5b9-beac-4452-b97b-52ec0612c4d8.
> > xctest-client.js:43:14 [master] pid:45228 project path: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.28@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:130:10 [master] pid:45228 {
> >     "bundleId": "com.hujiachun.com",
> >     "platformName": "iOS"
> > }
> > xctest-client.js:183:12 [master] pid:45228 xcode version: 7.3.1
> > WebDriverAgent version: 1.0.28
> > xctest-client.js:156:14 [master] pid:45228 2016-09-19 14:58:52.170 xcodebuild[45235:1278345] [MT] IDETestOperationsObserverDebug: (D8AD5EC2-8A8E-4DDC-8C29-1207376CF60E) Beginning test session D8AD5EC2-8A8E-4DDC-8C29-1207376CF60E with Xcode 7D1014 on target <DVTiOSDevice: 0x7f80be735fe0> {
> >         deviceSerialNumber:         FFMRJAR0G5MQ
> >         identifier:                 ecab65eca01ae1d42874c26e645a33aee78296b6
> >         deviceClass:                iPhone
> >         deviceName:                 iPhone 6
> >         deviceIdentifier:           ecab65eca01ae1d42874c26e645a33aee78296b6
> >         productVersion:             9.3.2
> >         buildVersion:               13F69
> >         deviceSoftwareVersion:      9.3.2 (13F69)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12756144128
> >         deviceAvailableCapacity:    378564608
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7f80be486140 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (9.3.2 (13F69))
> > 
> > xctest-client.js:156:14 [master] pid:45228 2016-09-19 14:58:52.172 xcodebuild[45235:1278378]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/hujiachun/Library/Developer/Xcode/DerivedData/WebDriverAgent-bagqeermmcadmcctywbyvbqewyeo/Logs/Test/73E0F75A-B48D-4717-8D97-AFAAB807F8AF/Session-2016-09-19_14:58:52-sNmfGq.log
> > 
> > xctest-client.js:156:14 [master] pid:45228 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/vj/v1jr__5d0853wc35vlvrjyk40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/8ad2a14507ff2ba9e072bc05b42f9634/ecab65eca01ae1d42874c26e645a33aee78296b6/webdriver-Runner.app
> > state->new_bundle: /Users/hujiachun/Library/Developer/Xcode/DerivedData/WebDriverAgent-bagqeermmcadmcctywbyvbqewyeo/Build/Products/Debug-iphoneos/webdriver-Runner.app
> > state->dst_bundle: /var/folders/vj/v1jr__5d0853wc35vlvrjyk40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/webdriver-Runner.app.dd7SAB/webdriver-Runner.app_sparse.ipa/Payload//webdriver-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/vj/v1jr__5d0853wc35vlvrjyk40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/webdriver-Runner.app.dd7SAB/webdriver-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:45228 __MDMDirectoryDiff_block_invoke37:1473 calling writeDictToFile with: /var/folders/vj/v1jr__5d0853wc35vlvrjyk40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/webdriver-Runner.app.dd7SAB/webdriver-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:45228 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/vj/v1jr__5d0853wc35vlvrjyk40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/webdriver-Runner.app.dd7SAB/webdriver-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > proxy.js:54:14 [master] pid:45228 Proxy: /session:POST to http://10.180.186.206:8100/session:POST with body: {"desiredCapabilities":{"bundleId":"com.hujiachun.com","platformName":"iOS"}}
> > proxy.js:58:18 [master] pid:45228 xctest client proxy error with: Error: connect ECONNREFUSED 10.180.186.206:8100
> > /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.4@xlogger/lib/xlogger.js:169
> >   throw new Error(res);
> >   ^

Error: >> proxy.js:58:18 [master] pid:45228 xctest client proxy error with: Error: connect ECONNREFUSED 10.180.186.206:8100
    at Logger.error (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.4@xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback](/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.19@xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.2.69.0@request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.2.69.0@request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by hujiachun** [comment]
模拟器可以， 包括真机app-inspector 都没问题

**Comment by hujiachun** [comment]
@xufafeng

**Comment by hujiachun** [comment]
@xudafeng 出现在概率挺大的，间断性出现

**Comment by CodeToSurvive1** [comment]
@xudafeng 我这出现的几率也很大  成功的情况很少

**Comment by CodeToSurvive1** [comment]
好吧 试了https://github.com/macacajs/macaca-cli/issues/51的方案  已经好了

**Comment by xudafeng** [comment]
请升级iOS驱动，参考https://testerhome.com/topics/6314
