### ISSUE TITLE
Error "Cannot set the selection end" is thrown for 'sendKeys()' to a contenteditable div

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#207]
* **Macaca Version**:

* **Macaca Doctor**:

* **Operate System**:

* **programming Language**:

**Comment by brucejcw** [comment]
please paste the code

**Comment by mpreethi90** [comment]
This is my element- 

`<div class="s-component-content needsclick recursive s-font-title cke_editable cke_editable_inline cke_contents_ltr" style="outline: 0px;" contenteditable="true" tabindex="0" spellcheck="true" role="textbox" aria-label="false"><p><font><font>Title-mob</font></font></p></div>`

and this is my test script-

`
         .elementByCssSelector('.slide:nth-child(1) .s-title .s-text .s-component-content')
.sendKeys('sample')

`

**Comment by brucejcw** [comment]
please paste the whole error log
