### ISSUE TITLE
click() does not work on image in webview

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#208]
Here is my element-
`<div class="s-component s-image"><div class="s-component-editor-wrapper"><div class="s-component-overlay" title=""><div class="center edit-button"><span><font><font>edit</font></font></span></div></div><span></span></div><span><div class="s-component-content"><div>
  **<img src="//7xpea4.com1.z0.glb.clouddn.com/images/448/FrE_02DDLD_CY1KRuQ-OxPn8v_wD.png?imageMogr2/strip/thumbnail/720x1440&gt;/quality/90!" alt="" title="" data-description="">**
</div></div></span></div>`

**Comment by brucejcw** [comment]
@mpreethi90 click does work on my side.  
Please format your code next time, and paste in parts:  
1. html code  
2. macaca test case
3. related full error log
