### ISSUE TITLE
for循环中如何操作元素

### ISSUE THREAD

**Issue by sunada** [alibaba/macaca#209]
Macaca Version:
1.1.3

Macaca Doctor:
Macaca Version:
1.1.2

Macaca Doctor:
Node.js checklist:
node env: D:\nodejs\node.exe
node version: v4.5.0
Android checklist:
JAVA version is 1.8.0_101
JAVA_HOME is set to D:\Program Files\Java\jdk1.8.0_101
ANDROID_HOME is set to D:\program_setup\android_sdk\sdk
Platforms is set to D:\program_setup\android_sdk\sdk\platforms\android-24
Android tools is set to D:\program_setup\android_sdk\sdk\tools\android.bat
ANT_HOME is set to D:\Program Files (x86)\apache-ant-1.9.4
Installed driver list:
android: 1.0.25

Operate System:
win7 64

programming Language: js

问题1：
it('#8 order', function(){
        return driver
            .elementsByXPath('//android.widget.ExpandableListView/android.widget.LinearLayout')
            .then(function(els){
                for(var el = 0; el < els.length; el++){
                    els[el].click().back();  //这里应该怎么表示对列表中的每个元素都进行这样的点击再返回操作呀？我这样写macaca报错... 求指教。
                }
            });
    })

**Comment by sunada** [comment]
els[el].click().back()   我运行了下，日志为：
recive: {"cmd":"click","args":{"elementId":"7"}}
{"cmd":"click","args":{"elementId":"9"}}
{"cmd":"click","args":{"elementId":"10"}}
{"cmd":"click","args":{"elementId":"12"}}
{"cmd":"click","args":{"elementId":"13"}}
{"cmd":"click","args":{"elementId":"11"}}

>>
  5 passing (1m)
  Error: read ECONNRESET
      at exports._errnoException (util.js:907:11)
      at TCP.onread (net.js:557:26)
Error: read ECONNRESET
      at exports._errnoException (util.js:907:11)
      at TCP.onread (net.js:557:26)
Error: read ECONNRESET
      at exports._errnoException (util.js:907:11)
      at TCP.onread (net.js:557:26)
Error: read ECONNRESET
      at exports._errnoException (util.js:907:11)
      at TCP.onread (net.js:557:26)
Error: read ECONNRESET
      at exports._errnoException (util.js:907:11)
      at TCP.onread (net.js:557:26)
Error: read ECONNRESET
      at exports._errnoException (util.js:907:11)
      at TCP.onread (net.js:557:26)

**Comment by zenzhu** [comment]
你这样写，顺序就乱了。els[el].click().back() 是一个 promise, 你得等第一个执行完了再执行第二个。
```
return els.reduce(function (prev, el) {
  return prev.then(function() {
    return el.click().back();
  }, Promise.resolve());
});
```

**Comment by sunada** [comment]
象这样么？错误提示： TypeError: prev.then is not a function。想了下木有想明白为啥错了……
it('#7.5 test loop', function(){
        return driver
            .elementsByXPath('//android.widget.ExpandableListView/android.widget.LinearLayout')
            .then(function(els){
               return els.reduce(function (prev, el) {
                   return prev.then(function() {
                       return el.click().click();
                   }, Promise.resolve());
               });
            });
    });

**Comment by sunada** [comment]
return els.reduce(function (prev, el) {
                    return prev.then(function() {
                        return el.click().click();
                    });
                }, Promise.resolve());
