### ISSUE TITLE
what is the purpose of driver.configureHttp() in the sample test you have given?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#211]

**Comment by xudafeng** [comment]
@mpreethi90 where?

**Comment by mpreethi90** [comment]
`  driver.configureHttp({
    timeout: 600000
  });`
in **macaca-mobile-sample.test.js**

**Comment by zenzhu** [comment]
It is the http timeout in ms.

**Comment by mpreethi90** [comment]
So, does that mean it is the timeout for http calls in the test suite? @xudafeng

**Comment by xudafeng** [comment]
@mpreethi90 this https://github.com/macacajs/macaca-test-sample/blob/master/macaca-test/macaca-mobile-sample.test.js#L38

**Comment by mpreethi90** [comment]
The timeout `  this.timeout(5 * 60 * 1000);` inside describe is the timeout for entire test suite right? How it is related to this `  driver.configureHttp({
    timeout: 600000
  });
`

**Comment by zenzhu** [comment]
`this.timeout(5 * 60 * 1000);` is the mocha timeout time for each test suite, not for entire test suite. https://mochajs.org/#timeouts

**Comment by mpreethi90** [comment]
thank you. Then how about `driver.configureHttp({ timeout: 600000 });` ?

**Comment by zenzhu** [comment]
It's the http timeout for each request.

**Comment by mpreethi90** [comment]
@zenzhu , when I don't set timeout for **describe()** in my macaca test, I get below error as soon as I start my test,

`Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test`

Does macaca has a default timeout of 2000ms ? and is it mandatory for us to write **this.timeout()** ??

**Comment by xudafeng** [comment]
@mpreethi90 https://github.com/xudafeng/autoresponsive-react/blob/master/macaca-test/example.test.js#L22
