### ISSUE TITLE
webview上elementByClassName无效

### ISSUE THREAD

**Issue by sunada** [alibaba/macaca#213]
Macaca Version:
1.1.3

Macaca Doctor:
Macaca Version:
1.1.3

Macaca Doctor:
Node.js checklist:
node env: D:\nodejs\node.exe
node version: v4.5.0
Android checklist:
JAVA version is 1.8.0_101
JAVA_HOME is set to D:\Program Files\Java\jdk1.8.0_101
ANDROID_HOME is set to D:\program_setup\android_sdk\sdk
Platforms is set to D:\program_setup\android_sdk\sdk\platforms\android-24
Android tools is set to D:\program_setup\android_sdk\sdk\tools\android.bat
ANT_HOME is set to D:\Program Files (x86)\apache-ant-1.9.4
Installed driver list:
android: 1.0.25

Operate System:
win7 64

programming Language: js

case:
it('#5.6 test webview', function(){
       return driver
           .elementsByClassName('android.widget.ImageView')
           .then(function(els){
               return els[0];
           })
           .click()
           .sleep(5000)
           .webview()
           .sleep(10000)
           .elementByClassName('more') 
           .tap();
});

日志：
recive: {"cmd":"find","args":{"strategy":"class name","selector":"android.widget
.ImageView","multiple":true}}

return: {"success":true,"data":[{"ELEMENT":"3"},{"ELEMENT":"4"},{"ELEMENT":"5"},
{"ELEMENT":"6"}]}

recive: {"cmd":"click","args":{"elementId":"3"}}

return: {"success":true,"data":true}

> > chromedriver bin path: D:\nodejs\node-global\node_modules.macaca-android_npm
> > install\node_modules.1.0.17@macaca-chromedriver\exec\chromedriver.exe
> > kill all chromedriver process success!
> > Starting ChromeDriver 2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067)
> > on port 9515
> > Only local connections are allowed.
> > 
> > chromedriver starting success.
> > chromedriver ready with: {"sessionId":null,"status":0,"value":{"acceptSslCert
> > s":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browse
> > rName":"chrome","chrome":{},"cssSelectorsEnabled":true,"databaseEnabled":false,"
> > handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationCont
> > extEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"platform":"
> > ANDROID","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"vers
> > ion":"45.0.2454.95","webStorageEnabled":true}}
> > 
> > ```
> > 1) #5.6 test webview
> > ```

问题：
由native跳转到webview后，通过.elementByClassName('more')无法定位元素。在webview上现在支持通过classname来定位吧？我看日志里，也看不出来是哪里出了问题。日志里，chromedriver中，未打印操作及结果日志，无法定位原因。不知道可以怎么查原因呢？

**Comment by brucejcw** [comment]
你用的[webdriver-client](https://www.npmjs.com/package/webdriver-client)吧,  `.native().elementByClassName('more')`

**Comment by sunada** [comment]
改为用.native().elementByClassName('more')后，日志提示：
recive: {"cmd":"find","args":{"strategy":"class name","selector":"more","multipl
e":false}}
ignored selector
return: {"success":true}

1. 什么情况下会ignored selector呢？
2. webview()这个在什么情况下呀？我看示例case里用，我在本地也能跑通。

**Comment by xudafeng** [comment]
@kobe990

**Comment by LynneXu** [comment]
先不要.webview()，.contexts()看下log。

示例case里的webview()是针对示例app包装过的，实际上是要获取context。
