### ISSUE TITLE
求助！ windows环境macaca一直无法成功连接android模拟器和真机

### ISSUE THREAD

**Issue by githublue** [alibaba/macaca#214]
**问题：**
解决了sdk文件路径空格问题后，又有下面两个问题，快疯了！

1. windows环境下，adb命令的路径名称为啥有正反两个斜杠：D:\AndroidSDK\Android\android-sdk/platform-tools/adb？
2. 日志错误信息显示需要将一个文件push进设备里，然而进到实际安装文件夹下找C:\Users\Administrator\node_modules\.1.0.19@uiautomator-client\bin\uiautomator-bootstrap.jar， 这个包不存在啊， bin文件夹也不存在啊！ 什么东西没安装成功吗？

**安装信息如下：**

  macaca-doctor version: 1.0.19

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v6.2.0

  Android checklist:

  JAVA version is `1.7.0_67`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.7.0_67`
  ANDROID_HOME is set to `D:\AndroidSDK\Android\android-sdk`
  Platforms is set to `D:\AndroidSDK\Android\android-sdk\platforms\android-24`
  Android tools is set to `D:\AndroidSDK\Android\android-sdk\tools\android.bat`
  ADB tool is set to `D:\AndroidSDK\Android\android-sdk\platform-tools\adb.exe`
  ANT_HOME is set to `C:\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.28
  chrome: 1.0.2
  ios: 1.0.37

**日志信息如下：**

>> index.js:17:12 [master] pid:24760 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '172.25.127.1',
  host: 'honest-pc',
  loaded_time: '2016-09-21 15:51:55' }
>> middlewares.js:17:10 [master] pid:24760 base middlewares attached
>> router.js:108:10 [master] pid:24760 router set
>> webdriver sdk launched
>> 

>> 

>> macaca mobile sample

>> responseHandler.js:11:12 [master] pid:24760 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"Android","app":"D:\\macaca-test-sample\\app\\android-app-bootstrap.zip","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:24760 Creating session, sessionId: c4efd71f-b3a8-4229-a149-087419df0006.
>> helper.js:194:12 [master] pid:24760 Unzipping local app form D:\macaca-test-sample\app\android-app-bootstrap.zip
>> responseHandler.js:50:12 [master] pid:24760 Send Error Respone to Client: Error: Command failed: **D:\AndroidSDK\Android\android-sdk/platform-tools/adb** -s da36cc17 push **C:\Users\Administrator\node_modules\.1.0.19@uiautomator-client\bin\uiautomator-bootstrap.jar** /data/local/tmp

>> responseHandler.js:56:14 [master] pid:24760 Error: Command failed: **D:\AndroidSDK\Android\android-sdk/platform-tools/adb** -s da36cc17 push **C:\Users\Administrator\node_modules\.1.0.19@uiautomator-client\bin\uiautomator-bootstrap.jar** /data/local/tmp

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
>>

**Comment by xudafeng** [comment]
adb devices?

**Comment by githublue** [comment]
List of devices attached
da36cc17	device

**Comment by xudafeng** [comment]
删除 D:\AndroidSDK\Android\android-sdk\platforms\android-24 这个目录，重装 macaca-android

**Comment by githublue** [comment]
我这个这个目录删了，执行cnpm i macaca-android --save，报找不到Platforms的错误；
然后我把这个目录从回收站恢复，再把node_modules\.1.0.29@macaca-android删了，报Ant编译错误。
.1.0.29@macaca-android这个目录不删的话，cnpm装不上去，显示该模块已存在

**Comment by githublue** [comment]
还有.1.0.19@uiautomator-client 这个模块需要编译吗？ 为啥\bin\uiautomator-bootstrap.jar这个包不存在呢

**Comment by githublue** [comment]
明天找一台新机器再试一遍，先装好sdk，再装macaca-android，就是不知道uiautomator-bootstrap.jar是在哪一步产生的

**Comment by xudafeng** [comment]
删了，装18到23，看faq

**Comment by githublue** [comment]
sdk换过了，macaca-android驱动安装不成功，显示ant编译错误信息。
只能说，windows环境安装过程坑太多，安装工具之间的依赖性太强，稍有一步走错，满盘over！
还有安装尽量用npm命令，不要使用cnpm，编译出来的信息不太一样，其他的就不说了！

**Comment by xudafeng** [comment]
ant 错误太罕见了，ant home设置对了吗

**Comment by githublue** [comment]
可以的！错误信息是：D:\AndroidSdk\android-sdk-windows\tools\ant\build.xml文件中538行：
minSdkVersionOut="project.minSdkVersion"

**Comment by githublue** [comment]
ANT_HOME     D:\apache-ant-1.9.7

**Comment by githublue** [comment]
不用apache的ant，android有自带的ant吗？
