### ISSUE TITLE
How do I configure macaca  to use Babel compiler to use ES6 module?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#215]
In Mocha, after installing necessary Babel stuffs, we use "**mocha --compilers js:babel-core/register**" to tell mocha to use Babel compiler. In the same way, how do I configure in Macaca?
Kindly assist

**Comment by brucejcw** [comment]
es6 is supported by [node v6.x](http://node.green/)

**Comment by brucejcw** [comment]
@mpreethi90 It would be convenient if you share your git repository to us, so we can help you and know what's going on
