### ISSUE TITLE
急需macaca reportor  Java版

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#216]
目前已部署好本司自己的 java版本的 macaca server 和jenkins的初步集成.
目前已经可以通过jenkins  运行macaca java脚本的  但是日志是mvn test的日志输出
很不方便可视化查看,希望能做成类ant可配置模板型的输出统计报告.

![image](https://cloud.githubusercontent.com/assets/18392901/18736105/767b5e7c-80b6-11e6-88b6-623eb7bc3218.png)

已经尝试过Node.js版本的用法，但无法与Java集成，https://testerhome.com/topics/5998

**Comment by xudafeng** [comment]
http://stackoverflow.com/questions/2385553/how-can-i-generate-an-html-report-for-junit-results

**Comment by zenzhu** [comment]
https://maven.apache.org/surefire/maven-surefire-report-plugin/

**Comment by Archer456** [comment]
这个 我知道啊   mvn test 的输出日志 是存在这的 
![image](https://cloud.githubusercontent.com/assets/18392901/18736586/05e4a678-80bb-11e6-90a3-38837ab50f7b.png)

难道 是让自己定制 配置 maven-surefire-report ？

 不能 你们做个结合macaca java模板啥的吗 ,具体深度结合本项目macaca java的特色,类似ant 报告转义html日志汇总报告啥的么.

**Comment by Archer456** [comment]
http://www.cnblogs.com/weiweiyao/p/4250954.html

是这样自己弄不

最好 能做个带命令行参数的 macaca java reportor定制功能的命令  帮助配置转html

**Comment by xudafeng** [comment]
@supern 配过jenkins
