### ISSUE TITLE
wd更新到0.1.3，还是不支持swipe，python是3.5.2版本

### ISSUE THREAD

**Issue by Amoyehng** [alibaba/macaca#218]
- **Macaca Version** :1.1.3
- **Macaca Doctor Logs**:
- **Operate System**: win8
- **Programming Language**: python3.5.2

![image](https://cloud.githubusercontent.com/assets/22318489/18741029/874348d6-80df-11e6-9fdf-4248576db57f.png)

![image](https://cloud.githubusercontent.com/assets/22318489/18741071/bc825352-80df-11e6-9d30-670073fa4d76.png)

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/217

**Comment by zenzhu** [comment]
贴一下命令行的报错

**Comment by zenzhu** [comment]
你命令行的 wd 版本对吗，我在 win 上也装了一次，也没问题
在命令行里面输入
```
import pkg_resources
pkg_resources.get_distribution('wd')
```

**Comment by Amoyehng** [comment]
是对的呀，版本
![image](https://cloud.githubusercontent.com/assets/22318489/18742426/c53d4400-80e6-11e6-9209-eb95086721e8.png)

**Comment by zenzhu** [comment]
不是这个 是你命令行里面和 pip 是一样的吗 那个比较准

**Comment by Amoyehng** [comment]
已经可以了，谢谢各位大大的技术支持哈
