### ISSUE TITLE
wd.java，查找元素失败后，不再继续支持后续的测试脚本，此时会执行下一个方法删除脚本。

### ISSUE THREAD

**Issue by adfghzhang** [alibaba/macaca#220]
wd.java，查找元素失败后，不再继续支持后续的测试脚本，此时会执行下一个方法删除脚本。
希望改进wd.java的机制支持元素查找失败可判定，并能继续执行后续脚本

* **Macaca Version**:
1.1.3
* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.19

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v4.4.1

  Android checklist:

  JAVA version is `1.8.0_92`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_92`
  ANDROID_HOME is set to `D:\android-sdk`
  Platforms is set to `D:\android-sdk\platforms\android-23`
  Android tools is set to `D:\android-sdk\tools\android.bat`
  ADB tool is set to `D:\android-sdk\platform-tools\adb.exe`
  ANT_HOME is set to `D:\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.29
  electron: 1.1.4
* **Operate System**:
Windows 7
* **Programming Language**:
Java
 
	@Test
	public void test_case_1() throws Exception {
		System.out.println("*****"+driver.elementById("cn.cstonline.kartor3:id/alert_dialog_left_btn"));
		System.out.println("*****"+driver.elementById("cn.cstonline.kartor3:id/header_left_icon").getAttribute("name"));
	}
	
	@Test
	public void test_case_2() throws Exception {
		System.out.println("*****"+driver.elementById("cn.cstonline.kartor3:id/alert_dialog_right_btn"));
		System.out.println("*****"+driver.elementById("cn.cstonline.kartor3:id/header_left_icon").getAttribute("name"));
	}
	
	
	@AfterClass
	public void tearDown() throws Exception {
		driver.quit();
	}
>> responseHandler.js:11:12 [master] pid:6276 Recieve HTTP Request from Client:
method: POST url: /wd/hub/session/18235e79-f575-4bea-b5fb-654850c935a1/element,
jsonBody: {"using":"id","value":"cn.cstonline.kartor3:id/alert_dialog_left_btn"}

recive: {"cmd":"find","args":{"strategy":"id","selector":"cn.cstonline.kartor3:i
d/alert_dialog_left_btn","multiple":false}}

ignored selector

>> responseHandler.js:19:14 [master] pid:6276 Send HTTP Respone to Client: 404 N
ot Found
return: {"success":true}

>> responseHandler.js:11:12 [master] pid:6276 Recieve HTTP Request from Client:
method: POST url: /wd/hub/session/18235e79-f575-4bea-b5fb-654850c935a1/element,
jsonBody: {"using":"id","value":"cn.cstonline.kartor3:id/alert_dialog_right_btn"
}
recive: {"cmd":"find","args":{"strategy":"id","selector":"cn.cstonline.kartor3:i
d/alert_dialog_right_btn","multiple":false}}

ignored selector

return: {"success":true}

>> responseHandler.js:19:14 [master] pid:6276 Send HTTP Respone to Client: 404 N
ot Found
>> responseHandler.js:11:12 [master] pid:6276 Recieve HTTP Request from Client:
method: DELETE url: /wd/hub/session/18235e79-f575-4bea-b5fb-654850c935a1, jsonBo
dy: {}
>> session.js:80:12 [master] pid:6276 Delete session, sessionId: 18235e79-f575-4
bea-b5fb-654850c935a1
>> responseHandler.js:43:14 [master] pid:6276 Send HTTP Respone to Client: {"ses
sionId":"18235e79-f575-4bea-b5fb-654850c935a1","status":0}

**Comment by xudafeng** [comment]
升级wd.java 到1.0.17
