### ISSUE TITLE
下拉的动作在JS里怎么实现？

### ISSUE THREAD

**Issue by smoothdvd** [alibaba/macaca#222]

**Comment by xudafeng** [comment]
Android or iOS ?

**Comment by smoothdvd** [comment]
@xudafeng Android

**Comment by xudafeng** [comment]
swipe

**Comment by smoothdvd** [comment]
like this: .elementxxxx.swipe(x1, y1, x2, y2, duration)?

**Comment by xudafeng** [comment]
@smoothdvd sure

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-test-sample/blob/master/macaca-test/macaca-mobile-sample.test.js#L98

**Comment by smoothdvd** [comment]
@xudafeng Thanks
