### ISSUE TITLE
应用不能用过ipa文件启动吗？

### ISSUE THREAD

**Issue by CommanderXL** [alibaba/macaca#226]
log: 

[init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"/Users/didi/demo/macaca/macaca-test-sample/app/DidDriver.ipa"})] The environment you requested was unavailable.

请问模拟器不能启动ios打包后的ipa应用吗？

**Comment by xudafeng** [comment]
@CommanderXL 真机？

**Comment by CommanderXL** [comment]
@xudafeng  不是。昨天我和IOS开发的同学要了一个我们app打包好的包，包的格式是ipa，我想通过macaca去测试app里面的h5页面，但是启动不起来。我看示例给的app文件是zip。请问我应该让ios的同学给我什么样的包呢？

**Comment by xudafeng** [comment]
要app格式的包，或者手动build进去bundleId启动，只要装进去就可以了

**Comment by CommanderXL** [comment]
@xudafeng 你好。现在包是app格式的，并且在模拟器可以看到app了。但是在模拟器中打开app时就秒退了- - 。试了很多次都这样。暂时还不清楚是什么原因造成的

**Comment by xudafeng** [comment]
选debug 而不是release，schema选择test可运行

**Comment by CommanderXL** [comment]
@xudafeng 额，请问这个是macaca启动的时候输入的命令行需要配置的参数？还是模拟器需要改变的参数？

又去看了下文档没有发现相关的内容，不太清楚你说的这个解决方案怎么去做。

这个是我现在的命令，不过里面的app路径是我需要测试的路径：
browser=safari macaca run  -d ./macaca-test/macaca-mobile-sample.test.js

**Comment by xudafeng** [comment]
文档找
