### ISSUE TITLE
Is there a way macaca reports when app quits/crashes during test run in iOS/android?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#234]
I use macaca for automating a ReactNative project. When the test runs and if any crash happens on tapping on an element, macaca still tries to move forward with test script and fails the test. But, I wanted to check if there is any way that macaca can listen if app quits/crashes inbetween test execution?

**Comment by CrazyInAppium** [comment]
Same problem With @mpreethi90

**Comment by xudafeng** [comment]
update dirver
