### ISSUE TITLE
macaca提取公共资源后,运行时报" Selenium error: A session is either terminated or not started"

### ISSUE THREAD

**Issue by haochuang** [alibaba/macaca#236]
* **Macaca Version**: 1.1.0

* **Macaca Doctor Logs**:
```
E:\Ubuntu\macaca\autotest-macaca\macaca-test\desktop>macaca doctor

  Node.js checklist:

  node env: C:\Program\nodejs\node.exe
  node version: v6.6.0

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `C:\Program\JAVA\jdk1.8.0_91`
  ANDROID_HOME is set to `E:\CodeSpace\ANDROID\android-sdk-windows`
  Platforms is set to `E:\CodeSpace\ANDROID\android-sdk-windows\platforms\android-24`
  Android tools is set to `E:\CodeSpace\ANDROID\android-sdk-windows\tools\android.bat`
  ANT_HOME is set to `C:\Program\ANT\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.26
  chrome: 1.0.1
  electron: 1.1.4
  ios: 1.0.36


(node:5588) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
```

* **Operate System**:Win10 x86_64

* **Chrome 版本**: 53.0.2785.116 m

* **Programming Language**:

问题描述：
将测试代码结构化时候，把公共资源抽取到common，将用到的依赖抽取到utils，将写在BeforeEach中的项（比如baseUrl、timeout、windowContentSize、init等）提取到common中去，结果在执行的时候，会报"Error response status: 6,  Selenium error: A session is either terminated or not started"。
当前的macaca版本是不是暂不支持这样操作呢？

**Comment by zenzhu** [comment]
不影响函数调用的顺序的操作肯定不会影响的，这样肯定是某些调用顺序变了啊。

**Comment by xudafeng** [comment]
https://testerhome.com/topics/4523

**Comment by AllocAndInit** [comment]
@zenzhu @xudafeng @haochuang  对于同一个测试用例，我只想在 不同的设备进行测试，然后只把测试用例里面 desiredCap 的 udid 改变了，然后同样的操作也是会报相同的错误，请问这是什么原因了？
