### ISSUE TITLE
when I get the current text vlaue of the input element , the fucntion return ''

### ISSUE THREAD

**Issue by haochuang** [alibaba/macaca#237]
- **Macaca Version**: 1.1.0
- **Macaca Doctor Logs**:

```
E:\Ubuntu\macaca\autotest-macaca\macaca-test\desktop>macaca doctor

  Node.js checklist:

  node env: C:\Program\nodejs\node.exe
  node version: v6.6.0

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `C:\Program\JAVA\jdk1.8.0_91`
  ANDROID_HOME is set to `E:\CodeSpace\ANDROID\android-sdk-windows`
  Platforms is set to `E:\CodeSpace\ANDROID\android-sdk-windows\platforms\android-24`
  Android tools is set to `E:\CodeSpace\ANDROID\android-sdk-windows\tools\android.bat`
  ANT_HOME is set to `C:\Program\ANT\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.26
  chrome: 1.0.1
  electron: 1.1.4
  ios: 1.0.36


(node:5588) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
```
- **Operate System**:Win10 x86_64
- **Chrome 版本**: 53.0.2785.116 m
- **Programming Language**:

问题描述：

1.测试目的：希望获取到某个文本框的值，在修改之后，再获取一次，并进行值修改后的校验；
2.通过 .elementByCss('[placeholder="昵称"]')  获取到元素后，使用过如下几种方法进行值得校验和断言，结果都没成功；
      // .text()
      // .currentContext()
      // .textPresent('测试的输入值')
      // .getProperty('input')
预期结果：可以调用成功，并进行断言；
实际结果：
.getProperty('input')  返回：
AssertionError: expected '' to be true

.textPresent() 返回：
 Error: [element.getProperty("input")] Not JSON response。

![image](https://cloud.githubusercontent.com/assets/6335539/18940280/50c016ea-8639-11e6-8f97-a1cda251530b.png)

**Comment by zenzhu** [comment]
.text() 没返回？

**Comment by haochuang** [comment]
```
      .elementByCss('[placeholder="昵称"]')
      .text()
      .then(function(hasHeadWrapper){
        hasHeadWrapper.should.be.true()
      })
```
返回信息如下：
`AssertionError: expected '' to be true`

**Comment by zenzhu** [comment]
没有值确实不是true啊。还是说你之前有值，text 没有读取出来？

**Comment by haochuang** [comment]
是有值的，但调用text()没有收到

**Comment by zenzhu** [comment]
这样呢
```
.elementByCss('[placeholder="昵称"]')
.getAttribute('value')
```
