### ISSUE TITLE
AlertView 无效

### ISSUE THREAD

**Issue by TediWang** [alibaba/macaca#24]
IOS的AlertView弹出后，希望通过脚本去点击。
使用elementByXPath和Name都无法生效。

**Comment by zenzhu** [comment]
@TediWang iOS 下可以直接用 acceptAlert 或者 dismissAlert 来选择接受或者忽视 Alert，不用去查找元素，如果嫌麻烦，并且 Alert 不是功能性的（比如你是通过 Alert 来选择)，可以在配置中就设置 autoAcceptAlerts: true。

**Comment by zenzhu** [comment]
@TediWang 如果设置了 autoAcceptAlerts 还是没有用，你可以把 macaca server 的日志发出来看一下，grep '/wd/hub/session/temp/accept_alert' xxx.txt -C10，xxx.txt 是日志文件。

**Comment by TediWang** [comment]
Proxy: /wd/hub/session/temp/accept_alert:POST to http://10.32.24.19:8100/session/BD46D161-F35A-45D0-A273-1F774A36D42D/accept_alert:POST with body: {}
>> Got response with status 200: {"value":"Unhandled endpoint: /session/BD46D161-F35A-45D0-A273-1F774A36D42D/accept_alert -- http://10.32.24.19:8100/ with parameters {\n    wildcards =     (\n        \"session/BD46D161-F35A-45D0-A...

**Comment by TediWang** [comment]
@zenzhu : 日志如下
Proxy: /wd/hub/session/temp/accept_alert:POST to http://10.32.24.19:8100/session/BD46D161-F35A-45D0-A273-1F774A36D42D/accept_alert:POST with body: {}
Got response with status 200: {"value":"Unhandled endpoint: /session/BD46D161-F35A-45D0-A273-1F774A36D42D/accept_alert -- http://10.32.24.19:8100/ with parameters {\n    wildcards =     (\n        \"session/BD46D161-F35A-45D0-A...

**Comment by TediWang** [comment]
大概的可能和连续2次弹窗有关：
如果连续2次弹窗，一个是定位授权，一个是通知授权。不管是手动调用还是自动aceept设置，都只能点掉一个，另一个点不掉。循环10次也是一样。

**Comment by zenzhu** [comment]
https://github.com/xudafeng/webdriveragent/commit/d953f77cc4e63e86047e143940c87d34904e0464

**Comment by TediWang** [comment]
更新后已解决，赞！
