### ISSUE TITLE
macaca android setText无法输入纯英文

### ISSUE THREAD

**Issue by yaniswang** [alibaba/macaca#240]
![image](https://cloud.githubusercontent.com/assets/970390/19209519/59a5a0fc-8d3e-11e6-8a93-ac32a8dcf0c2.png)

在输入框上输入纯英文，会出现输入失败的问题（并不是100%无法成功，成功机率比较低）。

经测试，纯数字，或者与数字混合，均正常。

重现方法：

https://github.com/macacajs/macaca-test-sample/blob/master/macaca-test/macaca-mobile-sample.test.js#L63

改为：

```
  .login('a', 'b')
```

**Comment by kobe990** [comment]
官方用例apk的密码框应该是使用了native的密码控件，只能输入数字，此时及时唤起物理键盘也是只能输入数字的
