### ISSUE TITLE
macaca python示例的quit函数报错

### ISSUE THREAD

**Issue by etiaxie** [alibaba/macaca#242]
例子执行到cls.driver.quit()会报异常
this.chromedriver.killAll is not a function
[bb.txt](https://github.com/alibaba/macaca/files/517540/bb.txt)

**Comment by zenzhu** [comment]
这个 api 应该已经不用了，不知道为什么还会调用到，你更新一下 npm i -g macaca-android

**Comment by etiaxie** [comment]
更新了 还是一样的错误
而且官网上python的示例中没有调用Android 只是驱动Desktop的chrome浏览器

**Comment by zenzhu** [comment]
好的，应该是 chrome 驱动还没有修改，我去 fix 一下，谢谢反馈。

**Comment by zenzhu** [comment]
npm i -g macaca-chrome 更新一下就好了。

**Comment by etiaxie** [comment]
好了
