### ISSUE TITLE
wd.java版saveScreenshot方法 应该默认替换覆盖同名截图或截图文件名自追加时间后缀

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#243]
driver.takeScreenshot()
	          .saveScreenshot("/home/cmd/macaca/Screenshot/H5Mobile.png");

发现没发现  那个截图 如果路径下有同名称的 上一次跑通的截图
本次执行 并不会覆盖替换 还是上次的截图,查看截图文件的时间属性看出来的,修改 访问 新建时间等
删掉 再跑 才会有本次执行的最新截图  这应该是有问题的 应该默认替换覆盖？

期望 默认替换覆盖同名截图 或者 期望同名截图自增长后缀比如_1 _2 或者带截图时间后缀

**Comment by kobe990** [comment]
截图文件是通过java OutputStream写入的，应该是会覆盖的，我实际跑了几把也覆盖了哦，你可以尝试将截图代码放在另一个界面的显示逻辑里，文件名不变，可能更容易看出来@Archer456

**Comment by Archer456** [comment]
![image](https://cloud.githubusercontent.com/assets/18392901/19255825/388ab1ac-8f94-11e6-8c5a-ec02cedda81e.png)
关闭吧  看修改时间是有新生成的  不明白为什么 我删除掉H5Web截图  再重新跑脚本
重新生成的图 日期和创建日期是删除前的时间  只有看修改时间看出来是刚刚修改生成的。

**Comment by xudafeng** [comment]
@Archer456 你有权限close哦
