### ISSUE TITLE
运行用例,Error: Cannot find test framework "mocha" in node_modules

### ISSUE THREAD

**Issue by 709108584** [alibaba/macaca#244]
- **Macaca Version**:
  1.0.21
- **Macaca Doctor Logs**:
  mini:~ marlin$ macaca doctor
  
  macaca-doctor version: 1.0.21
  
  Node.js checklist:
  
  node env: /usr/local/bin/node
  node version: v4.6.0
  
  iOS checklist:
  
  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2339.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy
  
  Android checklist:
  
  JAVA version is `1.8.0_101`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  
  Installed driver list:
  
  ios: 1.0.38

mini:~ marlin$ cd /Users/marlin/Desktop/macaca-test-sample-master/macaca-test
mini:macaca-test marlin$ macaca run -d macaca-mobile-sample.test.js

> > webdriver sdk launched
> > /usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.1.1.5@macaca-cli/lib/run/index.js:44
> >       throw err;
> >       ^

Error: Cannot find test framework "mocha" in node_modules
    at Runner.startServer.Runner.initFramework.testProcess.stdout.on.testProcess.stderr.on.testProcess.on [as initFramework](/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.1.1.5@macaca-cli/lib/run/index.js:58:11)
    at /usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.1.1.5@macaca-cli/lib/run/index.js:41:10
    at process._tickCallback (node.js:369:9)

mini:macaca-test marlin$ \* **Operate System**:
mac
- **Programming Language**:

**Comment by xudafeng** [comment]
macaca doctor 贴一下

**Comment by 709108584** [comment]
@xudafeng

**Comment by xudafeng** [comment]
macaca doctor log 贴一下

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/247

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/445

**Comment by ElesG** [comment]
遇到了同样的问题，详细log在这：https://github.com/macaca-sample/mobile-app-sample-nodejs/issues/3

**Comment by xudafeng** [comment]
@ElesG 安装一下mocha https://macacajs.github.io/zh/nodejs

**Comment by ElesG** [comment]
安装过了，但是看日志他提示的是我工程文件里没有找到mocha  @xudafeng

**Comment by xudafeng** [comment]
看能npm文档
