### ISSUE TITLE
native中H5页面无法唤起input[type="file"]的手机控件

### ISSUE THREAD

**Issue by CommanderXL** [alibaba/macaca#245]
* **Macaca Version**:

    1.1.4

* **Macaca Doctor Logs**:

```
  macaca-doctor version: 1.0.20


  Node.js checklist:

  node env: /Users/didi/.nvm/versions/node/v4.4.0/bin/node
  node version: v4.4.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.6.0_65`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

  android: 1.0.29
  ios: 1.0.37
```

* **Operate System**:

Darwin localhost 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

* **Programming Language**:

javascript

想实现IOS端内H5页面上传图片，当前的实现思路是：

* 模拟用户点击`input[type="file"]`
* 然后就使用`XPath`进行`native`中一系列操作，来选中图片

现在遇到的问题就是，模拟用户点击`input[type="file"]`时，没法唤起端内原生的选择图片的控件，除非手动点击才能唤起。

**Comment by xudafeng** [comment]
```
input[type="file"]
```

有安全限制，只有用户操作才可以，不允许自动化，请想办法绕过或者暴露触发脚本
