### ISSUE TITLE
devtool  REPL调试问题

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#246]
D:\macaca\macaca-test-sample-master>npm i devtool -g
npm WARN deprecated electron-prebuilt@1.3.3: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron
D:\nodejs\node-global\devtool -> D:\nodejs\node-global\node_modules\devtool\bin\index.js
- async@1.5.2 node_modules\devtool\node_modules\async
- spdx-exceptions@1.0.5 node_modules\devtool\node_modules\spdx-exceptions
  D:\nodejs\node-global
  `-- devtool@2.2.0
  +-- chokidar@1.6.0
  | +-- anymatch@1.3.0
  | |`-- micromatch@2.3.11
  | |   `-- object.omit@2.0.0
  | |`-- for-own@0.1.4
  | |       `-- for-in@0.1.6
  | +-- async-each@1.0.1
  | +-- inherits@2.0.3
  | +-- is-binary-path@1.0.1
  | |`-- binary-extensions@1.7.0
  | +-- path-is-absolute@1.0.1
  | `-- readdirp@2.1.0
  |   +-- graceful-fs@4.1.9
  |`-- readable-stream@2.1.5
  +-- concat-stream@1.5.2
  +-- electron-prebuilt@1.3.3
  | `-- electron-download@2.2.1
  |   +-- mv@2.1.1
  |   |`-- rimraf@2.4.5
  |   |   `-- glob@6.0.4
  |   |`-- once@1.4.0
  |   `-- nugget@1.6.2
  |     +-- pretty-bytes@1.0.4
  |     |`-- meow@3.7.0
  |     |   +-- loud-rejection@1.6.0
  |     |   | +-- currently-unhandled@0.4.1
  |     |   | | `-- array-find-index@1.0.2
  |     |   |`-- signal-exit@3.0.1
  |     |   +-- normalize-package-data@2.3.5
  |     |   | `-- validate-npm-package-license@3.0.1
  |     |   |`-- spdx-expression-parse@1.0.4
  |     |   `-- redent@1.0.0
  |     |`-- indent-string@2.1.0
  |     |       `-- repeating@2.0.1
  |     |`-- is-finite@1.0.2
  |     |           `-- number-is-nan@1.0.1
  |`-- request@2.75.0
  |       +-- form-data@2.0.0
  |       | `-- asynckit@0.4.0
  |       +-- har-validator@2.0.6
  |       |`-- is-my-json-valid@2.15.0
  |       |   `-- jsonpointer@4.0.0
  |       +-- http-signature@1.1.1
  |       | +-- jsprim@1.3.1
  |       | |`-- json-schema@0.2.3
  |       | `-- sshpk@1.10.1
  |       |   +-- bcrypt-pbkdf@1.0.0
  |       |`-- tweetnacl@0.14.3
  |       `-- mime-types@2.1.12
  |`-- mime-db@1.24.0
  `-- mock-stdin@0.3.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\devtool\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

D:\macaca\macaca-test-sample-master>devtool -v

devtool 2.2.0
electron 1.3.3
node 6.3.0
chrome 52.0.2743.82

且已装
D:\macaca\macaca-test-sample-master>npm i webdriver-client -g
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
D:\nodejs\node-global
`-- webdriver-client@1.0.15

然后利用node模式的REPL调试 是可以的
![image](https://cloud.githubusercontent.com/assets/18392901/19225399/767e828e-8ece-11e6-8c49-1f019122d222.png)

但进入devtool下 一直调不通 
![image](https://cloud.githubusercontent.com/assets/18392901/19225415/ba7ad3c0-8ece-11e6-8b2e-8568d74107f9.png)

 以前也提过issue https://github.com/alibaba/macaca/issues/97
我以为是我自己的问题 今天调通node的REPL后确定肯定是devtool 在win10和ubuntu环境下的问题

**Comment by zenzhu** [comment]
你这个是webdriver-client 后面少了个单引号

**Comment by xudafeng** [comment]
你这个是语法问题啊

**Comment by Archer456** [comment]
![image](https://cloud.githubusercontent.com/assets/18392901/19225956/49f7c2bc-8ed7-11e6-9c10-177380173b91.png)

**Comment by xudafeng** [comment]
在你当前目录 npm i webdriver-client

**Comment by Archer456** [comment]
D:\macaca\macaca-test-sample-master>npm i webdriver-client -g
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
D:\nodejs\node-global
`-- webdriver-client@1.0.15

肯定装过的拉

**Comment by xudafeng** [comment]
@zenzhu @zensh 是不是版本的问题

**Comment by zensh** [comment]
好多年没接触 windows 😅

**Comment by xudafeng** [comment]
@Archer456 不是 -g

**Comment by Archer456** [comment]
![image](https://cloud.githubusercontent.com/assets/18392901/19228508/88db5586-8ef8-11e6-9645-b1fea370c5a6.png)
cmd@TR:~$ macaca -v

  1.1.5

cmd@TR:~$ macaca doctor

  macaca-doctor version: 1.0.21


  Node.js checklist:

  node env: /opt/nodejs/bin/node
  node version: v4.4.7

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/opt/android-sdk-linux`
  Platforms is set to `/opt/android-sdk-linux/platforms/android-24`
  Android tools is set to `/opt/android-sdk-linux/tools/android`
  ADB tool is set to `/opt/android-sdk-linux/platform-tools/adb`

  Installed driver list:

  android: 1.0.39
  chrome: 1.0.3
  electron: 1.1.4


cmd@TR:~$ devtool -v
devtool 2.2.0
electron 1.3.3
node 6.3.0
chrome 52.0.2743.82


ubuntu16.04下 是OK的了  win10 win环境还是那样

**Comment by xudafeng** [comment]
ubuntu好了？

**Comment by Archer456** [comment]
@xudafeng 
嗯 ubuntu好了  win10还是这样

刚打开这个工具 第一个红框内的错误 我怀疑就有问题 可能初始化打开就已经有问题了
![image](https://cloud.githubusercontent.com/assets/18392901/19229617/6adac82e-8f01-11e6-9c0e-fda6baa8f0c1.png)

**Comment by xudafeng** [comment]
那个文件到底有没有啊

**Comment by Archer456** [comment]
第二个红框里提示的文件吗？   不是安装了webdriver-client里边后的文件吗

我看了下 win10下 就这样
![image](https://cloud.githubusercontent.com/assets/18392901/19230090/07e148b6-8f05-11e6-922a-4a3874f85f09.png)

**Comment by xudafeng** [comment]
难道是系统解这个包有问题

**Comment by xudafeng** [comment]
给devtool作者提个issue问下这里

**Comment by Archer456** [comment]
https://github.com/Jam3/devtool/issues/96

提了  不过感觉他们没人理问题的 上一个问题都还没指派呢

**Comment by xudafeng** [comment]
安装固定版本吧https://macacajs.github.io/macaca/debugging.html
