### ISSUE TITLE
macaca-cli 新版本1.1.5有问题吗？运行test用例时找不到mocha框架

### ISSUE THREAD

**Issue by githublue** [alibaba/macaca#247]
升级到java 8 和 android API 24后，android驱动已经成功装上了，

但是运行test用例时候，报errror，找不到 framework “mocha”，

我是用cnpm镜像安装的，用cnpm i -g macaca-cli 命令重装了两次

**Comment by xudafeng** [comment]
npm 装一下吧

**Comment by githublue** [comment]
npm 可以 
不过macaca-chrome 和 macaca-android貌似只能用cnpm，android的驱动挂了chrome驱动，npm装不上

@xudafeng

**Comment by xudafeng** [comment]
https://testerhome.com/topics/4523

**Comment by lixiansky** [comment]
这个问题应该是运行测试命令时路径的问题！！！

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/445

**Comment by 562837423** [comment]
请问问题是怎么解决的呀，我也遇到了同样的问题

**Comment by MarsOu1998** [comment]
> 请问问题是怎么解决的呀，我也遇到了同样的问题

试试在运行macaca run之前安装项目依赖，如下所示：
```
npm i
```
