### ISSUE TITLE
macaca支持.net程序的测试吗？

### ISSUE THREAD

**Issue by githublue** [alibaba/macaca#248]
win7系统的嵌入式设备，采用.net开发应用程序，目前macaca支持吗？

**Comment by xudafeng** [comment]
UI测试？

**Comment by githublue** [comment]
是的 使用.net编写的exe应用程序  @xudafeng

**Comment by xudafeng** [comment]
懂了，推荐你用 https://github.com/octalmage/robotjs，目前API还没有被Macaca标准化

**Comment by githublue** [comment]
好的 谢谢
