### ISSUE TITLE
macaca-cli 兼容 node6+

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#249]
兼容cnpm

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/272

**Comment by xudafeng** [comment]
@dead-horse

**Comment by xudafeng** [comment]
nvm install 6  && nvm use 6 
npm 3.10.8

cnpm i macaca-cli macaca-electron -g 装cli和驱动

https://github.com/macacajs/macaca-test-sample 下载这个运行 make test-pc

**Comment by dead-horse** [comment]
cnpm -v 看下打印出来的版本

**Comment by dead-horse** [comment]
你这个 macaca-test-sample 仓库大的令人发指啊

**Comment by xudafeng** [comment]
```shell
$ cnpm -v
4.2.0
```

里面有app 😆 ,--depth=1

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-cli/pull/57

**Comment by xudafeng** [comment]
请更新到macaca-cli@1.18版本
