### ISSUE TITLE
远程设备调用问题

### ISSUE THREAD

**Issue by TediWang** [alibaba/macaca#25]
场景：测试用例和环境部署到远程服务器，服务器上统一管理和维护脚本。测试人员会在自己的PC上连接设备，设备和环境分别属于两个环境。Macaca是否能支持，远程调用用例跑在测试人员自己的机器上。（有点像设备租用）。

**Comment by xudafeng** [comment]
@zenzhu 看了这个功能可以开放了

**Comment by xudafeng** [comment]
@TediWang 后面可否把你们的实践总结一下？
