### ISSUE TITLE
调用滑动方法报空指针

### ISSUE THREAD

**Issue by ownehe** [alibaba/macaca#256]
在调用driver.swipe(300, 350, 50, 350, 2) 时，执行报空指针异常。报错代码如下：
java.lang.NullPointerException
macaca.client.common.Utils.postRequest(Utils.java:72)
macaca.client.common.Utils.request(Utils.java:135)
macaca.client.commands.Element.swipe(Element.java:66)
macaca.client.MacacaClient.swipe(MacacaClient.java:678)
huasheng.andorid.UI.HuaShengAppTest.TestCase_zhuce_RegisteredSuccess(HuaShengAppTest.java:47)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:483)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
org.testng.TestRunner.privateRun(TestRunner.java:782)
org.testng.TestRunner.run(TestRunner.java:632)
org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
org.testng.SuiteRunner.run(SuiteRunner.java:268)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
org.testng.TestNG.run(TestNG.java:1064)
org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Macaca Version: java 版 1.0.29 最新版本
node version: v4.4.7
Platform: Windows 64-bit.
Programming Language：java

**Comment by xudafeng** [comment]
@kobe990 这个可以关闭了
