### ISSUE TITLE
运行test 找不到mocha模块Error: Cannot find test framework "mocha" in node_modules

### ISSUE THREAD

**Issue by Wantersu** [alibaba/macaca#257]
Windows7环境下，在环境配置完成后，运行test用例时提示找不到mocha模块，使用的是npm（#247的解决办法试了，还是出错）

**Comment by Wantersu** [comment]
![1](https://cloud.githubusercontent.com/assets/13692540/19347929/fccef81c-917d-11e6-8f4a-7882c7fa362e.png)
这是macaca doctor的log

**Comment by xudafeng** [comment]
工程的依赖装了吗

**Comment by Wantersu** [comment]
您好，之前是安装了的，现在我把环境挂代理整个重装了一遍，目前已经不会报这个错误了------------------------------------------------------------------发件人：xdf <notifications@github.com>发送时间：2016年10月14日(星期五) 10:22收件人：alibaba/macaca <macaca@noreply.github.com>抄　送：梁峰 <derek.liang@trustlife.com>; Author <author@noreply.github.com>主　题：Re: [alibaba/macaca] 运行test 找不到mocha模块Error: Cannot find test framework "mocha" in node_modules (#257)
工程的依赖装了吗—

**Comment by githublue** [comment]
我之前也遇到了，macaca-cli安装不要用镜像，直接npm；
还有ant工具没装，后面可能会出其他问题

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/445
