### ISSUE TITLE
android 真机无法跑python示例

### ISSUE THREAD

**Issue by uugign** [alibaba/macaca#258]
- **Macaca Version**:
  1.1.5
- **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.21
  
  Node.js checklist:
  
  node env: /usr/local/bin/node
  node version: v4.6.0
  
  iOS checklist:
  
  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy
  
  Android checklist:
  
  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/qq/Library/Android/sdk`
  Platforms is set to `/Users/qq/Library/Android/sdk/platforms/android-24`
  Android tools is set to `/Users/qq/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/qq/Library/Android/sdk/platform-tools/adb`
  
  Installed driver list:
  
  android: 1.0.39
  electron: 1.1.4
  ios: 1.0.38
- **Operate System**:
  mac 10.11.6
  RELEASE_X86_64 x86_64
- **Programming Language**:
  python3.5

android模拟器可以正常跑示例，用已root的真机小米2s 系统4.1.1运行python示例报如下错误：

```
>> responseHandler.js:11:12 [master] pid:1147 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"android","app":"./app/android-app-bootstrap.zip","reuse":3}}
>> session.js:47:10 [master] pid:1147 Creating session, sessionId: d18f61bb-828d-481c-8cd6-77a9c18591aa.
>> helper.js:196:12 [master] pid:1147 Unzipping local app form /Users/qq/Documents/macaca-py/macaca-test-sample-python/app/android-app-bootstrap.zip
>> uiautomator-client.js:70:14 [master] pid:1147 connect lost
Terminated

INSTRUMENTATION_STATUS: current=1

INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize
INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:
INSTRUMENTATION_STATUS: numtests=1

INSTRUMENTATION_STATUS: test=testStartServer
INSTRUMENTATION_STATUS_CODE: 1

uiautomator start socket server.

>> socket server ready
>> socket client ready
>> responseHandler.js:54:12 [master] pid:1147 Send Error Respone to Client: get PIDs failed

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
```

**Comment by xudafeng** [comment]
更新android驱动

**Comment by xudafeng** [comment]
cnpm i macaca-android -g
