### ISSUE TITLE
Windows7环境下，运行Android测试用例时报错

### ISSUE THREAD

**Issue by Wantersu** [alibaba/macaca#260]
在Windows环境下，运行Android的测试时，第一次执行会提示找不到虚拟机
![1](https://cloud.githubusercontent.com/assets/13692540/19387107/acb2004a-924a-11e6-98e3-8813fd2d4fd8.png)
devices list如下
![2](https://cloud.githubusercontent.com/assets/13692540/19387164/01d22816-924b-11e6-8807-aa1832835db2.png)
第二次执行会报下列错误
![3](https://cloud.githubusercontent.com/assets/13692540/19387221/5c693f9e-924b-11e6-87e7-4c7fb3a7b72f.png)

请问这个该怎么解决
* **Macaca Version**: 1.1.5

* **Macaca Doctor Logs**:
![default](https://cloud.githubusercontent.com/assets/13692540/19387033/50018f8c-924a-11e6-9d2e-60e9c4cdc3d7.png)

* **Operate System**:Windows7

**Comment by githublue** [comment]
ant 没装啊 ，android-driver应该没有编译成功，少一个文件

**Comment by xudafeng** [comment]
看faq
