### ISSUE TITLE
macaca android setText 无法覆盖输入新内容

### ISSUE THREAD

**Issue by yaniswang** [alibaba/macaca#262]
现有内容如下：

![image](https://cloud.githubusercontent.com/assets/970390/19428606/94356aae-947d-11e6-90aa-bdac6d735d7c.png)

如果再次调用keys方法设置新字符：321，则有可能会出现以下两种情况：
1. 321你
2. 3213你

清理旧内容逻辑有BUG,导致无法准确的清空内容。

**Comment by xudafeng** [comment]
先clear

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/commit/6537561d576549b0883bbbd6fca3193a70e05e18

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/commit/43aeaa3ab1a43e9e10521463fb3f739159715992

**Comment by xudafeng** [comment]
升级macaca-android

**Comment by yaniswang** [comment]
还是没修复，问题更严重了

**Comment by kobe990** [comment]
可以正确clear了

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/webdriver-client/commit/904b4a2b9634a4bc738853a02679cdf242fa85f3

**Comment by xudafeng** [comment]
@kobe990 💯
