### ISSUE TITLE
macaca inspector不兼容ipad

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#264]
- **Macaca Version**:
- **Macaca Doctor Logs**:
- **Operate System**:
- **Programming Language**:

如图所示，macaca inspector不支持ipad，机器为ipad mini4
<img width="1223" alt="dingtalk20161018131852" src="https://cloud.githubusercontent.com/assets/4576123/19465346/ff61e63c-9535-11e6-87a6-6f75ee573331.png">

**Comment by meowtec** [comment]
这个应该是 dpr 的问题，我现在通过分辨率区分了 6 和 6 以下的手机，但是 ipad 等没有考虑到。xctest 能拿到设备型号吗？@xudafeng

**Comment by xudafeng** [comment]
拿不到

**Comment by meowtec** [comment]
看来只能根据分辨率枚举了。

**Comment by CodeToSurvive1** [comment]
@xudafeng 这个问题没改吧

<img width="1226" alt="ipad-inspector" src="https://cloud.githubusercontent.com/assets/4576123/21968295/231d148c-dbce-11e6-943b-a02e3f95f4c4.png">

**Comment by xudafeng** [comment]
@CodeToSurvive1 ipad不在支持计划里
