### ISSUE TITLE
Android设备上webview报ClassCastException

### ISSUE THREAD

**Issue by SmallBlackboard** [alibaba/macaca#269]
Response content:{"sessionId":"c8a63bd0-c7b5-491a-ac14-9bc9ca405359","status":0,"value":{"ELEMENT":"7"}}
The command executed successfully.
200
Response content:{"sessionId":"c8a63bd0-c7b5-491a-ac14-9bc9ca405359","status":0,"value":true}
The command executed successfully.
Response content:{"sessionId":"c8a63bd0-c7b5-491a-ac14-9bc9ca405359","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 6.1 SP1 x86_64)"}}
200
Response content:{"sessionId":"c8a63bd0-c7b5-491a-ac14-9bc9ca405359","status":0}
The command executed successfully.

java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to com.alibaba.fastjson.JSONArray

```
at macaca.client.commands.Context.getContexts(Context.java:27)
at macaca.client.MacacaClient.contexts(MacacaClient.java:118)
at macaca.client.SampleWeiXinTest.switchToWebView(SampleWeiXinTest.java:86)
at macaca.client.SampleWeiXinTest.test_case_2(SampleWeiXinTest.java:70)
```

**Comment by SmallBlackboard** [comment]
![qq 20161019092703](https://cloud.githubusercontent.com/assets/20770808/19502296/91d83306-95de-11e6-8485-f2f89fd8276e.png)
![qq 20161019092828](https://cloud.githubusercontent.com/assets/20770808/19502303/9b8081b0-95de-11e6-9a19-abf8c806eadf.png)

**Comment by SmallBlackboard** [comment]
return: {"success":true,"data":{"status":0,"value":true}}

>> responseHandler.js:47:14 [master] pid:3272 Send HTTP Respone to Client: {"ses                                                                                                                sionId":"c8a63bd0-c7b5-491a-ac14-9bc9ca405359","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:3272 Recieve HTTP Request from Client:                                                                                                                 method: GET url: /wd/hub/session/c8a63bd0-c7b5-491a-ac14-9bc9ca405359/contexts,                                                                                                                 jsonBody: {}
>> chromedriver bin path: C:\Users\Administrator\AppData\Roaming\npm\node_module                                                                                                                s\.macaca-android_npminstall\node_modules\.1.0.19@macaca-chromedriver\exec\chrom                                                                                                                edriver.exe
>> Starting ChromeDriver 2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067)                                                                                                                 on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:52:14 [master] pid:3272 Proxy: /status:GET to http://localhost:9515/                                                                                                                wd/hub/status:GET with body:
>> proxy.js:58:16 [master] pid:3272 Got response with status 200: "{\"sessionId\                                                                                                                ":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\                                                                                                                ":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1 SP1\"}}}"
>> proxy.js:52:14 [master] pid:3272 Proxy: /session:POST to http://localhost:951                                                                                                                5/wd/hub/session:POST with body: {"desiredCapabilities":{"chromeOptions":{"andro                                                                                                                idPackage":"com.tencent.mm","androidUseRunningApp":true,"androidDeviceSerial":"2                                                                                                                353c4bb"}}}
>> proxy.js:58:16 [master] pid:3272 Got response with status 200: {"sessionId":"                                                                                                                fd7b1a26550ea8c840a6a8d5a0c2f457","status":100,"value":{"message":"chrome not re                                                                                                                achable\n  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081                                                                                                                628a1396067),platform=W...
>> chromedriver ready with: {"sessionId":null,"status":100,"value":{"message":"c                                                                                                                hrome not reachable\n  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933e                                                                                                                c778dbcf7081628a1396067),platform=Windows NT 6.1 SP1 x86_64)"}}
>> proxy.js:52:14 [master] pid:3272 Proxy: /wd/hub/session/temp/window_handles:G                                                                                                                ET to http://localhost:9515/wd/hub/session/fd7b1a26550ea8c840a6a8d5a0c2f457/wind                                                                                                                ow_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:3272 Got response with status 200: {"sessionId":"                                                                                                                fd7b1a26550ea8c840a6a8d5a0c2f457","status":6,"value":{"message":"no such session                                                                                                                \n  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a139                                                                                                                6067),platform=Windows ...
>> responseHandler.js:54:12 [master] pid:3272 Send Error Respone to Client: NoSu                                                                                                                chDriver: no such session
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a13960                                                                                                                67),platform=Windows NT 6.1 SP1 x86_64)
>> responseHandler.js:60:14 [master] pid:3272 NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a13960                                                                                                                67),platform=Windows NT 6.1 SP1 x86_64)
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (C:\Users\Admini                                                                                                                strator\AppData\Roaming\npm\node_modules\.macaca-android_npminstall\node_modules                                                                                                                \.1.0.39@macaca-android\lib\helper.js:67:11)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (C:                                                                                                                \Users\Administrator\AppData\Roaming\npm\node_modules\.macaca-android_npminstall                                                                                                                \node_modules\.1.0.39@macaca-android\lib\macaca-android.js:270:18)
    at next (native)
    at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\maca                                                                                                                ca-cli\node_modules\co\index.js:65:19)
    at process._tickCallback (node.js:369:9)
>> responseHandler.js:76:14 [master] pid:3272 Send Bad HTTP Respone to Client: {                                                                                                                "sessionId":"c8a63bd0-c7b5-491a-ac14-9bc9ca405359","status":6,"value":{"message"                                                                                                                :"no such session\n  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec7                                                                                                                78dbcf7081628a1396067),platform=Windows NT 6.1 SP1 x86_64)"}}
>> responseHandler.js:11:12 [master] pid:3272 Recieve HTTP Request from Client:                                                                                                                 method: DELETE url: /wd/hub/session/c8a63bd0-c7b5-491a-ac14-9bc9ca405359, jsonBo                                                                                                                dy: {}
>> session.js:80:12 [master] pid:3272 Delete session, sessionId: c8a63bd0-c7b5-4                                                                                                                91a-ac14-9bc9ca405359
>> responseHandler.js:47:14 [master] pid:3272 Send HTTP Respone to Client: {"ses                                                                                                                sionId":"c8a63bd0-c7b5-491a-ac14-9bc9ca405359","status":0}
>> macaca-chromedriver.js:123:18 [master] pid:3272 chromedriver exit with code:                                                                                                                 null, signal: SIGTERM

**Comment by xudafeng** [comment]
微信暂不支持

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/421 已解决
