### ISSUE TITLE
macaca不支持微信公众号测试

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#270]
- **Macaca Version**:
- **Macaca Doctor Logs**:
- **Operate System**:
- **Programming Language**:

目前使用下来发现：

Android公众号测试会出现chrome not reachable的错误，但是通过chrome浏览器chrome://inspect/#devices能看到微信公众号的页面，无法测试使用。但是官方案例webview能跑通。

IOS公众号测试会出现点击公众号直接微信退出后台报错，同issue相同问题 https://github.com/alibaba/macaca/issues/263

**Comment by jessezyl** [comment]
Android微信用的是自带的X5内核，虽然是基于chromedriver的，但跟原生的chromedriver不兼容吧，Appium也是同样的问题。

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/421 已解决

**Comment by WangMegan713** [comment]
请问怎么解决的
