### ISSUE TITLE
macaca安卓版本每次跑脚本都会安装输入法跟unlock软件

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#271]
- **Macaca Version**:
- **Macaca Doctor Logs**:
- **Operate System**:
- **Programming Language**:

目前发现一款手机，估计是手机厂商权限设置，无论安装什么软件都会提示安装，需要手工人为点击同意，这样就造成了每次跑脚本的时候都再次安装macaca输入法和解锁unlock软件，都要人为操作后才能继续，能否在安装前先检查是否已经安装输入法和解锁软件，如果已经安装则不再安装呢？

**Comment by xudafeng** [comment]
@CodeToSurvive1 这样unlock更新会成问题

**Comment by CodeToSurvive1** [comment]
@xudafeng 能获取到软件的版本信息来确定版本不一致的时候再覆盖安装吗？

**Comment by xudafeng** [comment]
是可以，unlock和bootstrap可以用这种方式升级

**Comment by CodeToSurvive1** [comment]
好的  这样也能解决某些手机需要重复人为同意安装的问题了

**Comment by xudafeng** [comment]
https://testerhome.com/topics/7522

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/437

**Comment by xudafeng** [comment]
@wangyunshuai 这个issue
