### ISSUE TITLE
macaca 1.1.8升级出现问题

### ISSUE THREAD

**Issue by githublue** [alibaba/macaca#277]
npm i -g macaca-cli@1.1.8

之后运行测试用例，弹出Cannot find module '.../mocha.cmd' 的错误

**Comment by Archer456** [comment]
@githublue   请帖出你的安装源  
npm config get registry 

你可以保存自己的脚本 然后重新下载下或重新git clone 示例代码 
https://github.com/macacajs/macaca-test-sample

再npm i  为项目安装执行环境后 再试验下   

先保证查明自己的项目环境没问题 脚本内容没问题

**Comment by githublue** [comment]
没用什么源，macaca-cli包一直用npm原生的，

macaca-test-sample代码我看了一下，还是半个月前的，一直没更新，我就不重新下了，

只是重新npm i了一下，

错误log我抓了一下：

>> index.js:17:12 [master] pid:3380 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.20.220',
  host: 'PC-20141210GYTR',
  loaded_time: '2016-10-24 11:53:18' }
>> middlewares.js:17:10 [master] pid:3380 base middlewares attached
>> router.js:129:10 [master] pid:3380 router set
>> webdriver sdk launched
>> module.js:327
    throw err;
    ^

Error: Cannot find module 'D:\Node\nodejs\node-global\node_modules\macaca-cli\node_modules\mocha\bin\mocha.cmd'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

>> Test completed!

**Comment by githublue** [comment]
@Archer456

**Comment by thxl2010** [comment]
我也遇到了同样的问题

**Comment by githublue** [comment]
安装源： https://registry.npmjs.org/  @Archer456

**Comment by xudafeng** [comment]
@dead-horse @zenzhu

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/276

**Comment by Archer456** [comment]
@thxl2010 @githublue 
官方建议用cnpm 来安装部署了 你可以试一下
不喜欢cnpm 的话  可以改为 npm config set registry http://registry.npm.taobao.org    淘宝源
不只是代码不变的意思  样例每隔一段时间除了代码脚本其他的会变化一些的。所以建议你
重新签出下样例项目。

**Comment by dead-horse** [comment]
https://github.com/macacajs/macaca-cli/pull/59

**Comment by xudafeng** [comment]
麻烦升级到 1.1.9

**Comment by githublue** [comment]
OK 1.1.10没问题了 辛苦
