### ISSUE TITLE
真机运行报错：xctest-client.js:123:16 [master] pid:29961 ERROR: Could not start service com.apple.syslog_relay.

### ISSUE THREAD

**Issue by sbait123** [alibaba/macaca#279]
**hahahehehehehe:kanyunDemo farben$ macaca run --verbose

> > request.js:23:12 [master] pid:29935 get remote update info failed.
> > index.js:17:12 [master] pid:29936 webdriver server start with config:
> >  { port: 3456,
> >   verbose: false,
> >   always: true,
> >   window: true,
> >   ip: '172.20.10.3',
> >   host: 'hahahehehehehe.local',
> >   loaded_time: '2016-10-24 18:59:49' }
> > middlewares.js:17:10 [master] pid:29936 base middlewares attached
> > router.js:129:10 [master] pid:29936 router set
> > webdriver sdk launched
> > 
> >   macaca mobile sample
> > 
> > responseHandler.js:11:12 [master] pid:29936 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"10","deviceName":"iPhone 6","udid":"8f654d72113b4494058e811d4c234392be0b9b81","bundleId":"com.hzj.kanyunDemo","app":"/Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip"}}
> > session.js:47:10 [master] pid:29936 Creating session, sessionId: 224fa589-a4d1-446d-919a-a893d26cf15b.
> > helper.js:196:12 [master] pid:29936 Unzipping local app form /Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip
> > xctest-client.js:43:14 [master] pid:29936 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:144:10 [master] pid:29936 {
> >     "bundleId": "com.hzj.kanyunDemo",
> >     "platformName": "iOS",
> >     "platformVersion": "10",
> >     "app": "/var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/T/ios-kanyunDemo.app/"
> > }
> > xctest-client.js:183:12 [master] pid:29936 xcode version: 8.0
> > WebDriverAgent version: 1.0.28
> > ^C
> > hahahehehehehe:kanyunDemo farben$
> > hahahehehehehe:kanyunDemo farben$
> > hahahehehehehe:kanyunDemo farben$ macaca run --verbose
> > index.js:17:12 [master] pid:29961 webdriver server start with config:
> >  { port: 3456,
> >   verbose: false,
> >   always: true,
> >   window: true,
> >   ip: '172.20.10.3',
> >   host: 'hahahehehehehe.local',
> >   loaded_time: '2016-10-24 19:00:36' }
> > middlewares.js:17:10 [master] pid:29961 base middlewares attached
> > router.js:129:10 [master] pid:29961 router set
> > webdriver sdk launched
> > 
> >   macaca mobile sample
> > 
> > responseHandler.js:11:12 [master] pid:29961 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"10","deviceName":"iPhone 6","udid":"2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2","bundleId":"com.hzj.kanyunDemo","app":"/Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip"}}
> > session.js:47:10 [master] pid:29961 Creating session, sessionId: 633142ef-b961-4f4e-bdd9-a77ff86e63e3.
> > helper.js:196:12 [master] pid:29961 Unzipping local app form /Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip
> > xctest-client.js:43:14 [master] pid:29961 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:144:10 [master] pid:29961 {
> >     "bundleId": "com.hzj.kanyunDemo",
> >     "platformName": "iOS",
> >     "platformVersion": "10",
> >     "app": "/var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/T/ios-kanyunDemo.app/"
> > }
> > xctest-client.js:183:12 [master] pid:29961 xcode version: 8.0
> > WebDriverAgent version: 1.0.28
> > xctest-client.js:123:16 [master] pid:29961 ERROR: Could not start service com.apple.syslog_relay.
> > Could not start logger for udid 2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> > 
> > xctest-client.js:156:14 [master] pid:29961 2016-10-24 19:00:39.440 xcodebuild[29968:1631306]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/F83C4AA4-480F-47CD-B40B-0FD1CE282114/Session-WebDriverAgentRunner-2016-10-24_190039-5Eg1pP.log
> > 
> > xctest-client.js:156:14 [master] pid:29961 2016-10-24 19:00:39.440 xcodebuild[29968:1631301] [MT] IDETestOperationsObserverDebug: (D9999BC5-1E98-4C97-91D6-EB9AF98B96E8) Beginning test session WebDriverAgentRunner-D9999BC5-1E98-4C97-91D6-EB9AF98B96E8 at 2016-10-24 19:00:39.439 with Xcode 8A218a on target <DVTiOSDevice: 0x7fd292edbd60> {
> >         deviceSerialNumber:         DNQPTZ6HG5MQ
> >         identifier:                 2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> >         deviceClass:                iPhone
> >         deviceName:                 iPhone (10)
> >         deviceIdentifier:           2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> >         productVersion:             10.0.2
> >         buildVersion:               14A456
> >         deviceSoftwareVersion:      10.0.2 (14A456)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12001857536
> >         deviceAvailableCapacity:    1233584128
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7fd292e15ec0 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (10.0.2 (14A456))
> > 
> > xctest-client.js:156:14 [master] pid:29961 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/4374dd4b1315e9c66fb445dbf6ae6c45/2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.lRkT2t/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.lRkT2t/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:29961 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.lRkT2t/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:29961 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.lRkT2t/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > responseHandler.js:11:12 [master] pid:29961 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"10","deviceName":"iPhone 6","udid":"2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2","bundleId":"com.hzj.kanyunDemo","app":"/Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip"}}
> > session.js:47:10 [master] pid:29961 Creating session, sessionId: 37f278a5-4e72-4e21-9b25-d798a13d3065.
> > helper.js:196:12 [master] pid:29961 Unzipping local app form /Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip
> > xctest-client.js:43:14 [master] pid:29961 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:144:10 [master] pid:29961 {
> >     "bundleId": "com.hzj.kanyunDemo",
> >     "platformName": "iOS",
> >     "platformVersion": "10",
> >     "app": "/var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/T/ios-kanyunDemo.app/"
> > }
> > xctest-client.js:183:12 [master] pid:29961 xcode version: 8.0
> > WebDriverAgent version: 1.0.28
> > xctest-client.js:123:16 [master] pid:29961 ERROR: Could not start service com.apple.syslog_relay.
> > Could not start logger for udid 2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> > 
> > xctest-client.js:156:14 [master] pid:29961 2016-10-24 19:02:39.317 xcodebuild[30157:1633454]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/DEB08E9D-976A-45B2-9FAE-0485E498FD28/Session-WebDriverAgentRunner-2016-10-24_190239-PLrUhV.log
> > 2016-10-24 19:02:39.317 xcodebuild[30157:1633446] [MT] IDETestOperationsObserverDebug: (A7C6ED00-1FC6-4F3D-AD2D-A07356076FD9) Beginning test session WebDriverAgentRunner-A7C6ED00-1FC6-4F3D-AD2D-A07356076FD9 at 2016-10-24 19:02:39.316 with Xcode 8A218a on target <DVTiOSDevice: 0x7fb59db411a0> {
> >         deviceSerialNumber:         DNQPTZ6HG5MQ
> >         identifier:                 2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> >         deviceClass:                iPhone
> >         deviceName:                 iPhone (10)
> >         deviceIdentifier:           2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> >         productVersion:             10.0.2
> >         buildVersion:               14A456
> >         deviceSoftwareVersion:      10.0.2 (14A456)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12001857536
> >         deviceAvailableCapacity:    1232023552
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7fb59d673550 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (10.0.2 (14A456))
> > 
> > xctest-client.js:156:14 [master] pid:29961 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/4374dd4b1315e9c66fb445dbf6ae6c45/2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.klfVdw/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.klfVdw/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:29961 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.klfVdw/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:29961 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.klfVdw/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:29961 2016-10-24 19:02:54.856 xcodebuild[29968:1631706]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/F83C4AA4-480F-47CD-B40B-0FD1CE282114/Session-WebDriverAgentRunner-2016-10-24_190254-XkcSXG.log
> > 
> > xctest-client.js:156:14 [master] pid:29961 2016-10-24 19:02:54.856 xcodebuild[29968:1631301] [MT] IDETestOperationsObserverDebug: (0AFF298D-23F0-4D59-B2AB-7F8F6892AFF4) Beginning test session WebDriverAgentRunner-0AFF298D-23F0-4D59-B2AB-7F8F6892AFF4 at 2016-10-24 19:02:54.856 with Xcode 8A218a on target <DVTiOSDevice: 0x7fd292edbd60> {
> >         deviceSerialNumber:         DNQPTZ6HG5MQ
> >         identifier:                 2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> >         deviceClass:                iPhone
> >         deviceName:                 iPhone (10)
> >         deviceIdentifier:           2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> >         productVersion:             10.0.2
> >         buildVersion:               14A456
> >         deviceSoftwareVersion:      10.0.2 (14A456)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12001857536
> >         deviceAvailableCapacity:    1233584128
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7fd292e15ec0 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              {(
> >     <DTDKApplication: 0x7fd293913260>: 天猫 (/private/var/containers/Bundle/Application/FF2DE742-CB78-4E18-8BF6-CC83E540A145/Tmall4iPhone.app),
> >     <DTDKApplication: 0x7fd29040a5a0>: WeChat (/private/var/containers/Bundle/Application/5C38C273-8FB5-4A66-A376-BFEA32DAC6D9/WeChat.app),
> >     <DTDKApplication: 0x7fd29393c400>: 搜狗输入法 (/private/var/containers/Bundle/Application/99817479-511F-4F29-9AC1-B93B84DE4C2A/SogouInput.app),
> >     <DTDKApplication: 0x7fd29394a2f0>: 手机淘宝 (/private/var/containers/Bundle/Application/5F3D7707-4137-41EE-8796-C4043EE3682E/Taobao4iPhone.app),
> >     <DTDKApplication: 0x7fd2930b70f0>: WiFi万能钥匙 (/private/var/containers/Bundle/Application/826C4109-8432-4E50-80CA-AEF381A4478E/ConfigWiFi.app),
> >     <DTDKApplication: 0x7fd293061170>: 百度钱包 (/private/var/containers/Bundle/Application/8B248392-4CE4-4CCC-A74C-9A1C61A45E12/BWA_APP.app),
> >     <DTDKApplication: 0x7fd29394a1d0>: 平安口袋银行 (/private/var/containers/Bundle/Application/468C4D64-8E93-47EC-84C9-64889C4816E4/PAiPhoneBank2.0.app),
> >     <DTDKApplication: 0x7fd2933c3410>: 招商银行 (/private/var/containers/Bundle/Application/65207CB9-05A7-4558-9290-FB61F8057F73/MPBBank.app),
> >     <DTDKApplication: 0x7fd2933b7910>: 酷狗音乐 (/private/var/containers/Bundle/Application/235F026C-0938-4C70-8565-77C76009704E/kugou.app),
> >     <DTDKApplication: 0x7fd292d54c70>: Alipay (/private/var/containers/Bundle/Application/B4E0F586-115D-4C40-A350-5D18993465C6/AlipayWallet.app),
> >     <DTDKApplication: 0x7fd2933e4c30>: kanyunDemo (/private/var/containers/Bundle/Application/0FC81EA9-5756-4BB7-9CF3-7BEE79185795/kanyunDemo.app),
> >     <DTDKApplication: 0x7fd293087500>: 铁路12306 (/private/var/containers/Bundle/Application/F0C57DC2-E7DE-4E39-8A98-54B8AFD756BE/MobileTicket.app),
> >     <DTDKApplication: 0x7fd293087550>: QQ (/private/var/containers/Bundle/Application/A91559FA-BAD7-41ED-B5A8-03F05CE2CCB2/QQ.app),
> >     <DTDKApplication: 0x7fd293081560>: WebDriverAgentRunner (/private/var/containers/Bundle/Application/720538D5-B67B-46E1-A093-29DE24E8BC96/WebDriverAgentRunner-Runner.app),
> >     <DTDKApplication: 0x7fd2933c0260>: Weibo (/private/var/containers/Bundle/Application/93F7E73F-BF48-472B-893E-BEB44398C9B8/Weibo.app),
> >     <DTDKApplication: 0x7fd2929b5520>: 百度地图 (/private/var/containers/Bundle/Application/24A87F47-6423-4C14-9500-BC74F7D385A5/IphoneCom.app),
> >     <DTDKApplication: 0x7fd29391cfb0>: 手机百度 (/private/var/containers/Bundle/Application/5C45F9B0-01C1-4BBC-8777-F52676C618A9/BaiduBoxApp.app),
> >     <DTDKApplication: 0x7fd293367940>: 手机京东 (/private/var/containers/Bundle/Application/B90D7A9E-EA93-4748-8999-8EFA6445BED4/JD4iPhone.app)
> > )}
> >         provisioningProfiles:      {(
> >     <DTDKProvisioningProfile 0x7fd2934e2450: UUID: 01f0c93d-6928-4c26-8bf3-755fe4f1bce4, name: iOS Team Provisioning Profile: hzj.WebDriverAgentRunner, team: YGR2FRP5QF (志君 黄), platform: iOS>,
> >     <DTDKProvisioningProfile 0x7fd2934e2f50: UUID: 02c56f98-281e-4dcb-a368-4cfbc267b50d, name: iOS Team Provisioning Profile: *, team: 4G6QV9EUCZ (Shenzhen Pusi Technology Co., Ltd.), platform: iOS>,
> >     <DTDKProvisioningProfile 0x7fd292f98eb0: UUID: 7c4b62ad-a770-439f-b73b-677f9395368b, name: iOS Team Provisioning Profile: hzj.WebDriverAgentRunner, team: YGR2FRP5QF (志君 黄), platform: iOS>,
> >     <DTDKProvisioningProfile 0x7fd2934e4b70: UUID: 7801d36b-6a5b-4f34-97d9-b10488882153, name: XC: com.soufun.*, team: NH6HY2CF7L (Beijing Hua Ju Tian Xia Network Technology Co.Ltd.), platform: iOS>,
> >     <DTDKProvisioningProfile 0x7fd2934e5170: UUID: 23ae43f7-49d3-48ae-9868-9ae8a35283a4, name: iOS Team Provisioning Profile: pusikeji.com, team: 4G6QV9EUCZ (Shenzhen Pusi Technology Co., Ltd.), platform: iOS>,
> >     <DTDKProvisioningProfile 0x7fd2930ef0f0: UUID: 9925fd54-86ce-4d96-becd-9c846b06aa67, name: iOS Team Provisioning Profile: com.hzj.kanyunDemo, team: YGR2FRP5QF (志君 黄), platform: iOS>
> > )}
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (10.0.2 (14A456))
> > 
> > xctest-client.js:156:14 [master] pid:29961 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/4374dd4b1315e9c66fb445dbf6ae6c45/2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QhfJqw/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QhfJqw/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:29961 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QhfJqw/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:29961 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.QhfJqw/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > responseHandler.js:11:12 [master] pid:29961 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"10","deviceName":"iPhone 6","udid":"2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2","bundleId":"com.hzj.kanyunDemo","app":"/Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip"}}
> > session.js:47:10 [master] pid:29961 Creating session, sessionId: 26f69ecd-580e-490f-8c57-035c6fe5392b.
> > helper.js:196:12 [master] pid:29961 Unzipping local app form /Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip
> > xctest-client.js:43:14 [master] pid:29961 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:144:10 [master] pid:29961 {
> >     "bundleId": "com.hzj.kanyunDemo",
> >     "platformName": "iOS",
> >     "platformVersion": "10",
> >     "app": "/var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/T/ios-kanyunDemo.app/"
> > }
> > xctest-client.js:183:12 [master] pid:29961 xcode version: 8.0
> > WebDriverAgent version: 1.0.28
> > xctest-client.js:123:16 [master] pid:29961 ERROR: Could not start service com.apple.syslog_relay.
> > Could not start logger for udid 2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> > 
> > xctest-client.js:156:14 [master] pid:29961 2016-10-24 19:04:39.379 xcodebuild[30317:1635186]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/17B4AA2D-8C62-4DE9-BC89-E80FCF179078/Session-WebDriverAgentRunner-2016-10-24_190439-CljuIY.log
> > 
> > xctest-client.js:156:14 [master] pid:29961 2016-10-24 19:04:39.379 xcodebuild[30317:1635183] [MT] IDETestOperationsObserverDebug: (B0DE1832-E221-497E-B6A0-C227E4F00F22) Beginning test session WebDriverAgentRunner-B0DE1832-E221-497E-B6A0-C227E4F00F22 at 2016-10-24 19:04:39.378 with Xcode 8A218a on target <DVTiOSDevice: 0x7f93817808b0> {
> >         deviceSerialNumber:         DNQPTZ6HG5MQ
> >         identifier:                 2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> >         deviceClass:                iPhone
> >         deviceName:                 iPhone (10)
> >         deviceIdentifier:           2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
> >         productVersion:             10.0.2
> >         buildVersion:               14A456
> >         deviceSoftwareVersion:      10.0.2 (14A456)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12001857536
> >         deviceAvailableCapacity:    1231392768
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7f93815a7bf0 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (10.0.2 (14A456))
> > 
> > xctest-client.js:156:14 [master] pid:29961 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/4374dd4b1315e9c66fb445dbf6ae6c45/2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.61GoXY/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.61GoXY/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:29961 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.61GoXY/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:29961 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.61GoXY/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > ```
> > 1) "before all" hook
> > ```
> > 
> > responseHandler.js:11:12 [master] pid:29961 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> > responseHandler.js:23:14 [master] pid:29961 Send HTTP Respone to Client: 405 Method Not Allowed
> > 
> > ```
> > 2) "after all" hook
> > ```
> > 
> >   0 passing (5m)
> > 
> >   2 failing
> > 
> >   1) macaca mobile sample "before all" hook:
> >      Error: timeout of 300000ms exceeded. Ensure the done() callback is being called in this test.
> > 
> >   2) macaca mobile sample "after all" hook:
> >      Error: [quit()] Unexpected data in simpleCallback.
> >       at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
> >       at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
> >       at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
> >       at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
> >       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
> >       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
> >       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
> >       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
> >       at endReadableNT (_stream_readable.js:905:12)
> > 
> > Test completed!
> > hahahehehehehe:kanyunDemo farben$**

 # ##**_xctest-client.js:123:16 [master] pid:29961 ERROR: Could not start service com.apple.syslog_relay.
Could not start logger for udid 2b1c7f48a0b3dcd5b8564813ac7f76a89314d1c2
请问这是什么错误？完全搞不懂啊！！_**

**Comment by xudafeng** [comment]
请升级iOS驱动，参考https://testerhome.com/topics/6314
