### ISSUE TITLE
真机测试：Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-11246/IDEFoundation/Testing/IDETestRunner.m:793

### ISSUE THREAD

**Issue by sbait123** [alibaba/macaca#280]
> > xctest-client.js:156:14 [master] pid:33132 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/4374dd4b1315e9c66fb445dbf6ae6c45/8f654d72113b4494058e811d4c234392be0b9b81/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.aGoHmo/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.aGoHmo/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:33132 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.aGoHmo/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:33132 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.aGoHmo/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:33132 2016-10-24 20:43:44.989 xcodebuild[33298:1695848] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-11246/IDEFoundation/Testing/IDETestRunner.m:793
> > Details:  Suite WebDriverAgentLib.framework was expected at index 1 in stack (
> >     "<_IDEXCTestSuiteRecord: 0x7f8ca78163e0> 'Selected tests'",
> >     "<_IDEXCTestSuiteRecord: 0x7f8ca7daee00> 'WebDriverAgentRunner.xctest'",
> >     "<_IDEXCTestSuiteRecord: 0x7f8ca7e50fb0> 'UITestingUITests'"
> > ), suites that previously finished: {(
> > )}.
> > Object:   <IDETestRunner: 0x7f8ca78bee90>
> > Method:   -testSuite:didStartAt:rawOutput:sessionState:
> > Thread:   <NSThread: 0x7f8ca4f044c0>{number = 1, name = main}
> > Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
> > 
> > xctest-client.js:156:14 [master] pid:33132 2016-10-24 20:43:45.055 xcodebuild[33298:1695848] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-11246/IDEFoundation/Testing/IDETestRunner.m:857
> > Details:  Assertion failed: [suiteRecord.suiteIdentifier isEqualToString:suiteIdentifier]
> > Object:   <IDETestRunner: 0x7f8ca78bee90>
> > Method:   -testSuite:willFinishAt:rawOutput:sessionState:
> > Thread:   <NSThread: 0x7f8ca4f044c0>{number = 1, name = main}
> > Hints: None
> > Backtrace:
> >   0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:](in DVTFoundation)
> >   1   _DVTAssertionHandler (in DVTFoundation)
> >   2   _DVTAssertionFailureHandler (in DVTFoundation)
> >   3   _DVTAssertionFailureHandler (in DVTFoundation)
> >   4   -[IDETestRunner testSuite:willFinishAt:rawOutput:sessionState:](in IDEFoundation)
> >   5   __118-[IDETestOperationCoordinator _XCT_testSuite:didFinishAt:runCount:withFailures:unexpected:testDuration:totalDuration:]_block_invoke (in IDEFoundation)
> >   6   -[IDETestOperationCoordinator _considerDispatchingDelegateBlock](in IDEFoundation)
> >   7   -[IDETestOperationCoordinator _executeDelegateBlockWithNextConsoleChunk:](in IDEFoundation)
> >   8   -[IDETestOperationCoordinator _XCT_testSuite:didFinishAt:runCount:withFailures:unexpected:testDuration:totalDuration:](in IDEFoundation)
> >   9   __invoking___ (in CoreFoundation)
> >  10   -[NSInvocation invoke](in CoreFoundation)
> >  11   -[DTXMessage invokeWithTarget:replyChannel:validator:](in DTXConnectionServices)
> >  12   **51-[DTXChannel _scheduleMessage:tracker:withHandler:]_block_invoke.683 (in DTXConnectionServices)
> >  13   _dispatch_call_block_and_release (in libdispatch.dylib)
> >  14   _dispatch_client_callout (in libdispatch.dylib)
> >  15   _dispatch_queue_serial_drain (in libdispatch.dylib)
> >  16   _dispatch_queue_invoke (in libdispatch.dylib)
> >  17   _dispatch_queue_serial_drain (in libdispatch.dylib)
> >  18   _dispatch_queue_invoke (in libdispatch.dylib)
> >  19   _dispatch_main_queue_callback_4CF (in libdispatch.dylib)
> >  20   __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE** (in CoreFoundation)
> >  21   __CFRunLoopRun (in CoreFoundation)
> >  22   CFRunLoopRunSpecific (in CoreFoundation)
> >  23   CFRunLoopRun (in CoreFoundation)
> >  24   -[Xcode3CommandLineBuildTool _buildWithTimingSection:](in Xcode3Core)
> >  25   -[Xcode3CommandLineBuildTool run](in Xcode3Core)
> >  26  0x000000010a777202 (in xcodebuild)
> >  27   start (in libdyld.dylib)
> > 
> > xctest-client.js:164:14 [master] pid:33132 xctest client exit with code: null, signal: SIGABRT
> > responseHandler.js:11:12 [master] pid:33132 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.0","deviceName":"iPhone 5s","udid":"8f654d72113b4494058e811d4c234392be0b9b81","bundleId":"xudafeng.ios-app-bootstrap","app":"/Users/farben/Desktop/macaca-test-sample/app/ios-app-bootstrap.zip"}}
> > session.js:47:10 [master] pid:33132 Creating session, sessionId: 91d1ae6e-bec0-41c7-9ae1-ef3e78fde853.
> > helper.js:196:12 [master] pid:33132 Unzipping local app form /Users/farben/Desktop/macaca-test-sample/app/ios-app-bootstrap.zip
> > xctest-client.js:43:14 [master] pid:33132 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:144:10 [master] pid:33132 {
> >     "bundleId": "xudafeng.ios-app-bootstrap",
> >     "platformName": "iOS",
> >     "platformVersion": "9.0",
> >     "app": "/var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/T/ios-app-bootstrap.app/"
> > }
> > xctest-client.js:183:12 [master] pid:33132 xcode version: 8.0
> > WebDriverAgent version: 1.0.28
> > xctest-client.js:123:16 [master] pid:33132 ERROR: Could not start service com.apple.syslog_relay.
> > Could not start logger for udid 8f654d72113b4494058e811d4c234392be0b9b81
> > 
> > xctest-client.js:156:14 [master] pid:33132 2016-10-24 20:45:14.030 xcodebuild[33452:1697684]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/77A965BD-5AC5-4867-BCFD-6126E643A131/Session-WebDriverAgentRunner-2016-10-24_204514-Sn7TrV.log
> > 
> > xctest-client.js:156:14 [master] pid:33132 2016-10-24 20:45:14.031 xcodebuild[33452:1697677] [MT] IDETestOperationsObserverDebug: (C24C8095-F728-4BB8-B97B-8DACE1E74001) Beginning test session WebDriverAgentRunner-C24C8095-F728-4BB8-B97B-8DACE1E74001 at 2016-10-24 20:45:14.030 with Xcode 8A218a on target <DVTiOSDevice: 0x7ff6015a0e50> {
> >         deviceSerialNumber:         F18PH379G5MQ
> >         identifier:                 8f654d72113b4494058e811d4c234392be0b9b81
> >         deviceClass:                iPhone
> >         deviceName:                 iPhone (7)
> >         deviceIdentifier:           8f654d72113b4494058e811d4c234392be0b9b81
> >         productVersion:             9.2.1
> >         buildVersion:               13D15
> >         deviceSoftwareVersion:      9.2.1 (13D15)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12707897344
> >         deviceAvailableCapacity:    805380096
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7ff6016890e0 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (9.2.1 (13D15))
> > 
> > xctest-client.js:156:14 [master] pid:33132 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/4374dd4b1315e9c66fb445dbf6ae6c45/8f654d72113b4494058e811d4c234392be0b9b81/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.nBfjCs/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.nBfjCs/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:33132 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.nBfjCs/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:33132 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.nBfjCs/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > ```
> > 1) "before all" hook
> > ```
> > 
> > responseHandler.js:11:12 [master] pid:33132 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> > responseHandler.js:23:14 [master] pid:33132 Send HTTP Respone to Client: 405 Method Not Allowed
> > 
> > ```
> > 2) "after all" hook
> > ```
> > 
> >   0 passing (5m)
> >   2 failing
> > 
> >   1) macaca mobile sample "before all" hook:
> >      Error: timeout of 300000ms exceeded. Ensure the done() callback is being called in this test.
> > 
> >   2) macaca mobile sample "after all" hook:
> >      Error: [quit()] Unexpected data in simpleCallback.
> >       at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
> >       at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
> >       at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
> >       at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
> >       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
> >       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
> >       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
> >       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
> >       at endReadableNT (_stream_readable.js:905:12)
> > 
> > Test completed!

**Comment by sbait123** [comment]
xcodebuild[33298:1695848] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-11246/IDEFoundation/Testing/IDETestRunner.m:857
Details: Assertion failed: [suiteRecord.suiteIdentifier isEqualToString:suiteIdentifier]
Object: 
Method: -testSuite:willFinishAt:rawOutput:sessionState:
Thread: {number = 1, name = main}
Hints: None
Backtrace:
0 -DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:
1 DVTAssertionHandler (in DVTFoundation)
2 DVTAssertionFailureHandler (in DVTFoundation)
3 DVTAssertionFailureHandler (in DVTFoundation)
4 -IDETestRunner testSuite:willFinishAt:rawOutput:sessionState:
5 __118-[IDETestOperationCoordinator _XCT_testSuite:didFinishAt:runCount:withFailures:unexpected:testDuration:totalDuration:]_block_invoke (in IDEFoundation)
6 -IDETestOperationCoordinator _considerDispatchingDelegateBlock
7 -IDETestOperationCoordinator _executeDelegateBlockWithNextConsoleChunk:
8 -IDETestOperationCoordinator _XCT_testSuite:didFinishAt:runCount:withFailures:unexpected:testDuration:totalDuration:
9 __invoking (in CoreFoundation)
10 -NSInvocation invoke
11 -DTXMessage invokeWithTarget:replyChannel:validator:
12 51-[DTXChannel _scheduleMessage:tracker:withHandler:]_block_invoke.683 (in DTXConnectionServices)
13 _dispatch_call_block_and_release (in libdispatch.dylib)
14 _dispatch_client_callout (in libdispatch.dylib)
15 _dispatch_queue_serial_drain (in libdispatch.dylib)
16 _dispatch_queue_invoke (in libdispatch.dylib)
17 _dispatch_queue_serial_drain (in libdispatch.dylib)
18 _dispatch_queue_invoke (in libdispatch.dylib)
19 _dispatch_main_queue_callback_4CF (in libdispatch.dylib)
20 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE (in CoreFoundation)
21 __CFRunLoopRun (in CoreFoundation)
22 CFRunLoopRunSpecific (in CoreFoundation)
23 CFRunLoopRun (in CoreFoundation)
24 -Xcode3CommandLineBuildTool _buildWithTimingSection:
25 -Xcode3CommandLineBuildTool run
26 0x000000010a777202 (in xcodebuild)
27 start (in libdyld.dylib)
# 
**_这是什么错误？#_**

**Comment by xudafeng** [comment]
请升级iOS驱动，参考https://testerhome.com/topics/6314
