### ISSUE TITLE
【需求】按坐标点击、列表操作

### ISSUE THREAD

**Issue by dengwei729** [alibaba/macaca#281]
我这边有几个需求：
1. 按坐标进行点击、双击、longpress 的操作
2. 对列表进行滑动操作  （目前获取不到元素的bounds）
3. 按elementByName 是否支持模糊匹配
- **Macaca Version**: 1.1.7
- **Macaca Doctor Logs**:
- **Operate System**:
- **Programming Language**:

**Comment by xudafeng** [comment]
已支持 https://github.com/alibaba/macaca/issues/366
