### ISSUE TITLE
求助：真机运行报错the requested application's data container path does not exist

### ISSUE THREAD

**Issue by sbait123** [alibaba/macaca#282]
> > index.js:17:12 [master] pid:1742 webdriver server start with config:
> >  { port: 3456,
> >   verbose: false,
> >   always: true,
> >   window: true,
> >   ip: '172.20.10.3',
> >   host: 'hahahehehehehe.local',
> >   loaded_time: '2016-10-25 14:58:38' }
> > middlewares.js:17:10 [master] pid:1742 base middlewares attached
> > router.js:129:10 [master] pid:1742 router set
> > webdriver sdk launched
> > 
> >   macaca mobile sample
> > 
> > responseHandler.js:11:12 [master] pid:1742 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.0","deviceName":"iPhone 6","udid":"648171a0c9d444af498dcc9d675dd81d8e1f8dd0","bundleId":"com.hzj.kanyunDemo","app":"/Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip"}}
> > session.js:47:10 [master] pid:1742 Creating session, sessionId: 0d0abf04-52ff-4388-961e-be78bff70753.
> > helper.js:196:12 [master] pid:1742 Unzipping local app form /Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip
> > xctest-client.js:43:14 [master] pid:1742 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:144:10 [master] pid:1742 {
> >     "bundleId": "com.hzj.kanyunDemo",
> >     "platformName": "iOS",
> >     "platformVersion": "9.0",
> >     "app": "/var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/T/ios-kanyunDemo.app/"
> > }
> > xctest-client.js:183:12 [master] pid:1742 xcode version: 8.0
> > WebDriverAgent version: 1.0.28
> > xctest-client.js:123:16 [master] pid:1742 ERROR: Could not start service com.apple.syslog_relay.
> > Could not start logger for udid 648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> > 
> > xctest-client.js:156:14 [master] pid:1742 2016-10-25 14:58:42.726 xcodebuild[1752:15652]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/0354B396-263D-4C12-AB68-43E0E9C5636E/Session-WebDriverAgentRunner-2016-10-25_145842-4aga0i.log
> > 2016-10-25 14:58:42.726 xcodebuild[1752:15644] [MT] IDETestOperationsObserverDebug: (171E47D1-0D42-4F40-ABD6-6DB56EA1D0E4) Beginning test session WebDriverAgentRunner-171E47D1-0D42-4F40-ABD6-6DB56EA1D0E4 at 2016-10-25 14:58:42.726 with Xcode 8A218a on target <DVTiOSDevice: 0x7fe9390b1fa0> {
> >         deviceSerialNumber:         C7JQDD3GGRY5
> >         identifier:                 648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> >         deviceClass:                iPhone
> >         deviceName:                 Isnowball🌻💐
> >         deviceIdentifier:           648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> >         productVersion:             10.0.1
> >         buildVersion:               14A403
> >         deviceSoftwareVersion:      10.0.1 (14A403)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12061245440
> >         deviceAvailableCapacity:    1374765056
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7fe938d703d0 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (10.0.1 (14A403))
> > 
> > xctest-client.js:156:14 [master] pid:1742 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/cc7272f975cd8eaea1b5077d22f2da4b/648171a0c9d444af498dcc9d675dd81d8e1f8dd0/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Intermediates/CodeCoverage/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.So6Mro/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.So6Mro/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:1742 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.So6Mro/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:1742 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.So6Mro/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > responseHandler.js:11:12 [master] pid:1742 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.0","deviceName":"iPhone 6","udid":"648171a0c9d444af498dcc9d675dd81d8e1f8dd0","bundleId":"com.hzj.kanyunDemo","app":"/Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip"}}
> > session.js:47:10 [master] pid:1742 Creating session, sessionId: 356ed697-c9c0-410c-8764-c026d627e884.
> > helper.js:196:12 [master] pid:1742 Unzipping local app form /Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip
> > xctest-client.js:43:14 [master] pid:1742 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:144:10 [master] pid:1742 {
> >     "bundleId": "com.hzj.kanyunDemo",
> >     "platformName": "iOS",
> >     "platformVersion": "9.0",
> >     "app": "/var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/T/ios-kanyunDemo.app/"
> > }
> > xctest-client.js:183:12 [master] pid:1742 xcode version: 8.0
> > WebDriverAgent version: 1.0.28
> > xctest-client.js:123:16 [master] pid:1742 ERROR: Could not start service com.apple.syslog_relay.
> > Could not start logger for udid 648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> > 
> > xctest-client.js:156:14 [master] pid:1742 2016-10-25 15:00:41.071 xcodebuild[1930:17346]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/341EFE94-383B-4790-BCC6-31676E3719F0/Session-WebDriverAgentRunner-2016-10-25_150041-mp9sMO.log
> > 
> > xctest-client.js:156:14 [master] pid:1742 2016-10-25 15:00:41.071 xcodebuild[1930:17334] [MT] IDETestOperationsObserverDebug: (EA02FE34-8CE4-41F0-ABB1-9EBEE2280499) Beginning test session WebDriverAgentRunner-EA02FE34-8CE4-41F0-ABB1-9EBEE2280499 at 2016-10-25 15:00:41.070 with Xcode 8A218a on target <DVTiOSDevice: 0x7fe91ca3a4c0> {
> >         deviceSerialNumber:         C7JQDD3GGRY5
> >         identifier:                 648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> >         deviceClass:                iPhone
> >         deviceName:                 Isnowball🌻💐
> >         deviceIdentifier:           648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> >         productVersion:             10.0.1
> >         buildVersion:               14A403
> >         deviceSoftwareVersion:      10.0.1 (14A403)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12061245440
> >         deviceAvailableCapacity:    1379184640
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7fe91c660cf0 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (10.0.1 (14A403))
> > 
> > xctest-client.js:156:14 [master] pid:1742 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/cc7272f975cd8eaea1b5077d22f2da4b/648171a0c9d444af498dcc9d675dd81d8e1f8dd0/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Intermediates/CodeCoverage/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.fLBOoj/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.fLBOoj/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:1742 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.fLBOoj/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:1742 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.fLBOoj/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:1742 2016-10-25 15:00:53.951 xcodebuild[1752:17619]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/0354B396-263D-4C12-AB68-43E0E9C5636E/Session-WebDriverAgentRunner-2016-10-25_150053-ED9XiE.log
> > 
> > xctest-client.js:156:14 [master] pid:1742 2016-10-25 15:00:54.352 xcodebuild[1930:17334] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
> > 
> > xctest-client.js:156:14 [master] pid:1742 2016-10-25 15:00:56.905 xcodebuild[1930:17338]  # **_[DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application's data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application's data container path does not exist.,](`
> 
> url

`)_*\* com.apple.dtdevicekit.stacktrace=(
    0   DTDeviceKitBase                     0x00000001150bc3cb DTDKCreateNSError + 113
    1   DTDeviceKitBase                     0x00000001150bcb09 DTDK_AMDErrorToNSError + 791
    2   DTDeviceKitBase                     0x00000001150ce2f5 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 100
    3   DTDeviceKitBase                     0x00000001150cd1d1 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_4 + 22
    4   DTDeviceKitBase                     0x00000001150bf317 __DTDKExecuteInSession_block_invoke + 38
    5   DTDeviceKitBase                     0x00000001150be940 __DTDKExecuteWithConnection_block_invoke_2 + 477
    6   DTDeviceKitBase                     0x00000001150be73c __DTDKExecuteWithConnection_block_invoke + 107
    7   libdispatch.dylib                   0x00007fff8e40a128 _dispatch_client_callout + 8
    8   libdispatch.dylib                   0x00007fff8e40ad62 _dispatch_barrier_sync_f_invoke + 83
    9   libdispatch.dylib                   0x00007fff8e415674 _dispatch_barrier_sync_f_slow + 540
    10  DVTFoundation                       0x000000010c745bef DVTDispatchBarrierSync + 206
    11  DVTFoundation                       0x000000010c72259b -[DVTDispatchLock performLockedBlock:] + 116
    12  DTDeviceKitBase                     0x00000001150be646 DTDKExecuteWithConnection + 223
    13  DTDeviceKitBase                     0x00000001150bf2a1 DTDKExecuteInSession + 121
    14  DTDeviceKitBase                     0x00000001150cd108 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 117
    15  DVTFoundation                       0x000000010c744f4b __DVTDispatchAsync_block_invoke + 827
    16  libdispatch.dylib                   0x00007fff8e412f5f _dispatch_call_block_and_release + 12
    17  libdispatch.dylib                   0x00007fff8e40a128 _dispatch_client_callout + 8
    18  libdispatch.dylib                   0x00007fff8e41fc10 _dispatch_continuation_pop + 533
    19  libdispatch.dylib                   0x00007fff8e416ea3 _dispatch_async_redirect_invoke + 734
    20  libdispatch.dylib                   0x00007fff8e40bee0 _dispatch_root_queue_drain + 476
    21  libdispatch.dylib                   0x00007fff8e40bcb7 _dispatch_worker_thread3 + 99
    22  libsystem_pthread.dylib             0x00007fff8e656746 _pthread_wqthread + 1299
    23  libsystem_pthread.dylib             0x00007fff8e656221 start_wqthread + 13
), # **_NSLocalizedRecoverySuggestion=The requested application's data container path does not exist., NSLocalizedDescription=The requested application's data container path does not exist.}]_**

> > xctest-client.js:156:14 [master] pid:1742
> > Testing failed:
> > 
> > xctest-client.js:156:14 [master] pid:1742    Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
> > *\* TEST FAILED **
> > 
> > xctest-client.js:164:14 [master] pid:1742 xctest client exit with code: 65, signal: null
> > xctest-client.js:156:14 [master] pid:1742 Failing tests:
> > 
> > xctest-client.js:156:14 [master] pid:1742    -[UITestingUITests testRunner]
> > *\* TEST FAILED **
> > 
> > xctest-client.js:164:14 [master] pid:1742 xctest client exit with code: 65, signal: null
> > responseHandler.js:11:12 [master] pid:1742 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.0","deviceName":"iPhone 6","udid":"648171a0c9d444af498dcc9d675dd81d8e1f8dd0","bundleId":"com.hzj.kanyunDemo","app":"/Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip"}}
> > session.js:47:10 [master] pid:1742 Creating session, sessionId: 4f055999-0e70-4663-b4c3-5376c9796da6.
> > helper.js:196:12 [master] pid:1742 Unzipping local app form /Users/farben/Desktop/kanyunDemo/app/ios-kanyunDemo.zip
> > xctest-client.js:43:14 [master] pid:1742 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
> > macaca-ios.js:144:10 [master] pid:1742 {
> >     "bundleId": "com.hzj.kanyunDemo",
> >     "platformName": "iOS",
> >     "platformVersion": "9.0",
> >     "app": "/var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/T/ios-kanyunDemo.app/"
> > }
> > xctest-client.js:183:12 [master] pid:1742 xcode version: 8.0
> > WebDriverAgent version: 1.0.28
> > xctest-client.js:123:16 [master] pid:1742 ERROR: Could not start service com.apple.syslog_relay.
> > Could not start logger for udid 648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> > 
> > xctest-client.js:156:14 [master] pid:1742 2016-10-25 15:02:41.141 xcodebuild[2085:18517]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
> > /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/976E13CB-2326-48C2-AE99-BA28E575B6FA/Session-WebDriverAgentRunner-2016-10-25_150241-3JnBFv.log
> > 2016-10-25 15:02:41.141 xcodebuild[2085:18415] [MT] IDETestOperationsObserverDebug: (DE8D5561-5D26-4DC4-B1E0-3AF1B622CC0A) Beginning test session WebDriverAgentRunner-DE8D5561-5D26-4DC4-B1E0-3AF1B622CC0A at 2016-10-25 15:02:41.140 with Xcode 8A218a on target <DVTiOSDevice: 0x7f8ed81a5770> {
> >         deviceSerialNumber:         C7JQDD3GGRY5
> >         identifier:                 648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> >         deviceClass:                iPhone
> >         deviceName:                 Isnowball🌻💐
> >         deviceIdentifier:           648171a0c9d444af498dcc9d675dd81d8e1f8dd0
> >         productVersion:             10.0.1
> >         buildVersion:               14A403
> >         deviceSoftwareVersion:      10.0.1 (14A403)
> >         deviceArchitecture:         arm64
> >         deviceTotalCapacity:        12061245440
> >         deviceAvailableCapacity:    1375174656
> >         deviceIsTransient:          NO
> >         ignored:                    NO
> >         deviceIsBusy:               NO
> >         deviceIsActivated:          YES
> >         deviceActivationState:      Activated
> >         deviceType:                 <DVTDeviceType:0x7f8ed56c6810 Xcode.DeviceType.iPhone>
> >         supportedDeviceFamilies:    (
> >     1
> > )
> >         applications:              (null)
> >         provisioningProfiles:      (null)
> >         activityProgress:          -2
> >         activityTitle:
> >         hasInternalSupport:        NO
> >         isSupportedOS:             YES
> >         developerDiskMountError:   (null)
> > (null)
> >     } (10.0.1 (14A403))
> > 
> > xctest-client.js:156:14 [master] pid:1742 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
> > state->old_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/cc7272f975cd8eaea1b5077d22f2da4b/648171a0c9d444af498dcc9d675dd81d8e1f8dd0/WebDriverAgentRunner-Runner.app
> > state->new_bundle: /Users/farben/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Intermediates/CodeCoverage/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
> > state->dst_bundle: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.5Mg8mH/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
> >     dst_ipa: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.5Mg8mH/WebDriverAgentRunner-Runner.app_sparse.ipa
> > 
> > xctest-client.js:156:14 [master] pid:1742 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.5Mg8mH/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > xctest-client.js:156:14 [master] pid:1742 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/xf/3sbrscm521v5m_4cy8fzbvcw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.5Mg8mH/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
> > 
> > ```
> > 1) "before all" hook
> > ```
> > 
> > responseHandler.js:11:12 [master] pid:1742 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> > responseHandler.js:23:14 [master] pid:1742 Send HTTP Respone to Client: 405 Method Not Allowed
> > 
> > ```
> > 2) "after all" hook
> > ```
> > 
> >   0 passing (5m)
> > 
> >   2 failing
> > 
> >   1) macaca mobile sample "before all" hook:
> >      Error: timeout of 300000ms exceeded. Ensure the done() callback is being called in this test.
> > 
> >   2) macaca mobile sample "after all" hook:
> >      Error: [quit()] Unexpected data in simpleCallback.
> >       at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
> >       at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
> >       at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
> >       at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
> >       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
> >       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
> >       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
> >       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
> >       at endReadableNT (_stream_readable.js:905:12)
> > 
> > Test completed!
> > hahahehehehehe:kanyunDemo farben$

**Comment by xudafeng** [comment]
请升级iOS驱动，参考https://testerhome.com/topics/6314
