### ISSUE TITLE
运行macaca-test-sample时mocha报错（64位win10，node 6.9.1）

### ISSUE THREAD

**Issue by keithmork** [alibaba/macaca#283]
* **Macaca Version**: 1.1.8

* **Macaca Doctor Logs**:
![image](https://cloud.githubusercontent.com/assets/5634347/19681999/2a01e38a-9ade-11e6-89f9-7a08756af96c.png)
医生这里也有点小bug……

* **Operate System**: 64位 win10家庭版

* **Programming Language**: nodejs 6.9.1

![image](https://cloud.githubusercontent.com/assets/5634347/19682036/5f0001b6-9ade-11e6-8eff-0319eed95f4a.png)
虽然这是mocha的锅，看看能不能调整下package.json之类，兼容下windows用户？：）
毕竟公司用什么机子不是自己说了算……

**Comment by xudafeng** [comment]
@keithmork

macaca -v 多少

**Comment by xudafeng** [comment]
以后按照文档上提供的，安装最新版本 https://macacajs.github.io/macaca/environment-setup.html
