### ISSUE TITLE
reliable+macaca如何集成使用

### ISSUE THREAD

**Issue by vivi-c** [alibaba/macaca#286]
- **Macaca Version**:
- **Macaca Doctor Logs**:
- **Operate System**:
- **Programming Language**:

我在本地linux虚拟机中已经装好了reliable，在本机windows系统中也装好macaca，现在想把这一套自动化框架搭建起来。
但是在网上查询资料里面，看到需要安装slave，但是目前为止没看到在linux和windows上搭建完成的样例。
请问，应该如何搭建？

**Comment by CodeToSurvive1** [comment]
windows [https://testerhome.com/topics/6318](https://testerhome.com/topics/6318)
ubuntu [https://testerhome.com/topics/6435](https://testerhome.com/topics/6435)
