### ISSUE TITLE
请教一个问题：windows桌面的exe程序能测吗？

### ISSUE THREAD

**Issue by githublue** [alibaba/macaca#290]
macaca还有一个electron驱动是测什么的，windows桌面的exe程序能测吗？

谢谢！

**Comment by meowtec** [comment]
可以考虑用按键精灵。。。

**Comment by xudafeng** [comment]
@githublue

推荐先用 https://github.com/octalmage/robotjs ，robotjs目前api还不足以标准化

**Comment by githublue** [comment]
好的  谢谢楼上两位大虾
