### ISSUE TITLE
Any example of integrating applitools with macaca test??

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#291]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by xudafeng** [comment]
https://github.com/xudafeng/macaca-test-sample-ios-ci

**Comment by mpreethi90** [comment]
@xudafeng , the link you have given is for integrating with CI. But, I would like to know if there is any way to integrate with applitool image comparison tool? Please help.
