### ISSUE TITLE
mac chrome   Selenium error

### ISSUE THREAD

**Issue by arronf2e** [alibaba/macaca#292]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**: osx
 
* **Programming Language**: javascript

这是我参考的教程: http://www.doc00.com/doc/100100isp
用macaca-electron 的时候是正常的，然后将electron换成chrome就报以下错误了
Error: [maximize()] Error response status: 6 Selenium error: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.3 x86_64)

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/266
