### ISSUE TITLE
ui recorder cli throws error 

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#293]
I get **error: unknown option `--mobile'**

**Comment by yaniswang** [comment]
https://github.com/alibaba/uirecorder

Please use beta version: npm install uirecorder@beta -g

**Comment by mpreethi90** [comment]
Is it mandatory to connect mobile to record iOS mobile actions? I am trying to check uirecorder for iPhone simulator. Can you kindly assist?

**Comment by yaniswang** [comment]
iOS has some known issues, we are fixing.

**Comment by mpreethi90** [comment]
Does uirecorder works with android emulator now? If so I can try that out now.
Kindly inform when you fix the issue for iOS.

**Comment by yaniswang** [comment]
Androis is ok

**Comment by mpreethi90** [comment]
I get error message **error: unknown option `--mobile'** when I run the command **uirecorder init --mobile**

**Comment by yaniswang** [comment]
please install beta version:

npm i uirecorder@beta -g

**Comment by mpreethi90** [comment]
@yaniswang - Can you assist with more clearer steps to work with uirecorder in android? The one given here -https://github.com/alibaba/uirecorder is not detailing steps. Please help

**Comment by yaniswang** [comment]
![image](https://cloud.githubusercontent.com/assets/970390/19952928/d104e27e-a1a3-11e6-9afa-fa3537640fd1.png)

![image](https://cloud.githubusercontent.com/assets/970390/19952934/da20974a-a1a3-11e6-8457-76915dd75926.png)

**Comment by mpreethi90** [comment]
There were several questions asked like below when I execute **uirecorder init --mobile**

? Webdriver host or ip (ip) 
? Webdriver port


Also, when I start uirecorder , it asks me specify **Test spec file name**. So, how do I input value to this?

**Comment by yaniswang** [comment]
Please install macaca first, and then connect your mobile device to local pc, or open emulator.

**Comment by mpreethi90** [comment]
Yes I have already installed macaca and have been executing tests for ios/android for a while.

I tried opening an emulator but still I get the error mentioned above.
