### ISSUE TITLE
XPATH中含有$美元符导致卡住的问题

### ISSUE THREAD

**Issue by yaniswang** [alibaba/macaca#294]
如果XPATH中有出现美元符，就会导致命令无响应，一直卡住。

XPATH如下：

	//*[@resource-id="com.taobao.taobao:id/tl_tabs"]/android.widget.LinearLayout/android.support.v7.app.ActionBar$a[2]/android.widget.RelativeLayout/android.widget.ImageView

如果将美元符删除，卡住问题消失，立马就会报找不到对象。

美元符在XPATH中应该属于特殊符号，需要进行转义，估计是某个地方没有转义，导致出现这个问题。

**Comment by yaniswang** [comment]
经过多次测试，把XPATH精简成如下：

正常：//a
卡住：//a$

**Comment by sachinGirish** [comment]
@yaniswang  Did u tried with escape character for $

**Comment by xudafeng** [comment]
You can try the new version
