### ISSUE TITLE
macaca能支持一下Android API 17吗？

### ISSUE THREAD

**Issue by githublue** [alibaba/macaca#295]
目前，我们的macaca工具支持的Android API >= 18，

前段时间发现sendKeys用不了，是因为测试真机系统版本是Android API 17，我用了一个API 18的模拟器发现sendKeys是OK的，换成API 17的模拟器就不行，我们做测试的也不能要求开发使用什么版本，就是一个辅助而已，没办法。

只能看看还有没有别的工具，发现Appium恰好支持Android API >= 17，但是感觉Appium用起来太不简单清晰了，编程上也没有macaca那么直接明了，实在不顺手，不知道咱们的macaca是否能支持一下API 17呢？

**Comment by xudafeng** [comment]
@githublue  4.4.2 份额很小了，考虑放弃吧
