### ISSUE TITLE
uirecorder 启动真机时出现错误

### ISSUE THREAD

**Issue by lynnyoo** [alibaba/macaca#296]
按照https://github.com/yaniswang/jWebDriver
设置之后，
输入命令： uirecorder start --mobile

提示：Mobile open failed, please check macaca config. Internal Server Error

macaca sever的log为：
TypeError: Cannot set property 'proxyMode' of undefined
      at Object.createDevice (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.1.0.67@webdriver-server/lib/server/controllers/session.js:16:20)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:65:19)
      at /usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:50:10)
      at Object.toPromise (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:118:63)
      at next (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:99:29)
      at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:69:7)
      at /usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:54:5
      at Object.co (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:50:10)

所连接的机器为android 7

**Comment by yaniswang** [comment]
你是在执行mocha *.spec.js时报的这个错误吧？

**Comment by lynnyoo** [comment]
抱歉，网址贴错了，uirecorder安装参考的是：
https://macacajs.github.io/macaca/recorder.html
https://github.com/alibaba/uirecorder

出现TypeError: Cannot set property 'proxyMode' of undefined 的错误
的确是在uirecorder start --mobile时
? Test spec file name test.spec.js
? App Path, extensions: apk, app /Users/1.apk

Recorder server listen on: 9765
Mobile open failed, please check macaca config. Internal Server Error



真机和虚拟机都是报这个错误

**Comment by yaniswang** [comment]
把你的macaca doctor截图发一下

**Comment by lynnyoo** [comment]
macaca-doctor version: 1.0.23


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.1

  iOS checklist:

  Xcode is installed at: `/Library/Developer/CommandLineTools`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk`
  Platforms is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk/platforms/android-19`
  Android tools is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk/tools/android`
  ADB tool is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.38

**Comment by lynnyoo** [comment]
看log说   please run: `npm install macaca-android -g`

但是执行命令  之后，
看到在执行这样的命令
> macaca-chromedriver@1.0.27 install /usr/local/lib/node_modules/macaca-android/node_modules/macaca-chromedriver
> node ./bin/macaca-chromedriver install



debug:

BUILD SUCCESSFUL
Total time: 2 seconds
build success!
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "macaca-android" "-g"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! macaca-chromedriver@1.0.27 install: `node ./bin/macaca-chromedriver install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the macaca-chromedriver@1.0.27 install script 'node ./bin/macaca-chromedriver install'.
npm ERR! This is most likely a problem with the macaca-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/macaca-chromedriver install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs macaca-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls macaca-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/npm-debug.log




我之前安装过了chromedriver，这个macaca-chromedriver@1.0.27要怎么安装呢？
尝试过了以下方法：
https://libraries.io/npm/macaca-chromedriver

还不是不知道怎么安装 @xudafeng

**Comment by xudafeng** [comment]
@lynnyoo 安装过程中的报错发一下

**Comment by lynnyoo** [comment]
$ npm i macaca-chromedriver --save-dev

|
> macaca-chromedriver@1.0.27 install /Users/apple/node_modules/macaca-chromedriver
> node ./bin/macaca-chromedriver install

>> chromedriver cdn url: http://npm.taobao.org/mirrors/chromedriver/2.20/chromedriver_mac32.zip
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND npm.taobao.org npm.taobao.org:80
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "macaca-chromedriver" "--save-dev"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! macaca-chromedriver@1.0.27 install: `node ./bin/macaca-chromedriver install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the macaca-chromedriver@1.0.27 install script 'node ./bin/macaca-chromedriver install'.
npm ERR! This is most likely a problem with the macaca-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/macaca-chromedriver install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs macaca-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls macaca-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/npm-debug.log

**Comment by lynnyoo** [comment]
`$ npm i macaca-android -g`

npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
 
> uiautomator-client@1.0.30 install /usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client
> node ./scripts/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
Updated
file ./build.xml
Buildfile: /usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client/build.xml
-check-env:
[checkenv] Android SDK Tools Revision 22.3.0
[checkenv] Installed at /Applications/adt-bundle-mac-x86_64-20131030/sdk
-build-setup:
[getbuildtools] Using latest Build Tools: 19.0.0
[echo] Resolving Build Target for uiautomator-bootstrap...
[getuitarget] Project Target:   Android 4.4
[getuitarget] API level:        19
[echo] ----------

[echo] Creating output directories if needed...

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client/bin

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client/bin/classes

-pre-compile:

compile:

[javac] Compiling 26 source files to /usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client/bin/classes

[javac] 警告: [options] ソース値1.5は廃止されていて、今後のリリースで削除される予定です

[javac] 警告: [options] ターゲット値1.5は廃止されていて、今後のリリースで削除される予定です

[javac] 警告: [options] 廃止されたオプションについての警告を表示しないようにするには、-Xlint:オプションを使用します。

[javac] 注意:/usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client/src/com/android/uiautomator/client/XmlUtils/ReflectionUtils.javaの操作は、未チェックまたは安全ではありません。
    [javac] 注意:詳細は、-Xlint:uncheckedオプションを指定して再コンパイルしてください。
    [javac] 警告3個
-post-compile:
-dex:
[dex] input: /usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client/bin/classes

[dex] Converting compiled files and external libraries into /usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client/bin/classes.dex...
-post-dex:
-jar:
[jar] Building jar: /usr/local/lib/node_modules/macaca-android/node_modules/uiautomator-client/bin/uiautomator-bootstrap.jar
-post-jar:
build:
BUILD SUCCESSFUL
Total time: 3 seconds
uiautomator-bootstrap build success!
 
> android-unicode@1.0.9 install /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode
> node ./script/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
Buildfile: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/build.xml
-set-mode-check:
-set-debug-files:
-check-env:

[checkenv] Android SDK Tools Revision 22.3.0
[checkenv] Installed at /Applications/adt-bundle-mac-x86_64-20131030/sdk
-setup:
[echo] Project Name: android_unicode_ime
[gettype] Project Type: Application
-set-debug-mode:

-debug-obfuscation-check:
-pre-build:
-build-setup:
[getbuildtools] Using latest Build Tools: 19.0.0
[echo] Resolving Build Target for android_unicode_ime...

[gettarget] Project Target:   Android 4.4
[gettarget] API level:        19
[echo] ----------
[echo] Creating output directories if needed...

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/libs
[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin
[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res
[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/rsObj

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/rsLibs

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/gen
[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/classes
    [mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/dexedLibs
[echo] ----------
[echo] Resolving Dependencies for android_unicode_ime...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency]

[dependency] ------------------
[echo] ----------
[echo] Building Libraries with 'debug'...

[subant] No sub-builds to iterate on
-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
[echo] Handling aidl files...

[aidl] No AIDL files to compile.
[echo] ----------

[echo] Handling RenderScript files...
[echo] ----------
[echo] Handling Resources...
[aapt] Generating resource IDs...
[echo] ----------
[echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.
-pre-compile:
-compile:
[javac] Compiling 4 source files to /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/classes
[javac] 警告: [options] ソース値1.5は廃止されていて、今後のリリースで削除される予定です
[javac] 警告: [options] ターゲット値1.5は廃止されていて、今後のリリースで削除される予定です
[javac] 警告: [options] 廃止されたオプションについての警告を表示しないようにするには、-Xlint:オプションを使用します。
[javac] 警告3個
-post-compile:
-obfuscate:
-dex:

[dex] input: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/classes
[dex] Converting compiled files and external libraries into /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/classes.dex...
-crunch:
[crunch] Crunching PNG Files in source dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/res
[crunch] To destination dir: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res
   [crunch] Processing image to cache: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/res/mipmap-hdpi/ic_launcher.png => /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res/mipmap-hdpi/ic_launcher.png
[crunch]   (processed image to cache entry /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res/mipmap-hdpi/ic_launcher.png: 0% size of source)
[crunch] Processing image to cache: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/res/mipmap-mdpi/ic_launcher.png => /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res/mipmap-mdpi/ic_launcher.png

[crunch]   (processed image to cache entry /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res/mipmap-mdpi/ic_launcher.png: 0% size of source)
[crunch] Processing image to cache: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/res/mipmap-xhdpi/ic_launcher.png => /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res/mipmap-xhdpi/ic_launcher.png
[crunch]   (processed image to cache entry /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res/mipmap-xhdpi/ic_launcher.png: 84% size of source)
[crunch] Processing image to cache: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/res/mipmap-xxhdpi/ic_launcher.png => /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res/mipmap-xxhdpi/ic_launcher.png

[crunch]   (processed image to cache entry /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/res/mipmap-xxhdpi/ic_launcher.png: 53% size of source)
   [crunch] Crunched 4 PNG files to update cache

-package-resources:
     [aapt] Creating full resource package...
-package:

[apkbuilder] Current build type is different than previous build: forced apkbuilder run.
[apkbuilder] Creating android_unicode_ime-debug-unaligned.apk and signing it with a debug key...

-post-package:
-do-debug:
[zipalign] Running zip align on final apk...
[echo] Debug Package: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/android_unicode_ime-debug.apk
[propertyfile] Creating new property file: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/build.prop
[propertyfile] Updating property file: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/build.prop
[propertyfile] Updating property file: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/build.prop
[propertyfile] Updating property file: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/bin/build.prop
-post-build:

debug:

BUILD SUCCESSFUL
Total time: 2 seconds
build success!
 
> unlock-apk@0.1.16 install /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk
> node ./script/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
Buildfile: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/build.xml
-set-mode-check:
-set-debug-files:
-check-env:

[checkenv] Android SDK Tools Revision 22.3.0
[checkenv] Installed at /Applications/adt-bundle-mac-x86_64-20131030/sdk

-setup:

[echo] Project Name: unlock_apk
[gettype] Project Type: Application
-set-debug-mode:
-debug-obfuscation-check:

-pre-build:
-build-setup:

[getbuildtools] Using latest Build Tools: 19.0.0

[echo] Resolving Build Target for unlock_apk...

[gettarget] Project Target:   Android 4.4
[gettarget] API level:        19

[gettarget] WARNING: No minSdkVersion value set. Application will install on all Android versions.
[echo] ----------

[echo] Creating output directories if needed...

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/libs

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/rsObj

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/rsLibs

[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/gen
[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/classes
[mkdir] Created dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/dexedLibs
[echo] ----------

[echo] Resolving Dependencies for unlock_apk...

[dependency] Library dependencies:

[dependency] No Libraries

[dependency]

[dependency] ------------------

[echo] ----------
[echo] Building Libraries with 'debug'...
[subant] No sub-builds to iterate on
-code-gen:

[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.

[echo] Handling aidl files...
[aidl] No AIDL files to compile.
[echo] ----------

[echo] Handling RenderScript files...
[echo] ----------
[echo] Handling Resources...

[aapt] Generating resource IDs...

[echo] ----------
[echo] Handling BuildConfig class...

[buildconfig] Generating BuildConfig class.
-pre-compile:
-compile:
[javac] Compiling 3 source files to /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/classes
[javac] 警告: [options] ソース値1.5は廃止されていて、今後のリリースで削除される予定です
[javac] 警告: [options] ターゲット値1.5は廃止されていて、今後のリリースで削除される予定です
[javac] 警告: [options] 廃止されたオプションについての警告を表示しないようにするには、-Xlint:オプションを使用します。
[javac] 注意:/usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/src/xdf/android_unlock/MainActivity.javaは非推奨のAPIを使用またはオーバーライドしています。
    [javac] 注意:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。
    [javac] 警告3個
-post-compile:

-obfuscate:
-dex:
[dex] input: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/classes
[dex] Converting compiled files and external libraries into /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/classes.dex...
-crunch:
[crunch] Crunching PNG Files in source dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/res
   [crunch] To destination dir: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res
   [crunch] Processing image to cache: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/res/mipmap-hdpi/ic_launcher.png => /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res/mipmap-hdpi/ic_launcher.png
[crunch]   (processed image to cache entry /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res/mipmap-hdpi/ic_launcher.png: 0% size of source)
   [crunch] Processing image to cache: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/res/mipmap-mdpi/ic_launcher.png => /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res/mipmap-mdpi/ic_launcher.png
[crunch]   (processed image to cache entry /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res/mipmap-mdpi/ic_launcher.png: 0% size of source)
[crunch] Processing image to cache: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/res/mipmap-xhdpi/ic_launcher.png => /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res/mipmap-xhdpi/ic_launcher.png
[crunch]   (processed image to cache entry /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res/mipmap-xhdpi/ic_launcher.png: 84% size of source)
[crunch] Processing image to cache: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/res/mipmap-xxhdpi/ic_launcher.png => /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res/mipmap-xxhdpi/ic_launcher.png

[crunch]   (processed image to cache entry /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/res/mipmap-xxhdpi/ic_launcher.png: 53% size of source)
   [crunch] Crunched 4 PNG files to update cache
-package-resources:

[aapt] Creating full resource package...
-package:
[apkbuilder] Current build type is different than previous build: forced apkbuilder run.
[apkbuilder] Creating unlock_apk-debug-unaligned.apk and signing it with a debug key...
-post-package:

-do-debug:

[zipalign] Running zip align on final apk...
[echo] Debug Package: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/unlock_apk-debug.apk
[propertyfile] Creating new property file: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/build.prop
[propertyfile] Updating property file: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/build.prop

[propertyfile] Updating property file: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/build.prop

[propertyfile] Updating property file: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/bin/build.prop
-post-build:
debug:
BUILD SUCCESSFUL
Total time: 1 second

build success!
|
> macaca-chromedriver@1.0.27 install /usr/local/lib/node_modules/macaca-android/node_modules/macaca-chromedriver
> node ./bin/macaca-chromedriver install

>> chromedriver cdn url: http://npm.taobao.org/mirrors/chromedriver/2.20/chromedriver_mac32.zip
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND npm.taobao.org npm.taobao.org:80
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "macaca-android" "-g"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! macaca-chromedriver@1.0.27 install: `node ./bin/macaca-chromedriver install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the macaca-chromedriver@1.0.27 install script 'node ./bin/macaca-chromedriver install'.
npm ERR! This is most likely a problem with the macaca-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/macaca-chromedriver install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs macaca-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls macaca-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/npm-debug.log

**Comment by xudafeng** [comment]
网络原因

**Comment by greengreen1** [comment]
安装驱动报错 npm i macaca-android -g，
macaca doctor信息如下：
 macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.6.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/home/uc/android-sdk-linux`
  Platforms is set to `/home/uc/android-sdk-linux/platforms/android-23`
  Android tools is set to `/home/uc/android-sdk-linux/tools/android`
  ADB tool is set to `/home/uc/android-sdk-linux/platform-tools/adb`

  Installed driver list:

  electron: 1.1.5
但node -v显示的版本确实4.4
v4.4.4


错误信息如下：
Linux 3.2.0-29-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "macaca-android" "-g"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! unlock-apk@0.1.16 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unlock-apk@0.1.16 install script 'node ./script/build.js'.
npm ERR! This is most likely a problem with the unlock-apk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs unlock-apk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls unlock-apk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/uc/npm-debug.log
