### ISSUE TITLE
iOS真机app-inspector不可用

### ISSUE THREAD

**Issue by mercynoo** [alibaba/macaca#297]
开启--verbose的日志如下：
>> xctest-client.js:156:14 [master] pid:4938 2016-11-06 23:05:36.126 xcodebuild[4942:157144]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/leicl/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/A88F5E02-7A0D-46E5-9A3D-611FE18A24AD/Session-WebDriverAgentRunner-2016-11-06_230536-ym1vCS.log

>> xctest-client.js:156:14 [master] pid:4938 2016-11-06 23:05:36.126 xcodebuild[4942:157141] [MT] IDETestOperationsObserverDebug: (62D089DA-3720-4BF5-9A85-879380BBF07B) Beginning test session WebDriverAgentRunner-62D089DA-3720-4BF5-9A85-879380BBF07B at 2016-11-06 23:05:36.125 with Xcode 8B62 on target <DVTiOSDevice: 0x7fd9b016d0d0> {
		deviceSerialNumber:         DNTLG5BLFP6J
		identifier:                 602d56be7b97fad29bd3a20c6820403a4a17ce83
		deviceClass:                iPhone
		deviceName:                 iPhone
		deviceIdentifier:           602d56be7b97fad29bd3a20c6820403a4a17ce83
		productVersion:             10.0.2
		buildVersion:               14A456
		deviceSoftwareVersion:      10.0.2 (14A456)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12201926656
		deviceAvailableCapacity:    1172471808
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fd9afe45990 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.0.2 (14A456))

>> xctest-client.js:156:14 [master] pid:4938 2016-11-06 23:05:39.810 xcodebuild[4942:157141] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/leicl/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/A88F5E02-7A0D-46E5-9A3D-611FE18A24AD/Session-WebDriverAgentRunner-2016-11-06_230536-ym1vCS.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/leicl/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/A88F5E02-7A0D-46E5-9A3D-611FE18A24AD/Session-WebDriverAgentRunner-2016-11-06_230536-ym1vCS.log}

>> xctest-client.js:156:14 [master] pid:4938 
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.

>> xctest-client.js:156:14 [master] pid:4938 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:164:14 [master] pid:4938 xctest client exit with code: 65, signal: null
  <-- GET /
  --> GET / 200

5s，10.1系统 app-inspector是1.2.14

**Comment by mercynoo** [comment]
同时我用8.4系统的真机报错是：
>> xctest-client.js:156:14 [master] pid:5676 xcodebuild: error: The run destination MiniAlice is not valid for Testing the scheme 'WebDriverAgentRunner'.
	MiniAlice’s iOS 8.4 doesn’t match WebDriverAgentRunner.xctest’s iOS 9.3 deployment target. Upgrade MiniAlice’s iOS version or lower WebDriverAgentRunner.xctest’s deployment target.

>> xctest-client.js:164:14 [master] pid:5676 xctest client exit with code: 70, signal: null

**Comment by mercynoo** [comment]
请问该怎么解决这种问题

**Comment by xudafeng** [comment]
MiniAlice’s iOS 8.4 升级一下

**Comment by mercynoo** [comment]
公司测试机 不可以擅自升级。我现在换了9.3.3的系统，报错如下：


>> xctest-client.js:156:14 [master] pid:13970 
Testing failed:
	No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.
** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:164:14 [master] pid:13970 xctest client exit with code: 65, signal: null

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5953

**Comment by xudafeng** [comment]
https://testerhome.com/topics/6314
