### ISSUE TITLE
Mac os 安装不上macaca-android

### ISSUE THREAD

**Issue by lynnyoo** [alibaba/macaca#298]
系统环境为：Mac 10.8
网络环境：目前设置了淘宝镜像
所用命令：  $ npm install -g cnpm --registry=http://registry.npm.taobao.org 

$ cnpm install macaca-android -g

[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 100ms, retry left 4, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":1,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 200ms, retry left 3, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":2,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 300ms, retry left 2, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":3,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 400ms, retry left 1, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":4,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 100ms, retry left 4, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":6,"closeSocketCount":5,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 200ms, retry left 3, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":7,"closeSocketCount":6,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 300ms, retry left 2, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":8,"closeSocketCount":7,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npm.taobao.org/binary-mirror-config/latest after 400ms, retry left 1, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":9,"closeSocketCount":8,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://r.cnpmjs.org/binary-mirror-config/latest after 100ms, retry left 4, error: RequestError: getaddrinfo ENOTFOUND r.cnpmjs.org r.cnpmjs.org:443 (req "error"), GET https://r.cnpmjs.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":11,"closeSocketCount":10,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"r.cnpmjs.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://r.cnpmjs.org/binary-mirror-config/latest after 200ms, retry left 3, error: RequestError: getaddrinfo ENOTFOUND r.cnpmjs.org r.cnpmjs.org:443 (req "error"), GET https://r.cnpmjs.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":12,"closeSocketCount":11,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"r.cnpmjs.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://r.cnpmjs.org/binary-mirror-config/latest after 300ms, retry left 2, error: RequestError: getaddrinfo ENOTFOUND r.cnpmjs.org r.cnpmjs.org:443 (req "error"), GET https://r.cnpmjs.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":13,"closeSocketCount":12,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"r.cnpmjs.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://r.cnpmjs.org/binary-mirror-config/latest after 400ms, retry left 1, error: RequestError: getaddrinfo ENOTFOUND r.cnpmjs.org r.cnpmjs.org:443 (req "error"), GET https://r.cnpmjs.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":14,"closeSocketCount":13,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"r.cnpmjs.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npmjs.org/binary-mirror-config/latest after 100ms, retry left 4, error: RequestError: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443 (req "error"), GET https://registry.npmjs.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":16,"closeSocketCount":15,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npmjs.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npmjs.org/binary-mirror-config/latest after 200ms, retry left 3, error: RequestError: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443 (req "error"), GET https://registry.npmjs.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":17,"closeSocketCount":16,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npmjs.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npmjs.org/binary-mirror-config/latest after 300ms, retry left 2, error: RequestError: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443 (req "error"), GET https://registry.npmjs.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":18,"closeSocketCount":17,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npmjs.org:443::::::::":1},"requests":{}})
headers: {}
[npminstall:get] retry GET https://registry.npmjs.org/binary-mirror-config/latest after 400ms, retry left 1, error: RequestError: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443 (req "error"), GET https://registry.npmjs.org/binary-mirror-config/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":19,"closeSocketCount":18,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npmjs.org:443::::::::":1},"requests":{}})
headers: {}
Get /binary-mirror-config/latest from https://registry.npm.taobao.org error: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
⠙ [npminstall:get] retry GET https://registry.npm.taobao.org/macaca-android/latest after 100ms, retry left 4, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/macaca-android/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":21,"closeSocketCount":20,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443:::::::true:":1},"requests":{}})
headers: {}
⠹ Installing macaca-android@*[npminstall:get] retry GET https://registry.npm.taobao.org/macaca-android/latest after 200ms, retry left 3, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/macaca-android/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":22,"closeSocketCount":21,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443:::::::true:":1},"requests":{}})
headers: {}
⠴ Installing macaca-android@*[npminstall:get] retry GET https://registry.npm.taobao.org/macaca-android/latest after 300ms, retry left 2, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/macaca-android/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":23,"closeSocketCount":22,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443:::::::true:":1},"requests":{}})
headers: {}
⠇ Installing macaca-android@*[npminstall:get] retry GET https://registry.npm.taobao.org/macaca-android/latest after 400ms, retry left 1, error: RequestError: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443 (req "error"), GET https://registry.npm.taobao.org/macaca-android/latest -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":24,"closeSocketCount":23,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"registry.npm.taobao.org:443:::::::true:":1},"requests":{}})
headers: {}
⠸ Installing macaca-android@*Error: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443
    at errnoException (dns.js:27:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
npminstall version: 2.11.2
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/apple/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org macaca-android -g

**Comment by xudafeng** [comment]
网络问题吧
