### ISSUE TITLE
iOS app-inspector真机启动报错

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#299]
真机启动，启动时WebDriver能正常安装到手机，启动之后闪一下退出。登录WEB页面，一直是wait device start...
日志如下：
>> app-inspector.js:42:10 [master] pid:16973 server start at: http://192.168.1.104:5679
>> xctest-client.js:46:14 [master] pid:16973 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:215:12 [master] pid:16973 xcode version: 8.1
>> WebDriverAgent version: 1.0.28
>> xctest-client.js:196:14 [master] pid:16973 xctest client exit with code: 208, signal: null
>> xctest-client.js:160:14 [master] pid:16973 2016-11-08 15:13:13.810 xcodebuild[16979:147502]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/xunlei/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/A6437C84-5A5A-4C72-A051-B7DEC768D1CF/Session-WebDriverAgentRunner-2016-11-08_151313-DNCtrf.log

>> xctest-client.js:160:14 [master] pid:16973 2016-11-08 15:13:13.811 xcodebuild[16979:147499] [MT] IDETestOperationsObserverDebug: (BAF87F97-A351-4661-BE29-43EE7753B1B4) Beginning test session WebDriverAgentRunner-BAF87F97-A351-4661-BE29-43EE7753B1B4 at 2016-11-08 15:13:13.807 with Xcode 8B62 on target <DVTiOSDevice: 0x7fb8f413c750> {
		deviceSerialNumber:         F2MR2LFJGRX5
		identifier:                
		deviceClass:               
		deviceName:                 
		deviceIdentifier:          
		productVersion:             10.1.1
		buildVersion:               14B100
		deviceSoftwareVersion:      10.1.1 (14B100)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        58891735040
		deviceAvailableCapacity:    45434368000
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fb8f3ecd350 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.1.1 (14B100))

>> xctest-client.js:160:14 [master] pid:16973 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/q4/2skydwf51sv1g0l4ht4rtnvh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/762362255d8938e4bcacf0933e9c56e0/b2f922f52494975d66bc15a7d914ca1824216154/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/xunlei/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/q4/2skydwf51sv1g0l4ht4rtnvh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.0BZ3Nm/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/q4/2skydwf51sv1g0l4ht4rtnvh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.0BZ3Nm/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:160:14 [master] pid:16973 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/q4/2skydwf51sv1g0l4ht4rtnvh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.0BZ3Nm/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:160:14 [master] pid:16973 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/q4/2skydwf51sv1g0l4ht4rtnvh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.0BZ3Nm/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:160:14 [master] pid:16973 2016-11-08 15:13:22.724 xcodebuild[16979:147499] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

>> xctest-client.js:160:14 [master] pid:16973 
Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

>> xctest-client.js:160:14 [master] pid:16973 ** TEST FAILED **

>> xctest-client.js:168:14 [master] pid:16973 xctest client exit with code: 65, signal: null

**Comment by xudafeng** [comment]
https://testerhome.com/topics/6328

**Comment by zsmjluo** [comment]
@xudafeng 操作步骤基本上一样 不知道为啥有问题

**Comment by xudafeng** [comment]
SDK 什么版本

**Comment by xudafeng** [comment]
@zsmjluo xcode什么版本 macaca doctor贴一下

**Comment by zsmjluo** [comment]
xcode8.1

  macaca-doctor version: 1.0.27
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.0.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

  ios: 1.0.41

**Comment by xudafeng** [comment]
闪一下就退是正常现象

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/317
