### ISSUE TITLE
Macaca【建议】and【需求】

### ISSUE THREAD

**Issue by TediWang** [alibaba/macaca#30]
1. Macaca 关于Keyboard使用过程的KeyCode的支持，例如完成Done，delete按钮等
2. Macaca 有强大的Assert，能否提供相应的sample或者document。断言在case中是非常关键的
3. Macaca 创建模块化的sample，比如公共组件可以模块化被调用测试。

**Comment by xudafeng** [comment]
@zenzhu @tsj1107 @kobe990 一起关注下

**Comment by xudafeng** [comment]
@TediWang Assert 可以看这里 https://testerhome.com/topics/4644

**Comment by louisHeb** [comment]
@xudafeng assert 急需完善文档啊，求解<span class="cost_price">￥999.00</span>这种怎么assert
