### ISSUE TITLE
API 文档标识支持平台

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#300]
主要是区分移动端和传统web

**Comment by guoqx123** [comment]
我现在就想用移动端app的,不知道用那些

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/268

**Comment by xudafeng** [comment]
@zenzhu python 的按照js版的贴一下

**Comment by zenzhu** [comment]
已更新 https://github.com/macacajs/wd.py/pull/20/commits/b07a882d61636d61afbe9b4f05d0a3463b560ff4
