### ISSUE TITLE
更新成usb驱动后，也会出现socket hang up的错误

### ISSUE THREAD

**Issue by fengytn** [alibaba/macaca#304]
* **Macaca Version**: 1.1.16

* **Macaca Doctor Logs**:

  macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_73`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/bita/Library/Android/sdk`
  Platforms is set to `/Users/bita/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/bita/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/bita/Library/Android/sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.41

* **Operate System**: ios 10.12.1

* **Programming Language**: python

***ios真机 iphone6plus 10.1.1
xcode 8.1
更新完usb驱动后，跑之前的case，一共跑了三条case，单条run的时候case都能passed.
但是把三条case连起来跑，到第二条一半的时候总是会报错
log如下：

>> proxy.js:58:18 [master] pid:27587 xctest client proxy error with: Error: socket hang up
/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> proxy.js:58:18 [master] pid:27587 xctest client proxy error with: Error: socket hang up
    at Logger.error (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback] (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:346:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zsmjluo** [comment]
表示遇到了同样的问题。。。

**Comment by fengerapple** [comment]
我也遇到了，执行第一遍是ok的，再执行就会报这个错

**Comment by xudafeng** [comment]
@fengytn 能提供个简单的示例吗，我这边不复现

**Comment by huangejuan** [comment]
示例：
@Before
    public void setUp() throws Exception {
        JSONObject porps = new JSONObject();
        porps.put("platformName", "iOS");
        porps.put("autoAcceptAlerts", true);
        //porps.put("app", "./app/" + platform + "-app-bootstrap.zip");
        //porps.put("reuse", 1);
        porps.put("bundleId", "com.nd.sdp.component.debug");
        porps.put("platformVersion", "9.3.2");
        porps.put("deviceName", "iPhone 6s");
        porps.put("udid", "8dd542865fd408128d0276d16c9a9d77802987b9" );
        JSONObject desiredCapabilities = new JSONObject();
        desiredCapabilities.put("desiredCapabilities", porps);
        driver.initDriver(desiredCapabilities); **//请求失败**
    }
还是报异常信息：
Error: >> proxy.js:58:18 [master] pid:5654 xctest client proxy error with: Error: socket hang up

**Comment by xudafeng** [comment]
@huangejuan 你提供的这些信息看不出问题

**Comment by huangejuan** [comment]
@xudafeng 这是相关配置：
macaca-doctor version: 1.0.27
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home`
  ANDROID_HOME is not set

  Installed driver list:

  ios: 1.0.41

**Comment by xudafeng** [comment]
localhost:3456 failed to respond 

你server开启了吗

**Comment by huangejuan** [comment]
@xudafengadmindeMac-mini:~ nd-mac$ macaca server --verbose
>> request.js:24:12 [master] pid:6012 get remote update info failed.
>> index.js:17:12 [master] pid:6013 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '172.18.162.225',
  host: 'admindeMac-mini.local',
  loaded_time: '2016-11-11 18:50:12' }
>> middlewares.js:17:10 [master] pid:6013 base middlewares attached
>> router.js:129:10 [master] pid:6013 router set
>> webdriver sdk launched

**Comment by 183181731** [comment]
xctest-client.js中的iproxy的端口转发有问题，我把端口的LOG打出来了。可以看出两个都是8906，
这样执行的就是iproxy 8906 8906，这样肯定是有问题的。我尝试了写死成8100，8100 就成功启动了。
···
>> index.js:17:12 [master] pid:15363 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '192.168.241.195',
  host: 'QA-wangdeMac-mini.local',
  loaded_time: '2016-11-11 22:13:26' }
>> middlewares.js:17:10 [master] pid:15363 base middlewares attached
>> router.js:129:10 [master] pid:15363 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:15363 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformVerison":"10.1","platformName":"iOS","bundleId":"com.nd.app.factory.jianggongyouth","udid":"c4ac25813b981d253b518fb88b511ad024be2709","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:15363 Creating session, sessionId: f345dff3-5edd-44ec-af45-bfe26ecec784.
>> xctest-client.js:48:14 [master] pid:15363 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:144:10 [master] pid:15363 {
	"bundleId": "com.nd.app.factory.jianggongyouth",
	"platformName": "iOS",
	"browserName": "firefox"
}
>> xctest-client start with port: 8906
>> xctest-client.js:224:12 [master] pid:15363 xcode version: 8.1
>> xctest-client.js:227:14 [master] pid:15363 is realdevice......
>> xctest-client.js:178:14 [master] pid:15363 Port:8906,8906 .........
>> WebDriverAgent version: 1.0.28
>> xctest-client.js:162:14 [master] pid:15363 2016-11-11 22:13:34.392 xcodebuild[15373:1828067] [MT] IDETestOperationsObserverDebug: (22E635C7-C518-41B9-9965-B52FD192DF08) Beginning test session 
···

**Comment by 183181731** [comment]
···
*startIproxy() {
    this.proxyPort = 8100;//我加进去的
    let args = [this.proxyPort, this.proxyPort];  //这两个proxyPort参数长一样。。。
      logger.debug(`Port:${args} .........`);

    const IOS_USBMUXD_IPROXY = 'iproxy';
    const binPath = yield _.exec(`which ${IOS_USBMUXD_IPROXY}`);
···

**Comment by fengerapple** [comment]
`macaca server --verbose
>> index.js:17:12 [master] pid:3065 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '30.96.176.36',
  host: 'fengdeMacBook-Air.local',
  loaded_time: '2016-11-12 12:41:55' }
>> middlewares.js:17:10 [master] pid:3065 base middlewares attached
>> router.js:129:10 [master] pid:3065 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:3065 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"reuse":2,"platformVersion":"9.3","autoAcceptAlerts":true,"deviceName":"iPhone 6 Plus","platformName":"iOS","autoDismissAlerts":true,"udid":"fd2d4a71ffb6d15d955c837cec7884281e1561d4","bundleId":"dgf.ios-app-bootstrap"}}
>> session.js:47:10 [master] pid:3065 Creating session, sessionId: 5c62b195-6259-457b-8e97-c3b39829f3a3.
>> xctest-client.js:48:14 [master] pid:3065 project path: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.28@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:144:10 [master] pid:3065 {
	"bundleId": "dgf.ios-app-bootstrap",
	"platformVersion": "9.3",
	"platformName": "iOS"
}
>> xctest-client start with port: 8902
>> xctest-client.js:223:12 [master] pid:3065 xcode version: 8.1
>> WebDriverAgent version: 1.0.28
>> xctest-client.js:162:14 [master] pid:3065 2016-11-12 12:42:28.361 xcodebuild[3083:146830]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/feng/Library/Developer/Xcode/DerivedData/WebDriverAgent-bagqeermmcadmcctywbyvbqewyeo/Logs/Test/333497B9-1DC4-4130-87AC-A9CF02BEA000/Session-WebDriverAgentRunner-2016-11-12_124228-7KP38A.log
2016-11-12 12:42:28.361 xcodebuild[3083:146827] [MT] IDETestOperationsObserverDebug: (256BCA73-EE71-4831-9DA6-DA2C98603A15) Beginning test session WebDriverAgentRunner-256BCA73-EE71-4831-9DA6-DA2C98603A15 at 2016-11-12 12:42:28.359 with Xcode 8B62 on target <DVTiOSDevice: 0x7f8c34321810> {
		deviceSerialNumber:         FK1NP1CJG5QQ
		identifier:                 fd2d4a71ffb6d15d955c837cec7884281e1561d4
		deviceClass:                iPhone
		deviceName:                 dgf
		deviceIdentifier:           fd2d4a71ffb6d15d955c837cec7884281e1561d4
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12524146688
		deviceAvailableCapacity:    2039246848
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7f8c33de9f10 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.5 (13G36))

>> xctest-client.js:163:14 [master] pid:3065 please check project: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.28@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:162:14 [master] pid:3065 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/gv/pws8vdzn6fx01vzb4_5dt3r40000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/2388c03a4b8b71c4738455f51b437cb5/fd2d4a71ffb6d15d955c837cec7884281e1561d4/ManifestCache.plist

>> xctest-client.js:163:14 [master] pid:3065 please check project: /usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.28@webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:54:14 [master] pid:3065 Proxy: /session:POST to http://127.0.0.1:8902/session:POST with body: {"desiredCapabilities":{"bundleId":"dgf.ios-app-bootstrap","platformVersion":"9.3","platformName":"iOS"}}
>> proxy.js:58:18 [master] pid:3065 xctest client proxy error with: Error: socket hang up
/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.5@xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> proxy.js:58:18 [master] pid:3065 xctest client proxy error with: Error: socket hang up
    at Logger.error (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.5@xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback] (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.22@xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.2.69.0@request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.2.69.0@request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:344:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by huangejuan** [comment]
@xudafeng  183181731 正解，xctest-client.js 真机端口转换的代码逻辑不对，需要你们修改呃

**Comment by xudafeng** [comment]
@183181731 Macaca 没有使用8100端口，如果你用8100端口启动成功，那你需要把手机中的其他工程构建的wda删除

**Comment by xudafeng** [comment]
@huangejuan @183181731 Macaca端口是从8900起始的，发现占用便递增以支持多设备并行，如果占用到8906请用ps -ef 查看并删除未死进程。

进程偶尔结束不掉的问题还在持续排查

**Comment by 183181731** [comment]
@xudafeng  了解，看来macaca改过wda的工程了。。那真机使用的wda重签名是要用xctest-client下的wda工程去重签了？因为我之前用的都是facebook上的wda重签后替换到xctest-client下，我觉得很多人估计都是因为这个才造成的hand up

**Comment by xudafeng** [comment]
@183181731 是有二次开发过，不要用fb提供的仓库了。

等新iOS驱动开发好后就会彻底替换掉wda

**Comment by fengytn** [comment]
@xudafeng 还需要示例吗？我没弄明白你要哪部分示例。

**Comment by fengytn** [comment]
@183181731 @xudafeng  WDA不是更新后成usb后，运行macaca server时自动装的吗？那个自动安装的不是facebook的WDA吧。我是把我手机上原先的WDA删除了，运行macaca server时如何不删除原先的WDA会报错。

**Comment by lylh** [comment]
@xudafeng 
是否有Appium 一样的resetApp https://github.com/appium/appium/issues/7019
貌似也可以解决socket hang up https://github.com/appium/appium/issues/7063

**Comment by huangejuan** [comment]
@xudafeng  usb问题可以了，但是请问一下，app-inspector 现在是不是只支持10.x的ios系统，9.x的系统一直运行不起来？

**Comment by CleverPotato** [comment]
我在iOS10上跑几乎没什么问题，在iOS9.3上跑，只能跑一次，再想跑就得重启手机才行，不然一直socket hang up@xudafeng，另外我还想请教一下，macaca里的WDA和appium16里的WDA能用一个签名吗。

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/317

**Comment by xudafeng** [comment]
https://github.com/macacajs/xctest-client/pull/15

**Comment by xudafeng** [comment]
请各位更新macaca-ios 看是否还有稳定性问题

**Comment by CleverPotato** [comment]
是npm i -g macaca-ios？我现在App-inspector完全打不开了= =

**Comment by CleverPotato** [comment]
`>> proxy.js:54:14 [master] pid:7571 Proxy: /session:POST to http://127.0.0.1:8909/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:58:18 [master] pid:7571 xctest client proxy error with: Error: socket hang up
/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> proxy.js:58:18 [master] pid:7571 xctest client proxy error with: Error: socket hang up
    at Logger.error (/usr/local/lib/node_modules/app-inspector/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request.request [as _callback] (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:345:9)
    at emitNone (events.js:91:20)`

**Comment by xudafeng** [comment]
重装App-inspector

**Comment by one-inch** [comment]
@xudafeng feng大哥，请问下这个问题目前解决了吗？我用的测试示例，目前还是会出现这个问题，初次运行是可以的，之后就会一直出现socket hang up。
测试环境：macaca-ios是V2.0.18；WDA是facebook上clone下来后重签名自己安装到设备的。
另：上述中说到的二次开发后的WDA工程我应该去哪里获取呢？现版本安装后的macaca-ios下好像并没有此工程。执行macaca server现在也不会自动安装WDA，是否可以考虑把安装WDA这步重新加到自动化里去。
看到望回复！
