### ISSUE TITLE
ios端滑动、拖动问题

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#306]
查看API后，在ios端分别使用滑动相关的接口moveTo、swipe、flick均提示“is not a function”。
请问下，在ios端如何实现滑动、拖动操作。

**Comment by xudafeng** [comment]
swipe

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-test-sample/blob/master/macaca-test/macaca-mobile-sample.test.js#L99

**Comment by zsmjluo** [comment]
@xudafeng 我使用swipe接口时报错：
>>   1) macaca mobile sample #5 test5:
     TypeError: driver.swipe is not a function

用例如下：
  it('#5 test5', function() {
    return driver
      .swipe(200, 400, 200, 100, 500);
  });

**Comment by xudafeng** [comment]
@zsmjluo https://travis-ci.org/xudafeng/macaca-test-sample-ios-ci#L3869

**Comment by zsmjluo** [comment]
@xudafeng 你的意思是你在模拟器上是可以的吗？我用的时候一直报TypeError: this.swipe is not a function

**Comment by zsmjluo** [comment]
@xudafeng 我在想我这个错误有没有可能是我的环境有问题？函数不存在，是不是我这缺少什么模块。

**Comment by zsmjluo** [comment]
我的是真机6s plus 10.1.0

**Comment by xudafeng** [comment]
@zsmjluo 只有swipe不行？能试试别的吗

**Comment by zsmjluo** [comment]
@xudafeng 几个滑动类的接口都不行（moveTo、swipe、flick），其它的接口像截图、点击、元素查找、sendkeys等等都很正常。操作类的接口其实需要的不多，能点击、滑动拖动就行。挺着急的，麻烦帮忙排查一下是什么原因。

**Comment by zsmjluo** [comment]
@xudafeng 用例的场景就是列表下滑或者上滑，app首次安装时引导页的滑动。

**Comment by xudafeng** [comment]
@zsmjluo swipe支持的，你可以跑sample看看 前面贴给你了

**Comment by zsmjluo** [comment]
@xudafeng 我在想是不是我的wd模块问题，用例执行时报错提示没有wd模块，所以我在工程目录执行npm install wd安装了wd。但是我刚看sample的node_modules里面也没有wd。

**Comment by zsmjluo** [comment]
@xudafeng 知道原因了，之前写用例参考的原来的sample，sample里面是wd的获取是wd = require('wd')，正确的写法应该是wd = require('maraca-wd')。或者根据最新的sample，require('webdriver-client')(_.merge({}, platform === 'ios' ? iOSOpts : androidOpts));
