### ISSUE TITLE
macaca uirecorder 运行真机时，报错

### ISSUE THREAD

**Issue by lynnyoo** [alibaba/macaca#308]
执行命令顺序如下：
（1）macaca server --port 4444
（2）uirecorder init --mobile
（3）uirecorder start --mobile
此时出现错误：
? Test spec file name test.spec.js
? App Path, extensions: apk, app   test.apk

Recorder server listen on: 9765
Mobile open failed, please check macaca config. Internal Server Error

server log为：
>> uiautomator-client.js:31:12 [master] pid:6642 uiautomator-bootstrap was not found in: /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.1.0.30@uiautomator-client/bin/uiautomator-bootstrap.jar, please check your Android ENV

  Error: >> uiautomator-client.js:31:12 [master] pid:6642 uiautomator-bootstrap was not found in: /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.1.0.30@uiautomator-client/bin/uiautomator-bootstrap.jar, please check your Android ENV
      at Logger.error (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.1.0.5@xlogger/lib/xlogger.js:169:9)
      at UIAutomator.init (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.1.0.30@uiautomator-client/lib/uiautomator-client.js:31:12)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:65:19)

 当前macaca环境如下：
macaca doctor

  macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.4

  iOS checklist:

  Xcode is installed at: `/Library/Developer/CommandLineTools`
  Xcode Command Line Tools is ready, version: 2343.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk`
  Platforms is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk/platforms/android-19`
  Android tools is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk/tools/android`
  ADB tool is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk/platform-tools/adb`

  Installed driver list:

  android: 1.0.39
  electron: 1.1.4
  ios: 1.0.38 [out-of-date]

**Comment by xudafeng** [comment]
android_npminstall/node_modules/.1.0.30@uiautomator-client/bin/uiautomator-bootstrap.jar, please check your Android ENV

**Comment by lynnyoo** [comment]
已解决，重装了macaca-chome和macaca-android
