### ISSUE TITLE
xcode8 自动处理证书脚本

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#309]

**Comment by Frozenaria** [comment]
主要是修改`WebDriverAgent.xcodeproj/project.pbxproj`文件内
`DevelopmentTeam = 4A847D3N3T;  
PRODUCT_BUNDLE_IDENTIFIER = com.XXX.XXX.uitest;`
这两个参数
`DevelopmentTeam`原值为空，填开发者自己的Team编号
`PRODUCT_BUNDLE_IDENTIFIER`原值好像是`com.facebook.WebDriverAgentCoreTests`之类，改成你需要的就行
比较方便的方法是写个shell用sed命令替换

**Comment by xudafeng** [comment]
https://github.com/xudafeng/webdriveragent/commit/65b588e884a894b286cea153ea7628d2e42dfa94

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/323

**Comment by xudafeng** [comment]
https://testerhome.com/topics/6503

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/332

**Comment by huangejuan** [comment]
**1.执行脚本，macaca server 端异常：**
>> xctest-client.js:145:16 [master] pid:590 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:255:14 [master] pid:590 Fail to start xctest: undefined
>> responseHandler.js:54:12 [master] pid:590 Send Error Respone to Client: undefined

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (node.js:369:9)

>> xctest-client.js:209:14 [master] pid:590 iproxy exit with code: null, signal: SIGKILL
**2.执行app-inspector -u xxxx 命令异常**
port: 5678 was occupied, changed port: 5679 xctest-client.js:58:14 [master] pid:41295 project path not found app-inspector:66:44 [master] pid:41295 Error: >> xctest-client.js:58:14 [master] pid:41295 project path not found at Logger.error (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.5@xlogger/lib/xlogger.js:169:9) at XCTest.checkProjectPath (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.28@xctest-client/lib/xctest-client.js:58:14) at XCTest.init (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.28@xctest-client/lib/xctest-client.js:51:10) at XCTest (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.0.28@xctest-client/lib/xctest-client.js:39:10) at Object.exports.initDevice (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.1.2.15@app-inspector/lib/ios.js:90:12) at next (native) at onFulfilled (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:65:19) at /usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:54:5 at co (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:50:10) at toPromise (/usr/local/lib/node_modules/.app-inspector_npminstall/node_modules/.4.6.0@co/index.js:118:63)
