### ISSUE TITLE
macaca run 指定端口执行脚本报错

### ISSUE THREAD

**Issue by SmallBlackboard** [alibaba/macaca#320]
运行报错如下：

$ macaca run -p 8888 -d macaca-mobile-2.test.js --verbose
>> index.js:17:12 [master] pid:4592 webdriver server start with config:
 { port: '8888',
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.156.1',
  host: 'shishy',
  loaded_time: '2016-11-21 16:11:04' }
>> middlewares.js:17:10 [master] pid:4592 base middlewares attached
>> router.js:129:10 [master] pid:4592 router set
>> webdriver sdk launched
>>

>>

>>   macaca mobile sample

>>
>>     1) "before all" hook

>>
>>     2) "after all" hook

>>

>>   0 passing (3s)
  2 failing

>>

>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"Android","udid":"DU2MYN146D002912","app":"E:\\github\\BOCmacaca\\macaca-test-sample\\app\\android-app-bootstrap.zip"})] connect ECONNREFUSED 127.0.0.1:3456
  Error: connect ECONNREFUSED 127.0.0.1:3456
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

>>   2) macaca mobile sample "after all" hook:
     [quit()] connect ECONNREFUSED 127.0.0.1:3456
  Error: connect ECONNREFUSED 127.0.0.1:3456
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

>> Test completed!

运行macaca doctor 如下：
$ macaca doctor

  macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v4.5.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\javasoftware\javajdk8`
  ANDROID_HOME is set to `F:\android-sdk-windows`
  Platforms is set to `F:\android-sdk-windows\platforms\android-24`
  Android tools is set to `F:\android-sdk-windows\tools\android.bat`
  ADB tool is set to `F:\android-sdk-windows\platform-tools\adb.exe`
  ANT_HOME is set to `E:\20161104windows\apache-ant-1.9.7`

  Installed driver list:

  android: 1.0.39 [out-of-date]
  chrome: 1.0.4
  electron: 1.1.4
  ios: 1.0.40 [out-of-date]

**Comment by SmallBlackboard** [comment]
为什么启动时指定了以端口8888启动，它起了一个8888的server，却又去找端口3456的server？？？

**Comment by zenzhu** [comment]
你客户端用的什么包，wd ? 那个脚本里面也得设置端口号。

**Comment by SmallBlackboard** [comment]
用的是全局安装的macaca-cli，1.1.16版本

**Comment by SmallBlackboard** [comment]
怎么写可以用指定的端口去跑脚本？

**Comment by CodeToSurvive1** [comment]
@SmallBlackboard  之前的版本这么运行脚本不是没问题吗？macaca run -p 8888 -d macaca-mobile-2.test.js --verbose

**Comment by zenzhu** [comment]
@SmallBlackboard 我是说测试用例中用的是 webdriver-client ?

**Comment by SmallBlackboard** [comment]
@zenzhu 用例中的"webdriver-client": "~1.0.0"

**Comment by zenzhu** [comment]
试一下
```
wd.initPromiseChain({ port: 8888})
```

**Comment by SmallBlackboard** [comment]
@zenzhu 加上这个确实可以了
