### ISSUE TITLE
'deviceName' value not picking up correct simulator/emulator in both iOS and android

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#322]
When I add a variable '**deviceName**' and version in iOS, it does not pick up correctly.
For example, in iOS I entered `platformVersion=9.1 deviceName='iPhone 6' `  but everytime macaca picks up 'iPhone 6' '**9.3**' instead of '**9.1**'

Similarly in android, when I add a variable 'Nexus 6' or 'Nexus One' etc., macaca picks up only the emulator that is displayed at the top of the list in AVD list of android studio IDE.

Please help.

**Comment by xudafeng** [comment]
udid work

**Comment by mpreethi90** [comment]
@xudafeng , thank you for the suggestion. But , the problem with udid is that when I trigger macaca in CI , I cannot be very sure of the udid in that machine.

**Comment by xudafeng** [comment]
travis?

**Comment by mpreethi90** [comment]
Yes

**Comment by xudafeng** [comment]
@mpreethi90 https://github.com/macacajs/macaca-test-sample/blob/master/README.md#ci-sample

**Comment by mpreethi90** [comment]
@xudafeng , I don't get what are you trying to telling through that link? Please assist
