### ISSUE TITLE
JavaScript 版 API hasElement  elementOrNull elementIfExists 没有正确返回

### ISSUE THREAD

**Issue by septem123** [alibaba/macaca#325]
代码如图所示 
![qq 20161123205348](https://cloud.githubusercontent.com/assets/6112395/20562554/23b444e4-b1bf-11e6-9b5e-9f570af51b95.png)
执行结果 elementOrNull没有返回null 而是报错
![qq 20161123205328](https://cloud.githubusercontent.com/assets/6112395/20562558/2e80f6b0-b1bf-11e6-85f6-6dcc38880bac.png)

hasElement elementIfExists也不会返回 False

**Comment by septem123** [comment]
@xdf

**Comment by zenzhu** [comment]
经研究，这应该 macaca-android 的实现问题，使用 elementsByClassName 类似的时候，如果找不到元素，不该返回报错，直接返回空数组即可。
https://github.com/macacajs/uiautomator-client/blob/master/src/com/android/uiautomator/client/cmd/Find.java#L55

**Comment by septem123** [comment]
@zenzhu 那么 这个缺陷可以修复吗

**Comment by zenzhu** [comment]
@septem123 等 @kobe990 更新下 macaca-android 就可以了。

**Comment by zenzhu** [comment]
已修复，请更新 macaca-android, npm i -g macaca-android。
https://github.com/macacajs/uiautomator-client/commit/e15d7a52f0d8ff214685d12a8af11d19bbc3cde1
