### ISSUE TITLE
Error: $JAVA_HOME is not set appears while building in travis CI

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#326]
I had configured macaca to travis CI. I have also set *JAVA_HOME* as my environment variable. Just before the macaca cli, I make sure `echo $JAVA_HOME` prints correct value. But, when I execute `npm install` , the control fails while installing `uiautomator-client` saying `Error: $JAVA_HOME is not set`

Kindly assist

**Comment by xudafeng** [comment]
https://macacajs.com/using-with-ci

**Comment by mpreethi90** [comment]
@xudafeng , I have already reviewed the doc and had successfully setup for iOS. But, for android the  $JAVA_HOME variable just print the script above `npm install`. But, when doing npm install it fails. That is the reason I raised the ticket.

**Comment by mpreethi90** [comment]
And please try not to close the ticket before understanding the real problem.
