### ISSUE TITLE
js版本如何捕获case中的异常

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#327]
当案例执行过程中出现异常，比如macaca中的一些元素查找api查不到元素时直接抛异常，应该怎样捕获这个异常来做一些异常处理，比如做个截图操作！比较着急，望指点！

**Comment by zsmjluo** [comment]
@xudafeng

**Comment by xudafeng** [comment]
.catch 为什么截图会出异常？

**Comment by zsmjluo** [comment]
明白了，用.catch可以捕获异常
