### ISSUE TITLE
macaca doctor建议提示安卓驱动支持的范围，比如android: 1.1.1【16-24】，现在最新的已经25了

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#328]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

如题，macaca doctor建议提示安卓驱动支持的安卓版本范围，比如android: 1.1.1【16-24】，现在最新的已经25了，免得已经只下载了25的相关sdk，运行却报错

**Comment by xudafeng** [comment]
https://macacajs.com/zh/environment-setup

**Comment by CodeToSurvive1** [comment]
好的  不过现在已经支持24版本了

**Comment by xudafeng** [comment]
@CodeToSurvive1 疏漏了，已更新
