### ISSUE TITLE
Error: $JAVA_HOME is not set appears while building in travis CI

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#329]
@xudafeng , I have already reviewed the doc and had successfully setup for iOS. But, for android the $JAVA_HOME variable just print the script above npm install. But, when doing npm install it fails. That is the reason I raised the ticket.

**Comment by xudafeng** [comment]
https://github.com/xudafeng/macaca-test-sample-android-ci/blob/master/.travis.yml
