### ISSUE TITLE
response 404 when i use element.location.get('x') in Android whith python

### ISSUE THREAD

**Issue by ThunderStorm1503** [alibaba/macaca#330]
* **Macaca Version**:
 1.1.16
* **Macaca Doctor Logs**:
macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.8.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/Admin/Public/Android/sdk`
  Platforms is set to `/Users/Admin/Public/Android/sdk/platforms/android-24`
  Android tools is set to `/Users/Admin/Public/Android/sdk/tools/android`
  ADB tool is set to `/Users/Admin/Public/Android/sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.1
  electron: 1.1.4
  ios: 1.0.42 [out-of-date]

* **Operate System**:
Mac OS 10.12.1 
* **Programming Language**:
python

I use the sample code:https://github.com/macacajs/macaca-test-sample-python
and I  add  "print els[1].location.get('x')"    in  testcase:test_01_login

the code like  this:
      els = self.driver \
            .elements_by_class_name('android.widget.EditText')
        print els[1].location.get('x')

the log shows:
HTTPError: 404 Client Error: Not Found for url: http://localhost:3456/wd/hub/session/92921395-5161-4575-b7ec-d1dddfb4ae82/element/3/location

**Comment by xudafeng** [comment]
https://macacajs.github.io/macaca-wd/#getProperty

**Comment by xudafeng** [comment]
https://macacajs.github.io/wd.java/

**Comment by xudafeng** [comment]
getProperty 

Support: Android iOS Web(WebView), Android iOS can only get `origin` `size`

**Comment by xudafeng** [comment]
@zenzhu python 的加一下

**Comment by xudafeng** [comment]
@ThunderStorm1503 

getProperty 

Support: Android iOS Web(WebView), Android iOS can only get `origin` `size`

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.py/commit/91537faaf67caa2018fdf80dab7b1703f0e4cb72

**Comment by zenzhu** [comment]
文档和代码均已更新，升级到 wd 0.1.4 即可。安卓上可以使用 
```
els[1].getProperty('origin').x
```
