### ISSUE TITLE
控件选择器增加模糊匹配

### ISSUE THREAD

**Issue by Yinxl** [alibaba/macaca#331]
希望控件查找的时候能增加模糊匹配的功能，类似appium所支持的功能：
https://github.com/appium/appium-uiauto/blob/3052dace828db2ab3d722281fb7853cbcbc3252f/uiauto/appium/app.js#L68

**Comment by xudafeng** [comment]
@Yinxl 万能选择器适合在业务逻辑中封装

**Comment by xudafeng** [comment]
在外围实现
