### ISSUE TITLE
Test does not fail when 'waitForElement' has error response

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#333]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by brucejcw** [comment]
@mpreethi90 what error ?  
[waitForElement](https://macacajs.github.io/macaca-wd/#waitForElement) should add suffix, e.g., `waitForElementByClassName`

**Comment by mpreethi90** [comment]
@brucejcw , say I have a line in my test suite `.waitForElementByName(loginPage.Elements.EmailTextField, 10000, 1000)`. When the element is not found within 10000, the test just moves to next step and in the console I get *NoSuchElement: An element could not be located on the page using the given search parameters.*. But, the test itself does not fail.

**Comment by brucejcw** [comment]
update `macaca-wd` and try again

**Comment by brucejcw** [comment]
update `macaca-wd` and re-try

**Comment by mpreethi90** [comment]
Thank you. let me try

**Comment by mpreethi90** [comment]
@brucejcw , I tried updating macaca-wd and running the test. But even now, the test passes when the 'waitForElementByName()' dos not return with element

**Comment by mpreethi90** [comment]
@brucejcw , can you kindly assist on this issue?

**Comment by mpreethi90** [comment]
**My webdriver-client version is 1.0.15**
PFB the test report -
`>> responseHandler.js:11:12 [master] pid:50114 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/3d59c77e-57b4-41e1-b4f1-6d7981c35713/element, jsonBody: {"using":"name","value":"Log In"}
>> proxy.js:54:14 [master] pid:50114 Proxy: /wd/hub/session/3d59c77e-57b4-41e1-b4f1-6d7981c35713/element:POST to http://192.168.1.17:8100/session/8D33F8F7-D905-4F5D-A09C-F28FC1C87EF8/element:POST with body: {"using":"name","value":"Log In"}
>> proxy.js:67:16 [master] pid:50114 Got response with status 200: {"value":{},"sessionId":"3d59c77e-57b4-41e1-b4f1-6d7981c35713","status":0}
>> session.js:107:14 [master] pid:50114 Send HTTP Respone to Client: {"value":"{}","sessionId":"3d59c77e-57b4-41e1-b4f1-6d7981c35713","status":0}
>> proxy.js:67:16 [master] pid:50114 Got response with status 200: {"value":{"using":"name","value":"Log In","description":"unable to find an element"},"sessionId":"3d59c77e-57b4-41e1-b4f1-6d7981c35713","status":7}
>> session.js:107:14 [master] pid:50114 Send HTTP Respone to Client: {"value":"{\"using\":\"name\",\"value\":\"Log In\",\"description\":\"unable to find an element\"}","sessionId":"3d59c77e-57b4-41e1-b4f1-6d7981c35713","status":7}
>> 
>>     ✓ TS01-7-01,TS01-7-02-Existing free subscription user can log-in-Email (2399ms)

`
