### ISSUE TITLE
Windows7环境下Android驱动安装不成功，后面跑Android测试用例的时候一直报错，求大神帮忙

### ISSUE THREAD

**Issue by freechenh** [alibaba/macaca#334]
![qq 20161129101721](https://cloud.githubusercontent.com/assets/24238297/20693987/0b35541e-b61d-11e6-8e12-3bea2f990baa.png)

![qq 20161129101721](https://cloud.githubusercontent.com/assets/24238297/20694009/35021c96-b61d-11e6-80aa-073cd5256f87.png)

* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by freechenh** [comment]
![qq 20161129101811](https://cloud.githubusercontent.com/assets/24238297/20694032/63e8df9a-b61d-11e6-874b-2d687edc08e2.png)
log贴错了一张，就是安装Android驱动的时候提示node-modules这个文件夹需要删除，然后我删除了以后，重新安装，还是提示这个错误

**Comment by freechenh** [comment]
![qq 20161129101811](https://cloud.githubusercontent.com/assets/24238297/20694032/63e8df9a-b61d-11e6-874b-2d687edc08e2.png)
log贴错了一张，就是安装Android驱动的时候提示node-modules这个文件夹需要删除，然后我删除了以后，重新安装，还是提示这个错误

**Comment by freechenh** [comment]
![android](https://cloud.githubusercontent.com/assets/24238297/20694163/3bb8331c-b61e-11e6-8b2f-b56156aebd4e.png)
跑Android用例的时候提示before all hook/after all hook这个不明白是什么意思，网上没有找到类似的问题

**Comment by freechenh** [comment]
![android](https://cloud.githubusercontent.com/assets/24238297/20694163/3bb8331c-b61e-11e6-8b2f-b56156aebd4e.png)
跑Android用例的时候提示before all hook/after all hook这个不明白是什么意思，网上没有找到类似的问题

**Comment by freechenh** [comment]
![default](https://cloud.githubusercontent.com/assets/24238297/20695620/62e0bd06-b628-11e6-9b39-cd5718982692.png)

**Comment by zenzhu** [comment]
贴出 macaca doctor

**Comment by freechenh** [comment]
![macacadoctor](https://cloud.githubusercontent.com/assets/24238297/20702644/9f934c98-b653-11e6-8580-af344087810f.png)
我后面把所有的软件都重新安装了一遍，现在貌似驱动已经没有问题了，但是跑Android用例的时候还是会出问题，这个新的log
![mobilesample](https://cloud.githubusercontent.com/assets/24238297/20702687/e024b4f4-b653-11e6-9fc0-910ea210228b.png)

**Comment by freechenh** [comment]
https://testerhome.com/topics/5483    我参考的是这个文章，前面都没有问题，就是跑用例的时候提示这个错误了

**Comment by Archer456** [comment]
@freechenh 

执行npm i 为样例项目安装需要的执行环境依赖

切到 D:\macaca\macaca-test-sample-master目录下

  C:\Users\cmd>d:
      D:\>cd macaca\macaca-test-sample-master
      D:\macaca\macaca-test-sample-master>npm i     

你到这里执行npm i 了吗？

**Comment by freechenh** [comment]
@Archer456 我之前有执行过npm i了，是每次执行用例之前都需要npm i吗？

**Comment by freechenh** [comment]
![npm i](https://cloud.githubusercontent.com/assets/24238297/20705215/0f7fd054-b65d-11e6-8e2f-aa1b339042d2.png)
不行，先执行了npm i    然后在执行测试用例还是同样的问题

**Comment by Archer456** [comment]
@freechenh   那你换genymotion 虚拟机 试下   你连的好像是真机？

**Comment by freechenh** [comment]
@Archer456 不是····我用的是AVD···············不知道是不是虚拟机的问题，genymotion还没有安装，我的是Windows，我记得你之前有个和我类似的问题，不过你的好像是mac是吧

**Comment by Archer456** [comment]
@freechenh   我三环境通吃  win10  ubuntu  mac  哈哈哈哈  都是好的  不过都是用的genymotion

**Comment by freechenh** [comment]
@Archer456 我试一下用genymotion····如果是虚拟机的问题就好说了

**Comment by freechenh** [comment]
@zenzhu 求帮忙这个是什么问题

**Comment by zenzhu** [comment]
macaca run 后面加上 --verbose 吧，现在日志太少

**Comment by freechenh** [comment]
![verbose](https://cloud.githubusercontent.com/assets/24238297/20736102/682c35f8-b6df-11e6-9c6e-f2a99e655688.png)
@zenzhu 这个是添加了verbose的输出日志

**Comment by freechenh** [comment]
@Archer456 不是模拟器的问题，我换了模拟器以后还是提示一样的情况
![genymotion](https://cloud.githubusercontent.com/assets/24238297/20738511/8c2ee5b8-b6ee-11e6-87fc-22302dd698fa.png)

**Comment by zenzhu** [comment]
你运行的时候模拟器有打开吗？还是直接就挂了，要不你先打开你模拟器看看

**Comment by freechenh** [comment]
恩，模拟器是先打开的，刚在群里问了一下，可能是我的adb没有配置好，我再重新试一下 ，看一下情况怎么样，谢谢了@zenzhu

**Comment by freechenh** [comment]
已经可以了······应该是SDK那边没有配置好，还有就是模拟器的问题，模拟器版本要改成API16以上的，然后adb devices -l的时候就可以成功，然后脚本有的地方被改动了一下出错了，只要改一下platform“iOS”变成“Android”就可以了，然后模拟器建议用genymotion的，速度比较快，然后adb的连接方式改成SDK的，还有跑的时候记得npm i要不然会提示找不到模块········差不多就酱，然后谢谢 @zenzhu @Archer456 两位的帮忙

**Comment by Kirkowo** [comment]
![image](https://cloud.githubusercontent.com/assets/22292039/21538320/c20cfb12-cdd6-11e6-87bd-b98eca027e8d.png)
你好，这是我通过macaca doctor检测出来 安装的驱动，然后我运行 npm i -g macaca-android 安装android的驱动，但是效果如下。
![image](https://cloud.githubusercontent.com/assets/22292039/21538333/f8c9c798-cdd6-11e6-961a-ca22a40a3067.png)
再次运行macaca doctor 还是检测出没有安装android驱动，安装的步骤以及通过cnpm 安装 我也安装了3 4遍，但是，还是没有找到症结所在。希望，能帮助一下。

**Comment by freechenh** [comment]
@Kirkowo 你确定你的Android驱动已经安装好了吗？在安装的过程中是不是有中断操作什么的

**Comment by Kirkowo** [comment]
@freechenh   通过cnpm i -g macaca-android 的那个图，
![image](https://cloud.githubusercontent.com/assets/22292039/21538610/ca1f22a0-cdd9-11e6-9f51-7eaf0112cdd8.png)
然后 不知道症结在哪。。

**Comment by freechenh** [comment]
@Kirkowo 你都是按照那个步骤来的吗，有没有哪一步漏了，还是没有安装好，这个我也有点蒙蔽了

**Comment by Kirkowo** [comment]
@freechenh  我按照这个上面来的。。http://www.jianshu.com/p/a92bde80cf0a 发现自己还是不可用之后 又找了虫师的教程 又重新安装了一遍 （把之前安装的也卸载了）。。 别的同事安装成功了 但是不知道自己出错在哪里。。

**Comment by freechenh** [comment]
@Kirkowo 蛋疼了········我也不是很清楚了，爱莫能助，群里问问其他人吧，或者多npm i macaca-Android -g安装几遍试试，没准是因为网络的原因

**Comment by Kirkowo** [comment]
@freechenh  好的 谢谢了 我再去群里问看看。

**Comment by Kirkowo** [comment]
@freechenh  解决了 是因为系统变量配置的原因 我配置到成员变量上去了 应该配置到成员变量里面去。

**Comment by freechenh** [comment]
@Kirkowo 解决了就好············这样的问题真是不好发现
