### ISSUE TITLE
macaca-java版waitForElement问题

### ISSUE THREAD

**Issue by guoqx123** [alibaba/macaca#335]
@xudafeng 
macaca-java版中的waitForElement方法在控件未加载成功的情况下，不能正常进行循环查找，直接返回异常，在debug时发现elementExist = isElementExist(wayToFind, value);此只返回true和异常，不能返回false,致使不能够循环
public MacacaClient waitForElement(GetElementWay wayToFind,String value) throws Exception{
		int count = 0;
		int timeLeft = waitElementTimeout;
		boolean satisfied = false;
		while (timeLeft > 0) {
			boolean elementExist = false;
			System.out.println(String.format("attempt to search the element for %d times", count++));
			elementExist = isElementExist(wayToFind, value);
			if (!elementExist) {
				// not find element ,keep searching
				this.sleep(waitElementTimeInterval);
				timeLeft -= waitElementTimeInterval;
			} else {
				// finded , break
				satisfied = true;
				getElement(wayToFind, value);
				break;
			}
		}
		if (satisfied == false) {
			System.out.println("can't find the element:" + value);
			throw new Exception();
		}
		return this;
	}

**Comment by kobe990** [comment]
@guoqx123 试试直接调waitForElementByXXX这些方法能否成功

**Comment by WilliamStark** [comment]
这个问题现在还有啊 请问如何解决
