### ISSUE TITLE
建议uiautomator-client的/src/com/android/uiautomator/client/cmd/GetProperties.java类增加一些属性的获取

### ISSUE THREAD

**Issue by septem123** [alibaba/macaca#336]
看了源代码 目前只有
![d2 lr hb2 ua c 6wfmlj](https://cloud.githubusercontent.com/assets/6112395/20719959/7e1b9f4e-b698-11e6-816b-613a9b0ed443.png)
origin size text description这几种
希望能顺手增加一些
比如说下图的这些 工作中经常可能用到
![wq189w1tqmdam41f izuw3q](https://cloud.githubusercontent.com/assets/6112395/20720019/b8c9410a-b698-11e6-807a-0b85f6afbb10.png)
@zenzhu

**Comment by xudafeng** [comment]
增加后需要同步改文档

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-wd/commit/e0b8da1d66dbb005370e2f456494259e54f1c391

**Comment by kobe990** [comment]
https://github.com/macacajs/uiautomator-client/pull/33

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/commit/31b4ffc6b041de534c8efa79afcbd9fba058dc2a @kobe990

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.java/pull/76/files
