### ISSUE TITLE
升级node.js 为6.9.1LTS版本后，重新部署macaca  Installed driver list 有报错

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#337]
C:\Users\cmd>node -v
v6.9.1

C:\Users\cmd>npm -v
3.10.8

C:\Users\cmd>macaca -v

  1.1.16

C:\Users\cmd>macaca doctor

  macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.9.1

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_111`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-24`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  ANT_HOME is set to `D:\apache-ant-1.9.7`

  Installed driver list:

(node:8612) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
  android: 1.1.2
  chrome: 1.0.5
  electron: 1.1.4

请帮助查明为何报错

  Installed driver list:

(node:8612) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined

**Comment by Archer456** [comment]
C:\Users\cmd>npm -v
4.0.2

C:\Users\cmd>node -v
v6.9.1

C:\Users\cmd>macaca -v

  1.1.16


C:\Users\cmd>macaca doctor

  macaca-doctor version: 1.0.27


  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.9.1

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_111`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-24`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  ANT_HOME is set to `D:\apache-ant-1.9.7`

  Installed driver list:

(node:11404) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
  android: 1.1.2
  chrome: 1.0.5
  electron: 1.1.4


升级了下npm为lastest 4.0.2  依旧报错

**Comment by xudafeng** [comment]
```
(node:11404) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
```

这个Node promise的一个bug吧？@zenzhu

**Comment by xudafeng** [comment]
怀疑docter有问题，但是MacOS 6.91 7.x 都不出这个warn，不复现啊

**Comment by xudafeng** [comment]
新版Node的warn，需要解决掉的

**Comment by xudafeng** [comment]
已解决，请重新安装macaca-cli
