### ISSUE TITLE
虚拟机的Ubuntu14.04 运行不了案例

### ISSUE THREAD

**Issue by Linjianhan** [alibaba/macaca#338]
root@ubuntu:/macaca/macaca-test-sample# make test-pc
macaca doctor

  macaca-doctor version: 1.0.27

  Node.js checklist:

  node env: /opt/nodejs/bin/node
  node version: v6.9.1

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/opt/android-sdk-linux`
  Platforms is set to `/opt/android-sdk-linux/platforms/android-24`
  Android tools is set to `/opt/android-sdk-linux/tools/android`
  ADB tool is set to `/opt/android-sdk-linux/platform-tools/adb`

  Installed driver list:

(node:5395) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
  chrome: 1.0.5
  electron: 1.1.4
  ios: 1.0.46

macaca run --verbose -d ./macaca-test/macaca-desktop-sample.test.js
>> index.js:17:12 [master] pid:5431 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.8.128',
  host: 'ubuntu',
  loaded_time: '2016-11-29 18:45:50' }
>> middlewares.js:17:10 [master] pid:5431 base middlewares attached
>> router.js:129:10 [master] pid:5431 router set
>> webdriver sdk launched
>> 

>> 
  macaca desktop sample

>> responseHandler.js:11:12 [master] pid:5431 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"browserName":"chrome","platformName":"desktop","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:5431 Creating session, sessionId: 50abbf7e-266b-45ad-b033-b4158a441dde.
>> chromedriver bin path: /opt/nodejs/lib/node_modules/macaca-chrome/node_modules/macaca-chromedriver/exec/chromedriver
>> Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:52:14 [master] pid:5431 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body: 
Error: chromedriver proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9515
    at Request.request [as _callback] (/opt/nodejs/lib/node_modules/macaca-chrome/node_modules/macaca-chromedriver/lib/proxy.js:56:25)
    at self.callback (/opt/nodejs/lib/node_modules/macaca-chrome/node_modules/request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/opt/nodejs/lib/node_modules/macaca-chrome/node_modules/request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
>> proxy.js:52:14 [master] pid:5431 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body: 
>> proxy.js:58:16 [master] pid:5431 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Linux\",\"version\":\"3.13.0-101-generic\"}}}"
>> proxy.js:52:14 [master] pid:5431 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"autoAcceptAlerts":true,"browserName":"chrome","platformName":"desktop","version":"","javascriptEnabled":true,"platform":"ANY","show":true}}
>> proxy.js:58:16 [master] pid:5431 Got response with status 200: {"sessionId":"7e4b3b1e52ca9c67ecff603f31af674e","status":13,"value":{"message":"unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c8...
>> chromedriver ready with: {"sessionId":null,"status":13,"value":{"message":"unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-101-generic x86_64)"}}
>> responseHandler.js:47:14 [master] pid:5431 Send HTTP Respone to Client: {"sessionId":"50abbf7e-266b-45ad-b033-b4158a441dde","status":0,"value":"{\"autoAcceptAlerts\":true,\"browserName\":\"chrome\",\"platformName\":\"desktop\",\"version\":\"\",\"javascriptEnabled\":true,\"platform\":\"ANY\",\"show\":true}"}
>> responseHandler.js:11:12 [master] pid:5431 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/50abbf7e-266b-45ad-b033-b4158a441dde/window/current/maximize, jsonBody: {}
>> proxy.js:52:14 [master] pid:5431 Proxy: /wd/hub/session/50abbf7e-266b-45ad-b033-b4158a441dde/window/current/maximize:POST to http://localhost:9515/wd/hub/session/7e4b3b1e52ca9c67ecff603f31af674e/window/current/maximize:POST with body: {}
>> proxy.js:58:16 [master] pid:5431 Got response with status 200: {"sessionId":"7e4b3b1e52ca9c67ecff603f31af674e","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3....
>> session.js:107:14 [master] pid:5431 Send HTTP Respone to Client: {"sessionId":"50abbf7e-266b-45ad-b033-b4158a441dde","status":6,"value":"{\"message\":\"no such session\\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-101-generic x86_64)\"}"}
>> 
>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:5431 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/50abbf7e-266b-45ad-b033-b4158a441dde, jsonBody: {}
>> macaca-chromedriver.js:123:18 [master] pid:5431 chromedriver exit with code: null, signal: SIGTERM
>> session.js:80:12 [master] pid:5431 Delete session, sessionId: 50abbf7e-266b-45ad-b033-b4158a441dde
>> responseHandler.js:47:14 [master] pid:5431 Send HTTP Respone to Client: {"sessionId":"50abbf7e-266b-45ad-b033-b4158a441dde","status":0}
>> 

  0 passing (1m)
  1 failing

  1) macaca desktop sample "before all" hook:
     Error: [maximize()] Error response status: 6 Selenium error: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-101-generic x86_64)
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/macaca-wd/wd/lib/callbacks.js:33:23
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

>> Test completed!
make: *** [test-pc] Error 1

### 是在xshell执行的案例，一直不能启动chrome ###

**Comment by Archer456** [comment]
@Linjianhan 
chrome 版本有限制  你可以看下issue里相关  也可以看这
https://testerhome.com/topics/6233
是win10或ubuntu16.04系统当把chrome浏览器升级到最新版本54.0.2840.71 后会导致脚本里如果用的是 browserName: 'chrome'的话，会导致之前成功的pc web浏览器脚本执行失败，失败的具体错误就是macaca server 不断的循环报错。然后自行崩溃退出macaca server。

建议你换electron   也可以参考安装指定版本的chromedirver 的macaca-chrome

**Comment by Linjianhan** [comment]
我这里的错误没有macaca server不断的循环报错。
之前有指定过版本，就是下面这样的，不知道成功了没，没有报错。
root@ubuntu:/macaca/macaca-test-sample# CHROMEDRIVER_VERSION=2.25 npm i macaca-chrome -g 
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> macaca-chromedriver@1.0.30 install /opt/nodejs/lib/node_modules/macaca-chrome/node_modules/macaca-chromedriver
> node ./bin/macaca-chromedriver install

>> chromedriver cdn url: https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
>> chromedriver local in /opt/nodejs/lib/node_modules/macaca-chrome/node_modules/macaca-chromedriver/exec/chromedriver
/opt/nodejs/lib
└─┬ macaca-chrome@1.0.5 
  └─┬ macaca-chromedriver@1.0.30 
    └── detect-port@1.0.6 
最后还是执行失败的！

**Comment by Archer456** [comment]
@Linjianhan  不断循环报错的话 那还是chromedriver 没有正确指定安装2.25 的现象 

你可以npm uninstall macaca-chrome -g  
npm cache clean
再重新安装 CHROMEDRIVER_VERSION=2.25 npm i macaca-chrome -g

建议你安装npm i macaca-electron -g  用 这个electron开源chrome也挺好
