### ISSUE TITLE
IOS场景下存在以下问题

### ISSUE THREAD

**Issue by yaniswang** [alibaba/macaca#340]
ios输入法无法隐藏问题
===============

setText输完后，输入法无法自动隐藏，会产生以下几个问题

1. UI Recorder录制器无法继续进行录制，因为某些按钮会被输入法挡住
2. 执行自动化时，坐标定位失败，因为之前记录的坐标是以全屏状态进行定位的，打开输入法，坐标就错误了

ios卡壳问题
=================

macaca自带的app中，list等页面会经常的卡壳，导致UIRecorder执行截图命令卡住，会卡上10-20秒左右

ios无法重复执行问题
=================

macaca server命令开启情况下，如果连接ios多次启动app，就会导致JS报错，直接挂掉

**Comment by xudafeng** [comment]
构建目录占用磁盘空间太大，越来越大
