### ISSUE TITLE
运行 make test-ios-safari 报错

### ISSUE THREAD

**Issue by worry127722** [alibaba/macaca#342]
运行环境 ：macos 10.12.1 ,   xcode 8.1 . ios10
![image](https://cloud.githubusercontent.com/assets/6937117/20822812/d9b797ee-b888-11e6-8d57-9e5af1662a1b.png)

报错信息： 
![image](https://cloud.githubusercontent.com/assets/6937117/20822820/f719cc58-b888-11e6-86a1-05ee02a9319a.png)

单独运行 xcrun simctl openurl "68C75628-B83C-45E4-813A-7170E586AB78" "https://macacajs.github.io/macaca/"，报错，报错信息：
![image](https://cloud.githubusercontent.com/assets/6937117/20822834/1b774a94-b889-11e6-9404-81d09c71c8df.png)

将模拟器  reset content and setting  之后再次运行 xcrun simctl openurl "68C75628-B83C-45E4-813A-7170E586AB78" "https://macacajs.github.io/macaca/" 就可以运行成功，但是再次运行make test-ios-safari 依然报错

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-test-sample/issues/7

**Comment by xudafeng** [comment]
目前是已知问题，待修复

**Comment by xudafeng** [comment]
https://testerhome.com/topics/8039
