### ISSUE TITLE
win7下更新macaca-cli 后还是显示当前版本

### ISSUE THREAD

**Issue by Linjianhan** [alibaba/macaca#343]
+-- lodash.union@4.6.0
+-- lodash.uniq@4.5.0
+-- lodash.without@4.4.0
+-- minimatch@3.0.3
| `-- brace-expansion@1.1.6
|   +-- balanced-match@0.4.2
|   `-- concat-map@0.0.1
+-- node-gyp@3.4.0
| +-- minimatch@3.0.3
| | `-- brace-expansion@1.1.6
| |   +-- balanced-match@0.4.2
| |   `-- concat-map@0.0.1
| +-- nopt@3.0.6
| +-- npmlog@3.1.2
| | +-- are-we-there-yet@1.1.2
| | | `-- delegates@1.0.0
| | +-- console-control-strings@1.1.0
| | +-- gauge@2.6.0
| | | +-- has-color@0.1.7
| | | +-- object-assign@4.1.0
| | | +-- signal-exit@3.0.0
| | | +-- string-width@1.0.2
| | | | +-- code-point-at@1.0.0
| | | | | `-- number-is-nan@1.0.0
| | | | `-- is-fullwidth-code-point@1.0.0
| | | |   `-- number-is-nan@1.0.0
| | | `-- wide-align@1.1.0
| | `-- set-blocking@2.0.0
| +-- osenv@0.1.3
| | +-- os-homedir@1.0.1
| | `-- os-tmpdir@1.0.1
| +-- path-array@1.0.1
| | `-- array-index@1.0.0
| |   +-- debug@2.2.0
| |   | `-- ms@0.7.1
| |   `-- es6-symbol@3.1.0
| |     +-- d@0.1.1
| |     `-- es5-ext@0.10.12
| |       `-- es6-iterator@2.0.0
| `-- tar@2.2.1
|   `-- block-stream@0.0.8
+-- npm-package-arg@4.2.0
| `-- hosted-git-info@2.1.5
+-- npm-registry-client@7.2.1
| +-- concat-stream@1.5.2
| | +-- readable-stream@2.0.6
| | | +-- core-util-is@1.0.2
| | | +-- isarray@1.0.0
| | | +-- process-nextick-args@1.0.7
| | | +-- string_decoder@0.10.31
| | | `-- util-deprecate@1.0.2
| | `-- typedarray@0.0.6
| +-- normalize-package-data@2.3.5
| | `-- is-builtin-module@1.0.0
| |   `-- builtin-modules@1.1.1
| +-- npmlog@3.1.2
| | +-- are-we-there-yet@1.1.2
| | | `-- delegates@1.0.0
| | +-- console-control-strings@1.1.0
| | +-- gauge@2.6.0
| | | +-- has-color@0.1.7
| | | +-- object-assign@4.1.0
| | | +-- signal-exit@3.0.0
| | | +-- string-width@1.0.2
| | | | +-- code-point-at@1.0.0
| | | | | `-- number-is-nan@1.0.0
| | | | `-- is-fullwidth-code-point@1.0.0
| | | |   `-- number-is-nan@1.0.0
| | | `-- wide-align@1.1.0
| | `-- set-blocking@2.0.0
| +-- retry@0.10.0
| `-- slide@1.1.6
+-- npm-user-validate@0.1.5
+-- npmlog@4.0.0
| +-- are-we-there-yet@1.1.2
| | `-- delegates@1.0.0
| +-- console-control-strings@1.1.0
| +-- gauge@2.6.0
| | +-- has-color@0.1.7
| | +-- object-assign@4.1.0
| | +-- signal-exit@3.0.0
| | +-- string-width@1.0.2
| | | +-- code-point-at@1.0.0
| | | | `-- number-is-nan@1.0.0
| | | `-- is-fullwidth-code-point@1.0.0
| | |   `-- number-is-nan@1.0.0
| | `-- wide-align@1.1.0
| `-- set-blocking@2.0.0
+-- once@1.4.0
+-- opener@1.4.2
+-- path-is-inside@1.0.2
+-- read-package-tree@5.1.5
| +-- debuglog@1.0.1
| +-- dezalgo@1.0.3
| +-- read-package-json@2.0.4
| | +-- glob@6.0.4
| | | `-- path-is-absolute@1.0.0
| | `-- json-parse-helpfulerror@1.0.3
| |   `-- jju@1.3.0
| `-- readdir-scoped-modules@1.0.2
+-- readable-stream@2.1.5
| +-- buffer-shims@1.0.0
| +-- core-util-is@1.0.2
| +-- isarray@1.0.0
| +-- process-nextick-args@1.0.7
| +-- string_decoder@0.10.31
| `-- util-deprecate@1.0.2
+-- request@2.75.0
| +-- aws-sign2@0.6.0
| +-- aws4@1.4.1
| +-- bl@1.1.2
| | `-- readable-stream@2.0.6
| |   +-- core-util-is@1.0.2
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@1.0.7
| |   +-- string_decoder@0.10.31
| |   `-- util-deprecate@1.0.2
| +-- caseless@0.11.0
| +-- combined-stream@1.0.5
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.0
| +-- forever-agent@0.6.1
| +-- form-data@2.0.0
| | `-- asynckit@0.4.0
| +-- har-validator@2.0.6
| | +-- chalk@1.1.3
| | | +-- ansi-styles@2.2.1
| | | +-- escape-string-regexp@1.0.5
| | | +-- has-ansi@2.0.0
| | | `-- supports-color@2.0.0
| | +-- commander@2.9.0
| | | `-- graceful-readlink@1.0.1
| | +-- is-my-json-valid@2.15.0
| | | +-- generate-function@2.0.0
| | | +-- generate-object-property@1.2.0
| | | | `-- is-property@1.0.2
| | | +-- jsonpointer@4.0.0
| | | `-- xtend@4.0.1
| | `-- pinkie-promise@2.0.1
| |   `-- pinkie@2.0.4
| +-- hawk@3.1.3
| | +-- boom@2.10.1
| | +-- cryptiles@2.0.5
| | +-- hoek@2.16.3
| | `-- sntp@1.0.9
| +-- http-signature@1.1.1
| | +-- assert-plus@0.2.0
| | +-- jsprim@1.3.1
| | | +-- extsprintf@1.0.2
| | | +-- json-schema@0.2.3
| | | `-- verror@1.3.6
| | `-- sshpk@1.10.1
| |   +-- asn1@0.2.3
| |   +-- assert-plus@1.0.0
| |   +-- bcrypt-pbkdf@1.0.0
| |   +-- dashdash@1.14.0
| |   +-- ecc-jsbn@0.1.1
| |   +-- getpass@0.1.6
| |   +-- jodid25519@1.0.2
| |   +-- jsbn@0.1.0
| |   `-- tweetnacl@0.14.3
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.12
| | `-- mime-db@1.24.0
| +-- node-uuid@1.4.7
| +-- oauth-sign@0.8.2
| +-- qs@6.2.1
| +-- stringstream@0.0.5
| +-- tough-cookie@2.3.1
| `-- tunnel-agent@0.4.3
+-- retry@0.10.0
+-- rimraf@2.5.4
+-- semver@5.3.0
+-- sorted-object@2.0.1
+-- which@1.2.11
| `-- isexe@1.1.2
+-- wrappy@1.0.2
`-- write-file-atomic@1.2.0
  `-- imurmurhash@0.1.4

D:\macaca\macaca-test-sample-master\macaca-test>cnpm i macaca-cli -g

Macaca was successfully installed!

Run `macaca -h` for further help.

deprecate macaca-cli@1.1.16 › macaca-utils@0.1.9 › xutil@1.0.3 › node-uuid@1.4.
 use uuid module instead
deprecate macaca-cli@1.1.16 › mocha@2.4.5 › glob@3.2.3 › graceful-fs@2.0.3 grac
ful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to g
aceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in th
 tree.
deprecate macaca-cli@1.1.16 › mocha@2.4.5 › jade@0.26.3 Jade has been renamed t
 pug, please install the latest version of pug instead of jade
deprecate macaca-cli@1.1.16 › mocha@2.4.5 › glob@3.2.3 › minimatch@0.2.14 Pleas
 update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
√ All packages installed (188 packages installed from npm registry, use 20s, s
eed 128.6kB/s, json 213(1.25MB), tarball 1.27MB)
Recently updated (since 2016-11-25): 2 packages (detail see file node_modules/.
ecently_updates.txt)

D:\macaca\macaca-test-sample-master\macaca-test>macaca -v

  1.1.10

D:\macaca\macaca-test-sample-master\macaca-test>node -v
v6.2.0

D:\macaca\macaca-test-sample-master\macaca-test>npm -v
3.8.9

**Comment by Archer456** [comment]
@Linjianhan 
node 用lts版本  4.4.7  或最新的6.1.9  
npm版本无所谓

**Comment by Linjianhan** [comment]
@Archer456 
D:\macaca\macaca-test-sample-master\macaca-test>node -v
v6.2.0
node我已经用了最新版本的6.2.0的了

**Comment by xudafeng** [comment]
uninstall 再装呢？

**Comment by Linjianhan** [comment]
@xudafeng 
恩 这个问题解决了，应该是node版本的问题，现在是Android驱动安装不成功！
```
Total time: 0 seconds
D:\nodejs\node-global\node_modules\macaca-android\node_modules\uiautomator-clien
t\scripts\build.js:177
      throw e;
      ^

Error: build failed
    at ChildProcess.<anonymous> (D:\nodejs\node-global\node_modules\macaca-andro
id\node_modules\uiautomator-client\scripts\build.js:163:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
D:\nodejs\node-global
`-- (empty)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node-global\\node_modules\\npm
\\bin\\npm-cli.js" "i" "macaca-android" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE

npm ERR! uiautomator-client@1.0.36 install: `node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uiautomator-client@1.0.36 install script 'node ./scripts/
build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uiautomator-client pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uiautomator-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uiautomator-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator.PC-20141216NSRQ\npm-debug.log
npm ERR! code 1
'''

**Comment by Archer456** [comment]
可以先卸载掉npm uninstall *** -g ，再npm cache clean 清理干净后，再清理下
C:\Users\your name\AppData\Local\Temp 目录npm相关都删掉 ，再重新尝试安装。
