### ISSUE TITLE
android 测试脚本运行时，macaca服务出现假死的情况，脚本未运行完没有继续执行，macaca的log也没有报错

### ISSUE THREAD

**Issue by xiaoxiao86** [alibaba/macaca#344]
* **Macaca Version**:    1.1.16

* **Macaca Doctor Logs**:
>> responseHandler.js:47:14 [master] pid:12952 Send HTTP Respone to Client: {"sessionId":"5659afe6-09de-4b91-84ef-afdcbcbd8507","status":0,"value":"{\"ELEMENT\":\"42\"}"}
>> responseHandler.js:11:12 [master] pid:12952 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5659afe6-09de-4b91-84ef-afdcbcbd8507/element/42/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"42"}}

return: {"success":true,"data":{"status":0,"value":true}}

>> responseHandler.js:47:14 [master] pid:12952 Send HTTP Respone to Client: {"sessionId":"5659afe6-09de-4b91-84ef-afdcbcbd8507","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:12952 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5659afe6-09de-4b91-84ef-afdcbcbd8507/element, jsonBody: {"using":"id","value":"com.
recive: {"cmd":"find","args":{"strategy":"id","selector":"com.airmedia_commute.passenger:id/personal_center_all_route_rl","multiple":false}}

return: {"success":true,"data":{"status":0,"value":{"ELEMENT":"43"}}}

>> responseHandler.js:47:14 [master] pid:12952 Send HTTP Respone to Client: {"sessionId":"5659afe6-09de-4b91-84ef-afdcbcbd8507","status":0,"value":"{\"ELEMENT\":\"43\"}"}
>> responseHandler.js:11:12 [master] pid:12952 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/5659afe6-09de-4b91-84ef-afdcbcbd8507/element/43/displayed, jsonBody: {}
recive: {"cmd":"isDisplayed","args":{"elementId":"43"}}

return: {"success":true,"data":{"status":0,"value":true}}

>> responseHandler.js:47:14 [master] pid:12952 Send HTTP Respone to Client: {"sessionId":"5659afe6-09de-4b91-84ef-afdcbcbd8507","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:12952 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5659afe6-09de-4b91-84ef-afdcbcbd8507/element, jsonBody: {"using":"id","value":"com.
recive: {"cmd":"find","args":{"strategy":"id","selector":"com.airmedia_commute.passenger:id/personal_center_all_route_rl","multiple":false}}

return: {"success":true,"data":{"status":0,"value":{"ELEMENT":"44"}}}

>> responseHandler.js:47:14 [master] pid:12952 Send HTTP Respone to Client: {"sessionId":"5659afe6-09de-4b91-84ef-afdcbcbd8507","status":0,"value":"{\"ELEMENT\":\"44\"}"}
>> responseHandler.js:11:12 [master] pid:12952 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5659afe6-09de-4b91-84ef-afdcbcbd8507/element, jsonBody: {"using":"id","value":"com.
recive: {"cmd":"find","args":{"strategy":"id","selector":"com.airmedia_commute.passenger:id/personal_center_all_route_rl","multiple":false}}

return: {"success":true,"data":{"status":0,"value":{"ELEMENT":"45"}}}
>> responseHandler.js:47:14 [master] pid:12952 Send HTTP Respone to Client: {"sessionId":"5659afe6-09de-4b91-84ef-afdcbcbd8507","status":0,"value":"{\"ELEMENT\":\"45\"}"}

>> responseHandler.js:11:12 [master] pid:12952 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5659afe6-09de-4b91-84ef-afdcbcbd8507/element/45/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"45"}}

return: {"success":true,"data":{"status":0,"value":true}}

>> responseHandler.js:47:14 [master] pid:12952 Send HTTP Respone to Client: {"sessionId":"5659afe6-09de-4b91-84ef-afdcbcbd8507","status":0,"value":"true"}

* **Operate System**:win7

* **Programming Language**:java

**Comment by zenzhu** [comment]
看日志最后是停在了收到请求之后没有后续操作了？应该是对 com.airmedia_commute.passenger:id/personal_center_all_route_rl 点击之后，看看测试用例中之后是怎么写的呢

**Comment by Archer456** [comment]
以老衲的经验  一般卡在那里 且没有日志输出的话 一般是卡在adb通信连接上的.  你这时候  执行下
adb devices -l  看看这个日志是否是正常的.   不正常的话  就会卡日志.
