### ISSUE TITLE
process.cwd().split('/').pop(); 在win系统不能正常执行

### ISSUE THREAD

**Issue by baozhida** [alibaba/macaca#345]
* **Macaca Version**:
1.1.16
* **Macaca Logs**:
Error happened when writing to output html: Error: ENOENT: no such file or directory, open 'D:\macac
a-test-sample\macaca-test\macaca-test\macaca-D:\macaca-test-sample\macaca-test-2016-12-05-1480933412
336.html'
* **Operate System**:
window7
* **Programming Language**:
js

使用官网例子，执行
D:\macaca-test-sample\macaca-test>macaca run -o -d ./macaca-desktop-sample.test.js

在windows上对路径执行split('/')无效，projectName没有按照希望的那样返回，最终
projectName = 'D:\macaca-test-sample\macaca-test'

**Comment by xudafeng** [comment]
http://xudafeng.github.io/nodejs/path.html#path_path_sep

**Comment by baozhida** [comment]
这是macaca-cli/bin/macaca-cli-run 里的一行代码，需要更新下吧

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-cli/pull/63

**Comment by xudafeng** [comment]
@baozhida 是的，请更新
