### ISSUE TITLE
macaca过期提示，更新日志页面无法访问

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#346]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

```xml
mac:uirecorder mac$ macaca server --port 4444 --verbose

*************************************
*  version 1.1.16 is outdate        *
*  run: npm i -g macaca-cli@1.1.17  *
*************************************

More information: https://macacajs.github.io/macaca/changelog.html

```

更新记录页面https://macacajs.github.io/macaca/changelog.html无法访问

**Comment by xudafeng** [comment]
@CodeToSurvive1 

网站有调整过

https://macacajs.github.io/changelog.html

**Comment by CodeToSurvive1** [comment]
今天的更新也没有体现  也不知道都更新了些什么东西  文档要求是不是应该要求高一点

**Comment by xudafeng** [comment]
是的，的确没体现，要等下次才会有正确的changelog地址
