### ISSUE TITLE
使用Macaca进行多个设备测试时socket连接被打断，运行时只有一个设备能正常运行，另外一个初始化driver异常。

### ISSUE THREAD

**Issue by adfghzhang** [alibaba/macaca#347]
* **Macaca Version**:
1.1.17
* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: D:\Program Files\nodejs\node.exe
  node version: v6.9.1

  Android checklist:

  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_102`
  ANDROID_HOME is set to `F:\android-sdk`
  Platforms is set to `F:\android-sdk\platforms\android-24`
  Android tools is set to `F:\android-sdk\tools\android.bat`
  ADB tool is set to `F:\android-sdk\platform-tools\adb.exe`
  ANT_HOME is set to `F:\apache-ant-1.9.7`

  Installed driver list:

(node:11288) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
  android: 1.1.3
  electron: 1.1.4
* **Operate System**:
Windows 10
* **Programming Language**:
Java

使用Macaca进行多个设备测试时socket连接被打断，运行时只有一个设备能正常运行，另外一个初始化driver异常。同时测试两个desktop的electron浏览器无此问题。

运行失败的设备日志：

    macaca server --verbose
    >> index.js:17:12 [master] pid:16776 webdriver server start with config:
     { port: 3456,
      verbose: true,
      always: true,
      ip: '192.168.6.2',
      host: 'DESKTOP-PHHDJ8D',
      loaded_time: '2016-12-06 23:56:24' }
    >> middlewares.js:17:10 [master] pid:16776 base middlewares attached
    >> router.js:129:10 [master] pid:16776 router set
    >> webdriver sdk launched
    >> responseHandler.js:11:12 [master] pid:16776 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"C:\\Users\\qianchang\\Desktop\\Macaca-Android\\macaca-test-sample-java-master/app/android-app-bootstrap.zip","reuse":1,"platformName":"android","udid":"192.168.239.101:5555"},"port":3456,"host":"127.0.0.1"}
    >> session.js:47:10 [master] pid:16776 Creating session, sessionId: 0f5ef732-5336-4934-b8aa-f67cd243e2f3.
    >> helper.js:196:12 [master] pid:16776 Unzipping local app form C:\Users\qianchang\Desktop\Macaca-Android\macaca-test-sample-java-master\app\android-app-bootstrap.zip
    INSTRUMENTATION_STATUS: numtests=1
    >> socket server ready
    >> socket client ready
    >> uiautomator-client.js:70:14 [master] pid:16776 connect lost
    >> macaca-android.js:297:12 [master] pid:16776 UnknownError from uiautomator Error: This socket has been ended by the other party
    >> responseHandler.js:54:12 [master] pid:16776 Send Error Respone to Client: UnknownError: An unknown server-side error occurred while processing the command.
    >> responseHandler.js:60:14 [master] pid:16776 UnknownError: An unknown server-side error occurred while processing the command.
        at Android.send (C:\Users\qianchang\AppData\Roaming\npm\node_modules\macaca-android\lib\macaca-android.js:298:11)
        at throw (native)
        at onRejected (C:\Users\qianchang\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\.4.6.0@co\index.js:81:24)
    >> responseHandler.js:76:14 [master] pid:16776 Send Bad HTTP Respone to Client: {"sessionId":"0f5ef732-5336-4934-b8aa-f67cd243e2f3","status":13,"value":{"message":"An unknown server-side error occurred while processing the command."}}

运行成功的设备日志：

    macaca server --verbose
    >> request.js:24:12 [master] pid:13264 get remote update info failed.
    >> port: 3456 was occupied, changed port: 3457
    >> index.js:17:12 [master] pid:8532 webdriver server start with config:
     { port: 3457,
      verbose: true,
      always: true,
      ip: '192.168.6.2',
      host: 'DESKTOP-PHHDJ8D',
      loaded_time: '2016-12-06 23:56:32' }
    >> middlewares.js:17:10 [master] pid:8532 base middlewares attached
    >> router.js:129:10 [master] pid:8532 router set
    >> webdriver sdk launched
    >> responseHandler.js:11:12 [master] pid:8532 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"C:\\Users\\qianchang\\Desktop\\Macaca-Android\\macaca-test-sample-java-master/app/android-app-bootstrap.zip","reuse":1,"platformName":"android","udid":"192.168.239.102:5555"},"port":3457,"host":"127.0.0.1"}
    >> session.js:47:10 [master] pid:8532 Creating session, sessionId: 964eef25-511c-43af-8028-1389ebc33dc2.
    >> helper.js:196:12 [master] pid:8532 Unzipping local app form C:\Users\qianchang\Desktop\Macaca-Android\macaca-test-sample-java-master\app\android-app-bootstrap.zip
    INSTRUMENTATION_STATUS: numtests=1
    >> socket server ready
    >> socket client ready
    recive: {"cmd":"wake","args":{}}
    return: {"success":true,"data":{"status":0,"value":true}}
    >> responseHandler.js:47:14 [master] pid:8532 Send HTTP Respone to Client: {"sessionId":"964eef25-511c-43af-8028-1389ebc33dc2","status":0,"value":"{\"app\":\"C:\\\\Users\\\\QIANCH~1\\\\AppData\\\\Local\\\\Temp\\\\android-app-bootstrap.apk\",\"reuse\":1,\"platformName\":\"android\",\"udid\":\"192.168.239.102:5555\"}"}

测试代码

    public static void main(String[] args) {
		Thread myThread1 = new AndroidMulti("3456", "192.168.239.101:5555");
		Thread myThread2 = new AndroidMulti("3457", "192.168.239.102:5555"); 
		myThread1.start(); // 调用start()方法使得线程进入就绪状态
		myThread2.start(); // 调用start()方法使得线程进入就绪状态
	}

	class AndroidMulti extends Thread {

	MacacaClient driver = new MacacaClient();
	String port = "";
	String udid = "";

	public AndroidMulti(String port, String udid) {
		this.port = port;
		this.udid = udid;
	}

	@Override
	public void run() {
		String platform = "android";
		JSONObject porps = new JSONObject();
		porps.put("platformName", platform);
		porps.put("app", System.getProperty("user.dir") + "/app/" + platform + "-app-bootstrap.zip");
		porps.put("udid", udid);
		porps.put("reuse", 1);
		JSONObject desiredCapabilities = new JSONObject();
		desiredCapabilities.put("host", "127.0.0.1"); 
		desiredCapabilities.put("port", Integer.parseInt(port));
		desiredCapabilities.put("desiredCapabilities", porps);
		try {
			driver = driver.initDriver(desiredCapabilities);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		System.out.println(driver);
		try {
			test_case_1();
			tearDown();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

**Comment by adfghzhang** [comment]
补充一下运行设备的设备的app也已经成功启动。

**Comment by Archer456** [comment]
确是有问题   实现方式也是 testng  java   用的mvn test跑的java类

我这儿  是执行到业务动作  前边两个端口的server --verbose 初始化driver 和 打开app都正常  执行到欢迎页 右滑动后 

就一个3456端口的在跑  另一个3457端口报的错 和你一样了

**Comment by adfghzhang** [comment]
该问题可参考该帖解决。https://testerhome.com/topics/6611

**Comment by xudafeng** [comment]
@adfghzhang 确定3456和3457两个服务能用吗

**Comment by adfghzhang** [comment]
@xudafeng 确定可用，后面第二个线程加了延时，就能正常使用了。如果不可用的时候，失败的那个服务不会抛
>> uiautomator-client.js:70:14 [master] pid:16776 connect lost
>> macaca-android.js:297:12 [master] pid:16776 UnknownError from uiautomator Error: This socket has been ended by the other party这个异常的
