### ISSUE TITLE
inspector 在真机上无法使用，Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by johnwanggithub** [alibaba/macaca#348]
* **Macaca Version**:
1.1.16
* **Macaca Doctor Logs**:
Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.1.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home`
  ANDROID_HOME is not set

  Installed driver list:

  ios: 1.0.46

* **Operate System**:
OSX EI Capitan 10.11.6

* **iphone 真机 **:
ios 10.1.1

***logs***:
> server.js:16:12 [master] pid:23872 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'a464f01afbd649db7d8c1fd2359f1fef1a6a2b8f',
  ip: '172.30.182.99',
  host: 'johns-MacBook-Pro.local',
  loaded_time: '2016-12-07 14:42:38' }
>> app-inspector.js:42:10 [master] pid:23872 server start at: http://172.30.182.99:5678
>> xctest-client.js:56:14 [master] pid:23872 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client start with port: 8900
>> xctest-client.js:234:14 [master] pid:23872 xcode version: 8.1
>> WebDriverAgent version: 1.0.38

>> xctest-client.js:171:14 [master] pid:23872 2016-12-07 14:43:12.651 xcodebuild[23878:3922677]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
....
...
..
> xctest-client.js:172:14 [master] pid:23872 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:171:14 [master] pid:23872 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/ls/c4q51zg53cd57c_qksvhqc780000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/9b10e9a51994a9d725b288ded5d4663c/a464f01afbd649db7d8c1fd2359f1fef1a6a2b8f/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/johnwang/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/ls/c4q51zg53cd57c_qksvhqc780000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.8a4YN9/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/ls/c4q51zg53cd57c_qksvhqc780000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.8a4YN9/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:172:14 [master] pid:23872 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:171:14 [master] pid:23872 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/ls/c4q51zg53cd57c_qksvhqc780000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.8a4YN9/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:172:14 [master] pid:23872 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:171:14 [master] pid:23872 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/ls/c4q51zg53cd57c_qksvhqc780000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.8a4YN9/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:172:14 [master] pid:23872 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:56:14 [master] pid:23872 Proxy: /session:POST to http://172.30.172.2:8900/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:62:22 [master] pid:23872 xctest client proxy error with: Error: connect ETIMEDOUT 172.30.172.2:8900
..
..
..
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
>> proxy.js:62:22 [master] pid:23872 xctest client proxy error with: Error: connect ETIMEDOUT 172.30.172.2:8900
>> xctest-client.js:256:14 [master] pid:23872 Fail to start xctest: Error: connect ETIMEDOUT 172.30.172.2:8900
>> xctest-client.js:268:14 [master] pid:23872 killing deviceLogProc pid: 23875
>> xctest-client.js:273:14 [master] pid:23872 killing runnerProc pid: 23878
>> xctest-client.js:279:14 [master] pid:23872 killing iproxyProc pid: 23877
>> app-inspector:66:44 [master] pid:23872 Error: connect ETIMEDOUT 172.30.172.2:8900
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
(node:23872) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:23872 Error: connect ETIMEDOUT 172.30.172.2:8900
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
(node:23872) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>> xctest-client.js:146:16 [master] pid:23872 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:210:14 [master] pid:23872 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:182:14 [master] pid:23872 xctest client exit with code: null, signal: SIGKILL
 <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200
  <-- GET /
  --> GET / 200

**Comment by johnwanggithub** [comment]
@Archer456 , 看过这篇文章。我这边bundle  id 等都改过，build也都success。但是app-inspector 在模拟器上也ok，但在真机上就是不行

**Comment by johnwanggithub** [comment]
I think I figured out why. 在用macaca前，我直接使用了原版的fb的WDA，并且看了一些其他blog将appium&app-inspector下面的WDA替换成了原始的fb的WDA。绕了个弯路。目前看app-inspector 只要follow:https://macacajs.github.io/app-inspector/ 这个上的基本步骤应该能在真机上跑起来。

**Comment by xudafeng** [comment]
@johnwanggithub 💯
