### ISSUE TITLE
需要的几点帮助

### ISSUE THREAD

**Issue by lengyao88** [alibaba/macaca#35]
1.代码过程中控件元素命名的规范化指导建议
2.测试用例脚本中除了tap，click外的操作是否有帮助，比如滑屏等。

**Comment by xudafeng** [comment]
@lengyao88 我和 @zenzhu 正在整理 API 统一用法，本周内会提供出来

**Comment by xudafeng** [comment]
@lengyao88 请查阅统一文档 http://macacajs.github.io/macaca-wd/docs/
