### ISSUE TITLE
python setup(self)设置问题

### ISSUE THREAD

**Issue by CleverPotato** [alibaba/macaca#352]
def setUp(self):
        self.driver = WebDriver(desired_caps, server_url)
        self.driver.init()
        self.driver.set_implicitly_wait(10)

    def tearDown(self):
        self.driver.quit()
我想让macaca在运行每一条case的时候都走一遍setUp&tearDown,就写了如上代码，但是运行过程中只有WDA被一次次唤起，被测应用没有反应

server里是这种状态：
>> proxy.js:62:22 [master] pid:5642 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:5642 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:5642 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:255:14 [master] pid:5642 Fail to start xctest: Error: socket hang up
>> xctest-client.js:267:14 [master] pid:5642 killing deviceLogProc pid: 6256
>> xctest-client.js:272:14 [master] pid:5642 killing runnerProc pid: 6259
>> xctest-client.js:278:14 [master] pid:5642 killing iproxyProc pid: 6258
>> responseHandler.js:54:12 [master] pid:5642 Send Error Respone to Client: Error: socket hang up
>> responseHandler.js:60:14 [master] pid:5642 Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by CleverPotato** [comment]
无论是否保留了类方法都是那个样子

**Comment by zenzhu** [comment]
跑的是真机吗？

**Comment by CleverPotato** [comment]
@zenzhu 是真机啊，而且macaca也不能自己把app装进设备里，要手动安装yin应用

**Comment by zenzhu** [comment]
之前真机可以用吗？还是说改了 setup 之后不能用了？

**Comment by CleverPotato** [comment]
@zenzhu 改了setUp后不能用了，之前用setUpClass时应用能正常启动并执行脚本。但是一直都得手动装应用，没办法自动安装。

**Comment by zenzhu** [comment]
因为 iOS 不越狱的话，不是像安卓那样很容易装的，话说你们应用要反复卸载吗，如果只是测一个应用的话，build 进去一次应该就好了啊。另外，我不大清楚为什么 setup 不行，但一般来说 重启 driver 是有什么目的吗？那个真机连接确实不太稳定，反复重启会影响稳定性。现在加了 setUp 的话，setUpClass 还在吗，会不会有连续两次启动服务器发生？

**Comment by CleverPotato** [comment]
@zenzhu 更新完iOS驱动可以执行脚本了。反复卸载是因为前一条case会留下一些登录信息浏览记录什么的，有时候会影响到后面的case执行。我也有用了'reuse':0,可是没有效果啊

**Comment by CleverPotato** [comment]
设备是添加了企业证书那种的，没有越狱，用PP助手和Appium能自己装进去

**Comment by zenzhu** [comment]
@CleverPotato 你是装 app 文件的吗，我们可以考虑加入自动安装。

**Comment by CleverPotato** [comment]
@zenzhu 是ipa，主要reuse那个参数我写了没反应，我写了'reuse':0，但是之前的用户数据都还在。反复卸载就是为了防止对后面的脚本产生影响。

**Comment by zenzhu** [comment]
好 我们那个 reuse 暂时只是针对模拟器的，等会加上自动安装试一下。

**Comment by zenzhu** [comment]
@CleverPotato 你尝试用 [ios-deploy](https://github.com/phonegap/ios-deploy) 安装一下应用，看看能不能装进去。因为不是所有的包都能装进手机的，所以自己build会比较确定。

**Comment by zenzhu** [comment]
@CleverPotato 最新版已经支持了，npm i -g macaca-ios@1.0.50，默认的 reuse 就是 1，先卸载，再重新安装 App。2 的话是只在原基础上安装，不卸载。3 的话保持不变。你可以试试看。

**Comment by CleverPotato** [comment]
辛苦了，我有试过，但是运行不起来，server报错提示
ios-deploy[1709:16964] [ !! ] Timed out waiting for device.

**Comment by zenzhu** [comment]
@CleverPotato 你命令行试试 ios-deploy -b -i xxxxxx(udid)，看看能不能装上 ipa 的包，我这边之前过滤了包的类型，所以没装成功。马上会加上 ipa 试试。

**Comment by CleverPotato** [comment]
ios-deploy可以成功安装ipa包

**Comment by zenzhu** [comment]
好的，你先暂时压缩成 zip 应该就行了。

**Comment by CleverPotato** [comment]
按照你说的，应用成功安装到设备中了，不过运行不起来，server里找不到明显的错误，只有这么一条看起来像
>> proxy.js:84:20 [master] pid:2056 Got response with status 200: {"sessionId":null,"value":"Path must be to the application bundle\n\n(\n\t0   CoreFoundation                      0x2401b933 <redacted> + 150\n\t1   libobjc.A.dylib                     0x237b6e17 o...

**Comment by zenzhu** [comment]
能把前后的日志多贴一点吗，我想看一下是从哪部开始报的错

**Comment by CleverPotato** [comment]
>> index.js:17:12 [master] pid:3324 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '10.168.31.69',
  host: 'autohome',
  loaded_time: '2016-12-09 10:21:21' }
>> middlewares.js:17:10 [master] pid:3324 base middlewares attached
>> router.js:129:10 [master] pid:3324 router set
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:3324 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"udid":"8994ddd04b22016fbeb616d7aab65e1dafb352ee","platformName":"iOS","app":"/Users/autohome/Downloads/autohome_macaca_demo.zip","autoAcceptAlerts":true,"bundleId":"com.autohome.new"}}
>> session.js:47:10 [master] pid:3324 Creating session, sessionId: 1cfb516f-0d4b-4fd0-a4e5-b2e52a59dff4.
>> helper.js:196:12 [master] pid:3324 Unzipping local app form /Users/autohome/Downloads/autohome_macaca_demo.zip
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> macaca-ios.js:257:12 [master] pid:3324 App "com.autohome.new" is not installed.
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> macaca-ios.js:260:14 [master] pid:3324 Install app "com.autohome.new" successfully.
>> xctest-client.js:56:14 [master] pid:3324 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:149:10 [master] pid:3324 {
	"bundleId": "com.autohome.new",
	"platformName": "iOS",
	"app": "/var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/T/autohome_macaca_demo.ipa"
}
>> macaca-ios.js:153:12 [master] pid:3324 Trying to start wda server...
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3324) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
^C
autohome:~ autohome$ macaca server --verbose
>> index.js:17:12 [master] pid:3357 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '10.168.31.69',
  host: 'autohome',
  loaded_time: '2016-12-09 10:22:09' }
>> middlewares.js:17:10 [master] pid:3357 base middlewares attached
>> router.js:129:10 [master] pid:3357 router set
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"udid":"8994ddd04b22016fbeb616d7aab65e1dafb352ee","platformName":"iOS","app":"/Users/autohome/Downloads/autohome_macaca_demo.zip","autoAcceptAlerts":true,"bundleId":"com.autohome.new"}}
>> session.js:47:10 [master] pid:3357 Creating session, sessionId: f3dc2d01-bc1c-4203-8e3c-9e0857e7b036.
>> helper.js:196:12 [master] pid:3357 Unzipping local app form /Users/autohome/Downloads/autohome_macaca_demo.zip
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> macaca-ios.js:257:12 [master] pid:3357 App "com.autohome.new" is not installed.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> macaca-ios.js:260:14 [master] pid:3357 Install app "com.autohome.new" successfully.
>> xctest-client.js:56:14 [master] pid:3357 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:149:10 [master] pid:3357 {
	"bundleId": "com.autohome.new",
	"platformName": "iOS",
	"app": "/var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/T/autohome_macaca_demo.ipa"
}
>> macaca-ios.js:153:12 [master] pid:3357 Trying to start wda server...
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:3357 xcode version: 8.1
>> WebDriverAgent version: 1.0.38
>> xctest-client.js:170:14 [master] pid:3357 2016-12-09 10:22:41.006 xcodebuild[3376:27460]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/autohome/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/7EFCE8D1-C710-412E-903E-4AA3D260023C/Session-WebDriverAgentRunner-2016-12-09_102241-DoCmgR.log

>> xctest-client.js:171:14 [master] pid:3357 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:3357 2016-12-09 10:22:41.007 xcodebuild[3376:27450] [MT] IDETestOperationsObserverDebug: (5D3227C6-EF01-43D3-8DDB-F1CDDA6AB121) Beginning test session WebDriverAgentRunner-5D3227C6-EF01-43D3-8DDB-F1CDDA6AB121 at 2016-12-09 10:22:41.005 with Xcode 8B62 on target <DVTiOSDevice: 0x7fc0d42114b0> {
		deviceSerialNumber:         CCQNF12CG22R
		identifier:                 8994ddd04b22016fbeb616d7aab65e1dafb352ee
		deviceClass:                iPod
		deviceName:                 毕彦为 的 iPod
		deviceIdentifier:           8994ddd04b22016fbeb616d7aab65e1dafb352ee
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         armv7f
		deviceTotalCapacity:        13507452928
		deviceAvailableCapacity:    9972232192
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fc0d3f18620 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.5 (13G36))

>> xctest-client.js:171:14 [master] pid:3357 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:56:14 [master] pid:3357 Proxy: /session:POST to http://127.0.0.1:8900/session:POST with body: {"desiredCapabilities":{"bundleId":"com.autohome.new","platformName":"iOS","app":"/var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/T/autohome_macaca_demo.ipa"}}
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:170:14 [master] pid:3357 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/35d743e01c0987fc8a39bdbd26cfdacf/8994ddd04b22016fbeb616d7aab65e1dafb352ee/ManifestCache.plist

>> xctest-client.js:171:14 [master] pid:3357 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:84:20 [master] pid:3357 Got response with status 200: {"sessionId":null,"value":"Path must be to the application bundle\n\n(\n\t0   CoreFoundation                      0x2401b933 <redacted> + 150\n\t1   libobjc.A.dylib                     0x237b6e17 o...
>> responseHandler.js:47:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":"f3dc2d01-bc1c-4203-8e3c-9e0857e7b036","status":0,"value":"{\"udid\":\"8994ddd04b22016fbeb616d7aab65e1dafb352ee\",\"platformName\":\"iOS\",\"app\":\"/var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/T/autohome_macaca_demo.ipa\",\"autoAcceptAlerts\":true,\"bundleId\":\"com.autohome.new\"}"}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036/timeouts/implicit_wait, jsonBody: {"ms":10000}
>> responseHandler.js:47:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":"f3dc2d01-bc1c-4203-8e3c-9e0857e7b036","status":0,"value":null}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036/timeouts/implicit_wait, jsonBody: {"ms":20000}
>> responseHandler.js:47:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":"f3dc2d01-bc1c-4203-8e3c-9e0857e7b036","status":0,"value":null}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036/element, jsonBody: {"using":"name","value":"论坛"}
>> proxy.js:56:14 [master] pid:3357 Proxy: /wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036/element:POST to http://127.0.0.1:8900/wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036/element:POST with body: {"using":"name","value":"论坛"}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> proxy.js:84:20 [master] pid:3357 Got response with status 200: {"sessionId":null,"value":"Unhandled endpoint: /wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036/element -- http://127.0.0.1:8900/ with parameters {\n    wildcards =     (\n        \"wd/hub/sess...
>> session.js:107:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":null,"value":"\"Unhandled endpoint: /wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036/element -- http://127.0.0.1:8900/ with parameters {\\n    wildcards =     (\\n        \\\"wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036/element\\\"\\n    );\\n}\"","status":1}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/f3dc2d01-bc1c-4203-8e3c-9e0857e7b036, jsonBody: {}
>> macaca-ios.js:327:10 [master] pid:3357 Stoping iOS driver...
>> xctest-client.js:267:14 [master] pid:3357 killing deviceLogProc pid: 3373
>> xctest-client.js:272:14 [master] pid:3357 killing runnerProc pid: 3376
>> xctest-client.js:278:14 [master] pid:3357 killing iproxyProc pid: 3375
>> macaca-ios.js:351:10 [master] pid:3357 iOS driver cleaned up.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> session.js:80:12 [master] pid:3357 Delete session, sessionId: f3dc2d01-bc1c-4203-8e3c-9e0857e7b036
>> responseHandler.js:47:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":"f3dc2d01-bc1c-4203-8e3c-9e0857e7b036","status":0}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> xctest-client.js:145:16 [master] pid:3357 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:209:14 [master] pid:3357 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:181:14 [master] pid:3357 xctest client exit with code: null, signal: SIGKILL
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"udid":"8994ddd04b22016fbeb616d7aab65e1dafb352ee","platformName":"iOS","app":"/Users/autohome/Downloads/autohome_macaca_demo.zip","autoAcceptAlerts":true,"bundleId":"com.autohome.new"}}
>> session.js:47:10 [master] pid:3357 Creating session, sessionId: 6f6556af-5d60-447f-98b6-1179d62598c5.
>> helper.js:196:12 [master] pid:3357 Unzipping local app form /Users/autohome/Downloads/autohome_macaca_demo.zip
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> macaca-ios.js:257:12 [master] pid:3357 App "com.autohome.new" is not installed.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> macaca-ios.js:260:14 [master] pid:3357 Install app "com.autohome.new" successfully.
>> xctest-client.js:56:14 [master] pid:3357 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:149:10 [master] pid:3357 {
	"bundleId": "com.autohome.new",
	"platformName": "iOS",
	"app": "/var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/T/autohome_macaca_demo.ipa"
}
>> macaca-ios.js:153:12 [master] pid:3357 Trying to start wda server...
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:3357 xcode version: 8.1
>> WebDriverAgent version: 1.0.38
>> xctest-client.js:170:14 [master] pid:3357 2016-12-09 10:23:17.573 xcodebuild[3539:28010]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/autohome/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/508BF65B-F6ED-4588-B1BD-4BA9B6A47642/Session-WebDriverAgentRunner-2016-12-09_102317-g1pvOM.log

>> xctest-client.js:171:14 [master] pid:3357 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:3357 2016-12-09 10:23:17.573 xcodebuild[3539:28004] [MT] IDETestOperationsObserverDebug: (F1532985-2562-429E-A5AE-5B271BE5F59D) Beginning test session WebDriverAgentRunner-F1532985-2562-429E-A5AE-5B271BE5F59D at 2016-12-09 10:23:17.572 with Xcode 8B62 on target <DVTiOSDevice: 0x7fecec86c6e0> {
		deviceSerialNumber:         CCQNF12CG22R
		identifier:                 8994ddd04b22016fbeb616d7aab65e1dafb352ee
		deviceClass:                iPod
		deviceName:                 毕彦为 的 iPod
		deviceIdentifier:           8994ddd04b22016fbeb616d7aab65e1dafb352ee
		productVersion:             9.3.5
		buildVersion:               13G36
		deviceSoftwareVersion:      9.3.5 (13G36)
		deviceArchitecture:         armv7f
		deviceTotalCapacity:        13507452928
		deviceAvailableCapacity:    9954734080
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fecec05bf00 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.5 (13G36))

>> xctest-client.js:171:14 [master] pid:3357 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:56:14 [master] pid:3357 Proxy: /session:POST to http://127.0.0.1:8900/session:POST with body: {"desiredCapabilities":{"bundleId":"com.autohome.new","platformName":"iOS","app":"/var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/T/autohome_macaca_demo.ipa"}}
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:170:14 [master] pid:3357 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/35d743e01c0987fc8a39bdbd26cfdacf/8994ddd04b22016fbeb616d7aab65e1dafb352ee/ManifestCache.plist

>> xctest-client.js:171:14 [master] pid:3357 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:3357 xctest client proxy error with: Error: socket hang up
>> proxy.js:84:20 [master] pid:3357 Got response with status 200: {"sessionId":null,"value":"Path must be to the application bundle\n\n(\n\t0   CoreFoundation                      0x2401b933 <redacted> + 150\n\t1   libobjc.A.dylib                     0x237b6e17 o...
>> responseHandler.js:47:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":"6f6556af-5d60-447f-98b6-1179d62598c5","status":0,"value":"{\"udid\":\"8994ddd04b22016fbeb616d7aab65e1dafb352ee\",\"platformName\":\"iOS\",\"app\":\"/var/folders/d7/rq09895n4wv8wf_ddgjm2cnw0000gn/T/autohome_macaca_demo.ipa\",\"autoAcceptAlerts\":true,\"bundleId\":\"com.autohome.new\"}"}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/6f6556af-5d60-447f-98b6-1179d62598c5/timeouts/implicit_wait, jsonBody: {"ms":10000}
>> responseHandler.js:47:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":"6f6556af-5d60-447f-98b6-1179d62598c5","status":0,"value":null}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/6f6556af-5d60-447f-98b6-1179d62598c5/element, jsonBody: {"using":"name","value":"论坛"}
>> proxy.js:56:14 [master] pid:3357 Proxy: /wd/hub/session/6f6556af-5d60-447f-98b6-1179d62598c5/element:POST to http://127.0.0.1:8900/wd/hub/session/6f6556af-5d60-447f-98b6-1179d62598c5/element:POST with body: {"using":"name","value":"论坛"}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> proxy.js:84:20 [master] pid:3357 Got response with status 200: {"sessionId":null,"value":"Unhandled endpoint: /wd/hub/session/6f6556af-5d60-447f-98b6-1179d62598c5/element -- http://127.0.0.1:8900/ with parameters {\n    wildcards =     (\n        \"wd/hub/sess...
>> session.js:107:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":null,"value":"\"Unhandled endpoint: /wd/hub/session/6f6556af-5d60-447f-98b6-1179d62598c5/element -- http://127.0.0.1:8900/ with parameters {\\n    wildcards =     (\\n        \\\"wd/hub/session/6f6556af-5d60-447f-98b6-1179d62598c5/element\\\"\\n    );\\n}\"","status":1}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:3357 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/6f6556af-5d60-447f-98b6-1179d62598c5, jsonBody: {}
>> macaca-ios.js:327:10 [master] pid:3357 Stoping iOS driver...
>> xctest-client.js:267:14 [master] pid:3357 killing deviceLogProc pid: 3536
>> xctest-client.js:272:14 [master] pid:3357 killing runnerProc pid: 3539
>> xctest-client.js:278:14 [master] pid:3357 killing iproxyProc pid: 3538
>> macaca-ios.js:351:10 [master] pid:3357 iOS driver cleaned up.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> session.js:80:12 [master] pid:3357 Delete session, sessionId: 6f6556af-5d60-447f-98b6-1179d62598c5
>> responseHandler.js:47:14 [master] pid:3357 Send HTTP Respone to Client: {"sessionId":"6f6556af-5d60-447f-98b6-1179d62598c5","status":0}
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:3357) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> xctest-client.js:145:16 [master] pid:3357 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:209:14 [master] pid:3357 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:181:14 [master] pid:3357 xctest client exit with code: null, signal: SIGKILL

**Comment by zenzhu** [comment]
研究了一下，是 ipa 的原因，装 APP 是没问题，已经修复了。更新一下 macaca-ios@1.0.51 即可。
