### ISSUE TITLE
tap()不支持vue中的tap事件

### ISSUE THREAD

**Issue by worry127722** [alibaba/macaca#353]
问题描述：
如果在vue中的一个节点对象上只监听了tap事件，那么macaca中的 tap（）方法无法成功触发该事件

**Comment by xudafeng** [comment]
如果是代理方式绑定的，excute触发一下呢？

**Comment by xudafeng** [comment]
@worry127722 搞定了吗

**Comment by xudafeng** [comment]
dom事件没问题 https://github.com/macaca-sample/vue-sample

**Comment by xudafeng** [comment]
@worry127722 示例 https://github.com/macaca-sample/vue-sample

支持点击操作和覆盖率

**Comment by xudafeng** [comment]
@worry127722 可以尝试使用 touchstart https://testerhome.com/topics/12255
