### ISSUE TITLE
js如何循环获取元素属性

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#354]
@xudafeng hi,请教一下，想循环获取某一元素的value属性，直到value等于某一特定值才退出，应该怎么做呢？代码如下，不知如何再次对value赋值，直接return又不是我想要的结果
return driver.elementByName("Progress").getProperty("value")
           .then(fuction(value){
               while(value != 100){
                    value = **此处想再次通过.getProperty("value")取值**
               }
})

**Comment by xudafeng** [comment]
@zsmjluo 学习下promise
