### ISSUE TITLE
android 英文无法输入的问题

### ISSUE THREAD

**Issue by yaniswang** [alibaba/macaca#357]
![image](https://cloud.githubusercontent.com/assets/970390/21008360/56152304-bd7c-11e6-88a9-dac7f4dfc9d2.png)

官方自带的apk，演示按照这个步骤，密码无法输入bbb
如果换成数字，就正常的。

**Comment by kobe990** [comment]
密码框应该是使用了native的密码控件，限制只能输入数字。即使唤起物理键盘，也是无法输入bbb的

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/439
