### ISSUE TITLE
使用Uirecorder 录制应用时报错

### ISSUE THREAD

**Issue by cjydayang** [alibaba/macaca#358]
* **Macaca Version**:
1.1.9
* **Macaca Doctor Logs**:
macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /opt/node-v6.9.1-linux-x64/bin/node
  node version: v6.9.1

  Android checklist:

  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `/opt/jdk`
  ANDROID_HOME is set to `/opt/android_develop/android_sdk`
  Platforms is set to `/opt/android_develop/android_sdk/platforms/android-24`
  Android tools is set to `/opt/android_develop/android_sdk/tools/android`
  ADB tool is set to `/opt/android_develop/android_sdk/platform-tools/adb`

  Installed driver list:

(node:13607) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
  android: 1.1.3

* **Operate System**:
Deepin linux x64

**uirecorder 的报错信息**：手机打开失败，请检查macaca是否配置正确？ Internal Server Error

**macaca server 的log：**
>> socket server ready
>> socket client ready
>> responseHandler.js:54:12 [master] pid:11588 Send Error Respone to Client: get apk mainifest failed with: TypeError: Cannot read property '1' of null

  InternalServerError: Internal Server Error
      at Object.throw (/opt/node-v6.9.1-linux-x64/lib/node_modules/.macaca-cli_npminstall/node_modules/.1.1.2@koa/lib/context.js:91:23)
      at Object.module.exports (/opt/node-v6.9.1-linux-x64/lib/node_modules/.macaca-cli_npminstall/node_modules/.1.0.68@webdriver-server/lib/server/responseHandler.js:57:17)
      at throw (native)
      at onRejected (/opt/node-v6.9.1-linux-x64/lib/node_modules/.macaca-cli_npminstall/node_modules/.4.6.0@co/index.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:103:7)

这是我录制某一个apk程序时的报错，试了其他几个apk程序则正常，我想确认出现这个问题是和apk有关还是其他原因，谢谢

**Comment by yaniswang** [comment]
你是基于模拟器录，还是基于真机？

如果是模拟器，是不是X86格式的？X86模拟器只支持跑X86格式的APK

**Comment by cjydayang** [comment]
@yaniswang 是基于真机来录制的，该apk应用在真机上可以正常安装。我在uirecorder的项目上和你提到过这个问题：https://github.com/alibaba/uirecorder/issues/49

**Comment by Kirkowo** [comment]
@cjydayang  可能是你那个没有安装成功，我昨天遇到了这个问题，然后把手机允许调试什么的打开，就可以运行了。
