### ISSUE TITLE
driver.webview() 出现 unknown error: Chrome version must be xxxx

### ISSUE THREAD

**Issue by laborchu** [alibaba/macaca#361]
* **Macaca Version**:1.1.19

* **Macaca Doctor Logs**:

> macaca-doctor version: 1.0.28
  Node.js checklist:
  node env: /Users/xxxx/.nvm/versions/node/v6.9.1/bin/node
  node version: v6.9.1
  iOS checklist:
  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  Android checklist:
  JAVA version is `1.7.0_71`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/xxxx/software/android-sdk-macosx`
  Platforms is set to `/Users/xxxx/software/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/xxxx/software/android-sdk-macosx/tools/android`
  ADB tool is set to `/Users/xxxx/software/android-sdk-macosx/platform-tools/adb`
  Installed driver list:
  android: 1.1.3
  electron: 1.1.4

* **Operate System**:macOs 10.12

* **Programming Language**:Nodejs

* **机器**:魅族mx4pro Android 5.1.1 flyme5.1.11

真机执行示例中的macaca-mobile-sample.test.js，执行driver.webview()时出现如下错误

> chromedriver ready with: {"sessionId":null,"status":13,"value":{"message":"unknown error: Chrome version must be >= 43.0.2357.0\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.12.0 x86_64)"}}

> Error: [contexts()] Error response status: 6,  Selenium error: no such session

**Comment by zenzhu** [comment]
这是让你升级魅族里面的 chrome 。

**Comment by laborchu** [comment]
@zenzhu 应该跟chrome没关系，我用另外一台华为p6就没有问题，华为没装chrome，我看了一下魅族的chrome版本是55的，我卸载掉chrome也不行

**Comment by laborchu** [comment]
@zenzhu 应该确实是chrome内核的关系，我查看测试app网页的内核，版本只有40，但是我看了一下魅族自带浏览器的版本有45，下载chrome浏览器的内核是55

**Comment by laborchu** [comment]
我刚才看了一下华为的那个，内核才30

**Comment by laborchu** [comment]
我把

> macaca-android/node_modules/macaca-chromedriver/exec/chromedriver

版本下降到2.15就可以了，下载地址在下面

> http://chromedriver.storage.googleapis.com/index.html
