### ISSUE TITLE
macaca如何定位到安卓端 自动滚动的viewpaper里的imageview

### ISSUE THREAD

**Issue by zjxht62** [alibaba/macaca#363]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

现在有一个程序 顶部是过一段时间自动滚动的viewpaper，里面有三个，现在我暂时只能点击这个view paper，但是无法做到想点击那个就点那个，请问大家是怎么解决的？谢谢！

**Comment by Yinxl** [comment]
用waitForElement的思路可以实现，在一定时间内轮寻目标ImageView，如果找到的话执行点击操作，如果没有没有，继续查找，可以根据你们的轮播图切换时间设置轮寻间隔以及最大时长。比如你们的动画切换时间为1s,你可以设置轮寻间隔为1s,然后总时长为3s。

**Comment by zjxht62** [comment]
谢谢！
