### ISSUE TITLE
移动端支持手势识别

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#366]
## 6 gestures supported

| Type              | Params                                   | Example                                  | Description       |
| ----------------- | ---------------------------------------- | ---------------------------------------- | ----------------- |
| tap               | { x: 100,  y: 100 }                      | driver.touch('tap', { x: 100, y: 100}) \| element.touch('tap') | 点击某个坐标或者当前元素   |
| doubleTap         | { x: 100,  y: 100 }                      | driver.touch('doubleTap', { x: 100, y: 100}) \| element.touch('doubleTap') | 双击某个坐标或者当前元素    |
| press             | { x: 100,  y: 100，duration: 2 (iOS，单位 S), steps: 100(Android) } | driver.touch('press', { x: 100, y: 100}) \| element.touch('press', { duration: 2 }) | 长按某个坐标或者当前元素    |
| pinch             | { x: 100,  y: 100，scale: 2 (iOS), velocity: 1(iOS),  direction: "in" or "out"(Android), percent: 200(Android), steps: 100(Android) } | iOS: element.touch('pinch', { scale: 2 }), Android: element.touch('pinch', { direction: "in", percent: 50 })  | 两只手指放大或者缩小当前元素    |
| rotate (iOS Only) | { rotation: 6(弧度), velocity: 1 }         | element.touch('rotate', { rotation: 6, velocity: 1 }) | 旋转当前元素            |
| drag              | { fromX: 100, fromY: 100, toX: 200, toY: 200, duration: 2(iOS，单位 S), steps: 100(Android)} | driver.touch('drag', { fromX: 100, fromY: 100, toX: 200, toY: 200 }) \| element.touch('drag', { toX: 200, toY: 200 }) | 拖拽一个元素或者在多个坐标之间移动 |

### 高级用法
连续执行多个 touch 操作，类似于下图的密码解锁。

```
driver.touch([{
  type: 'drag',
  fromX: 265,
  fromY: 860,
  toX: 825,
  toY: 860,
  steps: 200
}, {
  type: 'drag',
  toX: 265,
  toY: 1460
}, {
  type: 'drag',
  toX: 825,
  toY: 1460
}])
```

![touch-gestures](https://cloud.githubusercontent.com/assets/1011681/21174174/86de9c10-c216-11e6-8aae-0a89d305a6f2.png)

![1](https://cloud.githubusercontent.com/assets/1011681/21221462/68ef7fe8-c2f8-11e6-9e75-2b9814006b31.gif)

removed APIs

```
public static final String MOVE_TO = SESSION + "/moveTo";
public static final String SWIPE = SESSION + "/element/:elementId/swipe";
public static final String TOUCH_CLICK = SESSION + "/touch/click";
public static final String TOUCH_FLICK = SESSION + "/touch/flick";
```

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/198

**Comment by xudafeng** [comment]
https://github.com/xudafeng/android-app-bootstrap/pull/7

**Comment by xudafeng** [comment]
https://github.com/xudafeng/ios-app-bootstrap/pull/15

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.java/pull/67

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.py/commit/74a109a4194196f410103456395e701e2fe51e7c

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.py/commit/74a109a4194196f410103456395e701e2fe51e7c

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/231

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/pull/28

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/pull/46/files

**Comment by CodeToSurvive1** [comment]
tap像素的需求很迫切呀

**Comment by xudafeng** [comment]
@zenzhu 本次新增功能会实现的 @CodeToSurvive1

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/374

**Comment by mpreethi90** [comment]
@xudafeng ,Is the functionality done? If so, can you please provide an  example in JS on how to do swipe action? Swipe works fine in my local machine but when executed in saucelabs, I get an error that **The URL '/wd/hub/session/84eae9c3-2df1-426c-a81c-adc7f0b1a3e4/element/370/swipe' did not map to a valid resource**

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/macaca-test-sample-nodejs/commit/8bab04bafb174d2fddacb83b837ba8da0f6afe5a

**Comment by xudafeng** [comment]
https://testerhome.com/topics/6722

**Comment by beautyZ** [comment]
@xudafeng
你好，如果在使用touch之前，有步骤修改到了element，比如getElement()/isElementExist()，会导致touch的json参数漏传，代码如下
```
driver.getElement(GetElementWay.CLASS_NAME, "Application");

JSONObject json = new JSONObject();
json.put("fromX", 10);
json.put("fromY", 10);  
json.put("toX", 300);  
json.put("toY", 0);
json.put("duration", 0.5);

driver.touch("drag", json);
```
错误信息如下：
![22d1d338-6d82-4f80-b7c1-2b0b4ff865e3](https://cloud.githubusercontent.com/assets/24649023/21308864/d2024b34-c616-11e6-8de8-808f9c5c9e00.png)

如果在initDriver()之后，没有改变element的情况下，使用touch是正确的，如下：
![febc04ff-e3dd-4758-88b6-c4d9f4f64169](https://cloud.githubusercontent.com/assets/24649023/21308962/30d0ee36-c617-11e6-95c2-a3ba52ea8d56.png)

**Comment by adfghzhang** [comment]
@xudafeng 
达峰麻烦解释一下：
1.标准有(Android)或(iOS)的是否该参数只能在对应平台使用？
实验结果：drag可以在Android平台使用duration参数。
2.pinch的用法。
{ x: 100, y: 100，scale: 2 (iOS), velocity: 1(iOS), direction: "in" or "out"(Android), percent: 200(Android), steps: 100(Android) }
如果iOS用scale+velocity，Android使用direction+percent+steps?

**Comment by qq386169040** [comment]
@xudafeng 
遇到的问题：
IOS上，手势解锁操作中使用driver.touch()方法来实现‘先横后竖’的操作，但是执行时，并没有一步完成，而是连续的操作被分成两步操作分别进行的。请问是否支持ios？还是使用方法不对？

macaca版本：1.1.21
ios driver：1.0.53
手机：iPhone 6s  9.3.1
OS：10.11.6

源码：
``` javascript
driver.touch([
      {
        type: 'drag',
        fromX: 85,
        fromY: 312,
        toX: 281,
        toY: 312,
        duration:0.2
      },
      {
        type: 'drag',
        toX: 281,
        toY: 505
      }
    ]);
```

macaca server 日志：
```
>> responseHandler.js:11:12 [master] pid:77978 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/aa2ec7ef-7bf4-45c4-a46f-fd50ed20b523/actions, jsonBody: {"actions":[{"type":"drag","fromX":85,"fromY":312,"toX":281,"toY":312,"duration":0.2},{"type":"drag","toX":281,"toY":505}]}
>> proxy.js:56:14 [master] pid:77978 Proxy: /wd/hub/session/temp/dragfromtoforduration:POST to http://127.0.0.1:8900/session/47B7256E-7C1E-433A-A050-9B3BC40C4EE3/dragfromtoforduration:POST with body: {"fromX":85,"fromY":312,"toX":281,"toY":312,"duration":0.2}
>> proxy.js:84:20 [master] pid:77978 Got response with status 200: {"value":{},"sessionId":"temp","status":0}
>> proxy.js:56:14 [master] pid:77978 Proxy: /wd/hub/session/temp/dragfromtoforduration:POST to http://127.0.0.1:8900/session/47B7256E-7C1E-433A-A050-9B3BC40C4EE3/dragfromtoforduration:POST with body: {"toX":281,"toY":505,"duration":1}
>> proxy.js:84:20 [master] pid:77978 Got response with status 200: {"value":{},"sessionId":"temp","status":0}
>> responseHandler.js:47:14 [master] pid:77978 Send HTTP Respone to Client: {"sessionId":"aa2ec7ef-7bf4-45c4-a46f-fd50ed20b523","status":0,"value":null}
```

**Comment by zenzhu** [comment]
@qq386169040  iOS 原生就不支持这种手势操作，暂时只有安卓支持。

**Comment by qq386169040** [comment]
@zenzhu 谢谢你的解答

**Comment by ElesG** [comment]
求ios手势密码的解决方案，试过@qq386169040 的方法也试过连续tap，，好像都实现不了，，
另外想问一下touch方法在ios的坐标系是以怎么样子的，感觉每次定位都不准，用app-inspector给出的x，y参数都不怎么准确

**Comment by wlt184074150** [comment]
能否在tap方法增加个tap次数，我有个需求就是需要三击一个按钮，目前的api实现不了，尝试过tap，和doubletap串联起来使用，但是看了server的log，其实是两次http请求webdriveragent，时间比较长，导致三击不能生效，希望的是，tap时传入次数，一次请求webdriveragent完成三击

**Comment by loouxoon** [comment]
@qq386169040 @ElesG ios手势密码的问题你们解决了吗？

**Comment by ElesG** [comment]
@loouxoon 没有，而且升级了macaca版本后，，官方例子运行不了了，没法玩

**Comment by cingL** [comment]
#241 @wlt184074150

**Comment by taurusbb** [comment]
是否支持滑动？

**Comment by xuwei21** [comment]
iOS上，双指按住拖曳的旋转手势  当前是不是实现不了啊。。。

**Comment by SamuelZhaoY** [comment]
@xuwei21 on the way

**Comment by taurusbb** [comment]
是否支持快速滑动呢？

**Comment by mengdegong** [comment]
python ios  是不是暂时不支持press手势操作,使用后提示:
Error: WebDriverError.UNKNOWN_ERROR
Message: An unknown server-side error occurred while processing the command.

**Comment by mengdegong** [comment]
driver.wait_for_element('xpath','********',timeout=to).touch('press', { 'duration': 2})

**Comment by zwyxsyu** [comment]
ios， 通过webview上注入js获取元素（x, y, width, height）或抓取原生组件的getRect() ，实际代码中获取的值和看到的移动设备的坐标值不一致，导致无法操作（drag）。目前发现iphone6s是可以操作的，ipad不可以，不知道该问题是怎样导致的，怎么解决？

**Comment by zhugehui9527** [comment]
@xudafeng 我现在遇到和@qq386169040一样的问题 ，是不是iOS目前还不支持手势解锁？

**Comment by ZTinoZ** [comment]
.touch('doubleTap')双击速度不够快导致实际操作效果变成了2次单击 这个问题可以解决吗

**Comment by lvshuaijun** [comment]
android上使用python编程：self.driver.touch('drag', {"fromX": 500, "fromY": 1400, "toX": 500, "toY": 200, "steps": 100}) 不能实现拖拽的效果？这是怎么回事啊？  @xudafeng
