### ISSUE TITLE
各语言和示例补充全量API

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#367]
- 支持回归所有Node.js Java版本的API便于回归所有功能

- [x] dismiss keyboard?
- [x] 旋转屏幕
- [x] dismiss/accept alert 
- [x] ios/Android 物理键、unicode按键整理

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/168

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/268

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/issues/18

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/pull/47 alert

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/pull/29

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/macaca-test-sample-python/commit/cb001002311fe99405c1f1aae84a737d6c6d133e

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/mobile-app-sample-nodejs/commits/master

**Comment by wenshi11019** [comment]
建议在 Java 版本的源代码上，增加 javadoc 的注释，可以清晰知道 API 方法的用处

**Comment by xudafeng** [comment]
Java 全量 https://github.com/macaca-sample/macaca-test-sample-java

**Comment by xudafeng** [comment]
旋转屏幕 请在外围用adb解决
