### ISSUE TITLE
clear不能清除EditText中的密码

### ISSUE THREAD

**Issue by raininfall** [alibaba/macaca#369]
* **Macaca Version**: 
1.1.19

* **Macaca Doctor Logs**:
macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/rongqiansong/android/sdk`
  Platforms is set to `/Users/rongqiansong/android/sdk/platforms/android-24`
  Android tools is set to `/Users/rongqiansong/android/sdk/tools/android`
  ADB tool is set to `/Users/rongqiansong/android/sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.3
  chrome: 1.0.5

* **Operate System**:

Darwin rongqiansongdeMac-mini.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
* **Programming Language**:
node.js

clear不能清除EditText中的密码

测试工程： https://github.com/RainInFall/macacaClearTestAndroid
Android版本： 5.1 (API 22)
测试虚拟机参数模板： Nexus 5 (API 22)
测试实体机：MEIZU PRO5  , Android 5.1 (API 22),  Flyme 5.1.11.1A

**Comment by RainInFall** [comment]
更正： 在clear后添加延时2s，虚拟机和另一部手机（红米 NOTE2）可以清除密码，但是MEIZU PRO5仍不可以。

**Comment by kobe990** [comment]
棘手的问题，native隐藏数字类型的密码框，无法清除。连长按选中也无效。待调研

**Comment by xudafeng** [comment]
已解决

**Comment by cingL** [comment]
部分机型密码框还是没法clear成功。
用手上的测试机都试了一下
红米note2  √
NubiaZ7     ×
vivoX9        ×
另，在红米上观测到，有长按自动全选的现象，从而clear text
但是后两款机型无法长按全选
请问还有其他方法清除已有文本吗？谢谢

**Comment by xudafeng** [comment]
update driver
