### ISSUE TITLE
Is there a way to execute tests inside a folder parallel?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#370]
Say I have testA.test.js, testB.test.js inside a folder. Is there any way to execute these two tests parallel?

**Comment by xudafeng** [comment]
-f ava

**Comment by mpreethi90** [comment]
when I try using **ava** framework, I get below error message -

**ReferenceError: describe is not defined**

**Comment by dharmakrish6** [comment]
@mpreethi90 you can refer this site 
https://www.npmjs.com/package/mocha-parallel-tests

once installation done, run the test cases with `mocha-parallel-tests`

`mocha-parallel-tests ./Web/Smoketest/`

This will work fine with saucelab. not in local environment
