### ISSUE TITLE
跑安卓的sample时报错

### ISSUE THREAD

**Issue by hjw1991324** [alibaba/macaca#371]
![8n2 _9 vv3qe4 qnw 3h](https://cloud.githubusercontent.com/assets/8230181/21139970/832694d4-c170-11e6-861f-2d6631ebcfe4.png)
doctor出来的配置：
![7cwz w l ne ev3m ju 7iq](https://cloud.githubusercontent.com/assets/8230181/21139985/9d18fdd2-c170-11e6-8fb4-3aa6f6d2d900.png)

**Comment by Yinxl** [comment]
node7以上的版本好像会有问题，尝试一下node7以下的版本吧，可以试试6.9

**Comment by xudafeng** [comment]
@Yinxl Node7不兼容已经修复了

**Comment by xudafeng** [comment]
这个像是sdk没装好

**Comment by zhangfeilynu** [comment]
@xudafeng sdk安装好了啊

**Comment by zhangfeilynu** [comment]
macaca支持win7不啊

**Comment by xudafeng** [comment]
https://testerhome.com/topics/8039
