### ISSUE TITLE
.swipe() which works fine locally does not work in saucelabs VM

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#374]
I am not sure if this should come under your bucket. But, would be great if you could assist in letting know atleast the reason why it does not work in saucelabs VM?

**Comment by zenzhu** [comment]
Does saucelabs VM running macaca-cli  ? If it doesn't, server side implementation is depended their own service.

**Comment by mpreethi90** [comment]
@zenzhu , thank you for the reply. Can you please provide an example of using **TOuchActions** to do swipe on an element like in appium? I see TouchActions implemented in **macaca-wd?** It would be great

**Comment by xudafeng** [comment]
expose an inerface to adapt sourcelab's session server?

**Comment by mpreethi90** [comment]
Not sure what do you mean by that. But, from my integration experience with **macaca-saucelabs**, things works such that sauce VM server accepts protocols that are like appium's. Because when I use .**getProperty('origin')** it works in my local but does not in VM. Hence I used **getLocation()** which is there in appium that works like a charm in sauceLabs.
Thats the reason I am thinking if using **TouchActions** will be able to do **swipe** in VM

**Comment by mpreethi90** [comment]
FYI, I am now able to get **touchaction** variable from **macaca-wd** using **var TouchAction = new wd.TouchAction()** but not sure how to proceed with using the actions like longpress,moveTo etc.,
