### ISSUE TITLE
element.getProperty("description");获取不到description的值

### ISSUE THREAD

**Issue by guoqx123** [alibaba/macaca#375]
MacacaClient text=driver.getElement(GetElementWay.XPATH,"//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.webkit.WebView[1]/android.webkit.WebView[1]/android.view.View[3]/android.widget.Button[1]");
			JSONObject descObj = text.getProperty("origin");
			String desc0=descObj.toString();
			System.out.println("desc0"+desc0);
			
			JSONObject descObj1 = text.getProperty("size");
			String desc1=descObj1.toString();
			System.out.println("desc1"+desc1);
			
			JSONObject descObj2 = text.getProperty("description");
			String desc2=descObj2.toString();
			System.out.println("desc2"+desc2);

查看日志
	return: {"success":true,"data":{"status":0,"value":"{\"origin\":{\"x\":357,\"y\"
:669},\"size\":{\"width\":372,\"height\":108,\"centerX\":543,\"centerY\":723},
\"text\":\"\",\"description\":\"确定\"}"}}

打印结果
desc0{"y":669,"x":357}  
desc1{"centerY":723,"height":108,"centerX":543,"width":372}

origin与size的值可以获取到，description的值不能获取到，报错java.lang.ClassCastException: java.lang.String cannot be cast to com.alibaba.fastjson.JSONObject

**Comment by guoqx123** [comment]
text.getProperty("description");是一个string类型的，可是getProperty返回类型是JSONObject 
如果用String  descObj3 = text.getAttribute("description"); 还会报错Response content:Not Implemented

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/commit/a29d3278f9dcc878a877ecc1fa70fd39119ceb0f

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/pull/30
