### ISSUE TITLE
Android部分页面对输入框执行sentKeys，会触发旁边按钮的click事件，是什么问题？

### ISSUE THREAD

**Issue by laborchu** [alibaba/macaca#382]
@xudafeng  你知道原因吗？隐藏这个按钮就没有问题了

**Comment by laborchu** [comment]
这个问题应该跟macaca没有关系，appiumn也有人出现这个问题，https://github.com/appium/appium/issues/4297 具体原因不知道，我这边的解决方式就是改一下layout，下面两种方式我试了都可以
1.把Button放在一个layout里面
2.在Button前面放一个layout，可以把width和height设置为0

**Comment by c-yau** [comment]
请问最后调查出来是什么原因了吗？我最近也碰到这个问题，解决不了。

**Comment by laborchu** [comment]
@c-yau 没找到原因，但是调整布局可以解决问题，你可以试试
