### ISSUE TITLE
swipe无效，且没有touch等代替的api

### ISSUE THREAD

**Issue by yeehaoYBT** [alibaba/macaca#383]
<dependency>
			<groupId>macaca.webdriver.client</groupId>
			<artifactId>macacaclient</artifactId>
			<version>1.0.9</version>
</dependency>
macaca也已经更新到最新版本1.1.20,但是还是无法实现滑动

**Comment by zenzhu** [comment]
driver.touch('drag', { fromX: 100, fromY: 100, toX: 300, toY: 100, duration: 0.4 })
