### ISSUE TITLE
macaca-ios: 1.0.53 getProperty方法有错

### ISSUE THREAD

**Issue by candialala** [alibaba/macaca#386]
macaca-cli:1.1.21
Response content:{"value":"[<XCElementSnapshot 0x174361140> valueForUndefinedKey:]: this class is not key value coding-compliant for the key wdOrigin.\n\n(\n\t0   CoreFoundation                      0x0000000187f201d8 <redacted> + 148\n\t1   libobjc.A.dylib                     0x000000018695855c objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000187f1fe88 <redacted> + 0\n\t3   Foundation...more response is ignored..
An unknown server-side error occurred while processing the command.
![image](https://cloud.githubusercontent.com/assets/22468260/21373916/6b8f7bfe-c75d-11e6-871c-e1eb46d0ad8e.png)

**Comment by zenzhu** [comment]
getProperty('origin') 已经不用了，直接用 getRect 就可以得到 x, y, width, height。

**Comment by candialala** [comment]
@zenzhu 我看了js版的有这个接口，但是java版的没有

**Comment by zenzhu** [comment]
@Yinxl Java 版本也要加个 getRect 方法。

**Comment by candialala** [comment]
@zenzhu 好的，希望能尽快实现^_^
