### ISSUE TITLE
driver.touch('drag') does not work as expected

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#387]
PFB my request and response-
`
>> session.js:107:14 [master] pid:6191 Send HTTP Respone to Client: {"value":"{\"x\":0,\"y\":604}","sessionId":"3b7ac37e-ed38-4526-8c30-609b1c158996","status":0}
>> responseHandler.js:11:12 [master] pid:6191 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/3b7ac37e-ed38-4526-8c30-609b1c158996/actions, jsonBody: {"actions":**[{"fromX":200,"fromY":500,"toX":200,"toY":100,"duration":0.8,"type":"drag"}]}**
>> proxy.js:56:14 [master] pid:6191 Proxy: /wd/hub/session/temp/dragfromtoforduration:POST to http://192.168.1.62:8900/session/EBF4FD68-F0E7-4BE0-9075-7D41A4B47E1C/dragfromtoforduration:POST with body: **{"fromX":200,"fromY":200,"toX":200,"toY":100,"duration":0.8}**
>> proxy.js:84:20 [master] pid:6191 Got response with status 200: {"value":{},"sessionId":"temp","status":0}
`

**Comment by zenzhu** [comment]
There is a bug in macaca-ios@1.0.52, pls upgrade to 1.0.53, already fix the drag.

**Comment by mpreethi90** [comment]
thank you. Any update on 'getProperty' happened?
 Because **element.getProperty('origin')** was working fine but after macaca-ios@1.0.53 I get below message -

>> [ {"message":"[element.getProperty(\"origin\")] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command.","status":13,"cause":{"value":"[<XCElementSnapshot 0x7f815eb97980> valueForUndefinedKey:]: this class is not key value coding-compliant for the key wdOrigin.\n\n(\n\t0   CoreFoundation                      0x000000010ba42d85 __exceptionPreprocess + 165\n\t1   libobjc.A.dylib                     0x000000010b4b6deb objc_exception_throw + 48\n... ]

**Comment by zenzhu** [comment]
There is a new and easy way to get a element's dimensions and coordinates. Use 'getRect' you can get { x, y, height, width } back directly.

**Comment by mpreethi90** [comment]
Thank you so much!
