### ISSUE TITLE
ios真机测试问题，求教

### ISSUE THREAD

**Issue by GeorgeZh** [alibaba/macaca#388]
>> index.js:17:12 [master] pid:34006 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '10.0.0.114',
  host: 'GeorgeZ.local',
  loaded_time: '2016-12-21 17:50:35' }
>> middlewares.js:17:10 [master] pid:34006 base middlewares attached
>> router.js:127:10 [master] pid:34006 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:34006 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"deviceName":"iPhone 5s","platformName":"iOS","autoAcceptAlerts":false,"udid":"0edb9cee7e8f607d7a0c9e76d6fbd7483d259eb3","bundleId":"georgeZ.ios-app-bootstrap"}}
>> session.js:47:10 [master] pid:34006 Creating session, sessionId: ee2ecf63-910d-4755-8562-c69909383785.
ios-deploy
>> macaca-ios.js:229:12 [master] pid:34006 App "georgeZ.ios-app-bootstrap" is already installed.
>> xctest-client.js:56:14 [master] pid:34006 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:145:10 [master] pid:34006 {
	"bundleId": "georgeZ.ios-app-bootstrap",
	"platformName": "iOS"
}
>> macaca-ios.js:149:12 [master] pid:34006 Trying to start wda server...
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:34006 xcode version: 8.2
>> WebDriverAgent version: 1.0.41
>> xctest-client.js:170:14 [master] pid:34006 2016-12-21 17:50:42.624 xcodebuild[34021:9150711]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/george/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/80E2CFD4-1CC9-4A4B-A765-C7D48C7D3B57/Session-WebDriverAgentRunner-2016-12-21_175042-HbSf3f.log

>> xctest-client.js:171:14 [master] pid:34006 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:34006 2016-12-21 17:50:42.624 xcodebuild[34021:9150699] [MT] IDETestOperationsObserverDebug: (85772873-2126-42B3-A90B-CA0846BDCEC4) Beginning test session WebDriverAgentRunner-85772873-2126-42B3-A90B-CA0846BDCEC4 at 2016-12-21 17:50:42.623 with Xcode 8C38 on target <DVTiOSDevice: 0x7fb11ef47c40> {
		deviceSerialNumber:         DNPSDEZGHG71
		identifier:                 0edb9cee7e8f607d7a0c9e76d6fbd7483d259eb3
		deviceClass:                iPhone
		deviceName:                 GeorgeZ
		deviceIdentifier:           0edb9cee7e8f607d7a0c9e76d6fbd7483d259eb3
		productVersion:             10.2
		buildVersion:               14C92
		deviceSoftwareVersion:      10.2 (14C92)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        121850691584
		deviceAvailableCapacity:    101318459392
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fb11edaf620 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.2 (14C92))

>> xctest-client.js:171:14 [master] pid:34006 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:34006 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/ql/l977ttgj1jz4730n1xt13xlc0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/74f04c2f4a7278e3fdac2d90f0299b42/0edb9cee7e8f607d7a0c9e76d6fbd7483d259eb3/ManifestCache.plist

>> xctest-client.js:171:14 [master] pid:34006 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:34006 2016-12-21 17:50:54.410 xcodebuild[34021:9150699] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

>> xctest-client.js:171:14 [master] pid:34006 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:34006
Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

**Comment by zenzhu** [comment]
1. 把机器上的 WDA 删掉
2. 重新拔插真机
3. 实在不行重启

**Comment by leemony** [comment]
/usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
进这个目录，确保WebDriverAgent.xcodeproj编译成功

**Comment by jake20001** [comment]
autotest-ios:WebDriverAgent admin$ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=2a7cd84d5d266bdb2558972eb894aadbd8393481 test
2017-04-11 11:12:45.541 xcodebuild[5862:2495176]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cawmfybafmqbwbbksnlvaaamrjla/Logs/Test/9A4CA41F-2763-4112-AE20-02EA341C4C9A/Session-WebDriverAgentRunner-2017-04-11_111245-tEciTq.log
2017-04-11 11:12:45.541 xcodebuild[5862:2495089] [MT] IDETestOperationsObserverDebug: (43A30FB3-98FA-42FD-8C6F-9C36A2018879) Beginning test session WebDriverAgentRunner-43A30FB3-98FA-42FD-8C6F-9C36A2018879 at 2017-04-11 11:12:45.541 with Xcode 8E162 on target <DVTiOSDevice: 0x7fef349941d0> {
		deviceSerialNumber:         C8QLD5B1FFHR
		identifier:                 2a7cd84d5d266bdb2558972eb894aadbd8393481
		deviceClass:                iPhone
		deviceName:                 iPhone5c 10.1
		deviceIdentifier:           2a7cd84d5d266bdb2558972eb894aadbd8393481
		productVersion:             10.2.1
		buildVersion:               14D27
		deviceSoftwareVersion:      10.2.1 (14D27)
		deviceArchitecture:         armv7s
		deviceTotalCapacity:        13087301632
		deviceAvailableCapacity:    7095791616
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7fef3460b290 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.2.1 (14D27))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET IntegrationApp OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

Validate /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cawmfybafmqbwbbksnlvaaamrjla/Build/Products/Debug-iphoneos/IntegrationApp.app
    cd "/usr/local/lib/node_modules/appium/node_modules/._appium-xcuitest-driver@2.27.2@appium-xcuitest-driver/WebDriverAgent"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/appium/nodejs/bin:/Users/admin/.rvm/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/java/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/java/jre/lib:/Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/bin:/Users/admin/Desktop/WXJ_IOS/android-sdk-macosx/tools:/Users/admin/Desktop/WXJ_IOS/android-sdk-macosx/platform-tools:/Users/admin/Desktop/WXJ_IOS/android-sdk-macosx/build-tools/25.0.2:"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cawmfybafmqbwbbksnlvaaamrjla/Build/Products/Debug-iphoneos/IntegrationApp.app

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/b2/xryd_gbj04b2g5_r1yxsv7cm0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/045d1d24e6381edd91309c864f77f536/2a7cd84d5d266bdb2558972eb894aadbd8393481/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cawmfybafmqbwbbksnlvaaamrjla/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/b2/xryd_gbj04b2g5_r1yxsv7cm0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.oDauLw/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/b2/xryd_gbj04b2g5_r1yxsv7cm0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.oDauLw/WebDriverAgentRunner-Runner.app_sparse.ipa
__MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/b2/xryd_gbj04b2g5_r1yxsv7cm0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.oDauLw/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/b2/xryd_gbj04b2g5_r1yxsv7cm0000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.oDauLw/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
Test Suite 'All tests' started at 2017-04-11 11:12:56.159
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-04-11 11:12:56.164
Test Suite 'UITestingUITests' started at 2017-04-11 11:12:56.166
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-04-11 11:12:56.170
    t =     0.01s     Set Up
一直卡在那里？
