### ISSUE TITLE
macaca是否具有suite的概念？

### ISSUE THREAD

**Issue by ftvbftvbq** [alibaba/macaca#39]
FYI
组织用例执行顺序，比如：ios端和android端执行完毕后，然后，执行pc端的用例，谢谢！

**Comment by xudafeng** [comment]
PC，移动端混合执行是可以的，比如移动端的某些数据需要与PC端平台交互

**Comment by ftvbftvbq** [comment]
能否给出具体的例子呢？希望例子中包含了简单的业务逻辑关系，比如：移动端做完a业务后，启用pc端进行后台业务操作，这样的example才真的具有意义，谢谢！

**Comment by xudafeng** [comment]
@ftvbftvbq 

混合流程的文章，多机并行聊天的文章，后面会发到社区的。

如果你这已经遇到这种急需解决的场景，自己折腾一下或许更有意义哦
