### ISSUE TITLE
使用touch功能时，elementId默认值不为null

### ISSUE THREAD

**Issue by darker50** [alibaba/macaca#390]
使用touch功能默认使用elementId值为null。
但如果代码前面有element相关的操作，在touch中elementId会加1，会让touch功能中的elmentId默认值为数字，导致功滑动能不能使用，这个是个bug还是什么问题导致的啊
eg.
如前面代码有elementId操作 debug发现driver.touch("drag",JOSNObject)中的driver.getElementiD的值为1，正常的drag操作的elementId不应该是null的吗

**Comment by Yinxl** [comment]
这是wd.java的一个bug，已经修复了哈，更新到最新版本即可。

**Comment by darker50** [comment]
已更新到1.1.21版本了，还是有这个问题存在啊

**Comment by Yinxl** [comment]
我指的是macacaClient的版本 ，更新到1.0.40版本即可，你用的是什么脚本的,js吗？这个得讲明白呀
