### ISSUE TITLE
执行测试时报错，好像是说Android环境配置有问题，但是检查过都是正常的

### ISSUE THREAD

**Issue by zhaiworld** [alibaba/macaca#392]
* **Macaca Version**:1.1.21

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v7.0.0

  Android checklist:

  JAVA version is `1.6.0_39`
  JAVA_HOME is set to `D:\Program Files\jdk1.6.0_39`
  ANDROID_HOME is set to `D:\adt-bundle-windows-x86-20130219\adt-bundle-windows-
x86-20130219\sdk`
  Platforms is set to `D:\adt-bundle-windows-x86-20130219\adt-bundle-windows-x86
-20130219\sdk\platforms\android-17`
  Android tools is set to `D:\adt-bundle-windows-x86-20130219\adt-bundle-windows
-x86-20130219\sdk\tools\android.bat`
  ADB tool is set to `D:\adt-bundle-windows-x86-20130219\adt-bundle-windows-x86-
20130219\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `C:\apache-ant-1.9.7`

  Installed driver list:

  android: 1.1.13 [out-of-date]
  chrome: 1.0.5
  electron: 1.1.4
* **Operate System**:
windows7 pro
* **Programming Language**:
python

重新npm i macaca-android -g后，doctor显示正常。但是执行测试时出现：
C:\Users\zhaixirui\PycharmProjects\macaca-test-sample-python\tests>macaca server

>> webdriver sdk launched
>> uiautomator-client.js:31:12 [master] pid:10272 uiautomator-bootstrap was not
found in: C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca-android\nod
e_modules\.1.0.43@uiautomator-client\bin\uiautomator-bootstrap.jar, please check
 your Android ENV

  Error: >> uiautomator-client.js:31:12 [master] pid:10272 uiautomator-bootstrap
 was not found in: C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca-an
droid\node_modules\.1.0.43@uiautomator-client\bin\uiautomator-bootstrap.jar, ple
ase check your Android ENV
      at Logger.error (C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macac
a-android\node_modules\.1.0.6@xlogger\lib\xlogger.js:169:9)
      at UIAutomator.init (C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\m
acaca-android\node_modules\.1.0.43@uiautomator-client\lib\uiautomator-client.js:
31:12)
      at UIAutomator.init.next (<anonymous>)
      at onFulfilled (C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca
-cli\node_modules\co\index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by zenzhu** [comment]
你检查下 C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca-an
droid\node_modules.1.0.43@uiautomator-client\bin\uiautomator-bootstrap.jar有这个文件吗

**Comment by zhaiworld** [comment]
没有，路径到C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca-android\node_modules就不一样了

**Comment by zhaiworld** [comment]
@zenzhu 没有，路径到C:\Users\zhaixirui\AppData\Roaming\npm\node_modules\macaca-android\node_modules就不一样了

**Comment by zhaiworld** [comment]
我换了台windows7电脑，重装配置各种环境，试了一下还是不行，chrome可以启动测试。安卓的就是不可以。不知道该怎么补全这些缺少的文件

**Comment by zenzhu** [comment]
你是不是使用 cnpm 之类安装 macaca-android 的，尝试用原生的装一下，应该是这个文件不存在。

**Comment by zhaiworld** [comment]
是这个文件不存在，我在另一台电脑上用cnpm安装的也没有。我能通过卸载重装的方式来搞定吗，只是不知道缺少的文件依赖于哪个包

**Comment by zenzhu** [comment]
缺少的文件就是一个独立的 jar 没啥影响，不确定 cnpm 有什么问题，先重装试试。
