### ISSUE TITLE
macaca doctor : android: 1.1.12 [out-of-date] error

### ISSUE THREAD

**Issue by yatheendrabc** [alibaba/macaca#393]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

Macaca Version: 1.1.21
Macaca Doctor:  macaca-doctor version: 1.0.28

 Node.js checklist:

 node env: C:\Program Files\nodejs\node.exe
 node version: v6.9.2

 Android checklist:

 JAVA version is `1.8.0_101`
 JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
 ANDROID_HOME is set to `D:\EDrive\android-sdk-windows`
 Platforms is set to `D:\EDrive\android-sdk-windows\platforms\android-24`
 Android tools is set to `D:\EDrive\android-sdk-windows\tools\android.bat`
 ADB tool is set to `D:\EDrive\android-sdk-windows\platform-tools\adb.exe`
 ANT_HOME is set to `D:\D drive\apache-ant-1.9.4`

 Installed driver list:

 android: 1.1.12 [out-of-date]
 chrome: 1.0.5
 electron: 1.1.4
Platform: either Windows, version 64-bit.

Please mention what to update for the above android out-of-date issue

**Comment by xudafeng** [comment]
npm i macaca-android -g

**Comment by MahadevG** [comment]
Hi, In my case 
I am not able to see installed driver list.
Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v8.9.4

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_141`
  ANDROID_HOME is set to `C:\Users\Mahadev\AndriodSoftwere\android-sdk-windows`
  Platforms is set to `C:\Users\Mahadev\AndriodSoftwere\android-sdk-windows\platforms\android-26`
  ADB tool is set to `C:\Users\Mahadev\AndriodSoftwere\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\Gradle\gradle-4.2\bin`

  Installed driver list:




C:\Users\Mahadev>npm install app-inspector -g
