### ISSUE TITLE
ios 执行一段时间报错

### ISSUE THREAD

**Issue by hujiachun** [alibaba/macaca#396]
# macaca doctor ：
acaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.3.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy

ios: 1.0.53

# macaca log：
>> proxy.js:84:20 [master] pid:39962 Got response with status 200: {"value":"Application is not running, possibly crashed","sessionId":"temp","status":10}
>> responseHandler.js:54:12 [master] pid:39962 Send Error Respone to Client: StaleElementReference: An element command failed because the referenced element is no longer attached to the DOM.
>> responseHandler.js:60:14 [master] pid:39962 StaleElementReference: An element command failed because the referenced element is no longer attached to the DOM.
    at actionDelegate.call.then.result (/usr/local/lib/node_modules/.macaca-ios_npminstall/node_modules/.1.0.53@macaca-ios/lib/actions.js:121:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
>> responseHandler.js:76:14 [master] pid:39962 Send Bad HTTP Respone to Client: {"sessionId":"814e751a-b4fa-4108-a226-afaaa545d54a","status":10,"value":{"message":"An element command failed because the referenced element is no longer attached to the DOM."}}

**Comment by hujiachun** [comment]
@xdf  每次执行1个小时之后就报错了

**Comment by xudafeng** [comment]
iOS不稳定暂时没有好的解决办法，找个issue 先保留

**Comment by hujiachun** [comment]
在macaca的基础上写了随机事件跑稳定性，大概1个多小时就报错停止了，请问下有没有解决方案呀

**Comment by xudafeng** [comment]
@hujiachun 可以把你写的工程提交到github看看嘛

**Comment by hujiachun** [comment]
https://github.com/hujiachun/iosMonkey

@xudafeng  工程地址如上

**Comment by hujiachun** [comment]
ios不稳定问题有解决方案了吗？昨天发现ios版本回退了？
