### ISSUE TITLE
使用自己这边的app,模拟器有打开。app无法运行

### ISSUE THREAD

**Issue by lengyao88** [alibaba/macaca#4]
Last login: Wed Mar 23 16:08:02 on ttys000
clydeiMac:~ cly$ cd /Users/cly/Desktop/macaca-test/
clydeiMac:macaca-test cly$ make test
platform= macaca run --server --verbose
>> index.js:62:12 [master] pid:95872 webdriver server start with config:
 { port: 3456,
  ip: '192.168.3.70',
  host: 'clydeiMac.local',
  loaded_time: '2016-03-23 16:22:55' }
>> middlewares.js:31:10 [master] pid:95872 base middlewares attached
>> router.js:101:10 [master] pid:95872 router set
>> webdriver sdk launched
>> 
>> 
>>   macaca test sample
>> responseHandler.js:24:12 [master] pid:95872 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.2","deviceName":"iPhone 5s","app":"/Users/cly/Desktop/macaca-test/app/Surfboard.zip"}}
>> session.js:22:10 [master] pid:95872 Creating session, sessionId: 6dc40f1c-90e4-410f-b8ff-7043a3d50878.
>> helper.js:202:12 [master] pid:95872 Unzipping local app form /Users/cly/Desktop/macaca-test/app/Surfboard.zip
Get bundleId com.mosheberman.Surfboard from plist /var/folders/rf/1xrmds252jz7_j_pn27tkd380000gn/T/Surfboard.app/Info.plist
>> macaca-ios.js:128:10 [master] pid:95872 Get available devices [{"name":"iPhone 4s","udid":"13206806-16B8-409E-925B-A810C97B14C9","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 5","udid":"80EE788F-1100-4F5C-9647-CD45475A611A","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 5s","udid":"D631C120-FE43-4868-A603-78C06D7A41AC","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6","udid":"B5234B6C-BAD4-4C7C-BD47-77072EDB860C","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6 Plus","udid":"D604121E-0972-4CCB-AE77-AB09C1B93BD7","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6s","udid":"55022D79-D177-48FE-BFFA-C69155A7A037","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6s Plus","udid":"4FC6AA02-E6B9-416F-94B7-37569513BE94","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad 2","udid":"619F0A8C-9656-4BE2-98E3-96FEDEB31D07","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Retina","udid":"2BC7D133-D644-43A9-BE9E-7837351D0557","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Air","udid":"157C433B-644E-4957-A117-C68B3B8B51B2","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Air 2","udid":"981A2A6D-34D4-4933-9BA2-67F571C9DF76","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Pro","udid":"646D9BC8-CE0F-4B6F-8D5A-9199EF3ED6D0","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"Apple TV 1080p","udid":"27B45B68-8D4C-430A-9EE1-8F7D0E27CC33","state":"Shutdown","available":true,"runtime":"tvOS 9.1"},{"name":"Apple Watch - 38mm","udid":"D8D4DE1D-09EF-4B56-970C-2B6AA37A47CC","state":"Shutdown","available":true,"runtime":"watchOS 2.1"},{"name":"Apple Watch - 42mm","udid":"F091E9FB-889C-4CEF-BE24-CE311DEA993C","state":"Shutdown","available":true,"runtime":"watchOS 2.1"}]
>> macaca-ios.js:94:12 [master] pid:95872 Kill simulator failed Error: Command failed: /bin/sh -c killAll Simulator
No matching processes belonging to you were found

>> macaca-ios.js:100:12 [master] pid:95872 Shutdown simulator D631C120-FE43-4868-A603-78C06D7A41AC failed Error: Command failed: /bin/sh -c xcrun simctl shutdown "D631C120-FE43-4868-A603-78C06D7A41AC"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to shutdown device in current state: Shutdown

>> agent path: /Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-ios/node_modules/xctest-client/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcworkspace
>> macaca-ios.js:75:10 [master] pid:95872 {"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.2","deviceName":"iPhone 5s","app":"/var/folders/rf/1xrmds252jz7_j_pn27tkd380000gn/T/Surfboard.app/"}
>> xctest-client.js:122:14 [master] pid:95872 2016-03-23 16:23:40.805 xcodebuild[96002:305784] [MT] IDETestOperationsObserverDebug: (9EE233E5-906D-4875-9EA0-0B58DC5F6A39) Beginning test session 9EE233E5-906D-4875-9EA0-0B58DC5F6A39 with Xcode 7C68 on target <DVTiPhoneSimulator: 0x7fb8ee2dd3e0> {
		SimDevice: SimDevice : iPhone 5s (D631C120-FE43-4868-A603-78C06D7A41AC) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 9.2 (13C75) - com.apple.CoreSimulator.SimRuntime.iOS-9-2 }
} (9.2 (13C75))

>> Proxy: /session:POST to http://127.0.0.1:8100/session:POST with body: {"desiredCapabilities":{"platformName":"iOS","platformVersion":"9.2","deviceName":"iPhone 5s","autoAcceptAlerts":true,"app":"/var/folders/rf/1xrmds252jz7_j_pn27tkd380000gn/T/Surfboard.app/","bundle...
>> responseHandler.js:24:12 [master] pid:95872 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.2","deviceName":"iPhone 5s","app":"/Users/cly/Desktop/macaca-test/app/Surfboard.zip"}}
>> session.js:22:10 [master] pid:95872 Creating session, sessionId: fcbd35c2-5e7a-48a5-95f9-72d971e05b88.
>> helper.js:202:12 [master] pid:95872 Unzipping local app form /Users/cly/Desktop/macaca-test/app/Surfboard.zip
Get bundleId com.mosheberman.Surfboard from plist /var/folders/rf/1xrmds252jz7_j_pn27tkd380000gn/T/Surfboard.app/Info.plist
>> macaca-ios.js:128:10 [master] pid:95872 Get available devices [{"name":"iPhone 4s","udid":"13206806-16B8-409E-925B-A810C97B14C9","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 5","udid":"80EE788F-1100-4F5C-9647-CD45475A611A","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 5s","udid":"D631C120-FE43-4868-A603-78C06D7A41AC","state":"Booted","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6","udid":"B5234B6C-BAD4-4C7C-BD47-77072EDB860C","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6 Plus","udid":"D604121E-0972-4CCB-AE77-AB09C1B93BD7","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6s","udid":"55022D79-D177-48FE-BFFA-C69155A7A037","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPhone 6s Plus","udid":"4FC6AA02-E6B9-416F-94B7-37569513BE94","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad 2","udid":"619F0A8C-9656-4BE2-98E3-96FEDEB31D07","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Retina","udid":"2BC7D133-D644-43A9-BE9E-7837351D0557","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Air","udid":"157C433B-644E-4957-A117-C68B3B8B51B2","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Air 2","udid":"981A2A6D-34D4-4933-9BA2-67F571C9DF76","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"iPad Pro","udid":"646D9BC8-CE0F-4B6F-8D5A-9199EF3ED6D0","state":"Shutdown","available":true,"runtime":"iOS 9.2"},{"name":"Apple TV 1080p","udid":"27B45B68-8D4C-430A-9EE1-8F7D0E27CC33","state":"Shutdown","available":true,"runtime":"tvOS 9.1"},{"name":"Apple Watch - 38mm","udid":"D8D4DE1D-09EF-4B56-970C-2B6AA37A47CC","state":"Shutdown","available":true,"runtime":"watchOS 2.1"},{"name":"Apple Watch - 42mm","udid":"F091E9FB-889C-4CEF-BE24-CE311DEA993C","state":"Shutdown","available":true,"runtime":"watchOS 2.1"}]
>> proxy.js:71:18 [master] pid:95872 xctest client proxy error with: Error: socket hang up
/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:155
  throw new Error(res);
  ^

Error: >> proxy.js:71:18 [master] pid:95872 xctest client proxy error with: Error: socket hang up
    at Logger.error (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:155:9)
    at Request._callback (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-ios/node_modules/xctest-client/lib/proxy.js:71:18)
    at self.callback (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/cly/.nvm/versions/node/v4.4.0/lib/node_modules/macaca-client/node_modules/webdriver-server/node_modules/node-installer/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketOnEnd (_http_client.js:292:9)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
clydeiMac:macaca-test cly$

**Comment by zenzhu** [comment]
后面那个错误，是因为第一个请求未处理完又再次请求导致的，看看是否能够在 driver.initDriver() 后等待足够的时间让App启动起来。

**Comment by lengyao88** [comment]
感觉不是这个原因，发现安装的 app都是无法手动打开的。

**Comment by xudafeng** [comment]
@lengyao88 sample 里提供的 app 是可以打开的吗？

**Comment by lengyao88** [comment]
里面提供的是可以的

**Comment by xudafeng** [comment]
@lengyao88 推荐检查下你要测试的 App

**Comment by lengyao88** [comment]
这个APP我用xcode编译运行是正常的

**Comment by xudafeng** [comment]
@lengyao88 模拟器 sdk 版本一致吗？

**Comment by lengyao88** [comment]
要不，我把从网上的源代码给你吧。

**Comment by xudafeng** [comment]
@lengyao88 可以

**Comment by zenzhu** [comment]
@lengyao88  我这边测试了一下，是可以成功打开你的App的，所以我想有没有可能是打的包的问题。

**Comment by lengyao88** [comment]
嗯，确实是我打包的问题。问题解决了，谢谢你们的耐心帮我找到问题。开发给我的另外个app也是编译的问题。我用xcodebuild -sdk iphonesimulator9.2 -configuration Debug编译的是可以使用的。

**Comment by wrldeop** [comment]
你好  正确的应该打什么样的包 我这边也遇到了这样的问题
