### ISSUE TITLE
make test-pc, the browser is not shown

### ISSUE THREAD

**Issue by Alison2012win** [alibaba/macaca#40]
* **Macaca Version**:

  1.0.24

* **Macaca Doctor**:

  Node.js checklist:
  node env: C:\Program Files\nodejs\node.exe
  node version: v5.2.0

  Android checklist:

* **Platform**:

 Windows 7 64bit

* **Q Details**:

  **these are what I have done：**
  1、clone macaca-test-sample
  2、npm install
  3、download ’make‘ and install（to solve ''make' is not recognized as an internal or external command' problem）
  4、cd macaca-test-sample
  5、export CHROMEDRIVER_CDNURL=http://npm.taobao.org/mirrors/chromedriver
  6、export ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron
  7、make test-pc

  **then show:**
![image](https://cloud.githubusercontent.com/assets/10734177/15067664/a8ab25dc-13a4-11e6-9b1e-57c2a2a9c240.png)

  **Q：  `the browser is not opened ` like your test-PC demo shows**

  **If there are some errors in my operations? Hope for your help, thx~ **

**Comment by xudafeng** [comment]
@Alison2012win 推荐用 linux 或 mac

**Comment by Alison2012win** [comment]
@xudafeng 好的，我试试，谢谢~

**Comment by xudafeng** [comment]
@Alison2012win 升级最新 macaca-cli
