### ISSUE TITLE
macaca java版如何判断内嵌的H5页面是否成功加载？

### ISSUE THREAD

**Issue by zjxht62** [alibaba/macaca#400]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

由于需要进行内嵌H5的测试，所以需要进行js注入，但是注入时必须先要确保页面已经正确加载完成 ，我现在的思路是sleep5000ms，这么长的时间页面应该已经加载完毕了，但是页面有很多，这样的话太浪费时间，请问大家有什么好的方法么？

**Comment by xudafeng** [comment]
去社区问比较合适
