### ISSUE TITLE
Webview真机测试时使用.source()获取到的是一个JSON，请问怎么才能获取HTML？

### ISSUE THREAD

**Issue by GeorgeZh** [alibaba/macaca#402]
>> { tree:
   { bounds: '{{0, 0}, {375, 667}}',
     isEnabled: '1',
     isVisible: '1',
     children: [ [Object], [Object] ],
     rect: { y: 0, x: 0, width: 375, height: 667 },
     value: null,
     label: 'M部落',
     type: 'Application',
     name: 'M部落',
     rawIdentifier: null } }

**Comment by GeorgeZh** [comment]
还有，我使用driver.webview()时会报错“is not a function”

**Comment by GeorgeZh** [comment]
Error: [execute("document.getElementById('classroom')")] Error response status: 1

**Comment by GeorgeZh** [comment]
Error: [contexts()] Not JSON response,求救～～

**Comment by xudafeng** [comment]
.source 多看文档，理解wd语义
