### ISSUE TITLE
macaca-inspector ios真机启动不起来，长时间卡顿

### ISSUE THREAD

**Issue by GavinHellen** [alibaba/macaca#406]
* **Macaca Version**:
pp-inspector@1.2.18
* **Macaca Doctor Logs**:
>> app-inspector:66:44 [master] pid:14356 undefined
执行到这个地方就会长时间卡顿
* **Operate System**:
mac
* **Programming Language**:
no

**Comment by GavinHellen** [comment]
@xudafeng 长时间卡顿，日志停顿在app-inspector:66:44 [master] pid:14356 undefined
插上真机很容易看到现象

**Comment by lixiaoyudakeke** [comment]
我也有同样的问题，请问有解决办法了吗

**Comment by xudafeng** [comment]
升级新版
