### ISSUE TITLE
Issue in macaca.js installation in MAC

### ISSUE THREAD

**Issue by Prasanthquick** [alibaba/macaca#407]
Hi,
I am facing issue in macaca.js installation with mac. I installed all dependencies correctly and showed correctly when running command as "macaca doctor". But it is not showing the installed driver list there. Installed chrome and electron correctly. Please help.
Macaca Version: 1.1.21
Macaca Doctor: 1.1.21
* **Operate System**: MAC
<img width="812" alt="screen shot 2016-12-29 at 3 01 58 pm" src="https://cloud.githubusercontent.com/assets/13111996/21560274/4c836de8-ce82-11e6-9456-aa8d629f11ed.png">

**Comment by xudafeng** [comment]
try this command, and print your doctor info
```
npm i macaca-ios -g
```
