### ISSUE TITLE
将官方示例(mobile-app-sample-nodejs)克隆到本地，运行报错（win 7系统）

### ISSUE THREAD

**Issue by SmallBlackboard** [alibaba/macaca#409]
# 报错如下：
$ macaca run --verbose
>> index.js:17:12 [master] pid:2728 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.155.1',
  host: 'shishy',
  loaded_time: '2017-01-03 14:50:18' }
>> middlewares.js:17:10 [master] pid:2728 base middlewares attached
>> router.js:127:10 [master] pid:2728 router set
>> webdriver sdk launched
[ 'E:\\github\\macaa\\mobile-app-sample-nodejs\\node_modules\\.bin\\mocha',
  'macaca-test',
  '--colors',
  '--verbose' ]
>> E:\github\macaa\mobile-app-sample-nodejs\node_modules\.bin\mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

>> Test completed!

# macaca环境如下：

$ macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v6.2.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\javasoftware\javajdk8`
  ANDROID_HOME is set to `F:\android-sdk-windows`
  Platforms is set to `F:\android-sdk-windows\platforms\android-24`
  Android tools is set to `F:\android-sdk-windows\tools\android.bat`
  ADB tool is set to `F:\android-sdk-windows\platform-tools\adb.exe`
  ANT_HOME is set to `E:\20161104windows\apache-ant-1.9.7`

  Installed driver list:

  android: 1.1.15
  chrome: 1.0.5
  electron: 1.1.4

**Comment by xudafeng** [comment]
参考travis日志，解决win环境问题 https://github.com/macaca-sample/mobile-app-sample-nodejs

**Comment by scheibe1874** [comment]
我也遇到了相同的问题，请问您是怎么解决的

**Comment by SmallBlackboard** [comment]
@scheibe1874    我这边也没有解决，issues不知道怎么就关了。。。。
那个travis日志里面没有找到有用的信息

**Comment by scheibe1874** [comment]
@SmallBlackboard  travis我也没找到解决的突破口
macaca doctor没发现有什么问题 
run的时候一直报SyntaxError: missing ) after argument list

**Comment by SmallBlackboard** [comment]
@scheibe1874 在mac和ubuntu上run都是没问题的，开始以为是nodejs的版本问题（我原来用的是node4.5）,升级到6.2之后还是这里报错，这会不会是win7上兼容性问题??? 看看他们怎么解决吧
@xudafeng

**Comment by scheibe1874** [comment]
@SmallBlackboard  所以你就不在windows上使用了吗

**Comment by SmallBlackboard** [comment]
@scheibe1874 Windows上还使用，报这个错是因为最新的官方脚本实例上新增了许多新的功能，macaca原来的那些功能现在基本上可以满足我这边的开发需求，所以只是暂时先放弃macaca的新功能，等这个问题解决了之后再考虑这些新功能。

**Comment by scheibe1874** [comment]
@SmallBlackboard macaca run 这个命令都起不来 是怎么使用那些功能的呢？ “暂时先放弃macaca的新功能”的意思是 您使用的是历史版本 ？

**Comment by SmallBlackboard** [comment]
@scheibe1874 是脚本里面加了touch()这些新功能，我使用的是top(),swipe()这些对手机的点击，滑动事件。

**Comment by scheibe1874** [comment]
@SmallBlackboard  我在mac上搭完了报这个错Error: [init({"platformName":"Android","autoAcceptAlerts":false,"app":"https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk"})] The environment you requested was unavailable.     你遇到过没
