### ISSUE TITLE
关于android context切换到webview以后切回native的issue

### ISSUE THREAD

**Issue by laborchu** [alibaba/macaca#412]
@xudafeng 
**Macaca Android**:1.1.15
**场景：**
1、先把Context切换到webview
2、再把Context切换回native
3、调用driver.touch("drag",{})
4、出现NotImplementedError: Action drag is not implemented yet
**原因：**
问题出现在macaca-android下面的controllers.js
切换到webview的时候会把this.context赋值为CDwindow-xxxxxxx，但是切换会navite的时候，没有对this.context赋值为NATIVE_APP，导致在isWebContext判断时候永远为true了

![image](https://cloud.githubusercontent.com/assets/5244556/21677217/245a04ac-d374-11e6-839c-d792ca79822d.png)

![image](https://cloud.githubusercontent.com/assets/5244556/21677231/416dc8c6-d374-11e6-9f19-f00f9af8d233.png)

**Comment by xudafeng** [comment]
@laborchu web没支持touch的

**Comment by xudafeng** [comment]
@laborchu 明白了，我检查下这个bug，稍等回复你

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/pull/57

**Comment by xudafeng** [comment]
请升级macaca-android
