### ISSUE TITLE
Macaca 在运行过程中，app 发生 crash , 该怎么截图

### ISSUE THREAD

**Issue by AllocAndInit** [alibaba/macaca#413]
有一个疑问，如果在自动化测试过程中，app 发生 crash ,此时 如何捕获当前 app 崩溃的时机并截图？请问这个可以实现吗？对nodejs 不是很熟悉，如果能实现，请问在测试用例里面该怎么写？

如果在每个测试用例 promise chain 的最后加一个 catch 语句能够捕捉到崩溃的时间与信息？测试用例里该如何添加？能不能说的具体一点？ 本身 对 nodejs 不是很熟悉，多谢各位啦

**Comment by xudafeng** [comment]
@AllocAndInit 看描述你使用的是 JS 语言栈，可以通过 afterEach 实现，就像这样 https://github.com/macaca-sample/sample-nodejs/blob/master/macaca-test/mobile-app-sample.test.js#L88
