### ISSUE TITLE
macaca ios autoAcceptAlerts 参数第一次弹出的系统alert起作用，后面再弹出来的无效,不会点击accetp

### ISSUE THREAD

**Issue by GavinHellen** [alibaba/macaca#414]
* **Macaca Version**:
V1.0.53
* **Macaca Doctor Logs**:
porps.put("autoAcceptAlerts", true);
* **Operate System**:
mac
* **Programming Language**:
java

**Comment by xudafeng** [comment]
@GavinHellen 改为手动调用试试

**Comment by xudafeng** [comment]
autoAcceptAlerts 会在每次操作时调用一次acceptAlert，如果有连续多次弹出可以手动acceptAlert
