### ISSUE TITLE
app-inspector 查看包含UIAPickerWheel 元素长时间没有反应

### ISSUE THREAD

**Issue by xiaowei1003** [alibaba/macaca#415]
* **Macaca Version**:
1.1.21
* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.3.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home`
  ANDROID_HOME is not set

  Installed driver list:

  ios: 1.0.53

* **Operate System**:
Darwin VM-Mac.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

![image](https://cloud.githubusercontent.com/assets/24948983/21705509/509bf7fa-d3fb-11e6-8711-7bdcaaa0b02a.png)

**Comment by xudafeng** [comment]
新版支持
