### ISSUE TITLE
IOS中根据属性 isVisible 定位元素异常关闭

### ISSUE THREAD

**Issue by xiaowei1003** [alibaba/macaca#416]
Macaca Version:
1.1.21

Macaca Doctor Logs:
macaca-doctor version: 1.0.28

Node.js checklist:

node env: /usr/local/bin/node
node version: v7.3.0

iOS checklist:

Xcode is installed at: /Applications/Xcode.app/Contents/Developer
Xcode Command Line Tools is ready, version: 2347.
iproxy[usbmuxd] is installed at: /usr/local/bin/iproxy
ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

Android checklist:

JAVA version is 1.8.0_112
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home
ANDROID_HOME is not set

Installed driver list:

ios: 1.0.53

Operate System:
Darwin VM-Mac.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

**XPath语句:  //XCUIElementTypeTable[1]/XCUIElementTypeCell[@isVisible='1']**
![image](https://cloud.githubusercontent.com/assets/24948983/21712052/64cbb8f0-d42d-11e6-8be5-7270fc5ae0cb.png)

`>> responseHandler.js:11:12 [master] pid:12967 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/bcbcee4f-ccc9-417d-aee9-21b68d03adb7/elements, jsonBody: {"using":"xpath","value":"//XCUIElementTypeTable[1]/XCUIElementTypeCell[@isVisible='1']"}
>> proxy.js:56:14 [master] pid:12967 Proxy: /wd/hub/session/temp/accept_alert:POST to http://192.168.2.83:8900/session/F06CAFF9-1A9E-4C7B-AF50-8FE1CC2FE482/accept_alert:POST with body: {}
>> proxy.js:84:20 [master] pid:12967 Got response with status 200: {"value":{},"sessionId":"temp","status":27}
>> proxy.js:56:14 [master] pid:12967 Proxy: /wd/hub/session/bcbcee4f-ccc9-417d-aee9-21b68d03adb7/elements:POST to http://192.168.2.83:8900/session/F06CAFF9-1A9E-4C7B-AF50-8FE1CC2FE482/elements:POST with body: {"using":"xpath","value":"//XCUIElementTypeTable[1]/XCUIElementTypeCell[@isVisible='1']"}
>> proxy.js:84:20 [master] pid:12967 Got response with status 200: {"value":[],"sessionId":"bcbcee4f-ccc9-417d-aee9-21b68d03adb7","status":0}
>> session.js:107:14 [master] pid:12967 Send HTTP Respone to Client: {"value":"[]","sessionId":"bcbcee4f-ccc9-417d-aee9-21b68d03adb7","status":0}
>> responseHandler.js:11:12 [master] pid:12967 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/bcbcee4f-ccc9-417d-aee9-21b68d03adb7, jsonBody: {}
>> macaca-ios.js:335:10 [master] pid:12967 Stoping iOS driver...
>> xctest-client.js:267:14 [master] pid:12967 killing deviceLogProc pid: 13267
>> xctest-client.js:272:14 [master] pid:12967 killing runnerProc pid: 13268
>> macaca-ios.js:359:10 [master] pid:12967 iOS driver cleaned up.
>> session.js:80:12 [master] pid:12967 Delete session, sessionId: bcbcee4f-ccc9-417d-aee9-21b68d03adb7
`

**Comment by xudafeng** [comment]
getProperty('isVisible')
