### ISSUE TITLE
npm install macaca-android -g 出错，请麻烦解答

### ISSUE THREAD

**Issue by john-hoe** [alibaba/macaca#418]
Macaca Version:
1.1.21

macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: E:\NodeJs\node.exe
  node version: v6.9.4

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `E:\JAVA\JDK1.8`
  ANDROID_HOME is set to `E:\Android-SDK`
  Platforms is set to `E:\Android-SDK\platforms\android-23`
  Android tools is set to `E:\Android-SDK\tools\android.bat`
  ADB tool is set to `E:\Android-SDK\platform-tools\adb.exe`
  ANT_HOME is set to `E:\ANT\apache-ant-1.9.8`

  Installed driver list:

  electron: 1.1.4

Platform:
windows 10 64bit

command
npm install macaca-android -g

npm-debug.log
[http://pan.baidu.com/s/1dEM3kHz](url)

error info
JAVA_HOME is set to E:\JAVA\JDK1.8
{ Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/d', '/c', 'E:\\ANT\\apache-ant-1.9.8\\bin\\ant', 'debug' ] }
C:\Users\hejoh\AppData\Roaming\npm\node_modules\macaca-android\node_modules\android-unicode\script\build.js:15
    throw e;
    ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
C:\Users\hejoh\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "E:\\NodeJs\\node.exe" "E:\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "install" "macaca-android" "-g"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! android-unicode@1.0.9 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the android-unicode@1.0.9 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log
npm ERR! code 1

**Comment by xudafeng** [comment]
检查ant

**Comment by mijiawei** [comment]
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "macaca-android" "-g"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! android-unicode@1.0.11 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the android-unicode@1.0.11 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/micky/npm-debug.log
npm ERR! code 1

```
