### ISSUE TITLE
Not seeing highlight box on some screen

### ISSUE THREAD

**Issue by ronadinihari** [alibaba/macaca#422]
* **Macaca Version**: 1.1.21

* **Macaca Doctor Logs**: 

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/bin/node
  node version: v4.2.6

  Android checklist:

  JAVA version get not found
  JAVA_HOME is set to `/usr/lib/jvm/java-8-openjdk-amd64`
  ANDROID_HOME is set to `/home/rona/Android/Sdk/`
  Platforms is set to `/home/rona/Android/Sdk/platforms/android-24`
  Android tools is set to `/home/rona/Android/Sdk/tools/android`
  ADB tool is set to `/home/rona/Android/Sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.15
  chrome: 1.0.5

* **Operate System**: Ubuntu 16.04

* **Programming Language**: Javascript

Hello,

I have a problem recording test with my application. Interstitial is intractable and also some of widgets. But on some other widgets/screen, it is not. Please have a look at the screen-shots. 

Interstitial are well recognized. Buttons in first/main screen are well recognized. But the input, textarea, and button in form in the next screen after, are not.

How can I fix this so I can continue recording the test case?

So far it's better than others. Thank you teams.

Regards,
Rona

![todospell_00_spec_emulator_5554_1](https://cloud.githubusercontent.com/assets/1159021/21853559/3268352a-d84a-11e6-8204-b0f499e4e9d8.png)
![todospell_00_spec_emulator_5554_2](https://cloud.githubusercontent.com/assets/1159021/21853558/3266e85a-d84a-11e6-9494-bd74012aff43.png)
![todospell_00_spec_emulator_5554_3](https://cloud.githubusercontent.com/assets/1159021/21853560/326c0c9a-d84a-11e6-9996-940f266840e0.png)

**Comment by ronadinihari** [comment]
Sorry, I didn't checked it frequent enough.

I think I should add that it's Ionic framework. Last time I tried to look into it, it looks like something like iframe case. I used [https://creator.ionic.io/app/dashboard/projects](https://creator.ionic.io/app/dashboard/projects) to build the interface. Then I add the ads with Phonegap/Cordova plugin.

**Comment by xudafeng** [comment]
update new version
