### ISSUE TITLE
The command 'deleteAllCookies()' throws 404 error

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#423]
I would like to erase login data on each run. For this purpose I would like to delete all cookies after test execution. I found there is a method 'deleteAllCookies()' inside commands.js file. But this throws 404 error.Please help

**Comment by xudafeng** [comment]
https://github.com/macacajs/webdriver-server/pull/45

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-electron/pull/20

**Comment by xudafeng** [comment]
fixed
