### ISSUE TITLE
Windows7 执行官方示例出错 命令：macaca run --verbose

### ISSUE THREAD

**Issue by scheibe1874** [alibaba/macaca#424]
Macaca Version:
1.1.21

macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: D:\Program Files\nodejs\node.exe
  node version: v6.9.4

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_112`
  ANDROID_HOME is set to `D:\Android\sdk`
  Platforms is set to `D:\Android\sdk\platforms\android-24`
  Android tools is set to `D:\Android\sdk\tools\android.bat`
  ADB tool is set to `D:\Android\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `C:\apache-ant-1.10.0`

  Installed driver list:

  android: 1.1.15
  electron: 1.1.4

Platform:
windows 7 64bit

command
macaca run --verbose

error info
>> index.js:17:12 [master] pid:820 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '***.**.**.**',
  host: 'dell-PC',
  loaded_time: '2017-01-13 15:01:38' }
>> middlewares.js:17:10 [master] pid:820 base middlewares attached
>> router.js:127:10 [master] pid:820 router set
>> webdriver sdk launched
[ 'D:\\GitProject\\mobile-app-sample-nodejs\\node_modules\\.bin\\mocha',
  'macaca-test',
  '--colors',
  '--verbose' ]
>> D:\GitProject\mobile-app-sample-nodejs\node_modules\.bin\mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

>> Test completed!

Many Thanks！！！

**Comment by xudafeng** [comment]
@scheibe1874 到社区看windows合集

**Comment by SmallBlackboard** [comment]
@scheibe1874 你的问题解决了吗？？

**Comment by scheibe1874** [comment]
@SmallBlackboard 没有解决。。
