### ISSUE TITLE
官网-文档-上手指南页文档说明有错别字....

### ISSUE THREAD

**Issue by liang171** [alibaba/macaca#425]
官网-文档-上手指南 原文：

准备移动端App

iOS: 支持 .app 格式的包。
Android: 支持 .apk 格式的包。
Desktop: 支持任意浏览器网页。
桌面客户单软件目前暂未支持

桌面客户“单”？是客户端吧

**Comment by xudafeng** [comment]
https://github.com/macacajs/macacajs.github.io/commit/516629adefb32859e6bd88dd5b10a0a6f8355a91
