### ISSUE TITLE
Start app-inspector, failed with: app-inspector:66:44 [master] pid:10034 undefined

### ISSUE THREAD

**Issue by debbie-qin** [alibaba/macaca#426]
Macaca version:   1.1.21
app-inspector:  1.2.18 
When I start app-inspector: app-inspector -u bb1f6c5abfef652ef6b087f434acb8de105b90d4, if failed with the log:
>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.41
>> app-inspector:66:44 [master] pid:10034 undefined
(node:10034) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:10034 undefined
(node:10034) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Could you help me ?

**Comment by baozhida** [comment]
xcode 8.2  iPhone6  9.3.1

macaca@1.1.21

app-inspector@1.2.18


MACdeMacBook-Pro:25.0.2 MAC$ app-inspector -u 5f90993b9572a8ffcf37da9c947573ea17ddd2e0
>> port: 5678 was occupied, changed port: 50349
>> xctest-client.js:58:14 [master] pid:8498 project path not found
>> app-inspector:66:44 [master] pid:8498 Error: >> xctest-client.js:58:14 [master] pid:8498 project path not found
    at Logger.error (/usr/local/lib/node_modules/app-inspector/node_modules/.1.0.6@xlogger/lib/xlogger.js:169:9)
    at XCTest.checkProjectPath (/usr/local/lib/node_modules/app-inspector/node_modules/.1.0.29@xctest-client/lib/xctest-client.js:58:14)
    at XCTest.init (/usr/local/lib/node_modules/app-inspector/node_modules/.1.0.29@xctest-client/lib/xctest-client.js:51:10)
    at XCTest (/usr/local/lib/node_modules/app-inspector/node_modules/.1.0.29@xctest-client/lib/xctest-client.js:39:10)
    at Object.exports.initDevice (/usr/local/lib/node_modules/app-inspector/lib/ios.js:90:12)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:54:5
    at co (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:118:63)
**(node:8498) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): **Error: >> app-inspector:66:44 [master] pid:8498 Error: >> xctest-client.js:58:14 [master] pid:8498 project path not found
    at Logger.error (/usr/local/lib/node_modules/app-inspector/node_modules/.1.0.6@xlogger/lib/xlogger.js:169:9)
    at XCTest.checkProjectPath (/usr/local/lib/node_modules/app-inspector/node_modules/.1.0.29@xctest-client/lib/xctest-client.js:58:14)
    at XCTest.init (/usr/local/lib/node_modules/app-inspector/node_modules/.1.0.29@xctest-client/lib/xctest-client.js:51:10)
    at XCTest (/usr/local/lib/node_modules/app-inspector/node_modules/.1.0.29@xctest-client/lib/xctest-client.js:39:10)
    at Object.exports.initDevice (/usr/local/lib/node_modules/app-inspector/lib/ios.js:90:12)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:65:19)
    at /usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:54:5
    at co (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:50:10)
    at toPromise (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:118:63)

**Comment by tenjinMech** [comment]
I am encountering the same issue . the app-inspector initially worked for a while and than i am unable to start it up since i am getting the below error 

Application versions 
macaca@1.1.21
app-inspector@1.2.18

Steps to reproduce - 
1. Run the command  -> app-inspector  -u 3CA41691-B7D1-4833-8BCF-590EE86FB813
Expected Result : 
An ios simulator with that UDID will get launched
Actual Result (log below) :
>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.41
>> app-inspector:66:44 [master] pid:20179 undefined
(node:20179) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:20179 undefined
(node:20179) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Archer456** [comment]
请参考
https://testerhome.com/topics/6507

**Comment by tenjinMech** [comment]
Thank you for that link @Archer456  , but that was not really helpful .
The cause of the error as of now on iOS was due to a different simulator running in comparison to the simulator that i attempted to launch via app-inspector  .

**Comment by vivekguptaraw** [comment]
xctest-client start with port: 8900
WebDriverAgent version: 1.0.41
app-inspector:66:44 [master] pid:20179 undefined
(node:20179) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:20179 undefined
(node:20179) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

SAME ERROR

**Comment by Sandu1213** [comment]
>> xctest-client.js:181:14 [master] pid:20000 xctest client exit with code: 65, signal: null
>> xctest-client.js:145:16 [master] pid:20000 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:255:14 [master] pid:20000 Fail to start xctest: undefined
>> app-inspector:66:44 [master] pid:20000 undefined

The same question,help

**Comment by Sandu1213** [comment]
I've resolved the issue using the following steps:

1. Open WebDriverAgent in Xcode
2.Navigate WebDriverAgentRunner -> Build Phase
3.Add libraries Peertalk.framework and RoutingHTTPServer.framework https://gyazo.com/288bbd8c24a77e844d9ea630515f46a3
4.Rebuild project
Notes: WebDriverAgentRunner -> General -> Testing -> Target Application should be set 'None'

**Comment by TheChell** [comment]
Thank you for the detailed steps, @Sandu1213, but this did not resolve the error for me.

**Comment by lixiaoyudakeke** [comment]
I have the same problem，did you have a solution?

**Comment by TheChell** [comment]
Nah, I gave up. I am now using the Appium.app inspector with a bit of a workaround since it's not compatible with appium version 1.6 and above.

http://stackoverflow.com/questions/39484988/cant-use-inspector-with-appium-1-6-0

**Comment by laiyuncong8404** [comment]
I got the same isuue. Pls help me out.
`
>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.42
>> app-inspector:66:44 [master] pid:2648 undefined
(node:2648) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: >> app-inspector:66:44 [master] pid:2648 undefined
(node:2648) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I have tried this solution, it didn't work for me.

> 1.Open WebDriverAgent in Xcode
2.Navigate WebDriverAgentRunner -> Build Phase
3.Add libraries Peertalk.framework and RoutingHTTPServer.framework https://gyazo.com/288bbd8c24a77e844d9ea630515f46a3
4.Rebuild project
Notes: WebDriverAgentRunner -> General -> Testing -> Target Application should be set 'None'

OSX:10.12.3
xCode:8.2
app-inspector:1.2.20

**Comment by sandeshaAbeykoon** [comment]
I am still getting this issue. Has anyone found a solution ?

**Comment by xudafeng** [comment]
https://travis-ci.org/macacajs/app-inspector/builds 

@sandeshaAbeykoon please check your environment

**Comment by nguyenthinam** [comment]
I got the same issue, the following steps solved my problem
1. Uninstall all things with command 
`npm uninstall -g  <name>`

2. Follow the steps at https://macacajs.github.io/app-inspector/ to re-install 
```
npm install macaca-cli -g
macaca doctor
npm install app-inspector -g
```
3. Open WebDriverAgent in Xcode
4. Navigate WebDriverAgentRunner -> XCUICoordinate.h
Then, comment out method because of a compiler error there:
`//- (void)pressForDuration:(double)arg1 thenDragToCoordinate:(id)arg2;`
5. Rebuild Project, Then run on any iOS Simulator.
6. Run app-inspector from cli
`app-inspector -u YOUR-DEVICE-ID
`

Hope it helps!

---------
macaca ver:1.2.2
app-inspector ver:1.2.23
Xcode Version 8.0

**Comment by richashri87** [comment]
@nguyenthinam I opened my XCUICoordinate.h but could not find the method you mentioned.

<img width="886" alt="screen shot 2017-04-18 at 12 16 55 pm" src="https://cloud.githubusercontent.com/assets/13135890/25126628/87c0d0a2-2450-11e7-9bb3-e3aee73ee658.png">

**Comment by narendra-chandratre** [comment]
Any fix this issue with strong solution?
