### ISSUE TITLE
Is there a way to dismiss alert in desktop test?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#427]

**Comment by xudafeng** [comment]
chromedriver, 

Try It Out

**Comment by mpreethi90** [comment]
I use to execute test in electron. Is there any way?

**Comment by xudafeng** [comment]
@mpreethi90 `window.alert = function() {}`

**Comment by xudafeng** [comment]
temporary fix

**Comment by mpreethi90** [comment]
@xudafeng , How do I execute this window.alert function inbetween the test flow? webdriver does not seem to recognise and throw error while I use window.alert function

**Comment by xudafeng** [comment]
execute

**Comment by mpreethi90** [comment]
Yes, I tried that already. But end up with error message that says 
`"Send Bad HTTP Respone to Client: {"sessionId":"18232d63-f833-480a-b22e-3a781afc23c5","status":21,"value":{"message":"Wait for message from the runner TIMEOUT."}}"`


Here is my code-

`.waitForElementByCssSelector('.s-box .red', 5000, 1000)
			.click()
			.execute('window.alert = function() {}')`

and here where I get alert in electron -
![screen shot 2017-01-16 at 1 21 44 pm](https://cloud.githubusercontent.com/assets/20960378/21971803/01f4d166-dbef-11e6-9737-dd8cb38b2650.png)

**Comment by sachinGirish** [comment]
.execute($('.css_selector').click()) 

It works in chrome driver.

**Comment by xudafeng** [comment]
https://github.com/electron/electron/issues/5577

**Comment by xudafeng** [comment]
look at the sample, hope to help you!

https://github.com/macaca-sample/sample-nodejs/blob/master/macaca-test/desktop-browser-sample.test.js

**Comment by xudafeng** [comment]
@dfguo
