### ISSUE TITLE
Is mouse hover function capable through macaca in desktop test in electron?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#431]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by dharmamoolya** [comment]
not able to find the direct way of doing mouseover but with chrome browser, you can use **execute** 

`.execute("$('classname').mouseover()")`

**Comment by xudafeng** [comment]
@dharmamoolya yeah

@mpreethi90 

https://github.com/macaca-sample/sample-nodejs/blob/master/macaca-test/desktop-browser-sample.test.js

**Comment by xudafeng** [comment]
@dfguo

**Comment by vera3224** [comment]
@xudafeng mouseover在app端可用吗？Java 语言
