### ISSUE TITLE
Macaca Mac系统下Android模拟器/真机运行Demo均报错The environment you requested was unavailable

### ISSUE THREAD

**Issue by scheibe1874** [alibaba/macaca#433]
尝试了各种方法均没有解决问题。

如下报错：
Error: [init({"platformName":"Android","autoAcceptAlerts":false,"app":"https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk"})] The environment you requested was unavailable.

* **Macaca Version**:1.1.21

* **Macaca Doctor Logs**:
 macaca-doctor version: 1.0.28

  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v6.9.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhangbo/Desktop/jenkens/android-sdk-macosx`
  Platforms is set to `/Users/zhangbo/Desktop/jenkens/android-sdk-macosx/platforms/android-24`
  Android tools is set to `/Users/zhangbo/Desktop/jenkens/android-sdk-macosx/tools/android`
  ADB tool is set to `/Users/zhangbo/Desktop/jenkens/android-sdk-macosx/platform-tools/adb`

  Installed driver list:

  android: 1.1.16
  chrome: 1.0.5
  electron: 1.1.4
  ios: 1.0.53

* **Operate System**:Mac

* **Programming Language**:CHN

Command：macaca run --verbose

ErrLog：
1) macaca mobile sample "before all" hook:
     Error: [init({"platformName":"Android","autoAcceptAlerts":false,"app":"https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at .<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

Many Thanks!

**Comment by scheibe1874** [comment]
macaca run --verbose
报错如上所述，看到了很多人反应一样的问题，没有找到解决方案，自己尝试了各种都没有得到解决

**Comment by xudafeng** [comment]
@scheibe1874 https://github.com/macaca-sample/macaca-ci-sample-android-travis 对照一下travis 的log，看环境是什么问题

**Comment by dharmamoolya** [comment]
We got this issue when we don't connect device/anroid emulator properly or if we give device name wrong for iOS will get this kind of error.

If you try to run remote without having proper environment setup, even that time this issue will arise. @scheibe1874 If you share the CONFIG FILE, we may give more suggestions

**Comment by chujian** [comment]
到底什么环境设置呀，全部按照官方教程走了一遍，macaca doctor也都正确，但就是和楼主一样的错误，到底什么问题呢？

**Comment by Archer456** [comment]
@chujian    https://testerhome.com/topics/6507   请参考配置

**Comment by chujian** [comment]
@Archer456 我刚才在家里的电脑也装了一遍,也按照您提供的教程走了一遍,还是一样的错误,真的不知道哪里错了,

**Comment by CodeToSurvive1** [comment]
日志是全部的还是部分的？

**Comment by chujian** [comment]
macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.1.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/xxx/Library/Android/sdk`
  Platforms is set to `/Users/xxx/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/xxx/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/xxx/Library/Android/sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.19
  chrome: 1.0.5
  electron: 1.1.5
  ios: 1.0.53



macaca run --verbose
>> index.js:17:12 [master] pid:4008 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.1.125',
  host: 'chujiandeMac-mini.local',
  loaded_time: '2017-02-22 19:38:05' }
>> middlewares.js:17:10 [master] pid:4008 base middlewares attached
>> router.js:127:10 [master] pid:4008 router set
>> webdriver sdk launched
[ '/Volumes/HHD/Project/desktop-browser-sample-nodejs/node_modules/.bin/mocha',
  'macaca-test',
  '--colors',
  '--verbose' ]
>>

>>

>>   macaca desktop sample

>>     1) "before all" hook

>>     2) "after all" hook

>>

>>

>>   0 passing (277ms)

>>   2 failing

>>

>>   1) macaca desktop sample "before all" hook:
     Error: [init({"platformName":"desktop","browserName":"electron"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)


>>   2) macaca desktop sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at .<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)


>>


>> Test completed!

**Comment by CodeToSurvive1** [comment]
```

macaca run -d macaca-test/desktop-browser-sample-nodejs.test.js --verbose
>> index.js:17:12 [master] pid:1178 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.31.164',
  host: 'mac.local',
  loaded_time: '2017-02-22 19:45:23' }
>> middlewares.js:17:10 [master] pid:1178 base middlewares attached
>> router.js:127:10 [master] pid:1178 router set
>> webdriver sdk launched
[ '/Users/mac/software/github/macacajs/desktop-browser-sample-nodejs/node_modules/.bin/mocha',
  'macaca-test/desktop-browser-sample-nodejs.test.js',
  '--colors',
  '--verbose' ]
>> 

  macaca desktop sample

>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"desktop","browserName":"electron","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:1178 Creating session, sessionId: 5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3.
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"{\"platformName\":\"desktop\",\"browserName\":\"electron\",\"version\":\"\",\"javascriptEnabled\":true,\"platform\":\"ANY\",\"show\":true}"}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/window/current/maximize, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/window/current/size, jsonBody: {"width":1280,"height":800}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/url, jsonBody: {"url":"https://www.baidu.com"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>>     ✓ #0 should go into macaca (4850ms)

>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element, jsonBody: {"using":"id","value":"kw"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"{\"ELEMENT\":1000}"}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element/1000/value, jsonBody: {"value":["macaca"]}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element, jsonBody: {"using":"id","value":"su"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"{\"ELEMENT\":1001}"}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element/1001/click, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/source, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"\"<html><head>\\n    \\n    <meta http-equiv=\\\"content-type\\\" content=\\\"text/html;charset=utf-8\\\"><style data-for=\\\"result\\\" id=\\\"css_result\\\" type=\\\"text/css\\\">body{color:#333;background:#fff;padding:6px 0 0;margin:0;position:relative;min-width:900px}body,th,td,.p1,.p2{font-family:arial}p,form,ol,ul,li,dl,dt,dd,h3{margin:0;padding:0;list-style:none}input{padding-top:0;padding-bottom:0;-moz-box-si..."}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/elements, jsonBody: {"using":"css selector","value":"#head > div.head_wrapper"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"[{\"ELEMENT\":1002}]"}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/elements, jsonBody: {"using":"xpath","value":"//*[@id=\"kw\"]"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"[{\"ELEMENT\":1003}]"}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element/1003/value, jsonBody: {"value":[" elementByXPath"]}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element, jsonBody: {"using":"id","value":"su"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"{\"ELEMENT\":1004}"}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element/1004/click, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/screenshot, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAACgAAAAVeCAYAAAC9mGK2AAAgAElEQVR4nOzdeZgU5bn+8e9b1cvsDIvDIpsDsiMK7oA7QSUu0XNy1CRHo8bEiBo16tHkGE2uaCQeYxIxejSY/EyMiUrUEwUNMS6sYlC2YV8HBhgGZpilp7eq9/dHM800s7JDcn+uay6YrqXf6q7u6a6663mMtdYiIiIiIiIiIiIiIiIiIiIiIiIiIscU50gPQERERERERERERERERERERERERET2nQKAIiIiIiIiIiIiIiIiIiIiIiIiIscgBQBFREREREREREREREREREREREREjkEKAIqIiIiIiIiIiIiIiIiIiIiIiIgcgxQAFBERERERERERERERERERERERETkGKQAo..."}
>>     ✓ #1 should works with macaca (18118ms)

>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/url, jsonBody: {"url":"https://www.baidu.com"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>>     ✓ #2 should go into web (4418ms)

>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element, jsonBody: {"using":"id","value":"kw"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"{\"ELEMENT\":1005}"}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element/1005/value, jsonBody: {"value":["Macaca"]}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element, jsonBody: {"using":"id","value":"su"}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"{\"ELEMENT\":1006}"}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/element/1006/click, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/source, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"\"<html><head>\\n    \\n    <meta http-equiv=\\\"content-type\\\" content=\\\"text/html;charset=utf-8\\\"><style data-for=\\\"result\\\" id=\\\"css_result\\\" type=\\\"text/css\\\">body{color:#333;background:#fff;padding:6px 0 0;margin:0;position:relative;min-width:900px}body,th,td,.p1,.p2{font-family:arial}p,form,ol,ul,li,dl,dt,dd,h3{margin:0;padding:0;list-style:none}input{padding-top:0;padding-bottom:0;-moz-box-si..."}
>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3/screenshot, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAACgAAAAVeCAYAAAC9mGK2AAAgAElEQVR4nOzdd3Rd1Z33//c+51Z1N7ngXnDHYDo21XQYQiCNkCckhEnIQCBh8iMTJk/Ck1nDAEmIJxNSBgJhZUIytBBCTYBQjAsGgQtyr7JcZNmq9+qWc87+/XGla8mqNq7wea2lZemec/bZt+jK2vqc79dYay0iIiIiIiIiIiIiIiIiIiIiIiIiclRxDvcERERERERERERERERERERERERERGTfKQAoIiIiIiIiIiIiIiIiIiIiIiIichRSAFBERERERERERERERERERERERETkKKQAoIiIiIiIiIiIiIiIiIiIiIiIiMhRSAFAERERERERERERERERERERERERkaOQAoAi..."}
>>     ✓ #3 should works with web (9829ms)

>> responseHandler.js:11:12 [master] pid:1178 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3, jsonBody: {}
>> session.js:80:12 [master] pid:1178 Delete session, sessionId: 5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3
>> responseHandler.js:47:14 [master] pid:1178 Send HTTP Respone to Client: {"sessionId":"5d1be6df-ac7a-4e27-bb52-a2ad43ff64f3","status":0}
>> 


>>   4 passing (41s)


>> Test completed!


```

完整的日志，我刚下载下来跑了下 对比下呢？

**Comment by chujian** [comment]
macaca desktop sample

这行前面都一样的,后面就报错了,实在不知道哪里不对,唉

**Comment by CodeToSurvive1** [comment]
感觉macaca-electron有问题呢 把这个重新安装试试呢

**Comment by chujian** [comment]
卸载重装,重装几次,故障依旧. :(

**Comment by CodeToSurvive1** [comment]
跑的例子的脚本没改过对吧

**Comment by chujian** [comment]
在无奈的情况下，我执行了su - ，然后我再执行测试，它又可以执行了，难道一定要root用户下？？

**Comment by CodeToSurvive1** [comment]
你装macaca的时候用root装的吧  不要用管理员权限装

**Comment by chujian** [comment]
我装的时候都是普通用户的，初步怀疑是不是node npm之类的之前在root下装了，不管怎么样，问题找到就好了，非常感谢多次回复。

**Comment by CodeToSurvive1** [comment]
那就是这个原因了

**Comment by Archer456** [comment]
@CodeToSurvive1  @chujian      不要依赖用root账号     ubuntu和mac下  用tar包解压方式+配置环境变量方式安装 比直接用dmg方式安装会免去权限设置问题。    你就用普通账号 一直弄    不要一会root一会普通账号 。
