### ISSUE TITLE
部署Reliable Slave报错

### ISSUE THREAD

**Issue by wk1281472252** [alibaba/macaca#435]
![image](https://cloud.githubusercontent.com/assets/20434131/22180986/841df5d8-e0bc-11e6-99a7-99db6397f61c.png)
单点模式Reliable Slave 进行部署并挂载报错
reliable server -m 192.168.1.29:8080 --verbose

**Comment by CodeToSurvive1** [comment]
https://github.com/alibaba/reliable/issues
