### ISSUE TITLE
请问用 Docker 部署的 reliable 如何加载自己的测试用例？另官网 docker 教程有3处需要修改。

### ISSUE THREAD

**Issue by Erwin11** [alibaba/macaca#436]
### 个人机器环境基本信息 
* **Docker**
Docker version 1.13.0, build 49bf474
Docker-compose version 1.10.0, build 4bd6f1a

* **Macaca Version**:  1.1.21
* **Macaca Doctor Logs**:
Installed driver list:

  android: 1.1.16
  chrome: 1.0.5
  electron: 1.1.4
  ios: 1.0.53

* **Operate System**:
Macbook pro 2013 later
Darwin MacBook-Pro.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

<hr>
Hi all~  
<i>我有2个问题和1个建议。</i>  

### 问题2：我是mac本地安装 reliable, 这个和部署到云服务器上有区别吗？

# 建议：
官网 reliable 的安装教程实在是太简单了，对新手不友好。😂
它没告诉你的：Docker 安装是个坑，镜像源速度慢😂😂，需要换阿里云加速 / DaoCloud / 华中科大 的加速镜像源。

## 以下是我的 Docker 安装步骤：
1. 去 [https://www.docker.com](https://www.docker.com/products/docker#/mac) 下载dmg安装包，安装。 
2. 开启[阿里云加速服务](https://cr.console.aliyun.com/#/accelerator)，首次登录这里，需要设置密码。 
3. 打开 Docker，选择“Preference” 设置，在Tab栏的“Daemon”页面，Basic选项中，Registry mirrors标题下面添加：
阿里云加速： <i>https://你的配置信息.mirror.aliyuncs.com</i> 
华中科大镜像加速：<i>https://docker.mirrors.ustc.edu.cn/</i>

至此，你输入```docker info```就会看到有镜像信息被添加进去了。

## 就算你 Docker 安装成功，reliable-docker-base 也不一定能顺利build成镜像😂
它没告诉你的：Dockerfile 文件里面的 libsodium 和 zeromq 文件网址无法下载。

#### 解决方案：在 reliable-docker-base 目录，打开Dockerfile文件，
替换libsodium的网址
把“http://www.mirrorservice.org/sites/distfiles.macports.org/libsodium/1.0.3_1/”
替换为：
“https://distfiles.macports.org/libsodium/1.0.3_1/”

zeromq也被墙了，替换macports源。 
"http://pkgs.fedoraproject.org/repo/pkgs/zeromq/zeromq-$ZEROMQ_VERSION.tar.gz"
替换为：
"https://distfiles.macports.org/zmq/zeromq-$ZEROMQ_VERSION.tar.gz"

至此，你能顺利安装 reliable-docker-base 镜像 和 reliable-master 镜像了。

### BTW,设置成中文和邮件配置 
在 git clone reliable-master 源码并进入 cd reliable-master之后，

设置中文：进入 reliable-master/common目录，把config.js里面的 locale:en-US 改成 locale:zh-CN,
这样后面进入界面就是中文了。想必项目组是为了国际化，默认是英文。

邮件设置：拿163邮箱举例，在config.js里面，mail里面，host的值设为：‘smtp.163.com’,auth下面的user和pass的值改为你的邮箱名和密码即可。

## Docker-compose 输入make start失败😂
在 docker-compose 目录下，编辑 docker-compose.yml，reliable-master的配置项 restart:"UNLESS-STOP" 没有了，需要替换成 restart:"unless-stopped"。 
官方文档来源：（https://docs.docker.com/engine/reference/run/#restart-policies-restart）

至此，你输入make start就能顺利安装了。然后打开docker的GUI可视化界面——kitematic,在左侧选择reliable master，点击右边的“web preview” 旁的按钮就能看到这个reliable 了。 yeah!

**Comment by CodeToSurvive1** [comment]
https://github.com/alibaba/reliable/issues

**Comment by xudafeng** [comment]
@Erwin11 欢迎pull request

**Comment by litingjun2015** [comment]
请问 https://macacajs.github.io/zh/run-with-docker
macaca-android-docker
 
有没有进一步的说明，不会玩
