### ISSUE TITLE
Android测试时输入较长中文字符或中文数字混合时乱码，如图

### ISSUE THREAD

**Issue by adfghzhang** [alibaba/macaca#439]
* **Macaca Version**:
  1.1.21
* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: D:\Program Files\nodejs\node.exe
  node version: v6.9.4

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_112`
  ANDROID_HOME is set to `D:\android-sdk`
  Platforms is set to `D:\android-sdk\platforms\android-24`
  Android tools is set to `D:\android-sdk\tools\android.bat`
  ADB tool is set to `D:\android-sdk\platform-tools\adb.exe`
  ANT_HOME is set to `D:\apache-ant-1.9.7`

  Installed driver list:

  android: 1.1.16
  electron: 1.1.4
* **Operate System**:
  Windows 7
* **Programming Language**:
  Java

  输入：重庆市小雨点小额贷款有限公司 

![qq 20170203101952](https://cloud.githubusercontent.com/assets/20984179/22582525/64817cbc-ea22-11e6-90cb-ec5b5ae2c832.png)

  输入：重庆市渝北区嘉州路80号

![qq 20170203102018](https://cloud.githubusercontent.com/assets/20984179/22582533/70941d5c-ea22-11e6-9050-5be51f77a1a4.png)

**Comment by xudafeng** [comment]
看样子是 utf7输入法的bug

**Comment by xudafeng** [comment]
source code https://github.com/macacajs/android-unicode

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5327

**Comment by zhuyali** [comment]
https://testerhome.com/topics/7549

**Comment by xudafeng** [comment]
https://github.com/macacajs/android-unicode/pull/6

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/pull/36

**Comment by pepsicoffee** [comment]
@zhuyali ：第三方模拟器支持中文输入么？我使用夜神模拟器一直不能输入中文。。。
