### ISSUE TITLE
手势密码解锁问题

### ISSUE THREAD

**Issue by ftvbftvbq** [alibaba/macaca#44]
Thanks for wanting to report an issue you've found in Macaca. Please fill in the template below by replacing the html comments with an appropriate answer.

Macaca Version: usually output of `macaca -v`
Macaca Doctor: usually output of `macaca doctor`
Platform: either `uname -a` output, or if Windows, version and 32 or 64-bit.

Thank you!
-->

* **Macaca Version**:
1.0.24
* **Macaca Doctor**: 正常
* **Platform**:Mac

ios上的手势密码，要求四点链接，整个控件为一个整体的控件，点击任何一个点，都无法获得坐标，只有点击上去才能触发成功，然后才能操作四点链接，该类问题，如何解决？谢谢！

**Comment by codeskyblue** [comment]
锁屏的时候 xctest都跑不起来，怎么解锁呀

**Comment by xudafeng** [comment]
xctest 是没法解锁的
