### ISSUE TITLE
大婶，python的sit_packages下macaca库方法中没有elements_by_xxx的定位方法

### ISSUE THREAD

**Issue by linlin547** [alibaba/macaca#440]
我按照官方的安装教程安装的，但是运行官方python例子时，提示elements_by_xxx的类似方法没有，我搜索python的sit_packages下macaca库中所有文件，发现并没有这些方法，我应该怎么解决呢？看官方给出的python对应api是有的，但是安装后的库中确没有，能给一些建议，我应该怎么处理吗？

**Comment by zenzhu** [comment]
看一下报错的截图，方法在源码找不到是因为方法名是动态写的，例如 elements_by_(id/name)。

**Comment by linlin547** [comment]
没有这样的方法，所以改成wait_for_element('name', 'xx')的形式，可以使用
