### ISSUE TITLE
macaca-ios  对ios10.2.1 的支持问题

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#441]
vipdev:~ macaca$ macaca -v

  1.1.21

vipdev:~ macaca$ macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /Users/macaca/nodejs/bin/node
  node version: v6.9.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2345.1.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/macaca/android-sdk-macosx`
  Platforms is set to `/Users/macaca/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/macaca/android-sdk-macosx/tools/android`
  ADB tool is set to `/Users/macaca/android-sdk-macosx/platform-tools/adb`

  Installed driver list:

  android: 1.1.16
  electron: 1.1.4
  ios: 1.0.53

年前已经调试好的一台imac环境脚本 良好的跑了某一用例  年中手机系统升级到ios10.2.1后,
年后回来 反复调试折腾 最后确认是macaca server 对 ios10.2.1的支持有问题.

验证过程如下:
同一imac机器 同一脚本 
1 换同事另一部ios10.2 的手机  脚本就顺利跑 
2 换升级后的ios 10.2.1的手机  脚本  macaca server端 就开始报错,具体报错位置是在  覆盖安装这里.
如果手机已安装该app 脚本设置的参数 REUSE=3 覆盖安装 执行uninstall 卸载掉该步没问题 但重新安装该app会报错,server日志 会提示 该app没安装,但不会自动正常自动往下安装该app.

![image](https://cloud.githubusercontent.com/assets/18392901/22616625/7a74f980-eaeb-11e6-9245-bdb74394954d.png)

经多次试验,最终确认是  对ios10.2.1 的支持问题  请帮助排查该问题

>> macaca-ios.js:253:12 [master] pid:2913 App 'com.hszq.HSSecurities' is not installed.
>> macaca-ios.js:258:14 [master] pid:2913 2017-02-04 14:52:40.368 ios-deploy[2930:614168] [ !! ] Error 0xe8008015: A valid provisioning profile for this executable was not found. AMDeviceSecureInstallApplication(0, device, url, options, install_callback, 0)

有意思的是看到了 该行日志  应该是ios-delopy 没有正常去把app推送安装到手机上  好像是什么ios-deploy  profile for this executable was not found.

**Comment by CodeToSurvive1** [comment]
@Archer456 看截图是reuse传的是1吧  3的话只需要传bundle id就可以  怎么能复现下？

**Comment by zenzhu** [comment]
reuse 3 应该不是覆盖安装，1 是卸载再安装，2 是覆盖安装，3 是只要检测到有该 bundle id 存在，就不用重装了。
