### ISSUE TITLE
android真机执行mobile-app-sample-nodejs例子，执行到#5时报错Send Error Respone to Client: NoSuchDriver: no such session

### ISSUE THREAD

**Issue by ericchen82** [alibaba/macaca#448]
* **Macaca Version**:
1.1.21
* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.5.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/opt/android-sdk`
  Platforms is set to `/usr/local/opt/android-sdk/platforms/android-23`
  Android tools is set to `/usr/local/opt/android-sdk/tools/android`
  ADB tool is set to `/usr/local/opt/android-sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.16
  chrome: 1.0.5
  electron: 1.1.5
  ios: 1.0.53
* **Operate System**:
mac OS
* **Programming Language**:
nodejs

日志如下：
>>     1) #5 should go into webview

>>     2) #6 should go into test

>>     3) #7 should works with web

>>     4) #8 should logout success

>> chromedriver bin path: /usr/local/lib/node_modules/macaca-android/node_modules/.1.0.30@macaca-chromedriver/exec/chromedriver
>> Starting ChromeDriver 2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:52:14 [master] pid:74653 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body:
>> proxy.js:58:16 [master] pid:74653 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.12.3\"}}}"
>> proxy.js:52:14 [master] pid:74653 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.github.android_app_bootstrap","androidUseRunningApp":true,"androidDeviceSerial":"45AA5SEMBI5TWGRW"}}}
>> proxy.js:58:16 [master] pid:74653 Got response with status 200: {"sessionId":"1f566965bb4f4920ddacd4ee9e1cbffd","status":13,"value":{"message":"unknown error: Chrome version must be >= 53.0.2785.0\n  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f...
>> chromedriver ready with: {"sessionId":null,"status":13,"value":{"message":"unknown error: Chrome version must be >= 53.0.2785.0\n  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.3 x86_64)"}}
>> proxy.js:52:14 [master] pid:74653 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/1f566965bb4f4920ddacd4ee9e1cbffd/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:74653 Got response with status 200: {"sessionId":"1f566965bb4f4920ddacd4ee9e1cbffd","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X...
>> responseHandler.js:54:12 [master] pid:74653 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.3 x86_64)
>> responseHandler.js:60:14 [master] pid:74653 NoSuchDriver: no such session
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.3 x86_64)
    at Object._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-android/lib/helper.js:72:11)
    at Android.getWebviews (/usr/local/lib/node_modules/macaca-android/lib/macaca-android.js:288:18)
    at Android.getWebviews.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
>> responseHandler.js:76:14 [master] pid:74653 Send Bad HTTP Respone to Client: {"sessionId":"07c8e888-1ef5-4e35-a9b2-e130ca720d97","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.3 x86_64)"}}
>> responseHandler.js:11:12 [master] pid:74653 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/07c8e888-1ef5-4e35-a9b2-e130ca720d97/contexts, jsonBody: {}
>> proxy.js:52:14 [master] pid:74653 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/1f566965bb4f4920ddacd4ee9e1cbffd/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:74653 Got response with status 200: {"sessionId":"1f566965bb4f4920ddacd4ee9e1cbffd","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X...

**Comment by ericchen82** [comment]
本地chrome版本 54.0.2840.98 (64-bit)

**Comment by Archer456** [comment]
请参考  https://testerhome.com/wiki/macaca
关于 Macaca 中的 web 网页项目测试问题 (electron 和 chromedriver)  请参考该篇或其他相关篇

**Comment by xudafeng** [comment]
https://testerhome.com/topics/8039
