### ISSUE TITLE
 win7 64位 运行uirecorder，录制脚本，已打开Genymotion,显示chrome打开失败

### ISSUE THREAD

**Issue by BreakCircle** [alibaba/macaca#450]
## **- 运行uirecorder，显示chrome打开失败，步骤如下**

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>d:

D:\>cd D:\zsfile\pc

D:\zsfile\pc>uirecorder init
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.3.31

------------------------------------------------------------------

? 配置文件 config.json
? Path扩展属性配置,除id,name,class之外 (data-id,data-name,type,data-type,role,da
? Path扩展属性配置,除id,name,class之外 data-id,data-name,type,data-type,role,dat
a-role,d
ata-value
? 属性值黑名单正则
? 断言前隐藏
? WebDriver域名或IP 127.0.0.1
? WebDriver端口号 4444
? 需要同时测试的浏览器列表 chrome, ie 11
config.json 文件保存成功
package.json 文件创建成功
README.md 文件创建成功
screenshots 文件夹创建成功
commons 文件夹创建成功
uploadfiles 文件夹创建成功
.editorconfig 文件创建成功
.gitignore 文件创建成功
install.sh 文件创建成功
run.bat 文件创建成功
run.sh 文件创建成功
hosts 文件创建成功

D:\zsfile\pc>npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
uirecorderTest@1.0.0 D:\zsfile\pc
+-- chai@3.5.0
| +-- assertion-error@1.0.2
| +-- deep-eql@0.1.3
| | `-- type-detect@0.1.1
| `-- type-detect@1.0.0
+-- faker@3.1.0
+-- jwebdriver@2.0.8
| +-- node-zip@1.1.1
| | `-- jszip@2.5.0
| |   `-- pako@0.2.9
| +-- promiseclass@1.0.3
| | `-- co@4.6.0
| +-- request@2.65.0
| | +-- aws-sign2@0.6.0
| | +-- bl@1.0.3
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@1.0.1
| | | `-- async@2.1.4
| | |   `-- lodash@4.17.4
| | +-- har-validator@2.0.6
| | | +-- is-my-json-valid@2.15.0
| | | | +-- generate-function@2.0.0
| | | | +-- generate-object-property@1.2.0
| | | | | `-- is-property@1.0.2
| | | | +-- jsonpointer@4.0.1
| | | | `-- xtend@4.0.1
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@0.11.0
| | | +-- asn1@0.1.11
| | | +-- assert-plus@0.1.5
| | | `-- ctype@0.5.3
| | +-- isstream@0.1.2
| | +-- mime-types@2.1.14
| | | `-- mime-db@1.26.0
| | +-- oauth-sign@0.8.2
| | +-- qs@5.2.1
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.2.2
| | `-- tunnel-agent@0.4.3
| `-- xtend@2.0.3
+-- mocha@3.1.2
| +-- browser-stdout@1.3.0
| +-- commander@2.9.0
| | `-- graceful-readlink@1.0.1
| +-- debug@2.2.0
| | `-- ms@0.7.1
| +-- diff@1.4.0
| +-- escape-string-regexp@1.0.5
| +-- glob@7.0.5
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.3
| | +-- minimatch@3.0.3
| | | `-- brace-expansion@1.1.6
| | |   +-- balanced-match@0.4.2
| | |   `-- concat-map@0.0.1
| | +-- once@1.4.0
| | `-- path-is-absolute@1.0.1
| +-- growl@1.9.2
| +-- json3@3.3.2
| +-- lodash.create@3.1.1
| | +-- lodash._baseassign@3.2.0
| | | +-- lodash._basecopy@3.0.1
| | | `-- lodash.keys@3.1.2
| | |   +-- lodash._getnative@3.9.1
| | |   +-- lodash.isarguments@3.1.0
| | |   `-- lodash.isarray@3.0.4
| | +-- lodash._basecreate@3.0.3
| | `-- lodash._isiterateecall@3.0.9
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| `-- supports-color@3.1.2
|   `-- has-flag@1.0.0
+-- mocha-parallel-tests@1.2.4
| +-- debug@2.3.2
| | `-- ms@0.7.2
| `-- yargs@6.4.0
|   +-- camelcase@3.0.0
|   +-- cliui@3.2.0
|   | `-- wrap-ansi@2.1.0
|   +-- decamelize@1.2.0
|   +-- get-caller-file@1.0.2
|   +-- os-locale@1.4.0
|   | `-- lcid@1.0.0
|   |   `-- invert-kv@1.0.0
|   +-- read-pkg-up@1.0.1
|   | +-- find-up@1.1.2
|   | | `-- path-exists@2.1.0
|   | `-- read-pkg@1.1.0
|   |   +-- load-json-file@1.1.0
|   |   | +-- graceful-fs@4.1.11
|   |   | +-- parse-json@2.2.0
|   |   | | `-- error-ex@1.3.0
|   |   | |   `-- is-arrayish@0.2.1
|   |   | +-- pify@2.3.0
|   |   | `-- strip-bom@2.0.0
|   |   |   `-- is-utf8@0.2.1
|   |   +-- normalize-package-data@2.3.5
|   |   | +-- hosted-git-info@2.2.0
|   |   | +-- is-builtin-module@1.0.0
|   |   | | `-- builtin-modules@1.1.1
|   |   | +-- semver@5.3.0
|   |   | `-- validate-npm-package-license@3.0.1
|   |   |   +-- spdx-correct@1.0.2
|   |   |   | `-- spdx-license-ids@1.2.2
|   |   |   `-- spdx-expression-parse@1.0.4
|   |   `-- path-type@1.1.0
|   +-- require-directory@2.1.1
|   +-- require-main-filename@1.0.1
|   +-- set-blocking@2.0.0
|   +-- string-width@1.0.2
|   | +-- code-point-at@1.1.0
|   | `-- is-fullwidth-code-point@1.0.0
|   |   `-- number-is-nan@1.0.1
|   +-- which-module@1.0.0
|   +-- window-size@0.2.0
|   +-- y18n@3.2.1
|   `-- yargs-parser@4.2.1
+-- mochawesome-uirecorder@1.5.20
| +-- async@0.9.2
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- handlebars@3.0.3
| | +-- optimist@0.6.1
| | | `-- wordwrap@0.0.3
| | +-- source-map@0.1.43
| | | `-- amdefine@1.0.1
| | `-- uglify-js@2.3.6
| |   +-- async@0.2.10
| |   `-- optimist@0.3.7
| +-- highlight.js@8.9.1
| +-- json-stringify-safe@5.0.1
| +-- lodash@3.10.1
| +-- moment@2.17.1
| +-- ncp@1.0.1
| +-- node-uuid@1.4.7
| +-- opener@1.4.3
| `-- xml@1.0.1
`-- selenium-standalone@5.11.1
  +-- async@1.2.1
  +-- commander@2.6.0
  +-- lodash@3.9.3
  +-- minimist@1.1.0
  +-- mkdirp@0.5.0
  | `-- minimist@0.0.8
  +-- progress@1.1.8
  +-- request@2.79.0
  | +-- aws4@1.6.0
  | +-- form-data@2.1.2
  | | `-- asynckit@0.4.0
  | +-- http-signature@1.1.1
  | | +-- assert-plus@0.2.0
  | | +-- jsprim@1.3.1
  | | | +-- extsprintf@1.0.2
  | | | +-- json-schema@0.2.3
  | | | `-- verror@1.3.6
  | | `-- sshpk@1.10.2
  | |   +-- asn1@0.2.3
  | |   +-- assert-plus@1.0.0
  | |   +-- bcrypt-pbkdf@1.0.1
  | |   +-- dashdash@1.14.1
  | |   | `-- assert-plus@1.0.0
  | |   +-- ecc-jsbn@0.1.1
  | |   +-- getpass@0.1.6
  | |   | `-- assert-plus@1.0.0
  | |   +-- jodid25519@1.0.2
  | |   +-- jsbn@0.1.1
  | |   `-- tweetnacl@0.14.5
  | +-- is-typedarray@1.0.0
  | +-- qs@6.3.1
  | +-- tough-cookie@2.3.2
  | | `-- punycode@1.4.1
  | `-- uuid@3.0.1
  +-- tar-stream@1.5.2
  | +-- end-of-stream@1.1.0
  | | `-- once@1.3.3
  | +-- readable-stream@2.0.6
  | | +-- core-util-is@1.0.2
  | | +-- isarray@1.0.0
  | | +-- process-nextick-args@1.0.7
  | | +-- string_decoder@0.10.31
  | | `-- util-deprecate@1.0.2
  | `-- xtend@4.0.1
  +-- urijs@1.16.1
  +-- which@1.1.1
  | `-- is-absolute@0.1.7
  |   `-- is-relative@0.1.3
  `-- yauzl@2.7.0
    +-- buffer-crc32@0.2.13
    `-- fd-slicer@1.0.1
      `-- pend@1.2.0

npm WARN uirecorderTest@1.0.0 No repository field.
npm WARN uirecorderTest@1.0.0 scripts['server'] should probably be scripts['star
t'].
npm WARN uirecorderTest@1.0.0 No license field.

D:\zsfile\pc>uirecorder start --mobile
    __  ______   ____                           __
   / / / /  _/  / __ \___  _________  _________/ /__  _____
  / / / // /   / /_/ / _ \/ ___/ __ \/ ___/ __  / _ \/ ___/
 / /_/ // /   / _, _/  __/ /__/ /_/ / /  / /_/ /  __/ /
 \____/___/  /_/ |_|\___/\___/\____/_/   \__,_/\___/_/    v2.3.31

------------------------------------------------------------------

? 配置文件 config.json
? 测试脚本文件名 sample/test.spec.js
? App路径, 扩展名: apk, app () D:\zsfile\D:\zsfile\com.android.chrome_292408700.
? App路径, 扩展名: apk, app () D:\zsfile\D:\zsfile\com.android.chrome_292408700.
? App路径, 扩展名: apk, app () D:\zsfile\D:\zsfile\com.android.chrome_292408700.
? App路径, 扩展名: apk, app () D:\zsfile\D:\zsfile\com.android.chrome_292408700.
? App路径, 扩展名: apk, app D:\zsfile\com.android.chrome_292408700.apk

录制服务器监听在端口: 9765
Chrome打开失败！
{ Error: connect ECONNREFUSED 127.0.0.1:9766
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9766 }

## **- 服务端的信息是这样的：**
C:\Users\Administrator>macaca server --port 4444 --verbose
>> index.js:17:12 [master] pid:5852 webdriver server start with config:
 { port: '4444',
  verbose: true,
  always: true,
  ip: '192.168.0.198',
  host: 'USER-6IG90K3098',
  loaded_time: '2017-02-16 16:38:13' }
>> middlewares.js:17:10 [master] pid:5852 base middlewares attached
>> router.js:127:10 [master] pid:5852 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:5852 Recieve HTTP Request from Client:
method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformNa
me":"Android","udid":"192.168.9.101:5555","app":"D:\\zsfile\\com.android.chrome_
292408700.apk"}}
>> session.js:47:10 [master] pid:5852 Creating session, sessionId: 358f409a-5e47
-48b9-9b4f-46a3a8230e36.
>> helper.js:208:12 [master] pid:5852 Using local app form D:\zsfile\com.android
.chrome_292408700.apk

  Error: read ECONNRESET
      at exports._errnoException (util.js:1022:11)
      at TCP.onread (net.js:569:26)

>> uiautomator-client.js:31:12 [master] pid:5852 uiautomator-bootstrap was not f
ound in: C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android\
node_modules\.1.0.43@uiautomator-client\bin\uiautomator-bootstrap.jar, please ch
eck your Android ENV
>> responseHandler.js:54:12 [master] pid:5852 Send Error Respone to Client: Erro
r: >> uiautomator-client.js:31:12 [master] pid:5852 uiautomator-bootstrap was no
t found in: C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-andro
id\node_modules\.1.0.43@uiautomator-client\bin\uiautomator-bootstrap.jar, please
 check your Android ENV
>> responseHandler.js:60:14 [master] pid:5852 Error: >> uiautomator-client.js:31
:12 [master] pid:5852 uiautomator-bootstrap was not found in: C:\Users\Administr
ator\AppData\Roaming\npm\node_modules\macaca-android\node_modules\.1.0.43@uiauto
mator-client\bin\uiautomator-bootstrap.jar, please check your Android ENV
    at Logger.error (C:\Users\Administrator\AppData\Roaming\npm\node_modules\mac
aca-android\node_modules\.1.0.6@xlogger\lib\xlogger.js:169:9)
    at UIAutomator.init (C:\Users\Administrator\AppData\Roaming\npm\node_modules
\macaca-android\node_modules\.1.0.43@uiautomator-client\lib\uiautomator-client.j
s:31:12)
    at next (native)
    at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\maca
ca-cli\node_modules\.4.6.0@co\index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

  Error: >> uiautomator-client.js:31:12 [master] pid:5852 uiautomator-bootstrap
was not found in: C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca
-android\node_modules\.1.0.43@uiautomator-client\bin\uiautomator-bootstrap.jar,
please check your Android ENV
      at Logger.error (C:\Users\Administrator\AppData\Roaming\npm\node_modules\m
acaca-android\node_modules\.1.0.6@xlogger\lib\xlogger.js:169:9)
      at UIAutomator.init (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\macaca-android\node_modules\.1.0.43@uiautomator-client\lib\uiautomator-client
.js:31:12)
      at next (native)
      at onFulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ma
caca-cli\node_modules\.4.6.0@co\index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

## ## - Macaca docror 如下：
C:\Users\Administrator>macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v6.9.5

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_111`
  ANDROID_HOME is set to `D:\zsfile\Android`
  Platforms is set to `D:\zsfile\Android\platforms\android-22`
  Android tools is set to `D:\zsfile\Android\tools\android.bat`
  ADB tool is set to `D:\zsfile\Android\platform-tools\adb.exe`
  ANT_HOME is set to `C:\ant;`

  Installed driver list:

  android: 1.1.16
  chrome: 1.0.5
  electron: 1.1.4 [out-of-date]
  ios: 1.0.53

**Comment by Archer456** [comment]
https://testerhome.com/wiki/macaca  请参考下的  关于 Macaca 中的 web 网页项目测试问题 (electron 和 chromedriver)
