### ISSUE TITLE
ubuntu kylin 16.10 安装app-inspector 报错，运行不起来，请大神指点

### ISSUE THREAD

**Issue by BreakCircle** [alibaba/macaca#451]
- ## **安装过程如下：**

- ## 安装过程中出现JAVA_HOME没有找到；运行的时候，没有uiautomator-client'

breakcircle@zs:~$ sudo npm i -g app-inspector
[sudo] breakcircle 的密码： 
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/app-inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector
/usr/local/bin/inspector -> /usr/local/lib/node_modules/app-inspector/bin/app-inspector

> webdriveragent@1.0.41 install /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent
> node ./scripts/install.js

Successfully updated Bundle Id, but no Team Id was provided. Please update your team id manually in /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj/project.pbxproj, or reinstall the module with DEVELOPMENT_TEAM_ID in environment variable.

> uiautomator-client@1.0.43 install /usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client
> node ./scripts/build.js

/usr/local/lib/node_modules/app-inspector/node_modules/uiautomator-client/scripts/build.js:177
      throw e;
      ^

Error: $JAVA_HOME not found
    at /usr/local/lib/node_modules/app-inspector/node_modules/java-home/lib/java-home.js:74:17
npm WARN install:uiautomator-client@1.0.43 uiautomator-client@1.0.43 install: `node ./scripts/build.js`
npm WARN install:uiautomator-client@1.0.43 Exit status 1
/usr/local/lib
└─┬ app-inspector@1.2.18 
  ├─┬ chalk@1.1.3 
  │ ├── ansi-styles@2.2.1 
  │ ├── escape-string-regexp@1.0.5 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.1.1 
  │ ├── strip-ansi@3.0.1 
  │ └── supports-color@2.0.0 
  ├── co@4.6.0 
  ├── co-request@1.0.0 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├─┬ detect-port@1.1.0 
  │ └─┬ debug@2.6.1 
  │   └── ms@0.7.2 
  ├─┬ ios-simulator@1.0.9 
  │ └─┬ plist@1.2.0 
  │   ├── base64-js@0.0.8 
  │   ├── util-deprecate@1.0.2 
  │   ├── xmlbuilder@4.0.0 
  │   └── xmldom@0.1.27 
  ├─┬ ios-utils@1.0.4 
  │ └─┬ bplist-parser@0.1.1 
  │   └── big-integer@1.6.17 
  ├─┬ koa@1.2.5 
  │ ├─┬ accepts@1.3.3 
  │ │ └── negotiator@0.6.1 
  │ ├─┬ composition@2.3.0 
  │ │ └── any-promise@1.3.0 
  │ ├── content-disposition@0.5.2 
  │ ├── content-type@1.0.2 
  │ ├─┬ cookies@0.6.2 
  │ │ ├── depd@1.1.0 
  │ │ └── keygrip@1.0.1 
  │ ├── delegates@1.0.0 
  │ ├── destroy@1.0.4 
  │ ├── error-inject@1.0.0 
  │ ├── escape-html@1.0.3 
  │ ├── fresh@0.3.0 
  │ ├─┬ http-assert@1.2.0 
  │ │ ├── deep-equal@1.0.1 
  │ │ └─┬ http-errors@1.4.0 
  │ │   └── inherits@2.0.1 
  │ ├─┬ http-errors@1.6.0 
  │ │ ├── inherits@2.0.3 
  │ │ └── setprototypeof@1.0.2 
  │ ├── koa-compose@2.5.1 
  │ ├── koa-is-json@1.0.0 
  │ ├─┬ mime-types@2.1.14 
  │ │ └── mime-db@1.26.0 
  │ ├─┬ on-finished@2.3.0 
  │ │ └── ee-first@1.1.1 
  │ ├── only@0.0.2 
  │ ├── parseurl@1.3.1 
  │ ├── statuses@1.3.1 
  │ ├─┬ type-is@1.6.14 
  │ │ └── media-typer@0.3.0 
  │ └── vary@1.1.0 
  ├─┬ koa-bodyparser@2.3.0 
  │ ├─┬ co-body@4.2.0 
  │ │ ├── inflation@2.0.0 
  │ │ ├── qs@4.0.0 
  │ │ └─┬ raw-body@2.1.7 
  │ │   ├── bytes@2.4.0 
  │ │   ├── iconv-lite@0.4.13 
  │ │   └── unpipe@1.0.0 
  │ └── copy-to@2.0.1 
  ├─┬ koa-router@5.4.0 
  │ ├── methods@1.1.2 
  │ └─┬ path-to-regexp@1.7.0 
  │   └── isarray@0.0.1 
  ├─┬ koa-static@2.1.0 
  │ └─┬ koa-send@3.3.0 
  │   ├─┬ mz@2.6.0 
  │   │ ├── object-assign@4.1.1 
  │   │ └─┬ thenify-all@1.6.0 
  │   │   └── thenify@3.2.1 
  │   └─┬ resolve-path@1.3.3 
  │     └── http-errors@1.5.1 
  ├─┬ macaca-adb@1.0.20 
  │ └── macaca-utils@0.1.9 
  ├─┬ npm-update@1.0.5 
  │ └── co-request@0.2.1 
  ├─┬ nunjucks@2.5.2 
  │ ├── asap@2.0.5 
  │ ├─┬ chokidar@1.6.1 
  │ │ ├─┬ anymatch@1.3.0 
  │ │ │ ├── arrify@1.0.1 
  │ │ │ └─┬ micromatch@2.3.11 
  │ │ │   ├─┬ arr-diff@2.0.0 
  │ │ │   │ └── arr-flatten@1.0.1 
  │ │ │   ├── array-unique@0.2.1 
  │ │ │   ├─┬ braces@1.8.5 
  │ │ │   │ ├─┬ expand-range@1.8.2 
  │ │ │   │ │ └─┬ fill-range@2.2.3 
  │ │ │   │ │   ├── is-number@2.1.0 
  │ │ │   │ │   ├─┬ isobject@2.1.0 
  │ │ │   │ │   │ └── isarray@1.0.0 
  │ │ │   │ │   ├── randomatic@1.1.6 
  │ │ │   │ │   └── repeat-string@1.6.1 
  │ │ │   │ ├── preserve@0.2.0 
  │ │ │   │ └── repeat-element@1.1.2 
  │ │ │   ├─┬ expand-brackets@0.1.5 
  │ │ │   │ └── is-posix-bracket@0.1.1 
  │ │ │   ├── extglob@0.3.2 
  │ │ │   ├── filename-regex@2.0.0 
  │ │ │   ├─┬ kind-of@3.1.0 
  │ │ │   │ └── is-buffer@1.1.4 
  │ │ │   ├── normalize-path@2.0.1 
  │ │ │   ├─┬ object.omit@2.0.1 
  │ │ │   │ ├─┬ for-own@0.1.4 
  │ │ │   │ │ └── for-in@0.1.6 
  │ │ │   │ └── is-extendable@0.1.1 
  │ │ │   ├─┬ parse-glob@3.0.4 
  │ │ │   │ ├── glob-base@0.3.0 
  │ │ │   │ └── is-dotfile@1.0.2 
  │ │ │   └─┬ regex-cache@0.4.3 
  │ │ │     ├── is-equal-shallow@0.1.3 
  │ │ │     └── is-primitive@2.0.0 
  │ │ ├── async-each@1.0.1 
  │ │ ├── glob-parent@2.0.0 
  │ │ ├─┬ is-binary-path@1.0.1 
  │ │ │ └── binary-extensions@1.8.0 
  │ │ ├─┬ is-glob@2.0.1 
  │ │ │ └── is-extglob@1.0.0 
  │ │ ├── path-is-absolute@1.0.1 
  │ │ └─┬ readdirp@2.1.0 
  │ │   ├── graceful-fs@4.1.11 
  │ │   ├─┬ minimatch@3.0.3 
  │ │   │ └─┬ brace-expansion@1.1.6 
  │ │   │   ├── balanced-match@0.4.2 
  │ │   │   └── concat-map@0.0.1 
  │ │   ├─┬ readable-stream@2.2.2 
  │ │   │ ├── buffer-shims@1.0.0 
  │ │   │ ├── core-util-is@1.0.2 
  │ │   │ ├── isarray@1.0.0 
  │ │   │ ├── process-nextick-args@1.0.7 
  │ │   │ └── string_decoder@0.10.31 
  │ │   └── set-immediate-shim@1.0.1 
  │ └─┬ yargs@3.32.0 
  │   ├── camelcase@2.1.1 
  │   ├─┬ cliui@3.2.0 
  │   │ └── wrap-ansi@2.1.0 
  │   ├── decamelize@1.2.0 
  │   ├─┬ os-locale@1.4.0 
  │   │ └─┬ lcid@1.0.0 
  │   │   └── invert-kv@1.0.0 
  │   ├─┬ string-width@1.0.2 
  │   │ ├── code-point-at@1.1.0 
  │   │ └─┬ is-fullwidth-code-point@1.0.0 
  │   │   └── number-is-nan@1.0.1 
  │   ├── window-size@0.1.4 
  │   └── y18n@3.2.1 
  ├─┬ request@2.79.0 
  │ ├── aws-sign2@0.6.0 
  │ ├── aws4@1.6.0 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@2.1.2 
  │ │ └── asynckit@0.4.0 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ is-my-json-valid@2.15.0 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ ├── jsonpointer@4.0.1 
  │ │ │ └── xtend@4.0.1 
  │ │ └─┬ pinkie-promise@2.0.1 
  │ │   └── pinkie@2.0.4 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.1 
  │ │ ├── assert-plus@0.2.0 
  │ │ ├─┬ jsprim@1.3.1 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.3 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.10.2 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@1.0.0 
  │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │   ├─┬ dashdash@1.14.1 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├─┬ getpass@0.1.6 
  │ │   │ └── assert-plus@1.0.0 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.1 
  │ │   └── tweetnacl@0.14.5 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├── oauth-sign@0.8.2 
  │ ├── qs@6.3.1 
  │ ├── stringstream@0.0.5 
  │ ├─┬ tough-cookie@2.3.2 
  │ │ └── punycode@1.4.1 
  │ ├── tunnel-agent@0.4.3 
  │ └── uuid@3.0.1 
  ├─┬ webdriveragent@1.0.41 
  │ ├── adm-zip@0.4.7 
  │ └─┬ xcode@0.8.9 
  │   ├── node-uuid@1.4.7 
  │   ├── pegjs@0.9.0 
  │   └─┬ simple-plist@0.1.4 
  │     ├─┬ bplist-creator@0.0.4 
  │     │ └── stream-buffers@0.2.6 
  │     └── bplist-parser@0.0.6 
  ├─┬ xctest-client@1.0.29 
  │ ├── ios-deviceconsole@1.0.1 
  │ ├─┬ request@2.69.0 
  │ │ ├─┬ bl@1.0.3 
  │ │ │ └─┬ readable-stream@2.0.6 
  │ │ │   └── isarray@1.0.0 
  │ │ ├─┬ form-data@1.0.1 
  │ │ │ └─┬ async@2.1.4 
  │ │ │   └── lodash@4.17.4 
  │ │ ├── node-uuid@1.4.7 
  │ │ ├── qs@6.0.3 
  │ │ └── tough-cookie@2.2.2 
  │ └── webdriver-dfn-error-code@1.0.4 
  ├── xlogger@1.0.6 
  ├─┬ xml2map@1.0.2 
  │ ├── sax@0.4.2 
  │ └── xml-writer@1.6.0 
  └─┬ xutil@1.0.3 
    ├── ipv4@0.0.4 
    ├── lodash@3.10.1 
    ├─┬ mkdirp@0.5.1 
    │ └── minimist@0.0.8 
    ├── moment@2.10.6 
    ├── node-uuid@1.4.7 
    └─┬ rimraf@2.5.4 
      └─┬ glob@7.1.1 
        ├── fs.realpath@1.0.0 
        ├─┬ inflight@1.0.6 
        │ └── wrappy@1.0.2 
        └── once@1.4.0 

npm WARN optional Skipping failed optional dependency /app-inspector/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
breakcircle@zs:~$ sudo app-inspector -u 760BBKR228X2
[sudo] breakcircle 的密码： 
>> app-inspector:66:44 [master] pid:14458 Error: Cannot find module 'uiautomator-client'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/app-inspector/lib/android.js:7:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

-  ## **macaca doctor:**

root@zs:/home/breakcircle# macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/bin/node
  node version: v4.2.6

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/opt/android-sdk-linux`
  Platforms is set to `/opt/android-sdk-linux/platforms/android-22`
  Android tools is set to `/opt/android-sdk-linux/tools/android`
  ADB tool is set to `/opt/android-sdk-linux/platform-tools/adb`

  Installed driver list:

  android: 1.1.16
  chrome: 1.0.5
  electron: 1.1.5

**Comment by Archer456** [comment]
请参考 https://testerhome.com/wiki/macaca    中的相关章节   也有ubuntu的

**Comment by BreakCircle** [comment]
看了 没用

**Comment by CodeToSurvive1** [comment]
macaca doctor检查下有问题么

**Comment by richashri87** [comment]
You can find your Team ID using your developer account. Sign in to developer.apple.com/account, and click Membership in the sidebar. Your Team ID appears in the Membership Information section under the team name.
