### ISSUE TITLE
win7 64位 app-inspector安装报错

### ISSUE THREAD

**Issue by BreakCircle** [alibaba/macaca#452]
# win7 64位 app-inspector安装报错，如下
# uiautomator-client安装有什么技巧吗？
## C:\Users\Administrator>npm i -g app-inspector
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/Indigo
United/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/
node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
C:\Users\Administrator\AppData\Roaming\npm\inspector -> C:\Users\Administrator\A
ppData\Roaming\npm\node_modules\app-inspector\bin\app-inspector
C:\Users\Administrator\AppData\Roaming\npm\app-inspector -> C:\Users\Administrat
or\AppData\Roaming\npm\node_modules\app-inspector\bin\app-inspector

> uiautomator-client@1.0.43 install C:\Users\Administrator\AppData\Roaming\npm\n
ode_modules\app-inspector\node_modules\uiautomator-client
> node ./scripts/build.js

JAVA_HOME is set to C:\Program Files\Java\jdk1.8.0_111
Updated
file C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\node_
modules\uiautomator-client\build.xml
'C:\ant' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspector\node_modul
es\uiautomator-client\scripts\build.js:177
      throw e;
      ^

Error: build failed
    at ChildProcess.buildProcess.on.code (C:\Users\Administrator\AppData\Roaming
\npm\node_modules\app-inspector\node_modules\uiautomator-client\scripts\build.js
:163:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
- fsevents@1.0.17 node_modules\app-inspector\node_modules\fsevents
C:\Users\Administrator\AppData\Roaming\npm
`-- app-inspector@1.2.18

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ap
p-inspector\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uiautomator-client@1.0.43 (node_
modules\app-inspector\node_modules\uiautomator-client):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uiautomator-client@1.0.43 instal
l: `node ./scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

## C:\Users\Administrator>app-inspector -u  192.168.9.101:5555
>> app-inspector:66:44 [master] pid:5652 Error: Cannot find module 'uiautomator-
client'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\app-inspector\lib\android.js:7:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
(node:5652) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 2): Error: >> app-inspector:66:44 [master] pid:5652 Error: Cannot find
module 'uiautomator-client'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\app-inspector\lib\android.js:7:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

- ## **Macaca doctor：**

C:\Users\Administrator>macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v6.9.5

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_111`
  ANDROID_HOME is set to `D:\zsfile\Android`
  Platforms is set to `D:\zsfile\Android\platforms\android-22`
  Android tools is set to `D:\zsfile\Android\tools\android.bat`
  ADB tool is set to `D:\zsfile\Android\platform-tools\adb.exe`
  ANT_HOME is set to `C:\ant;`

  Installed driver list:

  android: 1.1.16
  chrome: 1.0.5
  electron: 1.1.5
  ios: 1.0.53

**Comment by dharmamoolya** [comment]
make sure you have "uiautomator-client" module inside app-inspector
`C:\Users\dharma\AppData\Roaming\npm\node_modules\app-inspector\node_modules`

If not present in this location, go to **"`macaca-android/node_module`"** . COPY from this place to 
**`app-inspector/node_modules`** directory.

I hope it will solve your issue

**Comment by Archer456** [comment]
https://testerhome.com/wiki/macaca  请参考  其中有关于安装的若干问题解决方案
