### ISSUE TITLE
如何根据相对的xpath获得子元素？

### ISSUE THREAD

**Issue by rita1014** [alibaba/macaca#454]
如何根据相对的xpath获得子元素？或者如何获得当前一个元素的xpath？

**Comment by ElesG** [comment]
使用app-inspector  传送门：https://macacajs.github.io/app-inspector/cn/

**Comment by yihuineng** [comment]
问题久远关闭，如有问题，可再次提issue

**Comment by candialala** [comment]
你好，来信已收到~~我会尽快查收并回复的！
XMU Software 
陈晓娟
