### ISSUE TITLE
app-inspector 在ios环境下crash

### ISSUE THREAD

**Issue by baozhida** [alibaba/macaca#455]
* **Macaca Version**:
1.2.0
* **app-inspector**:
 1.2.18 

* **Macaca Doctor Logs**:
 macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/MAC/Library/Android/sdk`
  Platforms is set to `/Users/MAC/Library/Android/sdk/platforms/android-24`
  Android tools is set to `/Users/MAC/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/MAC/Library/Android/sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.16 [out-of-date]
  ios: 1.0.53
* **Operate System**:
OS X 10.11.6

* **Device**:
iphone 7 
IOS 10.2

### app切到在公共号页面，刷新浏览器，微信闪退

app-inspector -u xxx 报错信息

```
  <-- GET /
The source may be wrong, please report with below message at:
    https://github.com/macacajs/app-inspector/issues/new
    ****** xctest source start *******
    {"value":{"tree":{"bounds":"{{0, 0}, {0, 0}}","rawIdentifier":null,"isVisible":"0","value":null,"label":null,"type":"Any","name":null,"isEnabled":"0"}},"sessionId":null,"status":0}
    '****** xctest source end *******

  TypeError: Cannot read property 'x' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/ios.js:27:9)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/ios.js:60:22)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/.4.6.0@co/index.js:65:19)
      at process._tickCallback (internal/process/next_tick.js:103:7)

```

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/381

**Comment by xudafeng** [comment]
https://github.com/facebook/WebDriverAgent/issues/501

**Comment by xudafeng** [comment]
update driver
