### ISSUE TITLE
getProperty()方法获取控件的value，如果返回的是boolean类型系统提示java.lang.ClassCastException: java.lang.Boolean cannot be cast to com.alibaba.fastjson.JSONObject

### ISSUE THREAD

**Issue by dieson** [alibaba/macaca#456]
* **Macaca Version**: 2.0.1

* **Macaca Doctor Logs**: java.lang.ClassCastException: java.lang.Boolean cannot be cast to com.alibaba.fastjson.JSONObject

* **Operate System**: Mac 10.12.1

* **Programming Language**: English

**Comment by zsmjluo** [comment]
@xudafeng 遇到了同样的问题，getProperty返回值应该是 JSONObject。执行后会出现java.lang.String cannot be cast to com.alibaba.fastjson.JSONObject错误。

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/466
