### ISSUE TITLE
app-inspector:66:44 [master] pid:32216 undefined

### ISSUE THREAD

**Issue by Tracydeng** [alibaba/macaca#459]
* **Macaca Version**:1.2.0

* **Macaca Doctor Logs**:

```
    macaca-doctor version: 1.0.28

    Node.js checklist:

    node env: /Users/iSteven/.nvm/versions/node/v6.3.1/bin/node
    node version: v6.3.1

    iOS checklist:

    Xcode is installed at: `/Applications/Xcode_7.3.1.app/Contents/Developer`
    Xcode Command Line Tools is ready, version: 2347.
    iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
    ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

    Android checklist:

    JAVA version is `1.8.0_101`
    JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`
    ANDROID_HOME is set to `/Users/iSteven/Library/Android/sdk`
    Platforms is set to `/Users/iSteven/Library/Android/sdk/platforms/android-24`
    Android tools is set to `/Users/iSteven/Library/Android/sdk/tools/android`
    ADB tool is set to `/Users/iSteven/Library/Android/sdk/platform-tools/adb`

    Installed driver list:

```

* **Operate System**: OSX 10.12.3

* **Programming Language**:Objective-c

  ~ app-inspector -u DC8E88DF-EDA7-487A-9D34-77AA58B3ADB5 --verbose
>> server.js:16:12 [master] pid:32216 server start with config:
 { port: 5678,
  verbose: true,
  udid: 'DC8E88DF-EDA7-487A-9D34-77AA58B3ADB5',
  ip: '10.180.185.87',
  host: 'iStevendeMacBook-Pro.local',
  loaded_time: '2017-02-27 16:42:19' }
>> app-inspector.js:42:10 [master] pid:32216 server start at: http://10.180.185.87:5678
>> xctest-client.js:56:14 [master] pid:32216 project path: /Users/iSteven/.nvm/versions/node/v6.3.1/lib/node_modules/app-inspector/node_modules/xctest-client/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:32216 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.41
>> xctest-client.js:99:16 [master] pid:32216 tail: /Users/iSteven/Library/Logs/CoreSimulator/DC8E88DF-EDA7-487A-9D34-77AA58B3ADB5/system.log: No such file or directory

>> xctest-client.js:107:16 [master] pid:32216 simulator log process exit with code: 1, signal: null
>> xctest-client.js:255:14 [master] pid:32216 Fail to start xctest: undefined
>> xctest-client.js:267:14 [master] pid:32216 killing deviceLogProc pid: 32220
>> xctest-client.js:272:14 [master] pid:32216 killing runnerProc pid: 32221
>> app-inspector:66:44 [master] pid:32216 undefined
>> xctest-client.js:181:14 [master] pid:32216 xctest client exit with code: null, signal: SIGKILL

**Comment by CodeToSurvive1** [comment]
没装ios驱动？

**Comment by lixiaoyudakeke** [comment]
我也遇到这个问题了，楼主解决了吗

**Comment by Tracydeng** [comment]
后面卸载重新安装app-inspector就可以了，真机的话要修改xxx/xxx/node_modules/app-inspector/node_modules/webdriveragent工程bundlid相关设置即可
