### ISSUE TITLE
android端/session/:sessionId/keys不支持中文输入

### ISSUE THREAD

**Issue by yaniswang** [alibaba/macaca#460]
问题描述：

在android下面，调用/session/:sessionId/keys这个api，无法输入中文，见以下截图：

实际输入文字：测试aaa111

![image](https://cloud.githubusercontent.com/assets/970390/23356095/92502608-fd13-11e6-9d65-7d4f6f64a386.png)

ios下面正常，如下截图：

![image](https://cloud.githubusercontent.com/assets/970390/23356115/a8f8c1f8-fd13-11e6-9863-eafa4e1cd632.png)

控件上的输入文字api是全兼容的：/session/:sessionId/element/:id/value

**Comment by yaniswang** [comment]
刚测试了下appium的keys函数，只要开启了unicodeKeyboard，是可以支持中文的。

**Comment by xudafeng** [comment]
@yaniswang https://github.com/macacajs/macaca-android/commit/7a0d18c10860afc7c183510f2d39566c1a3f1b6f

**Comment by xudafeng** [comment]
https://github.com/macacajs/android-unicode#use-with-macaca @yaniswang

**Comment by CodeToSurvive1** [comment]
@xudafeng 这么改我之前说过的两个问题都没解决吧

1.带空格的中文输入
2.焦点触发一下将输入法启动  是没法输入成功的

**Comment by xudafeng** [comment]
@codeskyblue 

- 空格在中间没问题啊，两端会trim
- 点击输入框获取焦点啊

**Comment by yaniswang** [comment]
![image](https://cloud.githubusercontent.com/assets/970390/23577912/1c467a7e-0106-11e7-9586-c22ec00c7fcf.png)

![image](https://cloud.githubusercontent.com/assets/970390/23577917/290262fa-0106-11e7-8dc7-0e7cbaee99a2.png)

还是没修复

**Comment by yaniswang** [comment]
必需这样输入文字吗？

`[ADB_INPUT_TEXT]使用ADB中文输入`

能不能把这个功能内置在macaca里？而不是让用户去输入一个前缀。

**Comment by CodeToSurvive1** [comment]
是的  现在是需要加前缀的 新开issue #https://github.com/alibaba/macaca/issues/473 再调查下看看有没有更完美的方案

**Comment by yaniswang** [comment]
无法默认就用adb发送文字？

那sendKeys函数为什么能默认就用adb来发送文字？

**Comment by CodeToSurvive1** [comment]
sendkeys没有用adb实现 用的uiautomator  adb text默认不支持中文  现在实现思路是用的广播输入法的方式 https://github.com/macacajs/macaca-android/commit/7a0d18c10860afc7c183510f2d39566c1a3f1b6f

**Comment by yaniswang** [comment]
能研究下appium是怎么实现的？
appium发送汉字的时候，并不需要特殊的前缀标记。

**Comment by CodeToSurvive1** [comment]
嗯呢 后研究下的

**Comment by yaniswang** [comment]
https://github.com/appium/appium-android-driver/blob/51b52b0302c06a5107c7b109527be1c9e59d3abe/lib/commands/general.js#L29

**Comment by yaniswang** [comment]
https://github.com/appium/appium-android-bootstrap/blob/e0df190e35baccf31b4e2af81db75cff580631a1/bootstrap/src/io/appium/android/bootstrap/handler/SetText.java

**Comment by xudafeng** [comment]
已解决
