### ISSUE TITLE
IOS JAVA版服务器持续返回500错误

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#464]
iPhone 10.2.1
用例跑一段时间后服务端就会出现如下错误：
>> proxy.js:62:22 [master] pid:11845 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8901
>> proxy.js:62:22 [master] pid:11845 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8901
>> responseHandler.js:54:12 [master] pid:11845 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8901
>> responseHandler.js:60:14 [master] pid:11845 Error: connect ECONNREFUSED 127.0.0.1:8901
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
客户端日志：
500
Response content:Internal Server Error
attempt to search the element for 25 times（一直执行）

**Comment by xudafeng** [comment]
感觉像socket不稳定

**Comment by zsmjluo** [comment]
@xudafeng Macaca能否优化下，当服务端出错和返回超时的情况下，客户端能够能把这个错误码抛出来给上层。这样用例编写时，可以根据对应的返回值去做对应的处理，比如断开连接重连、重试等等。目前一旦出现服务器错误或者服务器没返回就不能处理了。

**Comment by zsmjluo** [comment]
我在上层解决了下，写了个总结到社区，https://testerhome.com/topics/7768

**Comment by xudafeng** [comment]
@Yinxl 框架上加容错吧
