### ISSUE TITLE
android下acceptAlert和dismissAlert功能弄反了

### ISSUE THREAD

**Issue by yaniswang** [alibaba/macaca#465]
android下面，当调用acceptAlert函数时，是点击在no按钮上，调用dismissAlert时，是点击在yes按钮上。

![image](https://cloud.githubusercontent.com/assets/970390/23453379/1bd6db34-fea3-11e6-97c3-23a315b538e8.png)

![image](https://cloud.githubusercontent.com/assets/970390/23453393/2b8a9c00-fea3-11e6-8956-ab7a33aec6cd.png)

![image](https://cloud.githubusercontent.com/assets/970390/23453403/35dc1a62-fea3-11e6-8739-ad29ce156723.png)

**Comment by yaniswang** [comment]
补充下，ios环境下，这两个api是完全正确的。

**Comment by xudafeng** [comment]
应该是个bug

**Comment by yaniswang** [comment]
此问题修复后，建议测试脚本完善下，增加一下验证逻辑。

目前的测试脚本只是执行了一下功能，但是并不知道功能是否执行正确。

**Comment by xudafeng** [comment]
@yaniswang 恩，断言只写了前面一部分

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/blob/master/src/com/android/uiautomator/client/cmd/Alert.java#L29

**Comment by xudafeng** [comment]
跟App逻辑有关
