### ISSUE TITLE
iOS设备Java版本getProperty()方法获取控件的value属性异常

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#468]
ios上用的java版本，macacaclient2.0.2版本获取value属性报错,详情如下：
java.lang.ClassCastException: java.lang.String cannot be cast to com.alibaba.fastjson.JSONObject
at macaca.client.commands.Element.getProperty(Element.java:149)

**Comment by Yinxl** [comment]
已经修改完毕，更新macacaClient依赖至2.0.3 既可以解决。
具体修改见： https://github.com/macacajs/wd.java/commit/12e7c5cbcbc76a65dd2a5ceb6a8fa4496cb21e0f

**Comment by huangejuan** [comment]
@Yinxl 好的，谢谢！另外一个，ios多机并发测试，结果执行的时候都分发到了在同一台机子上去执行了，这个问题在看了吗？
