### ISSUE TITLE
python Electron 的assert支持对页面数字值判断吗？

### ISSUE THREAD

**Issue by PayneHeb** [alibaba/macaca#470]
* **Macaca Version**:1.2.0

* **Macaca Doctor Logs**:
macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.3.0

  iOS checklist:

  Xcode is installed at: `/Library/Developer/CommandLineTools`
  Xcode Command Line Tools is ready, version: 2347.
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home`
  ANDROID_HOME is not set

  Installed driver list:

  chrome: 1.0.5
  electron: 1.1.4 [out-of-date]

* **Operate System**:macOS Sierra 10.12.3

* **Programming Language**:中文

**Comment by xudafeng** [comment]
支持，参考sample https://github.com/macaca-sample

**Comment by PayneHeb** [comment]
@xudafeng 你是说 用assert  in driver.source进行判断吗
