### ISSUE TITLE
android端keys完美解决方案实现

### ISSUE THREAD

**Issue by CodeToSurvive1** [alibaba/macaca#473]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

android端keys完美解决方案实现

**Comment by xudafeng** [comment]
@yaniswang

**Comment by yaniswang** [comment]
![image](https://cloud.githubusercontent.com/assets/970390/23594175/c84397d8-0252-11e7-81c6-2e67cb8a2ec2.png)

从这个逻辑来看，对于没有指定element的，会调用api获取当前焦点的element，然后后面的逻辑就全部一致了。

我们有没有可能也按照这个方案来做？

**Comment by CodeToSurvive1** [comment]
是的  正在看

**Comment by xudafeng** [comment]
@CodeToSurvive1 @yaniswang 

能否仍然保持1一个参数

```
// Android 支持两种类型
.keys('中文1223  yy 字符67') // 中67将会成为字符
.keys(67) //数字类型将会被解析成为ADB按键

// iOS
.keys('中文1223  yy 字符67') // 如有焦点，默认调用sendKeys，无焦点忽略此次
var KEY_MAP = {
   HOME: 0
};
.keys(KEY_MAP.HOME) // 或者输入0的时候，调用wda /homescreen 路由实现Home物理键
```

**Comment by wxlsh114** [comment]
python/macaca里没有keys, 应该使用什么？

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/480

**Comment by xudafeng** [comment]
@codeskyblue https://github.com/alibaba/macaca/issues/480

**Comment by codeskyblue** [comment]
啊

**Comment by xudafeng** [comment]
已实现
