### ISSUE TITLE
Config for executing tests in saucelabs for mobile does not work with desktop test

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#474]
I use below driver definition and desired capabilities  to execute test in saucelabs for mobile. But that does not work with desktop. Kindly assist-

`const driver = wd.promiseChainRemote("ondemand.saucelabs.com", 80, 'username','accesskey')`

`var wd = require('webdriver-client')({
  platform: 'OS X 10.11',
  platformName:'desktop',
  version:'latest',
 browserName:'firefox'
});`
throws below error-

>      Error: [init({"autoAcceptAlerts":true,"browserName":"firefox","platform":"OS X 10.11","platformName":"desktop","version":"latest"})] The environment you requested was unavailable.

**Comment by mpreethi90** [comment]
@zenzhu  can you kindly help to fix this issue?

**Comment by dharmakrish6** [comment]
@mpreethi90 this will help you to run with saucelab
```
const wd = require('macaca-wd');
```
`const driver = wd.promiseChainRemote("ondemand.saucelabs.com", 80, 'username', 'accessKey')`
  ```
return driver
    .init({
      platform: 'Windows 7',
      browserName: 'chrome',
      version: 'latest',
      idleTimeout: 180
    })
```
