### ISSUE TITLE
新手   求大神 解答一下 node版 PC端 select 框 要怎么写 模拟

### ISSUE THREAD

**Issue by 14718011108** [alibaba/macaca#475]
我 点击了一个按钮  打开一个新的页面     但是下面的测试脚本就没有跑到
还是在原来的页面跑    应该要去到新打开的页面跑  这个要怎么解决？

要判断该页面里面存不存在 某个数据 比如说欢迎..登录  这样用hasElementByLinkText可以吗？   要怎么用

pc端测试脚本  select 框要怎么写测试elementByCssSelector    这个怎么用，，

**Comment by xudafeng** [comment]
@14718011108 https://github.com/macaca-sample/sample-nodejs sample中有select示例
