### ISSUE TITLE
运行uirecorder, macaca提示BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.

### ISSUE THREAD

**Issue by Lxxyx** [alibaba/macaca#476]
* **Macaca Version**:
1.2.0
* **Macaca Doctor Logs**:

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.7.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/opt/android-sdk`
  Platforms is set to `/usr/local/opt/android-sdk/platforms/android-24`
  Android tools is set to `/usr/local/opt/android-sdk/tools/android`
  ADB tool is set to `/usr/local/opt/android-sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.54
* **Operate System**:
MacOS 10.12
* **Programming Language**:
Node

```
➜  macaca git:(feature/macaca-test) ✗ macaca server --port 4444
>> webdriver sdk launched
ios-deploy
CFBundleIdentifier is edu.ncu.ncuhome.iNCU
Get bundleId edu.ncu.ncuhome.iNCU from plist /Users/lxxyx/Desktop/app/iNCU/macaca/iNCU.app/Info.plist
BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.
>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.42
BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.
>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.42
BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.
>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.42
BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.
>> xctest-client start with port: 8900
>> WebDriverAgent version: 1.0.42

  InternalServerError: Internal Server Error
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by stepforward** [comment]
@xudafeng 我也有同样的问题,提示BundleId com.apple.test.WebDriverAgentRunner-Runner does not exist.
这是什么情况?手机是9.3系统的,太低了吗?不过跑测试demo,webdriveragent都是可以安装的啊,只是录制的时候报这个错误.

**Comment by xudafeng** [comment]
@stepforward update driver
