### ISSUE TITLE
ios context切换到webview以后，调用getProperty，提示is not a function

### ISSUE THREAD

**Issue by laborchu** [alibaba/macaca#478]
* **Macaca Version**:1.2.0

* **Macaca Ios Version**:1.0.54

* **Driver Server Version**:1.0.75

* **Operate System**:ma os10.12.2

* **Programming Language**:nodejs

native是可以的，因为是通过proxy(xctest)调用的，但是切换到webview以后，proxy为null，会去调用macaca-ios，但是里面没有定义getProperty方法，但是API文档显示getProperty是支持Android iOS Web(WebView)

**Comment by laborchu** [comment]
@xudafeng 我看到selenium-atoms下面有get_attribute_value.js可以调用到元素的attribute，是否可以在macaca-ios下的controllers.js加入getProperty方法

```
controllers.getProperty = function *(elementId, attrName) {
  const atomsElement = convertElement2Atoms.call(this, elementId);
  return yield sendCommand.call(this, 'get_attribute_value', [atomsElement, attrName]);
};
```

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/commit/3be0d2551130d4c98de7c3d94a380bbf50d18744

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-ios/commit/6747260fa0035a21282e7bab4ec88aa1f5f631ea

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/mobile-app-sample-nodejs/commit/6a36484c64a979121a9037c7c81d6818eaf49b14

**Comment by xudafeng** [comment]
@laborchu ios android 升级到最新即可

**Comment by laborchu** [comment]
ok,tks
