### ISSUE TITLE
iOS 输入不成功，报错Timeout waiting for keybord to stop animating

### ISSUE THREAD

**Issue by adfghzhang** [alibaba/macaca#479]
测试环境 iOS10.2模拟器10.2.1 6s真机，调用sendkey方法输入字符时报该错误，同时appium也出现该问题。
但同样的环境下用ios-bootstrap这个app进行测试时，输入字符正常

>> responseHandler.js:11:12 [master] pid:7597 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element/32C51B7C-B516-4A95-AB3B-09827E256EA1/click, jsonBody: {}
>> proxy.js:56:14 [master] pid:7597 Proxy: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element/32C51B7C-B516-4A95-AB3B-09827E256EA1/click:POST to http://192.168.234.128:8900/session/1C757DD8-5904-4C7F-84BD-31A58F4E4953/element/32C51B7C-B516-4A95-AB3B-09827E256EA1/click:POST with body: {}
>> proxy.js:84:20 [master] pid:7597 Got response with status 200: {"status":0,"id":"32C51B7C-B516-4A95-AB3B-09827E256EA1","value":"","sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06"}
>> session.js:107:14 [master] pid:7597 Send HTTP Respone to Client: {"status":0,"id":"32C51B7C-B516-4A95-AB3B-09827E256EA1","value":"","sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06"}
>> responseHandler.js:11:12 [master] pid:7597 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element, jsonBody: {"using":"xpath","value":"/XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]"}
>> proxy.js:56:14 [master] pid:7597 Proxy: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element:POST to http://192.168.234.128:8900/session/1C757DD8-5904-4C7F-84BD-31A58F4E4953/element:POST with body: {"using":"xpath","value":"/XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElemen...
>> proxy.js:84:20 [master] pid:7597 Got response with status 200: {"value":{"ELEMENT":"A0169400-2609-4239-8B5B-31D5DFF6AF08","type":"XCUIElementTypeTextField","label":""},"sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06","status":0}
>> session.js:107:14 [master] pid:7597 Send HTTP Respone to Client: {"value":"{\"ELEMENT\":\"A0169400-2609-4239-8B5B-31D5DFF6AF08\",\"type\":\"XCUIElementTypeTextField\",\"label\":\"\"}","sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06","status":0}
>> responseHandler.js:11:12 [master] pid:7597 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element/A0169400-2609-4239-8B5B-31D5DFF6AF08/click, jsonBody: {}
>> proxy.js:56:14 [master] pid:7597 Proxy: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element/A0169400-2609-4239-8B5B-31D5DFF6AF08/click:POST to http://192.168.234.128:8900/session/1C757DD8-5904-4C7F-84BD-31A58F4E4953/element/A0169400-2609-4239-8B5B-31D5DFF6AF08/click:POST with body: {}
>> proxy.js:84:20 [master] pid:7597 Got response with status 200: {"status":0,"id":"A0169400-2609-4239-8B5B-31D5DFF6AF08","value":"","sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06"}
>> session.js:107:14 [master] pid:7597 Send HTTP Respone to Client: {"status":0,"id":"A0169400-2609-4239-8B5B-31D5DFF6AF08","value":"","sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06"}
>> responseHandler.js:11:12 [master] pid:7597 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element, jsonBody: {"using":"xpath","value":"/XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]"}
>> proxy.js:56:14 [master] pid:7597 Proxy: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element:POST to http://192.168.234.128:8900/session/1C757DD8-5904-4C7F-84BD-31A58F4E4953/element:POST with body: {"using":"xpath","value":"/XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElemen...
>> proxy.js:84:20 [master] pid:7597 Got response with status 200: {"value":{"ELEMENT":"0F4B24F1-8164-4BE6-8B16-CB9C3AEBC78F","type":"XCUIElementTypeTextField","label":""},"sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06","status":0}
>> session.js:107:14 [master] pid:7597 Send HTTP Respone to Client: {"value":"{\"ELEMENT\":\"0F4B24F1-8164-4BE6-8B16-CB9C3AEBC78F\",\"type\":\"XCUIElementTypeTextField\",\"label\":\"\"}","sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06","status":0}
>> responseHandler.js:11:12 [master] pid:7597 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element/0F4B24F1-8164-4BE6-8B16-CB9C3AEBC78F/value, jsonBody: {"value":["18696789382"]}
>> proxy.js:56:14 [master] pid:7597 Proxy: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06/element/0F4B24F1-8164-4BE6-8B16-CB9C3AEBC78F/value:POST to http://192.168.234.128:8900/session/1C757DD8-5904-4C7F-84BD-31A58F4E4953/element/0F4B24F1-8164-4BE6-8B16-CB9C3AEBC78F/value:POST with body: {"value":["18696789382"]}
>> proxy.js:84:20 [master] pid:7597 Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Timeout waiting for keybord to stop animating\" UserInfo={NSLocalizedDescription=Timeout waiting for keybord to stop animating}","session...
>> session.js:107:14 [master] pid:7597 Send HTTP Respone to Client: {"value":"\"Error Domain=com.facebook.WebDriverAgent Code=1 \\\"Timeout waiting for keybord to stop animating\\\" UserInfo={NSLocalizedDescription=Timeout waiting for keybord to stop animating}\"","sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06","status":13}
>> responseHandler.js:11:12 [master] pid:7597 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/a7306ba1-c480-486d-9502-a8637a5fcb06, jsonBody: {}
>> macaca-ios.js:336:10 [master] pid:7597 Stoping iOS driver...
>> xctest-client.js:267:14 [master] pid:7597 killing deviceLogProc pid: 7950
>> xctest-client.js:272:14 [master] pid:7597 killing runnerProc pid: 7951
>> macaca-ios.js:360:10 [master] pid:7597 iOS driver cleaned up.
>> session.js:80:12 [master] pid:7597 Delete session, sessionId: a7306ba1-c480-486d-9502-a8637a5fcb06
>> responseHandler.js:47:14 [master] pid:7597 Send HTTP Respone to Client: {"sessionId":"a7306ba1-c480-486d-9502-a8637a5fcb06","status":0}
>> xctest-client.js:107:16 [master] pid:7597 simulator log process exit with code: null, signal: SIGKILL
>> xctest-client.js:181:14 [master] pid:7597 xctest client exit with code: null, signal: SIGKILL

* **Macaca Version**:
  1.1.21
* **Macaca Doctor Logs**:

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/test/Documents/android-sdk`
  Platforms is set to `/Users/test/Documents/android-sdk/platforms/android-24`
  Android tools is set to `/Users/test/Documents/android-sdk/tools/android`
  ADB tool is set to `/Users/test/Documents/android-sdk/platform-tools/adb`

  Installed driver list:

  android: 1.1.16 [out-of-date]
  ios: 1.0.54

* **Operate System**:
MacOS 10.12
* **Programming Language**:
Java

**Comment by xudafeng** [comment]
请升级驱动 https://github.com/alibaba/macaca/issues/487

**Comment by xudafeng** [comment]
@Yinxl Java 端添加一下新keycode映射即可支持 HomeScreen 按键

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/487
