### ISSUE TITLE
IOS端实体按键模拟

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#480]
请教，IOS端能否实现实体按键，实现对home键、音量键的控制。
如果能实现home键切换APP到后台，又该如何回到APP界面。

**Comment by xudafeng** [comment]
@zsmjluo 请升级新版驱动，可实现home按键。切回可以考虑重新init

https://github.com/alibaba/macaca/issues/487

**Comment by zsmjluo** [comment]
@xudafeng 感谢！已升级使用确认home按键可行。但是重新init会重启app，我的需求是执行前后台切换，不想要重置。有没有更好的建议或支持方案？

**Comment by xudafeng** [comment]
@zsmjluo  暂时还没想到
