### ISSUE TITLE
物理键keys编码映射规范

### ISSUE THREAD

**Issue by yaniswang** [alibaba/macaca#487]
相关参考文档：
=============

W3C规范：https://w3c.github.io/webdriver/webdriver-spec.html
Android官方按键定义：https://developer.android.com/reference/android/view/KeyEvent.html#KEYCODE_SPACE

PC现有编码映射逻辑
-------------

* `\uE002`	"HELP" => `259 (0x00000103)`
* `\uE003`	"BACK_SPACE" => `67 (0x00000043)`
* `\uE004`	"TAB" => `61 (0x0000003d)`
* `\uE005`	"CLEAR" => `28 (0x0000001c)`
* `\uE007`	"ENTER" => `66 (0x00000042)`
* `\uE008`	"SHIFT" => `59 (0x0000003b)`
* `\uE009`	"CONTROL" => `113 (0x00000071)`
* `\uE00A`	"ALT" => `57 (0x00000039)`
* `\uE00B`	"PAUSE" => `121 (0x00000079)`
* `\uE00C`	"ESCAPE" =>  `111 (0x0000006f)`
* `\uE00E`	"PAGE_UP" => `92 (0x0000005c)`
* `\uE00F`	"PAGE_DOWN" => `93 (0x0000005d)`
* `\uE010`	"END" => `123 (0x0000007b)`
* `\uE011`	"HOME" => `122 (0x0000007a)`
* `\uE012`	"ARROW_LEFT" => `21 (0x00000015)`
* `\uE013`	"ARROW_UP" => `19 (0x00000013)`
* `\uE014`	"ARROW_RIGHT" => `22 (0x00000016)`
* `\uE015`	"ARROW_DOWN" => `20 (0x00000014)`
* `\uE016`	"INSERT" => `124 (0x0000007c)`
* `\uE017`	"DELETE" => `112 (0x00000070)`
* `\uE031`	"F1" => `131 (0x00000083)`
* `\uE032`	"F2" => `132 (0x00000084)`
* `\uE033`	"F3" => `133 (0x00000085)`
* `\uE034`	"F4" => `134 (0x00000086)`
* `\uE035`	"F5" => `135 (0x00000087)`
* `\uE036`	"F6" => `136 (0x00000088)`
* `\uE037`	"F7" => `137 (0x00000089)`
* `\uE038`	"F8" => `138 (0x0000008a)`
* `\uE039`	"F9" => `139 (0x0000008b)`
* `\uE03A`	"F10" => `140 (0x0000008c)`
* `\uE03B`	"F11" => `141 (0x0000008d)`
* `\uE03C`	"F12" => `142 (0x0000008e)`
* `\uE03D`	"META" => `117 (0x00000075)`

Android 编码映射逻辑
--------------

* `\uE101` "POWER 电源键" =>  `26 (0x0000001a)`
* `\uE102` "VOLUME_UP 音量加" => `24 (0x00000018)`
* `\uE103` "VOLUME_DOWN 音量减" => `25 (0x00000019)`
* `\uE104` "VOLUME_MUTE 禁音" => `164 (0x000000a4)`
* `\uE105` "HOME_SCREEN HOME键" => `3 (0x00000003)`
* `\uE106` "BACK BACK键" => `4 (0x00000004)`
* `\uE107` "MENU MENU键" => `82 (0x00000052)`
* `\uE108` "CAMERA 拍照键" => `27 (0x0000001b)`
* `\uE109` "CALL 电话键" => `5 (0x00000005)`
* `\uE10A` "END_CALL 结束电话键" => `6 (0x00000006)`
* `\uE10B` "SEARCH 搜索键" => `84 (0x00000054)`
* `\uE10C` "DPAD_LEFT 导航左键" => `21 (0x00000015)`
* `\uE10D` "DPAD_UP 导航上键" => `19 (0x00000013)`
* `\uE10E` "DPAD_RIGHT 导航右键" => `22 (0x00000016)`
* `\uE10F` "DPAD_DOWN 导航下键" => `20 (0x00000014)`
* `\uE110` "DPAD_CENTER 导航确定键" => `23 (0x00000017)`

iOS物理键编码规范
=============

* `\uE105` "HOME_SCREEN HOME键"

**Comment by xudafeng** [comment]
https://github.com/macacajs/webdriver-keycode/commit/c32ceabc205905714a315119fad529a260b75255 @CodeToSurvive1 @yaniswang

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/commit/df4a0aba8ca9893d124ec12eb18c656d09efeb72

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-ios/commit/6c367c125adb1f8d1796644dcec800e950989bee

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/sample-nodejs/commit/4c515289f385ecd1393cefa99229ef4a3d5ee827

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-ios/commit/fd6b6e4857240e098f50270baca052691c026eb0

**Comment by xudafeng** [comment]
https://github.com/macacajs/uiautomator-client/commit/ee16f79d45a82f15295b07afa75ff9006ea5fc2a

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/460

**Comment by xudafeng** [comment]
UIAutomator setText 可能会有丢失一个字符的情况，可以在使用层兼容

https://android.googlesource.com/platform/frameworks/testing/+/master/uiautomator/library/core-src/com/android/uiautomator/core/UiObject.java#595

**Comment by xudafeng** [comment]
```
.keys(`send keys: ${KEY_MAP.HOME_SCREEN}`)
```

**Comment by boyxiaohua** [comment]
electron模拟模拟按键数字8报错，类似编码格式错误：
2017-06-13 15:29:18 Request:http://127.0.0.1:3456/wd/hub/session/ce9f4551-dfa3-4137-a33b-65c83b926aea/keys:{"value":[""]}
2017-06-13 15:29:18 Response:Internal Server Error
代码：
driver.keys(Keycode.NUMPAD8.toString());

**Comment by xudafeng** [comment]
@boyxiaohua 试试这个 https://testerhome.com/topics/12254
