### ISSUE TITLE
Macaca环境配置问题-uiautomator-bootstrap was not found ,please check your Android Env

### ISSUE THREAD

**Issue by Yinxl** [alibaba/macaca#488]
* **Macaca Version**:1.2.0

* **Macaca Doctor Logs**:

* **Operate System**:Mac

* **Programming Language**:Java

报错：uiautomator-bootstrap was not found ,please check your Android Env
![error.jpg](http://wx3.sinaimg.cn/large/6b65a607gy1fdu8bp2scuj20vu0gu7pf.jpg)

**Comment by Yinxl** [comment]
**原因** 
出现这个问题的同学大部分是因为用最新的Android studio配置了Android sdk,而最新的Android studio更改了打包方式，不再支持ant，从而导致了失败。
 **解决方案**
1. $ brew install android-sdk
2. 配置ANDROID_HOME环境变量
eg: export ANDROID_HOME = /usr/local/opt/android-sdk
3. 打开sdkManager安装对应的platform以及build tool
sdkManager打开路径：$ANDROID_HOME/tools/android sdk
eg:usr/local/opt/android-sdk/tools/android sdk
打开sdkManager如下选择API 23以及对应的buildTools进行安装：
![sdkManager](http://wx4.sinaimg.cn/large/6b65a607gy1fdu8rvwufxj211y156tkm.jpg)

点击install,安装完毕后重装macaca-android(npm i -g macaca-android)就可以解决问题了

**Comment by yushuanggui** [comment]
brew install android-sdk 安装不了呢，有什么解决办法吗
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
ansible-lint               bandcamp-dl                ck
==> Updated Formulae
cargo-completion           googler                    terragrunt
cpanminus                  kobalt

Error: No available formula with the name "android-sdk" 
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
sh267s-MacBook-Air:node_modules sh267$
