### ISSUE TITLE
macaca 对于浏览器弹出框或者JS弹出框无法切换操作

### ISSUE THREAD

**Issue by wangpengfei100** [alibaba/macaca#489]
* **Macaca Version**:1.2.0

* **Macaca Doctor Logs**:

* **Operate System**:chrome

* **Programming Language**:JAVA

![sp20170321_111635](https://cloud.githubusercontent.com/assets/26562987/24133327/0f9528f0-0e37-11e7-9ee3-d8d604bc35a4.png)

**Comment by wangpengfei100** [comment]
在使用macaca进行自动化测试的时候，输入url之后，弹出的用户密码框无法定位，macaca好像也没有对应的方法去解决这个问题

**Comment by xudafeng** [comment]
参考alert解决办法 

https://github.com/macaca-sample/sample-nodejs/blob/master/macaca-test/desktop-browser-sample.test.js
