### ISSUE TITLE
macaca-test-sample PC执行macaca run无反应

### ISSUE THREAD

**Issue by sokmoon** [alibaba/macaca#49]
Macaca Version:1.0.24

Macaca Doctor: node version:4.4.4

Platform:Windows, 32-bit.

macaca 安装成功后执行macaca-test-sample的PC段 make test-pc后显示“macaca不是内部或外部命令”是怎么回事啊？
如果直接执行“macaca run --verbose -d ./macaca-test/macaca-desktop-sample.test.js” 则根本没有反应。
![image](https://cloud.githubusercontent.com/assets/19318607/15203362/5bf6c62a-1835-11e6-9461-9c51b2feece1.png)

**Comment by legendsnow** [comment]
macaca 没有安装好，先用macaca doctor检查一下，是否安装成功

**Comment by sokmoon** [comment]
![image](https://cloud.githubusercontent.com/assets/19318607/15204830/987bf4e4-1844-11e6-82a4-8b2190bb39f2.png)

**Comment by xudafeng** [comment]
@sokmoon win 暂时不提供技术支持，可以更换 Linux 或 osx

**Comment by xudafeng** [comment]
已支持windows https://testerhome.com/topics/4941
