### ISSUE TITLE
怎么实现列表滑动搜索功能

### ISSUE THREAD

**Issue by whitiancai** [alibaba/macaca#490]
* **Macaca Version**:1.20

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-24`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `H:\apache-ant-1.9.6`

  Installed driver list:

  android: 1.1.25 
  chrome: 1.0.5

* **Operate System**:win7 64bit

* **Programming Language**:node 

判断当前页面是否存在某个元素之后滑动一段距离再次判断，重复该操作直到找到该元素。
滑动使用drag,判断元素是否存在用hasElementByName，
但是不知道怎么重复执行直到找到元素。
求解。

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/webdriver-client/blob/master/lib/webdriver-client.js#L118
