### ISSUE TITLE
如何在回调中添加同步操作

### ISSUE THREAD

**Issue by whitiancai** [alibaba/macaca#491]
* **Macaca Version**:1.2.0

* **Macaca Doctor Logs**:macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-24`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `H:\apache-ant-1.9.6`

  Installed driver list:

  android: 1.1.27
  chrome: 1.0.5

* **Operate System**:win7 64bit

* **Programming Language**:nodejs

如何在回调中添加同步操作。
比如
elementsByClassName("xxx")
.then(function(els){
  //同步操作，对els中每一个元素按顺序做操作，全部完成之后再往下执行，怎么写？？
})
.elementByName("xxx")
.click()

**Comment by xudafeng** [comment]
return promise
