### ISSUE TITLE
set_implicitly_wait 方法不可用

### ISSUE THREAD

**Issue by ythinker** [alibaba/macaca#492]
* **Macaca Version**: 1.2.0

* **Operate System**:  mac 10.12

* **Programming Language**: Python

`driver.set_implicitly_wait(10)` 

经过多次尝试，一直没有成功使用！用一直没成功；

请问此方法是否可用？

**Comment by xudafeng** [comment]
.sleep

**Comment by ythinker** [comment]
@xudafeng    不能用 set_implicitly_wait 智能等待吗？  只能用 sleep ？

**Comment by xudafeng** [comment]
@zenzhu set_implicitly_wait 这个api不是用sleep替代了吗
