### ISSUE TITLE
在调用滑动，输入文字等api时press时间过长

### ISSUE THREAD

**Issue by whitiancai** [alibaba/macaca#495]
* **Macaca Version**:1.2.0

* **Macaca Doctor Logs**:
$ macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-24`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `H:\apache-ant-1.9.6`

  Installed driver list:

  android: 1.1.27 [out-of-date]
  chrome: 1.0.5

* **Operate System**:win7 64bit

* **Programming Language**:nodejs

@xudafeng 
在调用driver.touch('drag',{xxx})、sendKeys(xx)等api时会出现press时间过长导致触发控件的长按事件。
如何缩短press时间来避免出现长按事件？
在UC搜索文章和订阅号界面调用elementsByClassName('android.widget.EditText')会导致返回到上一个界面，请问这个是什么原因。

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/366

**Comment by xudafeng** [comment]
update driver
