### ISSUE TITLE
macaca怎么获取toast信息的内容?

### ISSUE THREAD

**Issue by wynanwong** [alibaba/macaca#496]
* **Macaca Version**: 1.2.0

* **Macaca Doctor Logs**:

* **Operate System**: mac 10.12.3

* **Programming Language**: nodejs

@xudafeng macaca怎么获取toast信息的内容?API文档看了一遍，没看到相应的方法。

**Comment by dharmakrish6** [comment]
@wynanwong 
Toast message will be dynamically created by the OS .There will be no locators for Toast messages element. The only solution , you can compare the images before toast and after Toast. But still getting content from Images is one more problem. (Toast消息将由OS动态创建。Toast消息元素将不会有定位符。唯一的解决方案，您可以比较吐司之前和之后的图像。但仍然从图像获取内容还有一个问题。)

**Comment by xudafeng** [comment]
try this https://macacajs.github.io/computer-vision
