### ISSUE TITLE
executing desktop test in chrome browser throws error.

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#498]
This is the error log I get -

`>> responseHandler.js:11:12 [master] pid:16257 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/window/current/size, jsonBody: {}
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:23:14 [master] pid:16257 Send HTTP Respone to Client: 404 Not Found
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:16257 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/window/current/size, jsonBody: {}
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:23:14 [master] pid:16257 Send HTTP Respone to Client: 404 Not Found
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> responseHandler.js:11:12 [master] pid:16257 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"desktop","platform":"desktop","browserName":"chrome","version":"","idleTimeout":180,"javascriptEnabled":true}}
>> session.js:47:10 [master] pid:16257 Creating session, sessionId: d1afc3cc-47d3-46f1-a487-3ce68ed2da9c.
>> chromedriver bin path: /Users/preethi/Documents/QA-Automation/node_modules/macaca-chrome/node_modules/macaca-chromedriver/exec/chromedriver
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:16257) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
>> Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:52:14 [master] pid:16257 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body: 
>> proxy.js:58:16 [master] pid:16257 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.11.5\"}}}"
>> proxy.js:52:14 [master] pid:16257 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"platformName":"desktop","platform":"desktop","browserName":"chrome","version":"","idleTimeout":180,"javascriptEnabled":true,"show":true}}
Error: chromedriver proxy error with: Error: socket hang up
    at Request.request [as _callback] (/Users/preethi/Documents/QA-Automation/node_modules/macaca-chrome/node_modules/macaca-chromedriver/lib/proxy.js:56:25)
    at self.callback (/Users/preethi/Documents/QA-Automation/node_modules/macaca-chrome/node_modules/request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/preethi/Documents/QA-Automation/node_modules/macaca-chrome/node_modules/request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:345:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
>> macaca-chromedriver.js:123:18 [master] pid:16257 chromedriver exit with code: null, signal: SIGSEGV
>> proxy.js:52:14 [master] pid:16257 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"platformName":"desktop","platform":"desktop","browserName":"chrome","version":"","idleTimeout":180,"javascriptEnabled":true,"show":true}}
Error: chromedriver proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9515
    at Request.request [as _callback] (/Users/preethi/Documents/QA-Automation/node_modules/macaca-chrome/node_modules/macaca-chromedriver/lib/proxy.js:56:25)
    at self.callback (/Users/preethi/Documents/QA-Automation/node_modules/macaca-chrome/node_modules/request/request.js:199:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/Users/preethi/Documents/QA-Automation/node_modules/macaca-chrome/node_modules/request/request.js:821:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
`

and this is my command -
`platform=desktop browserName='chrome' $(npm bin)/macaca run -d ./WebTests/Editor_Basic/CP_02_Editor-basic-GoogleMap.js --verbose
`

I try to run in Mac OS 10.11.5 and Google chrome version 57.0.2987.133

**Comment by xudafeng** [comment]
https://travis-ci.org/macaca-sample/sample-nodejs

**Comment by mpreethi90** [comment]
@xudafeng  thank you for the reply. But in the travis build you provided, the test was executed in electron browser. For me electron works fine,problem is with Google Chrome browser only. Kindly assist

**Comment by dharmakrish6** [comment]
@mpreethi90 as per your logs, the chrome version `ChromeDriver 2.20.353124
Update the chrome driver to 2.28 and try again. `

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-chromedriver#custom-version
