### ISSUE TITLE
macaca 测试安卓报错，试了下macaca Android安装有报错，用的指令cnpm install macaca-android -g

### ISSUE THREAD

**Issue by huangwnebin** [alibaba/macaca#503]
![image](https://cloud.githubusercontent.com/assets/26835338/24579907/2eedc31c-1731-11e7-999a-c45be7754533.png)

* **Macaca Version**:
![image](https://cloud.githubusercontent.com/assets/26835338/24579911/489eb000-1731-11e7-9513-f952b0356a85.png)

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by huangwnebin** [comment]
有没别的办法安装macaca Android？

**Comment by huangwnebin** [comment]
找到这个文件.npmrc，然后删掉就可以了,你的npm的config乱掉了

**Comment by mijiawei** [comment]
@huangwnebin 
想请问下.npmrc在哪个目录下的？
