### ISSUE TITLE
iOS App-inspector 真机启动不起来，老是报错“ Error: socket hang up”

### ISSUE THREAD

**Issue by AppleZou** [alibaba/macaca#505]
## Update Xcode To 8.3

https://travis-ci.org/macaca-sample/sample-nodejs

---

不知道为什么,我用macaca环境就没稳定过，之前好好的，放在那里什么都没动，过段时间在来运行就运行不起来了，最近就是启动app_inspector就老是报错，之前还重启手机跟电脑管用，现在是什么招都用了，就是起不来，在这个环境问题上乱费太多时间了
$ app-inspector -u 43d388600e6a6f0ca35ed991f73ae96eb30f59aa --verbose
>> request.js:24:12 [master] pid:441 get remote update info failed.
>> server.js:16:12 [master] pid:441 server start with config:
 { port: 5678,
  verbose: true,
  udid: '43d388600e6a6f0ca35ed991f73ae96eb30f59aa',
  ip: '192.168.1.106',
  host: 'lanthanum-4.local',
  loaded_time: '2017-04-04 21:45:47' }
>> app-inspector.js:42:10 [master] pid:441 server start at: http://192.168.1.106:5678
>> xctest-client.js:56:14 [master] pid:441 project path: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:441 xcode version: 8.2.1
>> WebDriverAgent version: 1.1.4
>> xctest-client.js:170:14 [master] pid:441 2017-04-04 21:45:50.443 xcodebuild[453:4771]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/apple/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/062435A3-8925-481C-812E-DC0467380E0C/Session-app-inspector-2017-04-04_214550-2RVm3R.log

>> xctest-client.js:171:14 [master] pid:441 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:441 2017-04-04 21:45:50.444 xcodebuild[453:4769] [MT] IDETestOperationsObserverDebug: (BD2E2A4A-22E5-4FB5-8A56-D5EF120137BC) Beginning test session app-inspector-BD2E2A4A-22E5-4FB5-8A56-D5EF120137BC at 2017-04-04 21:45:50.442 with Xcode 8C1002 on target <DVTiOSDevice: 0x7ff9fc92b9a0> {
		deviceSerialNumber:         C39MDH81FRC5
		identifier:                 43d388600e6a6f0ca35ed991f73ae96eb30f59aa
		deviceClass:                iPhone
		deviceName:                 BTCC iPhone5
		deviceIdentifier:           43d388600e6a6f0ca35ed991f73ae96eb30f59aa
		productVersion:             10.0.1
		buildVersion:               14A403
		deviceSoftwareVersion:      10.0.1 (14A403)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12088623104
		deviceAvailableCapacity:    10143289344
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7ff9f9e64840 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.0.1 (14A403))

>> xctest-client.js:171:14 [master] pid:441 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:441 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/987c650d26d3ba3f1b37f9548901653a/43d388600e6a6f0ca35ed991f73ae96eb30f59aa/app-inspector-Runner.app
state->new_bundle: /Users/apple/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Build/Products/Debug-iphoneos/app-inspector-Runner.app
state->dst_bundle: /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/app-inspector-Runner.app.mtELtl/app-inspector-Runner.app_sparse.ipa/Payload//app-inspector-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/app-inspector-Runner.app.mtELtl/app-inspector-Runner.app_sparse.ipa

>> xctest-client.js:171:14 [master] pid:441 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:441 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/app-inspector-Runner.app.mtELtl/app-inspector-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/5z/hjq6vzl133sf0kjt5fhv4nb80000gp/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/app-inspector-Runner.app.mtELtl/app-inspector-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:171:14 [master] pid:441 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> proxy.js:56:14 [master] pid:441 Proxy: /session:POST to http://127.0.0.1:8900/session:POST with body: {"desiredCapabilities":{}}
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> proxy.js:62:22 [master] pid:441 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:257:14 [master] pid:441 Fail to start xctest: Error: socket hang up
>> xctest-client.js:265:14 [master] pid:441 killing deviceLogProc pid: 450
>> xctest-client.js:270:14 [master] pid:441 killing runnerProc pid: 453
>> xctest-client.js:276:14 [master] pid:441 killing iproxyProc pid: 452
>> app-inspector:66:44 [master] pid:441 Error: socket hang up
    at createHangUpError (_http_client.js:252:15)
    at Socket.socketOnEnd (_http_client.js:344:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
>> xctest-client.js:145:16 [master] pid:441 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:209:14 [master] pid:441 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:181:14 [master] pid:441 xctest client exit with code: null, signal: SIGKILL

下面是macaca  doctor的贴图
![screen shot 2017-04-04 at 21 53 10](https://cloud.githubusercontent.com/assets/25732354/24660088/2e12c0bc-1981-11e7-9919-eb557f0f1678.png)

**Comment by ltkaczyk** [comment]
I have the same issue.

Why you block using previous versions? Currently I have to reinstall macaca doctor, resign WebDriverAgent and finally I face the above error. Please allow to use previous stable versions :(.

**Comment by AppleZou** [comment]
You mean i switch to the  previous stable version can solve this issue?

**Comment by ltkaczyk** [comment]
Yes. The previous version (app-inspector 1.2.22) worked without this issue.  I had to do an update because the alert appeared and there wasn't a possibility to use the old one.

**Comment by tangxue-snow** [comment]
I met the same issue after updating both my IOS to 10.3 and inspector to 1.2.23.
I think that is caused by the WebDriverAgent update but inspector 1.2.23 have not do the patch. Maybe we need to wait for newest version of inspector

**Comment by xudafeng** [comment]
update your xcode to vesion 8.3

**Comment by tangxue-snow** [comment]
Yes, my Xcode have been update to 8.3, otherwise WebDiverAgent will failed. 
Can you success to launch the IOS 10.3 device with inspector?

**Comment by ltkaczyk** [comment]
Unfortunately, I cannot update XCode at the moment :(. Please consider using different versions not only the latest one.
