### ISSUE TITLE
运行uirecorder start 启动chrome之后会提示“请停止以开发者模式运行的扩展程序”

### ISSUE THREAD

**Issue by etiaxie** [alibaba/macaca#508]
macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v4.6.0

  Android checklist:

  JAVA version is `1.7.0_15`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.7.0_15`
  ANDROID_HOME is not set
  ANT_HOME is not set

  Installed driver list:

  android: 1.0.39 [out-of-date]
  chrome: 1.0.5
  electron: 1.1.4 [out-of-date]

chrome 版本56.0.2924.87

运行uirecorder start 启动chrome之后会提示“请停止以开发者模式运行的扩展程序”
请问怎么让chrome可以不提示

**Comment by p2227** [comment]
https://github.com/alibaba/macaca/issues/266

**Comment by p2227** [comment]
你能在window环境下跑吗？忽略“请停止以开发者模式运行的扩展程序”这个问题

**Comment by huangwnebin** [comment]
chrome的版本太高了不支持，你下载个低版本点的试试。

**Comment by p2227** [comment]
@huangwnebin 有没有低版本的下载连接？我都是直接连接到google更新最新的

**Comment by huangwnebin** [comment]
百度搜索什么版本都有

**Comment by yaniswang** [comment]
更新最新版uirecorder，已经没有这个问题了

**Comment by p2227** [comment]
> 更新最新版uirecorder，已经没有这个问题了

请问如何更新？是更新macaca-cli还是macaca-driver还是什么？

**Comment by yaniswang** [comment]
tnpm i uirecorder -g
