### ISSUE TITLE
macaca android安装成功了，但是运行官方脚本的时候会报错 InternalServerError: Internal Server Error

### ISSUE THREAD

**Issue by huangwnebin** [alibaba/macaca#509]
macaca android安装成功了，但是运行官方脚本的时候会报错 InternalServerError: Internal Server Error
![image](https://cloud.githubusercontent.com/assets/26835338/24746712/ba628194-1aec-11e7-9f2b-ee4cc392ceae.png)

* **Macaca Version**:

![image](https://cloud.githubusercontent.com/assets/26835338/24746851/165407ca-1aed-11e7-93d1-09cab0049d93.png)

* **Macaca Doctor Logs**:
![image](https://cloud.githubusercontent.com/assets/26835338/24746831/0203f870-1aed-11e7-963c-cb8fb6992a3d.png)
![image](https://cloud.githubusercontent.com/assets/26835338/24746837/0aabacc0-1aed-11e7-9f61-57a2255ca348.png)

* **Operate System**:
win7
* **Programming Language**:
java/Python

**Comment by huangwnebin** [comment]
一直搞不定，我们公司有5台电脑，都报一样的错误

**Comment by sachinGirish** [comment]
![path issue](https://cloud.githubusercontent.com/assets/13481486/24751734/4db4f1c0-1ae8-11e7-965b-8d5a39ec7ec3.png)
It looks like path issue in logs (/ and \)

**Comment by huangwnebin** [comment]
@sachinGirish how to fix it？

**Comment by sachinGirish** [comment]
@huangwnebin Try to avoid of installations of files in "program files"  because few tools do not recognise spaces try in another drive and set the path for the program.

Now change your SDK file and path on another drive then try to run.

**Comment by huangwnebin** [comment]
![image](https://cloud.githubusercontent.com/assets/26835338/24850626/5e447f56-1e03-11e7-81b2-953222d2875c.png)
@sachinGirish I have change the installation path without ‘’program files‘’，but the issue always...

**Comment by dharmakrish6** [comment]
@huangwnebin  try to run `adb devices` command manually If that is only failed then problem with android SDK configuration.

**Comment by bensonday** [comment]
我是在iOS真机测试的时候碰到了这个问题，当时我开了VPN，而且手机网络与Mac的网络不是同一个。切换回来就没有这个问题了。

**Comment by HeartIsBeat** [comment]
I have the same issue with real device. How to fix?
macaca-android\node_modules\_uiautomatorwd@1.0.27@uiautom  orwd\app\build\outputs\apk\app-debug.apk': No such file or directory
![image](https://cloud.githubusercontent.com/assets/20472976/26099934/e34c6372-3a5e-11e7-9f65-350594adf4d2.png)

**Comment by xudafeng** [comment]
update macaca-android

**Comment by HeartIsBeat** [comment]
macaca-android是 android: 2.0.17版本最新了
macaca也是最新的了2.0.1，还是类似的问题，哎
![image](https://cloud.githubusercontent.com/assets/20472976/26663836/0f353f28-46c0-11e7-9be5-3ff8d4b7f02e.png)
