### ISSUE TITLE
ios java版本press操作突然无法使用

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#510]
之前一直用的好好的，今天用的时候发现不行了，升级xcode8.3，macaca及驱动全部重装仍然不行。
使用方法如下：
JSONObject timeoutJSON = new JSONObject();
timeoutJSON.put("duration",  20);
element.touch("press", timeoutJSON);

错误日志如下，提示：An unknown server-side error occurred while processing the command.

>> responseHandler.js:11:12 [master] pid:1623 Recieve HTTP Request from Client[2017-04-07 19:57:07]: method: POST url: /wd/hub/session/55ccdbc0-b713-40b0-bc2c-1e6c0b252e67/actions, jsonBody: {"actions":[{"duration":"20","type":"press","element":"B2DFC4A6-A4ED-4C48-A4BC-E3B4EBAFA761"}]}
>> proxy.js:56:14 [master] pid:1623 Proxy: /wd/hub/session/temp/uiaElement/B2DFC4A6-A4ED-4C48-A4BC-E3B4EBAFA761/touchAndHold:POST to http://127.0.0.1:8900/session/74AA2EC2-1EDC-4C85-A047-77AF6F0B9B44/uiaElement/B2DFC4A6-A4ED-4C48-A4BC-E3B4EBAFA761/touchAndHold:POST with body: {"duration":"20"}
>> proxy.js:84:20 [master] pid:1623 Got response with status 200: {"value":"Unhandled endpoint: /session/74AA2EC2-1EDC-4C85-A047-77AF6F0B9B44/uiaElement/B2DFC4A6-A4ED-4C48-A4BC-E3B4EBAFA761/touchAndHold -- http://127.0.0.1:8900/ with parameters {\n    wildcards =...
# ### **>> responseHandler.js:54:12 [master] pid:1623 Send Error Respone to Client: UnknownError: An unknown server-side error occurred while processing the command.
>> responseHandler.js:60:14 [master] pid:1623 UnknownError: An unknown server-side error occurred while processing the command.**

**Comment by zsmjluo** [comment]
@xudafeng 挺着急，麻烦帮忙定位下。

**Comment by zsmjluo** [comment]
应该是升级macaca的原因

**Comment by zsmjluo** [comment]
@xudafeng drag同样无法使用了。使用方法如下：
		JSONObject locationObj = new JSONObject();
		locationObj.put("x", toX);
		locationObj.put("y", toX);
		el.touch("drag", locationObj);
这个问题有在修复吗？

**Comment by lukcyjane** [comment]
我使用python调用press也遇到类似的问题，调用方法如下：
`self.driver.wait_for_element_by_xpath('//XCUIElementTypeTable[1]/XCUIElementTypeCell[last()]/XCUIElementTypeOther[1]').touch('press',{'duration': 2})`

报错信息如下：
>responseHandler.js:11:12 [master] pid:2562 Recieve HTTP Request from Client[2017-04-26 11:00:02]: method: POST url: /wd/hub/session/fc90da57-12a3-449f-8a87-8c9d86093ef4/actions, jsonBody: {"actions":[{"duration":2,"type":"press","element":"E6D54D75-E203-4BE8-9C05-C8010FCFF296"}]}
proxy.js:56:14 [master] pid:2562 Proxy: /wd/hub/session/temp/uiaElement/E6D54D75-E203-4BE8-9C05-C8010FCFF296/touchAndHold:POST to http://192.168.200.229:8900/session/7E95ECE1-9903-4236-82DC-EF506D4A474C/uiaElement/E6D54D75-E203-4BE8-9C05-C8010FCFF296/touchAndHold:POST with body: {"duration":2}
 proxy.js:84:20 [master] pid:2562 Got response with status 200: {"value":"Unhandled endpoint: /session/7E95ECE1-9903-4236-82DC-EF506D4A474C/uiaElement/E6D54D75-E203-4BE8-9C05-C8010FCFF296/touchAndHold -- http://192.168.200.229:8900/ with parameters {\n    wildc...
 responseHandler.js:54:12 [master] pid:2562 Send Error Respone to Client: UnknownError: An unknown server-side error occurred while processing the command.
responseHandler.js:60:14 [master] pid:2562 UnknownError: An unknown server-side error occurred while processing the command.
    at actionDelegate.call.then.result (/usr/local/lib/node_modules/macaca-ios/lib/actions.js:121:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)


其他说明：之前此方法可用，昨天升级macaca后就出现问题。

**Comment by SamuelZhaoY** [comment]
已修复 请更新 macaca-ios
