### ISSUE TITLE
怎么在iphone真机上运行safari测试

### ISSUE THREAD

**Issue by k19810703** [alibaba/macaca#513]
请教大神们，怎么在iphone真机上运行safari测试
const iOSSafariOpts = {
  // deviceName: 'iPhone 7',
  // platformName: 'iOS',
  browserName: 'Safari',
  //这里我都填写了正确的信息，考虑到隐私性，这里不写出来，实际没问题
  udid: 'myudid'
};
光写udid就行了么？

运行了出下面这个错
Error: [init({"browserName":"Safari","udid":"myudid","bundleId":"com.apple.mobilesafari"})] The environment you requested was unavailable.

**Comment by dharmakrish6** [comment]
@k19810703 try with this properties
```
platformName: 'iOS',
app: <app_path>,
deviceName: <device_name>,
platformVersion: <version>,
```
