### ISSUE TITLE
如何使用Python在Android下触发回车事件？send_keys(Keys.ENTER)并不生效

### ISSUE THREAD

**Issue by kentzzhang** [alibaba/macaca#515]
* **Macaca Version**:
v1.2.0
* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `C:\Users\kentz.zhang\AppData\Local\Android\android-sdk`
  Platforms is set to `C:\Users\kentz.zhang\AppData\Local\Android\android-sdk\platforms\android-24`
  Android tools is set to `C:\Users\kentz.zhang\AppData\Local\Android\android-sdk\tools\android.bat`
  ADB tool is set to `C:\Users\kentz.zhang\AppData\Local\Android\android-sdk\platform-tools\adb.exe`
  ANT_HOME is set to `C:\apache-ant`

  Installed driver list:

  android: 1.1.22 [out-of-date]
  chrome: 1.0.5
  electron: 1.1.5 [out-of-date]
* **Operate System**:
Win7
* **Programming Language**:
Python

**Comment by kentzzhang** [comment]
暂时只能通过adb shell input keyevent key_code来处理

**Comment by sachinGirish** [comment]
try with .keys('\uE007')

https://macacajs.github.io/wd.py/api.html#module-macaca.keys

**Comment by kentzzhang** [comment]
Thanks, @sachinGirish. But still with no effort.

**Comment by rubyvirus** [comment]
self.driver.keys(macaca.Keys.ENTER.value)
