### ISSUE TITLE
ios真机，server报错

### ISSUE THREAD

**Issue by Handsome2734** [alibaba/macaca#517]
* **Macaca Version**:
1.2.2
* **Macaca Doctor Logs**:

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home`
  ANDROID_HOME is not set

  Installed driver list:

  chrome: 1.0.5
  ios: 1.0.67
* **Operate System**:
osx
* **Programming Language**:
python

启动｀macaca server --verbose`后运行脚本，server报错。
错误信息如下：
```
>> xctest-client.js:263:14 [master] pid:2864 Fail to start xctest: TypeError: this.device.openURL is not a function
>> xctest-client.js:271:14 [master] pid:2864 killing deviceLogProc pid: 2872
>> xctest-client.js:276:14 [master] pid:2864 killing runnerProc pid: 2875
>> xctest-client.js:282:14 [master] pid:2864 killing iproxyProc pid: 2874
>> proxy.js:62:22 [master] pid:2864 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> xctest-client.js:150:16 [master] pid:2864 deviceconsole exit with code: null, signal: SIGKILL
>> xctest-client.js:214:14 [master] pid:2864 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:186:14 [master] pid:2864 xctest client exit with code: null, signal: SIGKILL
```
WebDriverAgent已经重签名了，运行脚本的时候wda会一闪而过。
重签名的方法都是一样的，但是app-inspector就能正常运行，不知道是哪里的问题。

**Comment by Handsome2734** [comment]
补充：我是要拉起Safari，测试网页

**Comment by xudafeng** [comment]
@Handsome2734 模拟器是ok的吗？

**Comment by Handsome2734** [comment]
没仔细试过模拟器……之前试了一次，但是在模拟器启动的时候server就抛错误了，后来就没试过

**Comment by Handsome2734** [comment]
@xudafeng 我今天试了一下xcode 8.2 + iOS 10.2的模拟器，是可以正常打开的
但是xcode 8.2 + iOS 10.1的真机，就报this.device.openURL那个错

**Comment by Handsome2734** [comment]
@xudafeng 
我用vscode attach了macaca server，看到Simulator类是有openURL方法的，但是Device类没有
<img width="207" alt="device" src="https://cloud.githubusercontent.com/assets/5567825/25490711/33bd8d36-2ba0-11e7-9987-9a0479f7bec4.png">
<img width="226" alt="simulator" src="https://cloud.githubusercontent.com/assets/5567825/25490712/33cc8048-2ba0-11e7-91f2-83c9ac5b57a4.png">

**Comment by xudafeng** [comment]
openURL 真机是不能使用的，可以尝试使用bundleidsafari

**Comment by Handsome2734** [comment]
@xudafeng 我加了bundleId，还是报同样的错……
是我desired_caps配置错了么？
``` python
# -*- coding: utf-8 -*-
from macaca import WebDriver

udid_real = 'xx'

desired_caps = {
    'platformName': 'iOS',
    'browserName': 'Safari',
    'udid': udid_real,
    'bundleId': 'com.apple.mobilesafari'
}

server_url = {
    'hostname': '127.0.0.1',
    'port': 3456
}

driver = WebDriver(desired_caps, server_url)

driver.init()

driver.get('http://m.baidu.com')

print driver.title

driver.close()
driver.quit()

```

**Comment by Handsome2734** [comment]
我知道怎么回事了……注掉browserName就好了
操作比较奇怪，和之前selenium+ChromeDriver不一样，但是总算是调通iPhone真机+Safari了……

**Comment by holylousie** [comment]
@Handsome2734   你现在真机还能调Safari吗?  我也遇到同样的问题了，请教一下

**Comment by Handsome2734** [comment]
@holylousie 抱歉刚看到……上面那串代码注掉browserName就可以真机调Safari了
