### ISSUE TITLE
android实现输入之后模拟回车操作失败

### ISSUE THREAD

**Issue by whitiancai** [alibaba/macaca#518]
* **Macaca Version**:1.2.2

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-24`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `H:\apache-ant-1.9.6`

  Installed driver list:

  android: 1.1.34
  chrome: 1.0.5

* **Operate System**:win7 64bit

* **Programming Language**:nodejs

driver.keys('[ADB_INPUT_TEXT]使用ADB中文输入');
driver.keys('[ADB_INPUT_CODE]67'); // delete key
driver.keys('[ADB_INPUT_CHARS]128568,32,67,97,116');
driver.keys('[ADB_EDITOR_CODE]2');

使用以上方法都只是当做普通字符串被写入到输入框中，没有实现删除等操作。是需要引入特殊的库？

it('模拟search事件',function () {
        return driver
            .elementByXPath('//*[@resource-id="xxxx"]')
            .sendKeys('搜索关键字')
            // .keys('[ADB_INPUT_CODE]66')//KEYCODE_ENTER
            //.keys('[ADB_EDITOR_CODE]3')//IME_ACTION_SEARCH
    })

android点击输入法键盘上的搜索按钮是回车(KEYCODE_ENTER)操作，还是搜索(IME_ACTION_SEARCH)操作？

**Comment by whitiancai** [comment]
@xudafeng

**Comment by xudafeng** [comment]
升级

示例
https://github.com/macaca-sample/sample-nodejs/blob/master/macaca-test/wd-extend.js#L56
