### ISSUE TITLE
 无法使用save_screenshot功能

### ISSUE THREAD

**Issue by 18280108415** [alibaba/macaca#519]
最开始使用时save_screenshot可以截图并且保存成功，隔了一周再运行时报异常，代码：self.driver.save_screenshot('.\login.png', quietly=True)
 
报错：
Error: Command failed: D:\autoTest\Android\Android\sdk/platform-tools/adb -s 3
05be8887ce3 pull /data/local/tmp/local/tmp/screenshot.png C:\Users\ADMINI~1\AppD
ata\Local\Temp\macaca-android-screenshot117318-8908-1dn9j5e.lruo6flxr.png
  remote object '/data/local/tmp/local/tmp/screenshot.png' does not exist

      at ChildProcess.exithandler (child_process.js:206:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:877:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by lusiqiao** [comment]
同上
recive: {"cmd":"getTmpDir","args":{}}

return: {"data":{"value":"\/data\/local\/tmp\/local\/tmp","status":0},"success":true}
两层/local/tmp是怎么回事，手机里找不到该目录

**Comment by loftyet** [comment]
可能是个bug

**Comment by xudafeng** [comment]
@loftyet 试着解决一下？

**Comment by lusiqiao** [comment]
有跟进吗？这个问题

**Comment by Archer456** [comment]
driver.takeScreenshot()
	.saveScreenshot("D:\\macaca\\Screenshot\\AndroidAcp.png");	

windows的话 截图路径 要如此 \\ 转义一个\来写  你试一下  我的是java代码

**Comment by xudafeng** [comment]
更新驱动
