### ISSUE TITLE
使用setFrame后，如何退出？API里没有这个命令，求助。

### ISSUE THREAD

**Issue by wumengxue** [alibaba/macaca#523]
使用setFrame后，如何退出？API里没有这个命令，求助。

platformName: 'desktop',
browserName: 'electron'

**Comment by dharmakrish6** [comment]
@wumengxue 
this might be helpful to you. 
**Once you switch to some frame, you have to use window handles to set focus back to main windows** 
```

.frame('frame id/name')
.waitForElementByName('<name>')
.click()
 .windowHandle()
      .then(function (name) {
              driver.window(name)
             })
```
