### ISSUE TITLE
如何获取android控件 android.view.View的文本值

### ISSUE THREAD

**Issue by whitiancai** [alibaba/macaca#524]
* **Macaca Version**:1.2.2

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: H:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_101`
  ANDROID_HOME is set to `D:\sdk`
  Platforms is set to `D:\sdk\platforms\android-24`
  Android tools is set to `D:\sdk\tools\android.bat`
  ADB tool is set to `D:\sdk\platform-tools\adb.exe`
  ANT_HOME is set to `H:\apache-ant-1.9.6`

  Installed driver list:

  android: 1.1.34
  chrome: 1.0.5

* **Operate System**:win 7 64bit

* **Programming Language**:nodejs

有一个页面用app-inspector查看发现文本都不是用的android.widget.TextView而是用的android.view.View，这个怎么获取到文本值？

**Comment by dharmakrish6** [comment]
@whitiancai can you try this
```
driver.waitForElementByName('android.view.view(text)')
.text()
```

**Comment by whitiancai** [comment]
@dharmakrish6 it does not work

**Comment by whitiancai** [comment]
@xudafeng

**Comment by xudafeng** [comment]
使用inspector选择
