### ISSUE TITLE
真机运行各种弹出框处理办法

### ISSUE THREAD

**Issue by cloudcrow** [alibaba/macaca#525]
1.运行脚本，安装apk,不同品牌不同时机会询问安装允许，静默安装等不同提示，如何解决针对各种机型的弹出处理
2.首次运行程序， 会提示GPS使用，信任等弹出提示，如何解决该弹窗问题。

**Comment by dharmakrish6** [comment]
use 

> autoAcceptAlerts: true

**Comment by xudafeng** [comment]
@dharmakrish6 💯

**Comment by huangwnebin** [comment]
为什么我autoAcceptAlerts: true还是没办法自动接受授权，华为mate手机
但是有个奇怪的现象，手机自动锁屏的时候脚本会往下跑，此时解锁就可以正常接受alert
