### ISSUE TITLE
Android 构建方式升级

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#527]
- [x] 构建方式ant -> gradle
- [x] UIAutomatorV1 -> UIAutomatorV2
- [x] 兼容windows

**Comment by yushuanggui** [comment]
我安装了Gradle 3.4.1 ，还是卡在那里，还需要做什么吗？

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/184

**Comment by yushuanggui** [comment]
https://macacajs.github.io/macaca/faq.html 页面404

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/82
