### ISSUE TITLE
执行cnpm i -g macaca-android --save 命令，卡死（window 7、node v4.4.4、npm 2.15.1、macaca 1.2.2）

### ISSUE THREAD

**Issue by yushuanggui** [alibaba/macaca#529]
执行cnpm i -g macaca-android --save 命令，卡死在
[dex] input: C:\Users\shuanggui.yu\AppData\Roaming\npm\node_modules\macaca-android\node_modules\_android-unicode@1.0.11@
android-unicode\bin\classes
      [dex] Converting compiled files and external libraries into C:\Users\shuanggui.yu\AppData\Roaming\npm\node_modules
\macaca-android\node_modules\_android-unicode@1.0.11@android-unicode\bin\classes.dex...

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/527
