### ISSUE TITLE
mac 执行  npm i macaca-android -g 报错

### ISSUE THREAD

**Issue by yushuanggui** [alibaba/macaca#531]
Total time: 0 seconds
Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/script/build.js:15
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "macaca-android" "-g"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! android-unicode@1.0.11 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the android-unicode@1.0.11 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log
npm ERR! code 1

sh267s-MacBook-Air:node_modules sh267$ macaca doctor

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.2

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/sh267/Library/Android/sdk`
  Platforms is set to `/Users/sh267/Library/Android/sdk/platforms/android-22`
  Android tools is set to `/Users/sh267/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/sh267/Library/Android/sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.53 [out-of-date]

**Comment by LarkinZero** [comment]
我有和你一样的错误，没解决
![Imgur](http://i.imgur.com/23tb4Q4.png)

**Comment by Archer456** [comment]
https://testerhome.com/topics/6507      参照这个来吧     
 1 nodejs 用LTS目前官方最新的LTS版本是 6.10.2     用 tar包方式安装
2 设定npm config set registry http://registry.npm.taobao.org   淘宝源
3 网络条件很重要，找个靠谱的VPN或国外代理 或者fan qiang 或者你开手机4G（中国移动最好）热点 让你的win10只连接该热点wifi ，再执行npm i

**Comment by yushuanggui** [comment]
@Archer456 非常感谢，按照你给的链接，重新安装了android sdk，成功了😄🙏🙏

**Comment by LarkinZero** [comment]
```
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> android-unicode@1.0.11 install /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode
> node ./script/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
Buildfile: /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/build.xml
BUILD FAILED
/usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/build.xml:81: Cannot find /usr/local/share/android-sdk/tools/ant/build.xml imported from /usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/build.xml

Total time: 0 seconds

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib/node_modules/macaca-android/node_modules/android-unicode/script/build.js:15
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "i" "macaca-android" "-g"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! android-unicode@1.0.11 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the android-unicode@1.0.11 install script 'node ./script/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the android-unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs android-unicode
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls android-unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Larkin/.npm/_logs/2017-05-03T08_07_35_790Z-debug.log
```

**Comment by Archer456** [comment]
build出错的话  
npm cache clean  清理一切相关npm缓存  重新执行npm i 命令

**Comment by Handsome2734** [comment]
我也遇到了这个问题，提示android sdk路径下找不到ant/build.xml，但是我的sdk是从Android Studio里装的，构建Android App啥的都是可以的

**Comment by Archer456** [comment]
参考   
https://testerhome.com/topics/6507

https://testerhome.com/topics/8618   这两个
