### ISSUE TITLE
官方文档快速上手中的视频中执行的脚本名字跟目前实际的不符合；

### ISSUE THREAD

**Issue by cherrycumtb** [alibaba/macaca#532]
* **Macaca Version**:  1.2.2

* **Macaca Doctor Logs**:

  macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.8.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/Cherry/Development/sdk`
  Platforms is set to `/Users/Cherry/Development/sdk/platforms/android-20`
  Android tools is set to `/Users/Cherry/Development/sdk/tools/android`
  ADB tool is set to `/Users/Cherry/Development/sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.67

* **Operate System**:

mac os 10.12.4

* **Programming Language**:

中文

**Comment by zhuyali** [comment]
看Makefile
