### ISSUE TITLE
获取微信webview的context No such session

### ISSUE THREAD

**Issue by sionmike** [alibaba/macaca#536]
* **Macaca Version**:1.2.2

* **Macaca Doctor Logs**:
macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.8.0

  iOS checklist:

  Xcode is installed at: `/Library/Developer/CommandLineTools`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/edz/Downloads/android-sdk-macosx`
  Platforms is set to `/Users/edz/Downloads/android-sdk-macosx/platforms/android-22`
  Android tools is set to `/Users/edz/Downloads/android-sdk-macosx/tools/android`
  ADB tool is set to `/Users/edz/Downloads/android-sdk-macosx/platform-tools/adb`

  Installed driver list:

  android: 1.1.34
  chrome: 1.0.5
  electron: 1.1.6
  ios: 1.0.67

* **Operate System**:mac os 10.12

* **Programming Language**:python

获取微信的context脚本报no such session  ，macaca server 里
chromedriver starting success.
chromedriver ready with: {"sessionId":null,"status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.12.3 x86_64)"}}

**Comment by dharmakrish6** [comment]
Chrome driver should be updated . Run the following command 
`CHROMEDRIVER_VERSION=2.29 npm i macaca-chromedriver -g`

**Comment by sionmike** [comment]
i have ran this command to upgrate chromedriver, but it still shows chromedriver=2.20.353124,

**Comment by pengchenglin** [comment]
微信的webview是chrome53的  要下载支持的chrome版本  2.29Supports Chrome v56-58
下载chromedriver2.26就好了
http://chromedriver.storage.googleapis.com/index.html?path=2.26/
