### ISSUE TITLE
app-inspector 从1.2.23 升级到1.2.25后，无法使用，提示： Error: connect ECONNREFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by tlllly** [alibaba/macaca#541]
* **Macaca Version**: 1.2.3

* **Macaca Doctor Logs**: 
  macaca-doctor version: 1.1.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 1.0.67

* **Operate System**: macOS Sierra 10.12.4

* **Programming Language**: English
![Uploading {21067C27-EFE5-A527-350D-A4D620EE271C}.png…]()

app-inspector 从1.2.23升级到1.2.25后，无法连接上手机，错误提示如下：
>> xctest-client start with port: 8001
>> XCTestWD version: 1.0.3
undefined
>> iOS device started: 245281e541a9bf674a8da38021681510398ebfd6
>> inspector start at: http://10.112.23.147:5678
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1018:11)
      at exports._exceptionWithHostPort (util.js:1041:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by ligaopan** [comment]
我也碰到这样的问题了，不升级还玩不了

**Comment by zsmjluo** [comment]
@xudafeng 能不能修改成不强制升级？一出问题所有用户都死翘翘，全部都得等你们解决问题。1.2.23好好的，升级1.2.27后同样不行了。

**Comment by upengfei** [comment]
@xudafeng 建议不要强制升级，可以给我出提示。。你们这样什么都玩不了了。。。

**Comment by upengfei** [comment]
@xudafeng  建议不要强制升级，不然一出问题，谁都玩不了了。。。

**Comment by upengfei** [comment]
Andriod:


{ Error: Command failed: D:\android\android-sdk-windows/platform-tools/adb -s 17
a8606b push C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspecto
r\node_modules\._uiautomatorwd@1.0.2@uiautomatorwd\app\build\outputs\apk\app-deb
ug.apk /data/local/tmp/undefined

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'D:\\android\\android-sdk-windows/platform-tools/adb -s 17a8606b push C:\
\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\app-inspector\\node_
modules\\._uiautomatorwd@1.0.2@uiautomatorwd\\app\\build\\outputs\\apk\\app-debu
g.apk /data/local/tmp/undefined' }

**Comment by whitiancai** [comment]
@tlllly @ligaopan @zsmjluo @upengfei 已经修复，重新安装最新版本即可

**Comment by zsmjluo** [comment]
@whitiancai 问题仍然存在

>> inspector start at: http://10.0.2.26:5678
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by tlllly** [comment]
@whitiancai 问题依然存在


        inspector start at: http://xxxxxxxx:5678
        <-- GET /

Error: connect ECONNREFUSED 127.0.0.1:8001
at Object.exports._errnoException (util.js:1026:11)
at exports._exceptionWithHostPort (util.js:1049:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by Archer456** [comment]
https://testerhome.com/topics/8618   参考这个 @tlllly
