### ISSUE TITLE
app-inspector 1.2.27版本出错

### ISSUE THREAD

**Issue by upengfei** [alibaba/macaca#543]
{ Error: Command failed: D:\android\android-sdk-windows/platform-tools/adb -s 17
a8606b push C:\Users\Administrator\AppData\Roaming\npm\node_modules\app-inspecto
r\node_modules\._uiautomatorwd@1.0.2@uiautomatorwd\app\build\outputs\apk\app-deb
ug.apk /data/local/tmp/undefined

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'D:\\android\\android-sdk-windows/platform-tools/adb -s 17a8606b push C:\
\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\app-inspector\\node_
modules\\._uiautomatorwd@1.0.2@uiautomatorwd\\app\\build\\outputs\\apk\\app-debu
g.apk /data/local/tmp/undefined' }

* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by upengfei** [comment]
@xudafeng

**Comment by sionmike** [comment]
一样
{ Error: Command failed: /Users/edz/Downloads/android-sdk-macosx/platform-tools/adb -s A1UABMSF3E3V push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.example.android.testing.uiautomator

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/edz/Downloads/android-sdk-macosx/platform-tools/adb -s A1UABMSF3E3V push /usr/local/lib/node_modules/app-inspector/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.example.android.testing.uiautomator' }



@xudafeng

**Comment by Uglena** [comment]
我的也是
{ Error: Command failed: /Users/fifinli/Documents/sdk/platform-tools/adb -s emulator-5554 push /usr/local/Cellar/node/7.10.0/lib/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug-androidTest.apk /data/local/tmp/com.macaca.android.testing.uiautomator

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/fifinli/Documents/sdk/platform-tools/adb -s emulator-5554 push /usr/local/Cellar/node/7.10.0/lib/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug-androidTest.apk /data/local/tmp/com.macaca.android.testing.uiautomator' }


查看发现没有app-debug-androidTest.apk 的文件
然后发现安装uiautomatorwd有问题：
tnpm install uiautomatorwd -g
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.

> uiautomatorwd@1.0.13 install /usr/local/Cellar/node/7.10.0/lib/node_modules/uiautomatorwd
> node ./scripts/build.js


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'uiautomatorwd'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.3.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:2.3.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
               > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/108.168.243.150] failed: Operation timed out (Connection timed out)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 1 mins 16.482 secs
(node:76382) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: build failed
(node:76382) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/usr/local/Cellar/node/7.10.0/lib
└─┬ uiautomatorwd@1.0.13 
  └── gradle@1.0.4 

@xudafeng

**Comment by whitiancai** [comment]
@upengfei @sionmike @Uglena 已经修复，重新安装即可

**Comment by unlimUA** [comment]
I have the same problem
  at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
  killed: false,
  code: 1,
  signal: null,
