### ISSUE TITLE
Cannot start app-inspecttor Mac OS

### ISSUE THREAD

**Issue by nrazvan87** [alibaba/macaca#544]
I cannot start app-inspector.

using the command: 
`app-inspector -u ... -verbose
`
I get:
`>> xctest-client.js:192:14 [master] pid:2570 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:191:14 [master] pid:2570 
Testing failed:

>> xctest-client.js:192:14 [master] pid:2570 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:191:14 [master] pid:2570 	Module compiled with Swift 3.1 cannot be imported in Swift 3.0.2: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/../Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64.swiftmodule
** TEST FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/XCTestWDStatus.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDStatusController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDKeysController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDWindowController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/XCTestWDAlert.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDScreenshotController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/extensions/XCTestWDApplicationTree.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/XCTestWDServer.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)`

* **Macaca Version**: 1.2.3

* **Macaca Doctor Logs**:
  macaca-doctor version: 1.1.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.9.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode 8.2.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.22.0

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is not set
  Gradle 3.3 is installed at: `/usr/local/bin/gradle`

  Installed driver list:

  ios: 1.0.67

* **Operate System**:
MAC OS 

* **Programming Language**:

**Comment by whitiancai** [comment]
@nrazvan87 重新安装最新版本即可

**Comment by nrazvan87** [comment]
This issue occurred after upgrading to the latest version.

**Comment by Archer456** [comment]
https://testerhome.com/topics/8618     参考下这个

**Comment by nrazvan87** [comment]
@Archer456 thanks, i've installed 1.2.28 and I'm getting:

>> xctest-client.js:192:14 [master] pid:38965 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:191:14 [master] pid:38965 
Testing failed:
	Module compiled with Swift 3.1 cannot be imported in Swift 3.0.2: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/../Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64.swiftmodule
** TEST FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/XCTestWDStatus.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDStatusController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDKeysController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDWindowController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/XCTestWDAlert.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDScreenshotController.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/server/models/extensions/XCTestWDApplicationTree.swift
	CompileSwift normal x86_64 /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/XCTestWDServer.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

**Comment by xudafeng** [comment]
@nrazvan87 reinstall macaca-cli

```
macaca doctor
```

to check your environment

**Comment by raymondlapak** [comment]
Happens to me as well. app-inspector@1.2.28 with latest macaca-cli

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-doctor/commit/9184225218bcd7afc53fc0816d52fda0523749d1

@raymondlapak 

pls reinstall macaca-cli 

```
npm i macaca-cli -g && macaca doctor
```

to check your xcodebuild version

**Comment by raymondlapak** [comment]
@xudafeng Hello. It did mention something about my xcodebuild.
` xcodebuild version: 8.2.1 lower than 8.3.2`

Does the latest app-inspector only support XCode 8.3? Thanks

**Comment by xudafeng** [comment]
https://testerhome.com/topics/8820
