### ISSUE TITLE
Macaca 安卓如何处理权限类的系统弹窗，autoAcceptAlert不起作用

### ISSUE THREAD

**Issue by BachWings** [alibaba/macaca#545]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

之前 app 的权限在打开app就会弹出，设置的 autoAcceptAlert 还能起作用，现在弹窗在引导页完成之后首页再弹出， autoAcceptAlert 就不起作用了，有遇到过的朋友吗，或者安卓的弹窗有什么别的处理方法吗？

**Comment by xudafeng** [comment]
@BachWings 更新驱动

**Comment by huangwnebin** [comment]
我的app的权限在打开app就会弹出，设置的 autoAcceptAlert 不起作用，macaca一直在等待app启动手动点掉才会继续往下走
