### ISSUE TITLE
app-inspector最新版1.2.28仍然无法使用

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#547]
惊闻1.2.27的问题已修复，升级1.2.28，问题依旧，详情如下：
inspector start at: http://10.0.2.26:5678
  <-- GET /
  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by zsmjluo** [comment]
能不能修改成不强制升级，希望能继续用1.2.23版本

**Comment by Archer456** [comment]
`C:\Users\cmd>macaca doctor

  macaca-doctor version: 1.1.4


  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-25`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\gradle-3.5`

  Installed driver list:

  android: 2.0.2
  chrome: 1.0.5
  electron: 1.1.6



C:\Users\cmd>adb devices -l
List of devices attached
192.168.92.101:5555    device product:vbox86p model:Samsung_Galaxy_S6___6_0_0___API_23___1440x2560 device:vbox86p


C:\Users\cmd>app-inspector -v

 1.2.28


C:\Users\cmd>app-inspector -u 192.168.92.101:5555 --verbose
>> server.js:16:12 [master] pid:5952 server start with config:
 { port: 5678,
  verbose: true,
  udid: '192.168.92.101:5555',
  ip: '192.168.56.1',
  host: 'cmd',
  loaded_time: '2017-05-11 09:17:44' }
>> app-inspector.js:43:12 [master] pid:5952 server start at: http://192.168.56.1:5678
{ Error: Command failed: D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.92.101:5555 push D:\nodejs\node-global\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'D:\\Android\\android-sdk-windows/platform-tools/adb -s 192.168.92.101:5555 push D:\\nodejs\\node-global\\node_modules\\app-inspector\\node_modules\\uiautomatorwd\\app\\build\\outputs\\apk\\app-debug.apk /data/local/tmp/com.macaca.android.testing' }
^C终止批处理操作吗(Y/N)? y`

**Comment by tlllly** [comment]
问题依然存在
inspector start at: http://xxxxx:5678
<-- GET /
Error: connect ECONNREFUSED 127.0.0.1:8001
at Object.exports._errnoException (util.js:1026:11)
at exports._exceptionWithHostPort (util.js:1049:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by Archer456** [comment]
https://testerhome.com/topics/8618   look at this @tlllly

**Comment by AppleZou** [comment]
同上，升级到1.2.28之后，app inspector不能开启
>> inspector start at: http://10.0.21.218:5679
>> xctest-client.js:230:14 [master] pid:911 iproxy exit with code: null, signal: SIGKILL
  <-- GET /
>> helper.js:97:16 [master] pid:911 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

Macaca doctor如下：
![Uploading image.png…]()
