### ISSUE TITLE
macaca android 2.0.2 不可执行老业务脚本，服务端报错

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#548]
`C:\Users\cmd>macaca doctor

  macaca-doctor version: 1.1.4

  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-25`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\gradle-3.5`

  Installed driver list:

  android: 2.0.2
  chrome: 1.0.5
  electron: 1.1.6
`

`C:\Users\cmd>macaca server -p 3456 --verbose
>> index.js:17:12 [master] pid:2776 webdriver server start with config:
 { port: '3456',
  verbose: true,
  always: true,
  ip: '192.168.56.1',
  host: 'cmd',
  loaded_time: '2017-05-11 09:25:55' }
>> middlewares.js:17:10 [master] pid:2776 base middlewares attached
>> router.js:127:10 [master] pid:2776 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:2776 Recieve HTTP Request from Client[2017-05-11 09:27:09]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"reuse":3,"package":"com.acp.aicaitencent","activity":".BootUI","javascriptEnabled":true,"platformName":"Android","udid":"192.168.92.101:5555","version":"","autoAcceptAlerts":true},"port":3456,"host":"127.0.0.1"}
>> session.js:47:10 [master] pid:2776 Creating session, sessionId: 26e3c1b0-85a4-4ca7-8444-3a7566f118b8.
>> responseHandler.js:54:12 [master] pid:2776 Send Error Respone to Client: Error: Command failed: D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.92.101:5555 push D:\nodejs\node-global\node_modules\macaca-android\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

>> responseHandler.js:60:14 [master] pid:2776 Error: Command failed: D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.92.101:5555 push D:\nodejs\node-global\node_modules\macaca-android\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

  Error: Command failed: D:\Android\android-sdk-windows/platform-tools/adb -s 192.168.92.101:5555 push D:\nodejs\node-global\node_modules\macaca-android\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

      at ChildProcess.exithandler (child_process.js:206:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:877:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`

**Comment by whitiancai** [comment]
看看你的D:\nodejs\node-global\node_modules\macaca-android\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk 这个文件存不存在。
看看你的D:\nodejs\node-global\node_modules\macaca-android\node_modules\uiautomatorwd\app\buile.gralde里面android节点下有没有lintOptions {
		abortOnError false
	}，没有就加上，然后在D:\nodejs\node-global\node_modules\macaca-android\node_modules\uiautomatorwd下执行gradle build 和gradle assembleDebugAndroidTest。再看看有没有apk 如果有app-debug.apk和app-debug-androidTest.apk再看能否正常使用

**Comment by Archer456** [comment]
保证安装macaca-android成功后   老业务脚本的错误

这是wd.java 2.0.7 API  mvn test 执行日志 
2017-05-11 14:25:04 Request:http://127.0.0.1:3456/wd/hub/session/a3b7aca7-9be6-48e5-ab33-7463f2847aee/element:{"using":"id","value":"com.acp.aicaitencent:id/tvAccount"}
2017-05-11 14:25:04 Response:{"status":0,"value":{"ELEMENT":"1"},"sessionId":"a3b7aca7-9be6-48e5-ab33-7463f2847aee"}
2017-05-11 14:25:04 Request:http://127.0.0.1:3456/wd/hub/session/a3b7aca7-9be6-48e5-ab33-7463f2847aee/element/1/text
2017-05-11 14:25:04 Response:{"status":0,"value":{"value":"madachuan"},"sessionId":"a3b7aca7-9be6-48e5-ab33-7463f2847aee"}
200
2017-05-11 14:25:04 Response:{"sessionId":"a3b7aca7-9be6-48e5-ab33-7463f2847aee","status":0}
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 25.809 sec <<< FAILURE! - in TestSuite
test_case_1(uiauto.AndroidAcpTest)  Time elapsed: 15.584 sec  <<< FAILURE!
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String
	at macaca.client.commands.Element.getText(Element.java:116)
	at uiauto.AndroidAcpTest.test_case_1(AndroidAcpTest.java:100)


Results :

Failed tests: 
  AndroidAcpTest.test_case_1:100 » ClassCast com.alibaba.fastjson.JSONObject can...

Tests run: 2, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.039 s
[INFO] Finished at: 2017-05-11T14:25:04+08:00
[INFO] Final Memory: 13M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project uiautotest: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/cmd/workspace/Macacadev/uiautoaicai/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException


这是对应的业务脚步报错的段
		driver.elementById("com.acp.aicaitencent:id/tvLogin");
		element.click();
		driver.sleep(3000);
			    
		    String view = driver.elementById("com.acp.aicaitencent:id/tvAccount").getText();
		    System.out.println("The view is："+view);
		    Assert.assertEquals(view,"×××××××");

对比好像是  macaca.client.commands.Element.getText    就是
String view = driver.elementById("com.acp.aicaitencent:id/tvAccount").getText();   这个gettext有问题。我看群里也有人反应get不到text

@whitiancai @xudafeng

**Comment by xudafeng** [comment]
@Archer456 更新驱动试试

https://travis-ci.org/macaca-sample/sample-nodejs

**Comment by Archer456** [comment]
![image](https://cloud.githubusercontent.com/assets/18392901/26040836/0d55f192-395b-11e7-9aeb-5e3470440fa7.png)
D:\workspace\svn\uiautotest>macaca doctor

  macaca-doctor version: 1.1.4


  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-25`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\gradle-3.5`

  Installed driver list:

  android: 2.0.8
  chrome: 1.0.5
  electron: 1.1.6


2.0.8  还是gettext报错了啊

**Comment by xudafeng** [comment]
@Archer456 https://github.com/macacajs/UIAutomatorWD/commit/156ddd9c8571502a2324bbef869bb4b3078430c1 

重装一下看

**Comment by Archer456** [comment]
升级为:\workspace\svn\uiautotest>macaca doctor

  macaca-doctor version: 1.1.9


  Node.js checklist:

  node env: D:\nodejs\node.exe
  node version: v6.10.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-25`
  Android tools is set to `D:\Android\android-sdk-windows\tools\android.bat`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\gradle-3.5`

  Installed driver list:

  android: 2.0.12
  chrome: 1.0.5
  electron: 1.1.6



D:\workspace\svn\uiautotest>macaca -v

  2.0.0

已好
