### ISSUE TITLE
xpath 和 css为无效的selector.

### ISSUE THREAD

**Issue by upengfei** [alibaba/macaca#551]
![6tg7 hg2 tml9q g6 dh 8q](https://cloud.githubusercontent.com/assets/18410330/25934147/c257f938-364e-11e7-81b8-5adb2d3d980f.png)

这个是什么原因？

* **Macaca Version**:1.2.3

* **Macaca Doctor Logs**:

* **Operate System**:win7 64

* **Programming Language**:python

**Comment by xudafeng** [comment]
@upengfei 更新驱动

**Comment by upengfei** [comment]
@xudafeng  xpath还是这个问题？驱动2.0.8

**Comment by zhuyali** [comment]
@upengfei 现在ok了么？

**Comment by upengfei** [comment]
@zhuyali 这个问题还没还有解决。。。等着修复

**Comment by upengfei** [comment]
@xudafeng 这个问题修复了吗？

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/commit/622142f5cf2848d8759562b37f1e92325eb3448d

**Comment by wxlsh114** [comment]
maraca-android @2.0.22, the same issue took place again. Please check it again.
ps: no matter with android version.(tested in android 6.0 & 7.0)
