### ISSUE TITLE
send_keys 命令错误(python)

### ISSUE THREAD

**Issue by upengfei** [alibaba/macaca#553]
send_kyes 输入框不能完整输入手机号，只能一个数字一个数字的输入。

send_kyes 输入框不能完整输入手机号，只能一个数字一个数字的输入。

* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by upengfei** [comment]
@xudafeng

**Comment by upengfei** [comment]
导致我的手机号输入的时候，不是完整的输入，而是一个数字一个数字的输入

**Comment by xudafeng** [comment]
@upengfei 更新驱动

**Comment by upengfei** [comment]
@xudafeng  send_keys 命令输入还是一个数字一个数字的输入，后面的数字会把前面的数字替换掉。就是不知道python的其他使用者是不是也是这个问题。

**Comment by wxlsh114** [comment]
when can it be fixed？

**Comment by upengfei** [comment]
@xudafeng 这个问题能否修复？

**Comment by xudafeng** [comment]
@upengfei https://github.com/macacajs/wd.py/pull/26/files

**Comment by upengfei** [comment]
@xudafeng  已解决，辛苦啦！！

**Comment by wxlsh114** [comment]
great job！thanks a lot.
