### ISSUE TITLE
升级Macaca后，python环境，driver.wait_for_element_by_id不可以使用

### ISSUE THREAD

**Issue by jack30639** [alibaba/macaca#555]
macaca-doctor version: 1.1.4

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v6.10.2

  Android checklist:

  JAVA version get not found
  JAVA_HOME is set to `C:\Program Files\Zulu\zulu-8`
  ANDROID_HOME is set to `D:\androidsdk`
  Platforms is set to `D:\androidsdk\platforms\android-25`
  Android tools is set to `D:\androidsdk\tools\android.bat`
  ADB tool is set to `D:\androidsdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\Program Files\gradle-3.5-bin\gradle-3.5`

  Installed driver list:

  android: 2.0.2

![image](https://cloud.githubusercontent.com/assets/12481335/25991408/9f3765aa-3735-11e7-94f6-048128864b3c.png)

![image](https://cloud.githubusercontent.com/assets/12481335/25991415/a886338e-3735-11e7-9bf3-a56f2e3acb00.png)

**Comment by upengfei** [comment]
你在用send_keys的时候，有没有出现不能完整输入的情况？比如输入"abc",最后输入框里就剩下一个c
