### ISSUE TITLE
获取手机分辨率的方法

### ISSUE THREAD

**Issue by mengde0077** [alibaba/macaca#556]
macaca 大神 你好！
      希望在后面的版本中能提供获取手机分辨率的方法！
      在写app自动化用例时，有时候需要 从手机屏中心，向下或向上滑半屏，这个时候如果能获取到 手机的分辨率，就比较好操作！

**Comment by xudafeng** [comment]
getWindowSize

sample:https://github.com/macaca-sample/webdriver-client/blob/master/lib/webdriver-client.js#L73
