### ISSUE TITLE
手机打开失败，请检查macaca是否配置正确？ Internal Server Error，我设置的app路径跟server端报错的路径不一致

### ISSUE THREAD

**Issue by logan62334** [alibaba/macaca#557]
? App路径 (扩展名: apk, app, zip): /User/logan/uirecorder/app-debug.apk
我设置的app路径跟server端报错的路径不一致，是什么情况呢？
下面是server报错信息：
Error: Command failed: /Users/mafei/Development/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing

      at ChildProcess.exithandler (child_process.js:204:12)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:191:7)
      at maybeClose (internal/child_process.js:886:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by loftyet** [comment]
你要测试的目标apk是uirecorder下的app-debug.apk?
这个报错信息指的app-debug.apk是UIAutomatorWD用到的，不是目标测试apk

**Comment by logan62334** [comment]
@loftyet 我要测的是目标测试apk不是uirecorder下的，如果正常测某个目标apk应该怎么配置呢？

**Comment by pengchenglin** [comment]
把你手机上原先跑自动化脚本 Macaca自动安装的那几个apk给删掉试试看

**Comment by logan62334** [comment]
@pengchenglin 我是新配置的Macaca和uirecorder的环境，然后第一次去跑录制脚本的命令行，就报这个apk路径错误

**Comment by logan62334** [comment]
不知道为什么传入的app路径参数跟返回的不一样
下面是详细的错误信息：
>> responseHandler.js:11:12 [master] pid:1085 Recieve HTTP Request from Client[2017-05-15 10:46:19]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"Android","app":"/Users/mafei/uirecorder/app-debug.apk","udid":"emulator-5554"}}
>> session.js:47:10 [master] pid:1085 Creating session, sessionId: b0dfc7fe-1403-4540-8071-5cea60964af1.
>> helper.js:208:12 [master] pid:1085 Using local app form /Users/mafei/uirecorder/app-debug.apk
>> responseHandler.js:54:12 [master] pid:1085 Send Error Respone to Client: Error: Command failed: /Users/mafei/Development/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing

>> responseHandler.js:60:14 [master] pid:1085 Error: Command failed: /Users/mafei/Development/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s emulator-5554 push /usr/local/lib/node_modules/macaca-android/node_modules/uiautomatorwd/app/build/outputs/apk/app-debug.apk /data/local/tmp/com.macaca.android.testing

**Comment by bujiduli** [comment]
解决否？我也出现了这个error

**Comment by logan62334** [comment]
已经解决，参考这个方案：https://testerhome.com/topics/8618
@loftyet @pengchenglin 感谢回答！
