### ISSUE TITLE
关于登陆输入验证码

### ISSUE THREAD

**Issue by zanjs** [alibaba/macaca#56]
PC 端情况下,用户登录是需要输入验证码的,
,需要输入图片验证码, 这个该如何破呢

,想到的解决方案是 验证码识别, 这个可以有吗

### demo 

哔哩哔哩站 登陆

https://passport.bilibili.com/login

这个该如何登陆呢

**Comment by xudafeng** [comment]
@zanjs http://www.cnblogs.com/fnng/p/3606934.html
