### ISSUE TITLE
运行sample-noedjs报错

### ISSUE THREAD

**Issue by fantasticcmm** [alibaba/macaca#560]
![image](https://cloud.githubusercontent.com/assets/18608661/26087119/985377b2-3a21-11e7-91a7-708de8b17300.png)

为何不把macaca-electron当做本地依赖？一定要全局安装？

Macaca Version: usually output of `macaca -v`
![image](https://cloud.githubusercontent.com/assets/18608661/26087070/54a965a8-3a21-11e7-85ba-7ca0059c3df4.png)

Macaca Doctor: usually output of `macaca doctor`
![image](https://cloud.githubusercontent.com/assets/18608661/26087084/6a1b2886-3a21-11e7-9f58-452d3ec50802.png)

Platform: either `uname -a` output, or if Windows, version and 32 or 64-bit.
![image](https://cloud.githubusercontent.com/assets/18608661/26087095/7786cfc0-3a21-11e7-92a1-48550a0126bf.png)

**Comment by loftyet** [comment]
这是npm没有找到macaca-electron. 试个不同的网络环境，有vpn的，再试试。
