### ISSUE TITLE
最新app-inspector 获取iOS 元素时，获取的name值和ID属性值一样。

### ISSUE THREAD

**Issue by ownehe** [alibaba/macaca#561]
环境：
 macaca-doctor version: 1.1.8

  Node.js checklist:

  node env: /Users/longfei.he/nodejs/bin/node
  node version: v6.9.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.22.0

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/longfei.he/android-sdk-macosx`
  Platforms is set to `/Users/longfei.he/android-sdk-macosx/platforms/android-25`
  Android tools is set to `/Users/longfei.he/android-sdk-macosx/tools/android`
  ADB tool is set to `/Users/longfei.he/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.12
  electron: 1.1.6
  ios: 2.0.4

* **Operate System**:

* **Programming Language**:
--------------------------------------------------------------
更新最新版本app-inspector之后，链接IOS手机启动发现，获取的所有元素的name属性和该元素的ID属性一致，是否内部获取错了，前版本是可以获取到name属性的中文的，比如一个登入按钮，能获取到ID是：id_login，name属性是：登入。

**Comment by SamuelZhaoY** [comment]
please update to the latest version
