### ISSUE TITLE
app inspector 连接android真机和模拟器，网页端显示Internal Server Error

### ISSUE THREAD

**Issue by Uglena** [alibaba/macaca#562]
* **Macaca Version**:
1.2.3

* **Macaca Doctor Logs**:

  macaca-doctor version: 1.1.4

  Node.js checklist:

  node env: /usr/local/Cellar/node/7.10.0/bin/node
  node version: v7.10.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.22.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/fifinli/Documents/sdk`
  Platforms is set to `/Users/fifinli/Documents/sdk/platforms/android-25`
  Android tools is set to `/Users/fifinli/Documents/sdk/tools/android`
  ADB tool is set to `/Users/fifinli/Documents/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.12
  chrome: 1.0.5
  electron: 1.1.6
  ios: 1.0.67

* **Operate System**:
Mac 10.12.4 (16E195)

app inspector version / 版本号:1.2.27
-xcode: Version 8.3.2

* **Programming Language**:

server.js:16:12 [master] pid:20876 server start with config:
{ port: 5678,
verbose: true,
udid: '90aef623',
ip: '10.65.82.36',
host: 'FIFINLI-MC1',
loaded_time: '2017-05-16 15:20:30' }
app-inspector.js:43:12 [master] pid:20876 server start at: http://10.65.82.36:5678
UIAutomatorWD http server ready
Android device started: 90aef623
inspector start at: http://10.65.82.36:5678
<-- GET /
proxy.js:56:14 [master] pid:20876 Proxy: /wd/hub/session/temp/source:GET to http://127.0.0.1:9001/wd/hub/session/temp/source:GET with body: null
proxy.js:84:20 [master] pid:20876 Got response with status 200: {"status":0,"value":"","sessionId":null}
Dump Android XML success, save to /usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/.temp/android.json
TypeError: Cannot read property 'bounds' of undefined
at adaptor (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/lib/android.js:27:13)
at Object.exports.dumpXMLAndScreenShot (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/lib/android.js:64:14)
at exports.dumpXMLAndScreenShot.next ()
at onFulfilled (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
at process._tickCallback (internal/process/next_tick.js:109:7)

<-- GET /

proxy.js:56:14 [master] pid:20876 Proxy: /wd/hub/session/temp/source:GET to http://127.0.0.1:9001/wd/hub/session/temp/source:GET with body: null
proxy.js:84:20 [master] pid:20876 Got response with status 200: {"status":0,"value":"","sessionId":"temp"}
Dump Android XML success, save to /usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/.temp/android.json
TypeError: Cannot read property 'bounds' of undefined
at adaptor (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/lib/android.js:27:13)
at Object.exports.dumpXMLAndScreenShot (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/lib/android.js:64:14)
at exports.dumpXMLAndScreenShot.next ()
at onFulfilled (/usr/local/Cellar/node/7.10.0/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
at process._tickCallback (internal/process/next_tick.js:109:7)

@xudafeng

**Comment by xudafeng** [comment]
更新最新版
