### ISSUE TITLE
macaca升级2.0后，android真机运行报错

### ISSUE THREAD

**Issue by bujiduli** [alibaba/macaca#564]
* **Macaca Version**:
2.0.0
* **Macaca Doctor Logs**:
![image](https://cloud.githubusercontent.com/assets/27192729/26139901/4055a838-3b06-11e7-8ac1-9d23e49b7297.png)
* **Operate System**:
android
* **Programming Language**:
python

升级macaca后，按照官方步骤重新配置了环境。检查了一下macaca-android\node_modules\uiautomatorwd\app\build\outputs\apk路径，apk文件app-debug和app-debug-androidTest都存在。安装macaca-android时没有报错，只有warning，提示了两次build successfully。但在运行case时候，出现了以下错误：
![image](https://cloud.githubusercontent.com/assets/27192729/26139861/072ee63c-3b06-11e7-9fb2-8fab703781ca.png)
尝试过：
1.重新安装macaca-android，日志中没有出现build failed
2.重现下载安装wd.py
3.删除之前手机中调试下载的apk
问题依然存在

**Comment by xudafeng** [comment]
重启电脑

**Comment by bujiduli** [comment]
重启后依然如此，并没有什么变化

**Comment by xudafeng** [comment]
@bucketli 这样的话问题就不好查了，哪个sdb版本的手机

**Comment by bujiduli** [comment]
android6.0和android5.1我都试过了
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
现在出现了以上错误，看提示是远程端关闭连接？

**Comment by xudafeng** [comment]
手机的端口应该跟本地pc机没有绑定成功，网络不通

**Comment by bujiduli** [comment]
同样步骤的配置我在win10笔记本上能够运行，push命令也完成了。但在win7台式上没有解决，error还是没变，不知道是啥问题了……
![image](https://cloud.githubusercontent.com/assets/27192729/26294549/30f09cc8-3ef7-11e7-8a07-8b2deaaae4db.png)
且win10运行时会出现socket hang up的问题
