### ISSUE TITLE
不支持元素截图？

### ISSUE THREAD

**Issue by jack30639** [alibaba/macaca#565]
不支持元素截屏吗，我看Python的API有WebElement.save_screenshot()，但是执行就错误。

![image](https://cloud.githubusercontent.com/assets/12481335/26141788/3068b29e-3b10-11e7-82b9-f7c5cd86420c.png)

**Comment by zenzhu** [comment]
服务端不支持吧

**Comment by xudafeng** [comment]
使用 Webdriver.take_screenshot，WebElement.save_screenshot() 暂不支持
