### ISSUE TITLE
macaca升级2.0后，ios版启动测试报错

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#566]
升级后无法启动测试，启动macaca server --verbose后执行用例测试，报错如下：
* **Macaca Version**:2.0.0

* **Macaca Doctor Logs**:

  macaca-doctor version: 1.1.9
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v7.0.0
  iOS checklist:
  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.22.0

  Installed driver list:
  ios: 2.0.5

* **Operate System**:macOS 10.12.5

* **Programming Language**: java

proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: read ECONNRESET
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
proxy.js:61:22 [master] pid:5804 xctest client proxy error with: Error: socket hang up
xctest-client.js:249:14 [master] pid:5804 Fail to start xctest: Error: socket hang up
xctest-client.js:257:14 [master] pid:5804 killing deviceLogProc pid: 5813
xctest-client.js:262:14 [master] pid:5804 killing runnerProc pid: 5816
xctest-client.js:268:14 [master] pid:5804 killing iproxyProc pid: 5815
responseHandler.js:54:12 [master] pid:5804 Send Error Respone to Client: Error: socket hang up
responseHandler.js:60:14 [master] pid:5804 Error: socket hang up
at createHangUpError (_http_client.js:253:15)
at Socket.socketOnEnd (_http_client.js:345:23)
at emitNone (events.js:91:20)
at Socket.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
Error: socket hang up
at createHangUpError (_http_client.js:253:15)
at Socket.socketOnEnd (_http_client.js:345:23)
at emitNone (events.js:91:20)
at Socket.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zsmjluo** [comment]
增加说明：真机测试，XCTestWD安装启动均正常。

**Comment by SamuelZhaoY** [comment]
@zsmjluo  请更新目前 macaca-ios 版本， 如果出现偶尔socket hangup， 可以尝试重启模拟器， 重启进程XCTestWD

**Comment by zsmjluo** [comment]
@SamuelZhaoY 我找到问题原因了，原来的WDA的proxyPort默认是8900，升级后XCTestWD默认是8001，所以导致端口错误，我用的java版，设置proxyPort为8001即可。
porps.put("proxyPort", proxyPort);

当然，也可以修改XCTestWD工程里面配置的端口。
建议macaca同步修改下proxyPort为8001或者XCTestWD默认端口为8900，避免用户升级后出现问题。

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/commit/2cc8c1e5573e390695de88a0acd66e12f1d00c8d
