### ISSUE TITLE
after running app-inspector 1.2.29 , I have problem with : please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj

### ISSUE THREAD

**Issue by msmirzazadeh** [alibaba/macaca#567]
* **Macaca Version**: 2.0.0

* **Macaca Doctor Logs**: macaca-doctor version: 1.1.9

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.10.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: Carthage Version: 1.0.6
Built internally @ devagnos.com

* **Operate System**: OSX 10.12.2

* **Programming Language**: java

**app-inspector -u A908E923-3BBB-4D4A-808A-4CC69ED2C33E --verbose**                                       ‹ruby-2.2.2›
>> port: 5678 was occupied, changed port: 5679
>> server.js:16:12 [master] pid:62792 server start with config:
 { port: 5679,
  verbose: true,
  udid: 'A908E923-3BBB-4D4A-808A-4CC69ED2C33E',
  ip: '192.168.100.82',
  host: 'MSM.local',
  loaded_time: '2017-05-17 21:24:15' }
>> app-inspector.js:43:12 [master] pid:62792 server start at: http://192.168.100.82:5679
>> xctest-client.js:53:14 [master] pid:62792 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> xctest-client.js:226:14 [master] pid:62792 xcode version: 8.3.1
>> XCTestWD version: 1.0.18
>> xctest-client.js:174:14 [master] pid:62792 2017-05-17 21:24:16.449 xcodebuild[62795:1106814]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/17D06AD7-3F54-41FC-8F62-5D7329EF00D4/Session-XCTestWDUITests-2017-05-17_212416-TQtvhZ.log

>> xctest-client.js:175:14 [master] pid:62792 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:62792 2017-05-17 21:24:16.450 xcodebuild[62795:1106795] [MT] IDETestOperationsObserverDebug: (F31591C1-E7B5-4650-BE61-33CAFCD19458) Beginning test session XCTestWDUITests-F31591C1-E7B5-4650-BE61-33CAFCD19458 at 2017-05-17 21:24:16.450 with Xcode 8E1000a on target <DVTiPhoneSimulator: 0x7f9f7b6a0d80> {
		SimDevice: SimDevice : iPhone 6 (A908E923-3BBB-4D4A-808A-4CC69ED2C33E) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6 } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))

>> xctest-client.js:175:14 [master] pid:62792 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:62792 2017-05-17 21:24:16.759 xcodebuild[62795:1106795] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/17D06AD7-3F54-41FC-8F62-5D7329EF00D4/Session-XCTestWDUITests-2017-05-17_212416-TQtvhZ.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/17D06AD7-3F54-41FC-8F62-5D7329EF00D4/Session-XCTestWDUITests-2017-05-17_212416-TQtvhZ.log}

>> xctest-client.js:175:14 [master] pid:62792 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:62792
Testing failed:
	Command /bin/sh failed with exit code 1

>> xctest-client.js:175:14 [master] pid:62792 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:62792 ** TEST FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/administrator/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Build/Intermediates/XCTestWD.build/Debug-iphonesimulator/XCTestWD.build/Script-63D408691EAB64FC00198736.sh
(1 failure)

>> xctest-client.js:175:14 [master] pid:62792 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:257:14 [master] pid:62792 killing deviceLogProc pid: 62796
>> xctest-client.js:262:14 [master] pid:62792 killing runnerProc pid: 62795
>> xctest-client.js:185:14 [master] pid:62792 xctest client exit with code: 65, signal: null
>> xctest-client.js:109:18 [master] pid:62792 simulator log process exit with code: null, signal: SIGKILL

**Comment by xudafeng** [comment]
@msmirzazadeh 

```
npm i macaca-cli -g && macaca doctor
```

 check your xcodebuild version

**Comment by msmirzazadeh** [comment]
Hi thanks for your attention
I updated my xcode to 8.3.2 but still have the above problem, this is my macaca doctor response :

**Comment by msmirzazadeh** [comment]
> XCTest

**Comment by xudafeng** [comment]
https://testerhome.com/topics/8820
