### ISSUE TITLE
最新版本跑case时报错

### ISSUE THREAD

**Issue by ownehe** [alibaba/macaca#569]
* **Macaca Version**:
 macaca-doctor version: 1.1.10

  Node.js checklist:

  node env: /Users/longfei.he/nodejs/bin/node
  node version: v6.9.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.22.0

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/longfei.he/android-sdk-macosx`
  Platforms is set to `/Users/longfei.he/android-sdk-macosx/platforms/android-25`
  ADB tool is set to `/Users/longfei.he/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.16
  electron: 1.1.6
  ios: 2.0.7

系统：Mac Xcode8.3.2

语言：java

报错
安卓case报错：
>> responseHandler.js:11:12 [master] pid:1971 Recieve HTTP Request from Client[2017-05-19 14:45:22]: method: GET url: /wd/hub/session/14a3f298-5c66-4ae9-8488-2895f957e9ba/window/current/size, jsonBody: {}
>> proxy.js:55:14 [master] pid:1971 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9001/wd/hub/session/:sessionId/accept_alert:POST with body: {}  
body 内容为空，请求卡住不动。

IOS case报错：
>> xctest-client.js:175:14 [master] pid:2020 please check project: /Users/longfei.he/nodejs/lib/node_modules/macaca-ios/node_modules/.1.0.20@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:55:14 [master] pid:2020 Proxy: /wd/hub/session:POST to http://127.0.0.1:8900/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"************","platformName":"IOS"}}
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
确定xctest 已经成功装入手机。

**Comment by ownehe** [comment]
补充一下ios的报错日志：
responseHandler.js:11:12 [master] pid:2020 Recieve HTTP Request from Client[2017-05-19 14:59:56]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"bundleId":"com.hszq.HSSes","javascriptEnabled":true,"platformName":"IOS","udid":"8a357fdd0e91b3d01b5c451","version":"10.2","deviceName":"iPhone 6s","autoAcceptAlerts":true},"port":3456,"host":"127.0.0.1"}
>> session.js:47:10 [master] pid:2020 Creating session, sessionId: 7afea55f-4a2e-4558-aabf-3742a73f49df.
>> macaca-ios.js:231:12 [master] pid:2020 App "com.hszq.HSties" is already installed.
>> xctest-client.js:53:14 [master] pid:2020 project path: /Users/longfei.he/nodejs/lib/node_modules/macaca-ios/node_modules/.1.0.20@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:149:10 [master] pid:2020 {
	"bundleId": "com.hszq.HSities",
	"platformName": "IOS"
}
>> macaca-ios.js:151:10 [master] pid:2020 Trying to start xctestwd server...
BundleId XCTestWD.XCTestWD does not exist.
>> xctestwd start with port: 8900
>> xctest-client.js:226:14 [master] pid:2020 xcode version: 8.3.2
>> XCTestWD version: 1.0.20
>> xctest-client.js:174:14 [master] pid:2020 2017-05-19 14:59:58.757 xcodebuild[2334:425823]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/longfei.he/Library/Developer/Xcode/DerivedData/XCTestWD-bvltjetbtsevxwgqrvemaijbucio/Logs/Test/7DA7CB93-96F6-4190-91AD-7265972CD787/Session-XCTestWDUITests-2017-05-19_145958-OiLBN8.log

>> xctest-client.js:175:14 [master] pid:2020 please check project: /Users/longfei.he/nodejs/lib/node_modules/macaca-ios/node_modules/.1.0.20@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:2020 2017-05-19 14:59:58.758 xcodebuild[2334:425822] [MT] IDETestOperationsObserverDebug: (3F690E54-8F0F-4B4F-A5E2-77EE4589A99F) Beginning test session XCTestWDUITests-3F690E54-8F0F-4B4F-A5E2-77EE4589A99F at 2017-05-19 14:59:58.757 with Xcode 8E2002 on target <DVTiOSDevice: 0x7f8ea5e8b2c0> {
		deviceSerialNumber:         FK3RHFLV
		identifier:                 8a4611b3d01b5c451
		deviceClass:                iPhone
		deviceName:                 “lone”的 iPhone
		deviceIdentifier:           8a461******************0e91b3d01b5c451
		productVersion:             10.3.1
		buildVersion:               14E304
		deviceSoftwareVersion:      10.3.1 (14E304)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        283374720
		deviceAvailableCapacity:    2540064
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		isPasscodeLocked:           NO
		deviceType:                 <DVTDeviceType:0x7f8ea5b94110 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	bootArgs:                  <unavailable>
		} (10.3.1 (14E304))

>> xctest-client.js:175:14 [master] pid:2020 please check project: /Users/longfei.he/nodejs/lib/node_modules/macaca-ios/node_modules/.1.0.20@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:2020 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/qt/cqwj7pcs2lgd57ypmfywdwyr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/8ceb76616d24ad45b2fe4ababd870fea/8a461e9266754b92e73357fdd0e91b3d01b5c451/XCTestWDUITests-Runner.app
state->new_bundle: /Users/longfei.he/Library/Developer/Xcode/DerivedData/XCTestWD-bvltjetbtsevxwgqrvemaijbucio/Build/Products/Debug-iphoneos/XCTestWDUITests-Runner.app
state->dst_bundle: /var/folders/qt/cqwj7pcs2lgd57ypmfywdwyr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.OwaZwf/XCTestWDUITests-Runner.app_sparse.ipa/Payload//XCTestWDUITests-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/qt/cqwj7pcs2lgd57ypmfywdwyr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.OwaZwf/XCTestWDUITests-Runner.app_sparse.ipa

>> xctest-client.js:175:14 [master] pid:2020 please check project: /Users/lone/nodejs/lib/node_modules/macaca-ios/node_modules/.1.0.20@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:2020 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/qt/cqwj7pcs2lgd57ypmfywdwyr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.OwaZwf/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:175:14 [master] pid:2020 please check project: /Users/longfei.he/nodejs/lib/node_modules/macaca-ios/node_modules/.1.0.20@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:2020 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/qt/cqwj7pcs2lgd57ypmfywdwyr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.OwaZwf/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:175:14 [master] pid:2020 please check project: /Users/longfei.he/nodejs/lib/node_modules/macaca-ios/node_modules/.1.0.20@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:174:14 [master] pid:2020 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/qt/cqwj7pcs2lgd57ypmfywdwyr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/5958583b0a99ba0883aa9fbc2d53a0a5/8a461e9266754b92e73357fdd0e91b3d01b5c451/ManifestCache.plist

>> xctest-client.js:175:14 [master] pid:2020 please check project: /Users/longfei.he/nodejs/lib/node_modules/macaca-ios/node_modules/.1.0.20@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:55:14 [master] pid:2020 Proxy: /wd/hub/session:POST to http://127.0.0.1:8900/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.hszq.HS**ities","platformName":"IOS"}}
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2020 xctest client proxy error with: Error: socket hang up

**Comment by zsmjluo** [comment]
可以看下这个
#566 
不过我发现新版本还是不大稳定，所以我是先降级了。等版本稳定了再升级。

**Comment by xudafeng** [comment]
install macaca-ios@2.0.7
