### ISSUE TITLE
macaca-ios升级到2.0.8版本点击屏幕操作异常

### ISSUE THREAD

**Issue by bluesky12345** [alibaba/macaca#570]
* **Macaca Version**:
 2.0.1

* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.0

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.4.0

  iOS checklist:

  Xcode Command Line Tools require version: 2347 and above
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage require version 0.22.0 and above

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.8

* **Operate System**:
ios 

* **Programming Language**:
java

>> responseHandler.js:11:12 [master] pid:33648 Recieve HTTP Request from Client[2017-05-21 18:15:28]: method: GET url: /wd/hub/session/39521b60-7359-4006-ab2a-ecfa5698d70c/window/current/size, jsonBody: {}
>> proxy.js:55:14 [master] pid:33648 Proxy: /wd/hub/session/39521b60-7359-4006-ab2a-ecfa5698d70c/window/current/size:GET to http://127.0.0.1:8001/wd/hub/session/589F0093-B240-4440-9D01-849B7431B327/window/current/size:GET with body: {}
>> proxy.js:83:20 [master] pid:33648 Got response with status 200: {"value":{"height":568,"width":320},"status":0,"sessionId":""}
>> session.js:107:14 [master] pid:33648 Send HTTP Respone to Client[2017-05-21 18:15:29]: {"value":"{\"height\":568,\"width\":320}","status":0,"sessionId":""}
>> responseHandler.js:11:12 [master] pid:33648 Recieve HTTP Request from Client[2017-05-21 18:15:29]: method: POST url: /wd/hub/session/39521b60-7359-4006-ab2a-ecfa5698d70c/actions, jsonBody: {"actions":[{"x":"224.0","y":"539.6","type":"tap"}]}
>> proxy.js:55:14 [master] pid:33648 Proxy: /wd/hub/session/:sessionId/tap/null:POST to http://127.0.0.1:8001/wd/hub/session/589F0093-B240-4440-9D01-849B7431B327/tap/null:POST with body: {"x":"224.0","y":"539.6"}
>> proxy.js:83:20 [master] pid:33648 Got response with status 200: {"value":"","status":32,"sessionId":""}
>> responseHandler.js:54:12 [master] pid:33648 Send Error Respone to Client: InvalidSelector: Argument was an invalid selector (e.g. XPath/CSS).
>> responseHandler.js:60:14 [master] pid:33648 InvalidSelector: Argument was an invalid selector (e.g. XPath/CSS).
    at actionDelegate.call.then.result (/usr/local/lib/node_modules/macaca-ios/lib/actions.js:121:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
>> responseHandler.js:76:14 [master] pid:33648 Send Bad HTTP Respone to Client[2017-05-21 18:15:29]: {"sessionId":"39521b60-7359-4006-ab2a-ecfa5698d70c","status":32,"value":{"message":"Argument was an invalid selector (e.g. XPath/CSS)."}}
>> responseHandler.js:11:12 [master] pid:33648 Recieve HTTP Request from Client[2017-05-21 18:15:29]: method: DELETE url: /wd/hub/session/39521b60-7359-4006-ab2a-ecfa5698d70c, jsonBody: {}

**Comment by SamuelZhaoY** [comment]
This is caused by {"x":"224.0","y":"539.6"} strings are sent from Java client.  Working on data type compatibility

**Comment by SamuelZhaoY** [comment]
Please update macaca-ios

**Comment by bluesky12345** [comment]
macaca-ios升级到2.0.9解决了此问题，谢谢！
