### ISSUE TITLE
macaca-ios2.0.9版本查找的控件不存在时出现异常

### ISSUE THREAD

**Issue by bluesky12345** [alibaba/macaca#572]
* **Macaca Version**:
2.0.1
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.0

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.4.0

  iOS checklist:

  Xcode Command Line Tools require version: 2347 and above
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.9

* **Operate System**:
iOS
* **Programming Language**:
Java

当页面上不存在name为xxx的控件时根据elementByName(String name) 方法查找控件时，出现An element could not be located on the page using the given search parameters. 问题。

Response:{"value":"","status":7,"sessionId":""}
[2017-05-22 21:12:27]An element could not be located on the page using the given search parameters.

**Comment by xudafeng** [comment]
https://testerhome.com/topics/8820
