### ISSUE TITLE
XCTestWD 1.0.22 获取应用控件树中缺少“lable"值，“value”值为空字符串

### ISSUE THREAD

**Issue by leemony** [alibaba/macaca#575]
截取某页面source的部分如下：
{  "sessionId" : "",  "status" : 0,  "value" : {    "isEnabled" : true,    "name" : " ",    "value" : "",    "lable" : " ",    "isVisible" : true,    "rect" : {      "height" : 736,      "x" : 0,      "y" : 0,      "width" : 414    },    "type" : "Application",    "frame" : "{{0, 0}, {414, 736}}",    "children" : [      {        "children" : [          {            "children" : [              {                "rect" : {                  "height" : 736,                  "x" : 0,                  "y" : 0,                  "width" : 414                },                "value" : "",                "type" : "Other",                "frame" : "{{0, 0}, {414, 736}}",                "isVisible" : true,                "isEnabled" : true              }            ],            "value" : "",            "isVisible" : true,            "rect" : {              "height" : 736,              "x" : 0,              "y" : 0,              "width" : 414            },            "type" : "Other",            "frame" : "{{0, 0}, {414, 736}}",            "isEnabled" : true          },          {            "rect" : {              "height" : 736,              "x" : 0,              "y" : 0,              "width" : 414            },            "value" : "",            "type" : "Other",            "frame" : "{{0, 0}, {414, 736}}",            "isVisible" : true,            "isEnabled" : true          }        ],        "value" : "",        "isVisible" : true,        "rect" : {          "height" : 736,          "x" : 0,          "y" : 0,          "width" : 414        },        "type" : "Window",        "frame" : "{{0, 0}, {414, 736}}",        "isEnabled" : true      },      {        "children" : [          {            "children" : [              {                "children" : [                  {                    "children" : [                      {                        "children" : [                          {                            "children" : [                              {                                "children" : [                                  {                                    "rect" : {                                      "height" : 0,                                      "x" : -414,                                      "y" : 20,                                      "width" : 0                                    },                                    "value" : "",                                    "type" : "ScrollView",                                    "frame" : "{{-414, 20}, {0, 0}}",                                    "isVisible" : true,                                    "isEnabled" : true                                  },                                  {                                    "children" : [                                      {                                        "children" : [                                          {                                            "rect" : {                                              "height" : 736,                                              "x" : -414,                                              "y" : 0,                                              "width" : 414                                            },                                            "value" : "",                                            "type" : "Other",                                            "frame" : "{{-414, 0}, {414, 736}}",                                            "isVisible" : true,                                            "isEnabled" : true                                          }                                        ],                                        "value" : "",                                        "isVisible" : true,                                        "rect" : {                                          "height" : 736,                                          "x" : -414,                                          "y" : 0,                                          "width" : 414                                        },                                        "type" : "Other",                                        "frame" : "{{-414, 0}, {414, 736}}",                                        "isEnabled" : true                                      }                                    ],                                    "value" : "",                                    "isVisible" : true,                                    "rect" : {                                      "height" : 736,                                      "x" : -414,                                      "y" : 0,                                      "width" : 414                                    },                                    "type" : "Other",                                    "frame" : "{{-414, 0}, {414, 736}}",                                    "isEnabled" : true                                  },                                  {                                    "children" : [                                      {                                        "children" : [                                          {                                            "children" : [                                              {                                                "rect" : {                                                  "height" : 0,                                                  "x" : 0,                                                  "y" : 0,                                                  "width" : 0                                                },                                                "value" : "",                                                "type" : "Other",                                                "frame" : "{{0, 0}, {0, 0}}",                                                "isVisible" : true,                                                "isEnabled" : true                                              },                                              {                                                "rect" : {                                                  "height" : 0,                                                  "x" : 0,                                                  "y" : 0,                                                  "width" : 0                                                },                                                "value" : "",                                                "type" : "Other",                                                "frame" : "{{0, 0}, {0, 0}}",                                                "isVisible" : true,                                                "isEnabled" : true

**Comment by lylh** [comment]
+1

**Comment by leemony** [comment]
新增一行 info["lable"]
![image](https://cloud.githubusercontent.com/assets/13097980/26517263/9e40b8d4-42c7-11e7-889b-692ba94d70bd.png)

**Comment by SamuelZhaoY** [comment]
should be: lable -> label

**Comment by xudafeng** [comment]
should be: lable -> label 😆

**Comment by leemony** [comment]
哈哈 及时改正错误，label
这里的逻辑，如果 button的value字段为空字符串，那么也赋值为空字符串；能否考虑改为，button的value字段为空字符串，亦赋值为isSelected
![image](https://cloud.githubusercontent.com/assets/13097980/26517604/ace20526-42ce-11e7-8a1a-a35332c94a57.png)

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/pull/36/files

**Comment by SamuelZhaoY** [comment]
updated, please checkout the latest version
