### ISSUE TITLE
调用sendkeys时，出现error：an unknown server-side error occurred

### ISSUE THREAD

**Issue by bujiduli** [alibaba/macaca#576]
* **Macaca Version**:
2.0.1

* **Macaca Doctor Logs**:

C:\Users\qin.wei>macaca doctor

  macaca-doctor version: 2.0.0

  Node.js checklist:

  node env: E:\program\nodejs\node.exe
  node version: v6.10.3

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `E:\program\jdk`
  ANDROID_HOME is set to `E:\program\android-sdk-windows`
  Platforms is set to `E:\program\android-sdk-windows\platforms\android-25`
  ADB tool is set to `E:\program\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `E:\program\gradle-3.5`

  Installed driver list:

  android: 2.0.16

* **Operate System**:
android
* **Programming Language**:
python

我在运行一个登录的测试用例时，账号的sendkeys调用没有出现问题，但密码调用sendkeys时，出现了以下错误，复现率100%：
2017-05-24 16:45:40,072 - 2e52a430 - INFO -     --> LoginPage.wait_page
2017-05-24 16:45:40,241 - 2e52a430 - INFO -     --> LoginPage.input_account
2017-05-24 16:45:42,094 - 2e52a430 - INFO -     --> LoginPage.input_password
2017-05-24 16:45:43,153 - 2e52a430 - ERROR - WebDriverException,
Error: WebDriverError.UNKNOWN_ERROR
Message: An unknown server-side error occurred while processing the command.
账号输入框和密码输入框在同一界面

**Comment by lusiqiao** [comment]
遇到相同问题

**Comment by zthua** [comment]
这个问题  有解决吗 ？ 我也遇到同样的问题

**Comment by zthua** [comment]
@xudafeng

**Comment by xudafeng** [comment]
升级新版
