### ISSUE TITLE
回放录制脚本的时候报如下错误： getaddrinfo ENOTFOUND npm npm:80

### ISSUE THREAD

**Issue by Nubin4939** [alibaba/macaca#577]
主要环境如下：
Macaca Version: 2.0.1
Macaca Doctor: 2.0.0
Platform: Windows, version  64-bit.
Android设备：6.0.1

问题描述：
脚本正常录制之后使用如下命令回放：
macaca run -p 4444 -d 1.js --verbose

报错信息：                                                                  
  1) 1 : 2b285a2d "before all" hook:                                
     Error: getaddrinfo ENOTFOUND npm npm:80                        
      at errnoException (dns.js:28:10)                              
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26) 
                                                                    
  2) 1 : 2b285a2d "after all" hook:                                 
     Error: getaddrinfo ENOTFOUND npm npm:80                        
      at errnoException (dns.js:28:10)                              
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)

**Comment by yaniswang** [comment]
如果是用uirecorder录制的，不是通过这样的命令回放，具体使用请参考官网：http://uirecorder.com/
