### ISSUE TITLE
app-inspector 2.0有bug，xpath不正确

### ISSUE THREAD

**Issue by jack30639** [alibaba/macaca#578]
![image](https://cloud.githubusercontent.com/assets/12481335/26401674/99a8c7ea-40b9-11e7-9881-64e1ce34d1c3.png)
xpath标签旁边为什么有个红色问号’？‘

元素没有id的时候xpath路径为什么有
//*[@resource-id="android:id/content"]
导致脚本使用这个xpath查找不到元素
还有android.widget.FrameLayout/[1]/android.view.View/[1]，这个index怎么是/[1]/前后都有斜杠啊？

**Comment by xudafeng** [comment]
o

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/commit/6445dbe941e0cc0b297907ad7f7a6ce0da2ed24b

**Comment by jack30639** [comment]
good
