### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by LiuYuXuans** [alibaba/macaca#579]
* **Macaca Version**:
2.0.1

* **Macaca Doctor Logs**:
***************************************
*  version 2.0.0 is outdate           *
*  run: npm i -g app-inspector@2.0.1  *
***************************************

>> port: 5678 was occupied, changed port: 5679
>> xctestwd start with port: 8001
>> XCTestWD version: 1.0.22
undefined
>> iOS device started: df480520215e99beeaf1269e03b5c189e2a8bb11
>> inspector start at: http://172.30.11.41:5679
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:873:11)
      at exports._exceptionWithHostPort (util.js:896:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

* **Operate System**:
mac 10

* **Programming Language**:

**Comment by xudafeng** [comment]
npm i macaca-ios@2.0.10 -g

**Comment by narendra-chandratre** [comment]
@xudafeng I am observing same error.  Do you got solution?

**Comment by nguyenthinam** [comment]
@xudafeng  I ran "npm i macaca-ios@2.0.10 -g" but issue still occurs. Do you have another solution?

**Comment by narendra-chandratre** [comment]
@nguyenthinam Do not provide **macaca-ios** version explicitly. It worked for me as below : "npm i macaca-ios -g"

**Comment by nguyenthinam** [comment]
@narendra-chandratre Thanks for your feedback. I did it, still not get luck. I got the same error.

`>> xctestwd start with port: 8001
>> XCTestWD version: 1.0.42
undefined
>> iOS device started: 707e22e990bc422308e4740eeb6bd7478d89be29
>> inspector start at: http://192.168.1.139:5678
  <-- GET /

  Error: connect ECONNREFUSED 127.0.0.1:8001`

**Comment by laiyuncong8404** [comment]
I got this error too.
app-inspector:2.0.6,
OSX:10.12.3

other ENV as below:
`macaca-doctor version: 2.0.1


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.7.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/xiaoxue/Library/android-sdk-macosx`
  Platforms is set to `/Users/xiaoxue/Library/android-sdk-macosx/platforms/android-25`
  ADB tool is set to `/Users/xiaoxue/Library/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.30
  electron: 1.1.7
  ios: 2.0.22`

**Comment by strawhatboy** [comment]
I got this issue, too.

### Possible Solution
please try to enable the `debug` logger for `xctestwd` dependency:
1. Go to project `/usr/local/lib/node_modules/app-inspector/node_modules/xctestwd`
2. Modify file `./lib/logger.js` to add the debugMode
```js
'use strict';

var logger = require('xlogger');

module.exports = logger.Logger({
  closeFile: true,
  debugMode: true
});
```
3. Run app-inspector again to see the detailed errors

### In my case I have several issues:
1. xctestwd xcodeproj is not well signed, the certificate/team ID is not correct
2. carthage is not installed on my mac (run `brew install carthage` to fix

Hope this would help you guys. :)
