### ISSUE TITLE
切换webview，获取context不稳定，一会可以，一会不行

### ISSUE THREAD

**Issue by jack30639** [alibaba/macaca#581]
切换webview，获取context不稳定，一会可以，一会不行，提示no such no such session，很不稳定啊，怎么解决

**Comment by xudafeng** [comment]
chromedriver 日志有异常吗

**Comment by jack30639** [comment]
![image](https://cloud.githubusercontent.com/assets/12481335/26708571/1539ed14-477f-11e7-9f47-7856255fdd1e.png)
