### ISSUE TITLE
centos7 运行macaca的官方例子desktop-browser-sample.test.js，macaca doctor通过，但是运行时报错：>> ipc.js:26:36 [master] pid:9130 electron child process exited with: general error, you may need xvfb，请问xvbf应该怎么使用来运行例子？

### ISSUE THREAD

**Issue by 562837423** [alibaba/macaca#582]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:centos7

* **Programming Language**:>> ipc.js:26:36 [master] pid:9130 electron child process exited with: general error, you may need xvfb，

**Comment by xudafeng** [comment]
google
