### ISSUE TITLE
macaca2.0.0不支持红米6.0.1/小米note5.1.1，老版本1.2.2是好的；

### ISSUE THREAD

**Issue by clergychen** [alibaba/macaca#584]
* **Macaca Version**:2.0.0

* **Macaca Doctor Logs**: 
>> index.js:17:12 [master] pid:15661 webdriver server start with config:
 { port: '3456',
  verbose: true,
  always: true,
  ip: '10.0.76.243',
  host: 'chenjundeMacBook-Pro.local',
  loaded_time: '2017-05-31 10:36:00' }
>> middlewares.js:17:10 [master] pid:15661 base middlewares attached
>> router.js:127:10 [master] pid:15661 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:15661 Recieve HTTP Request from Client[2017-05-31 10:38:05]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"/Users/chenjun/work/code/QA/Git/macaca-personalDoc/app/personaldoc_test_V_4.2.0_1_false.apk","reuse":"2","platformName":"Android","udid":"a56cb0f7"},"port":3456}
>> session.js:47:10 [master] pid:15661 Creating session, sessionId: 5bd3c457-f4e1-4064-a3d7-c9710edca3db.
>> helper.js:208:12 [master] pid:15661 Using local app form /Users/chenjun/work/code/QA/Git/macaca-personalDoc/app/personaldoc_test_V_4.2.0_1_false.apk

* **Operate
Operate System**:Mac OS 10.12.5

* **Programming Language**:Java

手机：
试过2台手机，用红米note 6.0.1的手机和小米note5.1.1；
现象：
1.运行之前在1.2.2的server上调通的脚本，在Macaca2.0.0上run的时候，手机拉不起来直到IDEA超时报错。
2.相同脚本接到1.2.2的server上可以正常run；
预期结果：
希望能解决小米品牌在最新server上不能run的问题；

**Comment by xudafeng** [comment]
升级新版驱动
