### ISSUE TITLE
win10运行例子报错

### ISSUE THREAD

**Issue by blackmatch** [alibaba/macaca#585]
* **Macaca Version**: 2.0.1

* **Macaca Doctor Logs**:
<img width="576" alt="wechatimg8" src="https://cloud.githubusercontent.com/assets/12443954/26617169/32839462-4606-11e7-88a3-db20c4f2d600.png">

* **Operate System**: win10 64bit

* **Programming Language**: node.js

<img width="417" alt="wechatimg6" src="https://cloud.githubusercontent.com/assets/12443954/26617197/60d82b16-4606-11e7-86a7-66988508d886.png">

**Comment by Archer456** [comment]
@blackmatch    win10跑nodejs 版本的macaca样例的话 参考这个吧
https://testerhome.com/topics/5483

https://testerhome.com/harsayer/topics

**Comment by blackmatch** [comment]
已经解决，把全局模块里的electron模块删掉，然后全局安装electron-rebuilt模块就好了。
