### ISSUE TITLE
mocha回放出错TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by HeartIsBeat** [alibaba/macaca#588]
问题一：
折腾了好久，win10总算能录制安卓机，但是回放PC端的脚本失败了呀！
![image](https://cloud.githubusercontent.com/assets/20472976/26769433/91313576-49e1-11e7-8f32-166e0a0e49f8.png)

问题二：
node6录制的脚本不带async，node7带有async，这有办法兼容么？

**Comment by yaniswang** [comment]
升级为node7或node8，就都兼容了

**Comment by HeartIsBeat** [comment]
@yaniswang 咋mac就能支持pc，安卓，ios三种录制方式。windows不行？

**Comment by yaniswang** [comment]
设计的时候，我们就没考虑到同一个仓库里即有pc，又有无线。
