### ISSUE TITLE
请教下，如何用macaca测试内存泄露等

### ISSUE THREAD

**Issue by rita1014** [alibaba/macaca#589]
我想执行一些操作，看最后内存有无泄露，不知道如何用macaca实现。

**Comment by rita1014** [comment]
ios对于这个需求应该比较大吧

**Comment by SamuelZhaoY** [comment]
用xcode instrument 就好

**Comment by rita1014** [comment]
@SamuelZhaoY  我就是想问macaca怎么和xcode instrument配合？

**Comment by SamuelZhaoY** [comment]
instrument 目前没有cml api，不太好做.  你有什么建议吗？ 欢迎提出来
