### ISSUE TITLE
驱动安装报错，无法安装到最新版

### ISSUE THREAD

**Issue by ftvbftvbq** [alibaba/macaca#59]
* **Macaca Version**:
1.0.26
* **Macaca Doctor**:
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.2.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_31`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/edison/Library/Android/sdk`
  Platforms is set to `/Users/edison/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/edison/Library/Android/sdk/tools/android`

  Installed driver list:

  android: 1.0.10

* **Platform**:
mac

EdisondeMacBook-Air:~ edison$ macaca install ios
macaca-ios is installing for the first time with args: ["install","macaca-ios","--registry=https://registry.npmjs.org/"]

  |     loading...macaca-cli@1.0.34 /usr/local/lib/node_modules/macaca-cli
└── macaca-ios@1.0.30  extraneous

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "macaca-ios" "--registry=https://registry.npmjs.org/"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /usr/local/lib/node_modules/macaca-cli/node_modules/.staging/macaca-cli-4d061662
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/macaca-cli/node_modules/.staging/macaca-cli-4d061662' -> '/usr/local/lib/node_modules/macaca-cli'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/macaca-cli/node_modules/.staging/macaca-cli-4d061662' -> '/usr/local/lib/node_modules/macaca-cli'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "macaca-ios" "--registry=https://registry.npmjs.org/"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path npm-debug.log.3067690861
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3067690861'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3067690861'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/macaca-cli/npm-debug.log

npm install exited with code 254 and signal null
install macaca-ios failed with Error: npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "macaca-ios" "--registry=https://registry.npmjs.org/"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /usr/local/lib/node_modules/macaca-cli/node_modules/.staging/macaca-cli-4d061662
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/macaca-cli/node_modules/.staging/macaca-cli-4d061662' -> '/usr/local/lib/node_modules/macaca-cli'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/macaca-cli/node_modules/.staging/macaca-cli-4d061662' -> '/usr/local/lib/node_modules/macaca-cli'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "macaca-ios" "--registry=https://registry.npmjs.org/"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path npm-debug.log.3067690861
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3067690861'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3067690861'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/macaca-cli/npm-debug.log

EdisondeMacBook-Air:~ edison$ macaca install android
-bash: /usr/local/bin/macaca: No such file or directory

**Comment by xudafeng** [comment]
@ftvbftvbq  使用node4试试

**Comment by ftvbftvbq** [comment]
不行啊，我还要用到es2016的，这么搞，我自己的项目没发搞了，必须要node5以上,我自己的东西才能玩得转。

**Comment by xudafeng** [comment]
@ftvbftvbq 我们看看

**Comment by xudafeng** [comment]
试了下 node6 npm3 ok的

**Comment by xudafeng** [comment]
CI 是ok的，https://travis-ci.org/xudafeng/macaca-test-sample/builds/132251187
