### ISSUE TITLE
android获取当前activity的name

### ISSUE THREAD

**Issue by MrDreamCacher** [alibaba/macaca#592]
* **Macaca Version**:  2.0.3

* **Macaca Doctor Logs**:macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /Users/insomnia/.nvm/versions/node/v6.9.2/bin/node
  node version: v6.9.2

  iOS checklist:

  Xcode Command Line Tools require version: 2347 and above
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_65`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/insomnia/Library/Android/sdk`
  Platforms is set to `/Users/insomnia/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/insomnia/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.3

  Installed driver list:

  android: 2.0.18
  electron: 1.1.6

* **Operate System**:mac os

* **Programming Language**:python

请问UIAutomatorWD有没有提供获取当前Activity Name的方法，之前使用Appium可以通过current_activity属性拿到当前显示的Activity Name

**Comment by xudafeng** [comment]
更新驱动，使用 title()
