### ISSUE TITLE
macaca多台android真机测试失败

### ISSUE THREAD

**Issue by yinjun622** [alibaba/macaca#595]
* **Macaca Version**:

* **Macaca Doctor Logs**:
macaca doctor

  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.8.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/leon/Library/Android/sdk/`
  Platforms is set to `/Users/leon/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/leon/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.4

  Installed driver list:

  android: 2.0.18
  electron: 1.1.6
* **Operate System**:
Mac

* **Programming Language**:
Java

同一天mac，开多个macaca server，指定driver 不同的server port和android udid，
在开启地台时，会出server-side error

```
java.lang.Exception: An unknown server-side error occurred while processing the command.
	at macaca.client.common.Utils.handleStatus(Utils.java:165)
	at macaca.client.common.Utils.postRequest(Utils.java:115)
	at macaca.client.common.Utils.request(Utils.java:154)
	at macaca.client.MacacaClient.touch(MacacaClient.java:1368)
	at macaca.client.MacacaClient.tap(MacacaClient.java:1386)
```
测试代码：https://github.com/yinjun622/macaca-java-biz-sample/tree/master/res

**Comment by xudafeng** [comment]
https://github.com/macacajs/UIAutomatorWD/commit/3a1d1a26860a01911ae88f5033ab15b049e29219

更新驱动
