### ISSUE TITLE
在Linux系统下android平台调用wait_for_element_by_name报错

### ISSUE THREAD

**Issue by jack30639** [alibaba/macaca#596]
同样的脚本，最新的macaca，在windows下调用driver.wait_for_element_by_name可以正常返回结果，在ubuntu系统下调用就报错

![image](https://user-images.githubusercontent.com/12481335/27022841-6335d284-4f82-11e7-82c5-bf0930c519fe.png)
![image](https://user-images.githubusercontent.com/12481335/27022863-77d1d29c-4f82-11e7-8fd3-41119d3a101b.png)

**Comment by upengfei** [comment]
通过name查找元素会出现这个问题，我也是这个问题。

**Comment by upengfei** [comment]
@xudafeng

**Comment by upengfei** [comment]
@xudafeng 请问element_by_name以及wait_for_element_by_name等关于name查找元素的方法啥时候可以修复好？还是这不是bug？

**Comment by upengfei** [comment]
@zenzhu

**Comment by zenzhu** [comment]
window 要是正常的话，window 上日志是什么？我看 linux 发送的请求好像没啥问题啊。

**Comment by upengfei** [comment]
我的是windows 上出现的问题。。重新安装了驱动，清空了缓存。通过name查找还是出现argument was an invalid selector.

**Comment by xudafeng** [comment]
@upengfei 升级Android驱动，如果还有argument was an invalid selector 问题另外提issue，跟linux平台无关
