### ISSUE TITLE
brew命令在Linux下怎么执行

### ISSUE THREAD

**Issue by staver814** [alibaba/macaca#6]
资料里说：before install reliable-slave, you need to install the zeromq library first。
        $ brew install pkg-config
       $ brew install zeromq
我是Linux的系统，上面两条命令该怎么在Linux系统里面执行，或者说，在Linux系统里面是什么命令。
          

thanks

**Comment by xudafeng** [comment]
@staver814 请使用 Linux 系统部署 Maser 模块，Slave 模块部署到 OSX 或 Win 上或有界面的 Linux上。

**Comment by staver814** [comment]
在有界面的Linux的话，slave部署前，pkg-config和zeromq的安装也是用brew命令吗？

**Comment by xudafeng** [comment]
@staver814 目前 Slave 部署只提供 OSX 的，Linux 可以自己查文档部署，不过可以给你参考的 [链接](https://github.com/reliablejs/reliable-master/blob/master/Dockerfile#L26)

**Comment by staver814** [comment]
好的，谢谢

**Comment by xudafeng** [comment]
@staver814 这个能否解决你的问题 https://github.com/Linuxbrew/linuxbrew

**Comment by charyj2000** [comment]
今天在Ubuntu 14.04上配置macaca, 碰到几个问题：
1. macaca doctor
1）显示找不到JAVA_HOME，但其实已经设置了， 没办法只能直接修改原代码，按照isWindows修改的Linux环境，算是搞定了；很奇怪，检查不出来JAVA_HOME；
2）IPv6的域名检查
老是显示0::有错误，原来得设置ipv6的hostname

2. 以上两个奇葩的问题解决了，以为万事大吉，但
启动服务端：macaca server --verbose
启动测试程序：python test/macaca-android-sample.py 
Retry connecting server.... 

这个问题怎么都没有找到原因啊

**Comment by charyj2000** [comment]
Inside Ubuntu 14.04, it always failed to connect to macaca server when running sample test with python3

**Comment by charyj2000** [comment]
Retry connecting server....
Retry connecting server....
Retry connecting server....
Retry connecting server....
