### ISSUE TITLE
Error spawn node_modules/macaca-cli/node_modules/.bin/mocha ENOENT

### ISSUE THREAD

**Issue by markshao** [alibaba/macaca#60]
* **Macaca Version**: 

> 1.0.34

* **Macaca Doctor**:
`node env: /usr/local/bin/node
  node version: v6.2.0

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/cesc/Library/Android/sdk`
  Platforms is set to `/Users/cesc/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/cesc/Library/Android/sdk/tools/android`

  Installed driver list:

  android: 1.0.11`

* **Platform**:

> OSX 10.11.5

1. git clone the sample project macaca-test-sample
2. The device Samsung S5 is plugged with the machine, and the adb detect the connection OK.
3. Run the command under the macaca-test-sample folder 

> platform=android ./node_modules/macaca-cli/bin/macaca-cli run --verbose -d ./macaca-test/macaca-mobile-sample.test.js

Get the error message as following:

`>> index.js:79:12 [master] pid:9778 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '10.12.142.58',
  host: 'cesc-MacBook-Pro.local',
  loaded_time: '2016-05-26 17:35:01' }
>> middlewares.js:30:10 [master] pid:9778 base middlewares attached
>> router.js:118:10 [master] pid:9778 router set
>> webdriver sdk launched
>> macaca-cli-run:89:10 [master] pid:9778 Error: spawn /Users/cesc/spk/github/macacajs/macaca-test-sample/node_modules/macaca-cli/node_modules/.bin/mocha ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
>> Test completed!`

#54

**Comment by xudafeng** [comment]
初步判断是 npm 版本兼容性不好造成的

**Comment by markshao** [comment]
@xudafeng 

>  $ npm --version
3.8.9

我是用cnpm来安装modules的
`alias cnpm="npm --registry=https://registry.npm.taobao.org \
  --cache=$HOME/.npm/.cache/cnpm \
  --disturl=https://npm.taobao.org/dist \
  --userconfig=$HOME/.cnpmrc"`

**Comment by markshao** [comment]
>  $ npm --version
3.9.3

升级到了最新的npm，也是一样的问题，求帮忙看看

**Comment by markshao** [comment]
@xudafeng 问题解决了
是因为/Users/csec/spk/github/macacajs/macaca-test-sample/node_modules/macaca-cli 下没有node_modules目录，导致mocha实际是没有找到文件，导致不能启动进程

我去/Users/csec/spk/github/macacajs/macaca-test-sample/node_modules/macaca-cli下手动执行了一次

> cnpm i

**Comment by xudafeng** [comment]
@lihuazhang 像是 `--unsafe-perm=true` 问题
