### ISSUE TITLE
android-重复安装UIautomator等

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#600]
* **Macaca Version**: 2.0.4

* **Macaca Doctor Logs**:
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/joko/Library/Android/sdk`
  Platforms is set to `/Users/joko/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/joko/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.22
  ios: 2.0.15

* **Operate System**:
macos ：10.12.4
小米3：MIUI 8 7.5.25开发版

* **Programming Language**:python
* 步骤：链接手机，初始化
* 问题描述：每次运行手机均会提示需安装UIautomator与com.macaca.android.testing.test
注：请问这两个是必须每次重新安装吗？我记得之前unlock有过处理，此处是否也可安装后即忽略

**Comment by atomtong** [comment]
可以考虑优化一下流程。这样做主要确保安装的client 是最新的

**Comment by xudafeng** [comment]
配置reuse参数
