### ISSUE TITLE
Macaca app-inspector获取xpath问题

### ISSUE THREAD

**Issue by Leo-80** [alibaba/macaca#602]
* **Macaca Version**:
2.0.4
* **Macaca Doctor Logs**:
MacBook-Pro:~ xx$ macaca doctor

  macaca-doctor version: 2.0.1
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:
  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.6.0_65`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.11 [out-of-date]
* **Operate System**:
mocOS Sierra 10.12.5
* **Programming Language**:
python

最近在使用Macaca app-inspector功能时发现，通过app-inspector获取的xpath 有时候在测试运行时候会提示 无法通过xpath 捕获控件，并同app-inspector 获取横屏应用的xpath时候完全不能使用 。
我使用的命令如下

app-inspector -u UDID --verbose 
问题1：
获取xpath不准确问题是本身存在的问题还是我在用法出错导致？如是我使用出错还请指导
问题2
横屏情况下，点击屏幕获取xpath都是错位基本上不能定位xpath次问题是本身存在问题还是我在用法出错导致？如是我使用出错还请指导

**Comment by rita1014** [comment]
我也有此问题

**Comment by xudafeng** [comment]
升级inspector
