### ISSUE TITLE
iOS真机测试，现在是对XCTestWD重新进行签名安装到手机上吗？

### ISSUE THREAD

**Issue by 15910268591** [alibaba/macaca#605]

**Comment by Leo-80** [comment]
官方文档（https://macacajs.github.io/zh/environment-setup）环境配置中iOS真机环境中已经表明需要替换成你自己的teamid

**Comment by 15910268591** [comment]
teamid换成自己的账号了，真机还是运行不起来，之前需要wda的时候需要重新签名装到手机上，现在换成XCTestWD了，只需要改一下teamID就行了吗？

**Comment by Leo-80** [comment]
你的报错信息是什么，可以发出来看看 如果你按照官方的步骤做了的话应该不会有问题

**Comment by 15910268591** [comment]
>> xctest-client.js:173:14 [master] pid:46656 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:46656 2017-06-19 10:34:33.033 xcodebuild[46662:2695093] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/User/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/A3FB65AA-C0CC-4678-94D3-B35170658040/Session-XCTestWDUITests-2017-06-19_103432-sOSxNK.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/User/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/A3FB65AA-C0CC-4678-94D3-B35170658040/Session-XCTestWDUITests-2017-06-19_103432-sOSxNK.log}

>> xctest-client.js:173:14 [master] pid:46656 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:46656 
Testing failed:

>> xctest-client.js:173:14 [master] pid:46656 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:46656 	No profiles for 'XCTestWD.XCTestWD' were found:  Xcode couldn't find a provisioning profile matching 'XCTestWD.XCTestWD'.
	Code signing is required for product type 'Application' in SDK 'iOS 10.3'
	Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/User/Library/Developer/Xcode/DerivedData/XCTestWD-evljajykmolwzobrozpobiggeeea/Logs/Test/A3FB65AA-C0CC-4678-94D3-B35170658040/Session-XCTestWDUITests-2017-06-19_103432-sOSxNK.log
** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:173:14 [master] pid:46656 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:46656 killing deviceLogProc pid: 46659
>> xctest-client.js:260:14 [master] pid:46656 killing runnerProc pid: 46662
>> xctest-client.js:266:14 [master] pid:46656 killing iproxyProc pid: 46661
>> xctest-client.js:183:14 [master] pid:46656 xctest client exit with code: 65, signal: null
>> xctest-client.js:211:14 [master] pid:46656 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:145:16 [master] pid:46656 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:247:14 [master] pid:46656 Fail to start xctest: undefined
undefined
>> iOS device started: (XXXXXXX)
>> inspector start at: http://192.168.35.9:5678
  <-- GET /
>> helper.js:94:16 [master] pid:46656 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

  <-- GET /favicon.ico
  --> GET /favicon.ico 404

报错信息

**Comment by Leo-80** [comment]
![1](https://user-images.githubusercontent.com/2002280/27271602-38240e96-54f8-11e7-986e-747b9cfa3fa4.png)

这是我这里配置 供你参考

**Comment by zsmjluo** [comment]
@Leo-80 Bundle Identifier要修改吧

**Comment by 15910268591** [comment]
将XCTestWD在真机上运行，更换自己的账号，重新签名得修改bundleID，运行提示BundleId XCTestWD.XCTestWD does not exist.请问怎么解决？
>> xctest-client.js:173:14 [master] pid:63587 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:63587 	Test target XCTestWDUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **


>> xctest-client.js:173:14 [master] pid:63587 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:63587 killing deviceLogProc pid: 63597
>> xctest-client.js:260:14 [master] pid:63587 killing runnerProc pid: 63600
>> xctest-client.js:266:14 [master] pid:63587 killing iproxyProc pid: 63599
>> xctest-client.js:183:14 [master] pid:63587 xctest client exit with code: 65, signal: null
>> xctest-client.js:211:14 [master] pid:63587 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:145:16 [master] pid:63587 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:247:14 [master] pid:63587 Fail to start xctest: undefined
>> macaca-ios.js:163:12 [master] pid:63587 Trying to start xctestwd server...
BundleId XCTestWD.XCTestWD does not exist.
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:63587 xcode version: 8.3.2
>> XCTestWD version: 1.0.38

**Comment by qwezxcjohnny** [comment]
同楼上一样，即使修改了xctest.js里的bundleid也会提示

**Comment by pmhgo** [comment]
我看 XCTestWD和XCTestWDTest都不能build有错误，否则真机用不了。我iphone6 ios9.3 的真机没弄成功。而iphone5c ios10.0.1的真机成功了。

**Comment by mijiawei** [comment]
同样提示：BundleId XCTestWD.XCTestWD does not exist.

**Comment by xudafeng** [comment]
提供真机测试详细说明文档

**Comment by lovexiaov** [comment]
看完真机说明文档也没能解决此问题，有遇到同样问题的同学点下赞~

**Comment by xinxinga** [comment]
XCTestWD和XCTestWDTest 在xcode 里 build success。
问题
1） product-> test , 安装到测试机上，提示test fail
2) command run test, 提示 BundleId XCTestWD.XCTestWD does not exist.
>> XCTestWD version: 1.4.18
>> xctest-client.js:230:20 [master] pid:96860 please check project: /Users/xxx/npm-global/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
