### ISSUE TITLE
Macaca-ios 执行测试用例时高概率出现socket hang up, 请帮忙解答下，多谢！

### ISSUE THREAD

**Issue by Sandu1213** [alibaba/macaca#606]
* **Macaca Version**:
      2.0.4
* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.0.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_77`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:
  ios: 2.0.18

* **Operate System**:
    MAC 10.12.5
* **Programming Language**:  JS

>> responseHandler.js:11:12 [master] pid:54672 Recieve HTTP Request from Client[2017-06-16 09:07:16]: method: POST url: /wd/hub/session/a76c18ab-4f69-4826-88f6-b17a3228843f/element/11DEAAB9-F00D-4C60-BCAD-53F71D8291C0/click, jsonBody: {}
>> proxy.js:55:14 [master] pid:54672 Proxy: /wd/hub/session/a76c18ab-4f69-4826-88f6-b17a3228843f/element/11DEAAB9-F00D-4C60-BCAD-53F71D8291C0/click:POST to http://127.0.0.1:8001/wd/hub/session/294D72C8-2E4F-4B54-BA06-39AB64073E6F/element/11DEAAB9-F00D-4C60-BCAD-53F71D8291C0/click:POST with body: {}
>> **proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: socket hang up**

省略部分日志
>> responseHandler.js:11:12 [master] pid:54672 Recieve HTTP Request from Client[2017-06-16 09:07:38]: method: POST url: /wd/hub/session/a76c18ab-4f69-4826-88f6-b17a3228843f/element, jsonBody: {"using":"id","value":"id_gear_btn_20x20"}
>> proxy.js:55:14 [master] pid:54672 Proxy: /wd/hub/session/a76c18ab-4f69-4826-88f6-b17a3228843f/element:POST to http://127.0.0.1:8001/wd/hub/session/294D72C8-2E4F-4B54-BA06-39AB64073E6F/element:POST with body: {"using":"id","value":"id_gear_btn_20x20"}
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:54672 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:54:12 [master] pid:54672 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:60:14 [master] pid:54672 Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

**Comment by Sandu1213** [comment]
已经参考过#571 ， 使用过brew unlink/install/link 的方法，还是存在问题，请问是XCTest的稳定性问题么？还是我的环境配置不对？目前最多跑到80多个cases就挂了。请回复下，🙏

**Comment by chengliangbuct** [comment]
我也经常遇到，我一般是杀掉占用 8900 端口的进程来解决，通过：lsof -i:8900 获取进程号，kill 掉

**Comment by PENGZHONGLING** [comment]
请问解决了么？  我也经常执行时随机出现socket hang up问题

**Comment by Sandu1213** [comment]
@PENGZHONGLING 还没解决了, 查过一些资料，暂时没有找到好的解决方法（WDA也会出现这样的问题，只是概率相对低些），期待 @SamuelZhaoY 的解决方案。

**Comment by changming1987117** [comment]
请问这个问题现在解决了么？我启动就会出现hang up

**Comment by qwezxcjohnny** [comment]
同样遇到了这个问题 执行都不稳定

**Comment by PENGZHONGLING** [comment]
@Sandu1213 嗯嗯～。坐等

**Comment by SamuelZhaoY** [comment]
新版本中对socket hangup 易产生的地方做了保护， 请更新
