### ISSUE TITLE
XCTestWD XCTestWDUITests真机编译运行报错

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#607]
模拟器运行没问题，真机编译时XCTestWDUITests报错如下：
**Shell Script Invocational Error
Command /bin/sh failed with exit code162**

  版本信息如下：
  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.1.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.18

**Comment by Sandu1213** [comment]
TARGETS ->XCTestWDUITests 下,Build Phases ->第一个Run script 里面的shell是针对模拟器的，可以把脚本注释掉，我是这么解决的。但不知道是否合理。

**Comment by zsmjluo** [comment]
@Sandu1213 💯

**Comment by bluesky12345** [comment]
遇到了同样的问题，使用上面的方法解决了。十分感谢！手动点个赞！
