### ISSUE TITLE
升级macaca驱动之后，touch drag失效

### ISSUE THREAD

**Issue by BachWings** [alibaba/macaca#609]
log:
>> proxy.js:55:14 [master] pid:32668 Proxy: /wd/hub/session/0c76ab60-72f5-404d-bf51-7a0d02dc2bb0/window/current/size:GET to http://127.0.0.1:9002/wd/hub/session/:sessionId/window/current/size:GET with body: {}
>> proxy.js:83:20 [master] pid:32668 Got response with status 200: {"status":0,"value":{"height":1812,"width":1080},"sessionId":"0c76ab60-72f5-404d-bf51-7a0d02dc2bb0"}
>> session.js:107:14 [master] pid:32668 Send HTTP Respone to Client[2017-06-19 19:48:07]: {"status":0,"value":"{\"height\":1812,\"width\":1080}","sessionId":"0c76ab60-72f5-404d-bf51-7a0d02dc2bb0"}
>> responseHandler.js:11:12 [master] pid:32668 Recieve HTTP Request from Client[2017-06-19 19:48:07]: method: POST url: /wd/hub/session/0c76ab60-72f5-404d-bf51-7a0d02dc2bb0/actions, jsonBody: {"actions":[{"fromX":540,"fromY":906,"toX":270,"toY":906,"steps":3,"type":"drag"}]}

获取屏幕宽度然后进行drag操作，日志没有response，到这里就没了进行下一步操作去了

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/pull/48

**Comment by BachWings** [comment]
@xudafeng 安卓系统，不好意思 问题里忘记写了

**Comment by xudafeng** [comment]
wd.java是新版吗？

**Comment by BachWings** [comment]
@xudafeng wd.py是最新的

**Comment by xudafeng** [comment]
@BachWings

看着没什么问题

https://travis-ci.org/macaca-sample/sample-nodejs/jobs/242046364#L2830

你换个坐标试试

**Comment by BachWings** [comment]
>> index.js:18:12 [master] pid:30112 webdriver server start with config:
 { port: 3457,
  verbose: true,
  always: true,
  ip: '192.168.2.207',
  host: 'PC-20170425PLEE',
  loaded_time: '2017-06-20 11:47:13' }
>> middlewares.js:17:10 [master] pid:30112 base middlewares attached
>> router.js:127:10 [master] pid:30112 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:14]: method: GET url: /wd/hub/status, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:14]: {"sessionId":"","status":0,"value":"{\"build\":{},\"os\":{\"arch\":\"x64\",\"name\":\"win32\",\"version\":\"\"}}"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:14]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"Android","udid":"192.168.19.101:5555","package":"cn.pocketwallet.pocketwallet","autoAcceptAlerts":true}}
>> session.js:47:10 [master] pid:30112 Creating session, sessionId: bbe7c70b-99ae-47c7-887a-a9bbc261b603.
>> uiautomator-client.js:56:14 [master] pid:30112 INSTRUMENTATION_STATUS: numtests=1


INSTRUMENTATION_STATUS: stream=


com.macaca.android.testing.UIAutomatorWD:


INSTRUMENTATION_STATUS: id=AndroidJUnitRunner


INSTRUMENTATION_STATUS: test=MacacaTestRunner


INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD


INSTRUMENTATION_STATUS: current=1


INSTRUMENTATION_STATUS_CODE: 1



>> uiautomator-client.js:56:14 [master] pid:30112 INSTRUMENTATION_STATUS: stream=


UIAutomatorWD->http://localhost:9003<-UIAutomatorWD


INSTRUMENTATION_STATUS_CODE: 0



>> UIAutomatorWD http server ready
>> responseHandler.js:47:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:24]: {"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603","status":0,"value":"{\"platformName\":\"Android\",\"udid\":\"192.168.19.101:5555\",\"package\":\"cn.pocketwallet.pocketwallet\",\"autoAcceptAlerts\":true}"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:24]: method: POST url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/element, jsonBody: {"using":"class name","value":"android.widget.ImageView"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":null}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/element:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/element:POST with body: {"using":"class name","value":"android.widget.ImageView"}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:24]: {"status":0,"value":"{\"ELEMENT\":\"1\"}","sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:24]: method: GET url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/element/1/displayed, jsonBody: {}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/element/1/displayed:GET to http://127.0.0.1:9003/wd/hub/session/:sessionId/element/1/displayed:GET with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"value":true,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:24]: {"status":0,"value":"true","sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:24]: method: GET url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/window/current/size, jsonBody: {}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/window/current/size:GET to http://127.0.0.1:9003/wd/hub/session/:sessionId/window/current/size:GET with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"value":{"height":1184,"width":768},"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:24]: {"status":0,"value":"{\"height\":1184,\"width\":768}","sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:24]: method: POST url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/actions, jsonBody: {"actions":[{"fromX":384,"fromY":592,"toX":153.60000000000002,"toY":592,"steps":3,"type":"drag"}]}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/actions:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/actions:POST with body: {"actions":[{"fromX":384,"fromY":592,"toX":153.60000000000002,"toY":592,"steps":3,"type":"drag"}]}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:24]: {"status":0,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:25]: method: GET url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/window/current/size, jsonBody: {}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/window/current/size:GET to http://127.0.0.1:9003/wd/hub/session/:sessionId/window/current/size:GET with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"value":{"height":1184,"width":768},"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:25]: {"status":0,"value":"{\"height\":1184,\"width\":768}","sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:25]: method: POST url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/actions, jsonBody: {"actions":[{"fromX":384,"fromY":592,"toX":153.60000000000002,"toY":592,"steps":3,"type":"drag"}]}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/actions:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/actions:POST with body: {"actions":[{"fromX":384,"fromY":592,"toX":153.60000000000002,"toY":592,"steps":3,"type":"drag"}]}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:26]: {"status":0,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:27]: method: GET url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/window/current/size, jsonBody: {}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/window/current/size:GET to http://127.0.0.1:9003/wd/hub/session/:sessionId/window/current/size:GET with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"value":{"height":1184,"width":768},"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:27]: {"status":0,"value":"{\"height\":1184,\"width\":768}","sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:27]: method: POST url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/actions, jsonBody: {"actions":[{"fromX":384,"fromY":592,"toX":153.60000000000002,"toY":592,"steps":3,"type":"drag"}]}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/actions:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/actions:POST with body: {"actions":[{"fromX":384,"fromY":592,"toX":153.60000000000002,"toY":592,"steps":3,"type":"drag"}]}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:28]: {"status":0,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:29]: method: POST url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/element, jsonBody: {"using":"class name","value":"android.widget.ImageView"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/element:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/element:POST with body: {"using":"class name","value":"android.widget.ImageView"}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:29]: {"status":0,"value":"{\"ELEMENT\":\"1\"}","sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:29]: method: POST url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/element/1/click, jsonBody: {}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:30112 Proxy: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/element/1/click:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/element/1/click:POST with body: {}
>> proxy.js:83:20 [master] pid:30112 Got response with status 200: {"status":0,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> session.js:107:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:29]: {"status":0,"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603"}
>> responseHandler.js:11:12 [master] pid:30112 Recieve HTTP Request from Client[2017-06-20 11:47:29]: method: GET url: /wd/hub/session/bbe7c70b-99ae-47c7-887a-a9bbc261b603/screenshot, jsonBody: {}
>> responseHandler.js:47:14 [master] pid:30112 Send HTTP Respone to Client[2017-06-20 11:47:30]: {"sessionId":"bbe7c70b-99ae-47c7-887a-a9bbc261b603","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAAAwAAAAUACAYAAADwUTW0AAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzsvWuQJNd15/e792bWu/rd835hBjN4kxAeJAFJFihKJPiAlpJoeb2r8DpsyesvDu+GI+wNO8Jf7A3vByvsCIW9qw07NvaDVyvtSg5TVIggCBLiY0gBhEAAJAgMgHlPTz+ru55ZmXkf/nCzqqt7egY9QM9ME8gfojHdWVWZWVWZ955z7v+cI/7oj/7IkZOTk5OTc8dxOAcCgdOOtcYS337uL2lcuIBOU2w/IU4TrDVILFiLA3AOrN+DkNfu9cDJe/jU019k37HjKKEIlARxO99XTk5Ozu4iuNMnkJOTk5OTAw4wIEBbUEIhreTqxat0..."}


换了坐标还是这样，所有都重新安装了一遍

**Comment by xudafeng** [comment]
https://travis-ci.org/macaca-sample/sample-nodejs/builds/248389438 参考这个 有drag示例
