### ISSUE TITLE
Linux 无法调起chrome浏览器【目录权限问题】

### ISSUE THREAD

**Issue by yuxinwei** [alibaba/macaca#61]
macaca -v :1.0.24
macaca doctor: 
 Node.js checklist:
  node env: /data/nodejs/bin/node
  node version: v4.4.4
问题描述：
我在linux搭建了两套macaca，其中一台正常运行，另一台无法调起chrome浏览器
步骤描述：
1、启动macaca server -p 3456 &
2、make test-pc时，提示如下错误
>> webdriver sdk launched
>> chromedriver bin path: /data/nodejs/lib/node_modules/macaca-cli/node_modules/macaca-chromedriver/exec/chromedriver
>> Kill all running chromedriver process by: ps -ef | grep chromedriver | grep -v grep | grep -e '--port=' | awk '{ print $2 }' | xargs -r kill -15
fs.js:60
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^
Error: EACCES: permission denied, open '/data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/logs/restful-2016_05_27.log'
    at Error (native)
3、kill chrome进程时，再次执行make test-pc，问题还是一样
请帮忙看看

**Comment by xudafeng** [comment]
@zenzhu kill 那里是不是兼容有问题

**Comment by zenzhu** [comment]
@yuxinwei 应该不用先 macaca server 把，这样会重复启动服务器，直接 make test-pc 就可以了。

**Comment by yuxinwei** [comment]
[test1@zabbix ~/Desktop]# ps -ef|grep macaca
test1     4227  3517  0 13:10 pts/1    00:00:00 grep macaca

不启动后，直接执行make test-pc出现以下提示：
make test-pc
macaca run --verbose -d ./macaca-test/macaca-desktop-sample.test.js
*************************************
*  version 1.0.24 is outdate        *
*  run: npm i -g macaca-cli@1.0.34  *
*************************************
>> index.js:93:12 [master] pid:4192 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '172.16.1.180',
  host: 'zabbix',
  loaded_time: '2016-05-27 13:09:46' }
>> middlewares.js:30:10 [master] pid:4192 base middlewares attached
>> router.js:117:10 [master] pid:4192 router set
>> webdriver sdk launched
>> 
>> 
>>   macaca desktop sample
>> responseHandler.js:24:12 [master] pid:4192 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"browserName":"chrome","platformName":"desktop","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:24:10 [master] pid:4192 Creating session, sessionId: 2a3c0150-45d7-4bde-b0a1-c8c24836bb4e.
>> chromedriver bin path: /data/nodejs/lib/node_modules/macaca-cli/node_modules/macaca-chromedriver/exec/chromedriver
>> Kill all running chromedriver process by: ps -ef | grep chromedriver | grep -v grep | grep -e '--port=' | awk '{ print $2 }' | xargs -r kill -15
fs.js:60
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^
Error: EACCES: permission denied, open '/data/nodejs/lib/node_modules/macaca-cli/node_modules/webdriver-server/logs/restful-2016_05_27.log'
    at Error (native)
make: *** [test-pc] Error 1

**Comment by zenzhu** [comment]
@yuxinwei 应该是你这个目录的权限问题吧，给你 nodejs 下面的目录加权限。

**Comment by yuxinwei** [comment]
@zenzhu ，@达峰，问题解决了，直接加个777即可，非常感谢。

**Comment by xudafeng** [comment]
@zenzhu 加到我们的文档上

**Comment by xudafeng** [comment]
#62
