### ISSUE TITLE
Swipe报404 not found

### ISSUE THREAD

**Issue by BachWings** [alibaba/macaca#614]
Android
Windows
Python
Macaca  都为最新版本

>> proxy.js:83:20 [master] pid:8960 Got response with status 200: {"status":0,"value":{"height":1216,"width":800},"sessionId":"6e6f9578-747d-4f06-bccd-54efb7317cd5"}
>> session.js:107:14 [master] pid:8960 Send HTTP Respone to Client[2017-06-21 16:57:15]: {"status":0,"value":"{\"height\":1216,\"width\":800}","sessionId":"6e6f9578-747d-4f06-bccd-54efb7317cd5"}
>> responseHandler.js:11:12 [master] pid:8960 Recieve HTTP Request from Client[2017-06-21 16:57:15]: method: POST url: /wd/hub/session/6e6f9578-747d-4f06-bccd-54efb7317cd5/element/temp/swipe, jsonBody: {"startX":400,"startY":608,"endX":200,"endY":608,"duration":200}
>> responseHandler.js:23:14 [master] pid:8960 Send HTTP Respone to Client[2017-06-21 16:57:15]: 404 Not Found

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.py/pull/29

**Comment by xudafeng** [comment]
请使用touch swipe废弃了
