### ISSUE TITLE
Electron不支持自定义UA

### ISSUE THREAD

**Issue by ImTomy** [alibaba/macaca#617]
目前webapp UI自动化用于冒烟、日常回归，但无法应用于线上巡检。
 业内很多业务务需要在微信、支付宝内使用。所以需要自定义  UA才行
微信：mozilla/5.0 (iphone; cpu iphone os 5_1_1 like mac os x) applewebkit/534.46 (khtml, like gecko) mobile/9b206 micromessenger/5.0
支付宝： Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 AlipayClient/10.0.3.020920

 并且electron是支持自定义UA的，参考文档：
webview：[https://electron.atom.io/docs/api/webview-tag/#useragent](https://electron.atom.io/docs/api/webview-tag/#useragent)
browser： [https://electron.atom.io/docs/api/browser-window/#winloadurlurl-options](https://electron.atom.io/docs/api/browser-window/#winloadurlurl-options
)
建议添加这一功能，扩大UI自动化在平时工作中的应用范围。

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-electron/pull/17

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/sample-nodejs/commit/92b87e4271e84626a060990e5fe7b6cb99ae40a6

**Comment by xudafeng** [comment]
https://github.com/macacajs/macacajs.github.io/commit/430792d3be1e8c09d4c2dffc8b8b693b55d33e19
