### ISSUE TITLE
运行官网的 快速入手 卡住

### ISSUE THREAD

**Issue by sdlbp** [alibaba/macaca#618]
localhost:sample-nodejs lbp$ make 

make test-ios               Test sample for iOS
make test-android           Test sample for Android
make test-ios-safari        Test sample for iOS Safari
make test-android-chrome    Test sample for Android Chrome
make test-desktop-electron  Test sample for Desktop PC
make test-desktop-chrome    Test sample for Desktop PC
make custom-reporter        Test sample for PC with custom reporter
localhost:sample-nodejs lbp$ make test-ios 
macaca doctor

  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.11.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.18

platform=ios macaca run --verbose -d ./macaca-test/mobile-app-sample.test.js
>> port: 3456 was occupied, changed port: 3461
>> index.js:18:12 [master] pid:2105 webdriver server start with config:
 { port: 3461,
  verbose: false,
  always: true,
  window: true,
  ip: '10.12.141.52',
  host: 'localhost',
  loaded_time: '2017-06-23 19:12:05' }
>> middlewares.js:17:10 [master] pid:2105 base middlewares attached
>> router.js:127:10 [master] pid:2105 router set
>> webdriver sdk launched
[ '/Users/lbp/Desktop/sample-nodejs/node_modules/.bin/mocha',
  './macaca-test/mobile-app-sample.test.js',
  '--colors',
  '--verbose' ]
>> 

>> 

>>   macaca mobile sample

**Comment by sdlbp** [comment]
卡在  macaca mobile sample

**Comment by 1214503056** [comment]
我也卡住了

**Comment by 1214503056** [comment]
xctest-client.js:173:14 [master] pid:14962 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:14962 
Testing failed:
	Test target XCTestWDUITests encountered an error (No Info.plist found for application at path /Users/lucy/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist If you believe this error represents a bug, please attach the log file at /Users/lucy/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Logs/Test/B3EB12E4-F826-446A-A8EC-1CFB7A12924A/Session-XCTestWDUITests-2017-06-27_194307-9d087j.log)
** TEST FAILED **
我是这个错误。。。

**Comment by xudafeng** [comment]
参考ci环境的log 方便排查环境问题 https://travis-ci.org/macaca-sample/sample-nodejs/builds/248389438
