### ISSUE TITLE
app-inspector -u 执行异常

### ISSUE THREAD

**Issue by beloving** [alibaba/macaca#619]
[

* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

app-inspector -u fa339c6c7d52  卡住了
错误代码：  对应的apk路径确保有对应Apk文件，并且adb push执行其他文件是OK的，数据线是通的，真机测试

{ Error: Command failed: D:\code\sdk/platform-tools/adb -s fa339c6c7d52 push C:\Users\yu\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'D:\\code\\sdk/platform-tools/adb -s fa339c6c7d52 push C:\\Users\\yu\\AppData\\Roaming\\npm\\node_modules\\app-inspector\\node_modules\\uiautomatorwd\\app\\build\\outputs\\apk\\app-debug.apk /data/local/tmp/com.macaca.android.testing' }

**Comment by xudafeng** [comment]
macaca doctor

**Comment by summerww** [comment]
我也遇到的同样的问题，解决了吗？ @beloving  
  @xudafeng 我在真机上新建了/data/local/tmp/目录，但是还是会报错
macaca doctor 
![default](https://user-images.githubusercontent.com/30616663/28812490-82bf8fc0-76c7-11e7-9775-24545815d922.png)
app-inspector -u DQPNG67L99999999
![default](https://user-images.githubusercontent.com/30616663/28812585-f8fa003a-76c7-11e7-9f96-1ae37b510763.png)

**Comment by dshaha** [comment]
我之前也遇到过这个问题，看了一眼楼上的配置，我建议查看一下sdk有没有装android support repository,如果没装也有可能出现上面的问题

**Comment by zivyll** [comment]
macaca-doctor version: 2.0.4
node version: v8.9.1
JAVA version is `1.8.0_111`
gradle is installed, version: 3.3

模拟器真机都没问题，建议重装下环境，使用最新版本。 @beloving @summerww
