### ISSUE TITLE
com.macaca.android.testing和com.macaca.android.testing.test的几个疑问

### ISSUE THREAD

**Issue by JunchengChen** [alibaba/macaca#620]
1. 这2个包有什么区别？为什么要2个？UIAutomatorWD对应com.macaca.android.testing，com.macaca.android.testing.test的源码在哪里？
2. UIAutomator.prototype.init为什么一定非要卸载了这2个包再重新安装？已经安装过是否可以省略？
3. 内网是否有钉钉群交流？

**Comment by xudafeng** [comment]
- 搜索下UIAutomator2用法
- 搜索下
- 搜索下
