### ISSUE TITLE
No Info.plist found for application at path

### ISSUE THREAD

**Issue by 1214503056** [alibaba/macaca#621]
xctest-client.js:173:14 [master] pid:14962 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:14962 
Testing failed:
	Test target XCTestWDUITests encountered an error (No Info.plist found for application at path /Users/lucy/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist If you believe this error represents a bug, please attach the log file at /Users/lucy/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Logs/Test/B3EB12E4-F826-446A-A8EC-1CFB7A12924A/Session-XCTestWDUITests-2017-06-27_194307-9d087j.log)
** TEST FAILED **

您好！按照官网配置操作，macaca doctor没有问题，但是总是报错No Info.plist found for application at path /Users/lucy/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Build/Products/Debug-iphonesimulator/XCTestWD.app/Info.plist，进入文件夹查看了，真的没有，为什么没有呢

**Comment by xudafeng** [comment]
升级最新macaca-ios
