### ISSUE TITLE
waitForElement( )方法中timeout参数设置无效？

### ISSUE THREAD

**Issue by 562837423** [alibaba/macaca#624]
* **Macaca Version**:

* **Macaca Doctor Logs**: 2.0.4

* **Operate System**:

* **Programming Language**:node.js

**Comment by 562837423** [comment]
waitForElement( )方法中timeout参数设置为10000、3000、100、0等均无区别，但是感觉正常情况下，在元素出现前如果等待超过了设定的timeout就会报错吗？

**Comment by yihuineng** [comment]
这边测试是有效的 

问题久远关闭，如仍有问题，可再次提issue并提供详细环境信息&复现路径
