### ISSUE TITLE
部署 macaca 的时候找不到已安装的 xcode

### ISSUE THREAD

**Issue by wangpc** [alibaba/macaca#626]
* **Macaca Version**: 2.0.4

* **Macaca Doctor Logs**: 
macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.9.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zijing/Library/Android/sdk`
  Platforms is set to `/Users/zijing/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/zijing/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.0

  Installed driver list:

  ios: 2.0.20

* **Operate System**: macOS 10.12.5

* **Programming Language**: objc

 已经安装了最新版的 xcode 但是一直提示说 xcode is uninstalled 安装最新版的 beta 的 xocde9也不行

**Comment by xudafeng** [comment]
参考ci环境的配置 https://travis-ci.org/macaca-sample/sample-nodejs

**Comment by wangpc** [comment]
问题已经解决 不是 macaca 的问题, 但是也不是参考 CI 环境配置的问题, 愿意如下:

如果在安装 xcode 之前已经安装了 xcode command line tool 则会将 developer 激活到 xcode command line 的安装路径下, 此时安装 macaca-ios 也会报错, 说找不到 xcode , 具体表现为
```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

解决方法: 利用 xcode-select 来制定 developer 路径:
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

问题得以解决

**Comment by xyq929** [comment]
如果只做安卓测试，web或ios的环境都需要配置吗？
