### ISSUE TITLE
IOS 下 在文本中清除clear()无法清除

### ISSUE THREAD

**Issue by luozhang002** [alibaba/macaca#628]
是这样的，这两天在调研macacajs，用来自动化测试我们的APP，但是在用写测试脚本时，IOS遇到个问题，有一个文本框的内容可以塞进去，但是我调用clear（）方法却清除不了，我写的代码如下。

![2](https://user-images.githubusercontent.com/5653578/27727419-f4f034da-5db0-11e7-87c0-93ada4d5eee9.png)

使用的macaca 版本具体如下：

* **Macaca Version**: 2.0.4 

* **Macaca Doctor Logs**: node env: /usr/local/bin/node
  node version: v6.9.2

  iOS checklist:

  Xcode Command Line Tools require version: 2347 and above
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

* **Operate System**: Mac OS

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/sample-nodejs/blob/master/macaca-test/wd-extend.js#L25

**Comment by luozhang002** [comment]
我当时写你的时候就是参考这个代码的，这个代码一开始调用clear（）的时候第一个文本框里面本来就是空的，如果我等文本框里面填入东西，在调用clear()的时候文本框的内容清空不了

**Comment by luozhang002** [comment]
而且我本地基于你这个DEMO，在一个文本框里先sendkeys（a）然后再调用clear()，然后在调用sendkeys(b)的时候 ,a和b都是存在的

**Comment by xray2008** [comment]
同遇到此问题，无法clear

**Comment by xudafeng** [comment]
wd.py 升级最新版即可
