### ISSUE TITLE
iOS真机socket hang up

### ISSUE THREAD

**Issue by changming1987117** [alibaba/macaca#629]
* **Macaca Version**:
2.0.20
* **Macaca Doctor Logs**:

>> xctest-client.js:173:14 [master] pid:38501 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:38501 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/pc/d1nyvgtd2sn8svyfww1384f80000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.60Aev7/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:38501 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:38501 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/pc/d1nyvgtd2sn8svyfww1384f80000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.60Aev7/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:38501 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:61:22 [master] pid:38501 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:38501 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:38501 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:38501 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:172:14 [master] pid:38501 Failing tests:

>> xctest-client.js:173:14 [master] pid:38501 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:38501 	-[XCTextWDRunner testRunner()]
	-[XCTextWDRunner testRunner()]
** TEST FAILED **

* **Operate System**:
macOS Sierra
* **Programming Language**:
Java

**Comment by qwezxcjohnny** [comment]
>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:1936 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/27d52726292a4a54383ff432dfab34f0/e053977a549d25528eb031ed88586240caa520c8/XCTestWDUITests-Runner.app
state->new_bundle: /Users/admin/Library/Developer/Xcode/DerivedData/XCTestWD-awyzvjjpazhyedbexovronjzyepo/Build/Products/Debug-iphoneos/XCTestWDUITests-Runner.app
state->dst_bundle: /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.nW22Lp/XCTestWDUITests-Runner.app_sparse.ipa/Payload//XCTestWDUITests-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.nW22Lp/XCTestWDUITests-Runner.app_sparse.ipa

>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:1936 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.nW22Lp/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:1936 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.nW22Lp/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:172:14 [master] pid:1936 Failing tests:
	-[XCTextWDRunner testRunner()]

>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:1936 ** TEST FAILED **


>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:1936 killing deviceLogProc pid: 1945
>> xctest-client.js:260:14 [master] pid:1936 killing runnerProc pid: 1948
>> xctest-client.js:266:14 [master] pid:1936 killing iproxyProc pid: 1947
>> xctest-client.js:183:14 [master] pid:1936 xctest client exit with code: 65, signal: null
>> xctest-client.js:211:14 [master] pid:1936 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:145:16 [master] pid:1936 devicelog exit with code: null, signal: SIGKILL
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:54:12 [master] pid:1936 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:60:14 [master] pid:1936 Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

**Comment by qwezxcjohnny** [comment]
>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:1936 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/27d52726292a4a54383ff432dfab34f0/e053977a549d25528eb031ed88586240caa520c8/XCTestWDUITests-Runner.app
state->new_bundle: /Users/admin/Library/Developer/Xcode/DerivedData/XCTestWD-awyzvjjpazhyedbexovronjzyepo/Build/Products/Debug-iphoneos/XCTestWDUITests-Runner.app
state->dst_bundle: /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.nW22Lp/XCTestWDUITests-Runner.app_sparse.ipa/Payload//XCTestWDUITests-Runner.app, binaryDiff flag: FALSE
	dst_ipa: /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.nW22Lp/XCTestWDUITests-Runner.app_sparse.ipa

>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:1936 __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.nW22Lp/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:1936 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/qg/9t7hzdx91hng6k99j3qy5mrh0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.nW22Lp/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:172:14 [master] pid:1936 Failing tests:
	-[XCTextWDRunner testRunner()]

>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:1936 ** TEST FAILED **


>> xctest-client.js:173:14 [master] pid:1936 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.0.42@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:1936 killing deviceLogProc pid: 1945
>> xctest-client.js:260:14 [master] pid:1936 killing runnerProc pid: 1948
>> xctest-client.js:266:14 [master] pid:1936 killing iproxyProc pid: 1947
>> xctest-client.js:183:14 [master] pid:1936 xctest client exit with code: 65, signal: null
>> xctest-client.js:211:14 [master] pid:1936 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:145:16 [master] pid:1936 devicelog exit with code: null, signal: SIGKILL
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:1936 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:54:12 [master] pid:1936 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:60:14 [master] pid:1936 Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

**Comment by xudafeng** [comment]
社区看环境问题如何解决
