### ISSUE TITLE
app-inspector -u udid 无法connect ECONNREFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by yxys01** [alibaba/macaca#630]
Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1026:11)
      at exports._exceptionWithHostPort (util.js:1049:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)

这个完全无解。。。

**Comment by pmhgo** [comment]
我的是IOS真机 才这样，app-inspector -u udid ,,安卓和IOS模拟器都正常的。

**Comment by wxlsh114** [comment]
什么时候能解决？

**Comment by wxlsh114** [comment]
macaca-ios@2.0.23 still can not solve this bug. The inspector for real machine still fails with this error message. Hope you guys put some efforts on it. Thanks.

**Comment by wxlsh114** [comment]
@xdf , look at this bug please.

**Comment by xudafeng** [comment]
https://testerhome.com/search?q=macaca+%E7%9C%9F%E6%9C%BA
