### ISSUE TITLE
iOS10.3模拟器Error: connect ECONNREFUSED 127.0.0.1:8900

### ISSUE THREAD

**Issue by xiaoluosun** [alibaba/macaca#634]
```
testMacdeiMac:~ testmac$ macaca doctor

  macaca-doctor version: 2.0.1


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.9.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/testMac/Documents/tools/sdk/`
  Platforms is set to `/Users/testMac/Documents/tools/sdk/platforms/android-25`
  ADB tool is set to `/Users/testMac/Documents/tools/sdk/platform-tools/adb`
  gradle is installed, version: 4.0

  Installed driver list:

  ios: 2.0.22
```

```
testMacdeiMac:~ testmac$ macaca -v

  2.0.4
```

使用iOS10.3模拟器运行一段时间后（几分钟以后），必定会出现这个错误。

错误日志：
```
>> responseHandler.js:11:12 [master] pid:81730 Recieve HTTP Request from Client[2017-07-07 11:42:45]: method: POST url: /wd/hub/session/8d102153-6081-40ee-bd41-99463f76b792/actions, jsonBody: {"actions":[{"x":"308.0","y":"613.0","type":"tap"}]}
>> proxy.js:55:14 [master] pid:81730 Proxy: /wd/hub/session/:sessionId/tap/null:POST to http://localhost:8900/wd/hub/session/DAEF6F17-4EA4-4C3E-9665-574E76F6CC98/tap/null:POST with body: {"x":"308.0","y":"613.0"}
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> proxy.js:61:22 [master] pid:81730 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8900
>> responseHandler.js:54:12 [master] pid:81730 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8900
>> responseHandler.js:60:14 [master] pid:81730 Error: connect ECONNREFUSED 127.0.0.1:8900
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

  Error: connect ECONNREFUSED 127.0.0.1:8900
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by irina-zou** [comment]
我在真机上运行，过几分钟也会出现这个报错：

➜  ~ macaca doctor

  macaca-doctor version: 2.0.1


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.1.3

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  electron: 1.1.7
  ios: 2.0.23

>> xctest-client.js:173:14 [master] pid:2086 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:2086 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/x6/yhc3q3b549g1ytjk6q7kmd5w0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/XCTestWDUITests-Runner.app.f75FN2/XCTestWDUITests-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:173:14 [master] pid:2086 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: socket hang up
>> xctest-client.js:172:14 [master] pid:2086 Failing tests:
	-[XCTextWDRunner testRunner()]
** TEST FAILED **


>> xctest-client.js:173:14 [master] pid:2086 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:2086 killing deviceLogProc pid: 2098
>> xctest-client.js:260:14 [master] pid:2086 killing runnerProc pid: 2101
>> xctest-client.js:266:14 [master] pid:2086 killing iproxyProc pid: 2100
>> xctest-client.js:183:14 [master] pid:2086 xctest client exit with code: 65, signal: null
>> xctest-client.js:145:16 [master] pid:2086 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:211:14 [master] pid:2086 iproxy exit with code: null, signal: SIGKILL
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:2086 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:54:12 [master] pid:2086 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:60:14 [master] pid:2086 Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)

**Comment by laiyuncong8404** [comment]
同样有这个问题，目前所有驱动都是最新的

**Comment by xudafeng** [comment]
升级最新版本macaca-ios
