### ISSUE TITLE
win7系统，android-macaca，使用elementById报错

### ISSUE THREAD

**Issue by wuchao01** [alibaba/macaca#637]
macaca-doctor version: 2.0.1

 Node.js checklist:

 node env: C:\Program Files\nodejs\node.exe
 node version: v6.11.0

 Android checklist:

 JAVA version is `1.8.0_121`
 JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
 ANDROID_HOME is set to `D:\tools\adt-bundle-windows-x86-20130917\sdk`
 Platforms is set to `D:\tools\adt-bundle-windows-x86-20130917\sdk\platforms\an
roid-26`
 ADB tool is set to `D:\tools\adt-bundle-windows-x86-20130917\sdk\platform-tool
\adb.exe`
 GRADLE_HOME is set to `D:\tools\gradle4.0`

 Installed driver list:

 android: 2.0.28
 chrome: 1.0.5

使用语言：JAVA
操作系统：win7-64位

问题描述：
运行【macaca-android】后，使用elementById会报错“Argument was an invalid selector (e.g. XPath/CSS).”，log日志如下
>> proxy.js:55:14 [master] pid:7716 Proxy: /wd/hub/session/0bcd806c-4136-461a-ae
23-f1d320a5aed6/element:POST to http://127.0.0.1:9003/wd/hub/session/0bcd806c-41
36-461a-ae23-f1d320a5aed6/element:POST with body: {"using":"id","value":"com.XXX.XXX.XXX:id/btn_enter"}
>> proxy.js:83:20 [master] pid:7716 Got response with status 200: {"status":32,"
value":"Argument was an invalid selector (e.g. XPath/CSS).","sessionId":null}
>> session.js:107:14 [master] pid:7716 Send HTTP Respone to Client[2017-07-10 11
:23:04]: {"status":32,"value":"\"Argument was an invalid selector (e.g. XPath/CS
S).\"","sessionId":null}

**Comment by xudafeng** [comment]
升级macaca-android跟windows无关

**Comment by tongshan1** [comment]
升级了也不行啊～～～～～
