### ISSUE TITLE
运行官方python例子，ios模拟器，socket hang up

### ISSUE THREAD

**Issue by BachWings** [alibaba/macaca#638]
运行官方python例子，版本都为最新

环境：
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v8.1.3

  iOS checklist:
  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:
  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/lidejuan/Library/Android/sdk`
  Platforms is set to `/Users/lidejuan/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/lidejuan/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.0

  Installed driver list:
  android: 2.0.28
  chrome: 1.0.5
  electron: 1.1.6
  ios: 2.0.22

Log：
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:3553 Recieve HTTP Request from Client[2017-07-11 16:23:21]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","deviceName":"iPhone 6s","app":"https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip"}}
>> session.js:47:10 [master] pid:3553 Creating session, sessionId: 53b346f4-e4c6-4184-97fb-f0836c98baf1.
ios-deploy
>> get /Users/lidejuan/.macaca-temp/ios-app-bootstrap.zip from cache
>> sha:d2e65bba467659ef610b369f2ee599c1
>> helper.js:194:12 [master] pid:3553 Unzipping local app form /Users/lidejuan/.macaca-temp/ios-app-bootstrap.zip
>> macaca-ios.js:217:10 [master] pid:3553 Get available devices [{"name":"iPhone 5","udid":"E1B0920E-0521-4D2A-8296-C77B23DCD4CA","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 5s","udid":"FAD43D01-0BAE-4D52-B80F-85EA58CA67B9","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 6","udid":"02F29D2B-AF3B-4977-8AAC-BB6FD4F117F6","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 6 Plus","udid":"7E594D38-F96A-4C26-A8E9-7627E8228CDC","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 6s","udid":"110FF125-2247-416E-A887-B483DA7710E4","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 6s Plus","udid":"ED94C98B-001B-4EE2-A8FB-879535F13438","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 7","udid":"0D8901A2-ABFA-4E89-B093-0A644836FAE8","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 7 Plus","udid":"5BDA909C-7335-4046-BE12-E119E6327A09","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone SE","udid":"E6D75FB5-80B4-4425-B50C-6E70731A6855","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPad Air","udid":"C5CF8EFE-C419-489B-8777-1E458865D3D3","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPad Air 2","udid":"452AC479-3D2D-46BA-9994-F6B47675867D","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"Apple TV 1080p","udid":"B1325221-468B-4140-AC14-FAC6E45DCCDD","state":"Shutdown","available":true,"runtime":"tvOS 10.2"},{"name":"Apple Watch - 38mm","udid":"70A1999E-2A34-4B01-BFA3-B7BD7B36647C","state":"Shutdown","available":true,"runtime":"watchOS 3.2"},{"name":"Apple Watch - 42mm","udid":"1EA24EF0-DDEA-4558-8027-6168010053AF","state":"Shutdown","available":true,"runtime":"watchOS 3.2"},{"name":"Apple Watch Series 2 - 38mm","udid":"E1E3EDE3-C9CE-496C-9AFC-3663ECD807FF","state":"Shutdown","available":true,"runtime":"watchOS 3.2"},{"name":"Apple Watch Series 2 - 42mm","udid":"5033E295-7BD0-4973-B9BE-F793CD88F101","state":"Shutdown","available":true,"runtime":"watchOS 3.2"}]
CFBundleIdentifier is xudafeng.ios-app-bootstrap
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/7r/qf9j25f53rdfvpm98hjmrx_00000gn/T/ios-app-bootstrap.app/Info.plist
>> macaca-ios.js:308:12 [master] pid:3553 Kill simulator failed Error: Command failed: killAll Simulator
No matching processes belonging to you were found

>> macaca-ios.js:314:12 [master] pid:3553 Shutdown simulator 110FF125-2247-416E-A887-B483DA7710E4 failed Error: Command failed: xcrun simctl shutdown "110FF125-2247-416E-A887-B483DA7710E4"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=163):
Unable to shutdown device in current state: Shutdown

>> xctest-client.js:52:14 [master] pid:3553 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:159:10 [master] pid:3553 {
	"bundleId": "xudafeng.ios-app-bootstrap",
	"platformName": "iOS",
	"app": "/var/folders/7r/qf9j25f53rdfvpm98hjmrx_00000gn/T/ios-app-bootstrap.app/"
}
>> macaca-ios.js:166:12 [master] pid:3553 Trying to start xctestwd server...
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:3553 xcode version: 8.3.3
>> XCTestWD version: 1.1.0
>> xctest-client.js:172:14 [master] pid:3553 2017-07-11 16:23:43.527 xcodebuild[3649:228204]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/lidejuan/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Logs/Test/C4C78C1D-E2CA-40DD-B9A0-3AEBF3CB7B0C/Session-XCTestWDUITests-2017-07-11_162343-1Ow9EC.log

>> xctest-client.js:173:14 [master] pid:3553 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:3553 2017-07-11 16:23:43.527 xcodebuild[3649:228195] [MT] IDETestOperationsObserverDebug: (0947F463-D4BC-4F7D-98D0-F2A25AF196C9) Beginning test session XCTestWDUITests-0947F463-D4BC-4F7D-98D0-F2A25AF196C9 at 2017-07-11 16:23:43.527 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7ff8baf5b7b0> {
		SimDevice: SimDevice : iPhone 6s (110FF125-2247-416E-A887-B483DA7710E4) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6s } runtime={ SimRuntime : 10.3.1 (14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3.1 (14E8301))

>> xctest-client.js:173:14 [master] pid:3553 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:55:14 [master] pid:3553 Proxy: /wd/hub/session:POST to http://localhost:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"xudafeng.ios-app-bootstrap","platformName":"iOS","app":"/var/folders/7r/qf9j25f53rdfvpm98hjmrx_00000gn/T/ios-app-bootstrap.app/"}}
>> proxy.js:83:20 [master] pid:3553 Got response with status 200: {"sessionId":null,"status":0,"value":{"sessionId":"C3794E99-C64D-49D8-A841-C745603985D3","capabilities":{"browserName":"Bootstrap","device":"iphone","sdkVersion":"10.3.1","CFBundleIdentifier":"xuda...
>> responseHandler.js:47:14 [master] pid:3553 Send HTTP Respone to Client[2017-07-11 16:24:10]: {"sessionId":"53b346f4-e4c6-4184-97fb-f0836c98baf1","status":0,"value":"{\"platformName\":\"iOS\",\"deviceName\":\"iPhone 6s\",\"app\":\"/var/folders/7r/qf9j25f53rdfvpm98hjmrx_00000gn/T/ios-app-bootstrap.app/\"}"}
>> responseHandler.js:11:12 [master] pid:3553 Recieve HTTP Request from Client[2017-07-11 16:24:10]: method: POST url: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element, jsonBody: {"using":"xpath","value":"//XCUIElementTypeTextField[1]"}
>> proxy.js:55:14 [master] pid:3553 Proxy: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element:POST to http://localhost:8001/wd/hub/session/C3794E99-C64D-49D8-A841-C745603985D3/element:POST with body: {"using":"xpath","value":"//XCUIElementTypeTextField[1]"}
>> proxy.js:83:20 [master] pid:3553 Got response with status 200: {"sessionId":"","status":0,"value":{"ELEMENT":"68DD7C53-58C6-4657-9F24-4E41EC459CA2","label":"","type":"XCUIElementTypeTextField"}}
>> session.js:107:14 [master] pid:3553 Send HTTP Respone to Client[2017-07-11 16:24:10]: {"sessionId":"","status":0,"value":"{\"ELEMENT\":\"68DD7C53-58C6-4657-9F24-4E41EC459CA2\",\"label\":\"\",\"type\":\"XCUIElementTypeTextField\"}"}
>> responseHandler.js:11:12 [master] pid:3553 Recieve HTTP Request from Client[2017-07-11 16:24:10]: method: POST url: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element/68DD7C53-58C6-4657-9F24-4E41EC459CA2/value, jsonBody: {"value":["中文+Test+12345678"]}
>> proxy.js:55:14 [master] pid:3553 Proxy: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element/68DD7C53-58C6-4657-9F24-4E41EC459CA2/value:POST to http://localhost:8001/wd/hub/session/C3794E99-C64D-49D8-A841-C745603985D3/element/68DD7C53-58C6-4657-9F24-4E41EC459CA2/value:POST with body: {"value":["中文+Test+12345678"]}
>> proxy.js:83:20 [master] pid:3553 Got response with status 200: {"sessionId":"","status":0,"value":""}
>> session.js:107:14 [master] pid:3553 Send HTTP Respone to Client[2017-07-11 16:24:13]: {"sessionId":"","status":0,"value":""}
>> responseHandler.js:11:12 [master] pid:3553 Recieve HTTP Request from Client[2017-07-11 16:24:13]: method: POST url: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element, jsonBody: {"using":"xpath","value":"//XCUIElementTypeSecureTextField[1]"}
>> proxy.js:55:14 [master] pid:3553 Proxy: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element:POST to http://localhost:8001/wd/hub/session/C3794E99-C64D-49D8-A841-C745603985D3/element:POST with body: {"using":"xpath","value":"//XCUIElementTypeSecureTextField[1]"}
>> proxy.js:83:20 [master] pid:3553 Got response with status 200: {"sessionId":"","status":0,"value":{"ELEMENT":"448A2DD5-CFD4-4B7E-A9BB-521DB3E33C57","label":"","type":"XCUIElementTypeSecureTextField"}}
>> session.js:107:14 [master] pid:3553 Send HTTP Respone to Client[2017-07-11 16:24:13]: {"sessionId":"","status":0,"value":"{\"ELEMENT\":\"448A2DD5-CFD4-4B7E-A9BB-521DB3E33C57\",\"label\":\"\",\"type\":\"XCUIElementTypeSecureTextField\"}"}
>> responseHandler.js:11:12 [master] pid:3553 Recieve HTTP Request from Client[2017-07-11 16:24:13]: method: POST url: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element/448A2DD5-CFD4-4B7E-A9BB-521DB3E33C57/value, jsonBody: {"value":["111111"]}
>> proxy.js:55:14 [master] pid:3553 Proxy: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element/448A2DD5-CFD4-4B7E-A9BB-521DB3E33C57/value:POST to http://localhost:8001/wd/hub/session/C3794E99-C64D-49D8-A841-C745603985D3/element/448A2DD5-CFD4-4B7E-A9BB-521DB3E33C57/value:POST with body: {"value":["111111"]}
>> proxy.js:83:20 [master] pid:3553 Got response with status 200: {"sessionId":"","status":0,"value":""}
>> session.js:107:14 [master] pid:3553 Send HTTP Respone to Client[2017-07-11 16:24:16]: {"sessionId":"","status":0,"value":""}
>> responseHandler.js:11:12 [master] pid:3553 Recieve HTTP Request from Client[2017-07-11 16:24:16]: method: POST url: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element, jsonBody: {"using":"name","value":"Done"}
>> proxy.js:55:14 [master] pid:3553 Proxy: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element:POST to http://localhost:8001/wd/hub/session/C3794E99-C64D-49D8-A841-C745603985D3/element:POST with body: {"using":"name","value":"Done"}
>> proxy.js:83:20 [master] pid:3553 Got response with status 200: {"sessionId":"","status":0,"value":{"ELEMENT":"36B481F5-C2BB-42A2-8067-4B7194B54F55","label":"Done","type":"XCUIElementTypeButton"}}
>> session.js:107:14 [master] pid:3553 Send HTTP Respone to Client[2017-07-11 16:24:16]: {"sessionId":"","status":0,"value":"{\"ELEMENT\":\"36B481F5-C2BB-42A2-8067-4B7194B54F55\",\"label\":\"Done\",\"type\":\"XCUIElementTypeButton\"}"}
>> responseHandler.js:11:12 [master] pid:3553 Recieve HTTP Request from Client[2017-07-11 16:24:16]: method: POST url: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element/36B481F5-C2BB-42A2-8067-4B7194B54F55/click, jsonBody: {}
>> proxy.js:55:14 [master] pid:3553 Proxy: /wd/hub/session/53b346f4-e4c6-4184-97fb-f0836c98baf1/element/36B481F5-C2BB-42A2-8067-4B7194B54F55/click:POST to http://localhost:8001/wd/hub/session/C3794E99-C64D-49D8-A841-C745603985D3/element/36B481F5-C2BB-42A2-8067-4B7194B54F55/click:POST with body: {}
**>> proxy.js:61:22 [master] pid:3553 xctest client proxy error with: Error:  socket hang up**

>> xctest-client.js:172:14 [master] pid:3553 2017-07-11 16:24:18.358 xcodebuild[3649:229270]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/lidejuan/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Logs/Test/C4C78C1D-E2CA-40DD-B9A0-3AEBF3CB7B0C/Session-XCTestWDUITests-2017-07-11_162418-Vs3I8I.log
2017-07-11 16:24:18.358 xcodebuild[3649:228195] [MT] IDETestOperationsObserverDebug: (CE0679F8-290C-451F-B8FA-DC2540FADBE5) Beginning test session XCTestWDUITests-CE0679F8-290C-451F-B8FA-DC2540FADBE5 at 2017-07-11 16:24:18.358 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7ff8baf5b7b0> {
		SimDevice: SimDevice : iPhone 6s (110FF125-2247-416E-A887-B483DA7710E4) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6s } runtime={ SimRuntime : 10.3.1 (14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3.1 (14E8301))

>> xctest-client.js:173:14 [master] pid:3553 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:61:22 [master] pid:3553 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:3553 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:3553 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:172:14 [master] pid:3553 Failing tests:

>> xctest-client.js:173:14 [master] pid:3553 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:3553 	-[XCTextWDRunner testRunner()]
	-[XCTextWDRunner testRunner()]
** TEST FAILED **

>> xctest-client.js:173:14 [master] pid:3553 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:255:14 [master] pid:3553 killing deviceLogProc pid: 3650
>> xctest-client.js:260:14 [master] pid:3553 killing runnerProc pid: 3649
>> xctest-client.js:183:14 [master] pid:3553 xctest client exit with code: 65, signal: null
>> xctest-client.js:108:18 [master] pid:3553 simulator log process exit with code: null, signal: SIGKILL
>> proxy.js:61:22 [master] pid:3553 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:3553 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:61:22 [master] pid:3553 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

**Comment by xudafeng** [comment]
更新例子和依赖到最新即可
