### ISSUE TITLE
enhancement request: option to re-run failing tests <n> number of times

### ISSUE THREAD

**Issue by sachinGirish** [alibaba/macaca#641]
enhancement request: option to re-run failing tests <n> number of times
similar to mocha

Many GUI test frameworks support an option to re-run failing tests a specified number of times. For example, I'd like to see this command:

macaca run -s FAILING -a regression --rerun 3

give every failing test TWO more tries to pass.

**Comment by xudafeng** [comment]
@sachinGirish please use macaca server && mocha not the `macaca run`.
