### ISSUE TITLE
ios版本socket hang up问题严重，建议回退WD

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#642]
ios版本socket hang up问题严重影响使用，issues相关问题也比较多，解决问题进度很慢。能否先回退WD，确保能正常使用再逐步解决问题。目前ios端完全没办法正常使用。

**Comment by SamuelZhaoY** [comment]
此前 执行了什么命令？

试试：
xcodebuild -project XCTestWD.xcodeproj 
-scheme XCTestWDUITests 
-destination 'platform=iOS Simulator,name=iPhone 6' 
XCTESTWD_PORT=8001 
clean test

看能否正常启动XCTestWD ， 参考项目 README.MD 中提示进行排查

**Comment by adudurant** [comment]
@SamuelZhaoY   执行了  好像没啥差别？

**Comment by adudurant** [comment]
@zsmjluo   有稳定下来吗？

**Comment by zsmjluo** [comment]
@adudurant 
看回复就知道什么都没做。不过问题直接关闭了让人很费解。不想再等他们解决了，他们估计也没精力搞了。我现在只在开始的时候init,所有case都执行完了再quit。

**Comment by SamuelZhaoY** [comment]
没收到有效的排查信息， 故没有能够排查问题.  请问有按照XCTestWD 中README 进行排查吗
