### ISSUE TITLE
Win7/Python运行脚本失败

### ISSUE THREAD

**Issue by wxlsh114** [alibaba/macaca#645]
* **Macaca Version**:2.0.4

* **Macaca Doctor Logs**:
![doctor](https://user-images.githubusercontent.com/24494065/28246002-0518d98e-6a45-11e7-93cd-ec1145a44987.jpg)

* **Operate System**:Windows7 64bit

* **Programming Language**:Python v3.5

但是一运行case就失败，这些case在iMac环境下原先都运行成功的
![result](https://user-images.githubusercontent.com/24494065/28245999-ef13f114-6a44-11e7-81ff-2d8c08e24545.jpg)

**Comment by chenjiejiji** [comment]
我也碰到一样的问题了 解决了没
@wxlsh114

**Comment by chenjiejiji** [comment]
他提示是报错是
r: Command failed: H:\Android\android-sdk\/platform-tools/adb -s 192.168.240.101
:5555 push C:\Program Files\nodejs\node-global\node_modules\macaca-android\node_
modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.ma
caca.android.testing

我手动查看了 是有这个apk 的 但是运行adb -s 192.168.240.101
:5555 push C:\Program Files\nodejs\node-global\node_modules\macaca-android\node_
modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk /data/local/tmp/com.ma
caca.android.testing
报错 
解决麻烦告知下感谢

**Comment by zenzhu** [comment]
有些可能是权限问题，试试把东西装在 D 盘。

**Comment by wxlsh114** [comment]
我把node.js重新安装到d盘，gradle也是，其他android sdk等然保留在C盘后，重新安装macaca, 再运行这些python脚本都能正常运行通过，看来这个bug的确是权限问题，可以关闭了，谢谢！@ziczhu

**Comment by kuangye89757** [comment]
确定是权限问题,我装到D盘就好了, 并且android的platforms必须是25  最好也安装ant
![image](https://user-images.githubusercontent.com/15827114/30415124-2c121a4e-9959-11e7-9372-b5ada905705a.png)
