### ISSUE TITLE
macacaclient-2.0.12.jar init异常

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#646]
java.lang.Error: Unresolved compilation problems: 
	The import macaca.client.model.JsonWireStatus cannot be resolved
	JsonWireStatus cannot be resolved to a type
	JsonWireStatus cannot be resolved
	JsonWireStatus cannot be resolved to a variable
	JsonWireStatus cannot be resolved to a variable

	at macaca.client.common.Utils.<init>(Utils.java:5)
	at macaca.client.commands.Alert.<init>(Alert.java:16)
	at macaca.client.MacacaClient.<init>(MacacaClient.java:26)

**Comment by zsmjluo** [comment]
macacaclient-2.0.11正常

**Comment by Yinxl** [comment]
请更新  2.0.13 已解决

**Comment by zsmjluo** [comment]
验证已解决，谢谢
