### ISSUE TITLE
wd.java 2.0.12 有坑。。。ubuntu下不行

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#647]
cmd@TR:~$ macaca -v

  2.0.4

cmd@TR:~$ macaca doctor

  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /opt/nodejs/bin/node
  node version: v6.10.3

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/opt/android-sdk-linux`
  Platforms is set to `/opt/android-sdk-linux/platforms/android-25`
  ADB tool is set to `/opt/android-sdk-linux/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.29
  chrome: 1.0.5
  electron: 1.1.6

wd.java 今天由2.0.7 pom改为2.0.12 
同样的svn签出的工程项目， 脚本未动，win10下顺利用2.0.12跑通。

结果到ubuntu下  首次执行报错
`cmd@TR:~/workspace/MacacaDev/uiautoaicai$ mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building uiautotest 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/cmd/workspace/MacacaDev/uiautoaicai/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ uiautotest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cmd/workspace/MacacaDev/uiautoaicai/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ uiautotest ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /home/cmd/workspace/MacacaDev/uiautoaicai/target/test-classes
[WARNING] /home/cmd/workspace/MacacaDev/uiautoaicai/src/test/java/uiauto/H5WebTest.java:[5,25] sun.security.util.HostnameChecker是内部专用 API, 可能会在未来发行版中删除
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ uiautotest ---
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.409 s
[INFO] Finished at: 2017-07-18T17:22:14+08:00
[INFO] Final Memory: 23M/292M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project uiautotest: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: There was an error in the forked process
[ERROR] org.testng.TestNGException:
[ERROR] Cannot instantiate class uiauto.AndroidAcpTest
[ERROR] at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:40)
[ERROR] at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:377)
[ERROR] at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:290)
[ERROR] at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
[ERROR] at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:130)
[ERROR] at org.testng.TestRunner.initMethods(TestRunner.java:424)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:247)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:217)
[ERROR] at org.testng.TestRunner.<init>(TestRunner.java:161)
[ERROR] at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:556)
[ERROR] at org.testng.SuiteRunner.init(SuiteRunner.java:168)
[ERROR] at org.testng.SuiteRunner.<init>(SuiteRunner.java:117)
[ERROR] at org.testng.TestNG.createSuiteRunner(TestNG.java:1319)
[ERROR] at org.testng.TestNG.createSuiteRunners(TestNG.java:1306)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1160)
[ERROR] at org.testng.TestNG.run(TestNG.java:1064)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.reflect.InvocationTargetException
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
[ERROR] ... 22 more
[ERROR] Caused by: java.lang.Error: Unresolved compilation problems:
[ERROR] The import macaca.client.model.JsonWireStatus cannot be resolved
[ERROR] JsonWireStatus cannot be resolved to a type
[ERROR] JsonWireStatus cannot be resolved
[ERROR] JsonWireStatus cannot be resolved to a variable
[ERROR] JsonWireStatus cannot be resolved to a variable
[ERROR] 
[ERROR] at macaca.client.common.Utils.<init>(Utils.java:5)
[ERROR] at macaca.client.commands.Alert.<init>(Alert.java:16)
[ERROR] at macaca.client.MacacaClient.<init>(MacacaClient.java:26)
[ERROR] at uiauto.AndroidAcpTest.<init>(AndroidAcpTest.java:23)
[ERROR] ... 27 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
cmd@TR:~/workspace/MacacaDev/uiautoaicai$ mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building uiautotest 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ uiautotest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cmd/workspace/MacacaDev/uiautoaicai/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ uiautotest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ uiautotest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/cmd/workspace/MacacaDev/uiautoaicai/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ uiautotest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ uiautotest ---
[INFO] Surefire report directory: /home/cmd/workspace/MacacaDev/uiautoaicai/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.989 s
[INFO] Finished at: 2017-07-18T17:28:36+08:00
[INFO] Final Memory: 13M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project uiautotest: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test failed: There was an error in the forked process
[ERROR] org.testng.TestNGException:
[ERROR] Cannot instantiate class uiauto.AndroidAcpTest
[ERROR] at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:40)
[ERROR] at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:377)
[ERROR] at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:290)
[ERROR] at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:125)
[ERROR] at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:190)
[ERROR] at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:130)
[ERROR] at org.testng.TestRunner.initMethods(TestRunner.java:424)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:247)
[ERROR] at org.testng.TestRunner.init(TestRunner.java:217)
[ERROR] at org.testng.TestRunner.<init>(TestRunner.java:161)
[ERROR] at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:556)
[ERROR] at org.testng.SuiteRunner.init(SuiteRunner.java:168)
[ERROR] at org.testng.SuiteRunner.<init>(SuiteRunner.java:117)
[ERROR] at org.testng.TestNG.createSuiteRunner(TestNG.java:1319)
[ERROR] at org.testng.TestNG.createSuiteRunners(TestNG.java:1306)
[ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1160)
[ERROR] at org.testng.TestNG.run(TestNG.java:1064)
[ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
[ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
[ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.reflect.InvocationTargetException
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
[ERROR] ... 22 more
[ERROR] Caused by: java.lang.Error: Unresolved compilation problems:
[ERROR] The import macaca.client.model.JsonWireStatus cannot be resolved
[ERROR] JsonWireStatus cannot be resolved to a type
[ERROR] JsonWireStatus cannot be resolved
[ERROR] JsonWireStatus cannot be resolved to a variable
[ERROR] JsonWireStatus cannot be resolved to a variable
[ERROR] 
[ERROR] at macaca.client.common.Utils.<init>(Utils.java:5)
[ERROR] at macaca.client.commands.Alert.<init>(Alert.java:16)
[ERROR] at macaca.client.MacacaClient.<init>(MacacaClient.java:26)
[ERROR] at uiauto.AndroidAcpTest.<init>(AndroidAcpTest.java:23)
[ERROR] ... 27 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
`

刚开始还以为是  testng的错误  重新弄了好久 都不行 结果我换回2.0.7 又是可以的
那应该是2.0.12 在ubuntu下 有bug   

请wd.java的作者 看下

**Comment by Yinxl** [comment]
请更新2.0.13版本 已修复 谢谢
