### ISSUE TITLE
ios使用UI recorder报socket hang up错误

### ISSUE THREAD

**Issue by yxys01** [alibaba/macaca#648]
$ uirecorder --mobile sample/test.spec.js
之后，拖拽app文件进入后出现
问题：手机打开失败，请检查Macaca是否配置正确？{Error：socket hang up}
但是我macaca配置是好的，也能运行demo，请问该怎么解决这个问题？

**Comment by SamuelZhaoY** [comment]
请参考 XCTestWD 故障排查指南进行调试 https://github.com/macacajs/XCTestWD

**Comment by adudurant** [comment]
@yxys01  解决了吗？
