### ISSUE TITLE
build XCTestWd环节卡住，无法执行下一步

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#650]
* **Macaca Version**:2.0.4

* **Macaca Doctor Logs**:

  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/joko/Library/Android/sdk`
  Platforms is set to `/Users/joko/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/joko/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.29
  electron: 1.1.6
  ios: 2.0.22
* **Operate System**:
mac os ：10.12.5
* **Programming Language**:python

* 问题描述：执行iOS测试时，卡住在build xctestwd环节（经常性卡住，之前版本无此问题，超过3分钟无任何反馈），未编译成功（使用xcode编译，几秒钟即可编译成功）。无法进行下一步，请排查
```log
>> macaca-ios.js:166:12 [master] pid:9898 Trying to start xctestwd server...
>> xctestwd start with port: 8001
>> xctest-client.js:224:14 [master] pid:9898 xcode version: 8.3.3
>> XCTestWD version: 1.1.0
>> xctest-client.js:172:14 [master] pid:9898 2017-07-20 14:49:58.092 xcodebuild[9935:180487]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/joko/Library/Developer/Xcode/DerivedData/XCTestWD-gulhlqttpkdvbldvsjjkqmcgbggo/Logs/Test/A1757D07-15E7-4428-BE41-9A6EA8D6125E/Session-XCTestWDUITests-2017-07-20_144958-lYsVjD.log

>> xctest-client.js:173:14 [master] pid:9898 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:172:14 [master] pid:9898 2017-07-20 14:49:58.093 xcodebuild[9935:180466] [MT] IDETestOperationsObserverDebug: (67B75893-7588-4296-8CE7-BFC37BAD15D3) Beginning test session XCTestWDUITests-67B75893-7588-4296-8CE7-BFC37BAD15D3 at 2017-07-20 14:49:58.093 with Xcode 8E3004b on target <DVTiPhoneSimulator: 0x7fd61285db00> {
		SimDevice: SimDevice : iPhone 6s (4B29D047-C36E-4228-8AB8-06687B6D1A7E) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6s } runtime={ SimRuntime : 10.3.1 (14E8301) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3.1 (14E8301))

>> xctest-client.js:173:14 [master] pid:9898 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/._xctestwd@1.1.0@xctestwd/XCTestWD/XCTestWD.xcodeproj



```

**Comment by ztwo** [comment]
降级了macaca-ios至2.20，问题消失。2.0.20对应的xctestwd版本是1.0.43。2.0.22对应的xctestwd版本是1.1.0。请帮忙修复问题

**Comment by ztwo** [comment]
升级到2.0.24问题依然存在，对应1.1.8。使用app-inspector也有此问题，刚才卡在>> xctest-client.js:179:14 [master] pid:8584 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/._xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj 。长达半小时

**Comment by Chan-Chun** [comment]
最新版是没问题的
文档已经增加 ideviceinstaller 安装部分：https://macacajs.com/zh/environment-setup

**Comment by ztwo** [comment]
@Chan-Chun 这个问题是和ideviceinstaller没关系的，出现问题时，偶尔使用xcode编译也会出现卡住情况。
