### ISSUE TITLE
python设置 'autoAcceptAlerts': 'false'无效

### ISSUE THREAD

**Issue by xray2008** [alibaba/macaca#652]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by zenzhu** [comment]
服务端不支持

**Comment by xray2008** [comment]
@zenzhu 能否转给服务端的同学支持一下？

**Comment by xudafeng** [comment]
wd.py 升级最新版
