### ISSUE TITLE
在页面A点击m元素跳到其他页面，再返回页面A点击n元素的时候，提示没有找到n元素

### ISSUE THREAD

**Issue by PENGZHONGLING** [alibaba/macaca#653]
* **Macaca Version**:2.0.10

* **Macaca Doctor Logs**:

* **Operate System**:Mac

* **Programming Language**:java

1、在页面A点击m元素跳到其他页面，再返回页面A点击n元素的时候，提示没有找到n元素，通过source()能找到该元素。
2、如果进入页面A的时候不点击m，直接点击n，就能成功。

**Comment by xudafeng** [comment]
iOS, Android? 信息太少
