### ISSUE TITLE
提供真机测试详细说明文档

### ISSUE THREAD

**Issue by luozhang002** [alibaba/macaca#654]
# Macaca Ios真机调试文档

1. 前期检查

   必备：Ios真机、开发者账号（或者证书）、良好的数据线

   其他：

   * Ios真机信任此调试电脑
   * Ios真机已注册进入开发者账号

   - XCode version 9.0 and above.
   - iOS version 11.0 and above. 

2. Macaca环境配置

   参考[Macaca](https://macacajs.com/zh/environment-setup)配置环境页，配置Ios真机测试环境，步骤大致包括：

   - 请安装 Xcode9 或者更高版本
   - 请安装 [usbmuxd](https://github.com/libimobiledevice/usbmuxd) 以便于通过 USB 通道测试 iOS 真机

   ```shell
   $ brew install usbmuxd
   ```

   - 请安装 [ideviceinstaller](https://github.com/libimobiledevice/ideviceinstaller) 用来给真机安装 App。

   ```shell
   $ brew install ideviceinstaller
   ```

   - 应用中如含有 WebView，请安装 [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy)

   ```shell
   $ brew install ios-webkit-debug-proxy
   ```

   - 请安装 [carthage](https://github.com/Carthage/Carthage) 来构建 Macaca [XCTestWD](https://github.com/macacajs/XCTestWD).

   ```Shell
   $ brew install carthage
   ```

   * 安装带TEAM_ID的Macaca-ios

   ```shell
   $ DEVELOPMENT_TEAM_ID=TEAM_ID npm i macaca-ios -g
   ```

   查看TEAM_ID的方法，确保已经有开发者账号（或者证书）的情况下，已经将XCTestWD安装到真机的情况下查看，TEAM_ID。在XCTestWD项目中如下可查看TEAM_ID：
![6d308bd9gy1fg7cnt9hf6j20t70h7782](https://user-images.githubusercontent.com/17233599/37697212-7cb8049e-2d16-11e8-8817-3ac33fccac66.jpg)

   * Macaca-doctor：用Macaca-doctor确保环境安装正确

   ```shell
   $ npm i macaca-cli -g
   $ macaca doctor
   ```

3. 下载[XCTestWD](https://github.com/macacajs/XCTestWD)项目，并将其装入真机

   * Carthage构建

     ```shell
     carthage update --platform iOS
     ```

   * XCTestWD安装，打开/XCTestWD/XCTestWD.xcodeproj

     1. 导入开发者账号（证书）
     2. Run Test将XCTestWDUITest装入真机：
![1521611745508 2](https://user-images.githubusercontent.com/17233599/37697217-88e00366-2d16-11e8-9b4e-eaf1b693856c.jpg)

4. 在测试脚本中配置真机测试参数

   例子：
<img width="563" alt="2018-03-21 1 51 04" src="https://user-images.githubusercontent.com/17233599/37697224-8d655ce2-2d16-11e8-8699-34e5b8e91fc1.png">

   * 如果真机中有相应的测试app，参数中`app` 可注释
   * 确保udid对应真机已连入电脑，并信任此电脑
   * 确保测试App bundle ID一致

   

5. 测试

   例子:

   ```shell
   platform=ios macaca run --verbose --reporter macaca-reporter -d ./mobile-app-sample.test.js
   ```

   ​

常见问题：

* 提示有关ios-deploy找不到请安装[ios-deploy](https://github.com/phonegap/ios-deploy)

  ```Shell
  npm install -g ios-deploy
  ```

* xcode中如果提示XCTestWD.framwork找不到或出错，请删除XCTestWD.franwork重新执行Run Test
![1521611745508](https://user-images.githubusercontent.com/17233599/37697228-92766f6e-2d16-11e8-890e-b867a0621e62.jpg)

**Comment by xudafeng** [comment]
提供真机测试详细说明文档 https://github.com/alibaba/macaca/issues/605

**Comment by luozhang002** [comment]
谢谢

**Comment by Chan-Chun** [comment]
针对最新版Xcode，真机调试需要开发者证书
以后将会更新文档并且跟进IOS真机调试

**Comment by Chan-Chun** [comment]
@upengfei 预计三月中下旬在此issue中发布真机测试文档

**Comment by upengfei** [comment]
@Chan-Chun 感谢！

**Comment by ca-ssiee** [comment]
xcode 9.2  iOS11
已经修改bundleId 但还是报错
BundleId XCTestWD.XCTestWD does not exist.
>> xctest-client.js:190:18 [master] pid:12160 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.3.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:12160 killing deviceLogProc pid: 12217
>> xctest-client.js:281:14 [master] pid:12160 killing runnerProc pid: 12203
>> xctest-client.js:201:16 [master] pid:12160 xctest client exit with code: 65, signal: null
>> xctest-client.js:155:16 [master] pid:12160 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:268:14 [master] pid:12160 Fail to start xctest: undefined

**Comment by Chan-Chun** [comment]
Macaca Ios真机调试文档



1. 前期检查
   必备：Ios真机、开发者账号（或者证书）、良好的数据线
   其他：
   - Ios真机信任此调试电脑
   - Ios真机已注册进入开发者账号
   - XCode version 9.0 and above.
   - iOS version 11.0 and above. 

1. Macaca环境配置
   参考Macaca配置环境页，配置Ios真机测试环境，步骤大致包括：
   - 请安装 Xcode9 或者更高版本
   - 请安装 usbmuxd 以便于通过 USB 通道测试 iOS 真机，不需要测试真机则不用安装
       $ brew install usbmuxd
   - 请安装 ideviceinstaller 用来给真机安装 App。
       $ brew install ideviceinstaller
   - 应用中如含有 WebView，请安装 ios-webkit-debug-proxy
       $ brew install ios-webkit-debug-proxy
   - 请安装 carthage 来构建 Macaca XCTestWD.
       $ brew install carthage
   - 安装带TEAM_ID的Macaca-ios
       $ DEVELOPMENT_TEAM_ID=TEAM_ID npm i macaca-ios -g
   查看TEAM_ID的方法，确保已经有开发者账号（或者证书）的情况下，已经将XCTestWD安装到真机的情况下查看，TEAM_ID。在XCTestWD项目中如下可查看TEAM_ID：
   ![6d308bd9gy1fg7cnt9hf6j20t70h7782](https://user-images.githubusercontent.com/17233599/37696617-004e8b38-2d13-11e8-938e-b372c860ce36.jpg)

2. 下载XCTestWD项目，并将其装入真机
   - Carthage构建
         carthage update --platform iOS
   - XCTestWD安装，打开/XCTestWD/XCTestWD.xcodeproj
     1. 导入开发者账号（证书）
     2. Run Test将XCTestWDUITest装入真机：
![1521611745508 2](https://user-images.githubusercontent.com/17233599/37696650-3858f9be-2d13-11e8-9499-a8c247439672.jpg)

3. 在测试脚本中配置真机测试参数
   例子：
<img width="563" alt="2018-03-21 1 51 04" src="https://user-images.githubusercontent.com/17233599/37696943-d89cd5fc-2d14-11e8-88d6-4ed73fa1067d.png">


   - 如果真机中有相应的测试app，参数中app 可注释
   - 确保uuid对应真机已连入电脑，并信任此电脑
   - 确保测试App bundle ID一致
   
4. 测试
   例子:
       platform=ios macaca run --verbose --reporter macaca-reporter -d ./mobile-app-sample.test.js
   

常见问题：

- 提示有关ios-deploy找不到请安装ios-deploy
      npm install -g ios-deploy
- xcode中如果提示XCTestWD.framwork找不到或出错，请删除XCTestWD.franwork重新执行Run Test
![1521611745508](https://user-images.githubusercontent.com/17233599/37696948-ddac6a80-2d14-11e8-8371-8bc52ef344ca.jpg)

**Comment by luozhang002** [comment]
谢谢Macaca官方团队的支持

**Comment by upengfei** [comment]
先感谢Macaca团队的支持与贡献！
按照文档，配置好后，不过我这边还是一直提示：BundleId XCTestWD.XCTestWD does not exist.
![image](https://user-images.githubusercontent.com/18410330/37748548-30451a9e-2dbf-11e8-8a99-cd9c99e8b8a2.png)

**Comment by ca-ssiee** [comment]
没有开发者账号，iOS开发给提供了一个开发者证书，如何导入啊？

**Comment by ca-ssiee** [comment]
使用开发者证书后，我的开发者证书必须以com.开头 如何解决这个问题啊

**Comment by jinglv** [comment]
你好，我在Run Test的时候，Build File报了很多错，如下图，请问是什么原因，谢谢！
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/12013318/38237292-67bea924-3759-11e8-8de1-465daea629f9.png">

**Comment by lovexiaov** [comment]
@jinglv  这个是 Fuzi 库的问题，参考此 issue https://github.com/macacajs/XCTestWD/issues/122

**Comment by jinglv** [comment]
@lovexiaov 你好，非常感谢，根据的方法已解决

**Comment by dbixia** [comment]
![image](https://user-images.githubusercontent.com/4281584/38594339-62371322-3d78-11e8-8c2c-04e17eb1eaf7.png)
新装的macaca，没有XCTestWDDemo后如何使用，run后不会装app在手机上，但是server报错BundleId XCTestWD.XCTestWD does not exist.

**Comment by dbixia** [comment]
XCTestWDUITests target, 执行Product>Test的之后，提示Build Success,但是Test Failed
![image](https://user-images.githubusercontent.com/4281584/38600228-00918f12-3d96-11e8-94a9-0b2f2d80cf4e.png)

**Comment by SamuelZhaoY** [comment]
@dbixia 这可能是动态库没找到导致的.  应该还是跟你本身的xcode 版本 以及carthage 相关依赖是否成功适配有关

**Comment by upengfei** [comment]
@dbixia  请问你这个问题解决了吗？

**Comment by wxlsh114** [comment]
xcode9.4.1,ios11.4,XCTestWD真机，编译出错：
1.Use of undeclared type 'XCTestWDServer'
2.Use of unresolved identifier 'XCTestWDServer'
@upengfei ，请看看是什么问题？急用，谢谢！

**Comment by Nicolasyy** [comment]
1、XCtestXD项目提示找不到文件夹，但是可以编译安装成功
![image](https://user-images.githubusercontent.com/31531639/49351584-14b7b300-f6ef-11e8-9112-4d5d6b50cdad.png)
2、运行提示不存在，是什么问题呢，已经按真机文档去设置了
>> macaca-ios.js:250:12 [master] pid:33969 App "com.xmexe.execo" is already installed.
>> macaca-ios.js:251:12 [master] pid:33969 Adopting app reuse strategy: 3.
BundleId XCTestWD.XCTestWD does not exist.

**Comment by Chersh-Pan** [comment]
刚接触IOS，感觉这个步骤应该是有错误的？查看TEAM_ID之前先得把XCTestWD项目装到真机里吧？
在使用carthage update --platform iOS 构建的时候，出现提示Cartfile 找不到。不知道有遇到的么？

**Comment by weichao1996** [comment]
为什么没有完整的真机测试脚本demo

**Comment by crrrrrrrrr** [comment]
XCTestWDUITests target, 执行Product>Test的之后，提示Build Success,但是Test Failed;一直卡在这个“XCTestWDSetup->http://localhost:8001<-XCTestWDSetup”就不动了，另外app-inspector -u udid，一直提示“Internal Server Error”，log输出“xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001”
请问能帮忙解决么 多谢🙏

**Comment by paradite** [comment]
> XCTestWDUITests target, 执行Product>Test的之后，提示Build Success,但是Test Failed;一直卡在这个“XCTestWDSetup->http://localhost:8001<-XCTestWDSetup”就不动了，另外app-inspector -u udid，一直提示“Internal Server Error”，log输出“xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001”
> 请问能帮忙解决么 多谢🙏

估计是xcode 11.5兼容性问题，请先用xcode11.4。如果xcode11.4也不行，请开新的issue。
