### ISSUE TITLE
macaca-ios2.0.22 waitForElementByXPath出现获取不到Element的情况，获取增加调用source()后可以正常获取。1.0.70版本驱动没问题。

### ISSUE THREAD

**Issue by zsmjluo** [alibaba/macaca#655]
macaca-ios2.0.22 waitForElementByXPath出现获取不到Element的情况，获取之前增加调用source()后可以正常获取。同样的场景，老版本1.0.70没这个问题。
  
macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.11.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.22

**Comment by SamuelZhaoY** [comment]
已在 2.0.23 修复
