### ISSUE TITLE
click方法导致"An unknown server-side error occurred while processing the command."

### ISSUE THREAD

**Issue by laiyuncong8404** [alibaba/macaca#656]
* **Macaca Version**:
2.0.4
* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.7.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/xiaoxue/Library/android-sdk-macosx`
  Platforms is set to `/Users/xiaoxue/Library/android-sdk-macosx/platforms/android-25`
  ADB tool is set to `/Users/xiaoxue/Library/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.30
  chrome: 1.0.6
  electron: 1.1.7
  ios: 2.0.22
* **Operate System**:
OSX 10.12.3
Android: 5.1.1
* **Programming Language**:
python

* **错误概况**
运行官方以下例子时，报如下日志错误。
[https://github.com/macaca-sample/sample-python/blob/master/tests/macaca-android-sample.test.py](url)
通过对元素调用if_exists和or_none方法，判断元素是找到了，但是click()没有生效。
更换其他方法定位，如id，也会报同样的错误。
* **错误日志**
`>> session.js:107:14 [master] pid:25010 Send HTTP Respone to Client[2017-07-26 16:11:37]: {"status":0,"sessionId":"bc4d90dc-34ef-469d-94e6-d5424ab29997"}
>> responseHandler.js:11:12 [master] pid:25010 Recieve HTTP Request from Client[2017-07-26 16:11:37]: method: POST url: /wd/hub/session/bc4d90dc-34ef-469d-94e6-d5424ab29997/element, jsonBody: {"using":"name","value":"Login"}
>> proxy.js:55:14 [master] pid:25010 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:25010 Got response with status 200: {"status":13,"value":"An unknown server-side error occurred while processing the command.","sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:25010 Proxy: /wd/hub/session/bc4d90dc-34ef-469d-94e6-d5424ab29997/element:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/element:POST with body: {"using":"name","value":"Login"}
>> proxy.js:83:20 [master] pid:25010 Got response with status 200: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"bc4d90dc-34ef-469d-94e6-d5424ab29997"}
>> session.js:107:14 [master] pid:25010 Send HTTP Respone to Client[2017-07-26 16:11:38]: {"status":0,"value":"{\"ELEMENT\":\"1\"}","sessionId":"bc4d90dc-34ef-469d-94e6-d5424ab29997"}
>> responseHandler.js:11:12 [master] pid:25010 Recieve HTTP Request from Client[2017-07-26 16:11:38]: method: POST url: /wd/hub/session/bc4d90dc-34ef-469d-94e6-d5424ab29997/element/1/click, jsonBody: {}
>> proxy.js:55:14 [master] pid:25010 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:83:20 [master] pid:25010 Got response with status 200: {"status":13,"value":"An unknown server-side error occurred while processing the command.","sessionId":":sessionId"}
>> proxy.js:55:14 [master] pid:25010 Proxy: /wd/hub/session/bc4d90dc-34ef-469d-94e6-d5424ab29997/element/1/click:POST to http://127.0.0.1:9003/wd/hub/session/:sessionId/element/1/click:POST with body: {}
>> proxy.js:83:20 [master] pid:25010 Got response with status 200: {"status":13,"value":"An unknown server-side error occurred while processing the command.","sessionId":"bc4d90dc-34ef-469d-94e6-d5424ab29997"}`

**Comment by wangcong01** [comment]
我也遇到相同的问题， 该问题是否得到解决？

**Comment by laiyuncong8404** [comment]
@wangcong01 
没有。

**Comment by xudafeng** [comment]
升级最新sample

**Comment by laiyuncong8404** [comment]
更新sample后运行成功

**Comment by ZTTALTAI** [comment]
哈喽 现在demo还能运行成功么 我本地项目也有这个问题，然后运行了官方最新的sample demo java和nodejs的 也同样报错。
