### ISSUE TITLE
Android平台运行macaca-test-sample示例过程中，报错： macaca-chromedriver.js:168:18 [master] pid:19718 chromedriver exit with code: null, signal: SIGTERM

### ISSUE THREAD

**Issue by xuyuhan** [alibaba/macaca#660]
**执行命令：**  macaca run --verbose -d macaca-test/macaca-mobile-sample.test.js -o test-report/android_report.html

错误信息：  >> responseHandler.js:11:12 [master] pid:19718 Recieve HTTP Request from Client[2017-07-30 17:20:05]: method: DELETE url: /wd/hub/session/ad459a18-5acf-4a82-997d-98bac85df599, jsonBody: {}
>> session.js:80:12 [master] pid:19718 Delete session, sessionId: ad459a18-5acf-4a82-997d-98bac85df599
>> responseHandler.js:47:14 [master] pid:19718 Send HTTP Respone to Client[2017-07-30 17:20:05]: {"sessionId":"ad459a18-5acf-4a82-997d-98bac85df599","status":0}
>> **macaca-chromedriver.js:168:18 [master] pid:19718 chromedriver exit with code: null, signal: SIGTERM**
>> 

-----------------------------------------------------------------------------------
**版本信息：**
**Macaca Version:**   2.0.4
**Macaca Doctor:** 
  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/node/node-v6.11.1-linux-x64/bin/node
  node version: v6.11.1

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is set to `/usr/local/java/jdk1.8.0_144`
  ANDROID_HOME is set to `/home/pchost/Android/Sdk`
  Platforms is set to `/home/pchost/Android/Sdk/platforms/android-26`
  ADB tool is set to `/home/pchost/Android/Sdk/platform-tools/adb`
  gradle is installed, version: 3.3

  Installed driver list:

  android: 2.0.30
  chrome: 1.0.6
  electron: 1.1.7

**Platform:**  Linux pchost-ubuntu 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**chromedriver:**  ChromeDriver 2.23

--------------------------------------------------------------------------------
以上为64位Linux平台macaca环境 + Android 7.0 模拟器 遇到的问题；
此外在64位Windows7平台macaca环境 + Android 7.0 真机设备 也遇到同样的问题。

**Comment by xuyuhan** [comment]
更多日志信息：
>> index.js:18:12 [master] pid:19718 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '10.20.24.177',
  host: 'pchost-ubuntu',
  loaded_time: '2017-07-30 17:18:49' }
>> middlewares.js:17:10 [master] pid:19718 base middlewares attached
>> router.js:127:10 [master] pid:19718 router set
>> webdriver sdk launched
[ '/home/pchost/working/software/macaca-test-sample/node_modules/.bin/mocha',
  'macaca-test/macaca-mobile-sample.test.js',
  '--reporter',
  '--colors',
  '--verbose' ]
>> 


>> /////////////////////////////////////


please use `macaca-wd` instead


https://macacajs.github.io/nodejs


/////////////////////////////////////



>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:19718 Recieve HTTP Request from Client[2017-07-30 17:18:49]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"Android","app":"/home/pchost/working/software/macaca-test-sample/app/android-app-bootstrap.zip","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:19718 Creating session, sessionId: ad459a18-5acf-4a82-997d-98bac85df599.
>> helper.js:194:12 [master] pid:19718 Unzipping local app form /home/pchost/working/software/macaca-test-sample/app/android-app-bootstrap.zip
>> uiautomator-client.js:56:14 [master] pid:19718 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:56:14 [master] pid:19718 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9001<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> macaca-android.js:230:12 [master] pid:19718 unlock apk not found in: /usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/node_modules/unlock-apk/app/build/outputs/apk/app-debug.apk
>> macaca-android.js:293:10 [master] pid:19718 start app with: {"package":"com.github.android_app_bootstrap","activity":"com.github.android_app_bootstrap.activity.WelcomeActivity"}
>> responseHandler.js:47:14 [master] pid:19718 Send HTTP Respone to Client[2017-07-30 17:18:57]: {"sessionId":"ad459a18-5acf-4a82-997d-98bac85df599","status":0,"value":"{\"platformName\":\"Android\",\"app\":\"/tmp/android-app-bootstrap.apk\",\"browserName\":\"firefox\",\"version\":\"\",\"javascriptEnabled\":true,\"platform\":\"ANY\",\"show\":true}"}
>> responseHandler.js:11:12 [master] pid:19718 Recieve HTTP Request from Client[2017-07-30 17:18:57]: method: GET url: /wd/hub/session/ad459a18-5acf-4a82-997d-98bac85df599/window/current/size, jsonBody: {}
>> proxy.js:55:14 [master] pid:19718 Proxy: /wd/hub/session/ad459a18-5acf-4a82-997d-98bac85df599/window/current/size:GET to http://127.0.0.1:9001/wd/hub/session/ad459a18-5acf-4a82-997d-98bac85df599/window/current/size:GET with body: {}
>> proxy.js:83:20 [master] pid:19718 Got response with status 200: {"status":0,"value":{"height":1794,"width":1080},"sessionId":null}
>> session.js:107:14 [master] pid:19718 Send HTTP Respone to Client[2017-07-30 17:18:57]: {"status":0,"value":"{\"height\":1794,\"width\":1080}","sessionId":null}
>> current window size {"height":1794,"width":1080}
..................
>> this.webviewVersion found 52 use it!
>> starting chromedriver service!
>> chromedriver bin path: /usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/node_modules/macaca-chromedriver/exec/chromedriver2.23
>> Starting ChromeDriver 2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:51:14 [master] pid:19718 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body: 
>> proxy.js:57:16 [master] pid:19718 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Linux\",\"version\":\"4.4.0-87-generic\"}}}"
>> proxy.js:51:14 [master] pid:19718 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.github.android_app_bootstrap","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
>> proxy.js:57:16 [master] pid:19718 Got response with status 200: {"sessionId":"9f6134b5d771c7e8ef9cd2877ecde155","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=L...
>> chromedriver ready with: {"sessionId":null,"status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)"}}
>> proxy.js:51:14 [master] pid:19718 Proxy: /wd/hub/session/:sessionId/window_handles:GET to http://localhost:9515/wd/hub/session/9f6134b5d771c7e8ef9cd2877ecde155/window_handles:GET with body: {}
>> proxy.js:57:16 [master] pid:19718 Got response with status 200: {"sessionId":"9f6134b5d771c7e8ef9cd2877ecde155","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4....
>> responseHandler.js:54:12 [master] pid:19718 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)
>> responseHandler.js:60:14 [master] pid:19718 NoSuchDriver: no such session
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)
    at Object._.parseWebDriverResult (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/lib/helper.js:72:11)
    at Android.getWebviews (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/lib/macaca-android.js:326:16)
    at next (native)
    at onFulfilled (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
>> responseHandler.js:76:14 [master] pid:19718 Send Bad HTTP Respone to Client[2017-07-30 17:20:04]: {"sessionId":"ad459a18-5acf-4a82-997d-98bac85df599","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)"}}
>> 
>>     4) #5 should go into webview

>> responseHandler.js:11:12 [master] pid:19718 Recieve HTTP Request from Client[2017-07-30 17:20:04]: method: GET url: /wd/hub/session/ad459a18-5acf-4a82-997d-98bac85df599/contexts, jsonBody: {}
>> proxy.js:51:14 [master] pid:19718 Proxy: /wd/hub/session/:sessionId/window_handles:GET to http://localhost:9515/wd/hub/session/9f6134b5d771c7e8ef9cd2877ecde155/window_handles:GET with body: {}
>> proxy.js:57:16 [master] pid:19718 Got response with status 200: {"sessionId":"9f6134b5d771c7e8ef9cd2877ecde155","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4....
>> responseHandler.js:54:12 [master] pid:19718 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)
>> responseHandler.js:60:14 [master] pid:19718 NoSuchDriver: no such session
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)
    at Object._.parseWebDriverResult (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/lib/helper.js:72:11)
    at Android.getWebviews (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/lib/macaca-android.js:326:16)
    at next (native)
    at onFulfilled (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
>> responseHandler.js:76:14 [master] pid:19718 Send Bad HTTP Respone to Client[2017-07-30 17:20:04]: {"sessionId":"ad459a18-5acf-4a82-997d-98bac85df599","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)"}}
>> 
>>     5) #6 should go into test

>> responseHandler.js:11:12 [master] pid:19718 Recieve HTTP Request from Client[2017-07-30 17:20:04]: method: GET url: /wd/hub/session/ad459a18-5acf-4a82-997d-98bac85df599/contexts, jsonBody: {}
>> proxy.js:51:14 [master] pid:19718 Proxy: /wd/hub/session/:sessionId/window_handles:GET to http://localhost:9515/wd/hub/session/9f6134b5d771c7e8ef9cd2877ecde155/window_handles:GET with body: {}
>> proxy.js:57:16 [master] pid:19718 Got response with status 200: {"sessionId":"9f6134b5d771c7e8ef9cd2877ecde155","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4....
>> responseHandler.js:54:12 [master] pid:19718 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)
>> responseHandler.js:60:14 [master] pid:19718 NoSuchDriver: no such session
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)
    at Object._.parseWebDriverResult (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/lib/helper.js:72:11)
    at Android.getWebviews (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/lib/macaca-android.js:326:16)
    at next (native)
    at onFulfilled (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
>> responseHandler.js:76:14 [master] pid:19718 Send Bad HTTP Respone to Client[2017-07-30 17:20:04]: {"sessionId":"ad459a18-5acf-4a82-997d-98bac85df599","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)"}}
>> 
>>     6) #7 should works with web

>> responseHandler.js:11:12 [master] pid:19718 Recieve HTTP Request from Client[2017-07-30 17:20:04]: method: GET url: /wd/hub/session/ad459a18-5acf-4a82-997d-98bac85df599/contexts, jsonBody: {}
>> proxy.js:51:14 [master] pid:19718 Proxy: /wd/hub/session/:sessionId/window_handles:GET to http://localhost:9515/wd/hub/session/9f6134b5d771c7e8ef9cd2877ecde155/window_handles:GET with body: {}
>> proxy.js:57:16 [master] pid:19718 Got response with status 200: {"sessionId":"9f6134b5d771c7e8ef9cd2877ecde155","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4....
>> responseHandler.js:54:12 [master] pid:19718 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)
>> responseHandler.js:60:14 [master] pid:19718 NoSuchDriver: no such session
  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)
    at Object._.parseWebDriverResult (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/lib/helper.js:72:11)
    at Android.getWebviews (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-android/lib/macaca-android.js:326:16)
    at next (native)
    at onFulfilled (/usr/local/node/node-v6.11.1-linux-x64/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
>> responseHandler.js:76:14 [master] pid:19718 Send Bad HTTP Respone to Client[2017-07-30 17:20:04]: {"sessionId":"ad459a18-5acf-4a82-997d-98bac85df599","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1),platform=Linux 4.4.0-87-generic x86_64)"}}
>> 
>>     7) #8 should logout success

>> responseHandler.js:11:12 [master] pid:19718 Recieve HTTP Request from Client[2017-07-30 17:20:05]: method: DELETE url: /wd/hub/session/ad459a18-5acf-4a82-997d-98bac85df599, jsonBody: {}
>> session.js:80:12 [master] pid:19718 Delete session, sessionId: ad459a18-5acf-4a82-997d-98bac85df599
>> responseHandler.js:47:14 [master] pid:19718 Send HTTP Respone to Client[2017-07-30 17:20:05]: {"sessionId":"ad459a18-5acf-4a82-997d-98bac85df599","status":0}
>> macaca-chromedriver.js:168:18 [master] pid:19718 chromedriver exit with code: null, signal: SIGTERM
>> 

  1 passing (1m)
  7 failing
....................................

**Comment by xudafeng** [comment]
```
/////////////////////////////////////
please use macaca-wd instead

https://macacajs.github.io/nodejs

/////////////////////////////////////
```

**Comment by xuyuhan** [comment]
@xudafeng  谢谢你的回复，，，我之前跑的测试脚本是来自这个地址： https://github.com/xiaxiazhu/macaca-test-sample，，他使用的是webdriver-client，可能代码比较陈旧。现在我按照你的回复，重新下载了https://github.com/macaca-sample/sample-nodejs 代码。不过运行的时候，仍然遇到了相同的问题，还是报错：chromedriver exit with code: null, signal: SIGTERM，，，不同的是，这个脚本跑的时间更长，已经执行了好几个页面，出错时间要晚一些。

**Comment by xudafeng** [comment]
查看faq，跟chromedriver版本有关
