### ISSUE TITLE
Android sdk not support 空格

### ISSUE THREAD

**Issue by malasang** [alibaba/macaca#661]
* **Macaca Version**:
2.0.4

* **Macaca Doctor Logs**:
  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home`
  ANDROID_HOME is set to `/Applications/Android Sutdio0.app/sdk`
  Platforms is set to `/Applications/Android Sutdio0.app/sdk/platforms/android-8`
  ADB tool is set to `/Applications/Android Sutdio0.app/sdk/platform-tools/adb`
  gradle is installed, version: 4.0

* **Operate System**:
10.11.6 (15G31) OS X EI Captian
* **Programming Language**:
[图片](https://private-alipayobjects.alipay.com/alipay-rmsdeploy-image/rmsportal/DOWVeaNoloFrcyrfBNLf.png)

**Comment by xudafeng** [comment]
$ANDROID_HOME 设置不对，添加转移符
