### ISSUE TITLE
not support android 8.0

### ISSUE THREAD

**Issue by malasang** [alibaba/macaca#662]
* **Macaca Version**:
2.0.4
* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.2.1

  iOS checklist:

  Xcode Command Line Tools require version: 2347 and above
  xcodebuild version: 8.2.1 lower than 8.3.2
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled
  carthage is uninstalled

  Android checklist:

  JAVA version is `1.8.0_102`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home`
  ANDROID_HOME is set to `/Applications/Android_SDK/sdk`
  Platforms is set to `/Applications/Android_SDK/sdk/platforms/android-8`
  ADB tool is set to `/Applications/Android_SDK/sdk/platform-tools/adb`
  gradle is installed, version: 4.0

  Installed driver list:

  android: 2.0.30
  ios: 2.0.23
* **Operate System**:
10.11.6 (15G31) OS X EI Captian
* **Programming Language**:
>> responseHandler.js:54:12 [master] pid:18453 Send Error Respone to Client: get PIDs failed with TypeError: Cannot read property '0' of null

  InternalServerError: Internal Server Error
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/_webdriver-server@1.0.77@webdriver-server/lib/server/responseHandler.js:57:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/615

**Comment by xudafeng** [comment]
android-8 还是android-26？？

**Comment by xudafeng** [comment]
https://github.com/macacajs/UIAutomatorWD/commit/9af6eb5a27f54cf2d7829e49a853bfc6b09cd1d4

**Comment by xudafeng** [comment]
https://github.com/macacajs/unlock-apk/commit/2ab41857c40eb51b4c0434bd978f0f8f10643fa7
