### ISSUE TITLE
关于ios的录制回放问题

### ISSUE THREAD

**Issue by adudurant** [alibaba/macaca#664]
想问下，ios能通过window的pc机器来实现录制回放的功能吗？就是不基于mac

**Comment by xudafeng** [comment]
windows不支持iOS录制

**Comment by adudurant** [comment]
@xudafeng   那如果我想做一个 大范围的录制 回放。有什么好的思路的，是不是只能部署多个mac然后搭建录制的环境呢

**Comment by adudurant** [comment]
@xudafeng   我的意思是在windows上面做个客户端来录制 但是服务在mac上面启起来，这样的可以吗？
