### ISSUE TITLE
ios录制回放的思考

### ISSUE THREAD

**Issue by adudurant** [alibaba/macaca#665]
如果我想做一个 大范围的录制 回放。有什么好的思路的，是不是只能给每个人部署一个mac机器，让他们自己来进行录制回放？  还是说有什么法子能够达跨平台的效果呢，更好的进行集成和扩展？

**Comment by xudafeng** [comment]
@yaniswang uirecorder可以提供平台部署方式吗？目前的工具形式暂时支持不了
