### ISSUE TITLE
macaca录制的脚本，用户名可以正常输入字符，而密码输入框怎么都不能输入任何字符。

### ISSUE THREAD

**Issue by pmhgo** [alibaba/macaca#668]
* **Macaca Version**:2.0.4

* **Macaca Doctor Logs**:ok

* **Operate System**:andriod

* **Programming Language**:nodejs

**Comment by pmhgo** [comment]
尝试换了别的手机，密码输入正常..

**Comment by xudafeng** [comment]
参照官方sample，与密码框的具体实现有关
