### ISSUE TITLE
macaca运行安卓样例，报The environment you requested was unavailable.请问是哪里没配置对吗

### ISSUE THREAD

**Issue by zhengzejian** [alibaba/macaca#669]
* **Macaca Version**: 2.0.1

* **Macaca Doctor Logs**: Node.js checklist:

 node env: D:\NodeJs\node.exe
 node version: v6.9.4

 Android checklist:

 JAVA version is `1.8.0_144`
 JAVA_HOME is set to `D:\javaSDK\javSDK`
 ANDROID_HOME is set to `D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-
indows`
 Platforms is set to `D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-win
ows\platforms\android-25`
 ADB tool is set to `D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-wind
ws\platform-tools\adb.exe`
 GRADLE_HOME is set to `D:\Gradle\gradle-4.0.2-all\gradle-4.0.2`

 Installed driver list:

 android: 2.0.30
 chrome: 1.0.6
 electron: 1.1.7 [out-of-date]
 ios: 2.0.22 [out-of-date]

* **Operate System**:Android

* **Programming Language**:NodeJs

跟着文档运行安卓样例，然后报错
  Error: Command failed: D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-w
indows/platform-tools/adb -s emulator-5556 push C:\Users\dan\AppData\Roaming\npm
\node_modules\macaca-android\node_modules\_uiautomatorwd@1.0.40@uiautomatorwd\ap
p\build\outputs\apk\app-debug.apk /data/local/tmp/com.macaca.android.testing

>>   1) macaca mobile sample "before all" hook:
     Error: [init({"platformName":"Android","autoAcceptAlerts":false,"isWaitActi
vity":true,"app":"https://npmcdn.com/android-app-bootstrap@latest/android_app_bo
otstrap/build/outputs/apk/android_app_bootstrap-debug.apk"})] The environment yo
u requested was unavailable.

运行时模拟机没有安装运行APP，怀疑是没有发送操作请求到模拟机，但不知道是哪出错，研究了快一个星期没结果，不得已来提问，还请解答谢谢！

下面为配置环境:
D:\macaca-test-demo\sample-nodejs>adb devices -l
List of devices attached
emulator-5556          device product:sdk_phone_armv7 model:sdk_phone_armv7 devi
ce:generic
模拟机启动应该是正常的 并应该连接了

环境也配好了
D:\macaca-test-demo\sample-nodejs>macaca doctor

  macaca-doctor version: 2.0.1

  Node.js checklist:

  node env: D:\NodeJs\node.exe
  node version: v6.9.4

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is set to `D:\javaSDK\javSDK`
  ANDROID_HOME is set to `D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-
windows`
  Platforms is set to `D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-win
dows\platforms\android-25`
  ADB tool is set to `D:\androidSDK\android-sdk_r24.4.1-windows\android-sdk-wind
ows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\Gradle\gradle-4.0.2-all\gradle-4.0.2`

  Installed driver list:

  android: 2.0.30
  chrome: 1.0.6
  electron: 1.1.7
  ios: 2.0.22 [out-of-date]

**Comment by chenjiejiji** [comment]
1.对应目录下有这个C:\Users\dan\AppData\Roaming\npm
\node_modules\macaca-android\node_modules_uiautomatorwd@1.0.40@uiautomatorwd\ap
p\build\outputs\apk\app-debug.apk 文件吗 可能是没有生成对应的！解决方法（用cnpm 在拉一下确认在对应文件下生成了指定apk）
2.如果，有的话 ，可能是运行权限的问题。麻烦把 node 和 node-global 安装在D盘

**Comment by zhengzejian** [comment]
C:\Users\dan\AppData\Roaming\npm
\node_modules\macaca-android\node_modules_uiautomatorwd@1.0.40@uiautomatorwd\ap
p\build 到了这个文件就找不到outputs文件了 bulid文件里面只有这个intermediates文件，而且再往下打开这个文件也找不到上面指定的文件  请问这时该怎么做？？

**Comment by chenjiejiji** [comment]
这2个apk的报是在下载的时候通过Gradle编译生成的，请看有方法1括号里面的解决方法
