### ISSUE TITLE
macaca 关键字autoAcceptAlerts 不能对全部系统弹框做允许操作

### ISSUE THREAD

**Issue by chenjiejiji** [alibaba/macaca#671]
被测试应用：
腾讯动漫 
启动应用代码：
server_url = {
		'hostname':'127.0.0.1',
		'post':3456
}
desired_caps = {
		'autoAcceptAlerts':'true',
		'platformName':'android',
		'deviceName':'nexus5',
		'udid':'0307fd5a54a391d0',
		'package':'com.qq.ac.android'
}
![image](https://user-images.githubusercontent.com/6800735/29026134-cf8f4ad6-7bac-11e7-93ef-4336d5d3565e.png)
从描述上官网文档上的描述看应该是对所有的都能操作。
实际的结果：
只能对启动应用的第一个弹框做处理。

* **Macaca 环境**:
macaca-doctor version: 2.0.1

Node.js checklist:

node env: H:\nodejs\node.exe
node version: v6.11.0

Android checklist:

JAVA version is `1.8.0_131`
JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_131`
ANDROID_HOME is set to `H:\Android\android-sdk\`
Platforms is set to `H:\Android\android-sdk\platforms\android-25`
ADB tool is set to `H:\Android\android-sdk\platform-tools\adb.exe`
GRADLE_HOME is set to `H:\Gradle\`

Installed driver list:

android: 2.0.30 [out-of-date]
chrome: 1.0.6
electron: 1.1.7 [out-of-date]
* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by chenjiejiji** [comment]
请问是不是使用方法有问题！

**Comment by xudafeng** [comment]
@chenjiejiji 特殊地方手动调acceptAlert试试

**Comment by chenjiejiji** [comment]
谢谢 我试试看

**Comment by chenjiejiji** [comment]
@xudafeng 我试试看

**Comment by chenjiejiji** [comment]
好的 明白；额 谢谢
