### ISSUE TITLE
XCTextWDRunner报错

### ISSUE THREAD

**Issue by SmileYXHP** [alibaba/macaca#674]
* **Macaca Version**: 2.0.6;
* **npm Version**:5.3.0

* **Macaca Doctor Logs**

  macaca-doctor version: 2.0.2

  Node.js checklist:

  node env: /Users/xxx/.nvm/versions/node/v8.2.1/bin/node
  node version: v8.2.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  gradle is installed, version: 4.0

  Installed driver list:

  ios: 2.0.23

* **Operate System**:Darwin xxx.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

* **Programming Language**:node.js

* **XCTextWDRunner wrong log**:

/Users/xxx/Library/Developer/Xcode/DerivedData/XCTestWD-dwrvssjtosjuwrercaufhjgxjymn/Build/Intermediates/XCTestWD.build/Debug-iphonesimulator/XCTestWDUITests.build/Script-7FA43F311F0CB57400FB2332.sh:
 line 12: ideviceinstaller: command not found
Command /bin/sh failed with exit code 127

* **ps**:把上面路径的12行删除,但是再次运行程序,12行的代码又自动回来了......
运行中还经常出现下面情况:
>> xctest-client.js:183:14 [master] pid:15936 xctest client exit with code: 65, signal: null
>> xctest-client.js:108:18 [master] pid:15936 simulator log process exit with code: null, signal: SIGKILL

>>     3) "before all" hook

>> responseHandler.js:11:12 [master] pid:15936 Recieve HTTP Request from Client[2017-08-10 18:40:26]: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:15936 Send HTTP Respone to Client[2017-08-10 18:40:26]: 405 Method Not Allowed

>>     4) "after all" hook

>>

**Comment by SamuelZhaoY** [comment]
“ ideviceinstaller: command not found”  安装下 ideviceinstaller， 这个是真机测试吧

**Comment by SmileYXHP** [comment]
嗯,我重新安装了ideviceinstaller,就好了.不是真机测试,是模拟器.谢谢你的解答.
