### ISSUE TITLE
无法使用waitForElement，文档介绍很少！

### ISSUE THREAD

**Issue by blackmatch** [alibaba/macaca#675]
* **Macaca Version**:1.0

* **Macaca Doctor Logs**:

* **Operate System**:windows 7

* **Programming Language**:node

macaca docker结果：

![21502418266_ pic_hd](https://user-images.githubusercontent.com/12443954/29199442-a1f08402-7e7f-11e7-84f9-73d2fe3bc6cf.jpg)

首先我想了解一下`waitForElement`这个方法是为了确保能拿到dom元素么？还是说只是为了让某个dom元素等待，然后手动进行一些操作（这样的话这个方法就没意义了）。如果是前者，我使用以下方式调用均失败了(我页面上有一个input元素的id是name)：

.waitForElementById('name').clear();
.waitForElementById('name', 3000, 3000).clear();
.waitForElementById('web', 'name').clear();
.waitForElementById('name', () =>{}, 3000).clear();

官方的说明也比较模糊，求正确的姿势，最好提供几个Demo。万分感激！

**Comment by xudafeng** [comment]
https://github.com/macaca-sample/sample-nodejs
