### ISSUE TITLE
对于pc版的macaca测试时，可以把"--start-maximized", "allow-running-insecure-content", "--test-type"等加到浏览器启动参数里

### ISSUE THREAD

**Issue by jacksonlai** [alibaba/macaca#677]
对于pc版的macaca测试时，建议把

"--start-maximized", "allow-running-insecure-content", "--test-type"

等参数加到浏览器启动参数里

我看到electron官网api是有allowRunningInsecureContent这个参数的

后面很多页面都是走https的，但因为在测试环境一般是不带证书，对于浏览器来说，会提示不安全，如果我们没有设置允许不安全的参数，页面就会显示空白

这里要注意：chrome和electron都需要用上这个参数

**Comment by xudafeng** [comment]
- "--start-maximized" 使用 .maximize 实现

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-electron/commit/843f458bc3ff2cc69214d0e4a45a346d9f929cb3

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-electron/commit/8a77a4a047db3e2ecb68e44826ec57aeee827e29

**Comment by jacksonlai** [comment]
完美支持了，感谢快捷响应修改。
1、对于https无证书页面直接跳过，不提示安全
2、对于http，https mixedContent的不安全情况自动忽略。
