### ISSUE TITLE
建议提供setCookie功能，在使用electron/chrome访问页面时，可以把cookie带上

### ISSUE THREAD

**Issue by jacksonlai** [alibaba/macaca#680]
由于页面的登录功能经常会使用到验证码，滑动验证机器人。

如果登录功能是自己实现的，可以跟研发提下设置一下万能验证码直接登录。参考：http://www.cnblogs.com/fnng/p/3606934.html

**可是如果登录体系是接的第三方，人家不愿意配合，可是cookie是存在我们本地数据库的，所以带cookie访问页面就能绕过登录这个过程。**

建议提供setCookie功能，在使用electron访问页面时，自动可以把cookie带上

**Comment by xudafeng** [comment]
https://electron.atom.io/docs/api/cookies/

**Comment by jacksonlai** [comment]
#538 关联

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-electron/pull/19/

**Comment by xudafeng** [comment]
@jacksonlai 补充下用法
