### ISSUE TITLE
自从2.0.0更新版本之后后续又更新了几次，python，send_keys更新后一直都是单个字符一个一个输入的

### ISSUE THREAD

**Issue by zhaojiabi** [alibaba/macaca#683]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

自从2.0.0更新版本之后后续又更新了几次，python，send_keys更新后一直都是单个字符一个一个输入的，之前的bug已经修复。新电脑安装没有问题，只有更新的会有问题，重新安装了环境还是有相同问题。不知道是否还有哪里需要更新。

**Comment by zhaojiabi** [comment]
macaca doctor:
macaca-doctor version: 2.0.2

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.1.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_40`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhaojiabi/Library/Android/sdk`
  Platforms is set to `/Users/zhaojiabi/Library/Android/sdk/platforms/android-8`
  ADB tool is set to `/Users/zhaojiabi/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.36
  chrome: 1.0.6
  electron: 1.1.11
  ios: 2.0.24

**Comment by qichuan** [comment]
@zhaojiabi 只有在Python有这个问题吗？可以试一下 Nodejs 或其他语言吗？这个问题在iOS 和 Android 都存在吗？

**Comment by xudafeng** [comment]
@zhaojiabi @qichuan 已fix，升级wd.py 到最新版即可
