### ISSUE TITLE
ios真机启动

### ISSUE THREAD

**Issue by fengzzzz** [alibaba/macaca#685]
启用inspector 查看ios手机时 ，提示
Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object.exports._errnoException (util.js:1022:11)
      at exports._exceptionWithHostPort (util.js:1045:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

* **Macaca Version**:2.0.9  inspector:2.0.7

* **Macaca Doctor Logs**:

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yeleng/Library/Android/sdk`
  Platforms is set to `/Users/yeleng/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/yeleng/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.4

  Installed driver list:

  android: 2.0.36
  ios: 2.0.24

* **Operate System**:mac osx sierra

* **Programming Language**:

**Comment by xudafeng** [comment]
检查环境
