### ISSUE TITLE
iOS 实现 swipe

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#69]
目前缺失：driver.swipe(startX, startY, endX, endY, duration)

**Comment by xudafeng** [comment]
Android 端已实现 https://testerhome.com/topics/4766

**Comment by sencho** [comment]
solved

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5307

**Comment by xudafeng** [comment]
API: http://macacajs.github.io/macaca-wd/api/#swipe
