### ISSUE TITLE
ubuntu 16.04.2 server版本环境无异常安装android时未成功

### ISSUE THREAD

**Issue by dongwenhua** [alibaba/macaca#691]
$ macaca doctor

  macaca-doctor version: 2.0.2

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.4.0

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is set to `/usr/lib/jvm/java-8-oracle`
  ANDROID_HOME is set to `/home/xxxxx/jenkins/android-sdk`
  Platforms is set to `/home/xxxxx/jenkins/android-sdk/platforms/android-25`
  ADB tool is set to `/home/xxxxx/jenkins/android-sdk/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

$ sudo npm i -g macaca-android
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.

> macaca-chromedriver@1.0.37 install /usr/local/lib/node_modules/macaca-android/node_modules/macaca-chromedriver
> node ./bin/macaca-chromedriver install

/usr/local/lib/node_modules/macaca-android/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/macaca-android/logs'
    at Object.fs.mkdirSync (fs.js:891:18)
    at Object.sync [as mkdir] (/usr/local/lib/node_modules/macaca-android/node_modules/mkdirp/index.js:71:13)
    at Logger._init (/usr/local/lib/node_modules/macaca-android/node_modules/xlogger/lib/xlogger.js:44:5)
    at new Logger (/usr/local/lib/node_modules/macaca-android/node_modules/xlogger/lib/xlogger.js:40:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/xlogger/lib/xlogger.js:172:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macaca-chromedriver@1.0.37 install: `node ./bin/macaca-chromedriver install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the macaca-chromedriver@1.0.37 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxxx/.npm/_logs/2017-08-31T13_39_14_839Z-debug.log

**Comment by dongwenhua** [comment]
通过从桌面版的ubuntu上拷贝已安装好的macaca-android模块后 可以正常使用

**Comment by Archer456** [comment]
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/macaca-android/logs'

为什么用sudo 命令安装   检查下你的 node 权限  

请参考 https://testerhome.com/topics/5509

最好ls -al 下查看下解压并改名出来的nodejs 的所属用户和用户组和权限 我是看到所属用户和组是数字？好像是忘了没记录。
我就chown -R 用户:用户组 nodejs 给都给改成我当前账号的了

同理 android-sdk 也可以设置为 当前登录账号      尽量不要用sudo 或者 root账号   尽量用普通登录账号

**Comment by litingjun2015** [comment]
@Archer456  不用 sudo 安装会报错：

>  MAVEN_MIRROR_URL=http://maven.aliyun.com/nexus/content/groups/public/ npm i macaca-android -g


```
macaca@ubuntu-Standard-PC-i440FX-PIIX-1996:~$ MAVEN_MIRROR_URL=http://maven.aliyun.com/nexus/content/groups/public/ npm i macaca-android -g
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└─┬ macaca-android@2.0.40
  ├── driver-base@0.1.4
  ├─┬ macaca-adb@1.0.29
  │ ├─┬ chalk@1.1.3
  │ │ ├── ansi-styles@2.2.1
  │ │ ├── escape-string-regexp@1.0.5
  │ │ ├─┬ has-ansi@2.0.0
  │ │ │ └── ansi-regex@2.1.1
  │ │ ├── strip-ansi@3.0.1
  │ │ └── supports-color@2.0.0
  │ ├── commander@2.11.0
  │ ├── macaca-utils@0.1.9
  │ ├─┬ npm-update@1.0.6
  │ │ └── co-request@0.2.1
  │ └─┬ xutil@1.0.7
  │   ├─┬ ipv4@1.0.1
  │   │ └─┬ copy-paste@1.3.0
  │   │   ├── iconv-lite@0.4.19
  │   │   └── sync-exec@0.6.2
  │   ├── lodash@4.17.4
  │   ├─┬ mkdirp@0.5.1
  │   │ └── minimist@0.0.8
  │   ├── moment@2.10.6
  │   ├─┬ rimraf@2.5.4
  │   │ └─┬ glob@7.1.2
  │   │   ├── fs.realpath@1.0.0
  │   │   ├─┬ inflight@1.0.6
  │   │   │ └── wrappy@1.0.2
  │   │   ├── inherits@2.0.3
  │   │   ├─┬ minimatch@3.0.4
  │   │   │ └─┬ brace-expansion@1.1.8
  │   │   │   ├── balanced-match@1.0.0
  │   │   │   └── concat-map@0.0.1
  │   │   ├── once@1.4.0
  │   │   └── path-is-absolute@1.0.1
  │   └── uuid@3.1.0
  ├─┬ macaca-chromedriver@1.0.39
  │ ├── adm-zip@0.4.7
  │ ├─┬ commander@2.9.0
  │ │ └── graceful-readlink@1.0.1
  │ ├─┬ detect-port@1.2.1
  │ │ ├── address@1.0.3
  │ │ └─┬ debug@2.6.9
  │ │   └── ms@2.0.0
  │ └─┬ request@2.69.0
  │   ├── aws-sign2@0.6.0
  │   ├── aws4@1.6.0
  │   ├─┬ bl@1.0.3
  │   │ └─┬ readable-stream@2.0.6
  │   │   ├── core-util-is@1.0.2
  │   │   ├── isarray@1.0.0
  │   │   ├── process-nextick-args@1.0.7
  │   │   ├── string_decoder@0.10.31
  │   │   └── util-deprecate@1.0.2
  │   ├── caseless@0.11.0
  │   ├─┬ combined-stream@1.0.5
  │   │ └── delayed-stream@1.0.0
  │   ├── extend@3.0.1
  │   ├── forever-agent@0.6.1
  │   ├─┬ form-data@1.0.1
  │   │ └── async@2.5.0
  │   ├─┬ har-validator@2.0.6
  │   │ ├─┬ is-my-json-valid@2.16.1
  │   │ │ ├── generate-function@2.0.0
  │   │ │ ├─┬ generate-object-property@1.2.0
  │   │ │ │ └── is-property@1.0.2
  │   │ │ ├── jsonpointer@4.0.1
  │   │ │ └── xtend@4.0.1
  │   │ └─┬ pinkie-promise@2.0.1
  │   │   └── pinkie@2.0.4
  │   ├─┬ hawk@3.1.3
  │   │ ├── boom@2.10.1
  │   │ ├── cryptiles@2.0.5
  │   │ ├── hoek@2.16.3
  │   │ └── sntp@1.0.9
  │   ├─┬ http-signature@1.1.1
  │   │ ├── assert-plus@0.2.0
  │   │ ├─┬ jsprim@1.4.1
  │   │ │ ├── extsprintf@1.3.0
  │   │ │ ├── json-schema@0.2.3
  │   │ │ └── verror@1.10.0
  │   │ └─┬ sshpk@1.13.1
  │   │   ├── asn1@0.2.3
  │   │   ├── bcrypt-pbkdf@1.0.1
  │   │   ├── dashdash@1.14.1
  │   │   ├── ecc-jsbn@0.1.1
  │   │   ├── getpass@0.1.7
  │   │   ├── jsbn@0.1.1
  │   │   └── tweetnacl@0.14.5
  │   ├── is-typedarray@1.0.0
  │   ├── isstream@0.1.2
  │   ├── json-stringify-safe@5.0.1
  │   ├─┬ mime-types@2.1.17
  │   │ └── mime-db@1.30.0
  │   ├── node-uuid@1.4.8
  │   ├── oauth-sign@0.8.2
  │   ├── qs@6.0.4
  │   ├── stringstream@0.0.5
  │   ├── tough-cookie@2.2.2
  │   └── tunnel-agent@0.4.3
  ├── macaca-utils@1.0.0
  ├─┬ temp@0.8.3
  │ ├── os-tmpdir@1.0.2
  │ └── rimraf@2.2.8
  ├─┬ uiautomatorwd@1.0.45
  │ ├─┬ gradle@1.0.8
  │ │ └── win-spawn@2.0.0
  │ └─┬ request@2.83.0
  │   ├── aws-sign2@0.7.0
  │   ├── caseless@0.12.0
  │   ├─┬ form-data@2.3.1
  │   │ └── asynckit@0.4.0
  │   ├─┬ har-validator@5.0.3
  │   │ ├─┬ ajv@5.3.0
  │   │ │ ├── co@4.6.0
  │   │ │ ├── fast-deep-equal@1.0.0
  │   │ │ ├── fast-json-stable-stringify@2.0.0
  │   │ │ └── json-schema-traverse@0.3.1
  │   │ └── har-schema@2.0.0
  │   ├─┬ hawk@6.0.2
  │   │ ├── boom@4.3.1
  │   │ ├─┬ cryptiles@3.1.2
  │   │ │ └── boom@5.2.0
  │   │ ├── hoek@4.2.0
  │   │ └── sntp@2.1.0
  │   ├─┬ http-signature@1.2.0
  │   │ └── assert-plus@1.0.0
  │   ├── performance-now@2.1.0
  │   ├── qs@6.5.1
  │   ├── safe-buffer@5.1.1
  │   ├─┬ tough-cookie@2.3.3
  │   │ └── punycode@1.4.1
  │   └── tunnel-agent@0.6.0
  ├── unlock-apk@1.0.8
  ├── webdriver-dfn-error-code@1.0.4
  ├── xlogger@1.0.6
  └─┬ xml2map@1.0.2
    ├── sax@0.4.2
    └── xml-writer@1.7.0

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "macaca-android" "-g"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/macaca/.npm/_logs/2017-10-30T07_37_23_460Z-debug.log

```

**Comment by Archer456** [comment]
@litingjun2015   
请参考 https://testerhome.com/topics/5509
https://testerhome.com/topics/6507
ls -al 下查看下解压并改名出来的nodejs 的所属用户和用户组和权限 我是看到所属用户和组是数字？好像是忘了没记录。
我就chown -R 用户:用户组 nodejs 给都给改成我当前账号的了

同理 android-sdk 也可以设置为 当前登录账号 尽量不要用sudo 或者 root账号 尽量用普通登录账号

是权限问题 nodejs java android-sdk 这些 都用普通账号  来避免权限问题

**Comment by litingjun2015** [comment]
@Archer456 非常感谢！ 可以了
