### ISSUE TITLE
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

### ISSUE THREAD

**Issue by ulwxfjy** [alibaba/macaca#692]
>> xctest-client.js:179:14 [master] pid:2966 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2966 2017-09-01 12:06:46.525 xcodebuild[2970:69387] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/nbpt/Library/Developer/Xcode/DerivedData/XCTestWD-dmzkrzqgqycswxfjuqsoxtuhivee/Logs/Test/56A5C045-2380-4B98-83CD-C04D778A230D/Session-XCTestWDUITests-2017-09-01_120646-WZOLaC.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/nbpt/Library/Developer/Xcode/DerivedData/XCTestWD-dmzkrzqgqycswxfjuqsoxtuhivee/Logs/Test/56A5C045-2380-4B98-83CD-C04D778A230D/Session-XCTestWDUITests-2017-09-01_120646-WZOLaC.log}

>> xctest-client.js:179:14 [master] pid:2966 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2966 
Testing failed:

>> xctest-client.js:179:14 [master] pid:2966 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:178:14 [master] pid:2966 	XCTestWDUITests requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'
	Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/nbpt/Library/Developer/Xcode/DerivedData/XCTestWD-dmzkrzqgqycswxfjuqsoxtuhivee/Logs/Test/56A5C045-2380-4B98-83CD-C04D778A230D/Session-XCTestWDUITests-2017-09-01_120646-WZOLaC.log
** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

>> xctest-client.js:179:14 [master] pid:2966 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:263:14 [master] pid:2966 killing deviceLogProc pid: 2969
>> xctest-client.js:268:14 [master] pid:2966 killing runnerProc pid: 2970
>> xctest-client.js:189:14 [master] pid:2966 xctest client exit with code: 65, signal: null
>> xctest-client.js:150:16 [master] pid:2966 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:255:14 [master] pid:2966 Fail to start xctest: undefined
undefined
>> iOS device started: bfebd0cbc4871da6aa75c90b91919d7a9cb5d240
>> inspector start at: http://10.10.10.12:5678
  <-- GET /
>> helper.js:94:16 [master] pid:2966 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:1041:11)
      at _exceptionWithHostPort (util.js:1064:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)

在XCODE上调试/usr/local/lib/node_modules/app-inspector/node_modules/_xctestwd@1.1.8@xctestwd/XCTestWD/XCTestWD.xcodeproj在真机上运行正常
2017-09-01 12:13:21.457380+0800 XCTRunner[329:18491] Running tests...
2017-09-01 12:13:23.662906+0800 XCTRunner[329:18491] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-09-01 12:13:24.285
Test Suite 'XCTestWDUITests.xctest' started at 2017-09-01 12:13:24.287
Test Suite 'XCTextWDRunner' started at 2017-09-01 12:13:24.288
Test Case '-[XCTestWDUITests.XCTextWDRunner testRunner]' started.
    t =     0.00s     Start Test at 2017-09-01 12:13:24.290
    t =     0.01s     Set Up
2017-09-01 12:13:24.387435+0800 XCTRunner[329:18491] com.apple.test.XCTestWDUITests-Runner
2017-09-01 12:13:24.388403+0800 XCTRunner[329:18491] XCTestWDSetup->http://localhost:8001<-XCTestWDSetup

论坛中有人说：DEVELOPMENT_TEAM_ID=TEAM_ID cnpm i macaca-ios app-inspector -g带DEVELOPMENT_TEAM_ID安装，也试过了，然并卵

**Comment by ulwxfjy** [comment]
而启动

**Comment by ulwxfjy** [comment]
但是启动Simulator虚拟机又是正常的

**Comment by ztwo** [comment]
DEVELOPMENT_TEAM_ID=TEAM_ID 这个最新版本有bug，你进入xctestwd工程里手动选择team即可解决问题

**Comment by ulwxfjy** [comment]
手动选好了，app-inspector -u udid 启用查看元素还是报同样的错Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.3'

**Comment by ztwo** [comment]
app-inspector也手动选一下就行了
