### ISSUE TITLE
android-location方法requests 404

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#697]
* **Macaca Version**:2.0.9

* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.2

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.10.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/joko/Library/Android/sdk`
  Platforms is set to `/Users/joko/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/joko/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.36
  electron: 1.1.6 [out-of-date]
  ios: 2.0.23 [out-of-date]

* **Operate System**:
mac os 10.12.5

* **Programming Language**: python 2.7

预置环境:android 5.0 webview版本：54.0.2840.85
问题1：
步骤: 切换至webview，调用wait_for_element_by_partial_link_text('').location方法
问题描述: requests状态404。

```python
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:3457/wd/hub/session/379bd9cc-d7d5-48b2-925f-1b61172876a1/element/0.3729387510102242-1/location

```

问题2：python wd缺少针对location_in_view方法的调用。且我自己在wd增加此方法，也会报404。

麻烦排查解决

**Comment by xudafeng** [comment]
@ztwo 没有location

**Comment by ztwo** [comment]
@xudafeng python client源代码内有
```python
    @property
    def location(self):
        """The location of the element in the renderable canvas in pixels.

        Support:
            Web(WebView)

        Returns:
            A dict contains:
            x(float): X axis position of the top-left corner.
            y(float): Y axis position of the top-left corner.
        """
        return self._execute(Command.GET_ELEMENT_LOCATION)
```
    GET_ELEMENT_LOCATION = Endpoint(
        'GET',
        '/session/{session_id}/element/{element_id}/location'
```python

```

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.py/pull/32
