### ISSUE TITLE
Macaca是否支持Electron打包的桌面版应用程序的自动化测试，在electron的API中没找到相应的方法

### ISSUE THREAD

**Issue by YunhuiLee** [alibaba/macaca#698]
* **Macaca Version**:最新版

* **Macaca Doctor Logs**:

* **Operate System**:windows

* **Programming Language**:Java

Macaca是否支持Electron打包的桌面版应用程序的自动化测试，在electron的API中没找到相应的方法。官方的electron案例只是打开一个electron窗口，然后打开一个url，想知道是否支持打开一个已经由electron打包的安装好的exe程序，对桌面版的程序做UI自动化测试

**Comment by xudafeng** [comment]
electron 应用当成web应用来测试
