### ISSUE TITLE
macaca-reporter does not work

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#699]
* **Macaca Version**: 2.0.9

* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.2

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.4.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/preethi/Library/Android/sdk`
  Platforms is set to `/Users/preethi/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/preethi/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.31 [out-of-date]
  chrome: 1.0.6
  electron: 1.1.4 [out-of-date]
  ios: 2.0.22 [out-of-date]

* **Operate System**: Mac OS 10.12.5 

* **Programming Language**: JS

Command with "mocha" :
platform='Windows 7' PRODUCT_NAME='sxl'  SAUCELABS_USERNAME=strikingly  SAUCELABS_ACCESS_KEY=a7adf50f-fca8-4e2b-8a7a-0d21e03bce31  $(npm bin)/mocha  ./WebTests/SXL/SmokeTest/Landingpage  --reporter macaca-reporter --verbose

Here is the output:

(node:28325) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

  [Smoke Test] [Landing page link] Signup

    ✓ Landingpage-01 - Access landing page and signup (23319ms)

------------------------------------------------------------------------

https://saucelabs.com/jobs/29b12a7871024dfa82750d813576aee9?auth=9603b25fb2020568edbfed3562457a9d

------------------------------------------------------------------------

  [Smoke Test] [Landing page link] Discover

    ✓ Landingpage-02 - Access 发现 page and select each template (22083ms)

------------------------------------------------------------------------

https://saucelabs.com/jobs/626d553bf12a4c5e846dc87044288740?auth=6da2148aadda53d195efde57497f4248

------------------------------------------------------------------------

  2 passing (54s)

{ stats: 

   { suites: 2,

     tests: 2,

     passes: 2,

     pending: 0,

     failures: 0,

     start: 2017-09-13T01:45:45.483Z,

     passPercent: 66.7,

     pendingPercent: 0,

     other: 0,

     hasOther: false,

     skipped: 1,

     hasSkipped: true,

     duration: 45402,

     end: 2017-09-13T01:46:39.020Z },

  suites: 

   { title: '',

     ctx: {},

     suites: [ [Object], [Object] ],

     tests: [],

     pending: [],

     _beforeEach: [],

     _beforeAll: [],

     _afterEach: [],

     _afterAll: [],

     root: true,

     _timeout: 2000,

     _enableTimeouts: true,

     _slow: 75,

     _retries: -1,

     delayed: false,

     _events: { 'pre-require': [Object] },

     _eventsCount: 1,

     uuid: '5c9286a4-0b1a-47fa-8b9c-580d55a56084',

     fullFile: '',

     file: '',

     passes: [],

     failures: [],

     skipped: [],

     totalTests: 0,

     totalPasses: 0,

     totalFailures: 0,

     totalPending: 0,

     totalSkipped: 0,

     duration: 0,

     _totalTime: 45402 } } { name: 'macaca-reporter',

  fileName: 'index.html',

  assetsInline: true,

  dataAttr: 'data-output',

  configAttr: 'config-output',

  distDir: '/Users/preethi/Documents/QA-Automation' }

>> reporter generated: /Users/preethi/Documents/QA-Automation/reports/index.html

Command with mocha-parallel-tests :

platform='Windows 7' PRODUCT_NAME='sxl'  SAUCELABS_USERNAME=strikingly  SAUCELABS_ACCESS_KEY=a7adf50f-fca8-4e2b-8a7a-0d21e03bce31  $(npm bin)/mocha-parallel-tests  ./WebTests/SXL/SmokeTest/Landingpage  --reporter macaca-reporter --verbos

Here is the output:

(node:28402) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

------------------------------------------------------------------------

https://saucelabs.com/jobs/d42f1d3de2794d99b52a0e0846ad7839?auth=e2612b62f2dbf772f1a2340a2f9bac8c

------------------------------------------------------------------------

  [Smoke Test] [Landing page link] Signup

    ✓ Landingpage-01 - Access landing page and signup (19621ms)

------------------------------------------------------------------------

https://saucelabs.com/jobs/7a3c66cc2f3c425a8c00728fe42a0d5d?auth=d419cce159f1e6acc77d9fa9f9adcf28

------------------------------------------------------------------------

  [Smoke Test] [Landing page link] Discover

    ✓ Landingpage-02 - Access 发现 page and select each template (20617ms)

  2 passing (24s)

**Comment by xudafeng** [comment]
- [ ] mocha-parallel-tests error
- [ ] reporter 首次没有更新

**Comment by SamuelZhaoY** [comment]
use   io.sockets.emit('update reporter', mockData);  instead of  socket.broadcast.emit,  it will solve the issue that the first time page does not receive broadcast

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-reporter/issues/4

**Comment by mpreethi90** [comment]
@SamuelZhaoY Where do I have to add io.sockets.emit('update reporter', mockData); ? Because I haven't used  socket.broadcast.emit anywhere
