### ISSUE TITLE
Use "electron entry.js" command I can start a electron process,How I do with Macaca-electron

### ISSUE THREAD

**Issue by YunhuiLee** [alibaba/macaca#700]
* **Macaca Version**: The Latest Version

* **Macaca Doctor Logs**:

* **Operate System**: windows

* **Programming Language**: Java

Use "electron entry.js" command I can start a electron process,How I do with Macaca-electron, In Macaca-electron API, I can't find the same method

**Comment by xudafeng** [comment]
https://macacajs.github.io/zh/pageuitest
