### ISSUE TITLE
通用输入法设置

### ISSUE THREAD

**Issue by Yinxl** [alibaba/macaca#702]
目前的sendkeys()会调起系统键盘处理逻辑复杂多变，希望能支持utf7输入法简化处理逻辑
安卓真机上系统输入法和自定义输入法多种多样，用sendkeys调起键盘后失败率很高，建议增加utf7输入法的支持，这样在输入的时候可以不用吊起键盘，从而减少对应的处理

**Comment by xudafeng** [comment]
iOS与Android都会面临输入法弹出和隐藏的问题。输入法layout会影响当前界面的xml结构。

iOS与Android提供hideKeyBoard和showKeyBoard API开放到用户端是否可行？欢迎讨论

**Comment by SamuelZhaoY** [comment]
iOS 有个可能可行的方法， 需要验证.  这个也影响了NoSmoke 的使用
