### ISSUE TITLE
python client send_keys导致macaca server unknown error

### ISSUE THREAD

**Issue by laiyuncong8404** [alibaba/macaca#703]
* **Macaca Version**:
2.0.9
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.2

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.7.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/xiaoxue/Library/android-sdk-macosx`
  Platforms is set to `/Users/xiaoxue/Library/android-sdk-macosx/platforms/android-26`
  ADB tool is set to `/Users/xiaoxue/Library/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.36
  chrome: 1.0.6
  electron: 1.1.11
  ios: 2.0.20 [out-of-date]
* **Operate System**:
MacOS 10.12.3
* **Programming Language**:
Python 2.7

* **WD Version**:
0.1.10

* **server端Log**
`>> session.js:109:14 [master] pid:1695 Send HTTP Respone to Client[2017-09-21 09:19:06]: {"sessionId":"b2241619-2f29-4b46-be12-6dbae6432293","status":0,"value":"{\"ELEMENT\":\"1\"}"}
>> responseHandler.js:11:12 [master] pid:1695 Recieve HTTP Request from Client[2017-09-21 09:19:06]: method: POST url: /wd/hub/session/b2241619-2f29-4b46-be12-6dbae6432293/element/1/click, jsonBody: {}
>> proxy.js:55:14 [master] pid:1695 Proxy: /wd/hub/session/b2241619-2f29-4b46-be12-6dbae6432293/element/1/click:POST to http://127.0.0.1:9001/wd/hub/session/b2241619-2f29-4b46-be12-6dbae6432293/element/1/click:POST with body: {}
>> proxy.js:85:20 [master] pid:1695 Got response with status 200: {"sessionId":"b2241619-2f29-4b46-be12-6dbae6432293","status":0}
>> session.js:109:14 [master] pid:1695 Send HTTP Respone to Client[2017-09-21 09:19:07]: {"sessionId":"b2241619-2f29-4b46-be12-6dbae6432293","status":0}
>> responseHandler.js:11:12 [master] pid:1695 Recieve HTTP Request from Client[2017-09-21 09:19:07]: method: POST url: /wd/hub/session/b2241619-2f29-4b46-be12-6dbae6432293/element/1/value, jsonBody: {"value":["encyclopedia/#"]}
>> proxy.js:55:14 [master] pid:1695 Proxy: /wd/hub/session/b2241619-2f29-4b46-be12-6dbae6432293/element/1/value:POST to http://127.0.0.1:9001/wd/hub/session/b2241619-2f29-4b46-be12-6dbae6432293/element/1/value:POST with body: {"value":["encyclopedia/#"]}
>> proxy.js:85:20 [master] pid:1695 Got response with status 200: {"sessionId":"b2241619-2f29-4b46-be12-6dbae6432293","status":13,"value":"An unknown server-side error occurred while processing the command."}
>> session.js:109:14 [master] pid:1695 Send HTTP Respone to Client[2017-09-21 09:19:07]: {"sessionId":"b2241619-2f29-4b46-be12-6dbae6432293","status":13,"value":"\"An unknown server-side error occurred while processing the command.\""}`

* **Client端Log**
`test_01
Traceback (most recent call last):
  File "MQTT.py", line 100, in <module>
    test_01_sub(driver)
  File "MQTT.py", line 56, in test_01_sub
    .send_keys(topic_sub_encyclopedia)
  File "/Users/xiaoxue/Library/Python/2.7/lib/python/site-packages/macaca/util.py", line 145, in fluent_interface
    ret = func(instance, *args, **kwargs)
  File "/Users/xiaoxue/Library/Python/2.7/lib/python/site-packages/macaca/webelement.py", line 435, in send_keys
    'value': value_to_key_strokes(value)})
  File "/Users/xiaoxue/Library/Python/2.7/lib/python/site-packages/macaca/webelement.py", line 60, in _execute
    return self._driver._execute(command, data, unpack)
  File "/Users/xiaoxue/Library/Python/2.7/lib/python/site-packages/macaca/webdriver.py", line 68, in _execute
    ret.raise_for_status()
  File "/Users/xiaoxue/Library/Python/2.7/lib/python/site-packages/macaca/webdriverresult.py", line 54, in raise_for_status
    raise WebDriverException(error, message, screen, stacktrace)
macaca.webdriverexception.WebDriverException:
Error: WebDriverError.UNKNOWN_ERROR
Message: None`

**Comment by xudafeng** [comment]
升级最新 wd.py

**Comment by njf1107** [comment]
@laiyuncong8404 我也遇到一样的错误，但是升级wd后没有解决，请教下你是怎么解决的呢
