### ISSUE TITLE
xcode9 更新后  macaca doctor 显示  Xcode is uninstalled

### ISSUE THREAD

**Issue by oosnail** [alibaba/macaca#704]
macaca-doctor version: 2.0.2

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.5.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.25.0

  Android checklist:

  JAVA version is `1.6.0_65`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  android: 2.0.36
  chrome: 1.0.6
  electron: 1.1.11

**Comment by kidbear** [comment]
我也遇到了

**Comment by xudafeng** [comment]
@oosnail @kidbear 请升级新版macaca-cli
