### ISSUE TITLE
支持xcode9

### ISSUE THREAD

**Issue by grubby2013** [alibaba/macaca#705]
1./usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWDUITests/PrivateHeaders/XCUIApplication.h:37:1: Type of property 'unsigned long long' in class extension does not match property type in primary class

2.Failed to emit precompiled header '/Users/yujian/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Build/Intermediates.noindex/PrecompiledHeaders/XCTestWDUITests-Bridging-Header-swift_1AJWS0BF89JFL-clang_3F4FDQP5SKX2L.pch' for bridging header '/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWDUITests/XCTestWDUITests-Bridging-Header.h'

3.error: The following binaries use incompatible versions of Swift:
/Users/yujian/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Build/Products/Debug-iphoneos/XCTestWD.app/Frameworks/Swifter.framework/Swifter
/Users/yujian/Library/Developer/Xcode/DerivedData/XCTestWD-csksfttfbygcrbamoobfasiylmgb/Build/Products/Debug-iphoneos/XCTestWD.app/XCTestWD

* **Macaca Version**:
  ios: 2.0.24
* **Macaca Doctor Logs**:

* **Operate System**:
ios
* **Programming Language**:

**Comment by kidbear** [comment]
求修复

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/issues/88

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-doctor/commit/7de1599c0e5e73045cc52ac7cece7b8591326f60

**Comment by xudafeng** [comment]
https://github.com/macacajs/devicelog/issues/1

**Comment by grubby2013** [comment]
macaca-ios也无法安装？

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/139

**Comment by wxlsh114** [comment]
I met the same issue. Hope it can be fixed ASSP.

**Comment by jake20001** [comment]
解了没有啊

**Comment by xudafeng** [comment]
升级最新版macaca-ios

**Comment by wxlsh114** [comment]
already updated maraca-ios to v2.0.27, but still got the error message 'No such module 'Swifter'.
@xudafeng how to solve this problem?

**Comment by xilin** [comment]
@wxlsh114 try to run `carthage update`
