### ISSUE TITLE
自动化用例未执行，任务运行状态显示 pass

### ISSUE THREAD

**Issue by Ocean0227** [alibaba/macaca#707]
* **Macaca Version**:
 iwm@MacBook-Pro  ~  macaca -v
  2.0.6

* **Macaca Doctor Logs**:
iwm@MacBook-Pro  ~  macaca doctor

  macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.11.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/iwm/Downloads/android-sdk-macosx`
  Platforms is set to `/Users/iwm/Downloads/android-sdk-macosx/platforms/android-23`
  ADB tool is set to `/Users/iwm/Downloads/android-sdk-macosx/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  android: 2.0.36
  chrome: 1.0.6
  electron: 1.1.11
  ios: 2.0.23

* **Operate System**:
 iwm@MacBook-Pro  ~  uname -a
Darwin MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

* **Programming Language**:
java

***slave信息***
channel.js:34:20 [worker:1] pid:33862
---> zmq message
{"body":"https://github.com/Ocean0227/UIAuto4Macaca.git#master#,taskId:59c8ba5b997ea21800507bff,type:task,runiOS:true"}
Coming to processor...
channel.js:69:16 [worker:1] pid:33862
<--- zmq message
{ type: 'task',
taskId: '59c8ba5b997ea21800507bff',
sysInfo:
{ cpus:
[ { model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 13184630, nice: 0, sys: 13457990, idle: 133796490, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 4510840, nice: 0, sys: 3650390, idle: 152267460, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 11846810, nice: 0, sys: 10018990, idle: 138562930, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 4584800, nice: 0, sys: 3636000, idle: 152207840, irq: 0 } },
[length]: 4 ],
memory: 0.011448860168457031,
type: 'Darwin',
platform: 'darwin',
uptime: '5d 22h 55m',
release: '16.7.0',
hostname: 'bogon',
port: undefined },
status: 'busy',
body: '' }
flow.js:99:12 [worker:1] pid:33862 Task 59c8ba5b997ea21800507bff start git clone...
flow.js:116:12 [worker:1] pid:33862 Task 59c8ba5b997ea21800507bff start git clone success!
flow.js:127:14 [worker:1] pid:33862 Sending 59c8ba5b997ea21800507bff data ...
channel.js:69:16 [worker:1] pid:33862
<--- zmq message
{ type: 'task',
taskId: '59c8ba5b997ea21800507bff',
sysInfo:
{ cpus:
[ { model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 13184630, nice: 0, sys: 13457990, idle: 133796490, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 4510840, nice: 0, sys: 3650390, idle: 152267460, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 11846810, nice: 0, sys: 10018990, idle: 138562930, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 4584800, nice: 0, sys: 3636000, idle: 152207840, irq: 0 } },
[length]: 4 ],
memory: 0.011448860168457031,
type: 'Darwin',
platform: 'darwin',
uptime: '5d 22h 55m',
release: '16.7.0',
hostname: 'bogon',
port: undefined },
status: 'busy',
body: 'done! your test case exited with code \n\n' }
flow.js:72:12 [worker:1] pid:33862 Task is end with 59c8ba5b997ea21800507bff data...
channel.js:69:16 [worker:1] pid:33862
<--- zmq message
{ type: 'task',
taskId: '59c8ba5b997ea21800507bff',
sysInfo:
{ cpus:
[ { model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 13184630, nice: 0, sys: 13457990, idle: 133796490, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 4510840, nice: 0, sys: 3650390, idle: 152267460, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 11846810, nice: 0, sys: 10018990, idle: 138562930, irq: 0 } },
{ model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz',
speed: 2700,
times: { user: 4584800, nice: 0, sys: 3636000, idle: 152207840, irq: 0 } },
[length]: 4 ],
memory: 0.011448860168457031,
type: 'Darwin',
platform: 'darwin',
uptime: '5d 22h 55m',
release: '16.7.0',
hostname: 'bogon',
port: undefined },
status: 'available',
body: 'false',
bodyStatus: 2,
extra: {} }

***任务配置***
![image](https://user-images.githubusercontent.com/14172785/30852993-0f5d4cd4-a273-11e7-8e2c-e587088e5e20.png)

***任务状态***
![image](https://user-images.githubusercontent.com/14172785/30853067-510da0d4-a273-11e7-9924-66a9b8b97d95.png)

**Comment by xudafeng** [comment]
reliable问题暂不提供支持 @Ocean0227
