### ISSUE TITLE
执行脚本频繁抛出Error: read ECONNRESET

### ISSUE THREAD

**Issue by qwezxcjohnny** [alibaba/macaca#708]
* **Macaca Version**: 
mcaca-cli: 2.0.10
macaca android : 2.0.36
* **Operate System**: windows 10 64 位
* **Programming Language**: nodejs
手机： 安卓 7 华为荣耀9

macaca doctor: 
macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: D:\Program Files\nodejs\node.exe
  node version: v6.11.1

  Android checklist:

  JAVA version is `1.8.0_141`
  JAVA_HOME is set to `D:\Java\jdk1.8.0_141`
  ANDROID_HOME is set to `D:\Android\android-sdk`
  Platforms is set to `D:\Android\android-sdk\platforms\android-26`
  ADB tool is set to `D:\Android\android-sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\gradle-4.0.1`

  Installed driver list:

  android: 2.0.36

执行脚本频繁报Error: read ECONNRESET
log:
>> proxy.js:55:14 [master] pid:10888 Proxy: /wd/hub/session/a5d662d8-fe2c-45c0-b25d-e0244543606b/elements:POST to http://127.0.0.1:64043/wd/hub/session/a5d662d8-fe2c-45c0-b25d-e0244543606b/elements:POST with body: {"using":"id","value":"cmccwm.mobilemusic:id/img_setting"}
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:10888 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> responseHandler.js:56:12 [master] pid:10888 Send Error Respone to Client: Error: read ECONNRESET
>> responseHandler.js:62:14 [master] pid:10888 Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)

  Error: read ECONNRESET
      at exports._errnoException (util.js:1018:11)
      at TCP.onread (net.js:568:26)

麻烦帮忙看看，解惑，谢谢！

**Comment by qwezxcjohnny** [comment]
>> uiautomator-client.js:56:14 [master] pid:3340 INSTRUMENTATION_RESULT: shortMsg=Process crashed.

>> uiautomator-client.js:56:14 [master] pid:3340 INSTRUMENTATION_CODE: 0

>> 

>> proxy.js:63:22 [master] pid:3340 UIAutomatorWD client proxy error with: Error: socket hang up
>> proxy.js:63:22 [master] pid:3340 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:3340 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:3340 UIAutomatorWD client proxy error with: Error: read ECONNRESET
>> uiautomator-client.js:56:14 [master] pid:3340 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:56:14 [master] pid:3340 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:54742<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> proxy.js:63:22 [master] pid:3340 UIAutomatorWD client proxy error with: Error: read ECONNRESET

**Comment by feng317** [comment]
@遇到楼主同样的问题！@xudafeng请问解决了吗，升级到最新版本的macaca就这样了

**Comment by litingjun2015** [comment]
没有workaround吗？ 像会退到哪个稳定版？

**Comment by outtmanchen** [comment]
请问各位解决了嘛，现在我也遇到这个问题了， 真机录制好不容易起来一次，就一直报这个错误。。。。

**Comment by x3au** [comment]
Seeing the same issue, would be great to see a fix.

**Comment by zhujiliang** [comment]
请问 楼主解决了没有 我的也出现这问题了

**Comment by qwezxcjohnny** [comment]
@zhujiliang 没有 偶尔还会复现

**Comment by andrecnogueira-onefootball** [comment]
Are we fixing this issue? I've seen dozen of people complaining about it...

**Comment by wsYdd** [comment]
The same issue +1

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/929
