### ISSUE TITLE
使用 hasElementByXPath, waitForElementByXPath, elementByXPathOrNull 报错

### ISSUE THREAD

**Issue by zuiaibohe** [alibaba/macaca#720]
使用 hasElementByXPath, waitForElementByXPath, elementByXPathOrNull 方法，当页面的元素没有找到 by xpath，回报错，而不是继续等待、返回false、返回null
![image](https://user-images.githubusercontent.com/32834803/31604786-ef9f109c-b296-11e7-9223-5ec7d901a4a2.png)

* **Macaca Version**: 2.0.10

* **Macaca Doctor Logs**:
Node.js checklist
node version: v8.2.1

Android checklist

JAVA version is `1.8.0_144
JAVA_HOME is set...
ANDROID_HOME is set ...
Platforms is set..
ADB tool is set ....
GRADLE_HOME is set ...

Installed driver

android: 2.0.24 
chrome: 1.0.6

* **Operate System**:window 7 64bit

* **Programming Language**:node.js

**Comment by ZTinoZ** [comment]
遇到同样的问题 盼修复
