### ISSUE TITLE
Android H5 App: 无法切换Webview，提示：NoSuchDriver: no such session

### ISSUE THREAD

**Issue by wynanwong** [alibaba/macaca#721]
* **Macaca Version**: 
2.0.10

* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.6.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/wn/Library/Android/sdk`
  Platforms is set to `/Users/wn/Library/Android/sdk/platforms/android-25`
  ADB tool is set to `/Users/wn/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.6
  electron: 1.1.6 [out-of-date]
  ios: 2.0.27

* **Operate System**:
Mac 10.12.3

* **Programming Language**:
Java

app是纯H5的，手机内置的chrome版本是chrome=46.0.2490.76，而驱动版本是：chromedriver=2.20（这个试了从18到24的版本，都不行），官方的H5 demo是可以跑通的，所以应该不是chrome版本和chromedriver版本冲突的问题，下面附上server端的log:

>> index.js:18:12 [master] pid:96093 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '192.168.1.229',
  host: 'wndeMacBook-Pro.local',
  loaded_time: '2017-10-17 16:18:13' }
>> middlewares.js:17:10 [master] pid:96093 base middlewares attached
>> router.js:127:10 [master] pid:96093 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:96093 Recieve HTTP Request from Client[2017-10-17 16:18:20]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"/Users/wn/GitHome/superapp/src/app/xb-app-debug.apk","reuse":3,"platformName":"android","udid":"3fd1ee01","deviceName":"NEXUS"}}
>> session.js:47:10 [master] pid:96093 Creating session, sessionId: 7f68868f-4656-499b-8de7-6a3bf6cdcb7d.
>> helper.js:208:12 [master] pid:96093 Using local app form /Users/wn/GitHome/superapp/src/app/xb-app-debug.apk
>> uiautomator-client.js:56:14 [master] pid:96093 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:56:14 [master] pid:96093 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9007<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> macaca-android.js:294:10 [master] pid:96093 start app with: {"package":"com.cybertron.smarthome","activity":""}
>> responseHandler.js:49:14 [master] pid:96093 Send HTTP Respone to Client[2017-10-17 16:18:36]: {"sessionId":"7f68868f-4656-499b-8de7-6a3bf6cdcb7d","status":0,"value":"{\"app\":\"/Users/wn/GitHome/superapp/src/app/xb-app-debug.apk\",\"reuse\":3,\"platformName\":\"android\",\"udid\":\"3fd1ee01\",\"deviceName\":\"NEXUS\"}"}
>> responseHandler.js:11:12 [master] pid:96093 Recieve HTTP Request from Client[2017-10-17 16:18:36]: method: GET url: /wd/hub/session/7f68868f-4656-499b-8de7-6a3bf6cdcb7d/contexts, jsonBody: {}
>> No webview version found from adb shell!
>> use default chromedriver version!
>> starting chromedriver service!
>> chromedriver bin path: /usr/local/lib/node_modules/macaca-android/node_modules/.1.0.37@macaca-chromedriver/exec/chromedriver2.20
>> Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:51:14 [master] pid:96093 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body: 
>> proxy.js:57:16 [master] pid:96093 Got response with status 200: "{\"sessionId\":\"\",\"stat...
>> proxy.js:51:14 [master] pid:96093 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"ch...
>> proxy.js:57:16 [master] pid:96093 Got response with status 200: {"sessionId":"a1d7e02fdd245...
>> chromedriver ready with: {"sessionId":null,"status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.12.3 x86_64)"}}
>> proxy.js:51:14 [master] pid:96093 Proxy: /wd/hub/session/:sessionId/window_handles:GET to http://localhost:9515/wd/hub/session/a1d7e02fdd2458d19dd0ec8603bfdde7/window_handles:GET with body: {}
>> proxy.js:57:16 [master] pid:96093 Got response with status 200: {"sessionId":"a1d7e02fdd245...
>> responseHandler.js:56:12 [master] pid:96093 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.12.3 x86_64)
>> responseHandler.js:62:14 [master] pid:96093 NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.12.3 x86_64)
    at Object._.parseWebDriverResult (/usr/local/lib/node_modules/macaca-android/lib/helper.js:72:11)
    at Android.getWebviews (/usr/local/lib/node_modules/macaca-android/lib/macaca-android.js:327:16)
    at Android.getWebviews.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)
>> responseHandler.js:78:14 [master] pid:96093 Send Bad HTTP Respone to Client[2017-10-17 16:19:39]: {"sessionId":"7f68868f-4656-499b-8de7-6a3bf6cdcb7d","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.12.3 x86_64)"}}
>> responseHandler.js:11:12 [master] pid:96093 Recieve HTTP Request from Client[2017-10-17 16:19:39]: method: DELETE url: /wd/hub/session/7f68868f-4656-499b-8de7-6a3bf6cdcb7d, jsonBody: {}
>> session.js:80:12 [master] pid:96093 Delete session, sessionId: 7f68868f-4656-499b-8de7-6a3bf6cdcb7d
>> responseHandler.js:49:14 [master] pid:96093 Send HTTP Respone to Client[2017-10-17 16:19:39]: {"sessionId":"7f68868f-4656-499b-8de7-6a3bf6cdcb7d","status":0}
>> macaca-chromedriver.js:168:18 [master] pid:96093 chromedriver exit with code: null, signal: SIGTERM

**Comment by xudafeng** [comment]
chromedriver版本问题 看faq
