### ISSUE TITLE
TypeError: Cannot read property 'bounds' of undefined

### ISSUE THREAD

**Issue by wilischan** [alibaba/macaca#723]
* **Macaca Version**:
2.0.10
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.1.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/wilis/Library/Android/sdk`
  Platforms is set to `/Users/wilis/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/wilis/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.40
  ios: 2.0.27

* **Operate System**:
mac os

* **Programming Language**:
python

更新inspector后，inspector -u报错：
inspector -u BKFDU17418007099
>> UIAutomatorWD http server ready
>> Android device started: BKFDU17418007099
>> inspector start at: http://100.84.199.45:5678
  <-- GET /
>> Dump Android XML success, save to /usr/local/lib/node_modules/app-inspector/.temp/android.json

  TypeError: Cannot read property 'bounds' of undefined
      at adaptor (/usr/local/lib/node_modules/app-inspector/lib/android.js:28:13)
      at Object.exports.dumpXMLAndScreenShot (/usr/local/lib/node_modules/app-inspector/lib/android.js:49:14)
      at exports.dumpXMLAndScreenShot.next (<anonymous>)
      at onFulfilled (/usr/local/lib/node_modules/app-inspector/node_modules/co/index.js:65:19)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by qichuan** [comment]
@wilischan can you share the content of /usr/local/lib/node_modules/app-inspector/.temp/android.json

**Comment by wilischan** [comment]
@qichuan 
{"rotation":"0","class":"MacacaAppInspectorRoot","bounds":[0,0,1080,1812],"nodes":[{"index":"0","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1812,1080,108],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/rot0","class":"android.widget.RelativeLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1812,1080,108],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/no_expand_port","class":"android.widget.FrameLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1812,1080,108],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/deadzone","class":"android.view.View","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1812,1080,108]},{"index":"1","resource-id":"com.android.systemui:id/nav_buttons","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1812,1080,108],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/back","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"Back","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"true","password":"false","selected":"false","bounds":[210,1812,180,108]},{"index":"1","resource-id":"com.android.systemui:id/home","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"Home","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"true","password":"false","selected":"false","bounds":[450,1812,180,108]},{"index":"2","resource-id":"com.android.systemui:id/recent_apps","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"Recent apps","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"true","password":"false","selected":"false","bounds":[690,1812,180,108]},{"index":"3","class":"android.widget.FrameLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[930,1812,120,108]}]}]}]}]},{"index":"0","class":"android.widget.FrameLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,72],"nodes":[{"index":"1","resource-id":"com.android.systemui:id/status_bar","class":"android.widget.FrameLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,72],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/status_bar_contents","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,72],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/operator_name_container","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[18,11,339,49],"nodes":[{"index":"0","text":"Emergency calls only","resource-id":"com.android.systemui:id/msim_status_bar_operators_card_one_id","class":"android.widget.TextView","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[18,11,339,49]}]},{"index":"1","resource-id":"com.android.systemui:id/notification_icon_area","class":"android.widget.FrameLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[357,0,265,72],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/notification_icon_area_inner","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[357,0,265,72],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/notificationIcons","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[357,0,225,72],"nodes":[{"index":"0","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"Android System notification: USB debugging connected","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[362,19,36,36]},{"index":"1","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"Settings notification: USB connected (file transfer mode)","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[407,19,36,36]},{"index":"2","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"UC News notification: I will go back to Bigg Boss if Salman Khan apologises to me: Zubair Khan","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[452,19,36,36]},{"index":"3","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"BABE notification: Viral, Foto Istri Tua Ikut Duduk di Pelaminan Saat Suaminya Nikah Lagi","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[497,19,36,36]},{"index":"4","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"Dailyhunt notification: Ahead of Diwali, good news for Indian economy","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[542,19,36,36]}]},{"index":"1","resource-id":"com.android.systemui:id/moreIcon","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[587,7,35,58]}]}]},{"index":"2","resource-id":"com.android.systemui:id/system_icon_area","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[622,0,434,72],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/system_icons","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[622,0,278,72],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/statusIcons","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[622,0,33,72],"nodes":[{"index":"0","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"Bluetooth on.","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[622,0,33,72]}]},{"index":"2","resource-id":"com.android.systemui:id/signal_cluster","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[655,13,84,45],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/wifi_combo","class":"android.widget.FrameLayout","package":"com.android.systemui","content-desc":"Full Wi-Fi signal.","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[655,13,47,45],"nodes":[{"index":"2","resource-id":"com.android.systemui:id/wifi_signal","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[655,13,47,45]}]},{"index":"1","resource-id":"com.android.systemui:id/no_sims","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[702,13,37,45],"nodes":[{"index":"0","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"No SIM.","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[702,13,37,45]}]}]},{"index":"3","class":"android.widget.LinearLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[739,13,161,45],"nodes":[{"index":"1","text":"100%","resource-id":"com.android.systemui:id/battery_outside_percent","class":"android.widget.TextView","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[739,14,86,42]},{"index":"2","class":"android.widget.FrameLayout","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[825,13,75,45],"nodes":[{"index":"0","resource-id":"com.android.systemui:id/battery_border","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"100","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[825,13,75,45]},{"index":"1","resource-id":"com.android.systemui:id/battery_inside_charge_level","class":"android.widget.ImageView","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[825,13,75,45]}]}]}]},{"index":"1","text":"11:17 am","resource-id":"com.android.systemui:id/clock","class":"android.widget.TextView","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[900,0,156,72]}]}]}]},{"index":"2","resource-id":"com.android.systemui:id/scrim_behind","class":"android.view.View","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,72]},{"index":"3","resource-id":"com.android.systemui:id/scrim_in_front","class":"android.view.View","package":"com.android.systemui","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,72]}]},{"index":"0","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,1812],"nodes":[{"index":"0","class":"android.widget.LinearLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,1812],"nodes":[{"index":"0","resource-id":"android:id/content","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,1812],"nodes":[{"index":"0","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"true","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,1812],"nodes":[{"index":"0","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,1812],"nodes":[{"index":"0","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,1812],"nodes":[{"index":"0","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,1812],"nodes":[{"index":"0","class":"android.widget.RelativeLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,72,1080,1740]},{"index":"1","class":"android.view.ViewGroup","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,72,1080,1740],"nodes":[{"index":"0","class":"android.widget.RelativeLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,72,1080,132],"nodes":[{"NAF":"true","index":"0","resource-id":"com.uc.iflow:id/back_id","class":"android.widget.ImageButton","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"true","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,72,180,132]},{"index":"1","text":"Free Press Journal","resource-id":"com.uc.iflow:id/brand_title_icon","class":"android.widget.TextView","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[180,107,768,61]},{"index":"2","class":"android.widget.LinearLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[948,72,132,132],"nodes":[{"NAF":"true","index":"0","resource-id":"com.uc.iflow:id/page_menu_id","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[948,72,132,132],"nodes":[{"index":"0","class":"android.widget.ImageView","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[948,72,132,132]}]}]}]},{"index":"1","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,204,1080,1476],"nodes":[{"index":"0","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"true","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,204,1080,1476]}]},{"index":"2","class":"android.widget.LinearLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1662,1080,150],"nodes":[{"index":"0","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1668,1080,144],"nodes":[{"index":"0","class":"android.widget.LinearLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1668,1080,144],"nodes":[{"NAF":"true","index":"0","resource-id":"com.uc.iflow:id/ID_GOTO_EDIT_USER_INFO","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[30,1701,90,90],"nodes":[{"index":"0","class":"android.widget.RelativeLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[30,1701,90,90],"nodes":[{"index":"0","class":"android.widget.LinearLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[30,1701,90,90],"nodes":[{"index":"0","class":"android.view.View","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[30,1701,90,90]}]},{"index":"1","class":"android.widget.ImageView","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[102,1701,18,18]}]}]},{"index":"1","resource-id":"com.uc.iflow:id/ID_INPUT_COMMENT","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[150,1698,486,96],"nodes":[{"index":"0","text":"Let's talk about it !","class":"android.widget.TextView","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[180,1698,456,96]}]},{"index":"2","resource-id":"com.uc.iflow:id/ID_GOTO_COMMENT","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[666,1677,150,135],"nodes":[{"index":"0","class":"android.widget.RelativeLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[666,1677,150,135],"nodes":[{"index":"0","class":"android.widget.ImageView","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[693,1698,96,96]},{"index":"1","text":"6","class":"android.widget.TextView","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[736,1698,79,39]}]}]},{"index":"3","resource-id":"com.uc.iflow:id/ID_SHARE_MORE","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[816,1668,264,144],"nodes":[{"index":"0","class":"android.widget.LinearLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[816,1668,264,144],"nodes":[{"index":"0","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[816,1668,90,144],"nodes":[{"NAF":"true","index":"0","resource-id":"com.uc.iflow:id/ID_SHARE_MORE","class":"android.widget.ImageView","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[816,1668,90,144]}]},{"NAF":"true","index":"1","resource-id":"com.uc.iflow:id/ID_SHARE_TARGET","class":"android.widget.ImageView","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"true","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[936,1668,144,144]}]}]}]},{"index":"1","class":"android.view.View","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,1680,1080,132]}]}]}]}]}]}]},{"index":"1","class":"android.widget.FrameLayout","package":"com.uc.iflow","content-desc":"null","checkable":"false","checked":"false","clickable":"false","enabled":"true","focusable":"false","focused":"false","scrollable":"false","long-clickable":"false","password":"false","selected":"false","bounds":[0,0,1080,1812]}]}]}]}]}]}
