### ISSUE TITLE
PC录制脚本，执行脚本时提示missing script: paralleltest，按官方文档升级nodejs版本仍不行

### ISSUE THREAD

**Issue by bingjiesan** [alibaba/macaca#726]
* **Macaca Version**:2.0.10

* **Macaca Doctor Logs**:
  Node.js checklist:

  node env: /data01/QA/node-v8.7.0-linux-x64/bin/node
  node version: v8.7.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/usr/java/jdk1.8.0_101`
  ANDROID_HOME is set to `/data01/android-sdk-linux`
  Platforms is set to `/data01/android-sdk-linux/platforms/android-9`
  ADB tool is set to `/data01/android-sdk-linux/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  electron: 1.1.11

* **Operate System**:centos 7.0

* **Programming Language**:js

**Comment by yaniswang** [comment]
你执行这条命令所在的文件夹里有package.json文件吗？

把这个文件的内容复制到这里
