### ISSUE TITLE
Mac运行macaca-mobile-sample.test.js错误

### ISSUE THREAD

**Issue by firekyrin** [alibaba/macaca#73]
* **Macaca Version**:1.0.35

* **Macaca Doctor**:
Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.2.2

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is not set
  ANDROID_HOME is not set

  Installed driver list:

  ios: 1.0.30

* **Platform**:
Darwin haizitong3deiMac.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

haizitong3deiMac:macaca-test-sample haizitong3$ macaca run -d macaca-test/macaca-mobile-sample.test.js 
>> port: 3456 was occupied, changed port: 3457
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

>> 
>>     1) "before all" hook

>> 
>>     2) "after all" hook

>> 

>>   0 passing (2m)

>>   2 failing

>> 

>>   1) macaca mobile sample "before all" hook:
     [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"/Users/haizitong3/Documents/workspace/test/macaca-test-sample/app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
  Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:905:12)

>>   2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at null.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:905:12)

>> Test completed!

**Comment by sencho** [comment]
macaca install ios

**Comment by xudafeng** [comment]
@firekyrin 也可以用 npm i macaca-ios -g

**Comment by irrigator** [comment]
安装了ios driver并没有解决问题

macaca doctor

  macaca-doctor version: 1.0.28


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.7.4

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.8.0_112`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zjy/Library/Android/sdk`
  Platforms is set to `/Users/zjy/Library/Android/sdk/platforms/android-23`
  Android tools is set to `/Users/zjy/Library/Android/sdk/tools/android`
  ADB tool is set to `/Users/zjy/Library/Android/sdk/platform-tools/adb`

  Installed driver list:

  ios: 1.0.62


platform=ios macaca run --verbose -d ./macaca-test/mobile-app-sample.test.js
>> index.js:17:12 [master] pid:27264 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '192.168.5.107',
  host: 'JunyudeMacBook-Air.local',
  loaded_time: '2017-03-29 16:18:14' }
>> middlewares.js:17:10 [master] pid:27264 base middlewares attached
>> router.js:127:10 [master] pid:27264 router set
>> webdriver sdk launched
[ '/Users/zjy/Code/play/sample-nodejs/node_modules/.bin/mocha',
  './macaca-test/mobile-app-sample.test.js',
  '--colors',
  '--verbose' ]
>>

>>

>> (node:27266) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:27264 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"deviceName":"iPhone 5s","platformName":"iOS","autoAcceptAlerts":false,"app":"/Users/zjy/Code/play/sample-nodejs/node_modules/ios-app-bootstrap/build/ios-app-bootstrap.zip"}}
>> session.js:47:10 [master] pid:27264 Creating session, sessionId: d32521c8-11fc-4bae-94c4-74223e3a0095.
ios-deploy
>> helper.js:194:12 [master] pid:27264 Unzipping local app form /Users/zjy/Code/play/sample-nodejs/node_modules/ios-app-bootstrap/build/ios-app-bootstrap.zip
>> macaca-ios.js:207:10 [master] pid:27264 Get available devices [{"name":"iPhone 5","udid":"6DDE57A4-1CA3-48F4-96A6-CCEAF403D1A7","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 5s","udid":"3E5F3580-23DF-4966-BEF5-3ABB30E71B6B","state":"Booted","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 6","udid":"17BD5C65-3592-4C74-B0B4-4FAD489535D0","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 6 Plus","udid":"3A24C192-19F6-43B1-9592-F4C3DFD989F5","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 6s","udid":"0E076E8B-42A7-40D4-A281-8C3562CD94FD","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 6s Plus","udid":"12A44B0D-1FFD-450A-9D49-0373CB8FCBDF","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 7","udid":"18954E65-9693-4236-ABAD-35D1AD7AF5AD","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone 7 Plus","udid":"9A6EC5EA-53B9-4F82-9DC1-B5BDE95D4C59","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPhone SE","udid":"0C20A39D-23DA-4DA9-847B-3FA373D52543","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPad Air","udid":"D2B5368D-2F00-49F1-A449-59BFC84951E4","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"iPad Air 2","udid":"15D348EA-4C05-4EFC-95F1-952A44F0AEED","state":"Shutdown","available":true,"runtime":"iOS 10.3"},{"name":"Apple TV 1080p","udid":"79576E8D-6A9C-48E5-BE1A-5022F5AF3706","state":"Shutdown","available":true,"runtime":"tvOS 10.2"},{"name":"Apple Watch - 38mm","udid":"A9478F18-F26E-4763-8E08-C6DAF857F4A6","state":"Shutdown","available":true,"runtime":"watchOS 3.2"},{"name":"Apple Watch - 42mm","udid":"FDDCB58E-E69D-4D2D-9203-450308F5EF0E","state":"Shutdown","available":true,"runtime":"watchOS 3.2"},{"name":"Apple Watch Series 2 - 38mm","udid":"6596DD1D-3756-4C65-AD81-A1866D5CA524","state":"Shutdown","available":true,"runtime":"watchOS 3.2"},{"name":"Apple Watch Series 2 - 42mm","udid":"BBB53B92-136E-49FB-844E-E374E426B079","state":"Shutdown","available":true,"runtime":"watchOS 3.2"}]
CFBundleIdentifier is xudafeng.ios-app-bootstrap
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/q7/6fmkzcw15js74pqy5sgcbx6w0000gn/T/ios-app-bootstrap.app/Info.plist
>> xctest-client.js:56:14 [master] pid:27264 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:150:10 [master] pid:27264 {
	"bundleId": "xudafeng.ios-app-bootstrap",
	"platformName": "iOS",
	"app": "/var/folders/q7/6fmkzcw15js74pqy5sgcbx6w0000gn/T/ios-app-bootstrap.app/"
}
>> macaca-ios.js:154:12 [master] pid:27264 Trying to start wda server...
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:27264 xcode version: 8.3
>> WebDriverAgent version: 1.0.44
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:22.802 xcodebuild[27280:387253]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/A6353D2A-1BDC-4286-9202-BEFE9D013181/Session-WebDriverAgentRunner-2017-03-29_161822-3ycKoC.log

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:22.807 xcodebuild[27280:387213] [MT] IDETestOperationsObserverDebug: (45C4959A-1CE8-4420-896D-5B510B0EB4D7) Beginning test session WebDriverAgentRunner-45C4959A-1CE8-4420-896D-5B510B0EB4D7 at 2017-03-29 16:18:22.805 with Xcode 8E162 on target <DVTiPhoneSimulator: 0x7f982c82a480> {
		SimDevice: SimDevice : iPhone 5s (3E5F3580-23DF-4966-BEF5-3ABB30E71B6B) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:27.088 xcodebuild[27280:387213] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/A6353D2A-1BDC-4286-9202-BEFE9D013181/Session-WebDriverAgentRunner-2017-03-29_161822-3ycKoC.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/A6353D2A-1BDC-4286-9202-BEFE9D013181/Session-WebDriverAgentRunner-2017-03-29_161822-3ycKoC.log}

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:27.090 xcodebuild[27280:387433] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f9829dd7cc0>

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264
Testing failed:

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 	'XCUISiriService' is partial: introduced in iOS 10.3
	Could not build module 'XCTest'
** TEST FAILED **


The following build commands failed:
	CompileC /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Intermediates/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/FBXPathCreator.o WebDriverAgentLib/Utilities/FBXPathCreator.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:265:14 [master] pid:27264 killing deviceLogProc pid: 27279
>> xctest-client.js:270:14 [master] pid:27264 killing runnerProc pid: 27280
>> xctest-client.js:181:14 [master] pid:27264 xctest client exit with code: 65, signal: null
>> xctest-client.js:107:16 [master] pid:27264 simulator log process exit with code: null, signal: SIGKILL
>> xctest-client.js:257:14 [master] pid:27264 Fail to start xctest: undefined
>> macaca-ios.js:154:12 [master] pid:27264 Trying to start wda server...
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:27264 xcode version: 8.3
>> WebDriverAgent version: 1.0.44
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:38.709 xcodebuild[27316:387580]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/6AABA70B-4241-4236-A3F3-657C42B82E30/Session-WebDriverAgentRunner-2017-03-29_161838-NzwS9v.log

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:38.710 xcodebuild[27316:387574] [MT] IDETestOperationsObserverDebug: (D9785F78-556F-4D51-B24F-C9B05CAC9778) Beginning test session WebDriverAgentRunner-D9785F78-556F-4D51-B24F-C9B05CAC9778 at 2017-03-29 16:18:38.710 with Xcode 8E162 on target <DVTiPhoneSimulator: 0x7fa8555d1cf0> {
		SimDevice: SimDevice : iPhone 5s (3E5F3580-23DF-4966-BEF5-3ABB30E71B6B) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:41.372 xcodebuild[27316:387574] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/6AABA70B-4241-4236-A3F3-657C42B82E30/Session-WebDriverAgentRunner-2017-03-29_161838-NzwS9v.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/6AABA70B-4241-4236-A3F3-657C42B82E30/Session-WebDriverAgentRunner-2017-03-29_161838-NzwS9v.log}

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264
Testing failed:
	'XCUISiriService' is partial: introduced in iOS 10.3
	Could not build module 'XCTest'
** TEST FAILED **


The following build commands failed:
	CompileC /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Intermediates/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/FBScreenshotCommands.o WebDriverAgentLib/Commands/FBScreenshotCommands.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:265:14 [master] pid:27264 killing deviceLogProc pid: 27315
>> xctest-client.js:270:14 [master] pid:27264 killing runnerProc pid: 27316
>> xctest-client.js:181:14 [master] pid:27264 xctest client exit with code: 65, signal: null
>> xctest-client.js:107:16 [master] pid:27264 simulator log process exit with code: null, signal: SIGKILL
>> xctest-client.js:257:14 [master] pid:27264 Fail to start xctest: undefined
>> macaca-ios.js:154:12 [master] pid:27264 Trying to start wda server...
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:27264 xcode version: 8.3
>> WebDriverAgent version: 1.0.44
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:52.588 xcodebuild[27349:387802]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/0BE0A4BB-A1D5-4E44-B264-0B28BB063605/Session-WebDriverAgentRunner-2017-03-29_161852-l8RAaW.log

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:52.588 xcodebuild[27349:387789] [MT] IDETestOperationsObserverDebug: (6152796E-A21D-40EB-B98D-4297EB96FC14) Beginning test session WebDriverAgentRunner-6152796E-A21D-40EB-B98D-4297EB96FC14 at 2017-03-29 16:18:52.588 with Xcode 8E162 on target <DVTiPhoneSimulator: 0x7fcc0d7b9ec0> {
		SimDevice: SimDevice : iPhone 5s (3E5F3580-23DF-4966-BEF5-3ABB30E71B6B) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:18:55.106 xcodebuild[27349:387789] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/0BE0A4BB-A1D5-4E44-B264-0B28BB063605/Session-WebDriverAgentRunner-2017-03-29_161852-l8RAaW.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/0BE0A4BB-A1D5-4E44-B264-0B28BB063605/Session-WebDriverAgentRunner-2017-03-29_161852-l8RAaW.log}

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264
Testing failed:
	'XCUISiriService' is partial: introduced in iOS 10.3
	Could not build module 'XCTest'
** TEST FAILED **


The following build commands failed:
	CompileC /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Intermediates/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/FBXPathCreator.o WebDriverAgentLib/Utilities/FBXPathCreator.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:265:14 [master] pid:27264 killing deviceLogProc pid: 27348
>> xctest-client.js:270:14 [master] pid:27264 killing runnerProc pid: 27349
>> xctest-client.js:181:14 [master] pid:27264 xctest client exit with code: 65, signal: null
>> xctest-client.js:107:16 [master] pid:27264 simulator log process exit with code: null, signal: SIGKILL
>> xctest-client.js:257:14 [master] pid:27264 Fail to start xctest: undefined
>> macaca-ios.js:154:12 [master] pid:27264 Trying to start wda server...
>> xctest-client start with port: 8900
>> xctest-client.js:233:14 [master] pid:27264 xcode version: 8.3
>> WebDriverAgent version: 1.0.44
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:19:06.534 xcodebuild[27384:388052]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/353905AA-1A1F-4754-982E-2D4E5146CE97/Session-WebDriverAgentRunner-2017-03-29_161906-SJL6lM.log

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:19:06.535 xcodebuild[27384:388044] [MT] IDETestOperationsObserverDebug: (0A2A5579-1540-4472-A4DC-8A08CF8DDE73) Beginning test session WebDriverAgentRunner-0A2A5579-1540-4472-A4DC-8A08CF8DDE73 at 2017-03-29 16:19:06.535 with Xcode 8E162 on target <DVTiPhoneSimulator: 0x7fdee6cf6f90> {
		SimDevice: SimDevice : iPhone 5s (3E5F3580-23DF-4966-BEF5-3ABB30E71B6B) : state={ Booted } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-5s } runtime={ SimRuntime : 10.3 (14E269) - com.apple.CoreSimulator.SimRuntime.iOS-10-3 }
} (10.3 (14E269))

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264 2017-03-29 16:19:08.881 xcodebuild[27384:388044] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/353905AA-1A1F-4754-982E-2D4E5146CE97/Session-WebDriverAgentRunner-2017-03-29_161906-SJL6lM.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Logs/Test/353905AA-1A1F-4754-982E-2D4E5146CE97/Session-WebDriverAgentRunner-2017-03-29_161906-SJL6lM.log}

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:170:14 [master] pid:27264
Testing failed:
	'XCUISiriService' is partial: introduced in iOS 10.3
	Could not build module 'XCTest'
** TEST FAILED **


The following build commands failed:
	CompileC /Users/zjy/Library/Developer/Xcode/DerivedData/WebDriverAgent-earnspoghlsscjbxlmzvvcsmvulx/Build/Intermediates/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/x86_64/FBScreenshotCommands.o WebDriverAgentLib/Commands/FBScreenshotCommands.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

>> xctest-client.js:171:14 [master] pid:27264 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> xctest-client.js:265:14 [master] pid:27264 killing deviceLogProc pid: 27383
>> xctest-client.js:270:14 [master] pid:27264 killing runnerProc pid: 27384
>> xctest-client.js:181:14 [master] pid:27264 xctest client exit with code: 65, signal: null
>> xctest-client.js:107:16 [master] pid:27264 simulator log process exit with code: null, signal: SIGKILL
>> xctest-client.js:257:14 [master] pid:27264 Fail to start xctest: undefined
>> responseHandler.js:54:12 [master] pid:27264 Send Error Respone to Client: undefined

  InternalServerError: Internal Server Error
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:57:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:109:7)

>>     1) "before all" hook

>> responseHandler.js:11:12 [master] pid:27264 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
>> responseHandler.js:23:14 [master] pid:27264 Send HTTP Respone to Client: 405 Method Not Allowed
>>     2) "after all" hook


>>

>>   0 passing (55s)
  2 failing


>>   1) macaca mobile sample "before all" hook:
     Error: [init({"deviceName":"iPhone 5s","platformName":"iOS","autoAcceptAlerts":false,"app":"/Users/zjy/Code/play/sample-nodejs/node_modules/ios-app-bootstrap/build/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
      at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  2) macaca mobile sample "after all" hook:
     Error: [quit()] Unexpected data in simpleCallback.
      at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at PromiseWebdriver.<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
      at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
      at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)




>> Test completed!
make: *** [test-ios] Error 2
