### ISSUE TITLE
hasElementByXPath or elementByXPathIfExists or elementByTagNameOrNull当元素不存在时直接抛异常

### ISSUE THREAD

**Issue by lijingle1** [alibaba/macaca#733]
* **Macaca Version**:
  version 2.0.10 is outdate        
  run: npm i -g macaca-cli@2.0.12  
* **Macaca Doctor Logs**:
More information: https://macacajs.github.io/changelog.html

  macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /Users/lijingle/.nvm/versions/node/v8.4.0/bin/node
  node version: v8.4.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
{ Error: Command failed: xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'xcodebuild -version' }
  Xcode is uninstalled
{ Error: Command failed: which iproxy

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5) killed: false, code: 1, signal: null, cmd: 'which iproxy' }
  Command Line Tools: iproxy[usbmuxd] is uninstalled
  Command Line Tools: ios_webkit_debug_proxy is uninstalled
  carthage is uninstalled

  Android checklist:

  JAVA version is `1.8.0_111`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/lijingle/Library/Android/sdk`
  Platforms is set to `/Users/lijingle/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/lijingle/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  android: 2.0.40

* **Operate System**:
mac

* **Programming Language**:
nodejs

我用macaca nodejs版写android test case， 问下driver.hasElementByXPath(ele1)或driver.elementByXPathIfExists或elementByTagNameOrNull， 如果ele1这个xpath在当前native界面不存在，我这里直接就抛异常"UnknownError - An unknown server-side error occurred while processing the command."

期望是不抛异常，hasElementByXPath能够在then()中有回调值，elementByXPathIfExists返回的object如接口文档所约定

**Comment by alwaysonlinetxm** [comment]
遇到同样的bug，直接导致case failed了。期望官方早日修复！

**Comment by Chan-Chun** [comment]
相关[Bug](https://github.com/alibaba/macaca/issues/720)

**Comment by adcros** [comment]
请问该bug何时解？

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/720

**Comment by xudafeng** [comment]
https://github.com/macacajs/UIAutomatorWD/commit/e4e1cae2f183c04e39cc5a53eb80c5d5fd6bb16a

https://github.com/macacajs/macaca-android/commit/9ec2226f146703c23c6234ae6c7b908c0db06c3e

fixed
