### ISSUE TITLE
在执行安卓用例的时候，自定义执行adb shell命令会导致UIAutomatorWD报错

### ISSUE THREAD

**Issue by Yinxl** [alibaba/macaca#735]
* **Macaca Version**:

* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.10.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 8.3.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.24.0

  Android checklist:

  JAVA version is `1.8.0_101`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yxl/Library/Android/sdk`
  Platforms is set to `/Users/yxl/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/yxl/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.7
  electron: 1.1.6
  ios: 2.0.22

* **Operate System**:
Mac

* **Programming Language**:
wd.java

报错日志如下：
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:16660 Recieve HTTP Request from Client[2017-11-01 14:24:47]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"reuse":2,"package":"com.antfortune.wealth","activity":"com.alipay.mobile.quinox.LauncherActivity","udid":"562fc4b3","platformName":"Android","autoAcceptAlerts":true}}
>> session.js:47:10 [master] pid:16660 Creating session, sessionId: 42f44353-9f87-4c83-90c9-19e9be30a8e8.
>> uiautomator-client.js:61:14 [master] pid:16660 INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.macaca.android.testing.UIAutomatorWD:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=MacacaTestRunner
INSTRUMENTATION_STATUS: class=com.macaca.android.testing.UIAutomatorWD
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1

>> uiautomator-client.js:61:14 [master] pid:16660 INSTRUMENTATION_STATUS: stream=
UIAutomatorWD->http://localhost:9001<-UIAutomatorWD
INSTRUMENTATION_STATUS_CODE: 0

>> UIAutomatorWD http server ready
>> macaca-android.js:294:10 [master] pid:16660 start app with: {"package":"com.antfortune.wealth","activity":"com.alipay.mobile.quinox.LauncherActivity"}
>> responseHandler.js:49:14 [master] pid:16660 Send HTTP Respone to Client[2017-11-01 14:25:20]: {"sessionId":"42f44353-9f87-4c83-90c9-19e9be30a8e8","status":0,"value":"{\"reuse\":2,\"package\":\"com.antfortune.wealth\",\"activity\":\"com.alipay.mobile.quinox.LauncherActivity\",\"udid\":\"562fc4b3\",\"platformName\":\"Android\",\"autoAcceptAlerts\":true}"}
>> responseHandler.js:11:12 [master] pid:16660 Recieve HTTP Request from Client[2017-11-01 14:25:20]: method: POST url: /wd/hub/session/42f44353-9f87-4c83-90c9-19e9be30a8e8/elements, jsonBody: {"using":"id","value":"com.antfortune.wealth.home:id/btn_action_night"}
>> uiautomator-client.js:88:12 [master] pid:16660 get pids of com.macaca.android.testing failed, ignore this log
>> proxy.js:55:14 [master] pid:16660 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9001/wd/hub/session/:sessionId/accept_alert:POST with body: {}
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> proxy.js:63:22 [master] pid:16660 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
>> responseHandler.js:56:12 [master] pid:16660 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:9001
>> responseHandler.js:62:14 [master] pid:16660 Error: connect ECONNREFUSED 127.0.0.1:9001
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

  Error: connect ECONNREFUSED 127.0.0.1:9001
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

脚本中执行adb脚本方法如下：
``` java
 public static List<String> exec2(String cmd) {
        ResultGenerator.customLog("执行adb命令", cmd);
        Runtime run = Runtime.getRuntime();//返回与当前 Java 应用程序相关的运行时对象
        List<String> lines = new ArrayList<String>();
        try {
            Process p = run.exec(cmd);// 启动另一个进程来执行命令
            BufferedInputStream in = new BufferedInputStream(p.getInputStream());
            BufferedReader inBr = new BufferedReader(new InputStreamReader(in));
            String line;
            while ((line = inBr.readLine()) != null) {
                lines.add(line);
            }
            inBr.close();
            in.close();
        } catch (Exception e) {
            ResultGenerator.customLog("命令执行异常", e.getMessage());
        }
        return lines;
    }
```

复现场景：
在driver启动之后，执行
exec("adb -s 562fc4b3 shell ./data/local/tmp/client_performance.sh")
就会导致如上报错(sh脚本是安卓设备上用于性能采集的脚本)；
之前遇到过如下两种使用也会导致同样的问题
exec("adb -s 562fc4b3 shell input text 'text'") 
exec("adb -s 562fc4b3 shell shell am start -d "targetSchema" ")

猜测是本地执行的adb命令占用了UIAutomatorWD端口导致，但不知具体原因以及解决方案，辛苦大神们解决下

**Comment by ztwo** [comment]
adb路径不统一，打印一下exec执行adb调用的adb路径

**Comment by Yinxl** [comment]
多谢指教，问题已解决，通过将exec中的adb 替换为 ${ANDROID_HOME}/platform-tools/adb 可以解决

**Comment by mijiawei** [comment]
请教一下exec中的adb怎么查看？
@ztwo
