### ISSUE TITLE
请教：macaca在软件开发火车模型发布模式的应用

### ISSUE THREAD

**Issue by litingjun2015** [alibaba/macaca#737]
各位同仁，

我们团队刚上手 macaca，这里有些问题向各位先行者们请教：
1. 有没有推荐好的快速上手资料（我们运行环境已经部署好了，使用过程中避免哪些坑，像如何组织测试脚本，目录结构——把所有用例安排在一个脚本里应该不合适吧）
2. 关于持续集成部分文档资料很少，不知谁可以帮忙提供？
3. 关于用例设计，基本流，备选流等有没有好的macaca配套集成工具？ 还是直接用word？
4. 我们团队用的是互联网公司常用的火车模型发布模式，如果有团队愿意分享Macaca在软件开发火车模型发布模式的应用，样本工程那更好了

谢谢

**Comment by lihuazhang** [comment]
你问的问题和某一个特定技术无关了。

第一个问题，经验值。一般来说，数据和用例分离，用例和执行分离，执行和结果分离。

第二个问题，资料不少，Google下。testerhome社区也有不少。

第三个问题，不明白啥意思。

第四个问题，macaca应该和开发模式无关。我倾向于做主流程的冒烟测试。

**Comment by litingjun2015** [comment]
@lihuazhang 非常感谢！ 

第三个问题，我是想了解下产品设计，进行用例设计时，一般用什么工具来描述基本流，是用word吗？

**Comment by litingjun2015** [comment]
关于测试用例如何组织，是不是可以参考开源软件像 gcc 的测试
https://gcc.gnu.org/testing/

**Comment by litingjun2015** [comment]
按照“数据和用例分离，用例和执行分离，执行和结果分离。”的原则，目录组织是否可以这样：

```
D:.
├─commons
├─conf                         测试数据
├─output                       测试结果
└─scripts                      测试用例
    ├─purpose1/testcase1.js
    ├         /testcase2.js
    ├         ...
    └─purpose2/testcase1.js
    index.js                    执行入口 
```

**Comment by litingjun2015** [comment]
看到这篇很不错 https://testerhome.com/topics/7550
