### ISSUE TITLE
运行macaca官方例子出错，求帮助

### ISSUE THREAD

**Issue by dippac** [alibaba/macaca#74]
**下面是全部的log ，具体原因不清楚，已经找不到方向了。。。。**

> >> index.js:17:12 [master] pid:13580 webdriver server start with config:  { port: 3456,   window: true,   ip: '192.168.0.22',   host:
> 'mingodeMac-mini-5.local',   loaded_time: '2016-06-23 17:30:19' }
> >> middlewares.js:17:10 [master] pid:13580 base middlewares attached
> >> router.js:105:10 [master] pid:13580 router set
> >> webdriver sdk launched
> >> 
> 
> >> 
> 
> >>   macaca desktop sample
> 
> >> responseHandler.js:11:12 [master] pid:13580 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody:
> {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"/Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip"}}
> >> session.js:47:10 [master] pid:13580 Creating session, sessionId: 1e2c2bb8-e9de-40b6-bae5-4f88fb9ad722.
> >> session.js:39:14 [master] pid:13580 Error: Cannot find module 'macaca-ios'
>     at Function.Module._resolveFilename (module.js:440:15)
>     at Function.Module._load (module.js:388:25)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at detectDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:36:20)
>     at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:10:18)
>     at next (native)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> >> please run: `macaca install ios`
> >> helper.js:194:12 [master] pid:13580 Unzipping local app form /Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip
> >> responseHandler.js:50:12 [master] pid:13580 Send Error Respone to Client: TypeError: Cannot set property 'proxyMode' of undefined
> >> responseHandler.js:56:14 [master] pid:13580 TypeError: Cannot set property 'proxyMode' of undefined
>     at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:16:20)
>     at next (native)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
>     at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
>     at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> 
>   TypeError: Cannot set property 'proxyMode' of undefined
>       at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:16:20)
>       at next (native)
>       at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>       at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>       at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
>       at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
>       at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
>       at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
>       at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>       at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> 
> >> 
> >>     1) "before all" hook
> 
> >> responseHandler.js:11:12 [master] pid:13580 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> >> responseHandler.js:19:14 [master] pid:13580 Send HTTP Respone to Client: 405 Method Not Allowed
> >> 
> >>     2) "after all" hook
> 
> >> 
> 
> >>   macaca mobile sample
> 
> >> responseHandler.js:11:12 [master] pid:13580 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody:
> {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"/Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip"}}
> >> session.js:47:10 [master] pid:13580 Creating session, sessionId: 82e8d55e-cbb6-41b2-832f-85756bb5e45a.
> >> session.js:39:14 [master] pid:13580 Error: Cannot find module 'macaca-ios'
>     at Function.Module._resolveFilename (module.js:440:15)
>     at Function.Module._load (module.js:388:25)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at detectDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:36:20)
>     at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:10:18)
>     at next (native)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> >> please run: `macaca install ios`
> >> helper.js:194:12 [master] pid:13580 Unzipping local app form /Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip
> >> responseHandler.js:50:12 [master] pid:13580 Send Error Respone to Client: TypeError: Cannot set property 'proxyMode' of undefined
> >> responseHandler.js:56:14 [master] pid:13580 TypeError: Cannot set property 'proxyMode' of undefined
>     at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:16:20)
>     at next (native)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
>     at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
>     at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> 
>   TypeError: Cannot set property 'proxyMode' of undefined
>       at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:16:20)
>       at next (native)
>       at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>       at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>       at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
>       at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
>       at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
>       at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
>       at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>       at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> 
> >> 
> >>     3) "before all" hook
> 
> >> responseHandler.js:11:12 [master] pid:13580 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> >> responseHandler.js:19:14 [master] pid:13580 Send HTTP Respone to Client: 405 Method Not Allowed
> >> 
> >>     4) "after all" hook
> 
> 
> >>   macaca mobile sample
> 
> >> responseHandler.js:11:12 [master] pid:13580 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody:
> {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"/Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip"}}
> >> session.js:47:10 [master] pid:13580 Creating session, sessionId: d51ba8f6-8d58-4872-8d7d-07c341dc7f79.
> >> session.js:39:14 [master] pid:13580 Error: Cannot find module 'macaca-ios'
>     at Function.Module._resolveFilename (module.js:440:15)
>     at Function.Module._load (module.js:388:25)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at detectDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:36:20)
>     at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:10:18)
>     at next (native)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> >> please run: `macaca install ios`
> >> helper.js:194:12 [master] pid:13580 Unzipping local app form /Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip
> >> responseHandler.js:50:12 [master] pid:13580 Send Error Respone to Client: TypeError: Cannot set property 'proxyMode' of undefined
> >> responseHandler.js:56:14 [master] pid:13580 TypeError: Cannot set property 'proxyMode' of undefined
>     at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:16:20)
>     at next (native)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
>     at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
>     at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
>     at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
>     at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>     at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> 
>   TypeError: Cannot set property 'proxyMode' of undefined
>       at Object.createDevice (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/controllers/session.js:16:20)
>       at next (native)
>       at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
>       at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>       at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
>       at Object.toPromise (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:118:63)
>       at next (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:99:29)
>       at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:69:7)
>       at /usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:54:5
>       at Object.co (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:50:10)
> 
>     5) "before all" hook
> 
> >> responseHandler.js:11:12 [master] pid:13580 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> >> responseHandler.js:19:14 [master] pid:13580 Send HTTP Respone to Client: 405 Method Not Allowed
> >> 
> >>     6) "after all" hook
> 
> 
> >> 
> 
> >>   0 passing (4s)
> 
> >>   6 failing
> 
> 
> >>   1) macaca desktop sample "before all" hook:
>      [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"/Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip"})]
> The environment you requested was unavailable.   Error:
> [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"app/ios-app-bootstrap.zip"})] The environment you requested
> was unavailable.
>       at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
>       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
>       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
>       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
>       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
>       at endReadableNT (_stream_readable.js:934:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
> 
> >>   2) macaca desktop sample "after all" hook:
>      Error: [quit()] Unexpected data in simpleCallback.
>       at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
>       at .<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
>       at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
>       at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
>       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
>       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
>       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
>       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
>       at endReadableNT (_stream_readable.js:934:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
> 
> >>   3) macaca mobile sample "before all" hook:
>      [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"/Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip"})]
> The environment you requested was unavailable.   Error:
> [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"app/ios-app-bootstrap.zip"})] The environment you requested
> was unavailable.
>       at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
>       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
>       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
>       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
>       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
>       at endReadableNT (_stream_readable.js:934:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
>   4) macaca mobile sample "after all" hook:
>      Error: [quit()] Unexpected data in simpleCallback.
>       at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
>       at .<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
>       at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
>       at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
>       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
>       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
>       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
>       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
>       at endReadableNT (_stream_readable.js:934:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
> 
> >>   5) macaca mobile sample "before all" hook:
>      [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"/Users/mingo/Desktop/macaca-test-sample-master/app/ios-app-bootstrap.zip"})]
> The environment you requested was unavailable.   Error:
> [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone
> 5s","app":"app/ios-app-bootstrap.zip"})] The environment you requested
> was unavailable.
>       at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
>       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
>       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
>       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
>       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
>       at endReadableNT (_stream_readable.js:934:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
>   6) macaca mobile sample "after all" hook:
>      Error: [quit()] Unexpected data in simpleCallback.
>       at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
>       at .<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
>       at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
>       at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
>       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
>       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
>       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
>       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
>       at endReadableNT (_stream_readable.js:934:12)
>       at _combinedTickCallback (internal/process/next_tick.js:74:11)
>       at process._tickCallback (internal/process/next_tick.js:98:9)
> 
> 
> 
> 
> >> Test completed!

**Comment by xudafeng** [comment]
@dippac 你运行了什么命令？
