### ISSUE TITLE
Xcode 9.1 编译XCTestWD失败

### ISSUE THREAD

**Issue by WilliamStark** [alibaba/macaca#741]
* **Macaca Version**:2.0.28

* **Macaca Doctor Logs**:
macaca-doctor version: 1.0.28

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.9.5

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2347.
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yxtester/AndroidSDK`
  Android SDK Platforms directory is not exist, please install the whole thing

  Installed driver list:

  electron: 1.1.17
  ios: 2.0.28

* **Operate System**:macOS 10.12.6

* **Programming Language**:JAVA

失败截图如下：
![image](https://user-images.githubusercontent.com/6532570/32309219-12f7fcca-bf58-11e7-8f0d-43fbce364e82.png)

**Comment by shizu2014** [comment]
我也遇到个这个问题~~~

**Comment by xudafeng** [comment]
升级macaca-ios到2.0.29及以上

**Comment by shanglongmin** [comment]
@xudafeng ,我macaca-ios就是2.0.29版本（xcode版本9.0.1，Swift 4.0版本），编译XCTestWDUITests项目时，也是出现同样的问题；：/usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWDUITests/Server/Controllers/XCTestWDStatusController.swift:10:8: Module compiled with Swift 4.0.2 cannot be imported in Swift 4.0: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/../Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/x86_64.swiftmodule
请问您这个源项目是用Swift4.0.2编译的么，必须升级Xcode版本到9.0.2？

**Comment by WilliamStark** [comment]
@shanglongmin 我用的xcode 9.1 编译可以成功，你可以试着升级到最新xcode

**Comment by shanglongmin** [comment]
@WilliamStark ，嗯，xcode9.1版本编译通过，多谢

**Comment by shanglongmin** [comment]
@WilliamStark，xcode9.1版本编译还是失败了，你那边可以了么，已经可以进行iOS，app测试了么。
