### ISSUE TITLE
请教：推荐Win7 SP1下 macaca 兼容最好的安卓模拟器

### ISSUE THREAD

**Issue by litingjun2015** [alibaba/macaca#742]
有推荐说 Genymotion 不错？

另外最好该安卓模拟器能支持安装微信。

***

网上还有其他的模拟器，不知是否适用macaca。
https://www.androidauthority.com/best-android-emulators-for-pc-655308/

之前发现[三星手机Samsung SCH-N719与vivo X9L真机无法录制脚本  ](https://github.com/alibaba/macaca/issues/739)

**Comment by xudafeng** [comment]
Genymotion

**Comment by litingjun2015** [comment]
谢谢
