### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by grubby2013** [alibaba/macaca#744]
>> responseHandler.js:11:12 [master] pid:1715 Recieve HTTP Request from Client[2017-11-03 14:24:45]: method: POST url: /wd/hub/session/0bb819ad-407e-45af-ba9c-29cc8f0be755/element/7DA593EB-4C7F-45BD-B2EA-BE8E6EEA94F9/click, jsonBody: {}
>> proxy.js:55:14 [master] pid:1715 Proxy: /wd/hub/session/0bb819ad-407e-45af-ba9c-29cc8f0be755/element/7DA593EB-4C7F-45BD-B2EA-BE8E6EEA94F9/click:POST to http://localhost:8001/wd/hub/session/A65623CD-B3D2-4D6E-B16B-6E6C76BD8F2B/element/7DA593EB-4C7F-45BD-B2EA-BE8E6EEA94F9/click:POST with body: {}
>> proxy.js:85:20 [master] pid:1715 Got response with status 200: {"sessionId":"","status":0,"value":""}
>> session.js:109:14 [master] pid:1715 Send HTTP Respone to Client[2017-11-03 14:24:45]: {"sessionId":"","status":0,"value":""}
>> xctest-client.js:190:18 [master] pid:1715 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:1715 killing deviceLogProc pid: 1726
>> xctest-client.js:281:14 [master] pid:1715 killing runnerProc pid: 1723
>> xctest-client.js:287:14 [master] pid:1715 killing iproxyProc pid: 1983
>> xctest-client.js:201:16 [master] pid:1715 xctest client exit with code: 65, signal: null
>> xctest-client.js:231:14 [master] pid:1715 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:155:16 [master] pid:1715 devicelog exit with code: null, signal: SIGKILL
>> responseHandler.js:11:12 [master] pid:1715 Recieve HTTP Request from Client[2017-11-03 14:24:47]: method: POST url: /wd/hub/session/0bb819ad-407e-45af-ba9c-29cc8f0be755/elements, jsonBody: {"using":"name","value":"Applying for a part-time job没问题"}
>> proxy.js:55:14 [master] pid:1715 Proxy: /wd/hub/session/0bb819ad-407e-45af-ba9c-29cc8f0be755/elements:POST to http://localhost:8001/wd/hub/session/A65623CD-B3D2-4D6E-B16B-6E6C76BD8F2B/elements:POST with body: {"using":"name","value":"Applying for a part-time job没问题"}
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:1715 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:56:12 [master] pid:1715 Send Error Respone to Client: Error: connect ECONNREFUSED 127.0.0.1:8001
>> responseHandler.js:62:14 [master] pid:1715 Error: connect ECONNREFUSED 127.0.0.1:8001
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:1021:11)
      at _exceptionWithHostPort (util.js:1043:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)

* **Macaca Version**:
macaca-ios:2.0.29   macaca-cli:2.0.12
* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:
java

**Comment by Chan-Chun** [comment]
https://github.com/alibaba/macaca/issues/758#issuecomment-344507900 
Related issue.
