### ISSUE TITLE
使用xpath输入内容到搜索框（或输入框）后，会自动点击搜索（确定）

### ISSUE THREAD

**Issue by grubby2013** [alibaba/macaca#745]
* **Macaca Version**:
macaca-ios:2.0.29 macaca-cli:2.0.12
* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:
java

**Comment by Chan-Chun** [comment]
可以描述清楚一点么 或者有报错日志？

**Comment by grubby2013** [comment]
点击应用的搜索框，使用xpath进行sendkeys，发现：会自动完成搜索动作（自动点击软键盘上的搜索按键），以前是sendkeys以后要自己加一个步click

**Comment by Chan-Chun** [comment]
@grubby2013 提供模板系统信息 和 测试用例

**Comment by yihuineng** [comment]
问题久远关闭，如有问题，可再次提issue并提供详细环境信息&复现路径
