### ISSUE TITLE
如何可以选择真机已经安装的 apk，不用每次重装

### ISSUE THREAD

**Issue by litingjun2015** [alibaba/macaca#751]
* **Macaca Version**:
2.0.12

* **Macaca Doctor Logs**:
$ macaca doctor

  macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v7.10.1

  Android checklist:

  JAVA version is `1.8.0_121`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_121`
  ANDROID_HOME is set to `C:\soft\android_sdk\sdk`
  Platforms is set to `C:\soft\android_sdk\sdk\platforms\android-26`
  ADB tool is set to `C:\soft\android_sdk\sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\devtools\gradle-4.2.1`

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.7

* **Operate System**:
Win 7 SP1

* **Programming Language**:

是不是可以指定包名？

```
self.driver = driver.session({
                    'platformName': platformName,
                    'udid': device.udid,
                    'app': /^(\/|[a-z]:\\|https?:\/\/)/i.test(appPath) ? appPath : rootPath + '/' + appPath
                });
```

避免每次重装，以加快调试速度。

**Comment by njf1107** [comment]
在初始化时，设置reuse

**Comment by litingjun2015** [comment]
非常感谢！回头我试一下！
