### ISSUE TITLE
在unbuntu 中 使用docker进行 Reliable Master 部署

### ISSUE THREAD

**Issue by cooldeaaap1** [alibaba/macaca#752]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

按照你们的使用指南，使用docker部署：
$ git clone https://github.com/reliablejs/reliable-docker-base --depth=1
$ cd reliable-docker-base
$ docker build -t="reliable-docker-base" .
这里报错，说yum的问题，但是ubuntu没有yum啊，请问这个怎么解决，还是说ubuntu安装不了reliable?
![2017-11-10 02-18-24](https://user-images.githubusercontent.com/26562987/32622364-92343e8e-c5bd-11e7-9c4b-8508f4390647.png)

**Comment by xudafeng** [comment]
https://macacajs.github.io/reliable/guide/reliable-web-deploy.html
