### ISSUE TITLE
iOS端app定位元素查找时间很慢，最长十几分钟，被测APP断开网络连接后，则脚本执行速度趋近于Android，是XCTestWD的底层问题么，Appium也是这样

### ISSUE THREAD

**Issue by shanglongmin** [alibaba/macaca#755]
* **Macaca Version**: 2.0.12
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.3
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v8.2.0

  iOS checklist:
  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.26.2

  Android checklist:
  JAVA version is `1.8.0_77`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/longmin.shang/Library/Android/sdk`
  Platforms is set to `/Users/longmin.shang/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/longmin.shang/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.4

  Installed driver list:
  android: 2.0.40
  electron: 1.1.17
  ios: 2.0.29

* **Operate System**:
Darwin MacBook-Air.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* **Programming Language**:

**Comment by shanglongmin** [comment]
我先使用Appium做的iOS自动化，遇到这个定位慢（像卡死）一样的现象，然后尝试macaca，使用的大多elementByName，elementById，onclickBean方法定位的元素，也是遇到这个问题，怀疑是被测APP开着调试日志，有时会阻塞XCTestWD

**Comment by shanglongmin** [comment]
不知道大家有没有遇到过这个问题，我关掉网络连接之后，运行脚本，速度就基本正常了，否则越到后边执行越慢，能等几十分钟。

**Comment by SamuelZhaoY** [comment]
可暂时使用 模拟器进行测试，真机下 source 存在性能问题 应该与网络无关之前对比过 facebook WDA的驱动， 也存在同样问题

**Comment by nathandev0** [comment]
I got the same issue, any solution?

**Comment by candialala** [comment]
你好，来信已收到~~我会尽快查收并回复的！
XMU Software 
陈晓娟
