### ISSUE TITLE
升级xcode9.1后，无法启动xctestwd

### ISSUE THREAD

**Issue by wynanwong** [alibaba/macaca#758]
* **Macaca Version**:
  2.0.12
* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.3

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v7.6.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/wn/Library/Android/sdk`
  Platforms is set to `/Users/wn/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/wn/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.40
  chrome: 1.0.7
  electron: 1.1.6 [out-of-date]
  ios: 2.0.29
* **Operate System**:
Mac 10.13.1
* **Programming Language**:
java

升级xcode9.1后，一直无法启动xctestwd，看起来像是证书签名有问题。下面是执行过程中的log：
>> index.js:18:12 [master] pid:1682 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '172.16.10.136',
  host: 'wndeMacBook-Pro.local',
  loaded_time: '2017-11-15 10:50:59' }
>> middlewares.js:17:10 [master] pid:1682 base middlewares attached
>> router.js:133:10 [master] pid:1682 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:1682 Recieve HTTP Request from Client[2017-11-15 10:51:12]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"app":"/Users/wn/GitHome/xxxxx/src/app/xxxx.app","reuse":3,"platformName":"ios","udid":"xxxxxxxxxxxxxxx","deviceName":"iPhone 6 Plus"}}
>> session.js:47:10 [master] pid:1682 Creating session, sessionId: c110845e-4a68-4fbf-8fe8-158a170e6fe9.
ios-deploy
>> helper.js:176:12 [master] pid:1682 Using local app form /Users/wn/GitHome/xxx/src/app/xxx.app
CFBundleIdentifier is xxxxxxxxxxx
Get bundleId xxxxxxxx from plist /Users/wn/GitHome/xxxxx/src/app/xxxx.app/Info.plist
>> macaca-ios.js:246:12 [master] pid:1682 App "xxxxxxxxxxx" is already installed.
>> macaca-ios.js:247:12 [master] pid:1682 Adopting app reuse strategy: 3.
BundleId XCTestWD.XCTestWD does not exist.
>> macaca-ios.js:158:10 [master] pid:1682 {
	"bundleId": "xxxxxxxx",
	"platformName": "ios"
}
>> xctest-client.js:56:14 [master] pid:1682 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:167:12 [master] pid:1682 Trying to start xctestwd server...
>> xctest-client.js:242:14 [master] pid:1682 xcode version: 9.1
>> XCTestWD version: 1.3.6
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:1682 killing deviceLogProc pid: 1695
>> xctest-client.js:281:14 [master] pid:1682 killing runnerProc pid: 1692
>> xctest-client.js:201:16 [master] pid:1682 xctest client exit with code: 65, signal: null
>> xctest-client.js:155:16 [master] pid:1682 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:268:14 [master] pid:1682 Fail to start xctest: undefined
>> macaca-ios.js:167:12 [master] pid:1682 Trying to start xctestwd server...
>> xctest-client.js:242:14 [master] pid:1682 xcode version: 9.1
>> XCTestWD version: 1.3.6
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:1682 killing deviceLogProc pid: 1772
>> xctest-client.js:281:14 [master] pid:1682 killing runnerProc pid: 1769
>> xctest-client.js:201:16 [master] pid:1682 xctest client exit with code: 65, signal: null
>> xctest-client.js:155:16 [master] pid:1682 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:268:14 [master] pid:1682 Fail to start xctest: undefined
>> macaca-ios.js:167:12 [master] pid:1682 Trying to start xctestwd server...
>> xctest-client.js:242:14 [master] pid:1682 xcode version: 9.1
>> XCTestWD version: 1.3.6
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:1682 killing deviceLogProc pid: 1846
>> xctest-client.js:281:14 [master] pid:1682 killing runnerProc pid: 1843
>> xctest-client.js:201:16 [master] pid:1682 xctest client exit with code: 65, signal: null
>> xctest-client.js:155:16 [master] pid:1682 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:268:14 [master] pid:1682 Fail to start xctest: undefined
>> macaca-ios.js:167:12 [master] pid:1682 Trying to start xctestwd server...
>> xctest-client.js:242:14 [master] pid:1682 xcode version: 9.1
>> XCTestWD version: 1.3.6
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:1682 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:276:14 [master] pid:1682 killing deviceLogProc pid: 1926
>> xctest-client.js:281:14 [master] pid:1682 killing runnerProc pid: 1923
>> xctest-client.js:201:16 [master] pid:1682 xctest client exit with code: 65, signal: null
>> xctest-client.js:155:16 [master] pid:1682 devicelog exit with code: null, signal: SIGKILL
>> xctest-client.js:268:14 [master] pid:1682 Fail to start xctest: undefined
>> responseHandler.js:56:12 [master] pid:1682 Send Error Respone to Client: undefined

  InternalServerError: Internal Server Error
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:59:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by SamuelZhaoY** [comment]
可以去 xctestwd 的安装路径下，看xctestwd 能否编译通过

**Comment by wynanwong** [comment]
编译是可以通过的

**Comment by Chan-Chun** [comment]
https://github.com/macacajs/XCTestWD/issues/96 相关的issue
请更新最新的macaca-ios

**Comment by Chan-Chun** [comment]
https://github.com/alibaba/macaca/issues/757

**Comment by wynanwong** [comment]
@Chan-Chun 我看了最新的macaca-ios还是2.0.29版本，重新安装macaca-ios后，还是不行，还是报同样的错误

**Comment by upengfei** [comment]
这个问题好了吗？

**Comment by upengfei** [comment]
helper.js:176:12 [master] pid:1052 Using local app form /Users/yupfa/Desktop/U-debug.ipa
>> macaca-ios.js:246:12 [master] pid:1052 App ["com.xxxxxx"] is already installed.
>> macaca-ios.js:247:12 [master] pid:1052 Adopting app reuse strategy: 3.
# **BundleId XCTestWD.XCTestWD does not exist.
>> macaca-ios.js:158:10 [master] pid:1052 {
	"bundleId": "com.xxxxxx",
	"platformName": "ios"
}**
>> xctest-client.js:56:14 [master] pid:1052 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.3.10@xctestwd/XCTestWD/XCTestWD.xcodeproj



@Chan-Chun @SamuelZhaoY  这是因为xcode版本的缘故吗？重签名已经成功。

**Comment by upengfei** [comment]
@wynanwong @Chan-Chun @SamuelZhaoY 这个问题还能是否已经解决了？

**Comment by upengfei** [comment]
我怎么今天还是出现这个错误？
![image](https://user-images.githubusercontent.com/18410330/37390250-4b85dee2-27a2-11e8-9e7e-ab36610a540b.png)
