### ISSUE TITLE
xcode9.1 使用Macaca App Inspector 无法定位ios10单个元素，只能定位一整屏，ios11正常

### ISSUE THREAD

**Issue by lu398129884** [alibaba/macaca#759]
Macaca Version: 2.0.12
xcode version： 9.0
Macaca App Inspector Version：v2.0.10
![image](https://user-images.githubusercontent.com/33713711/32878794-6dd2e822-cae2-11e7-8033-a268f476408a.png)

**Comment by SamuelZhaoY** [comment]
目前 xcode 9.0 对iOS 10 以及以下版本兼容性差，系统接口返回不了元素树 请使用11
