### ISSUE TITLE
Android 中文输入问题

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#76]
目前的几个实现方案:

| 方案 | 优点 | 缺点 |
| --- | --- | --- | 
| UIAutomator 集成[Utf7ImeService](https://github.com/sumio/uiautomator-unicode-input-helper/blob/master/Utf7Ime/src/jp/jun_nama/test/utf7ime/Utf7ImeService.java) 输入法| 非侵入，外挂输入法 | 额外安装 apk |
| 剪切板 | 非侵入 | 复制简单，粘贴操作繁琐，实现困难 |
| App 内集成 | 侵入式 | 解决通信问题 |

**Comment by lihuazhang** [comment]
剪切板不靠谱，最早的appium才这样做。 我觉得第一个 utf7ime 比较好。而且可以统一输入法，免去其他输入法的干扰。

**Comment by xudafeng** [comment]
@lihuazhang 装了还需要设置默认啊

**Comment by lihuazhang** [comment]
看下 appium 怎么做的，他装好之后就直接默认了。

在 2016年6月24日，下午2:32，xdf <notifications@github.com<mailto:notifications@github.com>> 写道：

@lihuazhang<https://github.com/lihuazhang> 装了还需要设置默认啊

**Comment by xudafeng** [comment]
已集成Utf7ImeService，请升级最新版 macaca-android 驱动

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/439
