### ISSUE TITLE
wrong proxy command translation

### ISSUE THREAD

**Issue by SamuelZhaoY** [alibaba/macaca#764]
在安卓场景下向代理发出的 /wd/hub/session/' + crawler.sessionId + '/keys' 事件， 被转换成了 /value,

也应该由UIAutomator 中 keys 事件所接受

![default](https://user-images.githubusercontent.com/8198256/33170980-4b2f1a18-d085-11e7-9d58-da92f7a5b45a.png)

**Comment by SamuelZhaoY** [comment]
@xudafeng @qichuan

**Comment by xudafeng** [comment]
@Yinxl你有遇到过吗
