### ISSUE TITLE
sample-nodejs test-ios failed  to excute

### ISSUE THREAD

**Issue by lzhang1** [alibaba/macaca#767]
macaca-doctor version: 2.0.4

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.5.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.26.2

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhanglei/Library/Android/sdk`
  Platforms is set to `/Users/zhanglei/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/zhanglei/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.2

  Installed driver list:

  android: 2.0.41
  chrome: 1.0.7
  electron: 1.1.17
  ios: 2.0.29

>> macaca-ios.js:324:12 [master] pid:27365 Kill simulator failed Error: Command failed: killAll Simulator
No matching processes belonging to you were found

>> macaca-ios.js:330:12 [master] pid:27365 Shutdown simulator 1D8FF538-AD2F-4BAB-887C-3F949DE633D0 failed Error: Command failed: xcrun simctl shutdown "1D8FF538-AD2F-4BAB-887C-3F949DE633D0"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to shutdown device in current state: Shutdown

>> macaca-ios.js:158:10 [master] pid:27365 {
	"bundleId": "xudafeng.ios-app-bootstrap",
	"platformName": "iOS",
	"app": "/var/folders/st/1v14ncq55p936v4bj3fhj99c0000gn/T/ios-app-bootstrap.app/"
}
>> xctest-client.js:56:14 [master] pid:27365 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:167:12 [master] pid:27365 Trying to start xctestwd server...
>> xctest-client.js:242:14 [master] pid:27365 xcode version: 9.1
>> XCTestWD version: 1.3.10
>> xctest-client.js:190:18 [master] pid:27365 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:27365 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> Read simulator log at: /var/folders/st/1v14ncq55p936v4bj3fhj99c0000gn/T/com.apple.dt.XCTest/IDETestRunSession-537A8FFF-D1C8-4676-98EA-F961BB6DD176/XCTestWDUITests-034D0A01-C876-49A5-B237-D9A3F1939AA3/StandardOutputAndStandardError.txt
>> xctest-client.js:190:18 [master] pid:27365 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:27365 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:27365 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:190:18 [master] pid:27365 please check project: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:281:14 [master] pid:27365 killing runnerProc pid: 27479
>> xctest-client.js:201:16 [master] pid:27365 xctest client exit with code: 65, signal: null
>> Read simulator log at: /var/folders/st/1v14ncq55p936v4bj3fhj99c0000gn/T/com.apple.dt.XCTest/IDETestRunSession-537A8FFF-D1C8-4676-98EA-F961BB6DD176/XCTestWDUITests-034D0A01-C876-49A5-B237-D9A3F1939AA3/StandardOutputAndStandardError.txt

**Comment by lzhang1** [comment]
xcode 9.1,  已经更新xctestwd, npm i xctestwd-frameworks-9.1 --save, 依然存在这个问题， 程序执行到这儿，就停了，不在继续执行， 能不能帮助定位一下问题？ 谢谢

**Comment by Chan-Chun** [comment]
重新安装一下全局macaca-ios，确保为最新版本 @lzhang1
