### ISSUE TITLE
windows 10下安装macaca报错

### ISSUE THREAD

**Issue by lihaiye** [alibaba/macaca#771]
win10下安装macaca，我的步骤是这样的：
1、设置代理：运行CMD输入指令“npm config set proxy=http://IP:端口
2、运行管理员命令窗口，输入npm config set registry https://registry.npm.taobao.org切换源
3、在CDM命令中输入安装命令：npm i -g macaca-cli

然后安装失败，出现以下报错：(我的nodejs版本是v8.9.1)
npm ERR! cb() never called!
![image](https://user-images.githubusercontent.com/17242849/33760256-09891d4a-dc40-11e7-939a-de71d58e497f.png)

* **Macaca Version**:

* **Macaca Doctor Logs**:
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'macaca-cli' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose npm-session 9b39e195a2eea352
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 error cb() never called!
8 error This is an error with npm itself. Please report this error at:
9 error <https://github.com/npm/npm/issues>

* **Operate System**:

* **Programming Language**:

**Comment by Chan-Chun** [comment]
请尝试清空npm缓存或者重新安装node和npm
