### ISSUE TITLE
support xcode 9.2

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#772]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by Chan-Chun** [comment]
https://github.com/macacajs/xctestwd-frameworks-9.2
增加xcode9.2依赖包，已支持xcode9.2

**Comment by Chan-Chun** [comment]
xcode9.2版本用户请重装macaca-ios

```bash
$ npm i -g macaca-ios
```
