### ISSUE TITLE
运行macaca自带的demo时，模拟器上没有安装上xctestwd，无法执行测试

### ISSUE THREAD

**Issue by 876957458** [alibaba/macaca#774]
➜  sample-nodejs git:(master) ✗ platform=ios macaca run -d ./macaca-test/mobile-app-sample.test.js
>> webdriver sdk launched
>> 

>> 

>> (node:5334) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

>>   macaca-test/mobile-app-sample.test.js

ios-deploy
>> get /Users/zhaoyinfan/.macaca-temp/ios-app-bootstrap.zip from cache
>> sha:d2e65bba467659ef610b369f2ee599c1
CFBundleIdentifier is xudafeng.ios-app-bootstrap
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/gn/p0880v0n7kxd9mpjl_998rrm0000gn/T/ios-app-bootstrap.app/Info.plist
>> XCTestWD version: 1.3.11
>> Read simulator log at: /var/folders/gn/p0880v0n7kxd9mpjl_998rrm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-BD78747A-9ABC-4D6B-955E-888ADF521F9D/XCTestWDUITests-51E98639-9E84-4F37-8B63-53552916D965/StandardOutputAndStandardError.txt
>> Read simulator log at: /var/folders/gn/p0880v0n7kxd9mpjl_998rrm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-BD78747A-9ABC-4D6B-955E-888ADF521F9D/XCTestWDUITests-51E98639-9E84-4F37-8B63-53552916D965/StandardOutputAndStandardError.txt
>> Read simulator log at: /var/folders/gn/p0880v0n7kxd9mpjl_998rrm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-BD78747A-9ABC-4D6B-955E-888ADF521F9D/XCTestWDUITests-51E98639-9E84-4F37-8B63-53552916D965/StandardOutputAndStandardError.txt

* **Macaca Version**:
2.0.12
* **Macaca Doctor Logs**:
Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.9.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.27.0

  Android checklist:

  JAVA version is `1.8.0_144`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.29

* **Operate System**:
mac OX 10.12.6
* **Programming Language**:
node.js

**Comment by Chan-Chun** [comment]
请提供更多信息
