### ISSUE TITLE
ios，下载app失败

### ISSUE THREAD

**Issue by xray2008** [alibaba/macaca#775]
$ macaca doctor

  macaca-doctor version: 2.0.4

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v6.11.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.23.0

  Android checklist:

  JAVA version is `1.8.0_131`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  electron: 1.1.6 [out-of-date]
  ios: 2.0.29

* **Macaca Version**: 

* **Macaca Doctor Logs**:

* **Operate System**: MacOS sierra 10.12.6

* **Programming Language**:python

>> get /Users/youku/.macaca-temp/LaiFeng-Release.ipa from cache
>> sha:20b16fda57057448d2c83d2a006776ba
>> helper.js:176:12 [master] pid:48041 Using local app form /Users/youku/.macaca-temp/LaiFeng-Release.ipa
>> macaca-ios.js:279:12 [master] pid:48041 App 'com.youku.LaiFeng' is not installed.
>> macaca-ios.js:284:14 [master] pid:48041 this.device.installUntilReady is not a function
>> responseHandler.js:56:12 [master] pid:48041 Send Error Respone to Client: UnknownError: Failed to install app 'com.youku.LaiFeng', please install the app manually.
>> responseHandler.js:62:14 [master] pid:48041 UnknownError: Failed to install app 'com.youku.LaiFeng', please install the app manually.
    at IOS.startRealDevice (/usr/local/lib/node_modules/macaca-ios/lib/macaca-ios.js:285:13)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/_co@4.6.0@co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
>> responseHandler.js:78:14 [master] pid:48041 Send Bad HTTP Respone to Client[2017-12-18 15:59:31]: {"sessionId":"11eafbf2-55f6-4931-b415-a151cfb60401","status":13,"value":{"message":"Failed to install app 'com.youku.LaiFeng', please install the app manually."}}

**Comment by deadvia** [comment]
#### installUntilReady不是一个方法

```
this.device.installUntilReady is not a function
```

#### 解决

```
查看源码
commits: e73c3e3
replace to installUtilReady
将 yield this.device.install(app); 改为 yield this.device.installUntilReady(app, bundleId);
可是installUntilReady方法 跑不起来
于是我自己改回来，iOS真机就能跑起来了
```

#### 参考链接

[issues/755](https://github.com/alibaba/macaca/issues/775)

[issues/182](https://github.com/alibaba/uirecorder/issues/182)

**Comment by xudafeng** [comment]
安装.app格式的文件，不是.ipa

文档 https://macacajs.github.io/environment-setup
