### ISSUE TITLE
执行sudo cnpm i macaca-android -g失败

### ISSUE THREAD

**Issue by hekaiyou** [alibaba/macaca#778]
执行sudo cnpm i macaca-android -g时报以下异常：

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan
to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED
in 1s
Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/_gradle@1.0.8@gradle/lib/gradle.js:57:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[1/3] scripts.install unlock-apk@~1.0.3 finished in 2s
[2/3] scripts.install uiautomatorwd@~1.0.45 run "node ./scripts/build.js"

实际上我已经配置了环境变量：
$ echo $ANDROID_HOME
/Users/hekaiyou/Library/Android/sdk

为什么会这样？

**Comment by hekaiyou** [comment]
$ macaca doctor
  macaca-doctor version: 2.0.4

  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v8.9.3

  iOS checklist:
  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.27.0

  Android checklist:
  JAVA version is `1.8.0_151`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/hekaiyou/Library/Android/sdk`
  Platforms is set to `/Users/hekaiyou/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/hekaiyou/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.4

  Installed driver list:
  android: 2.0.41
  electron: 1.1.18
  ios: 2.0.29

**Comment by hekaiyou** [comment]
Mac下，npm命令下载的全局模块会存放在系统目录，我修改了默认的全局模块(node_global)的存放路径以及缓存(global_cache)的路径，重新安装后，就能正常安装了。

比如我在用户目录下新建node_modules文件夹，在下面建立node_global及node_cache两个文件夹，修改默认全局路径：

```
$ npm config set prefix "/Users/[用户名]/node_modules/node_global"
$ npm config set cache "/Users/[用户名]/node_modules/node_cache"
```

然后还要配置Node环境变量，让系统识别`npm`下载的全局模块：


```
$ vim ~/.bash_profile
[按下i，显示insert，进入输入模式，输入如下配置]
NODE_HOME="/Users/[用户名]/node_modules/node_global"
export PATH="$NODE_HOME/bin:$PATH"
export NODE_HOME
[按esc，输入:wq!保存]
$ source ~/.bash_profile
$ echo $NODE_HOME
```

**Comment by xudafeng** [comment]
先解决权限问题 https://macacajs.github.io/zh/faq
