### ISSUE TITLE
请问下：是不是用例编写中，一个case失败了。整个case集（js)就无法继续跳过失败的case继续执行了。

### ISSUE THREAD

**Issue by lemonadam** [alibaba/macaca#78]
* **Macaca Version**:
1.0.35
* **Macaca Doctor**:
 Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.7

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_11`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/lemon/work/sdk/android-sdk-macosx`
  Platforms is set to `/Users/lemon/work/sdk/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/lemon/work/sdk/android-sdk-macosx/tools/android`

  Installed driver list:

  android: 1.0.13
  ios: 1.0.30

* **Platform**:

**Comment by zhuyali** [comment]
如果是两个界面上或者逻辑上不相关的用例，那么用例执行的成功与否只由当前的测试脚本决定，而不依赖于其他用例是否执行成功。举个例子来说，如果case1是登录，其他测试用例是登录后所做的一系列事情，那么case1失败了，意味着登录没有成功，那么当执行到其他测试用例时，就会因为找不到界面元素等问题而导致测试用例失败；而如果一个case1是一个跳转页面然后又返回的测试用例，当其执行失败后，并不会对其他测试用例有影响。

**Comment by lemonadam** [comment]
@zhuyali 那我可以理解成如果在某个平行tab下的某个子tab挂了。其实case执行是无法出来的，也就是后续的都失败了。因为每个用例虽然是独立的，但是执行完case a 失败了会执行case b。而b的起点就是 a失败的终点位置。可以这样理解吧。因此最后case b 也会失败。

**Comment by zhuyali** [comment]
@lemonadam ＝。＝能说的稍微通俗一点么？没看懂你说的意思

**Comment by lemonadam** [comment]
@zhuyali 
不好意思··· —— ，我重新表达一下。
我其实就是想说，目前的策略就是case b 执行的开始的位置  就是 case a 执行结束的位置对吧。
我不知道我理解的是否对

**Comment by zhuyali** [comment]
@lemonadam 
其实我想说的是，如果一个case的脚本正确，并且它所涉及到的界面元素都是可以在当前界面找到的，那么脚本就会正确执行。你理解的意思应该是 上一个脚本的结束位置 会作为 下一个脚本的开始位置 吧？我觉得这样的理解是对的。

**Comment by lemonadam** [comment]
@zhuyali  好，谢谢。
那个人觉得如果业务逻辑有点深入的，还是写在不同js里吧。分别执行就好了。
感谢。
