### ISSUE TITLE
程序执行 driver.quit();时，报错：Send Error Respone to Client: TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by xyhzchn** [alibaba/macaca#783]
* **Macaca Version**:
     2.0.13
* **Macaca Doctor Logs**:
       macaca-doctor version: 2.0.4

  Node.js checklist:

  node env: C:\Program Files\nodejs\node.exe
  node version: v8.7.0

  Android checklist:

  JAVA version is `1.8.0_141`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_141`
  ANDROID_HOME is set to `D:\Android\android-sdk-windows`
  Platforms is set to `D:\Android\android-sdk-windows\platforms\android-9`
  ADB tool is set to `D:\Android\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\software\gradle-4.2.1`

  Installed driver list:

  android: 2.0.46
  chrome: 1.0.7
  electron: 1.1.19
* **Operate System**:
     window7
* **Programming Language**:
    java

  当执行driver.quit();方法时。

**Comment by Karenzxuel** [comment]
解决了吗这个问题？

**Comment by Karenzxuel** [comment]
能关注一下这个问题吗？

**Comment by xyhzchn** [comment]
没有再次跟踪，后面应该是解决了
