### ISSUE TITLE
增加Inspector特性：支持输出到文件

### ISSUE THREAD

**Issue by wuweicoco** [alibaba/macaca#784]
正常场景：本地调试脚本的过程中，如果出现错误了，可以马上停止，使用 app-inspector -u 进行元素tree的查看。
需求场景：jenkins 运行过程中，如果出错，不方便进行 app-inspector，临时的替代方法是使用 driver 进行  source API 的调用，dump 出所有的元素。但是source 出来的结果，只是一个 json 列表，缺少过滤，缺少截图，缺少相关 js，展示不友好。

需求：
inspector 支持dump 成 html 文件，并且不使用浏览器打开。 在 jenkins 操作时，判断出执行失败的情况下，可以自己dump出html文件，以便进一步分析错误原因。

**Comment by xudafeng** [comment]
@wuweicoco

`但是source 出来的结果，只是一个 json 列表，缺少过滤，缺少截图，缺少相关 js，展示不友好。`

json里返回是当前界面xml，截图可以在 source 后增加 screenshot 操作。

inspector 不是在集成阶段用的，jenkins job里再通过inspector 去dump xml就绕远了。
