### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by erdengbing** [alibaba/macaca#788]
这个问题看到很多之前issue，但都被close了
但没有一个帖子有明确的解决办法，谁能提供帮助？

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at Object._errnoException (util.js:1003:13)
      at _exceptionWithHostPort (util.js:1024:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)

* **Macaca Version**:
2.0.13
* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.4

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v9.4.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.28.0

  Android checklist:

  JAVA version is `1.8.0`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.30

* **Operate System**:
maxOS:10.13.3
Xcode:9.2

* **Programming Language**:

**Comment by qwezxcjohnny** [comment]
我也碰到了。两台ios并行 ，很容易出现这个错

**Comment by k19810703** [comment]
我也碰到这个问题，在模拟器上运行，安装好之后，应用打开以后闪退

**Comment by SamuelZhaoY** [comment]
XCTestWD 主要支持单设备运行，connect ECONNREFUSED 127.0.0.1:8001 这个错误是在执行测试脚本时，xctestwd 底层的XCTEST 接口执行异常导致的，需要参考 https://github.com/macacajs/XCTestWD 做断点排查 或者使用其他方案绕过特定UI 命令执行
