### ISSUE TITLE
app-inspector运行失败android

### ISSUE THREAD

**Issue by kissfu** [alibaba/macaca#789]
* **Macaca Version**:2.0.4

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

node_modules里面 UIAutomatorWD 模块出错。
第一次接受命令的时候参数permissionPattern出现undefined，解析json出错。
 if (args.containsKey("permissionPattern")) {
            String permissionPattern = args.getString("permissionPattern");
            Utils.print("UIAutomatorWD->permissionPattern=" + permissionPattern);
            if(!permissionPattern.equals("undefined")) {
                JSONArray permissionPatterns = JSON.parseArray(args.getString("permissionPattern"));
                skipPermission(permissionPatterns, 15);
            }
        }

第二个问题：两个apk文件编译失败，但是我用as编译出来的apk是成功的。
> uiautomatorwd@1.0.47 install /Users/able/.nvm/versions/node/v7.10.0/lib/node_modules/macaca-android/node_modules/uiautomatorwd
> node ./scripts/build.js

(node:13802) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ,,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve org.nanohttpd:nanohttpd:2.3.1.
     Required by:
         project :app
      > Could not resolve org.nanohttpd:nanohttpd:2.3.1.
         > Could not get resource 'http://maven.aliyun.com/nexus/content/groups/public/org/nanohttpd/nanohttpd/2.3.1/nanohttpd-2.3.1.pom'.
            > Could not GET 'http://maven.aliyun.com/nexus/content/groups/public/org/nanohttpd/nanohttpd/2.3.1/nanohttpd-2.3.1.pom'.
               > Connect to 127.0.0.1:10086 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve org.nanohttpd:nanohttpd:2.3.1.
         > Could not get resource 'https://jcenter.bintray.com/org/nanohttpd/nanohttpd/2.3.1/nanohttpd-2.3.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/nanohttpd/nanohttpd/2.3.1/nanohttpd-2.3.1.pom'.
               > Connect to 127.0.0.1:10086 [/127.0.0.1] failed: Connection refused (Connection refused)
   > Could not resolve com.alibaba:fastjson:1.2.31.
     Required by:
         project :app
      > Could not resolve com.alibaba:fastjson:1.2.31.
         > Could not get resource 'http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/fastjson/1.2.31/fastjson-1.2.31.pom'.
            > Could not GET 'http://maven.aliyun.com/nexus/content/groups/public/com/alibaba/fastjson/1.2.31/fastjson-1.2.31.pom'.
               > Connect to 127.0.0.1:10086 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve com.alibaba:fastjson:1.2.31.
         > Could not get resource 'https://jcenter.bintray.com/com/alibaba/fastjson/1.2.31/fastjson-1.2.31.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/alibaba/fastjson/1.2.31/fastjson-1.2.31.pom'.
               > Connect to 127.0.0.1:10086 [/127.0.0.1] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

(node:13802) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> unlock-apk@1.0.8 install /Users/able/.nvm/versions/node/v7.10.0/lib/node_modules/macaca-android/node_modules/unlock-apk
> node ./script/build.js

(node:13818) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ,,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'unlock-apk'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:2.3.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:2.3.1.
         > Could not get resource 'http://maven.aliyun.com/nexus/content/groups/public/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
            > Could not GET 'http://maven.aliyun.com/nexus/content/groups/public/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
               > Connect to 127.0.0.1:10086 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve com.android.tools.build:gradle:2.3.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
               > Connect to 127.0.0.1:10086 [/127.0.0.1] failed: Connection refused (Connection refused)

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/179
