### ISSUE TITLE
用例中的 .webview() .native() 作用是什么，有这些方法的时候会使得脚本执行失败。

### ISSUE THREAD

**Issue by lemonadam** [alibaba/macaca#79]
问题：用例中的 .webview() .native() 作用是什么，有这些方法的时候会使得脚本执行失败。这是封装好了什么方法么。请问如何找到对应方法关联的文件。

* **Macaca Version**:
1.0.35
* **Macaca Doctor**:
Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.7

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_11`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/lemon/work/sdk/android-sdk-macosx`
  Platforms is set to `/Users/lemon/work/sdk/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/lemon/work/sdk/android-sdk-macosx/tools/android`

  Installed driver list:

  android: 1.0.13
  ios: 1.0.30
* **Platform**:
ios & android

**Comment by lemonadam** [comment]
加入hosts
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1                            localhost
之后无障碍了

**Comment by xudafeng** [comment]
issue 关了，以后不要干掉ipv6的绑定

**Comment by yaniswang** [comment]
赞，我也碰到了！

感觉这个问题很容易出现，有没有办法在macaca的错误日志里把这个信息抛出来？

否则在没人告知的情况下，谁会想到是这个问题引起的。

**Comment by xudafeng** [comment]
@yaniswang 哪里抛出呢？你瞅瞅代码哪里加合适啊？

**Comment by ManningZhang** [comment]
@lemonadam 请问下这个要在哪里加呢
