### ISSUE TITLE
XCTestWD@1.3.13以后定位不到iOS的tableView下的元素

### ISSUE THREAD

**Issue by CaiWiKi** [alibaba/macaca#795]
你好：
        从macaca-ios@2.0.28开始xctestwd升级到@1.3.13，出现只能定位到tableView，而tableView下所有元素都无法定位，用app-inspector可以看到XCUIElementTypeTable下为空。
![app-inspector 1](https://user-images.githubusercontent.com/35788662/37129680-173eb05a-22bb-11e8-9c5e-e29182ba08cd.png)

回滚到xctestwd@1.1.8才正常。麻烦帮忙看下是什么原因，谢谢！

**Comment by SamuelZhaoY** [comment]
您好，上午我通过1.3.18 查询了macaca demo 以及iOS 系统原生界面，最你的问题做核对检查.   发现相关页面没有您描述的问题. 

![image](https://user-images.githubusercontent.com/8198256/37561747-652471fa-2a91-11e8-901b-10dc27bb0cf3.png)

<img width="1385" alt="screen shot 2018-03-18 at 9 44 42 am" src="https://user-images.githubusercontent.com/8198256/37561751-81771240-2a91-11e8-8448-cbee58bcacd1.png">

1.1.8 属于早期版本，后续做了source 优化，对于不可见的元素，在获取窗口树的时候做了移除.  可能是这个原因导致的.  这个是 1.1.8 到 1.3.X 关于元素检索的主要区别
