### ISSUE TITLE
执行uirecorder start --mobile时 报错

### ISSUE THREAD

**Issue by ca-ssiee** [alibaba/macaca#796]
开启macaca server后 执行uirecorder start --mobile。安装 iOS app 报错
(node:4201) UnhandledPromiseRejectionWarning: Error: Command failed: /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "/Users/guanjihong/.macaca-temp/Autohome.ipa/Info.plist"
Print: Entry, "CFBundleIdentifier", Does Not Exist

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:127:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:4201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by upengfei** [comment]
这是什么问题？

**Comment by upengfei** [comment]
我也碰到了
