### ISSUE TITLE
cnpm install macaca-android -g 安装 提示  A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by qinghuazhu** [alibaba/macaca#797]
windows 10   64位

C:\Users\Administrator>macaca doctor

macaca-doctor version: 2.0.9

Node.js checklist:

node env: C:\Program Files\nodejs\node.exe

node version: v8.10.0

Android checklist:

JAVA version is `9`

JAVA_HOME is set to `C:\Program Files\Java\jdk-9.0.4`

ANDROID_HOME is set to `D:\sdk`

Platforms is set to `D:\sdk\platforms\android-9`

ADB tool is set to `D:\sdk\platform-tools\adb.exe`

GRADLE_HOME is set to `C:\Gradle\gradle-4.4.1`

Installed driver list:

android: 2.0.46

C:\Users\Administrator>cnpm install macaca-android -g

Downloading macaca-android to C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android_tmp

Copying C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android_tmp\_macaca-android@2.0.46@macaca-android to C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android

Installing macaca-android's dependencies to C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android/node_modules

[1/10] webdriver-dfn-error-code@~1.0.1 installed at node_modules\_webdriver-dfn-error-code@1.0.4@webdriver-dfn-error-code

[2/10] driver-base@~0.1.0 installed at node_modules\_driver-base@0.1.4@driver-base

[3/10] macaca-utils@^1.0.0 installed at node_modules\_macaca-utils@1.0.1@macaca-utils

[4/10] temp@~0.8.3 installed at node_modules\_temp@0.8.3@temp

[5/10] xml2map@^1.0.2 installed at node_modules\_xml2map@1.0.2@xml2map

[6/10] uiautomatorwd@~1.0.45 installed at node_modules\_uiautomatorwd@1.0.50@uiautomatorwd

[7/10] unlock-apk@~1.0.3 installed at node_modules\_unlock-apk@1.0.8@unlock-apk

[8/10] xlogger@~1.0.0 installed at node_modules\_xlogger@1.0.6@xlogger

[9/10] macaca-chromedriver@~1.0.1 installed at node_modules\_macaca-chromedriver@1.0.40@macaca-chromedriver

[10/10] macaca-adb@~1.0.3 installed at node_modules\_macaca-adb@1.0.30@macaca-adb

execute post install 3 scripts...

[1/3] scripts.install uiautomatorwd@~1.0.45 run "node ./scripts/build.js"

(node:2040) UnhandledPromiseRejectionWarning: ,Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

,

FAILURE: Build failed with an exception.

* What went wrong:

A problem occurred configuring project ':app'.

> Failed to notify project evaluation listener.

> javax/xml/bind/annotation/XmlSchema

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

(node:2040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:2040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[1/3] scripts.install uiautomatorwd@~1.0.45 finished in 9s

[2/3] scripts.install unlock-apk@~1.0.3 run "node ./script/build.js"

(node:6040) UnhandledPromiseRejectionWarning: ,,

FAILURE: Build failed with an exception.

*** What went wrong:

A problem occurred configuring project ':app'.

> Failed to notify project evaluation listener.

> javax/xml/bind/annotation/XmlSchema

* Try:**

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

(node:6040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:6040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[2/3] scripts.install unlock-apk@~1.0.3 finished in 2s

[3/3] scripts.install macaca-chromedriver@~1.0.1 run "node ./bin/macaca-chromedriver install"

>> version: 2.33

>> chromedriver cdn url: https://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/chromedriver/2.33/chromedriver_win32.zip

>> chromedriver local in C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android\node_modules\_macaca-chromedriver@1.0.40@macaca-chromedriver\exec\chromedriver2.33.exe

[3/3] scripts.install macaca-chromedriver@~1.0.1 finished in 5s

deprecate macaca-chromedriver@1.0.40 › request@2.69.0 › node-uuid@~1.4.7 Use uuid module instead

deprecate macaca-chromedriver@1.0.40 › request@2.69.0 › tough-cookie@~2.2.0 ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

Recently updated (since 2018-03-08): 6 packages (detail see file C:\Users\Administrator\AppData\Roaming\npm\node_modules\macaca-android\node_modules\.recently_updates.txt)

2018-03-14

→ xlogger@1.0.6 › xutil@1.0.11 › opn@^5.1.0(5.3.0) (23:56:57)

2018-03-13

→ macaca-chromedriver@1.0.40 › request@2.69.0 › http-signature@1.1.1 › sshpk@^1.7.0(1.14.1) (08:12:08)

2018-03-12

→ uiautomatorwd@~1.0.45(1.0.50) (12:01:47)

→ macaca-adb@1.0.30 › npm-update@1.0.7 › co-request@0.2.1 › request@*(2.85.0) (18:37:49)

2018-03-09

→ unlock-apk@1.0.8 › gradle@1.0.9 › cross-spawn@5.1.0 › lru-cache@^4.0.1(4.1.2) (01:58:33)

2018-03-08

→ macaca-adb@1.0.30 › commander@^2.9.0(2.15.0) (09:11:52)

All packages installed (160 packages installed from npm registry, used 20s, speed 242.8kB/s, json 138(1.5MB), tarball 3.27MB)

**Comment by fengguochao** [comment]
你好，请问更新到最新版问题解决了吗？
如果还有问题，请提供一下详细信息
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
