### ISSUE TITLE
iOS脚本录制，使用NSClassFromString创建的控件无响应，获取不到控件名。

### ISSUE THREAD

**Issue by jack-github** [alibaba/macaca#798]
* **Macaca Version**:
2.0.9
* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.9

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.9.4

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.0
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.28.0

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/jack/Library/Android/sdk`
  Platforms is set to `/Users/jack/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/jack/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.5

  Installed driver list:

  android: 2.0.46
  chrome: 1.0.7
  ios: 2.0.30
* **Operate System**:
MacOS 10.13.3 (17D47)
* **Programming Language**:

脚本录制，使用NSClassFromString创建的控件无响应，获取不到控件名。
   ✓ 执行成功
  tap: //*[@name="xxx"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeTabBar/XCUIElementTypeButton

**Comment by SamuelZhaoY** [comment]
![screen shot 2018-09-09 at 11 31 15 am](https://user-images.githubusercontent.com/8198256/45260825-e6924200-b423-11e8-8e4d-46ae2ff30d3a.png)
建议详细描述 "使用NSClassFromString创建的控件" 的方式. 本地尝试通过此方法创建UIView，依然可以解析:
```
UIView* view = [[NSClassFromString(@"UIView") alloc] init];
    [view setFrame:CGRectMake(10,0,200,200)];
    view.backgroundColor = [UIColor blueColor];
```
