### ISSUE TITLE
iOS 某些情况click事件异常

### ISSUE THREAD

**Issue by ztwo** [alibaba/macaca#799]
* **Macaca Version**:
2.0.10
* **Macaca Doctor Logs**:
我这边使用的是macaca-iOS 2.0.26。因为需要测试iOS10
xctestwd是1.1.8

* **Operate System**:
mac 10.12.5
* **Programming Language**:
python 2.7

* 问题现象：iOS 点击控件，某些情况会发生点击页面不跳转行为。macaca日志输出了正常的点击日志，从肉眼来看控件发生了按下的效果。发生问题后，再次触发点击事件，可正常跳转
	
* 问题排查：
	* 1.使用xpah，坐标点，与上情况一致
	* 2.使用swipe，press_click，对此控件操作，情况一致
	* 3.因为第二次点击无异常，所以我对比了第一次点击前与点击后的source，页面结构无变化，仅有一个不相关的控件从StaticText变成了button
	* 4.确认控件已经加载完毕

总结：请帮忙排查，如何相关数据，我会及时提供

**Comment by ztwo** [comment]
@SamuelZhaoY 感谢回复。命令行既输出了点击操作日志，而且Ui层出现了点击效果。但是实际的业务逻辑未被执行（业务逻辑是跳转另一页，控件是 XCUIElementTypeCell）。

**Comment by SamuelZhaoY** [comment]
@ztwo 如果UI上出现了点击效果，则确认UI 测试空间指令生效，建议换其他的指令试试，是不是app UI 本身的问题

**Comment by ztwo** [comment]
@SamuelZhaoY 感谢回复，尝试了双击指令，能明显看到第一次点击无效，第二次则无异常。切换至appium执行也有类似问题，人肉点击 则无异常。
