### ISSUE TITLE
执行macaca-test-sample的PC段例子，出现如图错误

### ISSUE THREAD

**Issue by holysor** [alibaba/macaca#8]
具体步骤：
1.通过npm下载github上的macaca-test-sample样例
2.进入到macaca-test-sample目录执行命令：npm install
3.运行命令：make test-ios或者make test-pc
错误，如图(图片显示不出来。。。):

platform=ios macaca run --server --verbose -d ./macaca-test/macaca-mobile-sample.test.js
>> index.js:62:12 [master] pid:91126 webdriver server start with config:
 { port: 3456,
  ip: '10.10.1.20',
  host: 'holysordeiMac.local',
  loaded_time: '2016-03-31 11:03:05' }
>> middlewares.js:31:10 [master] pid:91126 base middlewares attached
>> router.js:101:10 [master] pid:91126 router set
>> webdriver sdk launched
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/.macaca-client_npminstall/mocha/2.2.4/.bin/mocha ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)

![Uploading err.png…]()

**Comment by xudafeng** [comment]
@holysor 操作系统是什么？

**Comment by holysor** [comment]
@xudafeng mac OS 10.11.3

**Comment by xudafeng** [comment]
@holysor `macaca run --verbose -d ./macaca-test/macaca-desktop-sample.test.js` 直接运行这个的log贴一下

**Comment by holysor** [comment]
@xudafeng 
![image](https://cloud.githubusercontent.com/assets/17400810/14165455/ababf854-f73b-11e5-8fa0-3a10d870951b.png)

**Comment by xudafeng** [comment]
@holysor 如下步骤操作试一下

```
$ npm i macaca-client -g
# 解决你的网络问题
$ export CHROMEDRIVER_CDNURL=http://npm.taobao.org/mirrors/chromedriver
$ make test-pc
```

**Comment by holysor** [comment]
@xudafeng 
![image](https://cloud.githubusercontent.com/assets/17400810/14166970/7df74a9e-f74a-11e5-887e-6b88a3cbc485.png)

**Comment by xudafeng** [comment]
@holysor 不要使用 `sudo`, [这里](https://testerhome.com/topics/4330)有说明。

**Comment by holysor** [comment]
@xudafeng 跟sudo应该没关系吧，我去掉一样报错。
![image](https://cloud.githubusercontent.com/assets/17400810/14167068/2d9f171a-f74b-11e5-932d-27a3cc2afcf6.png)

**Comment by xudafeng** [comment]
@holysor 不要使用 `sudo` 安装 node 模块, 先 `sudo chown -R $USER /usr/local`

**Comment by holysor** [comment]
还是出现截图的一样的错误。

**Comment by xudafeng** [comment]
@holysor 先 `sudo uninstall macaca-client -g`, 因为你之前用 sudo装的

**Comment by holysor** [comment]
![image](https://cloud.githubusercontent.com/assets/17400810/14167361/4cb9b5c2-f74d-11e5-9f02-30ebdb0f84fd.png)

**Comment by holysor** [comment]
我卸载后 重新zhi'x执行npm i macaca-client -g 下载成功，
然后执行sudo chown -R $USER /usr/local;
在执行make test-pc，log如图
![image](https://cloud.githubusercontent.com/assets/17400810/14167469/2639a550-f74e-11e5-8247-dc1c207430b1.png)

**Comment by holysor** [comment]
整个下载到make过程我是在macaca-desktop-sample文件夹下完成，

**Comment by holysor** [comment]
@xudafeng  我在根目录下执行成功了

**Comment by xudafeng** [comment]
@holysor :100:

**Comment by holysor** [comment]
@xudafeng 多谢啊，看来主要是sudo问题

**Comment by xudafeng** [comment]
@holysor 文章要细看哦

**Comment by holysor** [comment]
@xudafeng 嗯嗯

**Comment by Solomo-vip** [comment]
platform=android macaca run --server --verbose -d ./macaca-test/macaca-mobile-sample.test.js
>> index.js:64:12 [master] pid:30897 webdriver server start with config:
 { port: 3456,
  ip: '192.168.185.77',
  host: 'jinchengdeMacBook-Pro.local',
  loaded_time: '2016-04-07 15:07:32' }
>> middlewares.js:31:10 [master] pid:30897 base middlewares attached
>> router.js:101:10 [master] pid:30897 router set
>> webdriver sdk launched
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/lib/node_modules/.macaca-client_npminstall/mocha/2.2.4/.bin/mocha ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

我也遇到这个问题，并且已经按照上面的步骤重新执行了，还是这样

**Comment by xudafeng** [comment]
@Solomo-vip 你是执行pc示例吗？

**Comment by Solomo-vip** [comment]
执行android端的，我已经连接了真机，且adb devices
可以找到序列号

**Comment by xudafeng** [comment]
@Solomo-vip 先不用 cnpm，用 npm 装下试试

**Comment by Solomo-vip** [comment]
使用npm果然可行，应该不报这个错误了

**Comment by xudafeng** [comment]
@Solomo-vip :ok_hand:

**Comment by shenggen1987** [comment]
>> index.js:93:12 [master] pid:4592 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '174.3.4.54',
  host: 'shenggen.local',
  loaded_time: '2016-05-10 14:36:02' }
>> middlewares.js:30:10 [master] pid:4592 base middlewares attached
>> router.js:117:10 [master] pid:4592 router set
这是什么意思？？

**Comment by xudafeng** [comment]
```shell
$ sudo chown -R $(whoami) /usr/local
```

**Comment by xudafeng** [comment]
```shell
$ sudo chown -R $(whoami) /usr/local
```

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/issues/32

**Comment by simply-coder** [comment]
MINGW64 /d/test/macaca-test-sample-master
$ macaca run --verbose
>> index.js:17:12 [master] pid:7476 webdriver server start with config:
 { port: 3456,
  verbose: false,
  always: true,
  window: true,
  ip: '10.69.9.158',
  host: 'QIUYANAN',
  loaded_time: '2016-12-14 13:57:20' }
>> middlewares.js:17:10 [master] pid:7476 base middlewares attached
>> router.js:130:10 [master] pid:7476 router set
>> webdriver sdk launched
[ 'D:\\test\\macaca-test-sample-master\\node_modules\\.bin\\mocha',
  'macaca-test',
  '--colors',
  '--verbose' ]
>> D:\test\macaca-test-sample-master\node_modules\.bin\mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

>> Test completed!
