### ISSUE TITLE
adb shell ime set android.unicode.ime/.Utf7ImeService 设置完utf-7 字体输入后，手机键盘无法自动切换

### ISSUE THREAD

**Issue by lemonadam** [alibaba/macaca#80]
问题描述：
adb shell ime set android.unicode.ime/.Utf7ImeService 设置完utf-7 字体输入后，手机再次启动键盘需要手动切到别的输入法才能继续正常使用输入法。
* **Macaca Version**:
 1.0.35
* **Macaca Doctor**:
Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.7

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_11`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/lemon/work/sdk/android-sdk-macosx`
  Platforms is set to `/Users/lemon/work/sdk/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/lemon/work/sdk/android-sdk-macosx/tools/android`

  Installed driver list:

  android: 1.0.13
  ios: 1.0.30
* **Platform**:
android

**Comment by xudafeng** [comment]
@lemonadam 这里没有做恢复，可以考虑实现
