### ISSUE TITLE
被测APP调用麦克风后定位卡顿

### ISSUE THREAD

**Issue by CaiWiKi** [alibaba/macaca#802]
你好，我测试我们APP录音功能的时候，发现一旦开启麦克风macaca服务就会严重卡顿，安卓进行一次元素定位并进行点击操作需要一分多钟，而iOS则两分钟都没有看到request的log 直接超时。检查了手机CPU内存占用并不高，麻烦帮忙看一下，谢谢！

**Comment by SamuelZhaoY** [comment]
https://github.com/macacajs/XCTestWD 请参考问题排查指南进行追踪
