### ISSUE TITLE
Win7安装app-inspector报错，要执行xcode命令？怎么解决求帮忙。

### ISSUE THREAD

**Issue by Panda-Ching** [alibaba/macaca#808]
* **Version**：2.1.2
* **Operate System**：Win7 64
* **Macaca Doctor Logs**:

  macaca-doctor version: 2.0.12

  Node.js checklist:
  node env: C:\nodejs\node.exe
  node version: v8.9.3
  Android checklist:
  openjdk version "1.8.0_152-release"
  OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
  OpenJDK 64-Bit Server VM (build 25.152-b02, mixed mode)
  JAVA version is `1.8`
  JAVA_HOME is set to `D:\Program Files\Android\Android Studio\jre`
  ANDROID_HOME is set to `D:\Program Files\Android\Sdk`
  Platforms is set to `D:\Program Files\Android\Sdk\platforms\android-27`
  ADB tool is set to `D:\Program Files\Android\Sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\Program Files\gradle-4.6`

  Installed driver list:
  android: 2.0.47

命令行输入npm i app-inspector -g报错，错误信息：Error: Command failed: xcodebuild -version
为什么windows系统要执行xcode的命令？一脸懵逼

D:\Program Files (x86)\PowerCmd>npm i app-inspector -g
...(此处省略一万字)
BUILD SUCCESSFUL in 34s
43 actionable tasks: 43 executed

> xctestwd@1.3.27 install C:\nodejs\node_global\node_modules\app-inspector\node_modules\xctestwd
> node ./scripts/install.js

'xcodebuild' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'xcodebuild' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
child_process.js:644
    throw err;
    ^

Error: Command failed: xcodebuild -version
'xcodebuild' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.exports.getXcodeVersion (C:\nodejs\node_global\node_modules\app-inspector\node_modules\macaca-doctor\lib\ios.js:39:38)
    at Object.<anonymous> (C:\nodejs\node_global\node_modules\app-inspector\node_modules\xctestwd\scripts\install.js:62:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
npm ERR! path C:\nodejs\node_global\node_modules\app-inspector\node_modules\async\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall lstat
npm ERR! Error: EPERM: operation not permitted, lstat 'C:\nodejs\node_global\node_modules\app-inspector\node_modules\async\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, lstat 'C:\nodejs\node_global\node_modules\app-inspector\node_modules\async\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, lstat \'C:\\nodejs\\node_global\\node_modules\\app-inspector\\node_modules\\async\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'lstat',
npm ERR!   path: 'C:\\nodejs\\node_global\\node_modules\\app-inspector\\node_modules\\async\\node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\nodejs\node_cache\_logs\2018-04-16T22_57_19_301Z-debug.log

**Comment by baozhida** [comment]
一样的问题    v2.0.15

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/commit/3af2cdca7c549037fc17cc46a267ee971270fda1
