### ISSUE TITLE
关于ios demo 中webview（百度浏览器的空间定位定位不到的问题）

### ISSUE THREAD

**Issue by lemonadam** [alibaba/macaca#81]
* **问题描述**:
ios的脚本在执行百度那个页面的时候，去点击搜索框。却无法定位到对应搜索框的元素。我用浏览器定位了一下元素id 没有问题。报错信息：Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. 但是前面的那个webview 页面关于.elementById('pushView') 却是没有问题的。
* **Macaca Version**:
1.0.35
* **Macaca Doctor**:
Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.7

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_11`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/lemon/work/sdk/android-sdk-macosx`
  Platforms is set to `/Users/lemon/work/sdk/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/lemon/work/sdk/android-sdk-macosx/tools/android`

  Installed driver list:

  android: 1.0.13
  ios: 1.0.30

* **Platform**:
ios

**Comment by xudafeng** [comment]
@lemonadam `cat /etc/hosts` 贴下你的host绑定

**Comment by lemonadam** [comment]
127.0.0.1       localhost
127.0.0.1 activate.adobe.com
127.0.0.1 ereg.adobe.com
127.0.0.1 hlrcv.stage.adobe.com
127.0.0.1 lm.licenses.adobe.com
127.0.0.1 lmlicenses.wip4.adobe.com
127.0.0.1 na1r.services.adobe.com
127.0.0.1 na2m-pr.licenses.adobe.com
127.0.0.1 practivate.adobe.com
127.0.0.1 wip.adobe.com

**Comment by xudafeng** [comment]
@lemonadam 

加上这些
```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by lemonadam** [comment]
@xudafeng 
加入对应映射之后好了
BTW，百度的搜索按钮 id 名字换了 ，现在叫 ：index-bn
原始脚本里是 bn
顺便想问下 .elementById('index-bn')  内容是否支持正则匹配。
我这样写不行：.elementById('(?i).*?bn')

**Comment by xudafeng** [comment]
@lemonadam 看API文档
