### ISSUE TITLE
macaca,iOS虚拟机测试，app为ipa时无法安装

### ISSUE THREAD

**Issue by boyxiaohua** [alibaba/macaca#812]
测试官网的bootstrap.zip是OK的，换成ipa包则不行

>> get /Users/sheep/.macaca-temp/xxxx_build_268_390.ipa from cache
>> sha:81fea0830e1420092c65b7252a6d2972
>> helper.js:176:12 [master] pid:4970 Using local app form /Users/sheep/.macaca-temp/xxxx_build_268_390.ipa
>> macaca-ios.js:220:10 [master] pid:4970 Get available devices [{"name":"iPhone 8","udid":"454BF3C3-A9A3-4B43-B2E5-660993489C1B","state":"Shutdown","available":true,"runtime":"iOS 11.3"},{"name":"iPhone 8 Plus","udid":"54A4B3D0-72A4-40CF-8363-F2B20B91F9A5","state":"Shutdown","available":true,"runtime":"iOS 11.3"},{"name":"iPhone SE","udid":"4B043D8B-F392-458E-8CEB-1DDD2AF85D51","state":"Shutdown","available":true,"runtime":"iOS 11.3"},{"name":"iPhone X","udid":"83091EDC-F7F7-45E9-BD7E-06A1A87A19C7","state":"Shutdown","available":true,"runtime":"iOS 11.3"},{"name":"iPad Air","udid":"67DDB1EA-30DE-4A0D-AB2A-43938F68BEDB","state":"Shutdown","available":true,"runtime":"iOS 11.3"},{"name":"iPad Air 2","udid":"05C4F5C4-AAE6-42FF-AA17-2AFE82805A7A","state":"Shutdown","available":true,"runtime":"iOS 11.3"},{"name":"Apple TV","udid":"C99ACF1B-7B63-4032-BF7E-8707E20FA60A","state":"Shutdown","available":true,"runtime":"tvOS 11.3"},{"name":"Apple TV 4K","udid":"DB846F78-12F0-4EF2-96FD-9D5BA26E4047","state":"Shutdown","available":true,"runtime":"tvOS 11.3"},{"name":"Apple Watch - 38mm","udid":"7FDC852A-3BEB-48DA-A5D2-DE5509DC8824","state":"Shutdown","available":true,"runtime":"watchOS 4.3"},{"name":"Apple Watch - 42mm","udid":"CB6C0697-E1D7-4936-97FC-E3AC53580403","state":"Shutdown","available":true,"runtime":"watchOS 4.3"},{"name":"Apple Watch Series 2 - 38mm","udid":"F3453C68-71A0-4C3B-A068-E9256859C264","state":"Shutdown","available":true,"runtime":"watchOS 4.3"},{"name":"Apple Watch Series 2 - 42mm","udid":"4DC293C7-CCC4-49A7-8C0B-AF46AE5258AB","state":"Shutdown","available":true,"runtime":"watchOS 4.3"},{"name":"Apple Watch Series 3 - 38mm","udid":"FC6A39E9-E1D8-4C0C-B327-443BE960AA84","state":"Shutdown","available":true,"runtime":"watchOS 4.3"},{"name":"Apple Watch Series 3 - 42mm","udid":"A45C9879-B490-4209-A27F-D6EC42740713","state":"Shutdown","available":true,"runtime":"watchOS 4.3"}]
(node:4970) UnhandledPromiseRejectionWarning: Error: Command failed: /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" "/Users/sheep/.macaca-temp/xxxx_build_268_390.ipa/Info.plist"
Print: Entry, "CFBundleIdentifier", Does Not Exist

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
(node:4970) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)

**Comment by upengfei** [comment]
这个问题怎么解决？

**Comment by SamuelZhaoY** [comment]
@upengfei 声明.app 地址
