### ISSUE TITLE
真机报错：this.device.installUntilReady is not a function

### ISSUE THREAD

**Issue by wang111588** [alibaba/macaca#814]
iOS10 系统 ，this.device.installUntilReady is not a function
把 macaca-ios.js 文件中的所有    yield this.device.installUntilReady(app, this.bundleId); 
替换成       yield this.device.install(app);  
能跑起来。

app-inspector -u 真机没有问题。

****************
macaca doctor

  macaca-doctor version: 2.0.13

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v9.6.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`
  carthage is installed, version: 0.27.0

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  android: 2.0.46 [out-of-date]
  electron: 1.1.19
  ios: 2.0.30

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-ios/commit/7507f155fd3822b833d6b461ee7add1e1b38cbb2
