### ISSUE TITLE
iOS端真机无法运行

### ISSUE THREAD

**Issue by iwuxiekeji** [alibaba/macaca#82]
模拟器ok

* **Macaca Version**:

* **Macaca Doctor**:
```
  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.5

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_91`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/opt/android-sdk`
  Platforms is set to `/usr/local/opt/android-sdk/platforms/android-24`
  Android tools is set to `/usr/local/opt/android-sdk/tools/android`

  Installed driver list:

  ios: 1.0.30



```
* **Platform**:

```
>> xctest-client.js:206:14 [master] pid:1710 2016-07-07 14:15:32.864 xcodebuild[1717:43169] [MT] IDETestOperationsObserverDebug: (FD121006-3BCA-455D-AD14-5CE701E3520C) Beginning test session FD121006-3BCA-455D-AD14-5CE701E3520C with Xcode 7D1014 on target <DVTiOSDevice: 0x7fef536bd7e0> {
		deviceSerialNumber:         DNRPQX46G5MN
		identifier:                 6c3090705d45719ecf542cad940d19152cf78654
		deviceClass:                iPhone
		deviceName:                 “autotest”的 iPhone
		deviceIdentifier:           6c3090705d45719ecf542cad940d19152cf78654
		productVersion:             9.3.2
		buildVersion:               13F69
		deviceSoftwareVersion:      9.3.2 (13F69)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12683317248
		deviceAvailableCapacity:    299610112
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fef5703c6c0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.2 (13F69))

>> xctest-client.js:206:14 [master] pid:1710 2016-07-07 14:15:32.865 xcodebuild[1717:43215]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/autotest/Library/Developer/Xcode/DerivedData/WebDriverAgent-dlsmcimxoimufvawqqakamzcsjum/Logs/Test/6E00228B-F1CF-4470-A46D-F00EA877D80C/Session-2016-07-07_14:15:32-eFlUOm.log

>> xctest-client.js:206:14 [master] pid:1710 ** TEST FAILED **


>> xctest-client.js:214:14 [master] pid:1710 xctest client exit with code: 65, signal: null
```

**Comment by xudafeng** [comment]
@iwuxiekeji 32位的真机？

**Comment by iwuxiekeji** [comment]
iphone6，64位

**Comment by xudafeng** [comment]
@iwuxiekeji webdriveragent有build成功吗？

**Comment by iwuxiekeji** [comment]
@xudafeng 没有成功，但是xcode是可以build成功的

**Comment by BonnieShi** [comment]
@iwuxiekeji  有进展么，我也碰到同样的问题

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/135

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5804

**Comment by AlexJinsin** [comment]
2017-01-10 11:26:24.622 XCTRunner[273:152911] Running tests...
2017-01-10 11:26:24.752 XCTRunner[273:152911] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2017-01-10 11:26:24.752 XCTRunner[273:152911] (dlopen_preflight(/var/containers/Bundle/Application/CBF7DDC3-D552-459B-96A5-F6DB366E8041/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/Peertalk.framework/Peertalk
  Referenced from: /private/var/containers/Bundle/Application/CBF7DDC3-D552-459B-96A5-F6DB366E8041/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/CBF7DDC3-D552-459B-96A5-F6DB366E8041/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/Peertalk.framework/Peertalk: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/CBF7DDC3-D552-459B-96A5-F6DB366E8041/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/Peertalk.framework/Peertalk')

这个怎么办 楼主有没有经验
