### ISSUE TITLE
调用getProperty()返回404，unknow command

### ISSUE THREAD

**Issue by megolee** [alibaba/macaca#820]
* **Macaca Version**: 2.1.2

* **Macaca Doctor Logs**:

* **Operate System**: Mac 10.13.4

* **Programming Language**: NodeJs

Web元素 `<img src="https://xxx.cn/blog/iconset-reading-selected_1.png">`

定位到元素后调用.getProperty('src')

日志返回 proxy.js:59:16 [master] pid:1509 Got response with status 404: "unknown command: session/548208aad25e80180d1398c3925f3e46/element/0.46687237418930994-7/property/src"

**Comment by zhangyuheng** [comment]
看看

**Comment by xudafeng** [comment]
服务端没有这个路由

**Comment by xudafeng** [comment]
参考这个例子

https://github.com/macaca-sample/antd-sample/blob/master/test/new-page.test.js#L56-L59
