### ISSUE TITLE
按官方示例修改启动Android程序报错：Send Error Respone to Client: TypeError: _.trunc is not a function

### ISSUE THREAD

**Issue by xinac0421** [alibaba/macaca#826]
* **Macaca Version**:
2.1.2

* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.0.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.4
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/wangxin/Library/Android/sdk`
  Platforms is set to `/Users/wangxin/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/wangxin/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  android: 2.0.47
  electron: 2.0.3
  ios: 2.0.34

* **Operate System**:
MAC 10.13.4 (17E199)

* **Programming Language**:

源码很简单，直接在官方示例上改的，运行后能启动手机里自己的安卓APP，但启动好后就报错：
>> UIAutomatorWD http server ready
>> macaca-android.js:303:10 [master] pid:42531 start app with: {"package":"com.innotek.goodparking"}
>> responseHandler.js:54:12 [master] pid:42531 Send Error Respone to Client: TypeError: _.trunc is not a function
>> responseHandler.js:60:14 [master] pid:42531 TypeError: _.trunc is not a function
    at Object.module.exports (/Users/wangxin/Documents/CODE/Macaca/CT3_APP/node_modules/webdriver-server/lib/server/responseHandler.js:45:23)
    at module.exports.next (<anonymous>)
    at onFulfilled (/Users/wangxin/Documents/CODE/Macaca/CT3_APP/node_modules/co/index.js:65:19)

  TypeError: _.trunc is not a function
      at Object.module.exports (/Users/wangxin/Documents/CODE/Macaca/CT3_APP/node_modules/webdriver-server/lib/server/responseHandler.js:45:23)
      at module.exports.next (<anonymous>)
      at onFulfilled (/Users/wangxin/Documents/CODE/Macaca/CT3_APP/node_modules/co/index.js:65:19)

刚接触这些，不知道什么问题，按错误提示查看.../node_modules/webdriver-server/lib/server/responseHandler.js:45:23相关代码：
![image](https://user-images.githubusercontent.com/3013052/41235564-9b7c6ece-6dc1-11e8-81c5-6035ce6a8cf3.png)

按Google上找的可能原因把 _.trunc改成_.truncate后，试了下可以正常启动了。
但不太明白，完全用官方的示例是没问题的，改成公司自己的APP就报这个错

**Comment by xudafeng** [comment]
pls reinstall the driver
