### ISSUE TITLE
macaca测试web端，加载cookie报错

### ISSUE THREAD

**Issue by wynanwong** [alibaba/macaca#827]
* **Macaca Version**:
2.1.2
* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v8.11.2

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.3.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/wn/Library/Android/sdk`
  Platforms is set to `/Users/wn/Library/Android/sdk/platforms/android-26`
  ADB tool is set to `/Users/wn/Library/Android/sdk/platform-tools/adb`
  Not accepted Android SDK license agreements
  gradle is installed, version: 3.5

  Installed driver list:

  android: 2.0.46 [out-of-date]
  chrome: 1.0.7
  electron: 1.1.19 [out-of-date]
  ios: 2.0.34
* **Operate System**:
Mac 10.13.14
* **Programming Language**:
Java

通过java api接口，调用setCookie方法时，报如下错误：
java.lang.Exception: An unknown server-side error occurred while processing the command.

测试代码如下：
        driver.get("https://xxx/xx/");
        String json = "{\"sessionid\":\xxxx\",\"path\":\"/\",\"domain\":\".xxx.com\"}";
        JSONObject jsonObject = JSONObject.parseObject(json);
        driver.setCookie(jsonObject);

macaca server的log日志如下：
>> index.js:18:12 [master] pid:4652 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '172.16.11.93',
  host: 'wndeMacBook-Pro.local',
  loaded_time: '2018-06-12 15:35:00' }
>> middlewares.js:17:10 [master] pid:4652 base middlewares attached
>> router.js:133:10 [master] pid:4652 router set
>> Macaca server started
>> responseHandler.js:11:12 [master] pid:4652 Recieve HTTP Request from Client[2018-06-12 15:35:09]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"browserName":"chrome","platformName":"desktop"}}
>> session.js:58:10 [master] pid:4652 Creating session, sessionId: b874debb-ec8c-44b4-8836-59ab7d7d07aa.
>> use default chromedriver version!
>> chromedriver bin path: /usr/local/lib/node_modules/macaca-chrome/node_modules/macaca-chromedriver/exec/chromedriver2.33
>> Starting ChromeDriver 2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:51:14 [master] pid:4652 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body: 
>> proxy.js:59:16 [master] pid:4652 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.13.4\"}}}"
>> proxy.js:51:14 [master] pid:4652 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"browserName":"chrome","platformName":"desktop"}}
>> proxy.js:59:16 [master] pid:4652 Got response with status 200: {"sessionId":"9f8137aa3b236510ab7fa7a52e8be76c","status":0,"value":{"acceptInsecureCerts":false,"acceptSslCerts":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName"...
>> chromedriver ready with: {"sessionId":null,"status":0,"value":{"acceptInsecureCerts":false,"acceptSslCerts":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85)","userDataDir":"/var/folders/07/zd3fktb93x38fkd_rn9yp9sc0000gn/T/.org.chromium.Chromium.zkXTCY"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platform":"Mac OS X","rotatable":false,"setWindowRect":true,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"67.0.3396.79","webStorageEnabled":true}}
>> responseHandler.js:49:14 [master] pid:4652 Send HTTP Respone to Client[2018-06-12 15:35:12]: {"sessionId":"b874debb-ec8c-44b4-8836-59ab7d7d07aa","status":0,"value":"{\"browserName\":\"chrome\",\"platformName\":\"desktop\"}"}
>> responseHandler.js:11:12 [master] pid:4652 Recieve HTTP Request from Client[2018-06-12 15:35:12]: method: POST url: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa/url, jsonBody: {"url":"https://dev.gizwits.com"}
>> proxy.js:51:14 [master] pid:4652 Proxy: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa/url:POST to http://localhost:9515/wd/hub/session/9f8137aa3b236510ab7fa7a52e8be76c/url:POST with body: {"url":"https://dev.gizwits.com"}
>> proxy.js:59:16 [master] pid:4652 Got response with status 200: {"sessionId":"9f8137aa3b236510ab7fa7a52e8be76c","status":0,"value":null}
>> session.js:120:14 [master] pid:4652 Send HTTP Respone to Client[2018-06-12 15:35:19]: {"sessionId":"b874debb-ec8c-44b4-8836-59ab7d7d07aa","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:4652 Recieve HTTP Request from Client[2018-06-12 15:35:19]: method: POST url: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa/url, jsonBody: {"url":"https://dev.gizwits.com/zh-cn/developer/customize"}
>> proxy.js:51:14 [master] pid:4652 Proxy: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa/url:POST to http://localhost:9515/wd/hub/session/9f8137aa3b236510ab7fa7a52e8be76c/url:POST with body: {"url":"https://dev.gizwits.com/zh-cn/developer/customize"}
>> proxy.js:59:16 [master] pid:4652 Got response with status 200: {"sessionId":"9f8137aa3b236510ab7fa7a52e8be76c","status":0,"value":null}
>> session.js:120:14 [master] pid:4652 Send HTTP Respone to Client[2018-06-12 15:35:20]: {"sessionId":"b874debb-ec8c-44b4-8836-59ab7d7d07aa","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:4652 Recieve HTTP Request from Client[2018-06-12 15:35:20]: method: POST url: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa/url, jsonBody: {"url":"https://dev.gizwits.com/zh-cn/developer/customize"}
>> proxy.js:51:14 [master] pid:4652 Proxy: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa/url:POST to http://localhost:9515/wd/hub/session/9f8137aa3b236510ab7fa7a52e8be76c/url:POST with body: {"url":"https://dev.gizwits.com/zh-cn/developer/customize"}
>> proxy.js:59:16 [master] pid:4652 Got response with status 200: {"sessionId":"9f8137aa3b236510ab7fa7a52e8be76c","status":0,"value":null}
>> session.js:120:14 [master] pid:4652 Send HTTP Respone to Client[2018-06-12 15:35:20]: {"sessionId":"b874debb-ec8c-44b4-8836-59ab7d7d07aa","status":0,"value":null}
>> responseHandler.js:11:12 [master] pid:4652 Recieve HTTP Request from Client[2018-06-12 15:35:20]: method: POST url: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa/cookie, jsonBody: {"path":"/","domain":".xxx.com","sessionid":"xxxxxxx"}
>> proxy.js:51:14 [master] pid:4652 Proxy: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa/cookie:POST to http://localhost:9515/wd/hub/session/9f8137aa3b236510ab7fa7a52e8be76c/cookie:POST with body: {"path":"/","domain":".xxx.com","sessionid":"xxxxx"}
>> proxy.js:59:16 [master] pid:4652 Got response with status 200: {"sessionId":"9f8137aa3b236510ab7fa7a52e8be76c","status":13,"value":{"message":"unknown error: missing 'cookie'\n  (Session info: chrome=67.0.3396.79)\n  (Driver info: chromedriver=2.37.544337 (8c0...
>> session.js:120:14 [master] pid:4652 Send HTTP Respone to Client[2018-06-12 15:35:20]: {"sessionId":"b874debb-ec8c-44b4-8836-59ab7d7d07aa","status":13,"value":"{\"message\":\"unknown error: missing 'cookie'\\n  (Session info: chrome=67.0.3396.79)\\n  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.13.4 x86_64)\"}"}
>> responseHandler.js:11:12 [master] pid:4652 Recieve HTTP Request from Client[2018-06-12 15:35:20]: method: DELETE url: /wd/hub/session/b874debb-ec8c-44b4-8836-59ab7d7d07aa, jsonBody: {}
>> macaca-chromedriver.js:168:18 [master] pid:4652 chromedriver exit with code: null, signal: SIGTERM
>> session.js:91:12 [master] pid:4652 Delete session, sessionId: b874debb-ec8c-44b4-8836-59ab7d7d07aa
>> responseHandler.js:49:14 [master] pid:4652 Send HTTP Respone to Client[2018-06-12 15:35:20]: {"sessionId":"b874debb-ec8c-44b4-8836-59ab7d7d07aa","status":0}

**Comment by xudafeng** [comment]
更新最新驱动版本
