### ISSUE TITLE
【iOS】点击Home键driver.key("\uE105")后，再点击返回应用，无法点击应用内控件（提示can't find the element）

### ISSUE THREAD

**Issue by grubby2013** [alibaba/macaca#830]
* **Macaca Version**:
macaca-ios:2.0.34
macaca-cli:2.1.2
* **Macaca Doctor Logs**:

* **Operate System**:
10.13.4
* **Programming Language**:
java

**Comment by SamuelZhaoY** [comment]
新版 XCTestWD 已优化
