### ISSUE TITLE
【iOS】iOS端有切换横竖屏的方法吗

### ISSUE THREAD

**Issue by grubby2013** [alibaba/macaca#831]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by SamuelZhaoY** [comment]
目前尚未支持，可以参考此链接添加 https://stackoverflow.com/questions/35634182/how-can-you-change-orientation-for-testing-on-xctest-for-ios 欢迎PR
