### ISSUE TITLE
你好，自己研究了好久如何模拟断网的情况，没找到答案，不知道大家都是怎么解决的

### ISSUE THREAD

**Issue by liuxu263** [alibaba/macaca#834]
* **Macaca Version**:2.1.2

* **Macaca Doctor Logs**:

* **Operate System**:IOs

* **Programming Language**:NodeJs

**Comment by liuxu263** [comment]
想模拟一下断网的情况，不知道大家是怎么处理的

**Comment by paradite** [comment]
可以基于这个包的原理反向写个mock：
https://github.com/sindresorhus/is-online/blob/master/index.js
或者直接用这个包，然后测试的时候自己mock一下。
