### ISSUE TITLE
app-inspector使用命令行无法安装以及WebDriverAgent.xcodeproj使用苹果私人账户无法通过验证

### ISSUE THREAD

**Issue by lynnyoo** [alibaba/macaca#837]
* **Macaca Version**:
2.1.3
* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.14

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.6.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 9.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home`
  ANDROID_HOME is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk`
  Platforms is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk/platforms/android-19`
  ADB tool is set to `/Applications/adt-bundle-mac-x86_64-20131030/sdk/platform-tools/adb`
  Not accepted Android SDK license agreements
  gradle require version 3.3 and above

  Installed driver list:

  android: 2.0.48
  chrome: 1.0.6 [out-of-date]
  electron: 1.1.11 [out-of-date]
  ios: 2.0.24 [out-of-date]
* **Operate System**:
Mac OS 10.13.6
Xcode 9.3
* **Programming Language**:
java

2017年曾使用过macaca，现在因为项目原因重新使用。
更新了macaca之后发现有两个问题：
问题一：app-inspector无法使用命令行安装，log如下：
npm i -g app-inspector@2.0.19
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'spdx-license-ids/deprecated'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2018-07-25T07_44_36_163Z-debug.log

问题二：使用Xcode进行重签名时，个人账号无法通过验证
我记得之前使用macaca的时候，User账号还是可以通过签名的。

请问这两个问题需要什么操作可以解决，麻烦了

**Comment by lynnyoo** [comment]
第一个问题解决了，是因为node版本过高，降版本10-》8.0就可以使用命令行了，
只是想请问一下，私人苹果账号不能重新编译XCTestWD了吗？

**Comment by SamuelZhaoY** [comment]
@lynnyoo 检查你的个人证书，xctestwd 一直可以适配个人证书并完成编译 

![screen shot 2018-08-18 at 9 25 30 am](https://user-images.githubusercontent.com/8198256/44294384-afb78900-a2c8-11e8-874b-9912d55b6d3c.png)
