### ISSUE TITLE
Mouse action Right click in macaca?

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#846]
* **Macaca Version**:
2.1.2

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

I have a use case of right click and do copy/paste in macaca. Is that possible to do context click on an element?
please help.

**Comment by mpreethi90** [comment]
@xudafeng Can you please help looking into this?

**Comment by mpreethi90** [comment]
I managed to fix this problem . The purpose of my right click is to copy/paste content. I tried a work around of getting the html from DOM and used something like `.execute(window.frames[0].document.body.innerHTML =)` to accomplish this.

Closing this. Thanks @xudafeng  for the support through wechat!

**Comment by xudafeng** [comment]
@mpreethi90 great
