### ISSUE TITLE
Macaca-python iOS 示例运行时一直在 Retry connecting server... macaca server 命令行一直在Read simulator log at: /var/folders/_3/qr6dv7fn5lxd79qt9lfp96ch0000gn/T/com.apple.dt.XCTest/IDETestRunSession-1C268304-48B1-4C5E-A1AA-AACA9449D3E3/XCTestWDUITests-7A6220A4-872D-4DC0-8752-54270664D70A/StandardOutputAndStandardError.txt

### ISSUE THREAD

**Issue by zhangwenye** [alibaba/macaca#847]
* **Macaca Version**:
2.1.3
* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:
python

Macaca-python iOS 示例运行时一直在 Retry connecting server... macaca server 命令行一直在Read simulator log at: /var/folders/_3/qr6dv7fn5lxd79qt9lfp96ch0000gn/T/com.apple.dt.XCTest/IDETestRunSession-1C268304-48B1-4C5E-A1AA-AACA9449D3E3/XCTestWDUITests-7A6220A4-872D-4DC0-8752-54270664D70A/StandardOutputAndStandardError.txt
![image](https://user-images.githubusercontent.com/27949984/44843740-91b03800-ac7b-11e8-86ef-ef3d36a07aa9.png)
![image](https://user-images.githubusercontent.com/27949984/44848571-e3f85580-ac89-11e8-8f62-fe520d81dc0b.png)

**Comment by saling** [comment]
这个问题有解决方法么？同样的情况

**Comment by xudafeng** [comment]
@saling 建议升级操作系统到最新，重装驱动
