### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by pepsicoffee** [alibaba/macaca#851]
* **Macaca Version**:
macaca-doctor version: 2.0.14
* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.14

 Node.js checklist:

 node env: C:\Java\nodejs\node.exe
 node version: v8.12.0

 Android checklist:

 JAVA version is `1.8`
 JAVA_HOME is set to `C:\Java\jdk1.8.0_91`
 ANDROID_HOME is set to `D:\DevSoft\android-sdk_r24.4.1`
 Platforms is set to `D:\DevSoft\android-sdk_r24.4.1\platforms\android-25`
 ADB tool is set to `D:\DevSoft\android-sdk_r24.4.1\platform-tools\adb.exe`
 GRADLE_HOME is set to `C:\Java\gradle-4.10`

 Installed driver list:

 android: 2.0.48
 chrome: 1.0.7
* **Operate System**:
windows7
* **Programming Language**:
nodejs

c:\Java\nodejs\node-global\node_modules>cnpm install macaca-android -g
Downloading macaca-android to c:\Java\nodejs\node-global\node_modules\macaca-and
roid_tmp
Copying c:\Java\nodejs\node-global\node_modules\macaca-android_tmp\_macaca-andro
id@2.0.48@macaca-android to c:\Java\nodejs\node-global\node_modules\macaca-andro
id
Installing macaca-android's dependencies to c:\Java\nodejs\node-global\node_modu
les\macaca-android/node_modules
[1/10] webdriver-dfn-error-code@~1.0.1 installed at node_modules\_webdriver-dfn-
error-code@1.0.4@webdriver-dfn-error-code
[2/10] driver-base@~0.1.0 installed at node_modules\_driver-base@0.1.4@driver-ba
se
[3/10] macaca-utils@^1.0.0 installed at node_modules\_macaca-utils@1.0.1@macaca-
utils
[4/10] temp@~0.8.3 installed at node_modules\_temp@0.8.3@temp
[5/10] xml2map@^1.0.2 installed at node_modules\_xml2map@1.0.2@xml2map
[6/10] uiautomatorwd@~1.0.54 installed at node_modules\_uiautomatorwd@1.0.60@uia
utomatorwd
[7/10] unlock-apk@~1.0.3 installed at node_modules\_unlock-apk@1.0.8@unlock-apk
[8/10] xlogger@~1.0.0 installed at node_modules\_xlogger@1.0.6@xlogger
[9/10] macaca-chromedriver@~1.0.1 installed at node_modules\_macaca-chromedriver
@1.0.44@macaca-chromedriver
[10/10] macaca-adb@~1.0.3 installed at node_modules\_macaca-adb@1.0.34@macaca-ad
b
execute post install 3 scripts...
[1/3] scripts.install uiautomatorwd@~1.0.54 run "node ./scripts/build.js"
(node:14948) UnhandledPromiseRejectionWarning: ,,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not download fastjson.jar (com.alibaba:fastjson:1.2.31)
   > Could not get resource 'https://jcenter.bintray.com/com/alibaba/fastjson/1.
2.31/fastjson-1.2.31.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/alibaba/fastjson/1.2.31/f
astjson-1.2.31.jar'.
         > Connect to d29vzk4ow07wi7.cloudfront.net:443 [d29vzk4ow07wi7.cloudfro
nt.net/13.35.103.48, d29vzk4ow07wi7.cloudfront.net/13.35.103.62, d29vzk4ow07wi7.
cloudfront.net/13.35.103.11, d29vzk4ow07wi7.cloudfront.net/13.35.103.174] failed
: Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 3s

(node:14948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 2)
(node:14948) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
[1/3] scripts.install uiautomatorwd@~1.0.54 finished in 2m
[2/3] scripts.install unlock-apk@~1.0.3 run "node ./script/build.js"
[2/3] scripts.install unlock-apk@~1.0.3 finished in 5s
[3/3] scripts.install macaca-chromedriver@~1.0.1 run "node ./bin/macaca-chromedr
iver install"
>> version: 2.33
>> chromedriver cdn url: https://cdn.npm.taobao.org/dist/chromedriver/2.33/chrom
edriver_win32.zip
>> chromedriver local in c:\Java\nodejs\node-global\node_modules\macaca-android\
node_modules\_macaca-chromedriver@1.0.44@macaca-chromedriver\exec\chromedriver2.
33.exe
[3/3] scripts.install macaca-chromedriver@~1.0.1 finished in 3s
deprecate macaca-chromedriver@1.0.44 › request@2.69.0 › node-uuid@~1.4.7 Use uui
d module instead
deprecate macaca-chromedriver@1.0.44 › request@2.69.0 › tough-cookie@~2.2.0 ReDo
S vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
deprecate macaca-chromedriver@1.0.44 › request@2.69.0 › hawk@3.1.3 › hoek@2.x.x
The major version is no longer supported. Please update to 4.x or newer
Recently updated (since 2018-09-11): 1 packages (detail see file c:\Java\nodejs\
node-global\node_modules\macaca-android\node_modules\.recently_updates.txt)
  2018-09-13
    → xlogger@1.0.6 › xutil@1.0.11 › lodash@^4.17.4(4.17.11) (02:32:16)
All packages installed (157 packages installed from npm registry, used 2m(networ
k 3s), speed 1.43MB/s, json 140(994.56kB), tarball 3.37MB)

**Comment by quxiaozha** [comment]
pls try to change the repositories in build.gradle 
https://www.cnblogs.com/anylemons/p/7667677.html
