### ISSUE TITLE
UIRecorder录制iOS脚本时报错：手机打开失败，请检查macaca是否配置正确

### ISSUE THREAD

**Issue by 1214503056** [alibaba/macaca#855]
iOS模拟器有正常安装app并启动。chrome打开后一直转圈，无法同步到模拟器的画面。安卓是可以正常录制回放哒。
![image](https://user-images.githubusercontent.com/23491977/46142178-ad155f80-c288-11e8-9c76-4aa9b526624a.png)

![image](https://user-images.githubusercontent.com/23491977/46142190-bacae500-c288-11e8-9239-4d48d5334bee.png)

[StandardOutputAndStandardError.txt](https://github.com/alibaba/macaca/files/2423796/StandardOutputAndStandardError.txt)

* **Macaca Version**:2.1.3

* **Macaca Doctor Logs**: 
  macaca-doctor version: 2.0.15
  Node.js checklist:

  node env: /Users/devops/.nvm/versions/node/v8.9.4/bin/node
  node version: v8.9.4

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2347.
  xcodebuild version: 9.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/devops/Library/Android/sdk`
  Platforms is set to `/Users/devops/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/devops/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 4.1

  Installed driver list:

  android: 2.0.48
  chrome: 1.0.7
  electron: 2.0.3
  ios: 2.0.34

* **Operate System**:MacOS 10.12.6

* **Programming Language**:录制，没有写脚本

**Comment by zhangyuheng** [comment]
看看

**Comment by 1214503056** [comment]
macaca宝宝们帮忙安排解决一下哦，在线等～
