### ISSUE TITLE
提供Java语言客户端绑定

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#86]

**Comment by codeskyblue** [comment]
我Python党表示不服

**Comment by tt33025515** [comment]
java党表示炒鸡开森

**Comment by xudafeng** [comment]
@codeskyblue Py 后续一定支持，先做Java的

**Comment by xudafeng** [comment]
https://github.com/macacajs/wd.java

邀请内测

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5719

**Comment by xudafeng** [comment]
http://macacajs.github.io/macaca/java.html
