### ISSUE TITLE
Macaca coverage for stand alone test repo

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#860]
Hi,
 I would like to implement code coverage/function/module coverage to my web app and I use macaca for test automation. I was wondering if macaca coverage still works as all our tests are in an entirely separate repo and nothing to do with the webapp repo. 
For example, how do you measure coverage for https://github.com/macaca-sample/sample-nodejs

**Comment by xudafeng** [comment]
https://github.com/macacajs/awesome-macaca#coverage
