### ISSUE TITLE
xctest client exit with code: 65, signal: null

### ISSUE THREAD

**Issue by Opencil** [alibaba/macaca#865]
* **Macaca Version**:
2.1.3

* **Macaca Doctor Logs**:

  macaca-doctor version: 2.0.15

  Network checklist:

  Error, please set hosts: ::1 localhost

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.2.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
TypeError: Invalid Version: 9.4.1.0
    at new SemVer (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:312:11)
    at compare (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:585:10)
    at Function.lt (/usr/local/lib/node_modules/macaca-cli/node_modules/semver/semver.js:619:10)
    at Object.exports.xcodeBuild (/usr/local/lib/node_modules/macaca-cli/node_modules/macaca-doctor/lib/ios.js:56:16)
    at exports.xcodeBuild.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Xcode is uninstalled
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `9`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.35

* **Operate System**:
macOS High Sierra 10.13.5

* **Programming Language**:

[xctest不能启动日志.txt](https://github.com/alibaba/macaca/files/2517295/xctest.txt)

**Comment by SirCYong** [comment]
macaca-doctor version: 2.0.16


  Node.js checklist:

  node env: /usr/local/opt/node@8/bin/node
  node version: v8.15.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home`
  ANDROID_HOME is set to `/usr/local/android-sdk-macosx`
  Platforms is set to `/usr/local/android-sdk-macosx/platforms/android-28`
  ADB tool is set to `/usr/local/android-sdk-macosx/platform-tools/adb`
  Not accepted Android SDK license agreements
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.35
  location: /usr/local/lib/node_modules/macaca-ios
Why is it always code 65？？？
![image](https://user-images.githubusercontent.com/22674868/54184542-de55b500-44e1-11e9-8028-cd9d315a8864.png)

**Comment by ShenYj** [comment]
I get the 'Error, please set hosts: ::1 localhost' , and without other error, I just wanna test iOS/Android , I have to do somthing with this message?
