### ISSUE TITLE
pc桌面版基于electronjs的桌面版应用UI自动化鼠标右键操作无法模拟

### ISSUE THREAD

**Issue by joweywen** [alibaba/macaca#867]
求助，pc桌面版基于electronjs的桌面版应用的UI页面中，需要使用到鼠标右键的操作，试问鼠标右键的模拟操作macaca如何实现呢，api中未发现，借问求分享哦

**Comment by xudafeng** [comment]
目前不支持右键

**Comment by joweywen** [comment]
> 目前不支持右键

期待后期的更新支持此公共方法呢哦

**Comment by zhangyy0715** [comment]
请问现在还是不支持electron桌面版应用的右键吗？@xudafeng

**Comment by xudafeng** [comment]
This is the translated issue comment: @zhangyy0715

<hr/>

I ask now or right-electron desktop applications do not support it? @xudafeng
