### ISSUE TITLE
安卓真机手势密码操作，服务端报错

### ISSUE THREAD

**Issue by LayTonQ** [alibaba/macaca#868]
* **Macaca Version**: 
  2.1.5
* **Macaca Doctor Logs**:
  macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: C:\worksoft\node-v10.4.1-win-x64\node.exe
  node version: v10.4.1

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\Program Files (x86)\Java\jdk1.8.0_91`
  ANDROID_HOME is set to `E:\worksoft\android-sdk-windows`
  Platforms is set to `E:\worksoft\android-sdk-windows\platforms\android-28`
  ADB tool is set to `E:\worksoft\android-sdk-windows\platform-tools\adb.exe`
  Not accepted Android SDK license agreements
  GRADLE_HOME is set to `E:\worksoft\gradle-4.8`

  Installed driver list:

  android: 2.0.48
* **Operate System**:
  win10 32位
* **Programming Language**:
  JAVA

JAVA执行touch 手势密码命令时，服务端报错
    Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
具体JAVA代码和服务端日志如下
![java](https://user-images.githubusercontent.com/37096930/48115440-dc62b780-e29d-11e8-90d0-255fb661dd54.jpg)
![cmd](https://user-images.githubusercontent.com/37096930/48115469-f603ff00-e29d-11e8-9fa7-185ea6f6711b.jpg)

**Comment by houseshi** [comment]
参考这个数据结构试试
```java
driver.touch([{
  type: 'drag',
  fromX: 265,
  fromY: 860,
  toX: 825,
  toY: 860,
  steps: 200
}, {
  type: 'drag',
  toX: 265,
  toY: 1460,
  duration: 3
}, {
  type: 'drag',
  toX: 825,
  toY: 1460,
  duration: 3
}]);
```
