### ISSUE TITLE
iPhone XR/XS/XS MAX 苹果不再提供udid，新格式的identifier无法识别，无法真机测试

### ISSUE THREAD

**Issue by ContinueHR** [alibaba/macaca#869]
* **Macaca Version**:2.1.9

* **Macaca Doctor Logs**:

  macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.12.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  electron: 2.0.4 [out-of-date]
  ios: 2.0.35

  macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.12.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  electron: 2.0.4 [out-of-date]
  ios: 2.0.35

* **Operate System**: MacOS  10.13.6 

* **Programming Language**:java

**iPhone XR/XS/XS MAX   这一系列开始
苹果不再提供40位的udid，只给出了ecid，
启动Macaca server和脚本后，无法识别到真机，只能调起simulator**
### 请尽快兼容 @xudafeng

**Comment by aini123152011** [comment]
I hope to solve this problem as soon as possible. Thank you.@xudafeng

**Comment by ContinueHR** [comment]
> iPhone XR/XS/XS MAX 的设备 id 新格式是什么样子？

我的XR和XS Max设备，在Xcode里看到的identifier是 “00008020-00” + ”ecid“ 这样的格式。
尚不清楚 00008020-00 这一段数字代表的是什么，是否固定。
设备兼容问题还请大佬留意修复，感谢 @xudafeng

**Comment by xudafeng** [comment]
```
    iPhone SE (2B53A397-447F-4A0F-B643-B736809E1B92) (Shutdown) 
    iPhone X (674887E8-35A8-4F1F-B4A5-A787BF36AB3E) (Shutdown) 
    iPhone XS (B8B6B1F5-30E0-401B-B1CE-70E4F39937A5) (Shutdown) 
    iPhone XS Max (D06FA61C-1841-4B8D-AD6A-810427F5D629) (Shutdown) 
    iPhone XR (417B5F08-A1E9-4652-A48F-7EA4C7F409D0) (Shutdown) 
```

我看到的还是36位udid

**Comment by ContinueHR** [comment]
> ```
>     iPhone SE (2B53A397-447F-4A0F-B643-B736809E1B92) (Shutdown) 
>     iPhone X (674887E8-35A8-4F1F-B4A5-A787BF36AB3E) (Shutdown) 
>     iPhone XS (B8B6B1F5-30E0-401B-B1CE-70E4F39937A5) (Shutdown) 
>     iPhone XS Max (D06FA61C-1841-4B8D-AD6A-810427F5D629) (Shutdown) 
>     iPhone XR (417B5F08-A1E9-4652-A48F-7EA4C7F409D0) (Shutdown) 
> ```
> 我看到的还是36位udid

请问能否提供一下查询udid的方式，我通过几种常规的工具查询，都无法得到36位udid。
相关一些论坛也有提到相同的问题，希望我能转述解决方法，感谢 @xudafeng

**Comment by ztwo** [comment]
instruments -s devices

**Comment by ContinueHR** [comment]
> instruments -s devices

iPhone XR (12.1) [00008020-001D4D381EC2002E]
iPhone XS (12.0) [00008020-001108461408002E]
iPhone XR (12.1) [6DB3ADB0-079F-424F-A875-93E9EFFD87C7] (Simulator)
iPhone XS (12.1) [052ED305-0037-4857-AEFA-1F1FD3018F94] (Simulator)
iPhone XS Max (12.1) [D3B9ABD7-E259-4F64-841A-BA778AA1035C] (Simulator)

instruments -s devices 真机usb连接显示的仍然不是36位，只有Xcode的Simulator显示36位

**Comment by xudafeng** [comment]
https://github.com/macacajs/app-inspector/pull/218
