### ISSUE TITLE
win10  install ios and android and chrome problem。

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#87]
win10平台下 安装不了android 和 ios啊 求指点 。

以下是我机器环境相关和安装日志输出

C:\Users\cmd>macaca --registry http://registry.cnpmjs.org install chrome
http://registry.cnpmjs.org driver is not support yet

C:\Users\cmd>npm -v
3.8.7

C:\Users\cmd>node -v
v5.10.1

C:\Users\cmd>appium -v
1.5.3

C:\Users\cmd>macaca install android
macaca-android is installing for the first time with args: ["install","macaca-android","-—global","--registry=https://registry.npmjs.org/"]

/ loading...macaca-cli@1.0.36 D:\nodejs\node-global\node_modules\macaca-cli
`-- macaca-android@1.0.16 extraneous

npm WARN deprecated win-spawn@2.0.0: use cross-spawn or cross-spawn-async instead.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "macaca-android" "-—global" "--registry=https://registry.npmjs.org/"
npm ERR! node v5.10.1
npm ERR! npm v3.8.7
npm ERR! path D:\nodejs\node-global\node_modules\macaca-cli
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'D:\nodejs\node-global\node_modules\macaca-cli' -> 'D:\nodejs\node-global\node_modules.macaca-cli.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! D:\nodejs\node-global\node_modules\macaca-cli\npm-debug.log

npm install exited with code 4294963214 and signal null
install macaca-android failed with Error: npm WARN deprecated win-spawn@2.0.0: use cross-spawn or cross-spawn-async instead.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "macaca-android" "-—global" "--registry=https://registry.npmjs.org/"
npm ERR! node v5.10.1
npm ERR! npm v3.8.7
npm ERR! path D:\nodejs\node-global\node_modules\macaca-cli
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'D:\nodejs\node-global\node_modules\macaca-cli' -> 'D:\nodejs\node-global\node_modules.macaca-cli.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! D:\nodejs\node-global\node_modules\macaca-cli\npm-debug.log

C:\Users\cmd>npm config get registry
http://registry.cnpmjs.org/

C:\Users\cmd>macaca doctor

Node.js checklist:

node env: D:\nodejs\node.exe
node version: v5.10.1

Android checklist:

JAVA version is 1.8.0_91
JAVA_HOME is set to C:\Program Files\Java\jdk1.8.0_91
ANDROID_HOME is set to D:\Android\android-sdk-windows
Platforms is set to D:\Android\android-sdk-windows\platforms\android-24
Android tools is set to D:\Android\android-sdk-windows\tools\android.bat
ANT_HOME is set to D:\apache-ant-1.9.7

C:\Users\cmd>macaca install ios
macaca-ios is installing for the first time with args: ["install","macaca-ios","-—global","--registry=https://registry.npmjs.org/"]

| loading...macaca-cli@1.0.36 D:\nodejs\node-global\node_modules\macaca-cli
`-- macaca-ios@1.0.30 extraneous

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "macaca-ios" "-—global" "--registry=https://registry.npmjs.org/"
npm ERR! node v5.10.1
npm ERR! npm v3.8.7
npm ERR! path D:\nodejs\node-global\node_modules\macaca-cli
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'D:\nodejs\node-global\node_modules\macaca-cli' -> 'D:\nodejs\node-global\node_modules.macaca-cli.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! D:\nodejs\node-global\node_modules\macaca-cli\npm-debug.log

npm install exited with code 4294963214 and signal null
install macaca-ios failed with Error: npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "macaca-ios" "-—global" "--registry=https://registry.npmjs.org/"
npm ERR! node v5.10.1
npm ERR! npm v3.8.7
npm ERR! path D:\nodejs\node-global\node_modules\macaca-cli
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'D:\nodejs\node-global\node_modules\macaca-cli' -> 'D:\nodejs\node-global\node_modules.macaca-cli.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! D:\nodejs\node-global\node_modules\macaca-cli\npm-debug.log

**Comment by zenzhu** [comment]
重新装下 node.js 试试，用 v4.4.7 LTS 版本的。Win 10 上 node 好像不太稳定。

**Comment by xudafeng** [comment]
https://testerhome.com/topics/5483
