### ISSUE TITLE
Macaca coverage - how to get lines executed report with instrumented code

### ISSUE THREAD

**Issue by mpreethi90** [alibaba/macaca#870]
With macaca's coverage, it is required to instrument the web app code using istanbul. After instrumenting and executing the tests, the coverage report files always points only to instrumented code that makes it tough to check the actual hit of test in the source code file.

<img width="1337" alt="screen shot 2018-11-13 at 14 06 55" src="https://user-images.githubusercontent.com/20960378/48394253-cb0e2500-e74d-11e8-8ede-63791231473f.png">

**Comment by xudafeng** [comment]
参考这个sample的coverage 配置 https://github.com/macaca-sample/antd-sample
