### ISSUE TITLE
android里面用xpath定位元素后，重新打包了一个apk,则原来的脚本全都执行失败，请问是我的使用方法有问题，还是xpath只能是针对同一个apk包才有效？？

### ISSUE THREAD

**Issue by liuhuabing** [alibaba/macaca#874]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by xudafeng** [comment]
app-inspector 检查下应该可以帮到你吧？
