### ISSUE TITLE
chrome浏览器 pc <input type='file' /> 如何触发onchange事件 调用上传图片呢 .click()与sendKeys都无法赋值

### ISSUE THREAD

**Issue by cjstone1982** [alibaba/macaca#877]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by xudafeng** [comment]
推荐通过mock解决，input或者alert都会阻塞用户端语言运行时，暂时不支持驱动控制。
