### ISSUE TITLE
cnpm安装显示成功，但是命令行无法执行

### ISSUE THREAD

**Issue by findarice** [alibaba/macaca#880]
* **Macaca Version**:
C:\Users\llm>macaca -v

  2.1.10

C:\Users\llm>cnpm -v
cnpm@6.0.0 (D:\Macaca\nodejs\node_global\node_modules\cnpm\lib\parse_argv.js)
npm@6.5.0 (D:\Macaca\nodejs\node_global\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@11.5.0 (D:\Macaca\nodejs\node.exe)
npminstall@3.17.0 (D:\Macaca\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=D:\Macaca\nodejs\node_global
win32 x64 10.0.14393
registry=https://registry.npm.taobao.org

* **Macaca Doctor Logs**:
C:\Users\llm>macaca doctor

  macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: D:\Macaca\nodejs\node.exe
  node version: v11.5.0

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_191`
  ANDROID_HOME is set to `C:\Users\llm\AppData\Local\Android\Sdk`
  Platforms is set to `C:\Users\llm\AppData\Local\Android\Sdk\platforms\android-28`
  ADB tool is set to `C:\Users\llm\AppData\Local\Android\Sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\Users\llm\gradle4_10_2`

  Installed driver list:

C:\Users\llm>

* **Operate System**:
window10 64-bit

* **Programming Language**:

C:\Users\llm>cnpm i macaca-android -g
Get /binary-mirror-config/latest from https://registry.npm.taobao.org error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.com/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":4,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at Timeout._onTimeout (D:\Macaca\nodejs\node_global\node_modules\cnpm\node_modules\urllib\lib\urllib.js:849:15)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
Get /bug-versions/latest from https://registry.npm.taobao.org error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.com/bug-versions/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":8,"createSocketErrorCount":0,"closeSocketCount":8,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at Timeout._onTimeout (D:\Macaca\nodejs\node_global\node_modules\cnpm\node_modules\urllib\lib\urllib.js:849:15)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
Error: Cannot find module 'bug-versions/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at getRemotePackage (D:\Macaca\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\utils.js:457:11)
    at getRemotePackage.throw (<anonymous>)
    at onRejected (D:\Macaca\nodejs\node_global\node_modules\cnpm\node_modules\co\index.js:81:24)
npminstall version: 3.17.0
npminstall args: D:\Macaca\nodejs\node.exe D:\Macaca\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\llm\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org macaca-android -g

**Comment by xudafeng** [comment]
看log是下载超时，网络不好再试试

**Comment by idreamin** [comment]
I have the same problem, how do you solve it ？Thank you very much.
