### ISSUE TITLE
app-inspecter跑起来抓iOS真机，界面一直显示Wating Device star 。。

### ISSUE THREAD

**Issue by yuhaoyuhao** [alibaba/macaca#881]
* **Macaca Version**:
  macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.8.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home`
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.35

* **Macaca Doctor Logs**:

* **Operate System**:
mac系统 14.1
xcode 10.1
iOS真机：11.4

* **Programming Language**:
>> server.js:16:12 [master] pid:11903 server start with config:
 { port: '56789',
  verbose: true,
  udid: '808526ea34629c05201fee845ed030e029b4ed07',
  ip: '172.18.188.160',
  host: 'yuhaoyuhaodeMacBook-Pro.local',
  loaded_time: '2018-12-27 20:42:56' }
>> app-inspector.js:45:12 [master] pid:11903 server start at: http://172.18.188.160:56789
>> xctest-client.js:55:14 [master] pid:11903 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:247:14 [master] pid:11903 xcode version: 10.1
>> XCTestWD version: 1.4.5
>> xctest-client.js:195:18 [master] pid:11903 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:11903 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:195:18 [master] pid:11903 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:286:14 [master] pid:11903 killing runnerProc pid: 11906
>> xctest-client.js:206:16 [master] pid:11903 xctest client exit with code: 65, signal: null

xctest-client.js:206:16 [master] pid:11903 xctest client exit with code: 65, signal: null 这个一直报重签名的问题 但是我已经改了 而且app-inspecter安装最新版本 也下载了XCTestWD最新版本编译通过了，但仍然不行，用app-inspecter中的XCTestWD中在xcode中编译也报错
想问下是因为我的版本太新了，导致不兼容和系统或者xcode，盼回复！！

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/929
