### ISSUE TITLE
npm i macaca-android -g bulid failed

### ISSUE THREAD

**Issue by yanguoqiang** [alibaba/macaca#884]
* **Macaca Version**:2.0.15

* **Macaca Doctor Logs**:
C:\Users\Bob>macaca doctor

  macaca-doctor version: 2.0.15

  Node.js checklist:

  node env: D:\Program Files\nodejs\node.exe
  node version: v10.15.0

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `D:\Program Files\Java\jdk1.8.0_161`
  ANDROID_HOME is set to `D:\android-sdk-windows`
  Platforms is set to `D:\android-sdk-windows\platforms\android-26`
  ADB tool is set to `D:\android-sdk-windows\platform-tools\adb.exe`
  GRADLE_HOME is set to `D:\software\gradle-5.1`

  Installed driver list:

  android: 2.0.48

* **Operate System**:
win7 64

* **Error info**:
C:\Users\Bob>npm i macaca-android -g --registry=https://registry.npm.taobao.org
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.

> macaca-chromedriver@1.0.44 install D:\Program Files\nodejs\node_global\node_modules\macaca-android\node_modules\macaca-chromedriver
> node ./bin/macaca-chromedriver install

>> version: 2.33
>> chromedriver cdn url: http://npm.taobao.org/mirrors/chromedriver//2.33/chromedriver_win32.zip
>> chromedriver local in D:\Program Files\nodejs\node_global\node_modules\macaca-android\node_modules\macaca-chromedriver\exec\chromedriver2.33.exe

> uiautomatorwd@1.0.61 install D:\Program Files\nodejs\node_global\node_modules\macaca-android\node_modules\uiautomatorwd
> node ./scripts/build.js

(node:8012) UnhandledPromiseRejectionWarning: ,Configuration on demand is an incubating feature.
,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.tasks.factory.AndroidUnitTest.setTestClassesDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

(node:8012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

> unlock-apk@1.0.8 install D:\Program Files\nodejs\node_global\node_modules\macaca-android\node_modules\unlock-apk
> node ./script/build.js

(node:6508) UnhandledPromiseRejectionWarning: ,Configuration on demand is an incubating feature.
,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

(node:6508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
+ macaca-android@2.0.48
added 158 packages from 121 contributors in 49.029s

**Comment by yanguoqiang** [comment]
I‘m sorry , the version of Macaca is 2.1.10

**Comment by youdi0828** [comment]
我也有这个问题，Macaca is 2.1.10

**Comment by xudafeng** [comment]
@ youdi0828 你是windows系统吗？

**Comment by paradite** [comment]
cannot be re-produced. re-open if you still have problems.
