### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by wzh154710510** [alibaba/macaca#886]
uiautomator-client.js:42:14 [master] pid:14016 C:\Users\willem\AppData\Roaming\npm\node_modules\app-inspector\node_modules\uiautomatorwd\app\build\outputs\apk\app-debug.apk not found, please resolve and reinstall android driver

![image](https://user-images.githubusercontent.com/23711162/50948520-b21bb900-14dd-11e9-910b-a02b7e50c276.png)

![image](https://user-images.githubusercontent.com/23711162/50948536-c069d500-14dd-11e9-8097-5b284a1ae563.png)

**Comment by lijingxin** [comment]
重新安装也是这个问题
