### ISSUE TITLE
运行hackernews-datahub报错

### ISSUE THREAD

**Issue by a526672351** [alibaba/macaca#887]
例子地址：https://github.com/eggjs/examples/tree/master/hackernews-datahub

0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'd:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:e2e' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'pretest:e2e', 'test:e2e', 'posttest:e2e' ]
5 info lifecycle hackernews-datahub@1.0.0~pretest:e2e: hackernews-datahub@1.0.0
6 info lifecycle hackernews-datahub@1.0.0~test:e2e: hackernews-datahub@1.0.0
7 verbose lifecycle hackernews-datahub@1.0.0~test:e2e: unsafe-perm in lifecycle true
8 verbose lifecycle hackernews-datahub@1.0.0~test:e2e: PATH: C:\Users\ip\AppData\Roaming\nvm\v8.11.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\examples\hackernews-datahub\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Users\ip\AppData\Roaming\nvm;d:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;d:\Program Files\Geth;D:\Program Files\Android\sdk\tools;D:\Program Files\Android\sdk\tools\bin;D:\Program Files\Android\sdk\platform-tools;C:\Users\ip\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\ip\AppData\Local\.meteor;C:\Users\ip\AppData\Local\Programs\Microsoft VS Code\bin;d:\Program Files (x86)\Egret\Egret Wing 3\bin;D:\apache-maven-3.6.0\bin
9 verbose lifecycle hackernews-datahub@1.0.0~test:e2e: CWD: F:\examples\hackernews-datahub
10 silly lifecycle hackernews-datahub@1.0.0~test:e2e: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=test macaca run --f_options \'--opts test/e2e/mocha.opts\' -d ./test/e2e' ]
11 silly lifecycle hackernews-datahub@1.0.0~test:e2e: Returned: code: 4294963238  signal: null
12 info lifecycle hackernews-datahub@1.0.0~test:e2e: Failed to exec test:e2e script
13 verbose stack Error: hackernews-datahub@1.0.0 test:e2e: `cross-env NODE_ENV=test macaca run --f_options '--opts test/e2e/mocha.opts' -d ./test/e2e`
13 verbose stack Exit status 4294963238
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\ip\AppData\Roaming\nvm\v8.11.3\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\ip\AppData\Roaming\nvm\v8.11.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid hackernews-datahub@1.0.0
15 verbose cwd F:\examples\hackernews-datahub
16 verbose Windows_NT 10.0.15063
17 verbose argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:e2e"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 4294963238
22 error hackernews-datahub@1.0.0 test:e2e: `cross-env NODE_ENV=test macaca run --f_options '--opts test/e2e/mocha.opts' -d ./test/e2e`
22 error Exit status 4294963238
23 error Failed at the hackernews-datahub@1.0.0 test:e2e script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294963238, true ]

**Comment by a526672351** [comment]
F:\examples\hackernews-datahub>npm run test:e2e> hackernews-datahub@1.0.0 test:e2e F:\examples\hackernews-datahub
> cross-env NODE_ENV=test macaca run --f_options '--opts test/e2e/mocha.opts' -d ./test/e2e

>> Macaca server started
>> Test completed!
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! hackernews-datahub@1.0.0 test:e2e: `cross-env NODE_ENV=test macaca run --f_options '--opts test/e2e/mocha.opts' -d ./test/e2e`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the hackernews-datahub@1.0.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\H004335.WTOIP\AppData\Roaming\npm-cache\_logs\2019-01-22T07_35_27_814Z-debug.log

**Comment by zivyangll** [comment]
@a526672351 重装 node_modules 试试？
