### ISSUE TITLE
请问下ios设备的性能数据怎么采集，谢谢

### ISSUE THREAD

**Issue by liurj** [alibaba/macaca#890]
我看了所有的问题好像也没有什么解决方案，这个是否可以解决，麻烦明确说下，谢谢

**Comment by dharmakrish6** [comment]
You can collect all the performance details from the Profile only. Not from the Macaca. I hope it helps you.

**Comment by SamuelZhaoY** [comment]
The profiling of ios app is possible via macaca but a very hacking one, which is like ingoking macaca instance and before it starts to get executed invoke ur own profiling scripts or ide function. Personally i wont recomment it
