### ISSUE TITLE
请问macaca支持在IE浏览器录制脚本吗？（Can macaca record script under ie browser？）

### ISSUE THREAD

**Issue by lijinghan1102** [alibaba/macaca#891]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by Stngle** [comment]
recorder 录制功能是基于 chrome extension 实现的，只能在 chrome 浏览器完成录制功能。

**Comment by Stngle** [comment]
因为 ie 浏览器本身也没有 plugin 或 extension 的机制，所以 ie 浏览器的录制功能目前也没法实现，是有什么场景需要吗？

**Comment by lijinghan1102** [comment]
> 因为 ie 浏览器本身也没有 plugin 或 extension 的机制，所以 ie 浏览器的录制功能目前也没法实现，是有什么场景需要吗？

您好，谢谢您的回复！因为我是在银行的开发中心做测试开发的，需要开发web端自动化测试工具或脚本，但银行的系统都是只支持ie浏览器，所以想咨询一下。
