### ISSUE TITLE
请问怎么没有代码呢？

### ISSUE THREAD

**Issue by TommyLemon** [alibaba/macaca#892]
看起来是个空仓库啊，迁移地址了吗？
![image](https://user-images.githubusercontent.com/5738175/53930030-cab5e300-40ca-11e9-815e-73b839d7db93.png)

**Comment by paradite** [comment]
代码在单独的org：
https://github.com/macacajs
README里有写：
https://github.com/alibaba/macaca/blob/master/README.zh.md#%E5%B8%AE%E5%8A%A9%E6%94%AF%E6%8C%81
官网也有写：
https://macacajs.com/zh/guide/support.html#github

**Comment by paradite** [comment]
关于这个找不到代码问题，有什么更好的建议嘛？

**Comment by TommyLemon** [comment]
可以在主页 Readme 加上各种实现库的链接哈
