### ISSUE TITLE
xctest安装问题

### ISSUE THREAD

**Issue by zhouhuiping** [alibaba/macaca#896]
* **Macaca Version**:
2.1.11

* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.16

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v11.10.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhp/Library/Android/sdk`
  Platforms is set to `/Users/zhp/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/zhp/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 5.2

  Installed driver list:

  android: 2.1.0
  location: /Users/zhp/Documents/GitHub/WebMonitor/mobileAutoTester/sample-nodejs/node_modules/.2.1.0@macaca-android

  chrome: 1.1.0
  location: /Users/zhp/Documents/GitHub/WebMonitor/mobileAutoTester/sample-nodejs/node_modules/.1.1.0@macaca-chrome

  electron: 2.2.4
  location: /Users/zhp/Documents/GitHub/WebMonitor/mobileAutoTester/sample-nodejs/node_modules/.2.2.4@macaca-electron

  ios: 2.0.35
  location: /Users/zhp/Documents/GitHub/WebMonitor/mobileAutoTester/sample-nodejs/node_modules/.2.0.35@macaca-ios

* **Operate System**:
macOs 10.14.3
xcode 10.1

* **Programming Language**:
nodejs

报错怎么解决？一头雾水
No profiles for 'XCTestWDRunner.XCTestWDRunner.Ali-71875N.local' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'XCTestWDRunner.XCTestWDRunner.Ali-71875N.local'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'XCTestWDUITests')

**Comment by SirCYong** [comment]
我只是关心如何解决这个问题！

**Comment by SamuelZhaoY** [comment]
@SirCYong @zhouhuiping 打开XCTestWD 安装位置参考https://github.com/macacajs/XCTestWD， 在真机运行的时候要适配自己的iOS开发证书
