### ISSUE TITLE
无法安装 app-inspector

### ISSUE THREAD

**Issue by linzh92** [alibaba/macaca#897]
* **Macaca Version**:
2.1.11
* **Macaca Doctor Logs**:
![image](https://user-images.githubusercontent.com/37093133/54590445-19686300-4a63-11e9-8ec0-d8205054f4d3.png)
* **Operate System**:
![image](https://user-images.githubusercontent.com/37093133/54590060-3486a300-4a62-11e9-8e3a-62d5f0868221.png)
* **Programming Language**:

使用命令「npm i app-inspector -g」安装 app-inspector 时，会出现如下错误：

![image](https://user-images.githubusercontent.com/37093133/54590306-c2fb2480-4a62-11e9-8623-59bfea3022ea.png)

xctestwd 都无法安装到本地，要进行重签名都没法重签名。

**Comment by linzh92** [comment]
> This is the translated issue:
> 
> # Unable to install app-inspector
> * **Macaca Version**:
>   2.1.11
> * **Macaca Doctor Logs**:
>   !![image](https://user-images.githubusercontent.com/37093133/54590003-1b7df200-4a62-11e9-937f-968d519f4c52.png)
> * **Operate System**:
>   ![image](https://user-images.githubusercontent.com/37093133/54590060-3486a300-4a62-11e9-8e3a-62d5f0868221.png)
> * **Programming Language**:
> 
> When installing the app-inspector with the command "npm i app-inspector -g", the following error occurs:
> 
> ![image](https://user-images.githubusercontent.com/37093133/54590306-c2fb2480-4a62-11e9-8623-59bfea3022ea.png)
> 
> Xctestwd can't be installed locally, and you can't re-sign it if you want to re-sign.

**Comment by SamuelZhaoY** [comment]
reinstall xctestwd@1.4.10, the issue has been fixed
