### ISSUE TITLE
iOS真机测试，按照提供的真机测试说明详细文档，使用python的例子，提示BundleId XCTestWD.XCTestWD does not exist。请问如何解决

### ISSUE THREAD

**Issue by gnxujj** [alibaba/macaca#898]
环境： xcode 10.1
手机：iphone 6p，系统10
按照文档说明，从github中下载了XCTestWD，修改bundle id，以及team（非开发者账号，只是普通的appid），可以将XCTestWD装入真机，但是运行case时，提示BundleId XCTestWD.XCTestWD does not exist.
请问有遇到类似情况的吗？怎么解决呢

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/929
