### ISSUE TITLE
app-inspector waiting device start...

### ISSUE THREAD

**Issue by linzh92** [alibaba/macaca#899]
* **Macaca Version**:
2.1.11
* **Macaca Doctor Logs**:
![image](https://user-images.githubusercontent.com/37093133/54831249-f654e200-4cf4-11e9-8301-cce9b6c8c2ed.png)

* **Operate System**:
![image](https://user-images.githubusercontent.com/37093133/54831160-cc9bbb00-4cf4-11e9-91ec-e4d9e8914ae9.png)

* **Programming Language**:

通过命令行启动 app-inspector，会有如下问题：
![image](https://user-images.githubusercontent.com/37093133/54831290-0c62a280-4cf5-11e9-9074-b38458aece20.png)

![image](https://user-images.githubusercontent.com/37093133/54831302-0f5d9300-4cf5-11e9-99f4-1c0cf64fb66e.png)

**Comment by paradite** [comment]
@linzh92  请提供完整的log，从你运行了什么命令开始。
比如
```
$ app-inspector -u xyz
...
```

**Comment by linzh92** [comment]
Hi @paradite :

     我就是想把 app-inspector 启动起来，运行命令如下：
     app-inspector -u $udid --verbose

Best regards.

**Comment by linzh92** [comment]
![image](https://user-images.githubusercontent.com/37093133/54861933-98b0ac00-4d6d-11e9-8bf2-eb6c3543a892.png)

@paradite

**Comment by paradite** [comment]
<img width="1223" alt="Screenshot 2019-03-23 at 1 17 24 PM" src="https://user-images.githubusercontent.com/1209810/54861969-08269b80-4d6e-11e9-9bfd-d798c482ee52.png">
<img width="627" alt="Screenshot 2019-03-23 at 1 18 26 PM" src="https://user-images.githubusercontent.com/1209810/54861985-2b514b00-4d6e-11e9-887b-8e734cde7c7f.png">

I just did a fresh installation of latest `app-inspector` and everything works fine.
Maybe you can try

- restarting the computer to get a clean state
- reinstall `app-inspector` by 

```
$ npm uninstall -g app-inspector
$ npm i -g app-inspector
```

**Comment by linzh92** [comment]
@paradite 
   
    work 不起来。
    我重启电脑，重装 app-inspector 也没用。
    需要重签名 XCtestWD 嘛？

Best regards.

**Comment by paradite** [comment]
Any build errors for `XCtestWD ` when you installed `app-inspector`? I think it is not built properly. Please supply the relevant logs for `npm i -g app-inspector`.

>  Need to re-sign XCtestWD?

not sure, you can try.

**Comment by xudafeng** [comment]
iOS 真机可以参考这里 https://github.com/alibaba/macaca/issues/654

**Comment by paradite** [comment]
@linzh92 you can try follow the guide, if it helps to resolve the issue, I will update the docs to include the guide for iOS real device. Thanks!

**Comment by linzh92** [comment]
> @linzh92 you can try follow the guide, if it helps to resolve the issue, I will update the docs to include the guide for iOS real device. Thanks!

OK, Thx a lot.

Best regards.

**Comment by linzh92** [comment]
> iOS 真机可以参考这里 #654

好的，我尝试一下。非常感谢。

Best  regards.

**Comment by linzh92** [comment]
> @linzh92 you can try follow the guide, if it helps to resolve the issue, I will update the docs to include the guide for iOS real device. Thanks!
Hi @paradite :
      I follow the #654, it works now!!
Best regards.

**Comment by paradite** [comment]
@linzh92 great. Did you install `XCtestWD` separately or did you use the `XCtestWD` dependency in global `app-inspector`?

**Comment by linzh92** [comment]
> @linzh92 great. Did you install `XCtestWD` separately or did you use the `XCtestWD` dependency in global `app-inspector`?

The latter.
