### ISSUE TITLE
安装client的时候出现权限不足

### ISSUE THREAD

**Issue by pdhxxj** [alibaba/macaca#9]
➜  ~ npm -v
2.14.4
➜  ~ npm i macaca-client -g
npm WARN engine macaca-client@1.0.11: wanted: {"node":">=4.2.1"} (current: {"node":"4.1.1","npm":"2.14.4"})
npm ERR! tar.unpack untar error /Users/auto1/.npm/macaca-client/1.0.11/package.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "macaca-client" "-g"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path /usr/local/lib/node_modules/macaca-client
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/macaca-client'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/macaca-client']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/macaca-client',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/macaca-client',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/auto1/npm-debug.log

**Comment by xudafeng** [comment]
按照提示安装[链接](https://testerhome.com/topics/4330)
