### ISSUE TITLE
reliable 跑macaca 搭建及运行过程中的疑问

### ISSUE THREAD

**Issue by oatsuper** [alibaba/macaca#90]
* **Macaca Version**:
macaca -v
1.0.35 （之前npm i macaca－cli －g 安装的）
* **Macaca Doctor**:
Node.js checklist:

  node env: /usr/local/bin/node
  node version: v5.9.1

  iOS checklist:

  Xcode is installed at: `/Applications/Xcode.app/Contents/Developer`
  Xcode Command Line Tools is ready, version: 2343.
  ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

  Android checklist:

  JAVA version is `1.8.0_77`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/yanyan/Install/android-sdk-macosx`
  Platforms is set to `/Users/yanyan/Install/android-sdk-macosx/platforms/android-23`
  Android tools is set to `/Users/yanyan/Install/android-sdk-macosx/tools/android`

  Installed driver list:

  android: 1.0.11
  ios: 1.0.30

* **Platform**:
Mac pro
uname -r
15.2.0

1. reliable master 我在 reliable-macaca-docker-compose 中make start后
   浏览器可以通过localhost：8083 进行显示
   
   标准的docker-compose.yml 最后有个slave_1 

   是不是对于单点模式下，如果slave之前已安装，对于make start ，slave 顺利的话就可以正常运行了，虽然源码中 slave connect master 的命令中有－－verbose ，但是在make start的串口中 看不到任何slave的debug打印，或者说一句打印都没有

2. 后面我讲docker－compose.yml 文件中的slave_1的相关删除，make start后，web 控制面板正常进入，也显示0个slave
   我在另一个终端下，手动执行connect master命令，并在web 控制面板中新增了 New task

   开始运行中，可以在运行slave 的终端下看到：
>> flow.js:68:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 start git clone...
>> flow.js:82:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 YAML start parsering...
>> flow.js:86:14 [worker:1] pid:36967 .macaca.yml does not exists!
>> flow.js:91:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 start git clone success!
>> flow.js:94:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 start npm install...
>> flow.js:103:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 npm install success!

    这里有个疑问，git的过程，文件是下载到我机器的哪里了呢？ 就类似于Jenkins的工作空间一样，应该有了工作路径

3. 3.  完成了上述git和install后

>> flow.js:113:12 [worker:1] pid:36967 Sending 579485f2e8397125003cab01 data...
>> index.js:63:14 [master] pid:36966 listening worker id: 1, pid: 36967, address: 192.168.0.103:%s%s
>> index.js:17:12 [worker:1] pid:36967 webdriver server start with config:
 { port: 3456,
  ip: '192.168.0.103',
  host: 'bogon',
  loaded_time: '2016-07-24 17:14:25' }
>> middlewares.js:17:10 [worker:1] pid:36967 base middlewares attached
>> router.js:108:10 [worker:1] pid:36967 router set
>> webdriver sdk launched
>> index.js:63:14 [master] pid:36966 listening worker id: 1, pid: 36967, address: 192.168.0.103:3456
>> flow.js:153:14 [worker:1] pid:36967 Sending 579485f2e8397125003cab01 error data...
>> channel.js:73:14 [worker:1] pid:36967 
status: 'busy',
  body: 'Error: spawn /usr/local/lib/node_modules/reliable-macaca-slave/node_modules/macaca-cli/node_modules/.bin/mocha ENOENT\n' }
/usr/local/lib/node_modules/reliable-macaca-slave/core/task/flow.js:173
      var bodyStatus = hasError ? bodyStatus.FAILED : execInfo.status;
                                            ^

TypeError: Cannot read property 'FAILED' of undefined
    at Runner.<anonymous> (/usr/local/lib/node_modules/reliable-macaca-slave/core/task/flow.js:173:45)
    at emitTwo (events.js:100:13)
    at Runner.emit (events.js:185:7)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/reliable-macaca-slave/node_modules/macaca-cli/lib/run/index.js:79:10)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
>> index.js:66:14 [master] pid:36966 worker disconnect
>> index.js:57:14 [master] pid:36966 worker fork success
>> index.js:70:14 [master] pid:36966 worker exit code: 1 signal: null
>> index.js:60:14 [master] pid:36966 worker online

关于mocha $pwd ==/usr/local/lib/node_modules

./reliable-macaca-slave/node_modules/.bin/mocha
./reliable-macaca-slave/node_modules/mocha
./reliable-macaca-slave/node_modules/mocha/bin/mocha

这个问题error怎么破呢？而且这个error 出现后，slave的连接后续会报错：
>> index.js:54:12 [worker:2] pid:37057 Zmq Reconnecting...
>> request.js:11:12 [worker:2] pid:37057 get info failed with: Error: connect ECONNREFUSED 127.0.0.1:8083

同时 master 的web 控制面板，该任务一直处于running状态，slave 断开后，处于waiting状态 
重新启动master之后，该任务还是waiting状态

还有问题是，reliable在执行编辑的任务时，怎么选取测试用例来执行呢？就像您那个sample code一样，一个Repository里面有很多test file， 
手动运行的时候还可以用 makefile 来调度运行，reliable中是怎么来确认执行那个测试用例呢？
此外，对于项目工程的测试用例集，我需要常见多个Repository 来组织项目的测试用例执行么？

如果想多台测试机（Andorid及IOS同时），我看reliable中的没有其他命令行选项可以填写uuid 和bundleId ，那么是不是需要在不同的Repository的XXX.test.js中固定写死呢？那么这样每次运行前都需要修改Respository中的测试代码

上述疑问较多，烦请逐项解疑，谢谢｀ 费心～

**Comment by sencho** [comment]
@oatsuper加我QQ147886833

**Comment by oatsuper** [comment]
谢谢Sencho的答疑，除了业务先相关的问题，这个issue主要是body: 'Error: spawn /usr/local/lib/node_modules/reliable-macaca-slave/node_modules/macaca-cli/node_modules/.bin/mocha ENOENT\n' }
/usr/local/lib/node_modules/reliable-macaca-slave/core/task/flow.js:173
var bodyStatus = hasError ? bodyStatus.FAILED : execInfo.status;
问题，再重新单独提个issue 这个issue 可以关闭了

**Comment by sunnydavid** [comment]
>> Coming to processor...
>> channel.js:69:16 [worker:1] pid:4832
<--- zmq message
{ type: 'task',
  taskId: '588218cf9261c61b00c4e8bd',
  sysInfo:
   { cpus:
      [ { model: 'Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz',
          speed: 3100,
          times: { user: 2662110, nice: 0, sys: 3541320, idle: 79241580, irq: 0 } },
        { model: 'Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz',
          speed: 3100,
          times: { user: 910390, nice: 0, sys: 949490, idle: 83584620, irq: 0 } },
        { model: 'Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz',
          speed: 3100,
          times: { user: 2478940, nice: 0, sys: 2671190, idle: 80294370, irq: 0 } },
        { model: 'Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz',
          speed: 3100,
          times: { user: 936030, nice: 0, sys: 931040, idle: 83577420, irq: 0 } },
        [length]: 4 ],
     memory: 0.015032529830932617,
     type: 'Darwin',
     platform: 'darwin',
     uptime: '0d 23h 44m',
     release: '16.3.0',
     hostname: 'sunbowendeMacBook-Pro.local',
     port: undefined },
  status: 'busy',
  body: '' }
>> flow.js:99:12 [worker:1] pid:4832 Task 588218cf9261c61b00c4e8bd start git clone...
>> flow.js:116:12 [worker:1] pid:4832 Task 588218cf9261c61b00c4e8bd start git clone success!
>> flow.js:176:12 [worker:1] pid:4832 Error: File .reliable.yml must exist, please check path or filename
    at Builder.parse (/usr/local/lib/node_modules/reliable-macaca-slave/node_modules/.1.0.7@reliable-build/lib/index.js:32:13)
    at Builder.init (/usr/local/lib/node_modules/reliable-macaca-slave/node_modules/.1.0.7@reliable-build/lib/index.js:23:10)
    at new Builder (/usr/local/lib/node_modules/reliable-macaca-slave/node_modules/.1.0.7@reliable-build/lib/index.js:17:10)
    at module.exports (/usr/local/lib/node_modules/reliable-macaca-slave/core/task/flow.js:119:21)
    at module.exports.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/reliable-macaca-slave/node_modules/.4.6.0@co/index.js:65:19)
>> flow.js:187:12 [worker:1] pid:4832 Sending 588218cf9261c61b00c4e8bd error data...
>> channel.js:69:16 [worker:1] pid:4832
<--- zmq message
{ type: 'task',
  taskId: '588218cf9261c61b00c4e8bd',
  sysInfo:
   { cpus:
      [ { model: 'Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz',
          speed: 3100,
          times: { user: 2662110, nice: 0, sys: 3541320, idle: 79241580, irq: 0 } },
        { model: 'Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz',
          speed: 3100,
          times: { user: 910390, nice: 0, sys: 949490, idle: 83584620, irq: 0 } },
        { model: 'Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz',
          speed: 3100,
          times: { user: 2478940, nice: 0, sys: 2671190, idle: 80294370, irq: 0 } },
        { model: 'Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz',
          speed: 3100,
          times: { user: 936030, nice: 0, sys: 931040, idle: 83577420, irq: 0 } },
        [length]: 4 ],
     memory: 0.015032529830932617,
     type: 'Darwin',
     platform: 'darwin',
     uptime: '0d 23h 44m',
     release: '16.3.0',
     hostname: 'sunbowendeMacBook-Pro.local' },
  status: 'busy',
  body: 'Error: File .reliable.yml must exist, please check path or filename' }
>> flow.js:72:12 [worker:1] pid:4832 Task is end with 588218cf9261c61b00c4e8bd data...
>> channel.js:69:16 [worker:1] pid:4832
<--- zmq message



这里的.reliable.yml是什么文件，reliable官方文档没有解释说明 是否能解答一下，这是最新的master分支的报错，目测和lz的类似

@xudafeng @sencho 

@sencho qq加你了，麻烦有空回复一下，多谢

**Comment by wk1281472252** [comment]
@sunnydavid 
.reliable.yml的问题解决了吗，能否告知下0.0

**Comment by sunnydavid** [comment]
@wk1281472252 https://github.com/reliablejs/reliable-build/blob/master/test/yaml/.reliable.yml
也可以参考我的repo的sample里的.reliable.yml
