### ISSUE TITLE
web测试不支持自定义userAgent吗

### ISSUE THREAD

**Issue by yxgtianya** [alibaba/macaca#903]
desired_caps = {
	'platformName': 'Desktop',  # iOS, Android, Desktop
	'browserName': 'Chrome',  # Chrome, Electron
	'userAgent': 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0 Safari/537.36 Macaca Custom UserAgent'
}
nginx做了ua跳转，pc不能直接打开m站

**Comment by paradite** [comment]
请提供一下具体的代码，macaca-wd的话，部分驱动是支持自己设置UA的：
https://macacajs.github.io/guide/helpful-settings.html#desired-capabilities
