### ISSUE TITLE
macaca怎么解决web界面鼠标移动才显示按钮的定位(java)

### ISSUE THREAD

**Issue by wuzhengbiao** [alibaba/macaca#906]
* **Macaca Version**:最新

* **Macaca Doctor Logs**:日志上就是找不到这种鼠标移动上去的悬浮按钮

* **Operate System**:window10 64位

* **Programming Language**:java

**Comment by yihuineng** [comment]
可以尝试使用快捷键
![image](https://github.com/alibaba/macaca/assets/10104168/0eda19b1-183a-4359-94fb-f12e1a7216f5)

问题久远关闭，如有问题，可再次提issue并提供详细环境信息&复现路径
