### ISSUE TITLE
Android 6 chromedriver 无法链接

### ISSUE THREAD

**Issue by xudafeng** [alibaba/macaca#91]

**Comment by xudafeng** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1378

**Comment by feifei168** [comment]
这个＃91的bug我之前就看到了，后来换了仨手机都不行，报同样的error，三星A9000，nexus6

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/99

**Comment by xudafeng** [comment]
https://github.com/xudafeng/android-app-bootstrap/commit/d02fd52863ac74a252df731dc4950a874183a2fb

**Comment by xudafeng** [comment]
Android4.4 需要开启

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
   WebView.setWebContentsDebuggingEnabled(true);
}
```
