### ISSUE TITLE
安装macaca-ios 问题 CompileSwift failed(编译失败)

### ISSUE THREAD

**Issue by zhouhuiping** [alibaba/macaca#910]
* **Macaca Version**:
2.1.12

* **Macaca Doctor Logs**:
macaca-doctor version: 2.0.16

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v11.10.1

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/zhp/Library/Android/sdk`
  Platforms is set to `/Users/***/Library/Android/sdk/platforms/android-28`
  ADB tool is set to `/Users/***/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 5.2

  Installed driver list:

  android: 2.1.0
  location: /usr/local/lib/node_modules/macaca-android

  ios: 2.0.35
  location: /usr/local/lib/node_modules/macaca-ios
* **Operate System**:
macos:10.14.3
xcode:10.1

* **Programming Language**:
nodejs

builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/build/Build/Intermediates.noindex/XCTestWD.build/Debug-iphonesimulator/XCTestWD.build/module.modulemap /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/build/Build/Products/Debug-iphonesimulator/XCTestWD.framework/Modules

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD/Server/XCTestWDController.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by paradite** [comment]
Please update Xcode to 10.2.

**Comment by zhouhuiping** [comment]
Thanks,the problem resolved
