### ISSUE TITLE
关于macaca的driver.quit()方法使用问题

### ISSUE THREAD

**Issue by zhechengmao** [alibaba/macaca#913]
因为业务逻辑需要退出app再进app，Android端调用driver.quit()方法可以满足退出app，但是在ios端，如果调用这个方法，app是没有退出去的，所以想问一下，这个是问题，还是另有其他方式？

**Comment by wuzhengbiao** [comment]
这个方法只是删除session,不会退出

**Comment by zhechengmao** [comment]
> 法只是删除session,不会退出

恩，看了一下，好像ios没有退出app的方法，Android端好像有个forceStopApp的方法可以用，但是也要root权限才行，目前ios端已经用initDriver这个方法暂时替代一下了
