### ISSUE TITLE
用例执行过程中，有方法能关闭和启动应用嘛？

### ISSUE THREAD

**Issue by sixstones** [alibaba/macaca#914]
用例执行过程中，有方法能关闭和启动应用嘛？
类似appium里的close_app()、start_activity这种方法

**Comment by IanWatsons** [comment]
同想问，而且跑完用例退出driver之后也不能关闭应用

**Comment by le4** [comment]
希望可以把这个方法加上，有时候想中断运行

**Comment by yihuineng** [comment]
问题久远关闭，如有问题，可再次提issue并提供详细环境信息&复现路径
