### ISSUE TITLE
ubentu系统上执行nosmoke，macaca server端错误uiautomator-client.js:119:12 [master] pid:2487 proxy.send except: Error: connect ECONNREFUSED 127.0.0.1:9001

### ISSUE THREAD

**Issue by liufeiflying** [alibaba/macaca#915]
## 在ubnetu系统上执行 nosmoke，macaca server端报以下错误，
系统版本信息：
Linux version 4.15.0-47-generic (buildd@lgw01-amd64-001) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019
--------------------------以下是日志截图-------------------------------------------
        responseHandler.js:11:12 [master] pid:2487 Recieve HTTP Request from Client[2019-04-17 15:44:51]: method: POST url: /wd/hub/session/e0e6fa2e-68ed-423b-b2db-f669ea73eaeb/actions, jsonBody: {"actions":[{"type":"tap","x":361,"y":1003.5}]}
        proxy.js:56:14 [master] pid:2487 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:9001/wd/hub/session/:sessionId/accept_alert:POST with body: {}
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        uiautomator-client.js:119:12 [master] pid:2487 proxy.send except: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:56:14 [master] pid:2487 Proxy: /wd/hub/session/e0e6fa2e-68ed-423b-b2db-f669ea73eaeb/actions:POST to http://127.0.0.1:9001/wd/hub/session/e0e6fa2e-68ed-423b-b2db-f669ea73eaeb/actions:POST with body: {"actions":[{"type":"tap","x":361,"y":1003.5}]}
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001
        proxy.js:64:22 [master] pid:2487 UIAutomatorWD client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:9001

* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

**Comment by xudafeng** [comment]
设备和宿主机连接失败了
