### ISSUE TITLE
uirecorder无法录制脚本

### ISSUE THREAD

**Issue by newbeginningxzm** [alibaba/macaca#916]
* **Macaca Version**:
2.1.12
* **Macaca Doctor Logs**:
![image](https://user-images.githubusercontent.com/16357645/56354328-fbc71e80-6205-11e9-9cc5-7152f9c424a6.png)
* **Operate System**:
windows 10
* **Programming Language**:
js

利用```uireocder init --mobile```初始化测试文件夹在install project dependencies卡住无反应，利用`npm install`手动安装依赖，`uirecorder start --mobile`在输入apk路径后无反应。
![image](https://user-images.githubusercontent.com/16357645/56354497-74c67600-6206-11e9-8e64-ccc75e6560d5.png)

**Comment by xuchongfeng** [comment]
同碰到，下面是我的环境
 macaca-doctor version: 2.0.16


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.9.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2349.
  xcodebuild version: 10.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/FlyFish/Library/Android/sdk`
  Platforms is set to `/Users/FlyFish/Library/Android/sdk/platforms/android-27`
  ADB tool is set to `/Users/FlyFish/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 5.1

  Installed driver list:

  android: 2.1.0
  location: /usr/local/lib/node_modules/macaca-android

  ios: 2.0.35
  location: /usr/local/lib/node_modules/macaca-ios

**Comment by newbeginningxzm** [comment]
问题已经解决，`uirecorder`的`install.sh`使用的`node`版本为`7.10.0`，使用`nvm`将`node`版本切换到`7.10.0`即可
