### ISSUE TITLE
proxy.js:63:22 [master] pid:19958 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by spa221** [alibaba/macaca#920]
您好，目前有一个问题困扰了我很久了，一直没有解决，求指导

macaca-ios的版本是2.0.25

运行demo（https://github.com/macaca-sample/sample-nodejs）的时候一直报错

运行demo执行的命令是：npm run test:ios

报错信息如下：
>> xctest-client.js:230:20 [master] pid:19958 please check project: /Users/duke/Documents/testmacaca/sample-nodejs/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:19958 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

**Comment by xudafeng** [comment]
@spa221 
看样子是网络问题，
运行 xcode功能，看能否提供更多 log信息。 /Users/duke/Documents/testmacaca/sample-nodejs/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj

**Comment by spa221** [comment]
> @spa221
> 看样子是网络问题，
> 运行 xcode功能，看能否提供更多 log信息。 /Users/duke/Documents/testmacaca/sample-nodejs/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj

目前直接使用命令启动
xcodebuild -project XCTestWD.xcodeproj \
           -scheme XCTestWDUITests \
           -destination 'platform=iOS Simulator,name=iPhone 6' \
           XCTESTWD_PORT=8001 \
           clean test

显示如下
2019-05-04 21:54:35.015913+0800 XCTestWDUITests-Runner[21541:345025] initializing wd server
2019-05-04 21:54:35.020827+0800 XCTestWDUITests-Runner[21541:345025] check log dir @:["/Users/duke/Library/Developer/CoreSimulator/Devices/33D57EDC-24F6-489C-9E8D-7F62031278FB/data/Containers/Data/Application/1D3E921F-3C20-4BA6-8C38-3DABED83A8B0/Documents"]
2019-05-04 21:54:35:023 XCTestWDUITests-Runner[21541:345025] XCTestWD-Debug-Info: 
setup debug log
2019-05-04 21:54:35.024494+0800 XCTestWDUITests-Runner[21541:345044] XCTestWD-Debug-Info: 
setup debug log
2019-05-04 21:54:35.051919+0800 XCTestWDUITests-Runner[21541:345025] com.apple.test.XCTestWDUITests-Runner
2019-05-04 21:54:35.052132+0800 XCTestWDUITests-Runner[21541:345025] XCTestWDSetup->http://localhost:8001<-XCTestWDSetup

感觉是成功启动了的

单独用Xcode进行运行，我看是有一些警告的，没有报错。
<img width="437" alt="WX20190504-220038@2x" src="https://user-images.githubusercontent.com/6396448/57180121-21b41a80-6eb8-11e9-887e-d418b4288600.png">

**Comment by spa221** [comment]
app-inspector是正常的，截图如下


<img width="565" alt="WX20190504-225302@2x" src="https://user-images.githubusercontent.com/6396448/57180869-a0f91c80-6ebf-11e9-806c-b6bf038bebe9.png">

<img width="536" alt="WX20190504-225321@2x" src="https://user-images.githubusercontent.com/6396448/57180882-bbcb9100-6ebf-11e9-8a84-679207508731.png">

**Comment by paradite** [comment]
@spa221 please provide diagnosis logs from macaca doctor, following the issue template.

**Comment by spa221** [comment]
> @spa221 please provide diagnosis logs from macaca doctor, following the issue template.

这个是诊断信息
DukedeMacBook-Pro:~ duke$ macaca doctor

  macaca-doctor version: 2.0.16


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.15.3

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.2.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  gradle is installed, version: 5.4

  Installed driver list:

  android: 2.1.0
  location: /usr/local/lib/node_modules/macaca-android

  chrome: 1.1.0
  location: /usr/local/lib/node_modules/macaca-chrome

  electron: 3.0.2
  location: /usr/local/lib/node_modules/macaca-electron

  ios: 2.0.35
  location: /usr/local/lib/node_modules/macaca-ios



DukedeMacBook-Pro:~ duke$

**Comment by spa221** [comment]
hi，有人能帮忙看看我的问题吗？

**Comment by paradite** [comment]
@spa221 试试 Xcode 10.2。详见
https://github.com/macacajs/app-inspector/issues/228#issuecomment-491171629

**Comment by xinxinga** [comment]
I meet the same problem, for several days.
Mac OS 10.14.5 + Xcode 10.2 ( also tried Xcode 10.2.1), neither work.

Log:
>> proxy.js:63:22 [master] pid:76512 xctest client proxy error with: Error: socket hang up
>> proxy.js:63:22 [master] pid:76512 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:76512 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:76512 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:309:14 [master] pid:76512 Fail to start xctest: Error: read ECONNRESET
>> xctest-client.js:322:14 [master] pid:76512 killing runnerProc pid: 84284
>> xctest-client.js:328:14 [master] pid:76512 killing iproxyProc pid: 84538
>> xctest-client.js:272:14 [master] pid:76512 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:242:16 [master] pid:76512 xctest client exit with code: null, signal: SIGKILL

**Comment by paradite** [comment]
@spa221 请问你的macOS版本是多少？

**Comment by spa221** [comment]
> @spa221 请问你的macOS版本是多少？

10.14.5
