### ISSUE TITLE
xctest client proxy error with: Error: read ECONNRESET

### ISSUE THREAD

**Issue by xinxinga** [alibaba/macaca#928]
* **Macaca Version**: 2.1.12

* **Macaca Doctor Logs**:
```
macaca-doctor version: 2.0.16


  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.15.3

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/XXX/Library/Android/sdk`
  Platforms is set to `/Users/XXX/Library/Android/sdk/platforms/android-28`
  ADB tool is set to `/Users/XXX/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 5.1

  Installed driver list:

  android: 2.1.0
  location: /Users/XXX/npm-global/lib/node_modules/macaca-android

  ios: 2.0.35
  location: /Users/XXX/npm-global/lib/node_modules/macaca-ios

```
* **Operate System**: MAC OS 10.14.5

* **Programming Language**: Python

run ```macaca server --verbose```
>> index.js:15:12 [master] pid:86802 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '7.0.xxx.41',
  host: '34363bc9e554.ant.xxx.xxx',
  loaded_time: '2019-05-29 16:31:01' }
>> middlewares.js:17:10 [master] pid:86802 base middlewares attached
>> router.js:132:10 [master] pid:86802 router set
>> Macaca server started
>> responseHandler.js:11:12 [master] pid:86802 Recieve HTTP Request from Client[2019-05-29 16:31:39]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"udid":"b29eee80cad2e09e78aa1d7b3b3b5948c7daeca0","deviceName":"iPhone","app":"/Users/XXX/Downloads/new-auto-cn-resigned.app","platformName":"ios","browserName":""}}
>> session.js:58:10 [master] pid:86802 Creating session, sessionId: fd9019f8-5023-409b-a313-fae2601ca4cd.
ios-deploy
>> helper.js:207:14 [master] pid:86802 Using local app form /Users/XXX/Downloads/new-auto-cn-resigned.app
CFBundleIdentifier is com.xxx.xxx
Get bundleId com.xxx.xxx from plist /Users/XXX/Downloads/new-auto-cn-resigned.app/Info.plist
>> macaca-ios.js:283:12 [master] pid:86802 App 'com.xxx.xxx' is not installed.
>> macaca-ios.js:286:14 [master] pid:86802 Install app 'com.xxx.xxx' successfully.
BundleId XCTestWD.XCTestWD does not exist.
>> macaca-ios.js:162:10 [master] pid:86802 {
	"bundleId": "com.XXX.XXX”,
	"platformName": "ios"
}
>> xctest-client.js:56:14 [master] pid:86802 project path: /Users/XXX/npm-global/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:171:12 [master] pid:86802 Trying to start xctestwd server...
>> xctest-client.js:283:14 [master] pid:86802 xcode version: 10.2
>> XCTestWD version: 1.4.18
>> xctest-client.js:227:20 [master] pid:86802 hitted for default mode
>> xctest-client.js:230:20 [master] pid:86802 please check project: /Users/XXX/npm-global/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:86802 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.xxx.xxx","platformName":"ios"}}
>> proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:230:20 [master] pid:86802 please check project: /Users/XXX/npm-global/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:86802 please check project: /Users/XXX/npm-global/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:86802 please check project: /Users/XXX/npm-global/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:86802 please check project: /Users/XXX/npm-global/lib/node_modules/macaca-ios/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:85:20 [master] pid:86802 Got response with status 200: {"status":0,"value":{"capabilities":{"browserName":"xxx Debug","sdkVersion":"11.2.6","CFBundleIdentifier":"com.XXX.XXX”,”device":"iphone"},"sessionId":"BE799F8A-D574-4405-A13B-FEEAD1E06B...
>> responseHandler.js:49:14 [master] pid:86802 Send HTTP Respone to Client[2019-05-29 16:32:56]: {"sessionId":"fd9019f8-5023-409b-a313-fae2601ca4cd","status":0,"value":"{\"udid\":\"b29eee80cad2e09e78aa1d7b3b3b5948c7daeca0\",\"deviceName\":\"iPhone\",\"app\":\"/Users/XXX/Downloads/new-auto-cn-resigned.app\",\"platformName\":\"ios\",\"browserName\":\"\"}"}
>> responseHandler.js:11:12 [master] pid:86802 Recieve HTTP Request from Client[2019-05-29 16:32:56]: method: POST url: /wd/hub/session, jsonBody: {"session_id":"fd9019f8-5023-409b-a313-fae2601ca4cd","desiredCapabilities":{"udid":"b29eee80cad2e09e78aa1d7b3b3b5948c7daeca0","deviceName":"iPhone","app":"/Users/XXX/Downloads/new-auto-cn-resigned.app","platformName":"ios","browserName":""}}
>> session.js:58:10 [master] pid:86802 Creating session, sessionId: 5042aa5d-9434-418e-8fb6-0e3f3e28904e.
>> helper.js:207:14 [master] pid:86802 Using local app form /Users/XXX/Downloads/new-auto-cn-resigned.app
CFBundleIdentifier is com.XXX.XXX
Get bundleId com.XXX.XXX from plist /Users/XXX/Downloads/new-auto-cn-resigned.app/Info.plist
>> macaca-ios.js:250:12 [master] pid:86802 App "com.XXX.XXX" is already installed.
>> macaca-ios.js:251:12 [master] pid:86802 Adopting app reuse strategy: 1.
>> macaca-ios.js:258:18 [master] pid:86802 Uninstall app "com.XXX.XXX".

**Comment by paradite** [comment]
@xinxinga  改下`desiredCapabilities `里面的`bundleId `试试。

**Comment by xinxinga** [comment]
> @xinxinga 改下`desiredCapabilities `里面的`bundleId `试试。
改成什么？ bundleId 是测试app的正确显示，我只是在这里提issue用xxx.xxx代替了

**Comment by xinxinga** [comment]
错误应该不在bundleId，根据log显示，没安装-》就去安装，提示已安装-》就先uninstall，再install...这块都能正确处理。测试app 能够正确安装，并成功launch，但是之后log就报错了，case没办法运行
proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET

**Comment by paradite** [comment]
@xinxinga 你这个看不出错误啊，`read ECONNRESET`后面不是又有新的log了吗？还是中间你操作了？
有同学反映改`bundleId`就行了，随便什么都行，你试试。具体为什么我也不明白。我不是iOS开发。

**Comment by xinxinga** [comment]
xcode 里运行也正常
```
2019-05-29 18:00:00.083082+0800 XCTestWDUITests-Runner[2508:144123] +[CATransaction synchronize] called within transaction
2019-05-29 18:00:00.147444+0800 XCTestWDUITests-Runner[2508:144123] Running tests...
2019-05-29 18:00:00.689441+0800 XCTestWDUITests-Runner[2508:144123] Continuing to run tests in the background with task ID 1
Test Suite 'Selected tests' started at 2019-05-29 18:00:01.330
Test Suite 'XCTestWDUITests.xctest' started at 2019-05-29 18:00:01.333
Test Suite 'XCTextWDRunner' started at 2019-05-29 18:00:01.333
Test Case '-[XCTestWDUITests.XCTextWDRunner testRunner]' started.
    t =     0.00s Start Test at 2019-05-29 18:00:01.337
    t =     0.20s Set Up
2019-05-29 18:00:01.621452+0800 XCTestWDUITests-Runner[2508:144123] initializing wd server
2019-05-29 18:00:01.631511+0800 XCTestWDUITests-Runner[2508:144123] check log dir @:["/var/mobile/Containers/Data/Application/2A2E5621-703E-4494-B07A-EABFABE8E4BA/Documents"]
2019-05-29 18:00:01:640 XCTestWDUITests-Runner[2508:144123] XCTestWD-Debug-Info: 
setup debug log
2019-05-29 18:00:01.641814+0800 XCTestWDUITests-Runner[2508:144151] XCTestWD-Debug-Info: 
setup debug log
2019-05-29 18:00:01.666210+0800 XCTestWDUITests-Runner[2508:144123] com.apple.test.XCTestWDUITests-Runner
2019-05-29 18:00:01.666445+0800 XCTestWDUITests-Runner[2508:144123] XCTestWDSetup->http://localhost:8001<-XCTestWDSetup
```

**Comment by xinxinga** [comment]
> @xinxinga 你这个看不出错误啊，`read ECONNRESET`后面不是又有新的log了吗？还是中间你操作了？
> 有同学反映改`bundleId`就行了，随便什么都行，你试试。具体为什么我也不明白。我不是iOS开发。

`read ECONNRESET`一直是这个错，retry 10次 就结束了，我中间没有做操作，测试完全没有执行。
`bundleId` 在哪儿改？

**Comment by paradite** [comment]
@xinxinga 在配置driver的时候应该有设置的：
https://macacajs.github.io/guide/helpful-settings.html#desired-capabilities
你只跑了`macaca server`？还有个client在跑，给server提供这些参数。

**Comment by paradite** [comment]
你的log是完整的嘛？如果报错应该停在
`proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET
`
但是你的log是接着跑的啊，最后是
`macaca-ios.js:258:18 [master] pid:86802 Uninstall app "com.XXX.XXX".`
你具体是怎么执行的？是不是有别的脚本在跑？

**Comment by xinxinga** [comment]
> @xinxinga 在配置driver的时候应该有设置的：
> https://macacajs.github.io/guide/helpful-settings.html#desired-capabilities
> 你只跑了`macaca server`？还有个client在跑，给server提供这些参数。

我是跑了client test 的，我前面说了，我执行测试，但是case完全跑不起来。
如果单纯macaca server, log 就只有：
```
>> index.js:15:12 [master] pid:6636 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '192.168.0.103',
  host: '34363bc9e554.ant.amazon.com',
  loaded_time: '2019-05-29 19:44:20' }
>> middlewares.js:17:10 [master] pid:6636 base middlewares attached
>> router.js:132:10 [master] pid:6636 router set
>> Macaca server started
```

**Comment by xinxinga** [comment]
> 你的log是完整的嘛？如果报错应该停在
> `proxy.js:63:22 [master] pid:86802 xctest client proxy error with: Error: read ECONNRESET `
> 但是你的log是接着跑的啊，最后是
> `macaca-ios.js:258:18 [master] pid:86802 Uninstall app "com.XXX.XXX".`
> 你具体是怎么执行的？是不是有别的脚本在跑？

是的，我在跑测试case，只是一直跑不起来，提示read ECONNRESET

**Comment by xinxinga** [comment]
> @xinxinga 在配置driver的时候应该有设置的：
> https://macacajs.github.io/guide/helpful-settings.html#desired-capabilities
> 你只跑了`macaca server`？还有个client在跑，给server提供这些参数。

回答上面的问题：
desired-capabilities 里面没有设置bundleId. 
bundleId是在macaca-ios.js里面获取的， 代码如下：
```
else if (app) {
    this.bundleId = yield iOSUtils.getBundleId(app);
```
同时，log 显示：
```
>> macaca-ios.js:250:12 [master] pid:6636 App "com.xxx.XXX" is already installed.
>> macaca-ios.js:251:12 [master] pid:6636 Adopting app reuse strategy: 1.
>> macaca-ios.js:258:18 [master] pid:6636 Uninstall app "com.xxx.XXX"".
>> macaca-ios.js:260:18 [master] pid:6636 Install app 'com.xxx.XXX"' successfully.
```
也可以看一下我的测试代码：
```
        for item in recd_file_content:
            if 0 == item.find("client_devicename"):    
                desired_caps["deviceName"] = item.split(":")[-1]
      
            if 0 == item.find("client_platformname"):
                # due to Macaca limit of supported platforms [android, chrome, electron, ios, puppeteer]
                # no matter what the input platform is, change it to android or ios
                # no consideration of mobile browser here
                pattern_list = []
                pattern_list = re.findall(r'[Aa][Nn][Dd][Rr][Oo][Ii][Dd]|[Ii][Oo][Ss]', item.split(":")[-1])
                desired_caps["platformName"] = pattern_list[0].lower()
            
            if 0 == item.find("client_deviceid"):
                desired_caps["udid"] = item.split(":")[-1]

            if 0 == item.find("client_browsername"):
                desired_caps["browserName"] = item.split(":")[-1]
 
            if 0 == item.find("client_app"):
                desired_caps["app"] = item.split(":")[-1]

        return desired_caps            
```

**Comment by paradite** [comment]
光这么看也看不出哪里的问题，如果能有最小的复现问题的例子我可以试试看哪里的问题。
建议1:试试虚拟机，看看是不是同样有问题。有可能是真机证书问题。
建议2:试试自己加入`bundleId `，看看问题是不是还有。有同学同样问题加了这个就好了。

**Comment by xinxinga** [comment]
> 光这么看也看不出哪里的问题，如果能有最小的复现问题的例子我可以试试看哪里的问题。
> 建议1:试试虚拟机，看看是不是同样有问题。有可能是真机证书问题。
> 建议2:试试自己加入`bundleId `，看看问题是不是还有。有同学同样问题加了这个就好了。

（1）
首先我确认不是证书问题。最近一直在做测试，每天都在跑测试的。只是这个问题原来没这么严重，比如10次有3次跑不起来。但是昨天到今天大概就是99%跑不起来。。。所以搞不明白是什么原因，

我的环境最大的改动，就是mac os 从10.14.4 升级到10.14.5， 另外这个问题卡住以后，我尝试了npm i macaca-ios -g, cnpm i macaca-ios -g, 都不行。
但同时 app-inspector 是好使的。

（2）
刚刚尝试加了bundleId ，不解决问题😔

**Comment by paradite** [comment]
那大概率是新的macOS的问题了。我们这面最近都没有更新代码。我让负责iOS的同学看看哈。

**Comment by xinxinga** [comment]
> 那大概率是新的macOS的问题了。我们这面最近都没有更新代码。我让负责iOS的同学看看哈。

谢谢，这个问题卡住，影响了最近的测试。
希望能尽快找到解决办法。

**Comment by fifi0526** [comment]
不过我的电脑没有更新系统，mac os还是：10.14.4，今天下午就突然不能运行了，和上面日志报错一样
PS：之前改bundleid正常了是改的Xcode里面wd的bundleid，但是今天再试这种方法就不行了

**Comment by XinxingAn** [comment]
Any progress for this issue?

**Comment by paradite** [comment]
@fifi0526 看看是不是已知问题，如果不是已知问题，请另外开一个issue：
https://github.com/alibaba/macaca/issues/929

**Comment by paradite** [comment]
@XinxingAn 你的macOS版本和XCode版本分别是什么？

**Comment by XinxingAn** [comment]
> @XinxingAn 你的macOS版本和XCode版本分别是什么？

macOS 10.14.5, Xcode 10.2

**Comment by XinxingAn** [comment]
also tried Xcode 10.2.1 + macOS 10.14.5, met the same problem

**Comment by paradite** [comment]
@xinxinga @XinxingAn  你们的问题只是iOS真机吗？我这面测试Xcode 10.2 + macOS 10.14.5，用iOS模拟器是可以的。

**Comment by XinxingAn** [comment]
> @xinxinga @XinxingAn 你们的问题只是iOS真机吗？我这面测试Xcode 10.2 + macOS 10.14.5，用iOS模拟器是可以的。

是的，我在真机上测试的，因为我们有些测试需要和第三方交互。模拟器没办法

**Comment by XinxingAn** [comment]
Update: 
1) 我尝试了sample test, 中间也出现这个error,但是过一会 就好了，可以继续跑测试。
而我跑自己的测试case，就hang在那里，一直是error

```
macaca server --verbose
>> index.js:15:12 [master] pid:25406 webdriver server start with config:
 { port: 3456,
  verbose: true,
  always: true,
  ip: '192.168.13.164',
  host: '34363bc9e554.ant.xxx.com',
  loaded_time: '2019-06-05 13:35:20' }
>> middlewares.js:17:10 [master] pid:25406 base middlewares attached
>> router.js:132:10 [master] pid:25406 router set
>> Macaca server started
>> responseHandler.js:11:12 [master] pid:25406 Recieve HTTP Request from Client[2019-06-05 13:35:26]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"deviceName":"iPhone 6s","app":"https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip","platformName":"iOS"}}
>> session.js:58:10 [master] pid:25406 Creating session, sessionId: 59900ece-81dc-43ea-bc0a-79f835bab14b.
/Users/xinxinga/npm-global/lib/node_modules/macaca-ios/node_modules/_ios-device@1.0.0@ios-device/node_modules/ios-deploy/build/Release/ios-deploy
>> get /Users/xinxinga/.macaca-temp/ios-app-bootstrap.zip from cache
>> sha:d2e65bba467659ef610b369f2ee599c1
>> helper.js:193:14 [master] pid:25406 Unzipping local app form /Users/xinxinga/.macaca-temp/ios-app-bootstrap.zip
>> macaca-ios.js:223:10 [master] pid:25406 Get available devices [{"name":"iPhone 5s","udid":"D292981B-C6A6-4C05-8035-A942CA1044D8","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone 6","udid":"3477AC99-84E1-4BB7-ADD4-C192B5113A07","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone 6 Plus","udid":"C5397801-A991-4494-97B5-151FA9E8109C","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone 6s","udid":"8BCE6BCC-76B8-4BD9-A368-C7EF3B7A4955","state":"Booted","available":true,"runtime":"iOS 12.2"},{"name":"iPhone 6s Plus","udid":"2B0FBC88-BF5A-457C-B143-09B06E1742FC","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone 7","udid":"73350A28-5860-4EE3-9010-1ACE7B6CFAC7","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone 7 Plus","udid":"4D63870D-76FB-4A5B-8104-9A9BFC44D9AA","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone 8","udid":"9B0FF811-C3E4-4780-BD27-69D06485278A","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone 8 Plus","udid":"549DA0F2-6199-4F0C-80B2-B54B33B5CB43","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone SE","udid":"A17A3169-BFC4-441C-9884-D3A26540A0AC","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone X","udid":"7A47C7C8-80C0-4012-96FF-60207FBEDB6E","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone Xs","udid":"6BA653E7-2C2E-4C6C-AE20-D28E0F29A45B","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone Xs Max","udid":"12A6A86E-D6DC-4DF2-A4FC-32B2FCF88C8C","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPhone Xʀ","udid":"18245142-90AE-4C99-9A4A-491E3064090E","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPad Air","udid":"30FDAF92-3B19-4038-818E-0DC4740EDD37","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"iPad Air 2","udid":"09A51F9A-ACCA-4331-BE0A-F45EC681A0F6","state":"Shutdown","available":true,"runtime":"iOS 12.2"},{"name":"Apple TV","udid":"4C083B0D-94E4-45A6-8DFF-3FBD68499461","state":"Shutdown","available":true,"runtime":"tvOS 12.2"},{"name":"Apple TV 4K","udid":"3B733BB9-E54C-4EE7-89A7-0B49285315D3","state":"Shutdown","available":true,"runtime":"tvOS 12.2"},{"name":"Apple Watch Series 2 - 38mm","udid":"1E30DB30-114C-4A3E-9AB4-F43E952323BC","state":"Shutdown","available":true,"runtime":"watchOS 5.2"},{"name":"Apple Watch Series 2 - 42mm","udid":"5378F2DC-5196-4D90-A1DF-C31F3164BC1B","state":"Shutdown","available":true,"runtime":"watchOS 5.2"},{"name":"Apple Watch Series 3 - 38mm","udid":"532CEA4D-3D0F-4E1C-9019-5BD8AFF1EC81","state":"Shutdown","available":true,"runtime":"watchOS 5.2"},{"name":"Apple Watch Series 3 - 42mm","udid":"AEAC86E5-5468-45AA-9E83-5A52FB216340","state":"Shutdown","available":true,"runtime":"watchOS 5.2"},{"name":"Apple Watch Series 4 - 40mm","udid":"0FF27D48-F91D-4337-BAA3-9F5DD922C9E7","state":"Shutdown","available":true,"runtime":"watchOS 5.2"},{"name":"Apple Watch Series 4 - 44mm","udid":"00888560-3C99-4BDD-855B-D2EB2482A1EB","state":"Shutdown","available":true,"runtime":"watchOS 5.2"}]
CFBundleIdentifier is xudafeng.ios-app-bootstrap
Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/gl/xnl6szq165q_yw__4sdb7bzxygppcv/T/ios-app-bootstrap.app/Info.plist
>> macaca-ios.js:163:10 [master] pid:25406 {
	"bundleId": "xudafeng.ios-app-bootstrap",
	"app": "/var/folders/gl/xnl6szq165q_yw__4sdb7bzxygppcv/T/ios-app-bootstrap.app/",
	"platformName": "iOS"
}
>> xctest-client.js:56:14 [master] pid:25406 project path: /Users/xinxinga/npm-global/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:172:12 [master] pid:25406 Trying to start xctestwd server...
>> xctest-client.js:283:14 [master] pid:25406 xcode version: 10.2.1
>> XCTestWD version: 1.4.18
>> xctest-client.js:227:20 [master] pid:25406 hitted for default mode
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:25406 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"xudafeng.ios-app-bootstrap","app":"/var/folders/gl/xnl6szq165q_yw__4sdb7bzxygppcv/T/ios-app-bootstrap.app/","platformName":"iOS"}}
>> xctest-client.js:230:20 [master] pid:25406 please check project: /Users/xinxinga/npm-global/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:25406 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:230:20 [master] pid:25406 please check project: /Users/xinxinga/npm-global/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:85:20 [master] pid:25406 Got response with status 200: {"sessionId":null,"value":{"sessionId":"9E97F92F-7438-4938-A6F5-2C316026FEBF","capabilities":{"device":"iphone","browserName":"Bootstrap","sdkVersion":"12.2","CFBundleIdentifier":"xudafeng.ios-app-...
>> responseHandler.js:49:14 [master] pid:25406 Send HTTP Respone to Client[2019-06-05 13:36:39]: {"sessionId":"59900ece-81dc-43ea-bc0a-79f835bab14b","status":0,"value":"{\"deviceName\":\"iPhone 6s\",\"app\":\"/var/folders/gl/xnl6szq165q_yw__4sdb7bzxygppcv/T/ios-app-bootstrap.app/\",\"platformName\":\"iOS\"}"}
>> responseHandler.js:11:12 [master] pid:25406 Recieve HTTP Request from Client[2019-06-05 13:36:39]: method: POST url: /wd/hub/session/59900ece-81dc-43ea-bc0a-79f835bab14b/element, jsonBody: {"using":"xpath","value":"//XCUIElementTypeTextField[1]"}
>> proxy.js:55:14 [master] pid:25406 Proxy: /wd/hub/session/59900ece-81dc-43ea-bc0a-79f835bab14b/element:POST to http://127.0.0.1:8001/wd/hub/session/9E97F92F-7438-4938-A6F5-2C316026FEBF/element:POST with body: {"using":"xpath","value":"//XCUIElementTypeTextField[1]"}
>> proxy.js:85:20 [master] pid:25406 Got response with status 200: {"status":0,"value":{"type":"XCUIElementTypeTextField","ELEMENT":"4A4146B8-B02D-4500-9A18-C131D9B88245","label":""},"sessionId":""}
>> session.js:120:14 [master] pid:25406 Send HTTP Respone to Client[2019-06-05 13:36:39]: {"status":0,"value":"{\"type\":\"XCUIElementTypeTextField\",\"ELEMENT\":\"4A4146B8-B02D-4500-9A18-C131D9B88245\",\"label\":\"\"}","sessionId":""}
>> responseHandler.js:11:12 [master] pid:25406 Recieve HTTP Request from Client[2019-06-05 13:36:39]: method: POST url: /wd/hub/session/59900ece-81dc-43ea-bc0a-79f835bab14b/element/4A4146B8-B02D-4500-9A18-C131D9B88245/value, jsonBody: {"value":["中文+Test+12345678"]}
>> proxy.js:55:14 [master] pid:25406 Proxy: /wd/hub/session/59900ece-81dc-43ea-bc0a-79f835bab14b/element/4A4146B8-B02D-4500-9A18-C131D9B88245/value:POST to http://127.0.0.1:8001/wd/hub/session/9E97F92F-7438-4938-A6F5-2C316026FEBF/element/4A4146B8-B02D-4500-9A18-C131D9B88245/value:POST with body: {"value":["中文+Test+12345678"]}
>> proxy.js:85:20 [master] pid:25406 Got response with status 200: {"status":0,"value":"","sessionId":""}
>> session.js:120:14 [master] pid:25406 Send HTTP Respone to Client[2019-06-05 13:36:41]: {"status":0,"value":"","sessionId":""}
>> responseHandler.js:11:12 [master] pid:25406 Recieve HTTP Request from Client[2019-06-05 13:36:41]: method: POST url: /wd/hub/session/59900ece-81dc-43ea-bc0a-79f835bab14b/element, jsonBody: {"using":"xpath","value":"//XCUIElementTypeSecureTextField[1]"}
>> proxy.js:55:14 [master] pid:25406 Proxy: /wd/hub/session/59900ece-81dc-43ea-bc0a-79f835bab14b/element:POST to http://127.0.0.1:8001/wd/hub/session/9E97F92F-7438-4938-A6F5-2C316026FEBF/element:POST with body: {"using":"xpath","value":"//XCUIElementTypeSecureTextField[1]"}
>> proxy.js:85:20 [master] pid:25406 Got response with status 200: {"status":0,"value":{"ELEMENT":"10F5069B-F316-492C-88BF-73814F0D0F69","type":"XCUIElementTypeSecureTextField","label":""},"sessionId":""}
>> session.js:120:14 [master] pid:25406 Send HTTP Respone to Client[2019-06-05 13:36:41]: {"sta
```

**Comment by XinxingAn** [comment]
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:25406 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"xudafeng.ios-app-bootstrap","app":"/var/folders/gl/xnl6szq165q_yw__4sdb7bzxygppcv/T/ios-app-bootstrap.app/","platformName":"iOS"}}
>> xctest-client.js:230:20 [master] pid:25406 please check project: /Users/xinxinga/npm-global/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:25406 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:230:20 [master] pid:25406 please check project: /Users/xinxinga/npm-global/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:85:20

**Comment by XinxingAn** [comment]
在模拟器上跑了sample test, 虽然有同样的error，但是还是可以继续跑测试case。
在模拟器和真机上，尝试自己的测试case，就卡了，一直报error.
测试机的现象就是，被测试app安装，launch，然后被卸载。。

**Comment by XinxingAn** [comment]
有人帮忙跟踪处理吗？

**Comment by paradite** [comment]
在跟进，耐心等待一下。sample可以跑的话，你的teat不能跑的话，需要看看你的test有什么问题。我们只能修复到sample可以跑起来。

**Comment by XinxingAn** [comment]
sample test 可以跑，能看到同样的error:
proxy.js:63:22 [master] pid:25406 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
xctest-client.js:230:20 [master] pid:25406 please check project: /Users/xinxinga/npm-global/lib/node_modules/macaca-ios/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
proxy.js:85:20

我自己的测试原来也是这样的现象，等待一会就可以跑测试，但是从某一天开始，就hang在这里了。。

**Comment by mahalo777** [comment]
same error

**Comment by paradite** [comment]
在最新的xcode 11下修复了，大家试一下。 @xinxinga @mahalo777

**Comment by mahalo777** [comment]
> 在最新的xcode 11下修复了，大家试一下。 @xinxinga @mahalo777

你好，请问我只需要更新xcode11吗？我这边更新后，报错：Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/arm64.swiftmodule

**Comment by paradite** [comment]
> @paradite
> 你好，请问我只需要更新xcode11吗？我这边更新后，报错：Module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /usr/local/lib/node_modules/macaca-ios/node_modules/xctestwd/Carthage/Build/iOS/Swifter.framework/Modules/Swifter.swiftmodule/arm64.swiftmodule

这应该是因为之前老的全局安装没有更新，可以手动删除，重新安装
```
npm uninstall -g macaca-ios
npm uninstall -g ...

npm i -g macaca-ios
npm i -g ...
```

**Comment by mahalo777** [comment]
你好。
1.  我重新安装后macaca-ios报错和之前一样：
`Fail to start xctest: Error: read ECONNRESET
xctest client proxy error with: Error: read ECONNRESET`
我的应用可以被打开，但是会一直卡在第一个页面。然后重复安装，停止。我检查了签名应该没问题。
2. 我怀疑是使用scheme 为release的包，换包后，会报错。
`xctest-client.js:242:16 [master] pid:9088 xctest client exit with code: 65, signal: null
>> xctest-client.js:272:14 [master] pid:9088 iproxy exit with code: null, signal: SIGKILL`
应用页面报错`No bundle url present`
您看要提供什么吗？辛苦帮我看下，谢谢🙏

**Comment by LongXiangGuo** [comment]
请问`npm uninstall -g ...` 后面 `...`代表了哪些依赖？
