### ISSUE TITLE
Send Error Respone to Client: Error: read ECONNRESET

### ISSUE THREAD

**Issue by fifi0526** [alibaba/macaca#930]
* **Macaca Version**:2.0.16

* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.16

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v12.1.0

  iOS checklist:

  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.2
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `12`
  JAVA_HOME is not set
  ANDROID_HOME is not set
  Command Line Tools: gradle is uninstalled

  Installed driver list:

  ios: 2.0.35
  location: /Users/zhangfeifei/macaca-lianjia/node_modules/_macaca-ios@2.0.35@macaca-ios

* **Operate System**:mac os:10.14.4

* **Programming Language**:python

log：
>> index.js:15:12 [master] pid:14095 webdriver server start with config:
 {
  port: 3456,
  verbose: true,
  always: true,
  ip: '10.33.132.141',
  host: 'fifideMacBook-Pro.local',
  loaded_time: '2019-05-30 15:11:52'
}
>> middlewares.js:17:10 [master] pid:14095 base middlewares attached
>> router.js:132:10 [master] pid:14095 router set
>> Macaca server started
>> responseHandler.js:11:12 [master] pid:14095 Recieve HTTP Request from Client[2019-05-30 15:12:12]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","deviceName":"iPhone","bundleId":"com.xxx.xxx","udid":"xxxxxxxxxxx","autoAcceptAlerts":"false"}}
>> session.js:58:10 [master] pid:14095 Creating session, sessionId: 9a25ae81-3176-4774-bb9a-5d1d19c8ab3b.
/Users/zhangfeifei/macaca-lianjia/node_modules/_ios-device@1.0.0@ios-device/node_modules/ios-deploy/build/Release/ios-deploy
>> macaca-ios.js:250:12 [master] pid:14095 App "com.xxx.xxx" is already installed.
>> macaca-ios.js:251:12 [master] pid:14095 Adopting app reuse strategy: 1.
BundleId XCTestWD.XCTestWD does not exist.
>> macaca-ios.js:162:10 [master] pid:14095 {
	"bundleId": "com.xxx.xxx",
	"platformName": "iOS"
}
>> xctest-client.js:56:14 [master] pid:14095 project path: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:171:12 [master] pid:14095 Trying to start xctestwd server...
>> xctest-client.js:283:14 [master] pid:14095 xcode version: 10.2
>> XCTestWD version: 1.4.18
>> xctest-client.js:227:20 [master] pid:14095 hitted for default mode
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:14095 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.xxx.xxx","platformName":"iOS"}}
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:322:14 [master] pid:14095 killing runnerProc pid: 14117
>> xctest-client.js:328:14 [master] pid:14095 killing iproxyProc pid: 14374
>> xctest-client.js:242:16 [master] pid:14095 xctest client exit with code: 65, signal: null
>> xctest-client.js:272:14 [master] pid:14095 iproxy exit with code: null, signal: SIGKILL
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:309:14 [master] pid:14095 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:8001
>> macaca-ios.js:171:12 [master] pid:14095 Trying to start xctestwd server...
>> xctest-client.js:283:14 [master] pid:14095 xcode version: 10.2
>> XCTestWD version: 1.4.18
>> xctest-client.js:227:20 [master] pid:14095 hitted for default mode
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:14095 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.xxx.xxx","platformName":"iOS"}}
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:322:14 [master] pid:14095 killing runnerProc pid: 14380
>> xctest-client.js:328:14 [master] pid:14095 killing iproxyProc pid: 14650
>> xctest-client.js:242:16 [master] pid:14095 xctest client exit with code: 65, signal: null
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:272:14 [master] pid:14095 iproxy exit with code: null, signal: SIGKILL
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:309:14 [master] pid:14095 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:8001
>> macaca-ios.js:171:12 [master] pid:14095 Trying to start xctestwd server...
>> xctest-client.js:283:14 [master] pid:14095 xcode version: 10.2
>> XCTestWD version: 1.4.18
>> xctest-client.js:227:20 [master] pid:14095 hitted for default mode
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:14095 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.xxx.xxx","platformName":"iOS"}}
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> responseHandler.js:11:12 [master] pid:14095 Recieve HTTP Request from Client[2019-05-30 15:14:12]: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformName":"iOS","deviceName":"iPhone","bundleId":"com.xxx.xxx","udid":"xxxxxxxxx","autoAcceptAlerts":"false"}}
>> session.js:58:10 [master] pid:14095 Creating session, sessionId: 342dc57b-1270-4e19-bb3f-418470a6618f.
>> macaca-ios.js:250:12 [master] pid:14095 App "com.xxx.xxx" is already installed.
>> macaca-ios.js:251:12 [master] pid:14095 Adopting app reuse strategy: 1.
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
BundleId XCTestWD.XCTestWD does not exist.
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:322:14 [master] pid:14095 killing runnerProc pid: 14655
>> xctest-client.js:328:14 [master] pid:14095 killing iproxyProc pid: 14912
>> xctest-client.js:242:16 [master] pid:14095 xctest client exit with code: 65, signal: null
>> xctest-client.js:272:14 [master] pid:14095 iproxy exit with code: null, signal: SIGKILL
>> macaca-ios.js:162:10 [master] pid:14095 {
	"bundleId": "com.xxx.xxx",
	"platformName": "iOS"
}
>> xctest-client.js:56:14 [master] pid:14095 project path: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> macaca-ios.js:171:12 [master] pid:14095 Trying to start xctestwd server...
>> xctest-client.js:283:14 [master] pid:14095 xcode version: 10.2
>> XCTestWD version: 1.4.18
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:227:20 [master] pid:14095 hitted for default mode
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:14095 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.xxx.xxx","platformName":"iOS"}}
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:322:14 [master] pid:14095 killing runnerProc pid: 14919
>> xctest-client.js:328:14 [master] pid:14095 killing iproxyProc pid: 15171
>> xctest-client.js:242:16 [master] pid:14095 xctest client exit with code: 65, signal: null
>> xctest-client.js:272:14 [master] pid:14095 iproxy exit with code: null, signal: SIGKILL
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:309:14 [master] pid:14095 Fail to start xctest: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:227:20 [master] pid:14095 hitted for default mode
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctestwd start with port: 8001
>> proxy.js:55:14 [master] pid:14095 Proxy: /wd/hub/session:POST to http://127.0.0.1:8001/wd/hub/session:POST with body: {"desiredCapabilities":{"bundleId":"com.lianjia.beike","platformName":"iOS"}}
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> xctest-client.js:230:20 [master] pid:14095 please check project: /Users/zhangfeifei/macaca-lianjia/node_modules/_xctestwd@1.4.18@xctestwd/XCTestWD/XCTestWD.xcodeproj
>> proxy.js:63:22 [master] pid:14095 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:309:14 [master] pid:14095 Fail to start xctest: Error: read ECONNRESET
>> responseHandler.js:56:12 [master] pid:14095 Send Error Respone to Client: Error: read ECONNRESET
>> responseHandler.js:62:14 [master] pid:14095 Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)

  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:183:27)

**Comment by paradite** [comment]
是突然不能用了嘛？还是第一次用？
如果是真机的话看看是不是配置问题：https://macacajs.github.io/guide/environment-setup.html#ios-real-device
可以试试用iOS的虚拟机跑下sample。我用XCode 10.2，macOS 10.14.4跑sample是正常的：
https://github.com/macaca-sample/sample-nodejs

**Comment by fifi0526** [comment]
官方sample可以运行模拟器，但是真机运行不了。
是突然不行的，昨日上午还可以运行，下午就不可以了。
真机环境配置的没有问题，证书和bundleid均已配置。

**Comment by paradite** [comment]
@fifi0526 那用模拟器运行你的case呢？
我和你同样的环境并没有问题，最近也没有发布新的代码。这个问题就比较诡异了。

**Comment by fifi0526** [comment]
我重新安装了macaca，配置真机后跑了一次case，可以运行成功，但是再等我第二次运行的时候，就一直失败，一直在重新卸载、安装我要测试的app，日志如下：
![image](https://user-images.githubusercontent.com/34715065/58851147-23921900-86c4-11e9-9c83-4006fc20f189.png)

**Comment by SamuelZhaoY** [comment]
Tried to reproduce your issue, on Xcode 10.2.1  on iPhoneX, but seems it is working fine on my device.

`$ ./curlTests.sh

#### Create Session ####
{"status":0,"value":{"capabilities":{"sdkVersion":"12.3.1","browserName":"Safari","CFBundleIdentifier":"com.apple.mobilesafari","device":"iphone"},"sessionId":"6FDBD2F3-1909-4D56-B23E-CF85DA6377CE"},"sessionId":"6FDBD2F3-1909-4D56-B23E-CF85DA6377CE"}

input the sessionID generated:

6FDBD2F3-1909-4D56-B23E-CF85DA6377CE

#### Query Session ####
{"status":0,"value":[{"id":"6FDBD2F3-1909-4D56-B23E-CF85DA6377CE"}],"sessionId":""}{"status":0,"value":[{"ELEMENT":"1C085A77-D114-4E03-9F0B-DAA861F6846E","type":"XCUIElementTypeTextField","label":""}],"sessionId":""}

input the elementID generated:

1C085A77-D114-4E03-9F0B-DAA861F6846E
{"value":"","sessionId":"","status":0}
#### Check Source ####
{"status":0,"value":{"frame":"{{0, 0}, {375, 812}}","label":"Safari","children":[{"frame":"{{0, 0}, {375, 812}}","rect":{"width":375,"x":0,"y":0,"height":812},"isVisible":true,"children":[{"children":[{"fra`

You may need to check open the xcode and execute the test case and feedback on which line gives the error. https://github.com/macacajs/XCTestWD#4-common-issues

**Comment by mahalo777** [comment]
same error in

**Comment by paradite** [comment]
It should be fixed by now. refer to https://github.com/alibaba/macaca/issues/929 for current known issues.
Create a new issue if it is not there.
