### ISSUE TITLE
关于reliable与macaca 无缝融合的测试结果反馈策略能否分享一下详细的融合过程，我自己探索了好多天了，都没有达到目标

### ISSUE THREAD

**Issue by wenzhaoxian** [alibaba/macaca#933]
* **Macaca Version**:  2.1.12
* **reliable-web Version**:reliable-web: 1.0.0 (用docker方式部署 )

* **Macaca Doctor Logs**: 
  macaca-doctor version: 2.0.18

  Node.js checklist:

  node env: A:\node\node.exe
  node version: v8.16.0

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `C:\Program Files\Java\jdk1.8.0_201`
  ANDROID_HOME is set to `E:\android-sdk`
  Platforms is set to `E:\android-sdk\platforms\android-29`
  ADB tool is set to `E:\android-sdk\platform-tools\adb.exe`
  GRADLE_HOME is set to `C:\gradle\gradle-5.4.1`

  Installed driver list:

  android: 2.1.0
  location: A:\node\node_global\node_modules\macaca-android

* **Operate System*:windows 10

* **Programming Language**: node.js
图一是我想期待用macaca 工具集成汇总到reliable的结果：
![image](https://user-images.githubusercontent.com/48466044/60479346-1f9fe980-9cb8-11e9-98ea-322e9220abea.png)

图二是 我目前搭建好的reliable ：
![image](https://user-images.githubusercontent.com/48466044/60479413-5544d280-9cb8-11e9-85a0-30ec279e0193.png)

是不是reliable升级了以后没有办法提供以前（就是我们期待的功能了呢）

**Comment by paradite** [comment]
参考这里吧： https://testerhome.com/topics/19743
有什么问题继续反馈。
> reliable升级了以后没有办法提供以前（就是我们期待的功能了呢）
是的。有些功能没有了。
