### ISSUE TITLE
app-inspector ios 真机连接失败

### ISSUE THREAD

**Issue by eblis0n** [alibaba/macaca#937]
eblisdeMacBook-Air:~ eblis$ app-inspector  -u 644379335e56dde99778c8165bf8  --verbose
>> server.js:16:12 [master] pid:3155 server start with config:
 { port: 5678,
  verbose: true,
  udid: '644379335e56dde99778c8165bf8',
  ip: '192.168.26.37',
  host: 'eblisdeMacBook-Air.local',
  loaded_time: '2019-07-18 13:49:42' }
>> app-inspector.js:45:12 [master] pid:3155 server start at: http://192.168.26.37:5678
>> xctest-client.js:56:14 [master] pid:3155 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:283:14 [master] pid:3155 xcode version: 10.2.1
>> XCTestWD version: 1.4.18
>> xctest-client.js:227:20 [master] pid:3155 hitted for default mode
>> xctest-client.js:230:20 [master] pid:3155 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:309:14 [master] pid:3155 Fail to start xctest: Error: Command failed: which iproxy

>> xctest-client.js:322:14 [master] pid:3155 killing runnerProc pid: 3158
{ Error: Command failed: which iproxy

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5) killed: false, code: 1, signal: null, cmd: 'which iproxy' }
>> iOS device started: 644379335e56dde9fc302354d9ff9778c8165bf8
>> inspector start at: http://192.168.26.37:5678
>> xctest-client.js:242:16 [master] pid:3155 xctest client exit with code: null, signal: SIGKILL
  <-- GET /
>> helper.js:94:16 [master] pid:3155 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001

  Error: connect ECONNREFUSED 127.0.0.1:8001
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

eblisdeMacBook-Air:~ eblis$ app-inspector  -u 644379335e56dde9fc302354d9ff9778c8165bf8  --verbose
>> server.js:16:12 [master] pid:3155 server start with config:
 { port: 5678,
  verbose: true,
  udid: '644379335e56dde9fc302354d9ff9778c8165bf8',
  ip: '192.168.26.37',
  host: 'eblisdeMacBook-Air.local',
  loaded_time: '2019-07-18 13:49:42' }
>> app-inspector.js:45:12 [master] pid:3155 server start at: http://192.168.26.37:5678
>> xctest-client.js:56:14 [master] pid:3155 project path: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:283:14 [master] pid:3155 xcode version: 10.2.1
>> XCTestWD version: 1.4.18
>> xctest-client.js:227:20 [master] pid:3155 hitted for default mode
>> xctest-client.js:230:20 [master] pid:3155 please check project: /usr/local/lib/node_modules/app-inspector/node_modules/xctestwd/XCTestWD/XCTestWD.xcodeproj
>> xctest-client.js:309:14 [master] pid:3155 Fail to start xctest: Error: Command failed: which iproxy

**Comment by carmensmile** [comment]
I got the same issue. but I found I change the network. the host changed from xxxx.local to xxxx.lan, it works for me. Most the time, the host is xxxx.local. I don't know what's difference between local and lan.

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/929
