### ISSUE TITLE
Android driver.send_keys 无法输入大写字母

### ISSUE THREAD

**Issue by Jodeee** [alibaba/macaca#943]
macaca-doctor version: 2.0.18
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v10.8.0
  android: 2.1.0
  location: /usr/local/lib/node_modules/macaca-android
  Operate System:macOS
  Programming Language:Python
 driver.send_keys 无法输入大写字母,element.send_keys 正常
![image](https://user-images.githubusercontent.com/30293087/64498605-c7085080-d2e7-11e9-950a-c1f3a1385a26.png)
![IMG_20190909_095429](https://user-images.githubusercontent.com/30293087/64498630-eacb9680-d2e7-11e9-9f8c-323f5c9c73c1.jpg)

**Comment by Jodeee** [comment]
这个问题没人帮忙看下嘛

**Comment by houseshi** [comment]
> macaca-doctor version: 2.0.18
> Node.js checklist:
> node env: /usr/local/bin/node
> node version: v10.8.0
> android: 2.1.0
> location: /usr/local/lib/node_modules/macaca-android
> Operate System:macOS
> Programming Language:Python
> driver.send_keys 无法输入大写字母,element.send_keys 正常
> ![image](https://user-images.githubusercontent.com/30293087/64498605-c7085080-d2e7-11e9-950a-c1f3a1385a26.png)
> ![IMG_20190909_095429](https://user-images.githubusercontent.com/30293087/64498630-eacb9680-d2e7-11e9-9f8c-323f5c9c73c1.jpg)

driver.send_keys没有获取到具体的元素，需要先使用driver获取到一个具体的元素，在进行send_keys。
如：
driver.elementById("id").senk_keys("ID");

driver.elementById("id")  获取到的对象 = element；
所 driver.elementById("id").senk_keys("ID"); 等同于 element.send_keys("ID")

**Comment by Jodeee** [comment]
driver.elementById("id").senk_keys("ID"); 这种方式我清楚的，现在我想先点击输入框，然后在driver.send_keys（分两部执行），我看你们支持这样的，只不过输入大小写这里有点问题

**Comment by houseshi** [comment]
> This is the translated issue comment: @Jodeee
> 
> driver.elementById ( "id") senk_keys ( "ID");. I know of in this way, and now I want to click the input box, and then driver.send_keys (two minutes to perform), I see your support for this, just enter the case a little problem here


![image](https://user-images.githubusercontent.com/50022460/82038727-9084a000-96d6-11ea-9d5e-d8eac687e6af.png)

我这边试了下，是可以的 ，我这边用的java实现的。
看你的截图，是浏览器的url输入框么 ？是不是被浏览器处理掉了 ？
或者 你换个输入域试试看？
