### ISSUE TITLE
uirecorder真机录制脚本后进行回放报错

### ISSUE THREAD

**Issue by paulakisscat** [alibaba/macaca#944]
报错信息：<br/>
>>     1) "before all" hook

>>

>>
  0 passing (35s)
  1 failing
---------------------
  "before all" hook:
     Error: ENAMETOOLONG: name too long, mkdir '/Users/paulakisscat/sample-nodejs/screenshots/macaca-test/ioslogin : 13:58:43 lockdown.c:654 lockdownd_client_new(): device udid: 36cdf0e04e32a452ec61f22694efc255edfba30e13:58:43 property_list_service.c:127 internal_plist_send(): sending 327 bytes13:58:43 service.c:140 service_send(): sending 4 bytes13:58:43 service.c:140 service_send(): sending 327 bytes13:58:43 property_list_service.c:132 internal_plist_send(): sent 327 bytes13:58:43 property_list_service.c:133 internal_plist_send(): printing 327 bytes plist:<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-/'<br/>

* **Macaca Version**:
<br/>2.2.0
* **Macaca Doctor Logs**:
<br/>macaca-doctor version: 2.0.18

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v12.10.0

  iOS checklist:

  macOS version: 10.14.6
  Xcode Command Line Tools is ready, version: 2354.
  xcodebuild version: 10.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/paulakisscat/Library/Android/sdk`
  Platforms is set to `/Users/paulakisscat/Library/Android/sdk/platforms/android-29`
  ADB tool is set to `/Users/paulakisscat/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 5.6

  Installed driver list:

  android: 2.1.0
  location: /usr/local/lib/node_modules/macaca-android

  chrome: 1.1.0 [out-of-date]

  electron: 5.0.1
  location: /usr/local/lib/node_modules/macaca-electron

  ios: 2.0.36
  location: /usr/local/lib/node_modules/macaca-ios
* **Operate System**:
macOS Mojave
<br/>10.14.6
* **Programming Language**:
<br/>nodejs

**Comment by xudafeng** [comment]
看错误比较明显，尝试自己解决
