### ISSUE TITLE
npm i macaca-ios -g --verbose error

### ISSUE THREAD

**Issue by wang542413041** [alibaba/macaca#949]
* **Macaca Version**:
npm i macaca-ios -g --verbose

***  Logs**:
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.9.4 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR!
npm ERR! Failed at the ios-deploy@1.9.4 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 65, true ]
npm timing npm Completed in 25706ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wangjiawei/.npm/_logs/2019-10-22T09_54_23_488Z-debug.log

* **Operate System**:
mac os catalina 10.15
➜  ~ npm -v
6.12.0
➜  ~ node -v
v12.10.0

**Comment by paradite** [comment]
应该是`ios-deploy`这个库的catalina 10.15兼容性问题，看一下这些方案：
https://github.com/ios-control/ios-deploy/issues/387
https://github.com/ios-control/ios-deploy/issues/415

**Comment by wang542413041** [comment]
Thanks . I will try

**Comment by wang542413041** [comment]
** BUILD FAILED **


The following build commands failed:
	Ld /usr/local/lib/node_modules/macaca-ios/node_modules/ios-deploy/build/Release/ios-deploy normal x86_64
(1 failure)
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! ios-deploy@1.9.4 preinstall: `./src/scripts/check_reqs.js && xcodebuild`
npm ERR! Exit status 65
npm ERR!
npm ERR! Failed at the ios-deploy@1.9.4 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wangjiawei/.npm/_logs/2019-10-22T10_24_12_416Z-debug.log
➜  ~ ios-deploy -V
1.10.0-beta.3

**Comment by wang542413041** [comment]
I tried to download deploy@beta, But when run npm i macaca-ios -g --verbose ; ios deploy version always 1.9.4

**Comment by paradite** [comment]
you can ignore the error when installing `macaca-ios` and just run `npm -g install ios-deploy@beta`.
`macaca-ios` will automatically use the globally installed `ios-deploy`.
