### ISSUE TITLE
集成Reliable和Slave后，在Master中创建任务执行中 提示Mocha 不存在，Master 任务状态一直不更新，提示running状态

### ISSUE THREAD

**Issue by oatsuper** [alibaba/macaca#95]
* **Macaca Version**:
macaca -v 1.0.35 （之前npm i macaca－cli －g 安装的）
* **Macaca Doctor**:
Node.js checklist:

node env: /usr/local/bin/node
node version: v5.9.1

iOS checklist:

Xcode is installed at: /Applications/Xcode.app/Contents/Developer
Xcode Command Line Tools is ready, version: 2343.
ios_webkit_debug_proxy is installed at: /usr/local/bin/ios_webkit_debug_proxy

Android checklist:

JAVA version is 1.8.0_77
JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home
ANDROID_HOME is set to /Users/yanyan/Install/android-sdk-macosx
Platforms is set to /Users/yanyan/Install/android-sdk-macosx/platforms/android-23
Android tools is set to /Users/yanyan/Install/android-sdk-macosx/tools/android

Installed driver list:

android: 1.0.11
ios: 1.0.30
* **Platform**:
Mac pro
uname -r
15.2.0

flow.js:68:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 start git clone...
flow.js:82:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 YAML start parsering...
flow.js:86:14 [worker:1] pid:36967 .macaca.yml does not exists!
flow.js:91:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 start git clone success!
flow.js:94:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 start npm install...
flow.js:103:12 [worker:1] pid:36967 Task 579485f2e8397125003cab01 npm install success!
这里有个疑问，git的过程，文件是下载到我机器的哪里了呢？ 就类似于Jenkins的工作空间一样，应该有了工作路径

完成了上述git和install后
flow.js:113:12 [worker:1] pid:36967 Sending 579485f2e8397125003cab01 data...
index.js:63:14 [master] pid:36966 listening worker id: 1, pid: 36967, address: 192.168.0.103:%s%s
index.js:17:12 [worker:1] pid:36967 webdriver server start with config:
{ port: 3456,
ip: '192.168.0.103',
host: 'bogon',
loaded_time: '2016-07-24 17:14:25' }
middlewares.js:17:10 [worker:1] pid:36967 base middlewares attached
router.js:108:10 [worker:1] pid:36967 router set
webdriver sdk launched
index.js:63:14 [master] pid:36966 listening worker id: 1, pid: 36967, address: 192.168.0.103:3456
flow.js:153:14 [worker:1] pid:36967 Sending 579485f2e8397125003cab01 error data...
channel.js:73:14 [worker:1] pid:36967 
status: 'busy',
body: 'Error: spawn /usr/local/lib/node_modules/reliable-macaca-slave/node_modules/macaca-cli/node_modules/.bin/mocha ENOENT\n' }
/usr/local/lib/node_modules/reliable-macaca-slave/core/task/flow.js:173
var bodyStatus = hasError ? bodyStatus.FAILED : execInfo.status;
^
TypeError: Cannot read property 'FAILED' of undefined
at Runner. (/usr/local/lib/node_modules/reliable-macaca-slave/core/task/flow.js:173:45)
at emitTwo (events.js💯13)
at Runner.emit (events.js:185:7)
at ChildProcess. (/usr/local/lib/node_modules/reliable-macaca-slave/node_modules/macaca-cli/lib/run/index.js:79:10)
at emitTwo (events.js💯13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket. (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)

index.js:66:14 [master] pid:36966 worker disconnect
index.js:57:14 [master] pid:36966 worker fork success
index.js:70:14 [master] pid:36966 worker exit code: 1 signal: null
index.js:60:14 [master] pid:36966 worker online
关于mocha $pwd ==/usr/local/lib/node_modules

./reliable-macaca-slave/node_modules/.bin/mocha
./reliable-macaca-slave/node_modules/mocha
./reliable-macaca-slave/node_modules/mocha/bin/mocha

这个问题error怎么破呢？而且这个error 出现后，slave的连接后续会报错：

index.js:54:12 [worker:2] pid:37057 Zmq Reconnecting...
request.js:11:12 [worker:2] pid:37057 get info failed with: Error: connect ECONNREFUSED 127.0.0.1:8083
同时 master 的web 控制面板，该任务一直处于running状态，slave 断开后，处于waiting状态 
重新启动master之后，该任务还是waiting状态

**Comment by xudafeng** [comment]
@oatsuper slave 断开后running会过一段时间自动超时

**Comment by oatsuper** [comment]
我这边一直都没有超时提示 slave倒是会自动断开，但是master 的web界面在此连接后还是running状态
主要问题是mocha的错误提示，我的salve都没有正常运行

**Comment by oatsuper** [comment]
这个新版本的问题，是否已经解决呢？
