### ISSUE TITLE
iOS真机调用Java API connect ECONNREFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by sprintuu** [alibaba/macaca#951]
使用macaca server --verbos成功启动服务，但是使用Java API启动手机是出现入如下端口连接错误，但是app能够正常启动，只是连接建立失败
![image](https://user-images.githubusercontent.com/31270751/68579142-6a274300-04ae-11ea-83aa-832e6930d7bb.png)

**Comment by paradite** [comment]
请参考 issue 模版提交一下环境信息和运行的脚本/命令。

**Comment by BeForever** [comment]
macaca 版本2.2.0  macOS Mojave 10.14.6  xcode 10.3  
看起来同样的错误，求解。首先macaca server启动 端口3456，然后app-inspector 启动 端口5678，之后启动自己的脚本， “platformName”， "udid"，"bundleId","app"等必要参数全部填写完毕，软件正常安装后，真机并不会打开软件执行脚本，而报错连接失败。相同配置在模拟器可以运行。

`>> proxy.js:63:22 [master] pid:17250 xctest client proxy error with: Error: read ECONNRESET
>> proxy.js:63:22 [master] pid:17250 xctest client proxy error with: Error: read ECONNRESET
>> xctest-client.js:309:14 [master] pid:17250 Fail to start xctest: Error: read ECONNRESET
>> xctest-client.js:322:14 [master] pid:17250 killing runnerProc pid: 19492
>> xctest-client.js:328:14 [master] pid:17250 killing iproxyProc pid: 19636
>> responseHandler.js:56:12 [master] pid:17250 Send Error Respone to Client: Error: read ECONNRESET
>> responseHandler.js:62:14 [master] pid:17250 Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)

  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:201:27)

>> xctest-client.js:272:14 [master] pid:17250 iproxy exit with code: null, signal: SIGKILL
>> xctest-client.js:242:16 [master] pid:17250 xctest client exit with code: null, signal: SIGKILL
>> proxy.js:68:22 [master] pid:17250 xctest client proxy received no data.
>> proxy.js:68:22 [master] pid:17250 xctest client proxy received no data.
>> proxy.js:68:22 [master] pid:17250 xctest client proxy received no data.
>> proxy.js:68:22 [master] pid:17250 xctest client proxy received no data.
>> proxy.js:68:22 [master] pid:17250 xctest client proxy received no data.
>> proxy.js:68:22 [master] pid:17250 xctest client proxy received no data.
>> proxy.js:68:22 [master] pid:17250 xctest client proxy received no data.
>> xctest-client.js:309:14 [master] pid:17250 Fail to start xctest: No data received from XCTestWD.
>> xctest-client.js:322:14 [master] pid:17250 killing runnerProc pid: 19718
>> xctest-client.js:328:14 [master] pid:17250 killing iproxyProc pid: 19863
>> responseHandler.js:56:12 [master] pid:17250 Send Error Respone to Client: No data received from XCTestWD.

  InternalServerError: Internal Server Error
      at Object.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:59:17)
      at module.exports.throw (<anonymous>)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)`

macaca 版本2.2.0  macOS Mojave 10.14.6  xcode 10.3

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/929
