### ISSUE TITLE
windows10环境， uiautomatorwd@1.1.1 安装失败

### ISSUE THREAD

**Issue by maxima-ying** [alibaba/macaca#959]
试了gradle 6.0.1, 6.1和 3.2都不行。
能帮忙看一下是什么问题，怎么解决吗？

6.1的log如下：
C:\temp\104.MacacaPlayground\macaca-sample\sample-nodejs>npm i uiautomatorwd --save

> uiautomatorwd@1.1.1 install C:\temp\104.MacacaPlayground\macaca-sample\sample-nodejs\node_modules\uiautomatorwd
> node ./scripts/build.js

(node:17144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ,
> Configure project :app
WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings
,
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > org/gradle/api/file/ProjectLayout.fileProperty(Lorg/gradle/api/provider/Provider;)Lorg/gradle/api/file/RegularFileProperty; (loaded from file:/C:/Gradle/gradle-6.1/lib/gradle-core-api-6.1.jar by VisitableURLClassLoader(ant-and-gradle-loader)) called from class com.android.build.gradle.internal.scope.BuildArtifactsHolder (loaded from file:/C:/Users/JIAQIMaxima/.gradle/caches/modules-2/files-2.1/com.android.tools.build/gradle/3.2.1/1ce0d907aa7805e19f553807b9bbdc9bb9841dbf/gradle-3.2.1.jar by VisitableURLClassLoader(ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings:C:\temp\104.MacacaPlayground\macaca-sample\sample-nodejs\node_modules\uiautomatorwd\buildSrc:root-project(export)})).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

(node:17144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-router@4.3.1 requires a peer of react@>=15 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.10.0-beta.3 (node_modules\ios-deploy):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deploy@1.10.0-beta.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ uiautomatorwd@1.1.1
updated 1 package in 29.215s

**Comment by houseshi** [comment]
new version is fixed
please reinstall macaca-android
