### ISSUE TITLE
macaca是否能同时执行移动端和pc端的测试用例

### ISSUE THREAD

**Issue by ftvbftvbq** [alibaba/macaca#964]
* **Macaca Version**:

* **Macaca Doctor Logs**:

* **Operate System**:

* **Programming Language**:

macaca是否能同时执行移动端和pc端的测试用例

**Comment by xudafeng** [comment]
启动两个driver

**Comment by ftvbftvbq** [comment]
启动2个driver的话，是否需要区分端口号？另外，代码上需要做什么处理？谢谢！

**Comment by xudafeng** [comment]
可以开不同的端口号 https://testerhome.com/topics/5361
