### ISSUE TITLE
devtool debug alibaba  macaca-test-sample-master error

### ISSUE THREAD

**Issue by Archer456** [alibaba/macaca#97]
https://github.com/Jam3/devtool/issues/83

已经提问题给devtool。
希望macaca这边的也帮着看下，从情况来看 安装应该是成功的devtool。
实际脚本也可以 macaca run  或者ubuntu下 make test-android 正常运行。
但使用devtool  就是无法类似https://testerhome.com/topics/4563 此篇作者 正常调试通。

估计是devtool问题？

**Comment by xudafeng** [comment]
@Archer456 问题解决了吗？

**Comment by Archer456** [comment]
NO  win10下 或 ubuntu16.04环境下，确保devtool安装正常情况下。按照那篇文章是无法调试macaca 用例内容的。
1 希望多增加下，关于如何构建项目，项目文件结构解释，项目依赖怎么写 比如package.json等
指导。
2并希望增加下，关于用例书写框架的解释，macaca用例用到的 比如mocha框架  wdjs webdriver-client 等的解释。因为我看不同的人 比如安卓app这块 有的调wd js  有的调macaca-utils 感觉有点蒙 初学者并不知道这两者在实现上有什么区别。
3 还有最好支持下主流前端开发工具 webstorm 和 sublime text3的API语法提示功能插件、

**Comment by xudafeng** [comment]
@Archer456 不同语言的项目构建方式和运行方式不同，需要有一定的项目基础，根据选择的语言构建。另外api数量不多，提供语法提示功能意义不大

**Comment by xudafeng** [comment]
@zenzhu
