### ISSUE TITLE
Macaca ios真机会偶现调用了click但无效的情况

### ISSUE THREAD

**Issue by fb0122** [alibaba/macaca#976]
* **Macaca Version**:  2.2.0

* **Macaca Doctor Logs**:    

>> proxy.js:55:14 [master] pid:51302 Proxy: /wd/hub/session/e26d3253-1a72-4321-8ce9-082c1b07b01c/element:POST to http://127.0.0.1:8001/wd/hub/session/22ED52D9-F201-45C2-A632-1644A548C784/element:POST with body: {"using":"xpath","value":"//XCUIElementTypeButton[@name='ClickButton']"}

>> proxy.js:85:20 [master] pid:51302 Got response with status 200: {"status":0,"sessionId":"","value":{"ELEMENT":"F4671F8C-D871-4DC7-875C-684EB8052C1F","label":"ClickButton","type":"XCUIElementTypeButton"}}

>> session.js:120:14 [master] pid:51302 Send HTTP Respone to Client[2020-06-04 17:25:59]: {"status":0,"sessionId":"","value":"{\"ELEMENT\":\"F4671F8C-D871-4DC7-875C-684EB8052C1F\",\"label\":\"ClickButton\",\"type\":\"XCUIElementTypeButton\"}"}

>> responseHandler.js:11:12 [master] pid:51302 Recieve HTTP Request from Client[2020-06-04 17:25:59]: method: POST url: /wd/hub/session/e26d3253-1a72-4321-8ce9-082c1b07b01c/element/F4671F8C-D871-4DC7-875C-684EB8052C1F/click, jsonBody: {}

>> proxy.js:55:14 [master] pid:51302 Proxy: /wd/hub/session/:sessionId/accept_alert:POST to http://127.0.0.1:8001/wd/hub/session/22ED52D9-F201-45C2-A632-1644A548C784/accept_alert:POST with body: {}

>> proxy.js:85:20 [master] pid:51302 Got response with status 200: {"value":"","sessionId":":sessionId","status":27}

>> proxy.js:55:14 [master] pid:51302 Proxy: /wd/hub/session/e26d3253-1a72-4321-8ce9-082c1b07b01c/element/F4671F8C-D871-4DC7-875C-684EB8052C1F/click:POST to http://127.0.0.1:8001/wd/hub/session/22ED52D9-F201-45C2-A632-1644A548C784/element/F4671F8C-D871-4DC7-875C-684EB8052C1F/click:POST with body: {}

>> proxy.js:85:20 [master] pid:51302 Got response with status 200: {"sessionId":"","status":0,"value":""}

>> session.js:120:14 [master] pid:51302 Send HTTP Respone to Client[2020-06-04 17:26:02]: {"sessionId":"","status":0,"value":""}

* **Operate System**:
Mac OS : 10.15.1

* **Programming Language**:
Node.js

这个不是必现的，但是偶尔会出现。看日志是在已经找到元素之后调用click方法，但是没反应。请问下这个情况是怎么回事？ 或者有什么处理方法吗？ 谢谢～

**Comment by xudafeng** [comment]
@fb0122 看日志是正常的，可以从视图渲染上找原因，如果一个视图刚打开(iOS 没有 ViewDidLoad)就操作是会有失败几率的
