### ISSUE TITLE
 Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

### ISSUE THREAD

**Issue by crrrrrrrrr** [alibaba/macaca#977]
macaca-test/mobile-app-sample.test.js

>>     1) "before all" hook

>>     2) "after all" hook

>> 

>> 

>>   0 passing (10m)
  2 failing

>> 

>>   1) macaca-test/mobile-app-sample.test.js
       "before all" hook:
     Error: Timeout of 600000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

**Comment by xudafeng** [comment]
参考 https://mochajs.org/#detects-multiple-calls-to-done
