### ISSUE TITLE
安装macaca-ios报错

### ISSUE THREAD

**Issue by lhbads** [alibaba/macaca#979]
![image](https://user-images.githubusercontent.com/31372600/86561146-9427fb00-bf92-11ea-90c2-65be12fc2254.png)
![image](https://user-images.githubusercontent.com/31372600/86561580-8f177b80-bf93-11ea-9b3b-ab7d8ef82c77.png)

**Comment by xudafeng** [comment]
@lhbads macaca doctor 测试下环境问题
