### ISSUE TITLE
Document timeout configuration in macaca-wd

### ISSUE THREAD

**Issue by paradite** [alibaba/macaca#986]
Document `setImplicitWaitTimeout` method in https://github.com/macacajs/macaca-wd which can change the global wait timeout from 5 seconds (5000ms) to custom variable (useful for `waitForElementByCss`)

https://github.com/macacajs/webdriver-server/pull/52

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-electron/pull/54
