### ISSUE TITLE
npm-doctor都正常，运行macaca run mobile-app-sample.test.js 报错Cannot find test framework "mocha"

### ISSUE THREAD

**Issue by arthur-wxy** [alibaba/macaca#987]
* **Macaca Version**:
2.2.1
* **Macaca Doctor Logs**:
> sample-nodejs@1.0.0 doctor /Users/arthurw/Desktop/sample-nodejs
> macaca doctor

  macaca-doctor version: 2.0.18

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v10.15.0

  iOS checklist:

  macOS version: 10.15.7
  Xcode Command Line Tools is ready, version: 2373.
  xcodebuild version: 12.0.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:

  JAVA version is `11`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk-11.0.7.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/arthurw/Library/Android/sdk`
  Platforms is set to `/Users/arthurw/Library/Android/sdk/platforms/android-29`
  ADB tool is set to `/Users/arthurw/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 6.7

  Installed driver list:

  chrome: 1.1.1
  location: /Users/arthurw/Desktop/sample-nodejs/node_modules/macaca-chrome

  ios: 2.1.0
  location: /Users/arthurw/Desktop/sample-nodejs/node_modules/macaca-ios
* **macaca run mobile-app-sample.test.js**:
arthurw@arthur-wxys-MacBook-Pro macaca-test % macaca run -d mobile-app-sample.test.js
>> Macaca server started
/usr/local/lib/node_modules/macaca-cli/lib/run/index.js:46
      throw err;
      ^

Error: Cannot find test framework "mocha" in /Users/arthurw/Desktop/sample-nodejs/macaca-test/node_modules
    at Runner.initFramework (/usr/local/lib/node_modules/macaca-cli/lib/run/index.js:79:13)
    at co.then (/usr/local/lib/node_modules/macaca-cli/lib/run/index.js:43:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)

* **Operate System**:
Darwin arthur-wxys-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
* **Programming Language**:
python

大哥有时间帮看下

**Comment by xudafeng** [comment]
npm install 安装下依赖
