### ISSUE TITLE
iOS| socket hang up | connect ECONNREFUSED 127.0.0.1:8001

### ISSUE THREAD

**Issue by 496767099** [alibaba/macaca#989]
* **Macaca Version**:
macaca -v
  2.2.1

* **Macaca Doctor Logs**:
 macaca doctor          

  macaca-doctor version: 2.0.18
  Node.js checklist:
  node env: /usr/local/bin/node
  node version: v15.3.0
  iOS checklist:
  macOS version: 10.15.4
  Xcode Command Line Tools is ready, version: 2373.
  xcodebuild version: 12.3
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

  Android checklist:
  JAVA version is `1.8`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/admin/Library/Android/sdk`
  Platforms is set to `/Users/admin/Library/Android/sdk/platforms/android-30`
  ADB tool is set to `/Users/admin/Library/Android/sdk/platform-tools/adb`
  gradle is installed, version: 6.7

  Installed driver list:
  android: 2.2.1
  location: /usr/local/lib/node_modules/macaca-android

  chrome: 1.1.1
  location: /usr/local/lib/node_modules/macaca-chrome

  ios: 2.1.0
  location: /usr/local/lib/node_modules/macaca-ios

* **Operate System**:
macOS 10.15.4 (19E287

* **Programming Language**:
java

运行macaca-java-biz-sample,启动iPhone 11模拟器,然后在IOS Bootstrap输入test文本后8001端口挂起.试过先输入密码也一样.
![image](https://user-images.githubusercontent.com/30050783/103500310-e84e6200-4e85-11eb-89f2-5d71eceefee3.png)

运行安卓模拟器没有任何问题.

**Comment by 496767099** [comment]
>> proxy.js:85:20 [master] pid:2311 Got response with status 200: {"sessionId":null,"status":0,"value":{"sessionId":"F7E8BC76-4541-4809-867D-E2AFBDDFECD5","capabilities":{"device":"iphone","browserName":"Bootstrap","sdkVersion":"14.3","CFBundleIdentifier":"xudafe...
>> responseHandler.js:49:14 [master] pid:2311 Send HTTP Respone to Client[2021-01-04 11:55:37]: {"sessionId":"791d758c-028d-4d77-8402-c569632b3c59","status":0,"value":"{\"app\":\"/var/folders/w9/hlfkwltd18s9vxy327v5tcx00000gn/T/ios-app-bootstrap.app/\",\"reuse\":1,\"platformName\":\"ios\",\"deviceName\":\"iPhone 11\"}"}
(node:2311) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
>> responseHandler.js:11:12 [master] pid:2311 Recieve HTTP Request from Client[2021-01-04 11:55:38]: method: POST url: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/elements, jsonBody: {"using":"name","value":"Login"}
>> proxy.js:55:14 [master] pid:2311 Proxy: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/elements:POST to http://127.0.0.1:8001/wd/hub/session/F7E8BC76-4541-4809-867D-E2AFBDDFECD5/elements:POST with body: {"using":"name","value":"Login"}
>> xctest-client.js:206:16 [master] pid:2311     t =     4.94s Find the Application 'xudafeng.ios-app-bootstrap'
2021-01-04 11:55:38:048 XCTestWDUITests-Runner[2586:96164] XCTestWD-Debug-Info: 
 no element id retrieved from current query

>> xctest-client.js:206:16 [master] pid:2311 2021-01-04 11:55:38.048823+0800 XCTestWDUITests-Runner[2586:96196] XCTestWD-Debug-Info: 
 no element id retrieved from current query

>> xctest-client.js:206:16 [master] pid:2311     t =     4.95s Find the Application 'xudafeng.ios-app-bootstrap'

>> xctest-client.js:206:16 [master] pid:2311     t =     4.95s Get all elements bound by index for: Elements matching predicate '"Login" IN identifiers'

>> xctest-client.js:206:16 [master] pid:2311     t =     5.00s Find the "Login" Any

>> xctest-client.js:206:16 [master] pid:2311     t =     5.02s Find the "Login" Button

>> xctest-client.js:206:16 [master] pid:2311     t =     5.03s Find the "Login" Button

>> xctest-client.js:206:16 [master] pid:2311     t =     5.05s Find the "Login" Button

>> xctest-client.js:206:16 [master] pid:2311     t =     5.06s Find the "Login" Any

>> xctest-client.js:206:16 [master] pid:2311     t =     5.07s Find the "Login" StaticText

>> xctest-client.js:206:16 [master] pid:2311     t =     5.08s Find the "Login" StaticText

>> xctest-client.js:206:16 [master] pid:2311     t =     5.09s Find the "Login" StaticText

>> proxy.js:85:20 [master] pid:2311 Got response with status 200: {"sessionId":"","status":0,"value":[{"ELEMENT":"06F39E1A-708F-4548-B672-EED0A105D43B","label":"Login","type":"XCUIElementTypeButton"},{"label":"Login","ELEMENT":"C691E05A-73BF-4175-90F9-8F7CE9CED56...
>> session.js:120:14 [master] pid:2311 Send HTTP Respone to Client[2021-01-04 11:55:38]: {"sessionId":"","status":0,"value":"[{\"ELEMENT\":\"06F39E1A-708F-4548-B672-EED0A105D43B\",\"label\":\"Login\",\"type\":\"XCUIElementTypeButton\"},{\"label\":\"Login\",\"ELEMENT\":\"C691E05A-73BF-4175-90F9-8F7CE9CED560\",\"type\":\"XCUIElementTypeStaticText\"}]"}
>> responseHandler.js:11:12 [master] pid:2311 Recieve HTTP Request from Client[2021-01-04 11:55:38]: method: GET url: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/screenshot, jsonBody: {}
>> proxy.js:55:14 [master] pid:2311 Proxy: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/screenshot:GET to http://127.0.0.1:8001/wd/hub/session/F7E8BC76-4541-4809-867D-E2AFBDDFECD5/screenshot:GET with body: 
>> proxy.js:85:20 [master] pid:2311 Got response with status 200: {"value":"iVBORw0KGgoAAAANSUhEUgAAAzwAAAcACAIAAACaY9F8AAAAAXNSR0IArs4c6QAAAHhlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAACQAAAAAQAAAJA...
>> responseHandler.js:49:14 [master] pid:2311 Send HTTP Respone to Client[2021-01-04 11:55:38]: {"sessionId":"791d758c-028d-4d77-8402-c569632b3c59","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAAAzwAAAcACAIAAACaY9F8AAAAAXNSR0IArs4c6QAAAHhlWElmTU0AKgAAAAgABQESAAMAAAABAAEAAAEaAAUAAAABAAAASgEbAAUAAAABAAAAUgEoAAMAAAABAAIAAIdpAAQAAAABAAAAWgAAAAAAAACQAAAAAQAAAJAAAAABAAKgAgAEAAAAAQAAAzygAwAEAAAAAQAABwAAAAAAvWaJSQAAAAlwSFlzAAAWJQAAFiUBSVIk8AAAABxpRE9UAAAAAgAAAAAAAAOAAAAAKAAAA4AAAAOAAABwxowvxpwAAEAASURBVHgB7N0J2DVXQR9w1CpahSoqyiJxQ1FrBWxFtC60Koj1EZcKVRGsCNKKtaWlLVjbxwUL..."}
>> responseHandler.js:11:12 [master] pid:2311 Recieve HTTP Request from Client[2021-01-04 11:55:38]: method: POST url: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/elements, jsonBody: {"using":"name","value":"please input username"}
>> proxy.js:55:14 [master] pid:2311 Proxy: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/elements:POST to http://127.0.0.1:8001/wd/hub/session/F7E8BC76-4541-4809-867D-E2AFBDDFECD5/elements:POST with body: {"using":"name","value":"please input username"}
>> xctest-client.js:206:16 [master] pid:2311     t =     5.24s Find the Application 'xudafeng.ios-app-bootstrap'
2021-01-04 11:55:38:349 XCTestWDUITests-Runner[2586:96164] XCTestWD-Debug-Info: 
 no element id retrieved from current query

>> xctest-client.js:206:16 [master] pid:2311 2021-01-04 11:55:38.349467+0800 XCTestWDUITests-Runner[2586:96195] XCTestWD-Debug-Info: 
 no element id retrieved from current query

>> xctest-client.js:206:16 [master] pid:2311     t =     5.25s Find the Application 'xudafeng.ios-app-bootstrap'

>> xctest-client.js:206:16 [master] pid:2311     t =     5.25s Get all elements bound by index for: Elements matching predicate '"please input username" IN identifiers'

>> xctest-client.js:206:16 [master] pid:2311     t =     5.29s Find the "please input username" Any

>> xctest-client.js:206:16 [master] pid:2311     t =     5.30s Find the "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.31s Find the "please input username" TextField

>> proxy.js:85:20 [master] pid:2311 Got response with status 200: {"sessionId":"","value":[{"label":"","ELEMENT":"0B7C88ED-CE3E-4D46-B7DC-FC9BC29E0FD6","type":"XCUIElementTypeTextField"}],"status":0}
>> session.js:120:14 [master] pid:2311 Send HTTP Respone to Client[2021-01-04 11:55:38]: {"sessionId":"","value":"[{\"label\":\"\",\"ELEMENT\":\"0B7C88ED-CE3E-4D46-B7DC-FC9BC29E0FD6\",\"type\":\"XCUIElementTypeTextField\"}]","status":0}
>> responseHandler.js:11:12 [master] pid:2311 Recieve HTTP Request from Client[2021-01-04 11:55:38]: method: POST url: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/elements, jsonBody: {"using":"name","value":"please input username"}
>> proxy.js:55:14 [master] pid:2311 Proxy: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/elements:POST to http://127.0.0.1:8001/wd/hub/session/F7E8BC76-4541-4809-867D-E2AFBDDFECD5/elements:POST with body: {"using":"name","value":"please input username"}
>> xctest-client.js:206:16 [master] pid:2311     t =     5.35s Find the Application 'xudafeng.ios-app-bootstrap'

>> xctest-client.js:206:16 [master] pid:2311 2021-01-04 11:55:38:456 XCTestWDUITests-Runner[2586:96164] XCTestWD-Debug-Info: 
 no element id retrieved from current query
2021-01-04 11:55:38.456356+0800 XCTestWDUITests-Runner[2586:96203] XCTestWD-Debug-Info: 
 no element id retrieved from current query

>> xctest-client.js:206:16 [master] pid:2311     t =     5.35s Find the Application 'xudafeng.ios-app-bootstrap'

>> xctest-client.js:206:16 [master] pid:2311     t =     5.36s Get all elements bound by index for: Elements matching predicate '"please input username" IN identifiers'

>> xctest-client.js:206:16 [master] pid:2311     t =     5.40s Find the "please input username" Any

>> xctest-client.js:206:16 [master] pid:2311     t =     5.42s Find the "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.43s Find the "please input username" TextField

>> proxy.js:85:20 [master] pid:2311 Got response with status 200: {"value":[{"ELEMENT":"27A14574-AB53-4487-B7AA-D8C1C5300442","type":"XCUIElementTypeTextField","label":""}],"sessionId":"","status":0}
>> session.js:120:14 [master] pid:2311 Send HTTP Respone to Client[2021-01-04 11:55:38]: {"value":"[{\"ELEMENT\":\"27A14574-AB53-4487-B7AA-D8C1C5300442\",\"type\":\"XCUIElementTypeTextField\",\"label\":\"\"}]","sessionId":"","status":0}
>> responseHandler.js:11:12 [master] pid:2311 Recieve HTTP Request from Client[2021-01-04 11:55:38]: method: POST url: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/element/27A14574-AB53-4487-B7AA-D8C1C5300442/value, jsonBody: {"value":["test"]}
>> proxy.js:55:14 [master] pid:2311 Proxy: /wd/hub/session/791d758c-028d-4d77-8402-c569632b3c59/element/27A14574-AB53-4487-B7AA-D8C1C5300442/value:POST to http://127.0.0.1:8001/wd/hub/session/F7E8BC76-4541-4809-867D-E2AFBDDFECD5/element/27A14574-AB53-4487-B7AA-D8C1C5300442/value:POST with body: {"value":["test"]}
>> xctest-client.js:206:16 [master] pid:2311     t =     5.45s Find the "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.47s Find the "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.48s Find the "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.49s Tap "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.50s     Wait for xudafeng.ios-app-bootstrap to idle

>> xctest-client.js:206:16 [master] pid:2311     t =     5.53s     Find the "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.54s     Check for interrupting elements affecting "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.56s     Synthesize event

>> xctest-client.js:206:16 [master] pid:2311     t =     5.66s     Wait for xudafeng.ios-app-bootstrap to idle

>> xctest-client.js:206:16 [master] pid:2311     t =     5.83s Find the "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.89s Type 'test' into "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     5.89s     Wait for xudafeng.ios-app-bootstrap to idle

>> xctest-client.js:206:16 [master] pid:2311     t =     6.31s     Find the "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     6.35s     Check for interrupting elements affecting "please input username" TextField

>> xctest-client.js:206:16 [master] pid:2311     t =     6.38s     Synthesize event

>> xctest-client.js:206:16 [master] pid:2311     t =     6.48s     Wait for xudafeng.ios-app-bootstrap to idle

>> xctest-client.js:206:16 [master] pid:2311 2021-01-04 11:55:39:623 XCTestWDUITests-Runner[2586:96164] XCTestWD-Debug-Info: 
 dismiss keyboard after setValue

>> xctest-client.js:206:16 [master] pid:2311 2021-01-04 11:55:39.623179+0800 XCTestWDUITests-Runner[2586:96198] XCTestWD-Debug-Info: 
 dismiss keyboard after setValue
2021-01-04 11:55:39.623396+0800 XCTestWDUITests-Runner[2586:96164] +[XCTestDriver sharedTestDriver]: unrecognized selector sent to class 0x1076a53b8

>> xctest-client.js:206:16 [master] pid:2311 2021-01-04 11:55:39.627816+0800 XCTestWDUITests-Runner[2586:96164] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[XCTestDriver sharedTestDriver]: unrecognized selector sent to class 0x1076a53b8'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff20420af6 __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff2042f610 __CFExceptionProem + 0
        3   CoreFoundation                      0x00007fff20425036 ___forwarding___ + 1489
        4   CoreFoundation                      0x00007fff20427068 _CF_forwarding_prep_0 + 120
        5   XCTestWD                            0x00000001098f3ec7 __37+[XCTestDaemonsProxy testRunnerProxy]_block_invoke + 39
        6   libdispatch.dylib                   0x00007fff20106508 _dispatch_client_callout + 8
        7   libdispatch.dylib                   0x00007fff2010775d _dispatch_once_callout + 20

>> xctest-client.js:206:16 [master] pid:2311    8   XCTestWD                            0x00000001098f3d97 +[XCTestDaemonsProxy testRunnerProxy] + 87
        9   XCTestWD                            0x00000001099111d5 $s8XCTestWD0A19WDElementControllerC15dismissKeyboard33_B0FA4F5B8ECC4353B5375D02A7FBBAC7LLyyFZ + 69
        10  XCTestWD                            0x000000010990502f $s8XCTestWD0A19WDElementControllerC8setValue7request7Swifter12HttpResponseOAF0I7RequestC_tFZ + 4783
        11  XCTestWD                            0x0000000109903d6a $s8XCTestWD0A19WDElementControllerC6routesSayAA12RequestRouteC_7Swifter12HttpResponseOAG0iF0CctGyFZAiKcACmcfu7_AiKcfu8_ + 42
        12  XCTestWD                            0x00000001099163cd $s8XCTestWD0A19WDElementControllerC6routesSayAA12RequestRouteC_7Swifter12HttpResponseOAG0iF0CctGyFZAiKcACmcfu7_AiKcfu8_TA + 13
        13  XCTestWD                            0x00000001098fde4f $s7Swifter11HttpRequestCAA0B8ResponseOIeggr_AcEIegnr_TR + 15
        14  XCTestWD                            0x0000000109903d31 $s7Swifter11HttpRequestCAA0B8ResponseOIeggr_AcEIegnr_TRTA.16 + 17

>> xctest-client.js:206:16 [master] pid:2311    15  XCTestWD                            0x00000001098fa980 $s7Swifter11HttpRequestCAA0B8ResponseOIegnr_AcEIeggr_TR + 64
        16  XCTestWD                            0x00000001098fd021 $s7Swifter11HttpRequestCAA0B8ResponseOIegnr_AcEIeggr_TRTA + 17
        17  XCTestWD                            0x00000001098f768f $s8XCTestWD11RouteOnMainy7Swifter12HttpResponseOAC0G7RequestCcAeGcFAeGcfU_yyXEfU_ + 111
        18  XCTestWD                            0x00000001098f717c $sIg_Ieg_TR + 12
        19  XCTestWD                            0x00000001098f71e1 $sIeg_IyB_TR + 17
        20  libdispatch.dylib                   0x00007fff20106508 _dispatch_client_callout + 8
        21  libdispatch.dylib                   0x00007fff20113c9a _dispatch_async_and_wait_invoke + 109
        22  libdispatch.dylib                   0x00007fff20106508 _dispatch_client_callout + 8
        23  libdispatch.dylib                   0x00007fff20112ff7 _dispatch_main_queue_callback_4CF + 1045
        24  CoreFoundation                      0x00007fff2038edbb __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
        25  CoreFoundation                      0x00007fff2038963e __CFRunLoopRun + 2685
        26  CoreFoundation                      0x00007fff203886d6 CFRunLoopRunSpecific + 567
        27  Foundation                          0x00007fff2082f7b9 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 209
        28  Foundation                          0x00007fff2082f9cd -[NSRunLoop(NSRunLoop) run] + 76
        29  XCTestWD                            0x00000001098f8713 $s8XCTestWD0A8WDServerC11startServeryyF + 1747
        30  XCTestWDUITests                     0x000000010974dcf9 $s15XCTestWDUITests14XCTextWDRunnerC10testRunneryyF + 201
        31  XCTestWDUITests                     0x000000010974dd7b $s15XCTestWDUITests14XCTextWDRunnerC10testRunneryyFTo + 43
        32  CoreFoundation                      0x00007fff204272fc __invoking___ + 140
        33  CoreFoundation                      0x00007fff204247b6 -[NSInvocation invoke] + 303
        34  XCTest                              0x000000010757c605 __24-[XCTestCase invokeTest]_block_invoke_2 + 52
        35  XCTest                              0x000000010757c5b1 __24-[XCTestCase invokeTest]_block_invoke.239 + 320
        36  XCTest                              0x00000001075d7d67 -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 183
        37  XCTest                              0x000000010757c013 -[XCTestCase invokeTest] + 1069
        38  XCTest                              0x000000010757d8d3 __26-[XCTestCase performTest:]_block_invoke_2 + 43
        39  XCTest                              0x00000001075d7d67 -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 183
        40  XCTest                              0x000000010757d80a __26-[XCTestCase performTest:]_block_invoke.365 + 86
        41  XCTest                              0x00000001075ebd57 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 220
        42  XCTest                              0x000000010757d087 -[XCTestCase performTest:] + 695
        43  XCTest                              0x00000001075c2b83 -[XCTest runTest] + 57
        44  XCTest                              0x00000001075767b9 __27-[XCTestSuite performTest:]_block_invoke + 354
        45  XCTest                              0x0000000107575f8e __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
        46  XCTest                              0x00000001075ebd57 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 220
        47  XCTest                              0x00000001075ebc68 +[XCTContext runInContextForTestCase:block:] + 52
        48  XCTest                              0x0000000107575f45 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
        49  XCTest                              0x0000000107576277 -[XCTestSuite performTest:] + 281
        50  XCTest                              0x00000001075c2b83 -[XCTest runTest] + 57
        51  XCTest                              0x00000001075767b9 __27-[XCTestSuite performTest:]_block_invoke + 354
        52  XCTest                              0x0000000107575f8e __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
        53  XCTest                              0x00000001075ebd57 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 220
        54  XCTest                              0x00000001075ebc68 +[XCTContext runInContextForTestCase:block:] + 52
        55  XCTest                              0x0000000107575f45 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
        56  XCTest                              0x0000000107576277 -[XCTestSuite performTest:] + 281
        57  XCTest                              0x00000001075c2b83 -[XCTest runTest] + 57
        58  XCTest                              0x00000001075767b9 __27-[XCTestSuite performTest:]_block_invoke + 354
        59  XCTest                              0x0000000107575f8e __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 24
        60  XCTest                              0x00000001075ebd57 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 220
        61  XCTest                              0x00000001075ebc68 +[XCTContext runInContextForTestCase:block:] + 52
        62  XCTest                              0x0000000107575f45 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 148
        63  XCTest                              0x0000000107576277 -[XCTestSuite performTest:] + 281
        64  XCTest                              0x00000001075c2b83 -[XCTest runTest] + 57
        65  XCTest                              0x00000001075fc696 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke_2 + 148
        66  XCTest                              0x00000001075ebd57 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 220
        67  XCTest                              0x00000001075ebc68 +[XCTContext runInContextForTestCase:block:] + 52
        68  XCTest                              0x00000001075fc5fb __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 111

>> xctest-client.js:206:16 [master] pid:2311    69  XCTest                              0x00000001075fc77c __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.99 + 96
        70  XCTest                              0x0000000107591253 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 325
        71  XCTest                              0x00000001075fc3c2 -[XCTTestRunSession runTestsAndReturnError:] + 615
        72  XCTest                              0x000000010755a9ae -[XCTestDriver _runTests] + 470
        73  XCTest                              0x00000001075e7c28 _XCTestMain + 108
        74  XCTestWDUITests-Runner              0x0000000107364922 -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
        75  XCTestWDUITests-Runner              0x0000000107364909 _XCTRunnerRunTests + 0
        76  CoreFoundation                      0x00007fff2038f120 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
        77  CoreFoundation                      0x00007fff2038e534 __CFRunLoopDoBlocks + 434
        78  CoreFoundation                      0x00007fff20388f44 __CFRunLoopRun + 899
        79  CoreFoundation                      0x00007fff203886d6 CFRunLoopRunSpecific + 567
        80  GraphicsServices                    0x00007fff2bededb3 GSEventRunModal + 139
        81  UIKitCore                           0x00007fff24690e0b -[UIApplication _run] + 912
        82  UIKitCore                           0x00007fff24695cbc UIApplicationMain + 101
        83  XCTestWDUITests-Runner              0x0000000107364add main + 183
        84  libdyld.dylib                       0x00007fff202593e9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

>> proxy.js:63:22 [master] pid:2311 xctest client proxy error with: Error: socket hang up
>> helper.js:20:18 [master] pid:2311 retrying... (10 retries left)
>> proxy.js:63:22 [master] pid:2311 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:2311 retrying... (9 retries left)
>> proxy.js:63:22 [master] pid:2311 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:2311 retrying... (8 retries left)
>> proxy.js:63:22 [master] pid:2311 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
>> helper.js:20:18 [master] pid:2311 retrying... (7 retries left)
>> proxy.js:63:22 [master] pid:2311 xctest client proxy error with: Error: connect ECONNREFUSED 127.0.0.1:8001
^C

**Comment by paradite** [comment]
fixed via https://github.com/macacajs/XCTestWD/pull/195 
also, please wait for a few more retires as the process is async.
