### ISSUE TITLE
Error  mac os(10.10.15) run macaca-mobile-sample.test on xiaomi android 6.0.1  

### ISSUE THREAD

**Issue by feifei168** [alibaba/macaca#99]
feichen3deMacBook-Pro:macaca-test-sample-master feichen3$ make test-android
macaca doctor

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v4.4.7

  iOS checklist:

  Xcode is installed at: `/Library/Developer/CommandLineTools`
  Xcode Command Line Tools is ready, version: 2339.
  Command Line Tools: ios_webkit_debug_proxy is uninstalled

  Android checklist:

  JAVA version is `1.7.0_79`
  JAVA_HOME is set to `/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home`
  ANDROID_HOME is set to `/Users/feichen3/Downloads/adt-bundle-mac-x86_64-20140321/sdk`
  Platforms is set to `/Users/feichen3/Downloads/adt-bundle-mac-x86_64-20140321/sdk/platforms/android-23`
  Android tools is set to `/Users/feichen3/Downloads/adt-bundle-mac-x86_64-20140321/sdk/tools/android`

  Installed driver list:

  android: 1.0.23

platform=android macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js
>> index.js:17:12 [master] pid:1999 webdriver server start with config:
 { port: 3456,
  window: true,
  ip: '192.168.0.102',
  host: 'feichen3deMacBook-Pro.local',
  loaded_time: '2016-07-31 23:58:47' }
>> middlewares.js:17:10 [master] pid:1999 base middlewares attached
>> router.js:108:10 [master] pid:1999 router set
>> webdriver sdk launched
>> 

>> 

>>   macaca mobile sample

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"Android","platformVersion":"6.0.1","deviceName":"xiaomi","app":"/Users/feichen3/Documents/macaca/macaca-test-sample-master/app/android-app-bootstrap.zip"}}
>> session.js:47:10 [master] pid:1999 Creating session, sessionId: ea6e9c3b-fbf8-4efc-b27f-313a56312507.
>> helper.js:194:12 [master] pid:1999 Unzipping local app form /Users/feichen3/Documents/macaca/macaca-test-sample-master/app/android-app-bootstrap.zip
INSTRUMENTATION_STATUS: numtests=1

INSTRUMENTATION_STATUS: stream=
com.android.uiautomator.client.Initialize:

INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
INSTRUMENTATION_STATUS: test=testStartServer

INSTRUMENTATION_STATUS: class=com.android.uiautomator.client.Initialize
INSTRUMENTATION_STATUS: current=1

INSTRUMENTATION_STATUS_CODE: 1

uiautomator start socket server.

>> socket server ready
>> socket client ready
recive: {"cmd":"wake","args":{}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"{\"autoAcceptAlerts\":true,\"platformName\":\"Android\",\"platformVersion\":\"6.0.1\",\"deviceName\":\"xiaomi\",\"app\":\"/var/folders/53/_s88l7xd4dj5wctnrt965c5w0000gn/T/android-app-bootstrap.apk\",\"window\":true}"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/elements, jsonBody: {"using":"class name","value":"android.widget.EditText"}
recive: {"cmd":"find","args":{"strategy":"class name","selector":"android.widget.EditText","multiple":true}}

return: {"success":true,"data":[{"ELEMENT":"1"},{"ELEMENT":"2"}]}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"[{\"ELEMENT\":\"1\"},{\"ELEMENT\":\"2\"}]"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element/1/value, jsonBody: {"value":["中文+Test+12345678"]}
recive: {"cmd":"setText","args":{"elementId":"1","text":"中文+Test+12345678"}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/elements, jsonBody: {"using":"class name","value":"android.widget.EditText"}
recive: {"cmd":"find","args":{"strategy":"class name","selector":"android.widget.EditText","multiple":true}}

return: {"success":true,"data":[{"ELEMENT":"3"},{"ELEMENT":"4"}]}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"[{\"ELEMENT\":\"3\"},{\"ELEMENT\":\"4\"}]"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element/4/value, jsonBody: {"value":["111111"]}
recive: {"cmd":"setText","args":{"elementId":"4","text":"111111"}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/elements, jsonBody: {"using":"name","value":"Login"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"Login","multiple":true}}

return: {"success":true,"data":[{"ELEMENT":"5"}]}
>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"[{\"ELEMENT\":\"5\"}]"}

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element/5/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"5"}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"true"}
>> 
>>     ✓ #1 should login success (50161ms)

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/source, jsonBody: {}
recive: {"cmd":"getSource","args":{}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"\"/system/bin/sh: cat: /data/local/tmp/macaca-dump.xml: No such file or directory\""}
>> /system/bin/sh: cat: /data/local/tmp/macaca-dump.xml: No such file or directory

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/screenshot, jsonBody: {}
>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzs3XdUVNf+NvBnCgxt6CAdVBTsWKLYULFiwd6jMSY3GnOT+zM95qYZo1FjTIxJzDWJLfYSBY1iI1aIBQU7KqIigjQpQ51h3j9YnJdxaMIBHHw+a7kW7Dmz96bKeWbv75YA0IKIiIiIiIiIyIBJG3oCRERERERERES1xYCDiIiIiIiIiAweAw4iIiIiIiIiMngMOIiIiIiIiIjI4DHgICIiIiIiIiKDx4CDiIiIiIiIiAweAw4iIiIiIiIiMngMOIiIiIiIiIjI4DHgICIiIiIiIiKDx4CDiIiIiIiIiAweAw4iIiIiIiIiMnjyhp4A..."}
>> 
>>     ✓ #2 should display home (2551ms)

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element, jsonBody: {"using":"name","value":"HOME"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"HOME","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"6"}}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"{\"ELEMENT\":\"6\"}"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element/6/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"6"}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element, jsonBody: {"using":"name","value":"list"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"list","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"7"}}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"{\"ELEMENT\":\"7\"}"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element/7/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"7"}}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"true"}
return: {"success":true,"data":true}

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element/200/swipe, jsonBody: {"startX":200,"startY":400,"endX":200,"endY":100,"duration":500}
recive: {"cmd":"swipe","args":{"startX":200,"startY":400,"endX":200,"endY":100,"duration":500}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/back, jsonBody: {}
>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":null}
>> 
>>     ✓ #3 should scroll tableview (14873ms)

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element, jsonBody: {"using":"name","value":"Webview"}
recive: {"cmd":"find","args":{"strategy":"name","selector":"Webview","multiple":false}}

ignored selector

return: {"success":true,"data":{"ELEMENT":"8"}}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"{\"ELEMENT\":\"8\"}"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/element/8/click, jsonBody: {}
recive: {"cmd":"click","args":{"elementId":"8"}}

return: {"success":true,"data":true}

>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"true"}
>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/screenshot, jsonBody: {}
>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0,"value":"\"iVBORw0KGgoAAAANSUhEUgAABDgAAAeACAYAAAArYecKAAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzs3XdUVNf3NvBnCgxt6CAdFBRsiCUKFlSs2HuNJZpEo9HERGOiMRq/xhpjYjQxMUYsUWOLscSuMTZiQcGOiqiAdKQMUmaY9w9e7o9x6Awg5vms5VrMmXvP3TPAyNn3nH1EANQgIiIiIiIiIqrFxDUdABERERERERFRZTHBQURERERERES1HhMcRERERERERFTrMcFBRERERERERLUeExxEREREREREVOsxwUFEREREREREtR4THERERERERERU6zHBQURERERERES1HhMcRERERERERFTrMcFBRERERERERLUeExxEREREREREVOtJ..."}
>> 
>>     ✓ #4 should display webview (5868ms)

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/contexts, jsonBody: {}
>> chromedriver bin path: /usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-chromedriver@1.0.15/exec/chromedriver
>> Kill all running chromedriver process by: ps -ef | grep chromedriver | grep -v grep | grep -e '--port=9515' | awk '{ print $2 }' | xargs kill -15
>> kill all chromedriver process success!
>> Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 9515
Only local connections are allowed.

>> chromedriver starting success.
>> proxy.js:52:14 [master] pid:1999 Proxy: /status:GET to http://localhost:9515/wd/hub/status:GET with body: 
>> proxy.js:58:16 [master] pid:1999 Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.10.5\"}}}"
>> proxy.js:52:14 [master] pid:1999 Proxy: /session:POST to http://localhost:9515/wd/hub/session:POST with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.github.android_app_bootstrap","androidUseRunningApp":true,"androidDeviceSerial":"9bc23878"}}}
>> proxy.js:58:16 [master] pid:1999 Got response with status 200: {"sessionId":"7b929322f11178157d29db3ca4eb47b3","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=M...
>> chromedriver ready with: {"sessionId":null,"status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)"}}
>> proxy.js:52:14 [master] pid:1999 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/7b929322f11178157d29db3ca4eb47b3/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:1999 Got response with status 200: {"sessionId":"7b929322f11178157d29db3ca4eb47b3","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X...
>> responseHandler.js:50:12 [master] pid:1999 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
>> responseHandler.js:56:14 [master] pid:1999 NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-android@1.0.23/lib/helper.js:68:11)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-android@1.0.23/lib/macaca-android.js:209:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.co@4.6.0/index.js:65:19)
    at process._tickCallback (node.js:369:9)
>> responseHandler.js:72:14 [master] pid:1999 Send Bad HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)"}}
>> 
>>     1) #5 should go into webview

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/contexts, jsonBody: {}
>> proxy.js:52:14 [master] pid:1999 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/7b929322f11178157d29db3ca4eb47b3/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:1999 Got response with status 200: {"sessionId":"7b929322f11178157d29db3ca4eb47b3","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X...
>> responseHandler.js:50:12 [master] pid:1999 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
>> responseHandler.js:56:14 [master] pid:1999 NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-android@1.0.23/lib/helper.js:68:11)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-android@1.0.23/lib/macaca-android.js:209:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.co@4.6.0/index.js:65:19)
    at process._tickCallback (node.js:369:9)
>> responseHandler.js:72:14 [master] pid:1999 Send Bad HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)"}}
>> 
>>     2) #6 should go into test

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/contexts, jsonBody: {}
>> proxy.js:52:14 [master] pid:1999 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/7b929322f11178157d29db3ca4eb47b3/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:1999 Got response with status 200: {"sessionId":"7b929322f11178157d29db3ca4eb47b3","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X...
>> responseHandler.js:50:12 [master] pid:1999 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
>> responseHandler.js:56:14 [master] pid:1999 NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-android@1.0.23/lib/helper.js:68:11)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-android@1.0.23/lib/macaca-android.js:209:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.co@4.6.0/index.js:65:19)
    at process._tickCallback (node.js:369:9)
>> responseHandler.js:72:14 [master] pid:1999 Send Bad HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)"}}
>> 
>>     3) #7 should works with web

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: GET url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507/contexts, jsonBody: {}
>> proxy.js:52:14 [master] pid:1999 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/7b929322f11178157d29db3ca4eb47b3/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:1999 Got response with status 200: {"sessionId":"7b929322f11178157d29db3ca4eb47b3","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X...
>> responseHandler.js:50:12 [master] pid:1999 Send Error Respone to Client: NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
>> responseHandler.js:56:14 [master] pid:1999 NoSuchDriver: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-android@1.0.23/lib/helper.js:68:11)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/.macaca-android_npminstall/node_modules/.macaca-android@1.0.23/lib/macaca-android.js:209:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/node_modules/.co@4.6.0/index.js:65:19)
    at process._tickCallback (node.js:369:9)
>> responseHandler.js:72:14 [master] pid:1999 Send Bad HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)"}}
>> 
>>     4) #8 should logout success

>> responseHandler.js:11:12 [master] pid:1999 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/ea6e9c3b-fbf8-4efc-b27f-313a56312507, jsonBody: {}
>> macaca-android.js:60:14 [master] pid:1999 Error: Command failed: /bin/sh -c /Users/feichen3/Downloads/adt-bundle-mac-x86_64-20140321/sdk/platform-tools/adb emu kill
error: no emulator detected

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)
>> session.js:80:12 [master] pid:1999 Delete session, sessionId: ea6e9c3b-fbf8-4efc-b27f-313a56312507
>> responseHandler.js:43:14 [master] pid:1999 Send HTTP Respone to Client: {"sessionId":"ea6e9c3b-fbf8-4efc-b27f-313a56312507","status":0}
>> 

>> 

>>   4 passing (3m)

>>   4 failing

>> 

>>   1) macaca mobile sample #5 should go into webview:
     Error: [contexts()] Error response status: 6,  Selenium error: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:75:19
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

>>   2) macaca mobile sample #6 should go into test:
     Error: [contexts()] Error response status: 6,  Selenium error: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:75:19
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  3) macaca mobile sample #7 should works with web:
     Error: [contexts()] Error response status: 6,  Selenium error: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:75:19
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

  4) macaca mobile sample #8 should logout success:
     Error: [contexts()] Error response status: 6,  Selenium error: no such session
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64)
      at exports.newError (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/utils.js:139:13)
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/callbacks.js:75:19
      at node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/webdriver.js:179:5
      at Request._callback (node_modules/webdriver-client/node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/webdriver-client/node_modules/macaca-wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

**Comment by xudafeng** [comment]
#91

**Comment by feifei168** [comment]
那个＃91的bug我之前就看到了，后来换了仨手机都不行，报同样的error，三星A9000，nexus6

**Comment by feifei168** [comment]
刚换了个华为G621，android 4.4.4，很遗憾还是不行，报同样的error

**Comment by xudafeng** [comment]
@feifei168 Android5，模拟器测试一下？是否是环境问题。

**Comment by feifei168** [comment]
模拟器是可以的～

**Comment by xudafeng** [comment]
@feifei168 🆗

**Comment by xudafeng** [comment]
https://github.com/alibaba/macaca/issues/91
