### ISSUE TITLE
xcode 12.5  ios 14.7.1 下 app-inspector 加载不出页面了

### ISSUE THREAD

**Issue by FuChen1649** [alibaba/macaca#997]
* **Macaca Version**:
Macaca Version :2.2.2
* **Macaca Doctor Logs**:
 macaca-doctor version: 2.0.18

  Node.js checklist:

  node env: /usr/local/bin/node
  node version: v15.8.0

  iOS checklist:

  macOS version: 11.5.2
  Xcode Command Line Tools is ready, version: 2384.
  xcodebuild version: 12.5.1
  iproxy[usbmuxd] is installed at: `/usr/local/bin/iproxy`
  ios_webkit_debug_proxy is installed at: `/usr/local/bin/ios_webkit_debug_proxy`

* **Operate System**:
macOS  BigSur 11.5.2
* **Programming Language**:

app-inspector 命令启动后.会有这么一个错误提示
<img width="800" alt="Screen Shot 2021-08-24 at 2 04 54 PM" src="https://user-images.githubusercontent.com/39113750/130565825-736f8f46-c4d3-4a08-826c-87683895e342.png">

页面一直会停留在等待状态
<img width="1128" alt="Screen Shot 2021-08-24 at 2 17 23 PM" src="https://user-images.githubusercontent.com/39113750/130565960-4f346d70-d036-4d14-a851-136b281f5262.png">

这个问题只在xcode12.5 有 麻烦看看. ios 一旦升到最新版本,12.5以下的版本就不支持了

**Comment by xudafeng** [comment]
https://github.com/macacajs/XCTestWD/pull/193#issuecomment-919743085
